var dicctr_85 = {
"стойко" : "persevere",
"стойло" : "stall",
"стокгольм" : "Stockholm",
"стократный" : "hundredfold",
"стол" : "table, board fare, meal, office bureau, hist. throne",
"столб" : "post pole, column, pillar",
"столбенеть" : "petrify",
"столбец" : "column",
"столбик" : "column",
"столбняк" : "stupor, tetanus",
"столбовая дорога" : "highway",
"столетие" : "century, centenary",
"столик" : "dim. #of стол, famil. table",
"столица" : "capital",
"столичный" : "metropolitan",
"столкновение" : "collision clash",
"столкнуть" : "push",
"столовая" : "dining room, restaurant",
"столовый" : "table, dinner",
"столп" : "pillar, column",
"столпиться" : "crowd throng, mob, swarm",
"столь" : "so",
"столько" : "so much so many",
"столько же" : "as much #or many",
"столяр" : "joiner, cabinetmaker",
"столярный" : "joiner's",
"стон" : "groan moan",
"стонать" : "groan moan",
"стоп" : "stop!",
"стопа" : "ream",
"сторож" : "caretaker, watcher",
"сторона" : "side",
"сторониться" : "make way step aside, avoid shun; See also: сторонись{!}",
"сторонник" : "adherent follower supporter, partisan",
"сточный" : "waste... soil...",
"стоялый" : "stale",
"стоянка" : "stop, stand station quarters pl., parking place #or lot, nav. anchorage",
"стоять" : "stand, be, stop, lodge quarter, stand up  defend, insist, стой! stop!, famil. wait!",
"стоячий" : "standing, stagnant, stand-up, standard",
"стоящий" : "rewarding, worth, worthwhile",
"стр" : "abbr.: страница page p.",
"страдать" : "suffer",
"страдающий" : "suffering",
"страна" : "southland",
"страница" : "page",
"странный" : "curious, oddish, queer, rummy, strange, unco",
"странствие" : "wandering travel",
"странствование" : "itineracy, itinerancy, roam",
"странствующий" : "errant, itinerant, peripatetic, wayfaring",
"страстный" : "impassioned, passional, vehement",
"стратег" : "strategist",
"стратегический" : "strategic, strategical",
"стратегия" : "strategy",
"стратосфера" : "stratosphere",
"страус" : "ostrich",
"страх" : "awe, dismay, dread, fear, funk",
"страхование" : "insurance",
"страховать" : "indemnify, insure, underwrote",
"страховой" : "insurance...",
"страшить" : "frighten",
"страшный" : "terrible frightful dreadful, Last, famil. awful, мне страшно I'm afraid I fear",
"стрекоза" : "dragonfly",
"стрела" : "arrow, bot. shaft",
"стрелец" : "sagittarius",
"стрелка" : "hand pointer indicator, needle, arrow, clock, tongue, Brt. point",
"стрелковый" : "shooting..., rifles pl.",
"стреловидный" : "sagittal",
"стрелок" : "marksman shot, milit. rifleman",
"стрелочник" : "switchman Brt. pointsman",
"стрельба" : "shooting fire",
"стрелять" : "shoot fire, impers. feel acute pains pl.",
"стреляться" : "impf. duel",
"стремглав" : "headlong headfirst",
"стремительность" : "dash, impetuosity",
"стремительный" : "impetuous violent rash",
"стремиться" : "aspire  strive, rush",
"стремление" : "aspiration striving urge, tendency",
"стремя" : "stirrup",
"стремящийся" : "aspiring, eager, intent",
"стрептококк" : "streptococcus",
"стрептомицин" : "streptomycin",
"стриж" : "sand martin",
"стриженый" : "bobbed short-haired, shorn, trimmed",
"стрижка" : "haircut, shearing, trimming",
"стриптиз" : "striptease",
"стрихнин" : "strychnine",
"стричь" : "cut, shear, clip trim",
"стричься" : "have one's hair cut",
"строгать" : "plane",
"строгий" : "severe, strict, austere, stern",
"строгость" : "severity austerity strictness",
"строевой" : "fighting front",
"строевой лес" : "timber",
"строение" : "construction building, structure",
"строитель" : "builder constructor",
"строительный" : "building...",
"строительство" : "construction",
"строить" : "построить build  construct, make scheme, play fig., выстроить milit. draw up form",
"строиться" : "be built, build a house, milit. fall in",
"строй" : "order array, line, system order regime, mus. tune",
"стройка" : "construction",
"стройность" : "harmony, slenderness",
"стройный" : "slender slim, harmonious, symmetrical well-shaped well-disposed",
"строка" : "line",
"стронций" : "strontium",
"стропило" : "rafter",
"строптивый" : "obstinate refractory",
"строфа" : "stanza",
"строчить" : "stitch sew, famil. scribble write, crackle",
"строчка" : "line, seam",
"стружка" : "shaving",
"струиться" : "stream flow run, purl",
"струйка" : "dim. #of струя",
"структура" : "structure",
"структурный" : "structural",
"струна" : "string",
"струнный" : "string",
"струп" : "scab",
"струсить" : "be afraid",
"стручковый" : "s. бобовый",
"стручок" : "pod husk",
"струя" : "stream, jet, current, flood",
"стряпать" : "cook",
"стряхивать" : "shake off",
"стряхнуть" : "shake off",
"студенистый" : "gelatinous",
"студент" : "student undergraduate",
"студентка" : "student undergraduate",
"студенческий" : "students'",
"студеный" : "cold",
"студень" : "jellied meat",
"студия" : "studio atelier",
"стук" : "knock, rattle clatter noise",
"стукнуть" : "s. стучать",
"стул" : "chair, seat, med. stool",
"ступа" : "mortar",
"ступать" : "step tread go",
"ступенчатый" : "graded",
"ступень" : "step, stage grade",
"ступенька" : "step, rung",
"ступить" : "step tread go",
"ступица" : "nave",
"ступка" : "mortar",
"ступня" : "foot, sole",
"стучать" : "knock, rap tap, throb, chatter, clatter rattle, стучат there's a knock at the door, стукнуть s. исполниться",
"стыд" : "shame",
"стыдить" : "shame make ashamed",
"стыдиться" : "be ashamed",
"стыдливый" : "shy bashful",
"стыдный" : "shameful, стыдно! shame!, мне стыдно I am ashamed",
"стык" : "joint juncture",
"стыть" : "cool",
"стычка" : "skirmish",
"стюардесса" : "stewardess",
"стягивать" : "constrict, subtend",
"суббота" : "saturday",
"субсидия" : "grant, subsidy",
"сувенир" : "souvenir",
"суверенитет" : "sovereignty",
"сугубый" : "especial exceptional",
"суд" : "judgment, court, tribunal, trial, justice; See also: полевой суд",
"суд линча" : "lynch law",
"суд присяжных" : "jury",
"судак" : "pike perch",
"сударыня" : "madam",
"сударь" : "sir",
"судебный" : "judicial legal, law..., court",
"судейский" : "judicial, referee's",
"судить" : "посудить judge fig., pf. try judge, destine; See also: судя по",
"судиться" : "be at law",
"судно" : "nav. ship vessel, vessel",
"судомойка" : "scullery #or kitchen maid",
"судорога" : "cramp spasm",
"судороги" : "convulsion",
"судорожный" : "convulsive",
"судостроение" : "shipbuilding",
"судостроительный" : "shipbuilding..., ship",
"судоходный" : "navigable",
"судоходство" : "navigation",
"судьба" : "fate",
"судья" : "judge, arbitrator referee umpire",
"судя по" : "judging by",
"суеверие" : "superstition",
"суеверный" : "superstitious",
"суета" : "vanity, fuss",
"суетиться" : "fuss",
"суетливый" : "fussy",
"суждение" : "judgment",
"сужение" : "narrowing, med. constriction",
"суживать" : "narrow",
"сузить" : "narrow",
"сук" : "bough branch, knot",
"сука" : "bitch",
"сукин" : "of a bitch",
"сукно" : "cloth",
"суконный" : "cloth...",
"сулема" : "sublimate",
"сулить" : "promise",
"султан" : "sultan, plume",
"султанат" : "sultanate",
"сульфат" : "sulfate",
"сума" : "scrip",
"сумасброд" : "madman, crank",
"сумасбродный" : "crazy cranky foolish",
"сумасбродство" : "folly madness",
"сумасшедший" : "mad insane, su. madman, lunatic",
"сумасшествие" : "madness insanity",
"суматоха" : "turmoil fuss",
"сумах" : "sumac",
"сумбур" : "s. путаница",
"сумеречный" : "crepuscular, dusky",
"сумерки" : "dusk twilight",
"суметь" : "can, know how",
"сумка" : "bag, pouch, satchel, wallet",
"сумма" : "sum  amount",
"суммарный" : "summary",
"суммирование" : "summation",
"суммировать" : "pf. sum up",
"сумочка" : "handbag",
"сумрак" : "twilight dusk, gloom",
"сумрачный" : "gloomy",
"сумчатый" : "marsupial",
"сундук" : "trunk chest",
"сунуть" : "put, famil. slip give, poke",
"суп" : "soup",
"суповой" : "soup",
"супруг" : "husband",
"супруга" : "wife",
"супружеский" : "matrimonial conjugal, married",
"супружество" : "matrimony wedlock",
"сургуч" : "sealing wax",
"суровость" : "severity",
"суровый" : "harsh rough, severe austere, stern, rigorous",
"сурок" : "marmot, woodchuck",
"суррогат" : "substitute",
"сурьма" : "antimony",
"суслик" : "gopher, suslik",
"сустав" : "joint",
"сутана" : "soutane",
"сутенер" : "ponce",
"сутки" : "24 hours day; See also: круглые сутки",
"сутолока" : "turmoil",
"суточный" : "day's daily 24 hours', su. daily allowance",
"сутулить" : "hunch",
"сутулость" : "slouch, stoop",
"сутулый" : "round-shouldered",
"суть" : "essence core main point, по сути at bottom",
"суфле" : "souffle",
"суфлер" : "prompter",
"суфлировать" : "prompt"
};
