var dicctr_20 = {
"долговой" : "долговое обязательство",
"долговязый" : "gangling, lanky, lathy",
"долгосрочный" : "longtime",
"долгота" : "longitude",
"долевой" : "lobar",
"должен" : "have to, must, ought",
"должник" : "debtor",
"должно" : "(cf. должно, must, owe",
"должно быть" : "probably apparently",
"должно1" : "one must #or ought to, proper",
"должно2" : "probably apparently",
"должностной" : "official",
"должность" : "post, office",
"должны" : "must, owe",
"должный" : "due  proper",
"должным образом" : "duly",
"доливать" : "fill  add",
"долина" : "valley",
"долить" : "fill  add",
"доллар" : "dollar",
"доложить" : "report, announce",
"долой" : "famil. off down, ~ ... ! down #or off with ...!; See also: с глаз долой{!}",
"долото" : "chisel",
"дольше" : "longer",
"доля" : "lot fate, grain  spark, в восьмую долю листа, octavo  in 8vo",
"дом" : "house, home, family, household, не все дома a bit off  nutty; See also: выйти из дому, на дом, на дому, дома, как дома",
"дома" : "at home",
"домашнее задание" : "homework",
"домашний" : "home... house..., private, domestic, su. folks",
"домашний обиход" : "household",
"домашний стол" : "plain fare",
"домашняя птица" : "poultry",
"доменная печь" : "= домна",
"домик" : "dim. #of дом",
"доминион" : "dominion",
"доминировать" : "dominate",
"домино" : "domino",
"домна" : "blast furnace",
"домовитый" : "thrifty careful, notable",
"домовладелец" : "house owner",
"домовой" : "bogey, bogy, brownie, goblin, hobgoblin",
"домовый" : "house...",
"домогаться" : "strive for solicit",
"домой" : "home",
"доморощенный" : "homebred",
"домосед" : "stay-at-home",
"домоуправление" : "house management",
"домочадцы" : "folks, inmate",
"домработница" : "housemaid",
"домысел" : "conjecture",
"дон" : "Don",
"донбасс" : "mining Donets Basin",
"донесение" : "report",
"донести" : "s. доносить",
"донкихотский" : "quixotic",
"доносчик" : "sneak, sneaker, snitch, squeaker, whistler",
"доныне" : "to this day till now",
"донять" : "press exhaust",
"допивать" : "drink up",
"допинг" : "dope",
"допить" : "drink up",
"доплата" : "additional payment extra charge",
"доплатить" : "pay in addition",
"доплачивать" : "pay in addition",
"доподлинный" : "true real",
"дополнение" : "addition, supplement, gr. object",
"дополнителный" : "complementary",
"дополнительное" : "connotation",
"дополнительные выборы" : "by-election",
"дополнительный" : "additional supplementary, extra, a. in addition, more",
"дополнить" : "add supply complete fill up, enlarge",
"дополнять" : "add supply complete fill up, enlarge",
"допотопный" : "antediluvian",
"допрашивать" : "jur. interrogate examine, impf. question",
"допрос" : "jur. interrogation examination, famil. questioning",
"допросить" : "jur. interrogate examine, impf. question",
"допуск" : "access admittance",
"допускать" : "admit  concede, allow, tolerate, suppose, make",
"допустимый" : "admissible permissible",
"допустить" : "admit  concede, allow, tolerate, suppose, make",
"допущение" : "admission",
"допытаться" : "famil. find out",
"допытываться" : "famil. find out",
"дореволюционный" : "pre-revolutionary before the revolution",
"дорога" : "road way, passage, trip journey, большая дорога highroad, железная дорога railroad Brt. railway, дорогой #or в дороге on the way, туда ему и дорога famil. that serves him right, a. путь",
"дороговизна" : "dearness high price",
"дорогой" : "dear  expensive",
"дородный" : "stout burly",
"дорожать" : "become dearer rise in price",
"дорожить" : "esteem  value",
"дорожка" : "path; See also: беговая дорожка, летная дорожка",
"дорожный" : "road..., traveling",
"досада" : "vexation, annoyance fret, famil. какая досада! how annoying! what a pity!",
"досадить" : "s. досаждать",
"досадливый" : "fretful peevish",
"досадный" : "annoying vexatious, deplorable, досадно it is annoying",
"досадовать" : "feel #or be annoyed vexed",
"досаждать" : "vex annoy",
"доска" : "board plank, blackboard, plate; See also: грифельная доска, от доски до доски, на одну доску",
"доскональный" : "thorough",
"дословный" : "literal verbal",
"досматривать" : "see up to #or to the end, watch look after, недосмотреть overlook",
"досмотр" : "supervision, examination",
"досмотреть" : "see up to #or to the end, watch look after, недосмотреть overlook",
"доспехи" : "armor, outfit",
"досрочный" : "preschedule",
"доставать" : "take, get, procure, touch, reach, famil. suffice have enough, -ся fall to a pers.'s share, be cost, famil. catch it",
"доставить" : "s. доставлять",
"доставка" : "delivery, conveyance, с доставкой carriage paid, free to the door",
"доставлять" : "deliver hand, bring, fig. procure cause give",
"достаток" : "prosperity fortune, famil. sufficiency",
"достаточно" : "considerably, enough sufficient, suffice",
"достаточный" : "sufficient",
"достать" : "take, get, procure, touch, reach, famil. suffice have enough, -ся fall to a pers.'s share, be cost, famil. catch it",
"достигать" : "reach arrive at attain, amount #or run up",
"достигнуть" : "reach arrive at attain, amount #or run up",
"достижение" : "attainment, achievement",
"достижимый" : "attainable",
"достичь" : "reach arrive at attain, amount #or run up",
"достоверный" : "authentic reliable, positive",
"достоинство" : "dignity, merit advantage, worth value",
"достойный" : "worthy, well-deserved",
"достопамятный" : "memorable notable",
"достопримечательность" : "sight",
"достопримечательный" : "remarkable noteworthy",
"достояние" : "property  fortune",
"доступ" : "access",
"доступный" : "accessible, approachable affable, comprehensible, susceptible, moderate",
"досуг" : "leisure; See also: на досуге",
"досуха" : "dry",
"досыта" : "one's fill",
"досягаемость" : "reach",
"дот" : "pillbox",
"дотла" : "completely utterly, to the ground",
"дотрагиваться" : "touch",
"дотронуться" : "touch",
"дохлый" : "dead",
"дохлятина" : "carrion",
"дохнуть" : "die, popul. croak kick off",
"доход" : "income revenue, proceeds pl.",
"доходить" : "go #or come  arrive  reach, hist. come down to, rise run up to",
"доходить до крайности" : "go #or run to extremes",
"доходный" : "profitable",
"доцент" : "lecturer instructor",
"дочерний" : "daughter",
"дочиста" : "clean, famil. completely",
"дочитать" : "finish #or read up to",
"дочитывать" : "finish #or read up to",
"дочка" : "daughter",
"дочь" : "daughter",
"дошкольный" : "preschool",
"дощатый" : "of boards plank...",
"дощечка" : "dim. #of доска",
"доярка" : "milkmaid",
"драга" : "dredge",
"драгоценности" : "jewelry",
"драгоценность" : "jewel gem, precious thing #or possession",
"драгоценный" : "precious  costly valuable",
"драгун" : "dragoon",
"дразнить" : "подразнить tease banter, nickname, раздразнить excite",
"драка" : "scuffle fight",
"дракон" : "dragon",
"драма" : "drama",
"драматический" : "dramatic",
"драматург" : "playwright dramatist",
"драматургия" : "dramaturgy",
"драпировать" : "drape",
"драповый" : "cloth",
"драть" : "pull, tweak, cf. выдирать & раздирать",
"драться" : "scuffle fight struggle",
"драхма" : "dram",
"драчливый" : "pugnacious",
"дребедень" : "trash",
"дребезг" : "clash, cf. вдребезги",
"дребезжать" : "rattle",
"древесина" : "wood substance #or material",
"древесный" : "tree..., wood",
"древесный спирт" : "methyl alcohol",
"древесный уголь" : "charcoal",
"древко" : "flagpole",
"древнееврейский" : "hebraic",
"древний" : "ancient  antique, old",
"древность" : "antiquity",
"древовидный" : "dendriform, dendritic, dendroid",
"дрейф" : "drift",
"дрейфовать" : "drift",
"дрек" : "grapnel",
"дрема" : "ragged robin, sandman",
"дремать" : "doze  slumber",
"дремота" : "drowsiness, slumber doze",
"дремотный" : "dozy",
"дремучий" : "dense",
"дремучий лес" : "primeval forest",
"дрессировать" : "train",
"дробинка" : "pellet",
"дробить" : "break to pieces crush, dismember divide #or split up, famil. drum",
"дробление" : "pounding",
"дробный" : "fractional, rolling, drumming",
"дробь" : "coll. shot, roll, math. fraction, decimal",
"дробящий" : "brisant",
"дрова" : "wood",
"дровни" : "peasant's sled",
"дровосек" : "lumberman Brt. woodcutter",
"дроги" : "dray",
"дрогнуть" : "продрогнуть shiver #or shake  chill, pf. start, waver falter, shrink flinch",
"дрожание" : "fremitus, quake",
"дрожать" : "tremble shake shiver, flicker glimmer, dread, be anxious, guard save",
"дрожащий" : "quaking, shivery, tremulant, tremulous",
"дрожжевой" : "yeast",
"дрожжи" : "yeast barm",
"дрожки" : "droshky",
"дрожь" : "trembling shiver, vibration, ripples pl.",
"дрозд" : "thrush",
"дрок" : "bot. broom",
"дроссель" : "throttle",
"дротик" : "dart javelin",
"дрофа" : "zo. bustard",
"друг" : "cully",
"друг друга" : "each other",
"друг за другом" : "one after another",
"друг с другом" : "with each other",
"друг1" : "friend, dear",
"другой" : "other different, else next second, и тот и другой both, на другой день the next day",
"дружба" : "friendship",
"дружелюбие" : "amity",
"дружелюбный" : "amicable friendly",
"дружеский" : "friendly",
"дружественный" : "friendly",
"дружина" : "bodyguard retinue, militia, troop brigade",
"дружить" : "be friends be on friendly terms",
"дружище" : "old chap #or boy",
"дружка" : "famil. = друг2, best man",
"дружный" : "friendly on friendly terms, harmonious concurrent unanimous, milit. vigorous, a. hand in hand together, at once",
"дряблый" : "limp flabby",
"дрязги" : "squabbles",
"дрянной" : "wretched mean trashy",
"дрянь" : "rubbish trash, popul. rotten lousy",
"дряхлый" : "decrepit, famil. dilapidated",
"дуб" : "oak",
"дубильный" : "tan...",
"дубильня" : "tannery",
"дубина" : "club cudgel, popul. boor dolt",
"дубинка" : "billy, bludgeon, shillelagh, truncheon",
"дубить" : "tan",
"дублер" : "thea. understudy double",
"дубликат" : "doublet",
"дубоватый" : "dull",
"дубовый" : "oak, fig. dull",
"дубрава" : "wood forest",
"дуга" : "arc, bow"
};
