var dicctr_56 = {
"ошеломлять" : "stun stupefy",
"ошибаться" : "be mistaken make a mistake  err, miss",
"ошибиться" : "be mistaken make a mistake  err, miss",
"ошибка" : "mistake  error fault",
"ошибочный" : "erroneous mistaken",
"ошпаривать" : "scald",
"ошпарить" : "scald",
"оштрафовать" : "fine",
"оштукатурить" : "plaster",
"ощетиниться" : "bristle up",
"ощупать" : "feel touch",
"ощупывать" : "feel touch",
"ощупь" : "на ощупь",
"ощущать" : "sensate",
"пава" : "peahen",
"павильон" : "pavilion",
"павлин" : "peacock, peafowl",
"павший" : "fallen",
"пагода" : "pagoda",
"пагубный" : "calamitous, maleficent, pernicious",
"падаль" : "carrion",
"паданец" : "windfall",
"падать" : "fall, tumble",
"падать ниц" : "prostrate o.s.",
"падеж1" : "gr. case",
"падеж2" : "plague rinderpest",
"падение" : "fall, downfall overthrow, commerc. slump",
"падкий" : "greedy  mad",
"падучая" : "epilepsy",
"падчерица" : "stepdaughter",
"паек" : "ration",
"паз" : "groove, mortise",
"пазуха" : "bosom, cavity",
"пай" : "share",
"пайщик" : "shareholder",
"пакет" : "parcel package packet, dispatch, paper bag",
"пакистан" : "pakistan",
"пакля" : "tow oakum",
"паковать" : "pack",
"пакость" : "filth smut dirt",
"пакт" : "pact treaty",
"палата" : "chamber, parl. house, board, ward; See also: оружейная палата",
"палатка" : "tent, booth",
"палач" : "hangman executioner",
"палестина" : "Palestine",
"палец" : "finger, toe, смотреть сквозь пальцы wink, знать как свои пять пальцев have at one's fingertips",
"палисадник" : "front garden",
"палитра" : "palette",
"палить" : "спалить burn scorch, опалить singe, выпалить fire shoot",
"палка" : "stick, cane, club, из-под палки famil. under #or in constraint",
"палладий" : "palladium",
"паломник" : "pilgrim",
"паломничество" : "pilgrimage",
"палочка" : "stick, mus. baton, wand, med. bacillus",
"палуба" : "deck",
"пальба" : "firing fire",
"пальма" : "palm",
"пальто" : "coat",
"пальцевидный" : "digital, digitate",
"памфлет" : "pamphlet",
"памятник" : "monument, memorial",
"памятный" : "memorable, unforgettable",
"память" : "memory, remembrance, recollection; See also: на память, без памяти",
"панамский пролив" : "Panama Canal",
"панацея" : "panacea",
"панда" : "panda",
"пандемический" : "pandemic",
"панель" : "pavement, wainscot",
"паника" : "panic",
"панихида" : "requiem dirge",
"панкреатический" : "pancreatic",
"панорама" : "panorama",
"пансион" : "boarding house, boarding school",
"панталоны" : "drawers pants",
"пантеизм" : "pantheism",
"пантеон" : "pantheon",
"пантера" : "panther",
"пантомима" : "mummery, pantomime",
"пантомимический" : "pantomimic",
"панцирь" : "coat of mail",
"папа" : "dad, dada, daddy, pa, papa",
"папа1" : "papa, dad",
"папа2" : "pope",
"паперть" : "porch",
"папильотка" : "hair curler",
"папироса" : "cigarette",
"папирус" : "papyrus",
"папка" : "folder, card-board",
"папоротник" : "fern",
"папский" : "apostolic, papal, popish",
"папство" : "papacy",
"пар" : "steam, fallow",
"пара" : "pair, couple",
"парабола" : "parabola",
"параболоид" : "paraboloid",
"парагвай" : "Paraguay",
"параграф" : "paragraph",
"парад" : "parade",
"парадный" : "full, front",
"парадокс" : "antimony, paradox",
"паразит" : "parasite, pest, sponger",
"паразитический" : "parasitic, parasitical",
"паразиты" : "vermin",
"паралич" : "palsy, paralysis",
"параллакс" : "parallax",
"параллелепипед" : "parallelepiped",
"параллельный" : "parallel",
"парамагнитный" : "paramagnetic",
"параметр" : "parameter",
"паранг" : "parang",
"параноидальный" : "paranoid",
"паранойя" : "paranoia",
"парапсихология" : "parapsychology",
"парафин" : "paraffin",
"парашют" : "parachute",
"парашютист" : "parachutist, milit. paratrooper",
"парвеню" : "parvenu",
"парез" : "paresis",
"парение" : "soar hover",
"парень" : "lad guy",
"пари" : "bet wager, пари? What do you bet?",
"париж" : "Paris",
"парижанин" : "Parisian",
"парижанка" : "Parisian",
"парик" : "wig",
"парикмахер" : "hairdresser barber",
"парикмахерская" : "hairdressing saloon barber's",
"парирование" : "parry",
"парировать" : "a. отпарировать parry",
"парис" : "paris",
"парить1" : "soar hover",
"парить2" : "steam",
"пария" : "castaway, pariah",
"парк" : "park",
"парка" : "parka",
"паркет" : "parquet, parquetry",
"парламент" : "parliament",
"парламентарий" : "parliamentarian",
"парламентский" : "parliamentary",
"парник" : "hotbed",
"парниковый" : "hotbed",
"парнишка" : "guy lad youngster",
"парной" : "fresh",
"парный" : "paired, twin...",
"паровоз" : "rail. engine",
"паровой" : "steam...",
"пародировать" : "parody",
"пародия" : "parody",
"пароль" : "password parole",
"паром" : "ferry",
"паромщик" : "ferryman",
"парообразный" : "steamy, vaporous",
"пароход" : "steamer",
"пароходный" : "steamship...",
"пароходство" : "line",
"парта" : "bench a. form",
"партактив" : "= партийный актив",
"партбилет" : "= партийный билет",
"партер" : "parterre Brt. pit",
"партиец" : "Party man #or member",
"партизан" : "guerilla partisan",
"партизанский" : "guerrilla, partisan",
"партийность" : "Party membership, partisanship, Party discipline",
"партийный" : "party..., su. = партиец",
"партитура" : "mus. score",
"партия" : "party, commerc. parcel lot consignment, milit. detachment, batch, game set, match, mus. part, commerc. партиями in lots",
"партнер" : "partner",
"партнерша" : "partner",
"парторг" : "Party organizer",
"парус" : "sail, на всех парусах under full sail",
"парусина" : "sailcloth canvas duck",
"парусиновый" : "canvas...",
"парусник" : "sailing ship",
"парусное судно" : "sailing ship",
"парфюмерия" : "perfumery",
"парча" : "brocade",
"парчовый" : "brocade",
"паршивый" : "mangy",
"пары" : "fume",
"пас" : "pass",
"паскаль" : "pascal",
"пасквиль" : "lampoon",
"паскудный" : "foul filthy",
"пасмурный" : "dull, gloomy",
"пасовать" : "pass, famil. yield",
"паспорт" : "passport",
"паспортный" : "passport",
"пассажир" : "passenger",
"пассажирка" : "passenger",
"пассажирский" : "passenger",
"пассажирский самолет" : "air liner",
"пассив" : "pl.",
"пассивный" : "passive",
"паста" : "paste",
"пастбище" : "pasture",
"пастбищный" : "pasturable",
"паства" : "eccl. flock",
"пастельный" : "pastel",
"пастернак" : "parsnip",
"пасти" : "graze  pasture",
"пастор" : "pastor",
"пастух" : "herder  shepherd",
"пастушеский" : "pastoral",
"пастуший" : "shepherd's",
"пастушка" : "shepherdess",
"пастырь" : "pastor",
"пасть" : "s. падать, pl. mouth",
"пасха" : "Easter, Easter cake, Passover",
"пасхальный" : "Easter...",
"пасынок" : "stepson",
"пасьянс" : "solitaire",
"патент" : "a. запатентовать patent",
"патентованный" : "patent",
"патентовать" : "a. запатентовать patent",
"патетический" : "pathetic",
"патефон" : "record player",
"патина" : "patina",
"патогенез" : "pathogenesis",
"патока" : "molasses a. treacle",
"патология" : "pathology",
"паточный" : "treacly",
"патриарх" : "patriarch",
"патриархальный" : "patriarchal, patriarchy",
"патриот" : "patriot",
"патриотический" : "patriotic",
"патрон" : "cartridge shell, socket, patron, pattern",
"патронташ" : "cartridge belt pouch",
"патрулировать" : "patrol",
"патруль" : "patrol",
"патрульный" : "patrolman",
"пауза" : "pause",
"паук" : "spider",
"паукообразный" : "arachnid, spidery",
"паутина" : "cobweb",
"пафос" : "pathos, verve vim",
"пах" : "anat. groin",
"пахание" : "ploughing",
"пахарь" : "plowman Brt. ploughman",
"пахать" : "plow  till",
"пахнуть1" : "smell",
"пахнуть2" : "pf. puff",
"пахота" : "tillage",
"пахотный" : "arable",
"пахта" : "buttermilk",
"пахучий" : "fragrant",
"пациент" : "patient",
"пациентка" : "patient",
"пацифизм" : "pacificism, pacifism",
"паче" : "тем паче",
"пачка" : "pack package, batch"
};
