var dicctr_39 = {
"манчестер" : "manchester",
"маори" : "maori",
"марафон" : "marathon",
"марганец" : "manganese",
"маргарин" : "margarine",
"маргаритка" : "daisy, marguerite",
"маринад" : "marinade",
"мариновать" : "pickle",
"марионетка" : "marionette, poppet, puppet",
"марихуана" : "marihuana, marijuana",
"марка" : "stamp, mark, counter, make, brand trademark",
"маркиз" : "marquess, marquis",
"маркиза" : "awning",
"марксистский" : "Marxist Marxian",
"марля" : "gauze",
"мармелад" : "fruit candy",
"мародерствовать" : "maraud",
"марокканец" : "moor",
"марс" : "mars",
"марсианин" : "martian",
"март" : "March",
"мартини" : "martini",
"мартовский" : "March",
"мартышка" : "marmoset",
"марфа" : "Martha",
"марш" : "march",
"маршал" : "marshal",
"маршировать" : "march",
"маршрут" : "route",
"марь" : "pigweed",
"маска" : "mask",
"маскарад" : "masked ball masquerade",
"маскировать" : "mask, disguise camouflage",
"маскировка" : "mask, disguise camouflage",
"масленица" : "carnival, famil. feast",
"масленка" : "butter dish, lubricator",
"масленый" : "s. масляный",
"маслина" : "olive",
"масличный" : "olive..., oil...",
"масло" : "butter, oil; See also: как по маслу",
"маслобойка" : "churn, oil mill",
"маслодельня" : "creamery",
"масляный" : "oil, butter, greasy unctuous",
"масон" : "mason",
"масонский" : "masonic",
"масса" : "mass, bulk, multitude",
"массаж" : "massage",
"массажист" : "masseur",
"массачусетс" : "massachusetts",
"массив" : "massif",
"массивный" : "massive",
"массировать" : "massage",
"массовый" : "mass...",
"мастер" : "master, foreman, craftsman, expert; See also: мастер на все руки",
"мастер на все руки" : "jack-of-all-trades",
"мастерить" : "work, make",
"мастерская" : "workshop, atelier studio",
"мастерской" : "masterly",
"мастерство" : "mastery skill, trade handicraft",
"мастика" : "mastic",
"маститый" : "venerable",
"мастурбировать" : "masturbate",
"масть" : "color, suit",
"масштаб" : "scale, fig. scope, caliber, repute, standard",
"мат" : "mat, mate",
"матвей" : "Matthew",
"математик" : "mathematician",
"математика" : "mathematics",
"математический" : "mathematical",
"материал" : "material",
"материализм" : "materialism",
"материалист" : "materialist",
"материалистический" : "materialistic",
"материальный" : "material, economic, financial",
"материк" : "continent",
"материковый" : "continental",
"материнский" : "mother motherly maternal",
"материнство" : "maternity",
"материя" : "matter, fabric material, stuff",
"матка" : "zo. female, queen, anat. uterus",
"матовый" : "dull dim mat",
"матрас" : "mattress",
"матрац" : "mattress",
"матрица" : "typ. matrix, stencil",
"матрос" : "sailor",
"матрос-индиец" : "lascar",
"матч" : "match",
"мать" : "mother",
"мать-и-мачеха" : "coltsfoot",
"мафия" : "mafia",
"мах" : "stroke flap, с маху at one stroke #or stretch, at once; See also: дать маху",
"махать" : "wave, wag, strike flap, famil. jump go; See also: махнуть рукой на",
"махинация" : "chicane, machination",
"махнуть" : "wave, wag, strike flap, famil. jump go; See also: махнуть рукой на",
"махнуть рукой на" : "give up",
"маховик" : "flywheel",
"маховое колесо" : "flywheel",
"махорка" : "tobacco",
"мачеха" : "stepmother",
"мачта" : "mast",
"маша" : "dim. #of Мария",
"машина" : "car, machine",
"машинальный" : "mechanical perfunctory",
"машинист" : "machinist, Brt. engine driver",
"машинистка" : "typist",
"машинка" : "machine, typewriter, clipper",
"машинный" : "machine... engine..., cf. МТС",
"машинописный" : "typescript, typewritten",
"машинопись" : "typewriting",
"машиностроение" : "mechanical engineering",
"маэстро" : "maestoso, maestro",
"маяк" : "lighthouse",
"маятник" : "pendulum",
"маяться" : "drudge",
"маячить" : "loom",
"мвд" : "abbr.: Министерство внутренних дел",
"мгла" : "darkness, mist haze",
"мглистый" : "hazy misty",
"мгновение" : "moment, instant twinkling",
"мгновенный" : "momentary instantaneous",
"мебель" : "furniture",
"меблировать" : "pf. обмеблировать furnish",
"меблировка" : "furnishing",
"мегабайт" : "megabyte",
"мегаватт" : "megawatt",
"мегаломания" : "megalomania",
"мегатонна" : "megaton",
"мегера" : "tatar",
"мед" : "honey, mead",
"медаль" : "medal",
"медальон" : "locket",
"медведица" : "she-bear, astr. Медведица Bear",
"медведь" : "bear",
"медвежий" : "bear, bad",
"медвежонок" : "bear cub",
"медея" : "medea",
"медик" : "medical man",
"медикаменты" : "medicaments medical supplies",
"медицина" : "medicine",
"медицинский" : "medical, medicinal",
"медленно" : "slow, slowly",
"медленный" : "slow",
"медлительный" : "sluggish slow indolent",
"медлить" : "delay linger be slow #or tardy hesitate",
"медник" : "brazier, tinker",
"медный" : "copper, brazen",
"медовый" : "honey",
"медоед" : "ratel",
"медосмотр" : "medical examination",
"медпункт" : "first-aid post",
"медсестра" : "nurse",
"медуза" : "jellyfish, medusa",
"медь" : "copper; See also: желтая медь",
"медянка" : "copperhead",
"меж" : "s. между",
"межа" : "border, balk",
"междометие" : "gr. interjection",
"междоусобный" : "internal civil",
"между" : "between, among; See also: между тем, между тем как",
"между прочим" : "by the way incidentally, among other things",
"между тем" : "meanwhile meantime",
"между тем как" : "whereas while",
"междугородный" : "teleph. long-distance..., Brt. trunk..., interurban",
"международный" : "international",
"междуцарствие" : "interregnum",
"межпланетный" : "interplanetary",
"мезонин" : "mezzanine",
"мейоз" : "meiosis",
"мексика" : "Mexico",
"мексиканец" : "Mexican",
"мексиканка" : "Mexican",
"мексиканский" : "Mexican",
"мел" : "chalk, whitewash",
"меланома" : "melanoma",
"меланхолик" : "melancholiac",
"меланхолический" : "melancholy melancholic",
"меланхоличный" : "melancholy melancholic",
"меланхолия" : "melancholy",
"мелеть" : "shallow",
"мелиорировать" : "meliorate",
"мелкий" : "small little, petty, fine shallow, flat",
"мелкий дождь" : "drizzle",
"мелководный" : "shallow",
"мелкость" : "shallowness",
"мелкота" : "famil. shallowness, coll.",
"меловой" : "cretaceous",
"мелодический" : "melodic, melodious",
"мелодичный" : "melodious",
"мелодия" : "melody",
"мелодрама" : "melodrama",
"мелодраматический" : "melodramatic, transpontine",
"мелочи" : "minutiae",
"мелочность" : "pettiness paltriness",
"мелочный" : "meticulous, niggling, peddling, petty",
"мелочный мелочной" : "petty paltry",
"мелочь" : "trifle, trinket, coll. small fry, change, pl. details particulars",
"мель" : "shoal sandbank; See also: на мели",
"мелькать" : "flash, gleam, flit, fly, loom, turn up",
"мелькнуть" : "flash, gleam, flit, fly, loom, turn up",
"мельком" : "in passing",
"мельник" : "miller",
"мельница" : "mill",
"мельчайший" : "infinitesimal",
"мельчать" : "become small #or shallow",
"мельчить" : "make small #or shallow",
"мелюзга" : "s. мелочь coll",
"мембрана" : "membrane",
"меморандум" : "memo",
"мемориальный" : "commemorative, memorial",
"мемуары" : "memoirs",
"мена" : "exchange, barter",
"менее" : "less; See also: менее всего, тем не менее",
"менее всего" : "least of all",
"менингит" : "meningitis",
"мениск" : "meniscus",
"меновой" : "exchange..., cf. мена",
"менопауза" : "menopause",
"менструировать" : "menstruate",
"ментор" : "mentor",
"менуэт" : "minuet",
"меньше" : "less, smaller, a. менее",
"меньшевик" : "Menshevik",
"меньший" : "smaller lesser, smallest least, famil. youngest",
"меньшинство" : "minority",
"меню" : "menu bill of fare",
"меня" : "me",
"менять" : "exchange barter, change, -ся",
"мера" : "measure, degree, way, по мере #or того как, according as to, as far as, while the ... the ..., по крайней мере at least",
"мерещиться" : "seem, appear, loom",
"мерзавец" : "rascal",
"мерзкий" : "vile odious",
"мерзлый" : "frozen",
"мерзнуть" : "freeze, be cold numb",
"мерзость" : "meanness, nasty thing",
"меридиональный" : "meridional",
"мерило" : "standard, criterion",
"мерин" : "gelding",
"мерить" : "measure",
"мериться" : "cope try conclusions with",
"мерка" : "measure",
"меркнуть" : "fade darken",
"мерлушка" : "astrakhan",
"мерный" : "measured",
"мероприятие" : "measure action",
"мертвая точка" : "engin. dead center, fig. deadlock",
"мертвенно-бледный" : "pallid",
"мертвенный" : "deadly",
"мертветь" : "deaden, grow #or turn numb",
"мертвец" : "corpse",
"мертвецкая" : "mortuary"
};
