var dicctr_19 = {
"дешевка" : "cheapness low price",
"дешевое" : "brummagem",
"дешевый" : "cheap, low",
"деятель" : "man, representative; See also: государственный деятель, научный деятель, общественный деятель, политический деятель",
"деятельность" : "activity -ties pl., work",
"деятельный" : "active",
"джазовый" : "jazz",
"джакарта" : "jakarta",
"джентльмен" : "gentleman, toff",
"джин" : "geneva, genie, gin, jinnee",
"джип" : "jeep",
"джоуль" : "joule",
"джунгли" : "jungle",
"джутовый" : "jute",
"дзюдо" : "judo",
"диабет" : "diabetes",
"диагноз" : "diagnosis",
"диагностический" : "diagnostic",
"диагональ" : "diagonal",
"диалект" : "dialect",
"диалектика" : "dialectic",
"диалектический" : "dialectic",
"диалектный" : "dialectic",
"диалог" : "dialogue",
"диамат" : "dialectical materialism",
"диаметр" : "diameter",
"диапазон" : "mus. diapason, engin. range",
"диапозитив" : "slide",
"диатез" : "diathesis",
"диафрагма" : "diaphragm",
"диван" : "divan sofa",
"диверсант" : "saboteur",
"диверсия" : "sabotage, milit. diversion",
"дивиденд" : "dividend",
"дивизия" : "division",
"дивиться" : "wonder",
"дивный" : "wonderful, delightful",
"диво" : "wonder miracle marvel, на диво excellently, что за диво! wonderful!, no wonder",
"дидактический" : "didactic",
"диета" : "diet",
"диетврач" : "dietician, dietitian",
"диетический" : "dietetic",
"дизель" : "diesel",
"дизентерия" : "dysentery",
"дикарь" : "savage, famil. shy person",
"дикий" : "wild savage, odd bizarre, shy unsociable, drab, med. proud, dog",
"дикобраз" : "porcupine",
"дикость" : "wildness savagery -geness, absurdity",
"диктант" : "s. диктовка",
"диктатор" : "dictator",
"диктаторский" : "dictatorial",
"диктатура" : "dictatorship",
"диктовать" : "dictate",
"диктовка" : "dictation",
"диктор" : "announcer",
"дикция" : "diction",
"дилетант" : "dilettante",
"дилетантский" : "dilettantish",
"дилижанс" : "diligence, stagecoach",
"дина" : "dyne",
"динамизм" : "dynamism",
"динамика" : "dynamics",
"динамит" : "dynamite",
"динамический" : "dynamic",
"динамо" : "dynamo",
"динамомашина" : "dynamo",
"динамо-машина" : "dynamo",
"династия" : "dynasty",
"динго" : "dingo",
"динозавр" : "dinosaur",
"диоптрия" : "diopter",
"диплом" : "diploma, famil. thesis to degree",
"дипломат" : "diplomat",
"дипломатический" : "diplomatic",
"дипломатия" : "diplomacy",
"директива" : "directive",
"директивный" : "directory",
"директор" : "manager director, principal Brt. headmaster",
"директорат" : "directorate",
"директорский" : "directorial, managerial",
"директриса" : "directrix",
"дирекция" : "management directorate",
"дирижабль" : "airship",
"дирижер" : "mus. conductor",
"дирижировать" : "mus. conduct",
"дисгармония" : "discord",
"диск" : "disk",
"дисковидный" : "discoid",
"дисконт" : "pf. discount",
"дисконтировать" : "pf. discount",
"дискотека" : "disco, discotheque",
"дискуссия" : "discussion",
"диспансер" : "dispensary",
"диспетчер" : "dispatcher, rail. traffic superintendent",
"диспут" : "dispute disputation",
"диссертация" : "dissertation thesis",
"диссонанс" : "dissonance discord",
"дистанция" : "distance, rail. section",
"дистиллировать" : "pf. distil",
"дисциплина" : "discipline",
"дисциплинарный" : "disciplinarian, disciplinary",
"дитя" : "child",
"дифирамб" : "dithyramb",
"дифтерит" : "diphtheria",
"дифтерия" : "diphtheria",
"диффамация" : "defamation",
"дифференциал" : "engin. differential",
"дифференциальный" : "engin. differential",
"дифференцировать" : "pf. differentiate",
"дичать" : "run wild, fig. grow shy unsociable, shun",
"дичиться" : "be shy unsociable",
"дичь" : "game wild fowl, famil. wilderness, famil. nonsense bosh",
"длина" : "length, в длину full length lengthwise, длиной в ... #or в длину ... long",
"длинно" : "long...",
"длинноногий" : "leggy",
"длинный" : "long",
"для" : "for",
"дневник" : "diary, journal",
"днепр" : "dnieper",
"днище" : "bilge",
"дно" : "bottom, fundus",
"до востребования" : "poste restante",
"до зарезу" : "famil. very badly",
"до зубов" : "to the teeth",
"до конца" : "completely",
"до отвала" : "famil. one's fill",
"до свидания" : "good-by",
"до сих пор" : "hitherto so far up to now",
"до тех пор" : "so long as",
"добавочный" : "accessory, adventitious, appendicular, plus",
"добираться" : "get to reach",
"добить" : "beat completely #or utterly smash, kill finish, -ся get obtain #or reach, strive for, find out, он добился своего he gained his end",
"доблестный" : "valiant brave",
"доблесть" : "valor",
"добраться" : "get to reach",
"добро бы" : "if only",
"добро пожаловать" : "welcome!, please",
"добровольный" : "freewill, voluntary",
"добродетель" : "virtue",
"добродетельный" : "moral, moralist, virtuous",
"добродушный" : "debonair",
"доброжелательность" : "goodwill",
"доброжелательный" : "benevolent",
"доброжелательство" : "benevolence",
"доброкачественный" : "good, med. benign",
"добром" : "famil. kindly amicably",
"добросердечный" : "good-hearted",
"добросовестный" : "conscientious",
"добрососедский" : "good neighborly",
"доброта" : "kindness",
"добротный" : "good, solid",
"добрый" : "kind, good, famil. solid; See also: доброе утро{!}, добрый день{!}, добрый вечер{!}, в добрый час{!}, всего доброго{!}, чего доброго, будь добр",
"добрый вечер" : "good evening!",
"добыча" : "catch, pillage, prey",
"довезти" : "s. довозить",
"доверенность" : "jur. letter of attorney, obsol. = доверие",
"доверенный" : "deputed, proxy, agent",
"доверие" : "confidence trust",
"доверить" : "s. доверять",
"доверчивость" : "credulity",
"доверчивый" : "trusting trustful, confidential",
"довершать" : "finish, complete",
"довершение" : "completion, в довершение #or к довершению, to complete #or crown",
"довершить" : "finish, complete",
"доверять" : "trust, confide #or entrust, entrust, -ся a. trust rely",
"довести" : "s. доводить",
"довод" : "argument",
"доводить" : "see, lead, bring, drive  make",
"довоенный" : "prewar",
"довозить" : "take #or bring",
"довольно" : "enough sufficient, rather pretty fairly",
"довольный" : "content satisfied",
"довольствие" : "ration allowance",
"довольство" : "contentment satisfaction, famil. prosperity",
"довольствоваться" : "content o.s.",
"довыборы" : "by-election",
"догадаться" : "s. догадываться",
"догадка" : "guess conjecture",
"догадливый" : "quick-witted",
"догадываться" : "guess surmise",
"догма" : "dogma",
"догмат" : "dogma",
"догматизм" : "dogmatism, pragmatism",
"догматический" : "dogmatic",
"догнать" : "s. догонять",
"договаривать" : "finish  speak",
"договариваться" : "agree  arrange",
"договаривающиеся стороны" : "/pl. contracting parties",
"договор" : "contract, pol. treaty",
"договорить" : "finish  speak",
"договорный" : "contract",
"догонять" : "catch up  overtake, drive #or bring to, a. pursue try to catch up be overtaking",
"догорать" : "burn down, fig. fade die out",
"догореть" : "burn down, fig. fade die out",
"доделать" : "finish complete",
"доделывать" : "finish complete",
"додуматься" : "find reach #or hit upon",
"додумываться" : "find reach #or hit upon",
"доезжать" : "reach, не доезжая short of",
"доехать" : "reach, не доезжая short of",
"дождаться" : "s. дожидаться",
"дождевик" : "raincoat",
"дождевой" : "rain",
"дождевой зонтик" : "umbrella",
"дождевой червь" : "earthworm",
"дождливый" : "rainy",
"дождь" : "rain",
"дождь идет" : "it is raining",
"доживать" : "etc., pf. live, see, come to",
"дожидаться" : "wait, a. see",
"дожить" : "etc., pf. live, see, come to",
"доза" : "dose",
"дозволенный" : "a. licit",
"дозволить" : "permit allow",
"дозволять" : "permit allow",
"дозвониться" : "pf. reach, ring till the door #or phone is answered",
"дозировка" : "dosage, posology, proportioning",
"дознание" : "inquest",
"дозор" : "patrol",
"дозорный" : "patrol",
"доискаться" : "find",
"доискиваться" : "find",
"доисторический" : "prehistoric",
"доить" : "milk",
"доказанный" : "proven",
"доказательный" : "evidential, probative",
"доказательство" : "demonstration, proof, vindication",
"доказать" : "prove, argue",
"доказуемый" : "demonstrable",
"доказывать" : "prove, argue",
"доканчивать" : "finish end",
"доклад" : "report, lecture",
"докладная" : "memorandum report",
"докладчик" : "lecturer, reporter",
"докладывать" : "report, announce",
"докончить" : "finish end",
"доктор" : "doctor",
"докторат" : "doctorate",
"доктрина" : "doctrine",
"документ" : "document",
"документальный" : "documentary",
"документация" : "documentation",
"докучать" : "= надоедать",
"долбить" : "выдолбить продолбить hollow, peck, chisel, famil. strike, popul. вдолбить inculcate, cram",
"долг" : "debt, sg. duty, honors pl.; See also: в долг, в долгу",
"долгий" : "long",
"долго" : "long a long time #or while",
"долго ли, коротко" : "ли sooner or later",
"долговечный" : "perennial  durable",
"долговое обязательство" : "promissory note"
};
