var dicctr_68 = {
"приказ" : "command, commandment",
"приказывать" : "bid",
"прикасаться" : "touch",
"приклад" : "butt",
"прикладной" : "applied",
"прикладывать" : "apply  put, enclose, affix",
"прикладываться" : "kiss, famil. level, apply",
"приклеенный" : "glued",
"приклеивать" : "paste",
"приклеить" : "paste",
"приключаться" : "happen occur",
"приключение" : "adventure",
"приключиться" : "happen occur",
"приковать" : "chain fetter, arrest captivate",
"приковывать" : "chain fetter, arrest captivate",
"приколачивать" : "nail  fasten",
"приколотить" : "nail  fasten",
"приколоть" : "pin fasten, stab",
"прикомандировать" : "pf. attach",
"прикосновение" : "touch contact",
"прикоснуться" : "touch",
"прикраса" : "embellishment",
"прикрасить" : "embellish",
"прикрашивать" : "embellish",
"прикрепить" : "s. прикреплять",
"прикреплять" : "attach",
"прилагательное" : "adjective",
"прилагать" : "enclose, apply, take  make",
"приладить" : "fit",
"прилаживать" : "fit",
"приласкать" : "caress, pet fondle, impf. cherish, flatter",
"прилегать" : "join border, прилечь, lie down, fit",
"прилегающий" : "adjoining, contiguous",
"прилежание" : "diligence",
"прилежный" : "diligent industrious",
"прилепить" : "stick",
"прилеплять" : "stick",
"прилетать" : "arrive fly",
"прилететь" : "arrive fly",
"прилечь" : "s. прилегать",
"прилив" : "flood flow, fig. rush",
"приливать" : "rush, add",
"приливно-отливный" : "tidal",
"прилипать" : "stick",
"прилипнуть" : "stick",
"прилить" : "rush, add",
"приличествовать" : "befit, beseem",
"приличие" : "decency  decorum",
"приличный" : "decent proper, famil. respectable",
"приложение" : "enclosure, supplement, application, gr. apposition, #seal: affixture",
"приложить" : "apply  put, enclose, affix",
"приложиться" : "kiss, famil. level, apply",
"прильнуть" : "cling nestle",
"примадонна" : "diva, prima donna",
"приманка" : "bait lure",
"применение" : "application, use, adaptation",
"применимый" : "applicable",
"применить" : "apply, use employ, -ся adapt o.s.",
"применяется" : "employed",
"применять" : "apply, use employ, -ся adapt o.s.",
"пример" : "example, не в ~ comp., к примеру famil. = например",
"примеривать" : "try #or fit on",
"примерить" : "famil. try on",
"примерка" : "trying #or fitting on",
"примерный" : "exemplary, approximate",
"примерять" : "= примеривать",
"примесь" : "admixture",
"примета" : "mark sign token, omen, pl. signalment description, на примете in view",
"приметить" : "s. примечать",
"приметный" : "s. заметный",
"примечание" : "note, notice",
"примечательный" : "notable remarkable",
"примечать" : "notice",
"примешать" : "add mix",
"примешивать" : "add mix",
"примирение" : "reconciliation",
"примирительный" : "conciliatory, arbitration...",
"примирить" : "reconcile, -ся make it up be reconciled",
"примириться" : "resign o.s. to, put up with",
"примирять" : "s. мирить",
"примкнуть" : "s. примыкать",
"приморский" : "coastal seaside...",
"примочка" : "lotion",
"примула" : "primrose",
"примус" : "kerosene stove",
"примчаться" : "pf. come in a great hurry",
"примыкать" : "join, impf. adjoin",
"примыкающий" : "abutting",
"принадлежать" : "belong  pertain",
"принадлежащий" : "belonging",
"принадлежность" : "accessory, material implement, a. equipment, membership",
"принести" : "s. приносить",
"принимать" : "take, accept, receive, admit, pass, adopt, assume; See also: принять на себя, принять на свой счет, принять парад",
"приниматься" : "set about #or to start, famil. take to task, med. take",
"приноровить" : "pf. adapt, fit",
"приносить" : "bring, yield, make",
"приносить в дар" : "s. дарить",
"принудительный" : "forced compulsory coercive",
"принудить" : "force compel constrain oblige",
"принуждать" : "force compel constrain oblige",
"принуждение" : "compulsion coercion constraint",
"принужденный" : "forced constrained obliged",
"принц" : "prince",
"принцесса" : "princess",
"принцип" : "principle",
"принципиальный" : "of principle",
"принятие" : "taking, acceptance, admission, passing, adoption, assumption",
"принятый" : "customary, a. принять s. принимать",
"принять" : "take, accept, receive, admit, pass, adopt, assume; See also: принять на себя, принять на свой счет, принять парад",
"принять на свой счет" : "feel hurt",
"принять на себя" : "take on o.s. undertake",
"принять парад" : "review troops",
"приняться" : "set about #or to start, famil. take to task, med. take",
"приобрести" : "acquire obtain get, buy",
"приобретать" : "acquire obtain get, buy",
"приобретение" : "acquisition",
"приобщать" : "join add",
"приобщаться" : "join",
"приобщить" : "join add",
"приобщиться" : "join",
"приостанавливать" : "stop, jur. suspend",
"приостановить" : "stop, jur. suspend",
"приотворенный" : "ajar",
"припадание" : "crouch",
"припадок" : "fit attack",
"припарка" : "cataplasm, fomentation, poultice",
"припасы" : "supplies stores",
"припаять" : "pf. solder",
"припев" : "refrain",
"припевать" : "sing",
"припеваючи" : "famil. in clover",
"припекать" : "burn be hot",
"припечь" : "burn be hot",
"приписать" : "ascribe attribute, add",
"приписка" : "postscript, addition",
"приписывание" : "ascription, attribution",
"приписывать" : "ascribe attribute, add",
"приплата" : "extra payment",
"приплод" : "increase offspring",
"приплывать" : "come arrive swim #or sail",
"приплыть" : "come arrive swim #or sail",
"приплюснутый" : "flat",
"приподнимать" : "lift #or raise",
"приподнятый" : "high, elevated",
"приподнять" : "lift #or raise",
"приползать" : "creep",
"приползти" : "creep",
"припоминать" : "remember",
"припомнить" : "remember",
"приправа" : "seasoning",
"приправить" : "season dress",
"приправлять" : "season dress",
"припухать" : "swell",
"припухнуть" : "swell",
"приработок" : "perquisite",
"приравнивать" : "compare, level",
"приравнять" : "compare, level",
"прирастать" : "take, grow, increase",
"прирасти" : "take, grow, increase",
"приращение" : "increase, taking",
"приревновать" : "be jealous",
"природа" : "nature",
"природный" : "natural, прирожденный",
"прирожденный" : "born",
"прирост" : "increase",
"приручать" : "tame",
"прирученный" : "tame",
"приручить" : "tame",
"присадка" : "additive",
"присаживаться" : "sit down",
"присваивать" : "appropriate, adopt, confer",
"присвоение" : "appropriation, adoption, conferment",
"присвоить" : "appropriate, adopt, confer",
"приседать" : "squat, curtsy",
"присест" : "sitting",
"присесть" : "sit down",
"прискакать" : "come arrive",
"прискакивать" : "come arrive",
"прискорбие" : "regret",
"прискорбный" : "deplorable pitiable",
"прислать" : "s. присылать",
"прислонить" : "lean",
"прислонять" : "lean",
"прислоняться" : "recline",
"прислуга" : "servant, pl.",
"прислуживать" : "wait on  serve",
"прислуживаться" : "be subservient  ingratiate o.s.",
"прислушаться" : "listen",
"прислушиваться" : "listen",
"присматривать" : "look after, famil. find",
"присматриваться" : "peer look narrowly, examine, familiarize o.s. get acquainted",
"присмотр" : "care supervision",
"присмотреть" : "look after, famil. find",
"присниться" : "impers.: dream",
"присовокупить" : "add, enclose",
"присовокуплять" : "add, enclose",
"присоединение" : "joining, connection, annexation",
"присоединить" : "join, connect attach, annex incorporate",
"присоединять" : "join, connect attach, annex incorporate",
"приспешник" : "accomplice",
"приспосабливаться" : "conform",
"приспособить" : "s. приспособлять",
"приспособление" : "adaptation, appliance, conformation, doohickey",
"приспособлять" : "accommodate, adapt",
"приставать" : "molest",
"приставка" : "prefix",
"пристань" : "dock, quayside",
"пристойность" : "propriety",
"пристрастие" : "predilection, bias",
"пристрастный" : "biased partial",
"пристреливать" : "shoot",
"пристрелить" : "shoot",
"пристроить" : "add #or attach, settle, place, provide",
"пристройка" : "addition, annex",
"приступ" : "assault onset onslaught storm, & fig. fit attack, famil. access",
"приступать" : "set about start begin, proceed, approach",
"приступить" : "set about start begin, proceed, approach",
"приступок" : "stile",
"пристыдить" : "shame make ashamed",
"пристыженный" : "ashamed, hangdog",
"присудить" : "sentence condemn, award",
"присуждать" : "sentence condemn, award",
"присуждение" : "awarding",
"присутствие" : "presence, obsol. office",
"присутствовать" : "be present",
"присутствующий" : "present",
"присущий" : "peculiar",
"присылать" : "send",
"присыпать" : "strew",
"присяга" : "oath",
"присягать" : "swear",
"присягающий" : "juror",
"присягнувший" : "swore",
"присягнуть" : "swear",
"присяжный" : "juror; See also: суд присяжных",
"притаить" : "famil. s. затаить",
"притаиться" : "hold, hide, keep quiet",
"притаскивать" : "drag, famil. bring",
"притащить" : "drag, famil. bring",
"притворить" : "s. притворять",
"притворство" : "affectation, feint, pretence",
"притворяться" : "feign pretend",
"притеснение" : "oppression",
"притеснитель" : "oppressor",
"притеснить" : "oppress, obsol. press",
"притеснять" : "oppress, obsol. press",
"притихать" : "become silent stop, abate",
"притихнуть" : "become silent stop, abate",
"приток" : "tributary, afflux",
"притом" : "besides, to that #or it"
};
