var dicctr_72 = {
"пугало" : "scarecrow",
"пугать" : "frighten scare",
"пугливый" : "timid fearful",
"пугнуть" : "frighten scare",
"пуговица" : "button",
"пуд" : "pood",
"пудель" : "poodle",
"пудинг" : "duff, pudding",
"пудра" : "powder; See also: сахарная пудра",
"пудреница" : "powder box",
"пудрить" : "powder",
"пузатый" : "paunchy",
"пузо" : "paunch",
"пузырек" : "vial, dim. #of пузырь",
"пузырчатый" : "bladdery, vesicular",
"пузырь" : "bubble, anat. bladder, famil. blister, kid",
"пук" : "wisp, bunch bundle",
"пулемет" : "machine gun",
"пулеметный" : "machine-gun, cartridge",
"пулеметчик" : "machine gunner",
"пуловер" : "pullover",
"пульверизатор" : "spray",
"пульмональный" : "pulmonary",
"пульс" : "pulse",
"пульсар" : "pulsar",
"пульсация" : "palpitation, pulsation",
"пульсировать" : "pulse",
"пульт" : "desk stand",
"пуля" : "bullet",
"пума" : "cougar, puma",
"пунический" : "punic",
"пункт" : "point, station, place spot, item clause article",
"пунктир" : "dotted line",
"пунктирный" : "dotted",
"пунктуальность" : "punctuality, accuracy",
"пунктуальный" : "punctual, accurate",
"пунцовый" : "crimson",
"пунш" : "punch",
"пуп" : "navel",
"пупок" : "navel",
"пупочный" : "umbilical",
"пурга" : "blizzard snowstorm",
"пуританский" : "puritan, puritanic, puritanical",
"пурпур" : "purple",
"пурпурный" : "purple",
"пурпуровый" : "purple",
"пуск" : "start setting in operation",
"пускай" : "s. пусть",
"пускать" : "let  set (free, going in motion #or operation [a. пускать в ход]), start, launch throw, release, allow, put, send, force, take; See also: пускать под откос",
"пускать под откос" : "derail",
"пускаться" : "start  set out, enter #or engage  begin undertake",
"пустеть" : "become empty #or deserted",
"пустить" : "let  set (free, going in motion #or operation [a. пускать в ход]), start, launch throw, release, allow, put, send, force, take; See also: пускать под откос",
"пустить в ход" : "start set going #or on foot circulate",
"пустить корни" : "take root",
"пустить по миру" : "bring to beggary",
"пустой" : "empty, void, vain idle, vacant, blank, dead, famil. hollow",
"пустомеля" : "bagpipe, chatterbox",
"пустота" : "emptiness, void, phys. vacuum, vacancy",
"пустынный" : "desert desolate",
"пустыня" : "desert waste wilderness",
"пустырь" : "waste ground",
"пустышка" : "blank, nonentity",
"пусть" : "let  may, even",
"пустяк" : "trifle, pl. nonsense, nothing",
"пустяки" : "trivia",
"пустяковый" : "trifling",
"пустячный" : "trifling",
"путаница" : "confusion muddle mess",
"путать" : "confuse muddle, mix up entangle",
"путевка" : "pass  permit",
"путеводитель" : "guide",
"путеводный" : "lode... pole",
"путевой" : "travelling, traveller's, road...",
"путешественник" : "traveler",
"путешествие" : "journey travel tour, voyage",
"путешествовать" : "travel",
"путник" : "traveler",
"путный" : "s. дельный",
"путы" : "shackles",
"путь" : "way  road path, rail. track  line, means, trip journey, route, в #or по пути on the way, in passing, нам по пути I have the same way, s. толк",
"пух" : "down; See also: в пух",
"пухленький" : "chubby plump",
"пухлый" : "chubby plump",
"пухнуть" : "swell",
"пуховка" : "powder puff",
"пуховый" : "down...",
"пучина" : "gulf abyss, eddy",
"пучок" : "s.",
"пушечный" : "gun... cannon...",
"пушинка" : "down fluff",
"пушистый" : "downy fluffy",
"пушка" : "gun cannon, famil. hoax",
"пушнина" : "furs pl.",
"пушница" : "canna",
"пушной" : "fur...",
"пушок" : "down",
"пуще" : "popul. more",
"пуэрториканец" : "puerto",
"пхеньян" : "pyongyang",
"пчела" : "bee",
"пчеловод" : "beekeeper",
"пчеловодство" : "beekeeping",
"пчельник" : "apiary",
"пшеница" : "wheat",
"пшеничный" : "wheaten",
"пшенный" : "millet...",
"пшено" : "millet",
"пыл" : "ardor zeal blaze, в пылу in the thick",
"пылать" : "blaze flare  flame, glow burn, rage",
"пылесос" : "vacuum cleaner",
"пылинка" : "mote",
"пылить" : "dust",
"пылиться" : "be dusty",
"пылкий" : "ardent fiery",
"пыль" : "dust",
"пыльник" : "anther",
"пыльный" : "dusty",
"пыльца" : "pollen",
"пытать" : "torture",
"пытаться" : "try attempt",
"пытка" : "torture",
"пытливый" : "inquisitive searching",
"пыхтение" : "chug",
"пыхтеть" : "puff pant, famil. sweat",
"пышность" : "splendor pomp",
"пышный" : "magnificent splendid sumptuous, luxuriant rich",
"пьедестал" : "pedestal",
"пьеса" : "thea. play, mus. piece",
"пьянеть" : "get drunk",
"пьяница" : "drunkard",
"пьянство" : "drunkenness",
"пьянствовать" : "drink famil. booze",
"пьяный" : "drunk fig.",
"пюре" : "mashed potatoes pl.",
"пядь" : "span, fig. inch",
"пята" : "heel",
"пятак" : "five-kopeck coin",
"пятачок" : "five-kopeck coin",
"пятая" : "math. fifth",
"пятерка" : "five, cf., five-ruble note",
"пятеро" : "five",
"пятидесятница" : "pentecost",
"пятидесятый" : "fiftieth, пятидесятые годы pl. the fifties, cf. пятый",
"пятиконечный" : "five-pointed",
"пятилетка" : "five-year plan",
"пятилетний" : "five-year  of five",
"пятисотый" : "five hundredth",
"пятиться" : "back",
"пятка" : "heel",
"пятнадцатый" : "fifteenth, cf. пятый",
"пятнадцать" : "fifteen, cf. пять",
"пятнистый" : "spotty spotted",
"пятница" : "Friday",
"пятно" : "spot stain blot; See also: родимое пятно",
"пятнышко" : "speck, speckle",
"пятое" : "su. fifth, пять пятого five past four",
"пятый" : "fifth, five",
"пять" : "five, без пяти час, five to one",
"пятьдесят" : "fifty",
"пятьсот" : "five hundred",
"пятью" : "five times",
"р" : "abbr.:, рубль -ля -лей, река",
"раб" : "bondservant, slave, thrall",
"рабовладелец" : "slaveholder",
"раболепный" : "fawning, menial, obsequies, servile",
"раболепство" : "servility",
"раболепствовать" : "cringe",
"работа" : "work, labor toil, assignment task",
"работать" : "work  function, labor toil, be open",
"работник" : "worker working man, laborer hand, maid, official functionary, employee, member, clerk",
"работница" : "worker working man, laborer hand, maid, official functionary, employee, member, clerk",
"работодатель" : "employer famil. boss",
"работоспособный" : "able to work able-bodied, hard-working efficient",
"работяга" : "dogsbody, drudge",
"рабочая сила" : "man power, labor",
"рабочий" : "worker, adj.: working work, workers' labor...",
"рабский" : "slave..., slavish servile",
"рабство" : "slavery",
"рабыня" : "s. раба",
"раввин" : "rabbi, rabbin",
"равенство" : "equality",
"равнение" : "milit. eyes",
"равнина" : "plain",
"равно" : "equal, as well, все равно it's all the same it doesn't matter, anyway in any case",
"равновесие" : "balance  equilibrium",
"равноденственный" : "equinoctial",
"равноденствие" : "equinox",
"равнодушие" : "indifference",
"равнодушный" : "indifferent",
"равнозначный" : "equivalent",
"равномерный" : "uniform even equal",
"равноправие" : "equality",
"равноправный" : "equal",
"равносильный" : "equivalent",
"равносторонний" : "equilateral",
"равноценный" : "equal",
"равный" : "equal",
"равным образом" : "s. равно, ему нет равного he has no match",
"равнять" : "equalize, milit. dress, famil. compare",
"равняться" : "align, amount to",
"рагу" : "haricot, ragout",
"рад" : "glad  pleased delighted, would like, willing; See also: не рад, рад не рад",
"рад не рад" : "willy-nilly",
"радар" : "radar",
"ради" : "for the sake of, for",
"ради бога" : "for God's sake",
"радиальный" : "radial",
"радиан" : "radian",
"радиатор" : "radiator",
"радий" : "radium",
"радикал" : "radical",
"радикальный" : "radical",
"радио" : "radio a. wireless",
"радиоактивность" : "radioactivity",
"радиоактивный" : "radioactive",
"радиоаппарат" : "s. радиоприемник",
"радиовещание" : "broadcasting",
"радиограмма" : "aerogram, radiogram",
"радиография" : "radiography, skiagraphy",
"радиола" : "radio-gramophone",
"радиология" : "radiology",
"радиолокатор" : "radar",
"радиолюбитель" : "radiofan",
"радиометр" : "radiometer",
"радиопередача" : "broadcast transmission",
"радиоприемник" : "receiving set radio Brt. wireless",
"радиослушатель" : "listener",
"радиостанция" : "radio station",
"радиотелеграф" : "radiotelegraph",
"радиотелефон" : "radiophone, radiotelephone",
"радиоузел" : "radio center",
"радиоустановка" : "radio plant",
"радист" : "radio operator",
"радиус" : "radius",
"радовать" : "gladden please rejoice, -ся rejoice  be glad #or pleased, look forward",
"радостный" : "joyful glad, merry",
"радость" : "joy gladness, pleasure",
"радуга" : "rainbow",
"радужная оболочка" : "iris",
"радужный" : "iridescent rainbow..., fig. rosy",
"радушие" : "kindliness, hospitality",
"радушный" : "kindly hearty, hospitable",
"раз" : "time, one, ~ once; See also: два раза, ни разу, не раз, как раз, в самый раз, вот тебе раз",
"разбавить" : "dilute",
"разбавление" : "dilution",
"разбавленный" : "dilute, diluted",
"разбавлять" : "dilute",
"разбалтывать" : "let out",
"разбег" : "start run"
};
