var dicctr_58 = {
"перелистать" : "turn over, look through",
"перелистывать" : "turn over, look through",
"перелить" : "decant pour, med. transfuse, переливать из пустого в порожнее, mill the wind, -ся overflow, mus. warble roll, play shimmer",
"перелицевать" : "face, turn",
"переложение" : "transposition, arrangement, setting to music",
"переложить" : "put lay #or pack  shift, interlay, cf. перелагать",
"перелом" : "fracture, crisis turning point",
"переломать" : "s. переламывать",
"переломить" : "s. переламывать",
"перемалывать" : "grind mill",
"переманивать" : "entice",
"перемежать" : "alternate, intermit",
"перемежающийся" : "intermittent",
"перемешать" : "mix, confuse",
"перемешивать" : "mix, confuse",
"перемещать" : "move shift",
"перемещение" : "transposition",
"перемещенные лица" : "pl. displaced persons",
"перемирие" : "armistice truce",
"перемолоть" : "grind, impf. talk",
"перенаселение" : "overpopulation",
"перенесение" : "transference",
"перенести" : "s. переносить",
"перенимать" : "adopt take over",
"перенос" : "transfer carrying over, sum carried over, syllabification",
"переносить" : "transfer carry over, bear endure stand, postpone put off",
"переносица" : "bridge",
"переноска" : "carrying transport",
"переносный" : "portable, figurative",
"переночевать" : "pass the night",
"перенять" : "adopt take over",
"переоборудование" : "reequipment",
"переоборудовать" : "pf. reequip",
"переодеваться" : "change",
"переодетый" : "a. disguised",
"переодеться" : "change",
"переоценивать" : "overestimate overrate, revalue",
"переоценить" : "overestimate overrate, revalue",
"переоценка" : "overestimation, revaluation",
"перепел" : "quail",
"перепечатать" : "reprint, type",
"перепечатка" : "reprint",
"перепечатывать" : "reprint, type",
"переписать" : "copy, type, list, enumerate, -ся impf. correspond",
"переписка" : "copying, typing, correspondence",
"переписчик" : "copyist",
"переписывание" : "transcription",
"переписывать" : "copy, type, list, enumerate, -ся impf. correspond",
"переписываться" : "correspond",
"перепись" : "census",
"переплатить" : "overpay",
"переплачивать" : "overpay",
"переплести" : "bind, interlace intertwine",
"переплет" : "binding book cover",
"переплетать" : "bind, interlace intertwine",
"переплетчик" : "bookbinder",
"переплывать" : "swim #or sail",
"переплыть" : "swim #or sail",
"переползать" : "creep crawl",
"переползти" : "creep crawl",
"переполненный" : "overcrowded, overflowing",
"переполнить" : "overfill  cram, overcrowd",
"переполнять" : "overfill  cram, overcrowd",
"переполох" : "tumult turmoil, dismay fright",
"переполошить" : "pf. alarm perturb",
"перепонка" : "membrane, web",
"переправа" : "crossing passage, ford, temporary bridge",
"переправить" : "carry  convey, -ся cross pass",
"переправлять" : "carry  convey, -ся cross pass",
"перепродавать" : "resell",
"перепродажа" : "resale",
"перепродать" : "resell",
"перепрыгивать" : "jump",
"перепрыгнуть" : "jump",
"перепуг" : "fright",
"перепугать" : "pf. frighten",
"перепутать" : "confuse muddle, mix up entangle",
"перепутывать" : "s. путать",
"перепутье" : "crossroad",
"перерабатывать" : "work  process, remake",
"переработать" : "work  process, remake",
"переработка" : "working  processing, remaking",
"перерастать" : "grow develop, overgrow",
"перерасти" : "grow develop, overgrow",
"перерасход" : "excess expenditure",
"перерезать" : "cut, cut off, kill",
"перерезывать" : "cut, cut off, kill",
"переродиться" : "regenerate, degenerate",
"перерождаться" : "regenerate, degenerate",
"перерубать" : "hew #or cut through",
"перерубить" : "hew #or cut through",
"перерыв" : "interruption, stop, break interval, time",
"пересадить" : "transplant, graft, make change seats",
"пересадка" : "transplanting, grafting, rail. change",
"пересаживать" : "transplant, graft, make change seats",
"пересаживаться" : "take another seat change seats, change",
"пересдавать" : "repeat",
"пересдать" : "repeat",
"пересекать" : "cut, intersect cross",
"переселенец" : "settler",
"переселение" : "migration, removal move",
"переселить" : "move",
"переселять" : "move",
"переселяться" : "migrate",
"переселятья" : "emigrate",
"переселяющийся" : "immigrant",
"пересесть" : "take another seat change seats, change",
"пересечение" : "intersection",
"пересечь" : "cut, intersect cross",
"пересиливать" : "overpower master subdue",
"пересилить" : "overpower master subdue",
"пересказ" : "retelling",
"пересказать" : "retell",
"пересказывать" : "retell",
"перескакивать" : "jump, skip",
"перескочить" : "jump, skip",
"переслать" : "s. пересылать",
"пересматривать" : "reconsider revise, jur. review",
"пересмотр" : "reconsideration revision, jur. review",
"пересмотреть" : "reconsider revise, jur. review",
"пересолить" : "pf. oversalt",
"пересохнуть" : "s. пересыхать",
"переспрашивать" : "repeat one's question",
"переспросить" : "repeat one's question",
"перессориться" : "pf. quarrel",
"переставать" : "stop cease quit",
"переставить" : "put  set move, rearrange, transpose, convert, math. permute",
"переставлять" : "put  set move, rearrange, transpose, convert, math. permute",
"перестановка" : "shift move, rearrangement, transposition, conversion, math. permutation",
"перестать" : "stop cease quit",
"перестраивать" : "rebuild reconstruct, reorganize, regroup",
"перестреливаться" : "skirmish",
"перестрелка" : "skirmish",
"перестроить" : "rebuild reconstruct, reorganize, regroup",
"перестройка" : "rebuilding reconstruction, reorganization",
"переступать" : "step over cross, fig. transgress",
"переступить" : "step over cross, fig. transgress",
"пересуды" : "gossip",
"пересчитать" : "re-count, count",
"пересчитывать" : "re-count, count",
"пересылать" : "send  transmit, forward",
"пересылка" : "consignment conveyance, carriage",
"пересыхать" : "dry up, parch",
"перетаскивать" : "drag #or carry",
"перетащить" : "drag #or carry",
"переть" : "press push",
"перетягивать" : "draw over, outweigh, cord",
"перетянуть" : "draw over, outweigh, cord",
"переубедить" : "make s.b. change his mind",
"переубеждать" : "make s.b. change his mind",
"переулок" : "lane alleyway side street",
"переутомление" : "overfatigue",
"переутомленный" : "overtired",
"переучет" : "inventory, stock-taking",
"перехват" : "interception",
"перехватить" : "intercept, embrace, famil. borrow",
"перехватывать" : "intercept, embrace, famil. borrow",
"перехитрить" : "pf. outwit",
"переход" : "passage, crossing, milit. march, fig. transition, conversion",
"переходить" : "cross go over, pass  proceed, turn, exceed transgress",
"переходить вброд" : "ford",
"переходный" : "transitional, gr. transitive",
"переходящий" : "challenge",
"перец" : "pepper, paprika",
"перечень" : "list, index",
"перечеркивать" : "cross out",
"перечеркнуть" : "cross out",
"перечесть" : "& перечитывать",
"перечислить" : "enumerate",
"перечислять" : "enumerate",
"перечитать" : "reread, read",
"перечитывать" : "reread, read",
"перечить" : "contradict oppose",
"перешагнуть" : "pf. step over cross, transgress",
"перешеек" : "isthmus",
"перешептываться" : "whisper",
"перешивать" : "make over alter",
"перешить" : "make over alter",
"перещеголять" : "pf. outdo",
"перигелий" : "perihelion",
"перила" : "railing, banisters",
"перина" : "feather bed",
"период" : "period, epoch age",
"периодический" : "periodic, math. circulating",
"перископ" : "periscope",
"перистый" : "pinnate, pinnated, plumy",
"периферийный" : "peripheral",
"периферия" : "circumference periphery, outskirts pl.",
"перламутр" : "mother-of-pearl",
"перловый" : "pearl",
"перманент" : "permanent wave",
"пермь" : "permian",
"пернатый" : "feathered feathery",
"перо" : "feather plume, pen, вечное перо fountain pen",
"перочинный нож" : "penknife",
"персей" : "perseus",
"персидский" : "persian",
"персик" : "peach",
"персона" : "persona",
"персонаж" : "personage",
"персонал" : "personnel",
"перспектива" : "vista",
"перспективный" : "perspective",
"перфузия" : "perfusion",
"перхлорат" : "perchlorate",
"перчатка" : "glove",
"песенка" : "ditty",
"песнопение" : "motet",
"песнь" : "chant",
"песня" : "song, famil. story",
"песок" : "sand, granulated sugar",
"песочный" : "sand",
"пессимизм" : "pessimism",
"пессимистический" : "pessimistic",
"пессимистичный" : "pessimistic",
"пестик" : "pestle, pistil, ponder",
"пестицид" : "pesticide",
"пестреть" : "grow variegated, gleam glisten",
"пестрота" : "motley, gayness",
"пестрый" : "variegated parti-colored motley, gay",
"песчаник" : "sandstone",
"песчанный" : "arenaceous",
"песчаный" : "sand",
"песчинка" : "grain",
"петелька" : "tab",
"петиция" : "petition",
"петлица" : "buttonhole, tab",
"петля" : "loop, eye, mesh, stitch, hinge",
"петр" : "Peter",
"петрология" : "petrology",
"петрушка" : "Punch, петрушка parsley",
"петух" : "rooster cock",
"петушиный" : "cock...",
"петь" : "спеть пропеть sing, пропеть crow",
"пехота" : "infantry",
"пехотинец" : "infantryman",
"пехотный" : "infantry",
"печалить" : "grieve",
"печаль" : "grief sorrow, famil. business concern",
"печальный" : "sad grieved sorrowful",
"печатать" : "print, type",
"печататься" : "impf. be in the press, write for appear in",
"печатник" : "printer",
"печатный" : "printed, printing",
"печать" : "seal stamp, press, print type",
"печенка" : "liver",
"печеночник" : "liverwort",
"печеный" : "baked",
"печень" : "liver",
"печенье" : "pastry, cookie biscuit"
};
