var dicctr_87 = {
"телевизор" : "TV set",
"телега" : "cart telega",
"телеграмма" : "telegram wire",
"телеграф" : "telegraph, wire",
"телеграфировать" : "telegraph, telegram... by wire",
"телеграфия" : "telegraphy",
"телеграфный" : "telegraph, telegram... by wire",
"тележка" : "handcart",
"телекинез" : "telekinesis",
"телекс" : "telex",
"теленок" : "calf",
"телеобработка" : "teleprocessing",
"телеология" : "teleology",
"телепатия" : "telepathy",
"телепередача" : "telecast",
"телескоп" : "telescope",
"телескопический" : "telescopic",
"телесный" : "corporal, corporeal, flesh-colored",
"телетайп" : "teleprinter, teletype",
"телефон" : "telephone",
"телефонировать" : "famil. phone",
"телефонист" : "operator",
"телефонистка" : "operator",
"телефония" : "telephony",
"телефонный" : "tele..., call",
"телефотография" : "telephotography",
"телец" : "taurus",
"телиться" : "calve",
"телка" : "heifer",
"теллур" : "tellurium",
"тело" : "body, phys. solid; See also: инородное тело, всем телом",
"телосложение" : "build, constitution",
"телохранитель" : "bodyguard",
"телятина" : "veal",
"телячий" : "veal",
"тем" : "s. тот",
"тем более" : "the more so",
"тем временем" : "meanwhile",
"тем лучше" : "so much the better",
"тем не менее" : "nevertheless",
"тем паче" : "all the more",
"тем самым" : "thereby",
"тема" : "subject theme",
"тематический" : "thematic, topical",
"тембр" : "timbre",
"темнеть" : "darkle",
"темно-коричневый" : "umber",
"темно-красный" : "crimson",
"темно-лиловый" : "petunia",
"темно-синий" : "sapphire",
"темный" : "cimmerian, dark, darksome, murk, tenebrous",
"темп" : "tempo",
"темперамент" : "mettle, temperament",
"температура" : "temperature",
"темя" : "crown",
"тенденциозный" : "tendentious",
"тенденция" : "tendency",
"тенденця" : "tendency",
"тендер" : "tender",
"тензор" : "tensor",
"тенистый" : "shady",
"теннис" : "tennis",
"тенор" : "tenor",
"тент" : "awning",
"тень" : "shade, shadow",
"теодолит" : "stadia, theodolite",
"теократия" : "theocracy",
"теология" : "theology",
"теорема" : "theorem",
"теоретик" : "theorist",
"теоретический" : "theoretical",
"теория" : "theory",
"теория познания" : "epistemology",
"теперешний" : "present actual",
"теперь" : "now at present",
"теплая встреча" : "warm welcome",
"теплеть" : "grow warm",
"теплиться" : "burn, glimmer",
"теплица" : "hothouse",
"тепличный" : "hothouse",
"тепло" : "warmth, phys. heat, warm weather, s. теплый",
"тепловатый" : "tepid",
"тепловой" : "heat thermal",
"теплота" : "warmth, phys. heat",
"теплоход" : "motor ship",
"теплушка" : "heatable boxcar",
"теплый" : "warm, hot, тепло it is warm",
"терапевт" : "therapist",
"терапевтический" : "therapeutic",
"терапия" : "therapy",
"теребить" : "pull, tousle, twitch, famil. pester",
"терем" : "attic, chamber",
"тереть" : "rub, grate",
"тереться" : "famil. hang about",
"терзание" : "torment agony",
"терзать" : "истерзать torment torture, растерзать tear to pieces",
"терка" : "grater",
"терм" : "therm",
"термальный" : "thermal",
"термин" : "term",
"терминология" : "terminology",
"термит" : "termite, thermit",
"термометр" : "thermometer",
"термос" : "vacuum #or thermos bottle",
"термостат" : "thermostat",
"терн" : "sloe",
"тернистый" : "thorny",
"терпеливый" : "patient",
"терпение" : "patience",
"терпеть" : "suffer endure, tolerate bear stand, not press permit of delay, не -ся impf. be impatient #or eager",
"терпимость" : "tolerance",
"терпимый" : "tolerant, bearable",
"терпкий" : "tart",
"терпкость" : "acerbity",
"терраса" : "terrace",
"территориальный" : "territorial",
"территория" : "territory",
"террор" : "terror",
"терроризировать" : "im terrorize",
"терроризовать" : "im terrorize",
"тертый" : "cunning sly",
"тертый калач" : "famil. cunning fellow",
"терьер" : "terrier",
"терять" : "lose, waste, shed, give up",
"терять из виду" : "lose sight of",
"теряться" : "be lost, disappear vanish, become embarrassed be at a loss",
"тесать" : "hew cut",
"теснить" : "press, oppress",
"тесниться" : "crowd throng, jostle",
"теснота" : "narrowness, throng",
"тесный" : "narrow, tight, close, intimate",
"тесто" : "dough paste",
"тестообразный" : "doughy, pasty",
"тесть" : "father-in-law",
"тесьма" : "tape",
"тетерев" : "black grouse blackcock",
"тетеря" : "глухая тетеря; See also: сонная тетеря",
"тетушка" : "auntie",
"тетя" : "aunt",
"техника" : "technics, technique",
"технический" : "technical",
"технологический" : "technological",
"технология" : "technology",
"течение" : "current, stream, course, fig. trend, movement",
"течка" : "oestrus",
"течь" : "flow run, stream, move, leak, leak",
"тешить" : "amuse, please",
"тешиться" : "amuse o.s., take comfort, banter",
"теща" : "mother-in-law",
"тибетец" : "Tibetan",
"тигель" : "crucible",
"тигр" : "tiger",
"тигрица" : "tigress",
"тик" : "tic, ticking",
"тиканье" : "tick",
"тикать" : "tick",
"тимофей" : "Timothy",
"тимьян" : "thyme",
"тина" : "ooze",
"тинистый" : "oozy",
"тип" : "type, famil. character",
"типичный" : "typical",
"типография" : "printing plant #or office",
"типографский" : "printing, printer's",
"типология" : "typology",
"тир" : "shooting gallery rifle range",
"тирада" : "tirade",
"тираж" : "circulation, drawing",
"тиран" : "tyrant",
"тиранить" : "tyrannize",
"тирания" : "tyranny",
"тиранство" : "tyranny",
"тире" : "dash",
"тискать" : "squeeze press, print",
"тиски" : "vice grip, famil. fix",
"тисненый" : "printed",
"тиснуть" : "squeeze press, print",
"титан" : "titan, titanium",
"титанический" : "titanic",
"титул" : "title",
"титулованный" : "titled, titular",
"титульный" : "title",
"тиф" : "typhus",
"тихий" : "quiet still, calm, soft gentle, slow, commerc. dull flat, cap. Pacific",
"тихомолком" : "famil. on the quiet",
"тише" : "silence!",
"тишина" : "calm, silence",
"тк" : "cf. так",
"тканый" : "woven",
"ткань" : "cloth, fabric, tela, tissue, woof",
"ткацкий" : "weaving",
"тмин" : "caraway, cumin, cummin",
"товарищ" : "companion, comrade, mate",
"товарищ по школе" : "schoolmate",
"товарищеский" : "friendly, companionable",
"товарищество" : "comradeship fellowship, partnership, association company",
"товарный" : "ware, goods..., Brt. goods...",
"товарообмен" : "barter",
"товарооборот" : "commodity circulation",
"товары" : "goods, merchandise",
"тогда" : "then at that time; See also: тогда как",
"тогда как" : "whereas while",
"тогдашний" : "of that time then",
"тождественный" : "identical",
"тождество" : "identity",
"тоже" : "also too as well, cf. также",
"той же монетой" : "in a pers.'s own coin",
"ток" : "current, floor",
"токарный" : "turner's, turning",
"токарь" : "turner",
"токсин" : "toxin",
"толк" : "sense, use, judgment, famil. talk rumor, obsol. doctrine, sect; See also: знать толк в",
"толкать" : "push shove thrust, fig. induce prompt, famil. urge on spur",
"толкаться" : "push, famil. knock",
"толкнуть" : "push shove thrust, fig. induce prompt, famil. urge on spur",
"толкователь" : "commentator",
"толковать" : "истолковать interpret expound explain, comment, take, потолковать famil. talk, speak tell say",
"толковый" : "explanatory commenting, famil. sensible smart wise",
"толком" : "= толково, a. in earnest",
"толкотня" : "crush crowd",
"толкучка" : "second-hand market",
"толокно" : "oat flour",
"толочь" : "pound",
"толочься" : "popul. hang about",
"толпа" : "crowd throng, mob, swarm",
"толпиться" : "crowd throng, mob, swarm",
"толстеть" : "grow stout",
"толстокожий" : "thick-skinned",
"толстый" : "thick, large big, stout fat",
"толстяк" : "fat man",
"толуол" : "toluene",
"толченый" : "pounded",
"толчея" : "crush crowd",
"толчок" : "push, shock, jolt, fig. impulse",
"толщина" : "thickness, stoutness; See also: толщиной в",
"толщиной в" : "... в толщину ... thick",
"толь" : "roofing felt",
"только" : "only but; See also: как только, лишь только, едва только, только бы, только что",
"только бы" : "if only",
"только что" : "just",
"только-только" : "famil. barely",
"том" : "volume",
"томат" : "tomato",
"томительный" : "painful tormenting, oppressive",
"томить" : "torment plague harass pester, pinch oppress",
"томиться" : "pine  languish",
"томление" : "languor",
"томность" : "languor",
"томный" : "languishing",
"томограф" : "tomograph"
};
