var dicctr_37 = {
"лектор" : "lecturer",
"лекция" : "lecture",
"лелеять" : "cherish fondle",
"лемех" : "plowshare",
"лен" : "flax",
"лена" : "lena",
"ленивец" : "s. лентяй",
"ленивица" : "s. лентяйка",
"ленивый" : "lazy idle, sluggish",
"ленинград" : "Leningrad",
"ленинградец" : "Leningrader",
"ленинец" : "Leninist",
"ленинский" : "Leninist",
"лениться" : "be lazy",
"лента" : "ribbon, band, engin. tape",
"ленточный" : "ribbon",
"лентяй" : "lazybones",
"лентяйка" : "lazybones",
"лентяйничанье" : "loll",
"лентяйничать" : "idle",
"лень" : "laziness idleness, listlessness, мне лень",
"леопард" : "leopard",
"лепесток" : "petal",
"лепет" : "babble prattle",
"лепетать" : "babble prattle",
"лепешка" : "scone, lozenge",
"лепить" : "sculpture model mold, famil. налепить stick",
"лепка" : "modeling molding, famil. sculpture",
"лепной" : "plastic",
"лепта" : "mite",
"лес" : "wood forest, lumber Brt. timber, pl. scaffold",
"леса" : "line",
"лесистый" : "woody wooded",
"леска" : "s. леса",
"лесник" : "ranger",
"лесничество" : "forest district",
"лесничий" : "forester",
"лесной" : "forest..., wood, lumber..., Brt. timber...",
"лесной орех" : "hazel",
"лесоводство" : "forestry",
"лесом" : "through a wood, как в лесу fig. at sea",
"лесоматериалы" : "timber",
"лесонасаждение" : "afforestation, forested tract, wood",
"лесопилка" : "sawmill",
"лесопильный" : "sawmill",
"лесопильный завод" : "sawmill",
"лесопильня" : "sawmill",
"лесоруб" : "lumberman woodcutter",
"лесс" : "loess",
"лестница" : "stairs pl. staircase, ladder, fig. scale",
"лестный" : "flattering",
"лесть" : "flattery",
"лет" : "flight, на лету in the air on the wing, fig. in haste, instantly quickly",
"лета" : "s. лето, a. год",
"летаргический" : "lethargic",
"летаргия" : "lethargy",
"летательный" : "flying",
"летать" : "fly",
"лететь" : "fly",
"летная дорожка" : "av. runway",
"летний" : "summer...",
"летный" : "flying, run...",
"лето" : "summer, pl. years age, сколько вам лет? how old are you?; See also: в летах",
"летописец" : "chronicler",
"летопись" : "chronicle",
"летосчисление" : "chronology, era",
"летучая мышь" : "zo. bat",
"летучий" : "flying, fleeting, offhand short, chem. volatile",
"летучий листок" : "leaflet",
"летучка" : "leaflet",
"летчик" : "aviator flier pilot airman",
"летчица" : "aviator flier pilot airman",
"лечебница" : "clinic hospital",
"лечебный" : "medical",
"лечение" : "treatment",
"лечить" : "treat",
"лечиться" : "undergo treatment be treated, treat",
"лечь" : "s. ложиться, a. лежать",
"леший" : "satyr, popul. Old Nick",
"лещ" : "zo. bream",
"лещина" : "filbert",
"лже" : "false, pseudo...",
"лживость" : "inveracity, mendacity",
"лживый" : "double-tongued, mendacious",
"либеральный" : "liberal",
"либерия" : "liberia",
"либидо" : "libido",
"либретто" : "libretto, wordbook",
"ливан" : "lebanon",
"ливанский" : "lebanese",
"ливень" : "downfall, downpour, hailstorm, rainfall",
"ливерпуль" : "liverpool",
"ливия" : "libya",
"ливрея" : "livery",
"лига" : "league",
"лиза" : "Liz Lise",
"лизать" : "lick",
"ликвидировать" : "closeout, liquidate",
"ликер" : "liqueur",
"ликование" : "chortle, jubilation",
"ликовать" : "exult",
"ликующий" : "exultant, gleeful, jubilant",
"лилейный" : "lily",
"лилипут" : "lilliputian",
"лиловато-синий" : "livid",
"лимон" : "lemon",
"лимонад" : "lemonade",
"лимонный" : "citric, lemony",
"лимузин" : "limousine",
"лимфа" : "lymph",
"линейный" : "lineal, linear",
"линза" : "lens",
"линзовидный" : "lenticular",
"линия" : "line",
"линовать" : "rule",
"линолеум" : "lino, linoleum",
"линотип" : "linotype",
"линч" : "закон Линча; See also: суд Линча",
"линять" : "exuviate, molt",
"липа" : "linden",
"липкий" : "adhesive, sticky, tacky",
"липнуть" : "clung",
"лира" : "lira, lyra",
"лирический" : "lyric, lyrical",
"лисий" : "foxy",
"лисица" : "fox, tod",
"лиссабон" : "lisbon",
"лист" : "leaf",
"листва" : "foliage, leafage",
"лиственница" : "larch",
"лиственный" : "foliose leafy, deciduous",
"листик" : "dim. #of лист",
"листовка" : "pol. leaflet",
"листовой" : "leaf, sheet..., folio...",
"листок" : "dim. #of лист",
"листопадный" : "deciduous",
"литва" : "Lithuania",
"литейная" : "литейный завод",
"литейный" : "литейный завод",
"литерал" : "lit",
"литература" : "literature",
"литературный" : "literary",
"литий" : "lithium",
"литография" : "lithograph, lithography",
"литой" : "cast",
"литология" : "lithology",
"литосфера" : "lithosphere",
"литр" : "liter",
"литургия" : "liturgy",
"лить" : "pour, shed, engin. cast, дождь льет как из ведра, it's raining cats and dogs",
"литье" : "founding cast",
"литься" : "flow pour, spread, sound",
"лифт" : "elevator Brt. lift",
"лифтер" : "elevator boy Brt. lift man",
"лифчик" : "waist bodice, bra",
"лихоимец" : "usurer, bribe taker",
"лихой" : "bold daring, dashing, nimble, smart",
"лихорадка" : "fever, hives",
"лихорадочный" : "feverish",
"лихость" : "bravery, smartness",
"лицевать" : "face, turn",
"лицевой" : "face..., front..., right",
"лицемер" : "hypocrite",
"лицемерие" : "hypocricy",
"лицемерить" : "dissemble",
"лицемерный" : "hypocritical",
"лицензия" : "license",
"лицо" : "face, countenance, front, person individual, a. действующий; See also: в лицо, от лица, лицом к лицу, быть к лицу, нет лица",
"лицом к лицу" : "face to face",
"личина" : "mask guise",
"личинка" : "larva, maggot",
"личность" : "personality, identity",
"личный" : "personal",
"лишай" : "bot. lichen, med. herpes",
"лишайник" : "lichen",
"лишать" : "deprive bereave strip; See also: лишать жизни, лишать себя жизни, лишенный",
"лишать жизни" : "commit murder",
"лишать себя жизни" : "commit suicide",
"лишаться" : "lose; See also: лишиться чувств",
"лишение" : "privation, loss, pl. privations hardships; See also: лишение прав, лишение свободы",
"лишение прав" : "disfranchisement",
"лишение свободы" : "imprisonment",
"лишенный" : "a. devoid of lack",
"лишить" : "deprive bereave strip; See also: лишать жизни, лишать себя жизни, лишенный",
"лишиться" : "lose; See also: лишиться чувств",
"лишиться чувств" : "faint",
"лишнее" : "undue  too much, ... с лишним over ...",
"лишний" : "superfluous odd excessive over... sur..., spare, extra, needless unnecessary, outsider",
"лишний раз" : "once again, не лишне inf. had better",
"лишь" : "only, merely just, as soon as no sooner ... than hardly; See also: лишь бы",
"лишь бы" : "if only",
"лишь только" : "no sooner ... than",
"лоб" : "forehead",
"лобзик" : "fret saw",
"лобный" : "milit. frontal",
"лобовой" : "milit. frontal",
"ловелас" : "lovelace",
"ловить" : "catch, trap, grasp seize; See also: поймать на слове",
"ловкий" : "dexterous adroit deft",
"ловкость" : "adroitness dexterity",
"ловля" : "catching, fishing",
"ловушка" : "trap, snare",
"логарифм" : "logarithm",
"логик" : "logician",
"логика" : "logic",
"логистический" : "logistic",
"логический" : "logical",
"логичный" : "logical",
"логовище" : "lair den",
"логово" : "lair den",
"лодка" : "boat",
"лодочник" : "boatman",
"лодыжка" : "ankle",
"лодырь" : "idler loafer",
"ложа" : "thea. box, lodge, stock",
"ложбина" : "hollow",
"ложе" : "couch bed, stock",
"ложиться" : "lie down, ~ в go to, fall",
"ложка" : "spoon",
"ложный" : "false",
"ложный путь" : "wrong tack",
"ложь" : "lie falsehood",
"лоза" : "vine, switch bot.",
"лозунг" : "slogan watchword",
"локализовать" : "pf. localize",
"локаут" : "shutout",
"локомотив" : "locomotive engine",
"локон" : "curl lock",
"локоть" : "elbow",
"лом" : "crowbar pry, scrap",
"ломаный" : "broken",
"ломать" : "break, pull  tear; See also: ломать голову",
"ломать голову" : "rack one's brains",
"ломаться" : "break, popul. clown jest, mince be prim",
"ломбард" : "pawnshop",
"ломбардский" : "lombard",
"ломить" : "famil. = ломать, impers. ache feel a pain in",
"ломиться" : "bend burst, famil. force  break",
"ломка" : "breaking",
"ломкий" : "brittle fragile",
"ломовой" : "breaking, scrap..., cart...",
"ломота" : "acute pains pl.",
"ломоть" : "slice",
"ломтик" : "dim. #of ломоть",
"лондон" : "london",
"лоно" : "lap, bosom",
"лопасть" : "blade, vane fan",
"лопата" : "shovel spade",
"лопатка" : "dim. #of лопата, shoulder blade",
"лопаточный" : "scapular"
};
