var dicctr_94 = {
"хек" : "hake",
"хельсинки" : "helsinki",
"херес" : "sherry",
"херувим" : "cherub",
"хижина" : "hut cabin",
"хилый" : "sickly",
"химера" : "chimera",
"химик" : "chemist",
"химиотерапия" : "chemotherapy",
"химический" : "chemical, indelible #or copying-ink",
"химия" : "chemistry",
"хинин" : "quinine",
"хиппи" : "hippie, hippy",
"хиреть" : "weaken grow sickly",
"хиросима" : "hiroshima",
"хирург" : "surgeon",
"хирургический" : "surgical",
"хирургия" : "surgery",
"хитрец" : "cunning fellow dodger",
"хитрить" : "dodge, fox, quibble, cf. мудрить",
"хитрость" : "craft cunning, artifice ruse trick, stratagem",
"хитроумный" : "catchy",
"хитрый" : "cunning crafty sly artful, ingenious",
"хихиканье" : "chuckle, giggle",
"хихикать" : "chuckle giggle titter",
"хищение" : "embezzlement",
"хищник" : "beast of prey",
"хищный" : "rapacious predatory, of prey",
"хладнокровие" : "composure",
"хладнокровный" : "cool calm",
"хлам" : "trash stuff lumber",
"хлеб" : "bread, loaf, grain Brt. corn, livelihood, pl. cereals",
"хлебать" : "drink sip, popul. eat",
"хлебнуть" : "drink sip, popul. eat",
"хлебные злаки" : "pl. cereals",
"хлебный" : "grain... corn... cereal, bread..., baker's, famil. profitable",
"хлебопекарня" : "bakery",
"хлебосольный" : "hospitable",
"хлебосольство" : "hospitality",
"хлеб-соль" : "hospitality",
"хлев" : "shed, cote, sty",
"хлестать" : "lash whip beat, splash, gush spurt, pour",
"хлестнуть" : "lash whip beat, splash, gush spurt, pour",
"хлипать" : "sob",
"хлоп" : "crack! plop!, a. хлопать",
"хлопок" : "cotton",
"хлопотный" : "troublesome",
"хлопушка" : "slapstick",
"хлопьевидный" : "flaky",
"хлопья" : "flake",
"хлор" : "chlorine",
"хлористоводородный" : "muriatic",
"хлористый" : "... chloride",
"хлорный" : "chloric",
"хлорофилл" : "chlorophyll",
"хлороформ" : "pf. chloroform",
"хлороформировать" : "pf. chloroform",
"хлынуть" : "pf. gush, rush, pour in torrents",
"хлыст" : "horsewhip, switch",
"хлюпанье" : "squelch",
"хлюпать" : "squelch",
"хмель" : "hop, intoxication; See also: во хмелю",
"хмельной" : "intoxicated, intoxicating",
"хмурить" : "knit",
"хмуриться" : "frown scowl, be overcast",
"хмурый" : "gloomy sullen, cloudy",
"хныканье" : "whimper, whine",
"хныкать" : "whine snivel",
"хобот" : "zo. trunk",
"ход" : "motion, speed, pace, course, passage, walk, a. action movement, stroke, entrance, access, lead, move, turn, vogue currency, в ходу a. = ходкий, на ходу etc., famil. in progress; See also: пустить в ход, все ходы и выходы",
"ходатай" : "intercessor advocate",
"ходатайство" : "intercession, petition",
"ходатайствовать" : "intercede, petition",
"ходить" : "go, walk, sail, run ply, move, visit attend, circulate, wear, look after take care of nurse, tend, hunt, lead, famil. be current, ease o.s.",
"ходить по миру" : "go begging",
"ходкая книга" : "best seller",
"ходкий" : "marketable salable, current, famil. quick easygoing; See also: ходкая книга",
"ходульный" : "stilted",
"ходьба" : "walking, walk",
"ходячий" : "current, trivial, famil. walking",
"хождение" : "going walking, circulation",
"хозяева" : "= хозяин & хозяйка",
"хозяин" : "master owner, boss principal, landlord, host, innkeeper, manager, farmer",
"хозяйка" : "mistress, landlady, hostess, housewife",
"хозяйничать" : "keep house, manage, make o.s. at home",
"хозяйственный" : "economic, thrifty",
"хозяйство" : "economy, household, farm",
"хоккей" : "hockey",
"холера" : "cholera",
"холестерин" : "cholesterin, cholesterol",
"холить" : "groom care for fondle",
"холка" : "withers",
"холм" : "hill",
"холмистый" : "hilly",
"холод" : "cold, chill, pl. cold",
"холодеть" : "grow cold chill",
"холодец" : "= студень",
"холодильник" : "refrigerator",
"холодность" : "coldness",
"холодный" : "cold, & fig. frigid, холодно it is cold",
"холоп" : "bondman, famil. toady",
"холостой" : "single unmarried, bachelor, blank, engin. idle",
"холостяк" : "bachelor",
"холст" : "linen, canvas",
"холуй" : "cad, toady",
"хомут" : "collar",
"хомяк" : "hamster",
"хор" : "chorus, choir",
"хорват" : "Croat",
"хорватка" : "Croat",
"хорватский" : "Croatian",
"хорек" : "polecat fitch",
"хореография" : "choreography",
"хористка" : "chorine",
"хоровод" : "round dance",
"хоронить" : "bury",
"хорош гусь" : "famil. a fine fellow indeed!",
"хорошенький" : "pretty",
"хорошенько" : "famil. properly",
"хорошеть" : "grow prettier",
"хороший" : "good, fine nice, pretty good-looking handsome",
"хорошо" : "well, #mark: good B, all right! O.K.! good!, мне хорошо I am well off, хорошо вам it is very well for you to ...",
"хорошо провести время" : "have a good time",
"хотеть" : "want wish, я хотел бы I would like, я хочу чтобы вы  pt. I want you to ...; See also: хочешь не хочешь",
"хотеться" : ": мне хочется I'd like, a. = хотеть",
"хоть" : "at least, even, if only, ~ ... хоть whether ... whether or, if you please, so much etc. that, any ..., I wish I could, a. хотя; See also: хоть бы и так, хоть убей",
"хоть бы и так" : "even if it be so",
"хоть куда" : "popul. tiptop smart, cf. ни",
"хоть убей" : "for the life of me",
"хотя" : "although though, a. хоть; See also: хотя бы",
"хотя бы" : "even though, if",
"хохол" : "tuft, crest, forelock, contp. Ukrainian",
"хохот" : "laughter roar",
"хохотать" : "roar",
"хочешь не хочешь" : "willy-nilly",
"храбрец" : "brave",
"храбрость" : "valor bravery",
"храбрый" : "brave valient",
"храм" : "eccl. temple",
"хранение" : "keeping, storage; See also: камера хранения ручного багажа",
"хранилище" : "storehouse, archives pl.",
"хранитель" : "keeper guardian, custodian",
"хранить" : "keep, store, preserve, observe, guard",
"храп" : "snore, snort",
"храпеть" : "snore, snort",
"хребет" : "anat. spine, range",
"хрен" : "horseradish",
"хризолит" : "chrysolite",
"хрип" : "rattle",
"хрипение" : "rattle",
"хрипеть" : "rattle, be hoarse, famil. speak hoarsely",
"хриплый" : "hoarse husky",
"хрипнуть" : "become hoarse",
"хрипота" : "hoarseness, husky voice",
"христианин" : "Christian",
"христианка" : "Christian",
"христианский" : "Christian",
"христианство" : "Christianity",
"христов" : "Christ's",
"христос" : "Christ",
"хром" : "chromium, chrome",
"хроматический" : "chromatic",
"хромать" : "limp, be lame",
"хромовый" : "chromic",
"хромой" : "lame",
"хромосома" : "chromosome",
"хромота" : "lameness",
"хроника" : "chronicle, current events, newsreel",
"хронический" : "chronic",
"хронологический" : "chronological",
"хронология" : "chronology",
"хрупкий" : "brittle fragile, frail infirm",
"хрупкость" : "frailty",
"хруст" : "crackle, crunch",
"хрусталь" : "crystal",
"хрустальный" : "crystal...",
"хрустеть" : "crunch",
"хрустящий" : "crisp, crunchy",
"хрущ" : "cockchafer",
"хрюкать" : "grunt",
"хрюкнуть" : "grunt",
"хрящ" : "cartilage",
"хрящевой" : "cartilaginous, gristly",
"худеть" : "grow thin",
"худо" : "evil, a. худой",
"художественный" : "artistic, art..., of art, belles, applied",
"художество" : "art",
"художник" : "artist, painter",
"худой" : "thin lean scrawny, bad evil",
"худощавый" : "scrawny",
"худшее" : "worse",
"худший" : "worse worst, cf. лучший",
"хуже" : "worse, & тот",
"хулиган" : "rowdy hooligan",
"хулиганский" : "ruffian",
"хулиганство" : "mugging",
"хурма" : "persimmon",
"хутор" : "farm, hamlet",
"цапать" : "snatch",
"цапля" : "heron",
"цапнуть" : "snatch",
"царапать" : "scratch",
"царапина" : "scratch",
"царапнуть" : "scratch",
"царевич" : "czarevitch, prince",
"царевна" : "princess",
"царить" : "reign, prevail",
"царица" : "czarina, empress, fig. queen",
"царский" : "of the czar czarist, imperial",
"царство" : "empire, kingdom, rule, царствование",
"царствование" : "reign",
"царствовать" : "reign rule, prevail",
"царь" : "czar emperor, king",
"цвести" : "bloom blossom",
"цвет" : "color; See also: цвет лица, защитного цвета",
"цвет лица" : "complexion",
"цветение" : "flowering",
"цветистый" : "florid",
"цветная капуста" : "cauliflower",
"цветник" : "flower bed",
"цветной" : "colored, variegated, nonferrous, technicolor; See also: цветная капуста",
"цветок" : "flower",
"цветочник" : "florist",
"цветочница" : "florist Brt. flower girl",
"цветочный" : "flower...",
"цветущий" : "flowering, flourishing, prime",
"цедить" : "процедить strain pass filter, famil. murmur utter, выцедить draw",
"цедра" : "citron",
"цезий" : "cesium",
"цейлон" : "Ceylon",
"цейхгауз" : "arsenal",
"целебный" : "curative medicinal",
"целевой" : "special for a specified purpose purposeful, principal",
"целесообразный" : "expedient",
"целеустремленный" : "purposeful",
"целиком" : "entirely wholly",
"целина" : "virgin soil",
"целительный" : "salutary curative",
"целить" : "aim",
"целлофан" : "cellophane",
"целовать" : "kiss",
"целое" : "unit",
"целомудренный" : "chaste",
"целостность" : "integrity",
"целый" : "livelong, total, whole",
"цель" : "goal, purpose, target",
"цельный" : "integral",
"цемент" : "cement",
"цена" : "price",
"цензура" : "censorship"
};
