var dicctr_11 = {
"воскресение" : "Resurrection",
"воскресенье" : "Sunday",
"воскресить" : "resuscitate revive",
"воскреснуть" : "rise, recover, Христос воскрес! Christ has arisen!, воистину воскрес! truly arisen!",
"воскрешать" : "resuscitate revive",
"воспаление" : "inflammation, воспаление легких pneumonia",
"воспаленный" : "inflamed",
"воспалительный" : "inflammatory",
"воспалить" : "inflame",
"воспалять" : "inflame",
"воспарять" : "levitate",
"воспевать" : "sing of praise",
"воспеть" : "sing of praise",
"воспитание" : "education upbringing",
"воспитанник" : "foster child, pupil",
"воспитанница" : "foster child, pupil",
"воспитанный" : "well-bred, плохо воспитанный ill-bred",
"воспитатель" : "educator, tutor",
"воспитательный" : "educational pedagogic",
"воспитать" : "bring up, educate",
"воспитывать" : "bring up, educate",
"воспламенение" : "inflammation",
"воспламенить" : "inflame",
"воспламенять" : "inflame",
"восполнить" : "fill, make up",
"восполнять" : "fill, make up",
"воспользоваться" : "s. пользоваться",
"воспоминание" : "remembrance recollection reminiscence, a. memoirs",
"воспрепятствовать" : "hinder prevent",
"воспретить" : "prohibit forbid, вход воспрещен! no entrance!, курить воспрещается! no smoking",
"воспрещать" : "prohibit forbid, вход воспрещен! no entrance!, курить воспрещается! no smoking",
"воспрещение" : "interdiction prohibition",
"восприимчивый" : "sensitive, susceptible",
"воспринимать" : "take, conceive",
"воспринимающий" : "perceptive, percipient",
"воспринять" : "take, conceive",
"восприятие" : "perception",
"воспроизведение" : "reproduction",
"воспроизвести" : "reproduce",
"воспроизводить" : "reproduce",
"воспротивиться" : "oppose object",
"воспрянуть" : "pf. rise jump up; See also: воспрянуть духом",
"воспрянуть духом" : "cheer up",
"воспылать" : "blaze flare  flame, glow burn, rage",
"воссоединение" : "reunion",
"воссоединить" : "reunite",
"воссоединять" : "reunite",
"восставать" : "rise, revolt",
"восставший" : "insurgent, revolted",
"восстанавливать" : "reconstruct restore, stir up dispose",
"восстание" : "insurrection revolt",
"восстановить" : "reconstruct restore, stir up dispose",
"восстановление" : "reconstruction restoration",
"восстать" : "rise, revolt",
"восток" : "east, Восток the East Orient; See also: Ближний Восток, Дальний Восток, на восток, на востоке, с востока, к востоку от",
"восторг" : "delight rapture, я в восторге I am delighted, приводить в восторг = восторгать",
"восторгать" : "impf. delight",
"восторженный" : "enthusiastic, rapturous",
"восточный" : "east, easterly, eastern, easterner, orient",
"восхитительный" : "delightful",
"восхитить" : "delight transport",
"восхититься" : "be delighted  admire",
"восхищать" : "delight transport",
"восхищаться" : "be delighted  admire",
"восхищение" : "admiration delight, приводить в восхищение s. восхищать",
"восхищенный" : "rapt",
"восход" : "rise, ascent",
"восход солнца" : "sunrise",
"восходить" : "rise ascend",
"восходящий" : "ascendant, ascending, upcast, uprise, upward",
"восхождение" : "rise, ascent",
"восшествие" : "ascent; See also: восшествие на престол",
"восшествие на престол" : "accession to the throne",
"восьмерка" : "eight",
"восьмеро" : "eight",
"восьмигранник" : "octahedron",
"восьмигранный" : "octahedral",
"восьмидесятилетний" : "octogenarian",
"восьмидесятый" : "eightieth, cf. пятый",
"восьмилетний" : "of eight aged 8",
"восьмиричный" : "octal",
"восьмисотый" : "eight hundredth",
"восьмиугольный" : "octagon, octagonal",
"восьмичасовой" : "eight-hour...",
"восьмой" : "eight, cf. пятый",
"восьмушка" : "eighth of lb., octavo",
"вот" : "here, there, now, well, that's ...; See also: вот и все, вот как{!}, вот те раз{!}, вот какой {...}, вот человек{!}, вот-вот",
"вот и все" : "famil. that's all",
"вот как" : "(что!} you don't say! is that so?",
"воткнуть" : "s. втыкать",
"вотум" : "vote",
"вотчина" : "patrimony",
"воцариться" : "accede to the throne, set in, be restored",
"воцаряться" : "accede to the throne, set in, be restored",
"вошь" : "louse",
"вощить" : "wax",
"воэдерживаться" : "forborne",
"воюющий" : "belligerent",
"впадать" : "fall in",
"впадать в крайности" : "go #or run to extremes",
"впадение" : "flowing into, mouth confluence",
"впадина" : "cavity socket",
"впалый" : "hollow sunken",
"впасть" : "fall in",
"впервые" : "for the first time",
"вперегонки" : "s. наперегонки",
"вперед" : "forward ahead  on, in future, in advance beforehand, a. зад",
"впереди" : "in front ahead before",
"вперемежку" : "famil. alternately",
"вперить" : "fix",
"вперять" : "fix",
"впечатление" : "impression",
"впечатлительный" : "sensitive",
"впивать" : "suck in imbibe",
"впиваться" : "cling to, seize, stick, fix",
"вписать" : "enter insert",
"вписывать" : "enter insert",
"впитать" : "soak up #or in, absorb imbibe",
"впитывание" : "absorption, soaking",
"впитывать" : "soak up #or in, absorb imbibe",
"впить" : "suck in imbibe",
"впиться" : "cling to, seize, stick, fix",
"впихивать" : "push #or squeeze in",
"впихнуть" : "push #or squeeze in",
"вплавь" : "by swimming",
"вплести" : "interlace braid",
"вплетать" : "interlace braid",
"вплотную" : "close by up to, famil. seriously",
"вплоть" : "up to, even",
"вполголоса" : "in a low voice",
"вползать" : "creep #or crawl in up",
"вползти" : "creep #or crawl in up",
"вполне" : "quite fully entirely",
"впопад" : "famil. to the point relevantly",
"впопыхах" : "s. второпях",
"впору" : "быть впору",
"впрыгивать" : "jump in #or on",
"впрыгнуть" : "jump in #or on",
"впрыскивание" : "injection",
"впрыскивать" : "inject",
"впрыснуть" : "inject",
"впрягать" : "harness put to",
"впрячь" : "harness put to",
"впуск" : "admission",
"впускать" : "let in admit",
"впускной" : "inlet, intake",
"впустить" : "let in admit",
"впустую" : "famil. in vain to no purpose",
"впутать" : "entangle involve",
"впутаться" : "become entangled",
"впутывать" : "entangle involve",
"впутываться" : "become entangled",
"впятеро" : "five times",
"впятером" : "five",
"враг" : "enemy, obsol. devil",
"вражда" : "enmity",
"враждебность" : "animosity",
"враждебный" : "hostile",
"враждовать" : "be at enmity",
"вражеский" : "enemy...",
"вражий" : "enemy...",
"вразброд" : "famil. separately scatteringly",
"вразрез" : "идти вразрез",
"врать" : "lie, make a mistake, be inaccurate, tell",
"врач" : "doctor physician",
"врачебный" : "medical",
"вращательный" : "gyratory, rotary, rotative, rotatory",
"вращать" : "turn revolve rotate",
"вращающийся" : "revolving rotatory",
"вращение" : "rotation",
"вред" : "harm damage, detriment",
"вредитель" : "farm. pest, saboteur",
"вредительство" : "sabotage",
"вредить" : "harm damage",
"вредный" : "harmful injurious",
"врезать" : "cut in, lay #or put in, -ся run in, project into, impress",
"временами" : "from time to time now and then sometimes",
"временный" : "temporary transient provisional",
"временщик" : "favorite minion",
"время" : "time, gr. tense, weather; See also: время года, во время, в настоящее время, от времени до времени, по временам, временами, в скором времени, в то время, в то же время, в то время как, за последнее время, на время, со временем, тем временем, сколько времени{?}, хорошо провести время",
"время года" : "season",
"времяисчисление" : "chronology",
"времяпровождение" : "pastime",
"врожденный" : "bred, confound, connate, connatural, inbred",
"вросший" : "ingrown",
"вруб" : "kerf",
"вручать" : "deliver, give in",
"вручение" : "committal",
"всадник" : "cavalier, horseman, rider",
"всадница" : "equestrienne, horsewoman",
"всасывание" : "imbibition, inflow, resorption",
"всасывать" : "absorb, adsorb",
"всасывающий" : "suction",
"все" : "adj. all the whole, full life, all over, everything a. everybody, лучше всего best of all the best, при всем том #or со всем тем for all that, во всем мире all over the world, по всей стране throughout the country, всего хорошего! good luck!, во всю s. сила, все adv. always all the time, only just, все не not yet, все больше more and more, все же nevertheless yet",
"все до одного" : "all to a man",
"все еще" : "still",
"все как один" : "all to a man",
"все ходы и выходы" : "the ins and outs",
"всеведущий" : "omniscient",
"всевозможный" : "of all kinds #or sorts",
"всегда" : "always",
"всегдашний" : "constant habitual",
"всего" : "altogether in all, sum total; See also: всего только, всего лишь, всего-навсего, прежде всего",
"всего доброго" : "good luck!",
"всезнающий" : "omniscient",
"вселенная" : "universe",
"вселить" : "settle move in, fig. inspire",
"вселять" : "settle move in, fig. inspire",
"всем телом" : "all over",
"всемерно" : "in every possible way",
"всемерный" : "every ... possible",
"всемирный" : "world... universal",
"всемогущий" : "= всесильный",
"всенародно" : "in public",
"всенародный" : "national nation-wide, всенародно",
"всенощная" : "vespers pl.",
"всеобщие выборы" : "pl. general election",
"всеобщий" : "universal general",
"всеобьемлющий" : "universal",
"всероссийский" : "All-Russian",
"всерьез" : "famil. in earnest seriously",
"всесильный" : "omnipotent almighty",
"всесоюзный" : "All-Union... of the U.S.S.R.",
"всесторонний" : "all-round",
"все-таки" : "nevertheless still",
"всеуслышание" : "во всеуслышание",
"всколыхать" : "stir up rouse",
"всколыхивать" : "stir up rouse",
"всколыхнуть" : "stir up rouse",
"вскользь" : "in passing cursorily",
"вскопать" : "dig up",
"вскоре" : "soon before long",
"вскормить" : "raise rear #or bring up",
"вскочить" : "jump #or leap, start, famil. rise #or swell",
"вскрикивать" : "cry out scream",
"вскрикнуть" : "cry out scream",
"вскричать" : "cry out scream",
"вскружить" : "вскружить голову turn a pers.'s head",
"вскрытие" : "baring, dissection",
"вслед" : "after behind following",
"вследствие" : "in consequence of owing to; See also: вследствие этого",
"вследствие этого" : "consequently",
"вслепую" : "famil. blindly at random",
"вслух" : "aloud",
"вслушаться" : "listen attentively",
"вслушиваться" : "listen attentively",
"всматриваться" : "peer look narrowly",
"всмотреться" : "peer look narrowly",
"всмятку" : "яйцо всмятку",
"вспархивать" : "soar"
};
