var dicctr_79 = {
"свищ" : "fistula, crack",
"свобода" : "freedom liberty, на свободу free",
"свободный" : "free, vacant, spare, ready, easy, loose, fluent, exempt",
"свободомыслящий" : "freethinking, su. freethinker liberal",
"свод" : "arch. vault, jur. code",
"сводить" : "lead take, bring, close, reduce, square, contract, remove, drive; See also: свести на нет",
"сводиться" : "come #or amount  result, turn",
"сводка" : "summary, report, communique', typ. revise",
"сводник" : "pander, pimp",
"сводный" : "summary, step...",
"сводня" : "bawd",
"сводчатый" : "vaulted",
"свое" : "my his her its our your their, one's own, peculiar, pl. one's people folks relations, не свой frantic",
"своевольный" : "self-willed wilful",
"своевременный" : "timely",
"своенравный" : "capricious",
"своеобразный" : "original, peculiar",
"свозить" : "take",
"свои" : "my his her its our your their, one's own, peculiar, pl. one's people folks relations, не свой frantic",
"своими силами" : "by o.s.",
"свой" : "my his her its our your their, one's own, peculiar, pl. one's people folks relations, не свой frantic",
"свойственный" : "peculiar, usual",
"свойство" : "property quality, famil. kind",
"сволочь" : "rabble riff-raff, rascal",
"свора" : "pack",
"сворачивать" : "turn",
"своровать" : "steal",
"своротить" : "turn",
"своя" : "my his her its our your their, one's own, peculiar, pl. one's people folks relations, не свой frantic",
"свояченица" : "sister-in-law",
"свыкаться" : "get used",
"свыкнуться" : "get used",
"свысока" : "haughtily",
"свыше" : "from above, over, beyond",
"связанный" : "connected, coupled, tied",
"связать" : "tie bind, knit, crochet",
"связист" : "signalman",
"связка" : "bunch, anat. ligament, cord, gr. copula",
"связный" : "coherent",
"связывание" : "fastening, ligature",
"связывать" : "tie  bind, connect join, unite, associate, teleph. put through connect",
"связываться" : "get into touch contact, associate",
"связывающий" : "communicant, liaison",
"связь" : "tie bond, connection, relation, contact, liaison, milit. signal, communication, post",
"святить" : "consecrate hallow",
"святки" : "Christmastide",
"святой" : "holy, sacred, godly, solemn, Easter, su. saint",
"святость" : "holiness sanctity",
"святотатство" : "sacrilege",
"святоша" : "hypocrite",
"святыня" : "relic, sanctuary",
"священник" : "priest",
"священный" : "holy, sacred",
"сг" : "abbr.: сего года, cf. сей",
"сгибатель" : "flexor",
"сгибать" : "flex, fold",
"сгнивать" : "s. гнить",
"сгнить" : "rot putrefy",
"сговор" : "s. уговор",
"сговориться" : "pf. agree, come to terms",
"сговорчивый" : "compliant amenable",
"сгонять" : "drive",
"сгорание" : "combustion",
"сгорать" : "burn down, perish, die",
"сгорбить" : "stoop bend curve",
"сгореть" : "burn  be on fire, glow gleam, не горит famil. there's no hurry, дело горит famil. the matter is top urgent",
"сгоряча" : "in a temper",
"сгребать" : "rake up, shovel",
"сгрести" : "rake up, shovel",
"сгружать" : "unload",
"сгрузить" : "unload",
"сгруппировать" : "group",
"сгубить" : "destroy ruin, waste",
"сгустить" : "s. сгущать",
"сгусток" : "clot",
"сгущать" : "thicken, condense; See also: сгущать краски",
"сгущать краски" : "exaggerate",
"сгущаться" : "coagulate",
"сдавать" : "deliver hand in, surrender, check register, rent let, deal, return, pass, yield, popul. seem",
"сдаваться" : "surrender, сдается ... ... for rent",
"сдавить" : "squeeze",
"сдавливать" : "squeeze",
"сдать" : "deliver hand in, surrender, check register, rent let, deal, return, pass, yield, popul. seem",
"сдать в багаж" : "check one's baggage Brt. register one's luggage",
"сдать внаймы" : "rent Brt. let",
"сдаться" : "surrender, сдается ... ... for rent",
"сдача" : "surrender, delivery, deal, change, check register",
"сдвиг" : "shift, slide",
"сдвигать" : "move, join, knit",
"сдвинуть" : "move, join, knit",
"сдвоенный" : "geminate",
"сделанный" : "done, made",
"сделать" : "make do; See also: делать нечего",
"сделать вывод" : "draw a conclusion",
"сделаться" : "become grow turn, happen  be going on, что с ним сделалось? what has become of him?",
"сделка" : "bargain transaction deal, arrangement settlement",
"сдельный" : "piece",
"сдержанность" : "reservation, restraint, reticence, self-restraint",
"сдержанный" : "reserved restrained",
"сдержать" : "check restrain, suppress, keep, -ся control o.s.",
"сдерживание" : "coercion",
"сдерживать" : "check restrain, suppress, keep, -ся control o.s.",
"сдирать" : "tear off  strip, flay",
"сдобная булка" : "bun",
"себя" : "herself, itself, myself, ourselves, themselves",
"сев" : "sowing",
"север" : "north, cf. восток",
"северный" : "north, northerly, arctic; See also: Северный Ледовитый океан",
"северный ледовитый океан" : "Arctic Ocean",
"северный олень" : "reindeer",
"северо-восток" : "northeast",
"северо-восточный" : "northeast...",
"северо-запад" : "northwest",
"северо-западный" : "northwest...",
"сегмент" : "segment, somite",
"сего года" : "of this year",
"сегодня" : "today; See also: сегодня утром",
"сегодня вечером" : "tonight",
"сегодня утром" : "this morning",
"сегодняшний" : "today's, this",
"седеть" : "turn gray",
"седиль" : "cedilla",
"седина" : "gray hair, a. fig. great age",
"седлать" : "saddle",
"седло" : "saddle",
"седоволосый" : "gray Brt. grey",
"седой" : "gray Brt. grey",
"седок" : "horseman, passenger",
"седьмой" : "seventh, cf. пятый",
"сезон" : "season",
"сезонный" : "seasonal",
"сей" : "this, cf. пора; See also: сим, при сем, сего года",
"сейм" : "seym",
"сейсмичный" : "seismic",
"сейсмограф" : "seismograph",
"сейсмология" : "seismology",
"сейчас" : "now at present, presently immediately at once, just",
"секанс" : "secant",
"секвойя" : "sequoia",
"секрет" : "secret",
"секретариат" : "secretariat",
"секретарь" : "secretary",
"секретничать" : "be secretive act secretely, whisper",
"секретность" : "secrecy",
"секретный" : "secret, confidential",
"секреты" : "secreta",
"секстет" : "sextet",
"сексуальный" : "sexual",
"секта" : "sect",
"сектантский" : "sectarian",
"сектор" : "sector, sphere branch",
"секторный" : "sector",
"секунда" : "second",
"секундный" : "second...",
"секундомер" : "stop watch",
"секция" : "section",
"селедка" : "herring",
"селезенка" : "anat. spleen",
"селезень" : "drake",
"селен" : "selenium",
"селение" : "settlement colony",
"селитра" : "saltpeter niter Brt. nitre",
"селить" : "s. поселять",
"сельдерей" : "celery",
"сельский" : "bucolic, rural",
"селям" : "salaam",
"сема" : "seme",
"семантический" : "semantic",
"семафор" : "semaphore",
"семейный" : "family..., married",
"семейство" : "family",
"семен" : "Simeon",
"семенить" : "trip mince",
"семенной" : "seed..., seminal",
"семерка" : "seven, cf. двойка",
"семеро" : "seven, cf. двое",
"семестр" : "term semester",
"семечко" : "seed",
"семидесятилетний" : "septuagenarian",
"семидесятый" : "seventieth, cf. пятый",
"семилетка" : "seven-year school",
"семилетний" : "seven-year  of seven",
"семинар" : "seminar",
"семинарий" : "seminar",
"семинария" : "seminary",
"семисотый" : "seven hundredth",
"семитический" : "semitic",
"семнадцатый" : "seventeenth, cf. пятый",
"семнадцать" : "seventeen, cf. пять",
"семь" : "seven, & пятый",
"семьдесят" : "seventy",
"семьсот" : "seven hundred",
"семью" : "seven times",
"семья" : "family",
"семьянин" : "family man",
"семя" : "seed",
"сен" : "sen",
"сенат" : "senate",
"сенатор" : "senator",
"сенаторский" : "senatorial",
"сени" : "hall",
"сено" : "hay",
"сеновал" : "hayloft",
"сенокос" : "haymaking, cf. косилка",
"сенсационный" : "sensational",
"сентиментальный" : "sentimental",
"сентябрь" : "September",
"сень" : "shade, shelter",
"сепаратный" : "separate",
"сепия" : "sepia",
"септический" : "septic",
"сера" : "sulfur, famil. earwax",
"серафим" : "seraph",
"серб" : "Serb",
"сербка" : "Serb",
"сердечнососудистый" : "cardiovascular",
"сердечный" : "cardiac, cordial, hearty",
"сердитый" : "angry, shirty",
"сердить" : "disgruntle",
"сердиться" : "sulk",
"сердце" : "heart",
"серебристый" : "argent, silvery",
"серебро" : "silver",
"середина" : "middle, center, mean",
"сережа" : "dim. #of Сергей",
"сережка" : "catkin, shackle, wattle",
"серенада" : "serenade",
"сержант" : "sergeant",
"серийный" : "serial",
"сернистый" : "sulfur, sulphur",
"серовато-коричневый" : "dun",
"сероватый" : "grayish",
"серология" : "serology",
"серп" : "sickle",
"серповидный" : "crescent, falcate, falciform",
"сертификат" : "certificate",
"серцевина" : "pith",
"серый" : "gray, grey",
"серьга" : "earring",
"серьезный" : "serious",
"сестра" : "sister",
"сети" : "mesh, toils",
"сетка" : "net, el. grid, scale",
"сетовать" : "complain",
"сетчатка" : "retina",
"сетчатый" : "cancellated, reticulate, reticulated",
"сеть" : "net, network",
"сечение" : "section",
"сечь" : "shred, swish",
"сечь1" : "cut  chop hew, cleave"
};
