var dicctr_40 = {
"мертвый" : "dead",
"мертвый час" : "after-dinner rest",
"мерцание" : "twinkle",
"мерцать" : "twinkle",
"мерцая" : "agleam",
"месить" : "knead",
"мессия" : "christ, messiah",
"местами" : "in places here & there",
"мести" : "sweep",
"местность" : "region district locality place",
"местный" : "local",
"местный житель" : "native",
"место" : "place spot, seat, famil. job post, passage, package, a. = местность, общее место commonplace; See also: больное место, задеть за больное место, к месту, не к месту, не на месте, местами",
"местожительство" : "residence",
"местоимение" : "gr. pronoun",
"местонахождение" : "location position",
"местоположение" : "location position",
"местопребывание" : "whereabouts, residence",
"месторождение" : "deposit field",
"месть" : "revenge",
"месяц" : "month, moon; See also: в месяц",
"месячный" : "month's, monthly, moon...",
"металл" : "metal",
"металлист" : "metalworker",
"металлический" : "metal",
"металлография" : "metallography, metalloid",
"металлургия" : "metallurgy",
"метаморфизм" : "metamorphism",
"метаморфоз" : "metamorphose",
"метаморфоза" : "metamorphosis",
"метан" : "methane",
"метание" : "casting, toss",
"метательный" : "missile",
"метать" : "throw, bring forth, keep, baste; See also: метать икру",
"метать икру" : "spawn",
"метаться" : "toss jerk, rush about",
"метафора" : "metaphor, metaphore",
"метелица" : "snowstorm",
"метелка" : "panicle",
"метель" : "snowstorm",
"метеор" : "meteor",
"метеорит" : "meteorite",
"метеорный" : "meteoric",
"метеоролог" : "meteorologist",
"метеорологический" : "meteorological",
"метеорология" : "meteorology",
"метил" : "methyl",
"метионин" : "methionine",
"метить" : "mark, aim drive at mean",
"метка" : "mark",
"метка-заполнитель" : "placeholder",
"меткий" : "well-aimed, good, keen accurate steady, pointed, neat, ready",
"метла" : "broom",
"метнуть" : "throw, bring forth, keep, baste; See also: метать икру",
"метод" : "method",
"методист" : "methodist",
"методический" : "methodic systematic",
"методология" : "methodology",
"метр" : "meter Brt. metre",
"метраж" : "footage",
"метрика" : "certificate of birth, metrics",
"метрический" : "metric",
"метро" : "subway Brt. tube underground",
"метрология" : "metrology",
"метроном" : "metronome",
"метрополитен" : "subway Brt. tube underground",
"мех" : "bellows pl., fur, skin; See also: на меху",
"механизировать" : "pf. mechanize",
"механизм" : "mechanism",
"механик" : "mechanic",
"механика" : "mechanics",
"механист" : "mechanist",
"механический" : "mechanical propelling",
"мехи" : "bellows",
"меховой" : "fur...",
"меховщик" : "furrier",
"меч" : "sword",
"мечеть" : "mosque",
"мечта" : "dream daydream reverie",
"мечтание" : "= мечта, dreaming",
"мечтатель" : "dreamer",
"мечтательно-грустный" : "elegiac",
"мечтательный" : "dreamy",
"мечтать" : "dream",
"мечты" : "reverie",
"мешанина" : "hash",
"мешать" : "размешать stir, смешать перемешать mix mingle, obsol. confuse, помешать disturb, hinder impede prevent, вам не мешает you'd better, -ся meddle interfere, не мешайтесь не в свое дело!, mind your own business!",
"мешкать" : "= медлить",
"мешковатый" : "baggy, clumry",
"мешковина" : "bagging, sackcloth",
"мешок" : "sack bag",
"мешочек" : "pouch, sac",
"мещанин" : "bourgeois Philistine",
"мещанский" : "bourgeois Philistine",
"мещанство" : "petty bourgeoisie lower-middle class, Philistinism Babbittry",
"ми" : "mi",
"миг" : "moment instant",
"мигать" : "blink wink, twinkle",
"мигнуть" : "blink wink, twinkle",
"мигом" : "famil. in a trice",
"мигрант" : "migrant",
"мигрень" : "sick headache",
"мидия" : "mussel",
"мизерный" : "paltry",
"мизинец" : "little finger",
"микенский" : "mycenaean",
"микология" : "mycology",
"микро" : "micro",
"микроб" : "germ, microbe",
"микрокосм" : "microcosm",
"микрон" : "micron",
"микроскопия" : "microscopy",
"микротом" : "microtome",
"микрофон" : "microphone, mike",
"милая" : "honey",
"миленький" : "lovely, dear, darling",
"милитаризм" : "militarism",
"милиционер" : "militiaman, policeman",
"милиция" : "militia, police",
"милли" : "milli",
"миллиард" : "billion Brt. milliard",
"миллиметр" : "millimeter",
"миллион" : "million",
"миллионер" : "millionaire",
"миловать" : "pardon, spare",
"миловидный" : "lovely sweet",
"милорд" : "milord",
"милосердие" : "charity mercy",
"милосердный" : "charitable merciful",
"милостивый" : "gracious kind",
"милостивый государь" : "Sir",
"милостыня" : "alms",
"милость" : "mercy, favor, pardon milit. quarter, kindness, милости просим! welcome!, iron. скажи на милость just imagine",
"милый" : "nice lovely sweet, dear darling",
"миля" : "mile",
"мимеограф" : "mimeograph",
"мимо" : "past by, beside; See also: бить мимо",
"мимолетный" : "fleeting passing",
"мимоходом" : "in passing, incidentally",
"мина" : "mining mine, look air",
"минарет" : "minaret",
"миндалина" : "almond, anat. tonsil",
"миндаль" : "almond",
"миндальничать" : "spoon, trifle",
"минерал" : "mineral",
"минералогия" : "mineralogy",
"миниатюра" : "miniature",
"миниатюрный" : "miniature..., fig. tiny diminutive",
"минимальный" : "minimal",
"минимум" : "minimum",
"министерский" : "ministerial",
"министерство" : "ministry; See also: министерство иностранных дел, министерство внутренних дел",
"министерство внутренних дел" : "Ministry of Internal Affairs, Department of the Interior, Home Office",
"министерство иностранных дел" : "Ministry of Foreign Affairs, State Department, Foreign Office",
"министр" : "minister secretary",
"мини-эвм" : "minicomputer",
"миновать" : "pass, leave out #or aside not enter into, escape, минуло s. исполниться",
"миноносец" : "torpedo boat; See also: эскадренный миноносец",
"минск" : "minsk",
"минувшее" : "su. past",
"минувший" : "su. past",
"минус" : "minus, defect",
"минускул" : "minuscule",
"минута" : "minute, moment instant, сиюминуту at once immediately, at this moment, с минуты на минуту any moment, & пять",
"минутный" : "minute, moment momentary",
"минуть" : "pass, leave out #or aside not enter into, escape, минуло s. исполниться",
"миньон" : "minion",
"миоглобин" : "myoglobin",
"миокард" : "myocardium",
"миоценовый" : "miocene",
"мир" : "peace, world universe, planet, obsol. community; See also: мир во всем мире, ходить по миру, пустить по миру",
"мир во всем мире" : "world peace",
"мираж" : "fata morgana, illusion, mirage",
"мирить" : "reconcile, -ся make it up be reconciled",
"мирный" : "peace... peaceful",
"мировоззрение" : "Weltanschauung world view, ideology",
"мировой" : "world world-wide universal, peaceful peaceable of peace, su. arrangement",
"миролюбивый" : "peaceful, peace loving",
"миросозерцание" : "world view outlook",
"мирра" : "myrrh",
"мирской" : "worldly, common",
"мирт" : "myrtle",
"миряне" : "laity",
"мирянин" : "layman",
"миска" : "dish tureen, bowl",
"мисс" : "miss",
"мисси" : "missy",
"миссионер" : "missionary",
"миссисипи" : "mississippi",
"миссия" : "mission, legation",
"миссури" : "missouri",
"мистика" : "mysticism",
"мистифицировать" : "mystify",
"мистический" : "orphic",
"митя" : "dim. #of Дмитрий",
"миф" : "myth",
"мифический" : "mythic",
"мифология" : "mythology",
"михаил" : "Michael",
"мичиган" : "michigan",
"миша" : "Mike",
"мишень" : "target",
"мишура" : "tinsel spangle",
"мишурный" : "tawdry",
"младенец" : "infant baby",
"младенческий" : "infantile, infantine",
"младенчество" : "infancy",
"младший" : "younger youngest, junior",
"младший сержант" : "corporal",
"млекопитающее" : "mammal",
"млеть" : "die faint sink droop",
"млечный" : "milky",
"мне лень" : "I hate don't want won't",
"мне недосуг" : "I have no time",
"мне нездоровится" : "I feel sick #or ill unwell",
"мне противно" : "a. I hate",
"мнемонический" : "mnemonic",
"мнение" : "opinion",
"мнимый" : "imaginary, supposed pretended would-be sham",
"мнительный" : "suspicious, hypochondriac",
"многие" : "many",
"много" : "much many, a lot of, more",
"многовато" : "famil. rather much",
"многоводный" : "abounding in water deep",
"многогранник" : "polyhedron",
"многогранный" : "many-sided",
"многоженец" : "mormon",
"многоженство" : "polygamy",
"многозначительный" : "significant",
"многозначный" : "of many places #or meanings",
"многократный" : "repeated frequent, math. multiple",
"многолетний" : "longstanding of many years, long-lived, long-term ..., bot. perennial",
"многолюдный" : "crowded, populous, mass ...",
"много-много" : "at most",
"многоножка" : "centipede, millepede, millipede, multiped",
"многообещающий" : "promising",
"многообразный" : "varied manifold",
"многоречивый" : "talkative, wordy",
"многословие" : "verbalism, verbiage",
"многословный" : "talkative, wordy",
"многосторонний" : "many-sided",
"многострадальный" : "long-suffering",
"многотомный" : "voluminous",
"многоточие" : "dots pl.",
"многоуважаемый" : "dear",
"многоугольник" : "polygon",
"многоцветный" : "multicolored",
"многочисленность" : "multiplicity",
"многочисленный" : "numerous",
"многочленный" : "polynomial"
};
