var dicctr_48 = {
"ни с того ни с сего" : "famil. all of a sudden without any visible reason",
"ни то ни се" : "famil. neither fish nor flesh",
"ни тот ни другой" : "neither",
"ни черта" : "famil. nothing at all, never mind!",
"нива" : "field",
"нигде" : "nowhere",
"нигер" : "niger",
"нигерия" : "nigeria",
"нигилизм" : "nihilism",
"нидерландец" : "dutchman",
"нидерланды" : "the Netherlands",
"ниже" : "below beneath under, lower, shorter",
"нижеподписавшийся" : "the undersigned",
"нижнее белье" : "underwear",
"нижний" : "lower, under..., ground #or first",
"низ" : "bottom lower part, a. masses",
"низать" : "string",
"низвергать" : "throw",
"низвергнуть" : "throw",
"низвержение" : "throw",
"низина" : "hollow lowland",
"низкий" : "low, mean base, short",
"низкопоклонник" : "groveler",
"низкопоклонничать" : "grovel fawn cringe",
"низкопробный" : "punk",
"низменность" : "lowland plain",
"низменный" : "low",
"низовой" : "lower, local",
"низовье" : "lower",
"низойти" : "s. нисходить",
"низость" : "meanness",
"низший" : "inferior",
"никак" : "by no means not at all",
"никакой" : "no, ни в каком случае on no account, a. никак",
"никарагуа" : "nicaragua",
"никелевый" : "nickel",
"никель" : "nickel",
"никогда" : "never",
"никоим образом" : "by no means",
"никой" : "s. никак",
"николай" : "Nicholas",
"никотин" : "nicotine",
"никто" : "nobody no one none",
"никуда" : "nowhere, a. годиться годный",
"никчемный" : "good-for-nothing",
"нил" : "nile",
"нимало" : "s. нисколько",
"нимфа" : "nymph",
"нимфомания" : "nymphomania",
"ниобий" : "niobium",
"ниоткуда" : "from nowhere",
"нипочем" : "etc.",
"нирвана" : "nirvana",
"нисколько" : "not in the least not at all",
"ниспровергать" : "subvert",
"нисходящий" : "descending",
"нитка" : "thread, string, cotton",
"нитрат" : "nitrate",
"нитрид" : "nitride",
"нитроглицерин" : "nitroglycerine",
"нить" : "thread, string, cotton",
"ниц" : "падать ниц",
"ничто" : "nothing, nought, o",
"ничтожество" : "nothingness vanity nonentity",
"ничтожность" : "nothingness vanity nonentity",
"ничтожный" : "insignificant tiny, vain",
"ничуть" : "s. нисколько",
"ничье" : "nobody's, draw",
"ничьи" : "nobody's, draw",
"ничья" : "nobody's, draw",
"ниша" : "niche",
"нищая" : "beggar woman",
"нищая братия" : "beggary",
"нищенка" : "beggar woman",
"нищенский" : "beggarly",
"нищенство" : "begging, beggary",
"нищенствовать" : "beg",
"нищета" : "poverty destitution",
"нищий" : "beggarly, beggar",
"нквд" : ", People's Commissariat of Internal Affairs",
"но" : "but yet",
"новатор" : "innovator",
"новая экономическая политика" : "NEP (New Economic Policy Sov. #from #1922 #to #192",
"новелла" : "short story",
"новенький" : "new",
"новизна" : "novelty, news",
"новинка" : "novelty, news",
"новичок" : "novice tyro, newcomer",
"новобранец" : "recruit",
"новобрачная" : "bride",
"новобрачный" : "newly married",
"нововведение" : "innovation",
"новогодний" : "New Year's",
"новогодняя елка" : "Christmas tree #or, party",
"новолуние" : "new moon",
"новообращенный" : "neophyte, proselyte",
"новоприбывший" : "newly arrived, newcomer",
"новорожденный" : "newborn",
"новоселье" : "new home, housewarming",
"новостройка" : "new building",
"новость" : "news, novelty",
"новшество" : "innovation novelty",
"новый" : "new, novel, recent, modern; See also: Новый год, новый месяц, что нового{?}",
"новый год" : "New Year's Day, с Новым годом! a happy New Year!",
"новый месяц" : "crescent",
"новь" : "virgin soil",
"нога" : "foot leg, идти в ногу march in step, со всех ног with all one's might at full speed, стать на ноги recover, become independent, положить ногу на ногу cross one's legs, на ... ноге #or ногу on ... terms #or a ... footing, in style, ни ногой not visit, ноги унести escape, в ногах at the foot, под ногами underfoot",
"ноги заплетаются" : "totter stagger",
"ноготки" : "marigold",
"ноготь" : "nail",
"ноев ковчег" : "Noah's Ark",
"нож" : "knife, на ножах at daggers drawn",
"ножик" : "famil. = нож",
"ножка" : "s., leg",
"ножницы" : "scissors, disproportion",
"ножной" : "foot...",
"ножны" : "sheath",
"ножовка" : "handsaw",
"ножовщик" : "cutler",
"ноздря" : "nostril",
"ной" : "noah",
"нокаут" : "kayo, knock out",
"ноктюрн" : "nocturne",
"ноль нуль" : "naught, zero",
"номенклатура" : "nomenclature",
"номер" : "number, size, room, item turn trick, tag plate",
"номинальный" : "nominal",
"номограмма" : "nomograph",
"нонет" : "nonet",
"нора" : "hole burrow",
"норвегия" : "Norway",
"норвежец" : "Norwegian",
"норвежка" : "Norwegian",
"норвежский" : "Norwegian",
"норка" : "dim. of нора, zo. mink",
"норма" : "norm standard, rate",
"нормальность" : "normalcy",
"нормальный" : "normal",
"нормандский" : "norman",
"нормативный" : "normative",
"нормировать" : "pf. standardize",
"норовистый" : "balky",
"нос" : "nose, beak, prow, famil. spout, в ~ through one's nose, за ~ by the nose, на носу at hand, у меня идет кровь носом my nose is bleeding",
"носик" : "dim. #of нос, spout",
"носилки" : "stretcher litter",
"носильщик" : "porter",
"носитель" : "bearer, carrier",
"носить" : "carry bear s. нести, wear, a. have one's mind occupied with",
"носки" : "socks",
"носовой" : "nasal, prow ...; See also: носовой платок",
"носовой платок" : "handkerchief",
"носок" : "sock, toe, a. = носик",
"носорог" : "rhinoceros",
"ностальгия" : "nostalgia",
"нота" : "note, a. music",
"нотариус" : "notary",
"нотация" : "reprimand lecture",
"ночевать" : "pass the night",
"ночевка" : "overnight stop, a. = ночлег",
"ночлег" : "night's lodging night quarters, a. = ночевка",
"ночная бабочка" : "moth",
"ночной" : "night nocturnal; See also: ночная бабочка",
"ночь" : "night, ночью at night, ночь под ... ... night",
"ноша" : "load burden",
"ноябрь" : "November",
"ноябрьский" : "november",
"нрав" : "disposition temper, pl. customs, по нраву to one's liking",
"нравиться" : "please, он мне нравится I like him",
"нравоучение" : "moral moral teaching",
"нравоучительный" : "moral",
"нравственность" : "morals pl. morality",
"нравственный" : "moral",
"ну" : "well #or now ! come ! why! what!, the deuce, indeed? really? you don't say!, ha?, ~ да of course sure, ~  inf. begin to, ~ так что же? what about it?",
"ну что же" : "what of that?",
"нудный" : "prolix",
"нуждаться" : "desiderate, require",
"нуждающийся" : "hard up, indigent, necessitous, needy, penniless",
"нужно" : "need",
"нуль" : "zero",
"нумизматический" : "numismatic",
"нутрия" : "coypu, nutria",
"ныряние" : "dive, diving",
"ньюкасл" : "newcastle",
"ньюфаундленд" : "newfoundland",
"нюанс" : "nuance",
"нюхательный табак" : "snuff",
"нюхать" : "smell, scent, snuff",
"нянчить" : "nurse tend",
"нянька" : "nurse a. nanny",
"няня" : "nurse a. nanny",
"о" : "about of, on, with, against on, by in",
"оазис" : "oasis",
"об" : "about of, on, with, against on, by in",
"оба" : "both",
"обагрить" : "redden purple, stain, steep",
"обагрять" : "redden purple, stain, steep",
"обанкротиться" : "go bankrupt",
"обаяние" : "spell charm",
"обаятельный" : "fascinating",
"обвал" : "collapse, landslide, avalanche",
"обваливаться" : "fall in #or off",
"обвалиться" : "fall in #or off",
"обвалять" : "pf. roll",
"обварить" : "scald",
"обвернуть" : "wrap  envelop",
"обвертывать" : "wrap  envelop",
"обвесить" : "famil. = обвешать",
"обвести" : "s. обводить",
"обветренный" : "weather-beaten",
"обветшалый" : "decayed",
"обветшать" : "decay dilapidate weaken",
"обвешать" : "hang",
"обвешивать" : "hang",
"обвивать" : "wind round, embrace",
"обвинение" : "accusation charge, indictment, prosecution",
"обвинитель" : "accuser, prosecutor",
"обвинительный" : "accusatory, of 'guilty'",
"обвинительный акт" : "indictment",
"обвинить" : "accuse  charge, find guilty",
"обвиняемый" : "accused, defendant",
"обвинять" : "accuse  charge, find guilty",
"обвислый" : "flabby",
"обвить" : "wind round, embrace",
"обводить" : "lead see #or look, enclose encircle #or border, draw out, famil. turn",
"обвораживать" : "charm fascinate",
"обворожительный" : "charming fascinating",
"обворожить" : "charm fascinate",
"обвязать" : "tie up #or round, dress, hang",
"обвязывать" : "tie up #or round, dress, hang",
"обглодать" : "gnaw",
"обгонять" : "distance outstrip",
"обгорать" : "scorch",
"обгореть" : "scorch",
"обгрызать" : "gnaw",
"обгрызть" : "gnaw",
"обдавать" : "pour over, scald, bespatter, wrap up, seize",
"обдать" : "pour over, scald, bespatter, wrap up, seize",
"обделать" : "s. обделывать",
"обделить" : "s. обделять",
"обделывать" : "work, lay out, cut, famil. manage wangle",
"обделять" : "deprive of one's due share",
"обдирать" : "bark peel, tear",
"обдирающий" : "abrasive",
"обдуманный" : "deliberate",
"обдумать" : "s. обдумывать",
"обдумывать" : "consider think over",
"обе" : "both",
"обед" : "dinner  lunch, famil. noon, до обеда in the morning",
"обедать" : "have dinner  dine",
"обеденный" : "dinner... lunch..."
};
