var dicctr_9 = {
"винтовой" : "helical",
"винтообразный" : "spiral",
"винчестер" : "winchester",
"виньетка" : "vignette",
"виолончель" : "cello",
"вираж" : "bend curve, phot. toning solution",
"виртуоз" : "virtuoso",
"виртуозность" : "virtuosity",
"вирус" : "virus",
"виселица" : "gallows gibbet",
"висеть" : "hang",
"виски" : "whisky",
"вискоза" : "viscose",
"висла" : "Vistula",
"висмут" : "bismuth",
"виснуть" : "hang be suspended",
"висок" : "anat. temple",
"високосный" : "високосный год leap year",
"вист" : "whist",
"висячий" : "pendant, pensile, suspension",
"висящий" : "dangling, floppy, pendent, pendulous",
"витамин" : "vitamin",
"витой" : "coiled",
"виток" : "coil",
"витрина" : "showcase",
"виться" : "wind, spin whirl, twine creep, curl, hover",
"витязь" : "hero",
"вихор" : "forelock",
"вихрь" : "whirlwind",
"вице-" : "vice-...",
"вице-король" : "viceroy",
"вкладка" : "inset",
"вкладчик" : "depositor",
"вкладывать" : "inclose, invest",
"вклиниваться" : "be wedged in",
"вклинить" : "wedge in",
"вклиниться" : "be wedged in",
"включать" : "include, insert, el. switch #or turn on, -ся join",
"включая" : "including",
"включение" : "inclusion, insertion, el. switching on",
"включенный" : "cutin, on",
"включительно" : "included",
"включить" : "include, insert, el. switch #or turn on, -ся join",
"вколачивать" : "drive #or hammer in",
"вколотить" : "drive #or hammer in",
"вконец" : "famil. completely altogether",
"вкопать" : "dig in, drive in, как вкопанный",
"вкоренившийся" : "established rooted",
"вкорениться" : "take root",
"вкореняться" : "take root",
"вкось" : "askew aslant obliquely; See also: вкривь и вкось",
"вкп" : "= Всесоюзная Коммунистическая партия, C.P.S.U. = Communist Party of the Soviet Union",
"вкрадчивый" : "insinuating ingratiating",
"вкрадываться" : "creep #or steal in, o.s.",
"вкрасться" : "creep #or steal in, o.s.",
"вкратце" : "briefly in a few words",
"вкривь и вкось" : "pell-mell, amiss",
"вкрутую" : "яйцо вкрутую",
"вкус" : "sapor, taste",
"вкусный" : "sapid, savory, tasty, yummy",
"влага" : "moist",
"влагалище" : "axil, axilla, vagina",
"влагалищный" : "vaginal",
"владелец" : "holder, keeper, proprietor",
"владение" : "demesne, holding, possession, tenure",
"владения" : "domain",
"владеть" : "possess, wield",
"владычество" : "rule sway",
"влажность" : "humidity",
"влажный" : "humid damp",
"вламываться" : "break in",
"властвовать" : "rule dominate",
"властелин" : "sovereign",
"властитель" : "master ruler",
"властный" : "imperious commanding, в этом я не властен I have no power over it",
"власть" : "authority power, rule regime, control, pl. authorities",
"влачить" : "drag, eke out",
"влево" : "left",
"влезать" : "climb #or get in, climb up",
"влезть" : "climb #or get in, climb up",
"влетать" : "fly in, rush in",
"влететь" : "fly in, rush in",
"влечение" : "inclination",
"влечь" : "drag pull, fig. attract draw; See also: влечь за собой",
"влечь за собой" : "involve entail",
"вливание" : "infusion",
"вливать" : "pour in, -ся flow #or fall in",
"влить" : "pour in, -ся flow #or fall in",
"влияние" : "influence",
"влиятельный" : "influential",
"влиять" : "influence",
"влксм" : ", Leninist Young Communist League of the Soviet Union",
"вложить" : "put in insert enclose, invest, deposit",
"вломиться" : "break in",
"влюбиться" : "fall in love",
"влюбленность" : "amorousness",
"влюбленный" : "enamored, lover",
"влюбляться" : "fall in love",
"влюбчивый" : "amorous",
"вменить" : "consider  impute, вменять в обязанность pledge s.b.",
"вменяемый" : "responsible accountable",
"вменять" : "consider  impute, вменять в обязанность pledge s.b.",
"вместе" : "together along with; See also: вместе с тем",
"вместе с тем" : "at the same time",
"вместилище" : "receptacle",
"вместимость" : "capacity",
"вместительный" : "capacious spacious",
"вместить" : "s. вмещать",
"вместо" : "instead in place, as",
"вмешательство" : "interference intervention, med. operation",
"вмешать" : "mingle, involve, -ся interfere intervene meddle",
"вмешивать" : "mingle, involve, -ся interfere intervene meddle",
"вмешиваться" : "cut in, interject, intermeddle, intervene, meddle",
"вмещать" : "put place, hold contain accommodate, -ся find room, hold",
"вмиг" : "in an instant in no time",
"вмятина" : "dint",
"внаем" : "отдать внаймы; See also: сдать внаймы, взять внаймы",
"внаймы" : "отдать внаймы; See also: сдать внаймы, взять внаймы",
"вначале" : "at first at the beginning",
"вне" : "out of outside, beyond; See also: быть вне себя",
"внебрачный" : "illegitimate",
"внедрение" : "introduction",
"внедрить" : "inculcate, introduce, -ся take root",
"внедрять" : "inculcate, introduce, -ся take root",
"внезапный" : "sudden unexpected",
"внеклассный" : "out-of-class",
"внеочередной" : "extra",
"внесение" : "entry",
"внести" : "s. вносить",
"внешкольный" : "nonschool",
"внешний" : "outward external, foreign",
"внешность" : "appearance, exterior",
"вниз" : "down",
"внизу" : "beneath below, down",
"вникать" : "penetrate  fathom",
"вникнуть" : "penetrate  fathom",
"внимание" : "attention, care, принять во внимание take into consideration, принимая во внимание in view of with regard to, оставить без внимания disregard",
"внимательность" : "attentiveness",
"внимательный" : "attentive",
"внимать" : "hear #or listen, follow watch, comply with",
"вничью" : "сыграть вничью",
"внук" : "grandson, cf. внучата",
"внутренний" : "inner inside internal interior, inland..., home...",
"внутренности" : "entrails, guts, viscera",
"внутренность" : "interior, internal organs entrails",
"внутри" : "in, within",
"внутримолекулярный" : "intramolecular",
"внутристеночный" : "mural",
"внутрь" : "in inward inside",
"внучата" : "grandchildren",
"внучка" : "granddaughter",
"внушать" : "suggest, inspire, inculcate",
"внушение" : "suggestion, infusion, reprimand",
"внушительный" : "imposing impressive",
"внушить" : "suggest, inspire, inculcate",
"внятный" : "distinct, intelligible",
"внять" : "hear #or listen, follow watch, comply with",
"во весь голос" : "at the top of one's voice",
"во весь дух" : "at full speed with all one's might",
"во весь опор" : "at full speed at a gallop",
"во время" : "during",
"во всеуслышание" : "in public",
"во всю мочь" : "with all one's might",
"во избежание" : "to avoid",
"во имя" : "in the name of",
"во хмелю" : "drunk",
"во что бы то ни стало" : "at all costs at any cost",
"вобрать" : "absorb imbibe",
"вовлекать" : "drag in, fig. involve",
"вовлечь" : "drag in, fig. involve",
"вовремя" : "in #or time timely",
"вовсе" : "quite; See also: вовсе не",
"вовсе не" : "not at all",
"во-вторых" : "second",
"вогнутый" : "concave, dished",
"вода" : "backwash, water",
"водворить" : "settle, install, establish",
"водворять" : "settle, install, establish",
"водевиль" : "musical comedy",
"водитель" : "driver",
"водить" : "lead conduct guide, drive, move, breed; See also: водить дружбу",
"водить дружбу" : "be on friendly terms",
"водиться" : "be  live, be customary #or the custom, have, associate, это за ним водится famil. that's in his way to be sure!",
"водка" : "vodka, дать на водку tip",
"водный" : "aquatic, aqueous, hydrous",
"водобоязнь" : "hydrophobia",
"водовоз" : "water carter",
"водоворот" : "whirlpool eddy",
"водоем" : "reservoir",
"водоизмещение" : "displacement tonnage",
"водокачка" : "waterworks",
"водолаз" : "diver",
"водолей" : "aquarius",
"водолечение" : "hydropathy water cure",
"водонапорная башня" : "water tower",
"водонепроницаемый" : "watertight",
"водонос" : "water carrier",
"водопад" : "waterfall",
"водопой" : "watering place, watering",
"водопровод" : "water pipe",
"водораздел" : "divide Brt watershed",
"водород" : "hydrogen",
"водородная бомба" : "hydrogen bomb",
"водоросли" : "algae",
"водоросль" : "alga seaweed",
"водоснабжение" : "water supply",
"водосток" : "drain drainpipe",
"водосточная труба" : "gutter",
"водохранилище" : "reservoir",
"водружать" : "set up, hoist",
"водрузить" : "set up, hoist",
"водянистый" : "watery",
"водянка" : "dropsy",
"водяной" : "water...",
"воевать" : "wage #or carry on war be at war",
"воедино" : "together",
"военачальник" : "commander",
"военизация" : "militarization",
"военизировать" : "pf. militarize",
"военно-воздушные силы" : "air force",
"военное положение" : "martial law",
"военно-морской" : "naval",
"военно-морской флот" : "navy",
"военнопленный" : "prisoner of war",
"военно-полевой суд" : "court-martial",
"военно-полицейский" : "provost",
"военнослужащий" : "military man soldier",
"военные" : "soldiery",
"военные действия" : "hostilities",
"военный" : "military war..., military man soldier; See also: военный врач, военный корабль, военное положение, поступить на военную службу, военные действия",
"военный врач" : "medical officer",
"военный корабль" : "man-of-war warship",
"вожак" : "guide, leader",
"вожатый" : "leader guide, streetcar driver",
"вожделение" : "lust",
"вождь" : "chief, leader",
"вожжи" : "reins",
"воз" : "cart",
"возбудимый" : "excitable",
"возбудитель" : "exciter",
"возбудительный" : "excitative, excitatory",
"возбудить" : "excite stir up, arouse, incite, raise, bring present",
"возбуждать" : "excite stir up, arouse, incite, raise, bring present",
"возбуждающее средство" : "stimulant",
"возбуждающий" : "stimulating",
"возбуждение" : "excitement",
"возбужденный" : "excited",
"возвеличивать" : "exalt praise glorify",
"возвеличить" : "exalt praise glorify",
"возвести" : "s. возводить"
};
