var dicctr_54 = {
"отводить душу" : "famil. unburden one's heart",
"отводный" : "drain ...",
"отводящий" : "abducent, abducting, deferent",
"отвоевать" : "conquer win",
"отвоевывать" : "conquer win",
"отвозить" : "take get drive",
"отворачивать" : "turn off, -ся turn away",
"отворить" : "s. отворять",
"отвратительный" : "abhorrent, abominable, damned, detestable",
"отвращать" : "avert, fend off",
"отвращение" : "abhorrence, abomination, aversion, disgust",
"отговаривать" : "dissuade",
"отговорить" : "dissuade, -ся pretend  extricate o.s.",
"отговорка" : "excuse pretext",
"отголосок" : "s. отзвук",
"отгонять" : "drive away, fig. banish",
"отгораживать" : "fence in, partition off",
"отгородить" : "fence in, partition off",
"отгружать" : "load ship",
"отгрузить" : "load ship",
"отгрызать" : "gnaw  pick",
"отгрызть" : "gnaw  pick",
"отдавать" : "give back return, give, send, devote, deliver check Brt. book, put, pay, marry, make, cast, recoil, ~ честь milit. salute, famil. sell, impf. smell #or taste, -ся devote o.s., surrender give o.s. up, resound, be reflected",
"отдавить" : "crush",
"отдавливать" : "crush",
"отдаление" : "removal, estrangement, distance",
"отдаленный" : "remote",
"отдалить" : "move away remove, put off postpone, alienate, -ся move away, become estranged",
"отдалять" : "move away remove, put off postpone, alienate, -ся move away, become estranged",
"отдать" : "give back return, give, send, devote, deliver check Brt. book, put, pay, marry, make, cast, recoil, ~ честь milit. salute, famil. sell, impf. smell #or taste, -ся devote o.s., surrender give o.s. up, resound, be reflected",
"отдать в прокат" : "hire out",
"отдать в стирку" : "send to the wash",
"отдать внаймы" : "rent Brt. let",
"отдать предпочтение" : "prefer",
"отдача" : "delivery, recoil, return",
"отдел" : "department, office, section",
"отделать" : "s. отделывать",
"отделение" : "secretion, segregation",
"отделимый" : "separable",
"отдельно" : "separately",
"отдельный" : "separate, individual single",
"отделять" : "separate, secrete",
"отделяться" : "secede",
"отдергивать" : "draw back, draw open",
"отдернуть" : "draw back, draw open",
"отдирать" : "tear, famil. thrash, pull",
"отдохнуть" : "s. отдыхать",
"отдушина" : "vent",
"отдых" : "rest relaxation, дом отдыха rest home sanatorium",
"отдыхать" : "rest relax",
"отдышаться" : "pf. recover breath",
"отеел" : "calving",
"отек" : "edema",
"отекать" : "swell, become dropsical",
"отелиться" : "calve",
"отец" : "father",
"отеческий" : "fatherly, paternal",
"отечественный" : "native home..., patriotic",
"отечество" : "motherland fatherland one's country",
"отечь" : "swell, become dropsical",
"отживать" : "live, become obsolete die out",
"отжить" : "live, become obsolete die out",
"отзвук" : "echo repercussion, response, reminiscence",
"отзыв" : "response, opinion  reference, comment review, recall, password",
"отзывать" : "take aside recall, -ся respond answer, speak, sound, call forth, affect, impf. smack",
"отзывчивый" : "responsive sympathetic",
"отказ" : "refusal denial rejection, renunciation, engin. breakdown, mus. natural, без отказа smoothly, до отказа to the full; See also: получить отказ",
"отказать" : "refuse deny, dismiss, engin. break, -ся refuse decline reject, renounce give up, would mind",
"отказывать" : "refuse deny, dismiss, engin. break, -ся refuse decline reject, renounce give up, would mind",
"отказываться" : "abnegate, disown, forgo, forgone, forwent, waive",
"откалывать" : "cut #or chop off, unfasten, -ся come off, secede",
"откапывать" : "dig up unearth",
"откармливать" : "feed fatten",
"откатить" : "roll",
"откатывать" : "roll",
"откачать" : "pump out",
"откачивать" : "pump out",
"откашливаться" : "clear one's throat",
"откашляться" : "clear one's throat",
"откидной" : "folding tip-up",
"откидывать" : "throw, turn down, drop leave, -ся recline",
"откинуть" : "throw, turn down, drop leave, -ся recline",
"откладывать" : "lay aside, save, put off defer postpone",
"откланяться" : "pf. take one's leave",
"отклеивать" : "unstick, -ся come unstuck",
"отклеить" : "unstick, -ся come unstuck",
"отклик" : "response, comment, suggestion, a. отзвук",
"откликаться" : "respond  answer, comment",
"откликнуться" : "respond  answer, comment",
"отклонение" : "deviation deflection, digression, rejection",
"отклонить" : "deflect, decline reject, divert dissuade, -ся deviate deflect, digress",
"отклонять" : "deflect, decline reject, divert dissuade, -ся deviate deflect, digress",
"отклоняться" : "deviate",
"отклоняющийся" : "digressive, divergent, excursive",
"отколоть" : "cut #or chop off, unfasten, -ся come off, secede",
"откопать" : "dig up unearth",
"откормить" : "feed fatten",
"откос" : "slope slant scarp",
"откровение" : "revelation",
"откровенный" : "frank candid open outspoken",
"открывать" : "open, turn on, discover, disclose, reveal, unveil, inaugurate, -ся open, declare #or unbosom o.s.",
"открытие" : "opening, discovery, revelation, inauguration, unveiling",
"открытка" : "post card",
"открытый" : "open, public",
"открыть" : "open, turn on, discover, disclose, reveal, unveil, inaugurate, -ся open, declare #or unbosom o.s.",
"откуда" : "where from?, wherefrom, popul. why, famil. = откуда-нибудь; See also: откуда-то",
"откуда ни возьмись" : "all of a sudden",
"откуда-нибудь" : "somewhere #or anywhere",
"откуда-то" : "somewhere #or anywhere",
"откуп" : "hist. lease",
"откупать" : "buy, take on lease, -ся ransom o.s.",
"откупить" : "buy, take on lease, -ся ransom o.s.",
"откупоривать" : "uncork, open",
"откупорить" : "uncork, open",
"откусить" : "bite off, pinch off",
"откусывать" : "bite off, pinch off",
"отлагательство" : "delay",
"отлагаться" : "be deposited, secede fall away",
"отладка" : "debugging",
"отлакировать" : "laquer, varnish",
"отламывать" : "break off",
"отлепить" : "s. отклеить",
"отлив" : "ebb",
"отличающийся" : "discrepant",
"отличник" : "excellent pupil etc.",
"отличница" : "excellent pupil etc.",
"отличный" : "excellent perfect, different, a. very good A",
"отлогий" : "sloping",
"отложение" : "deposit",
"отложить" : "lay aside, save, put off defer postpone",
"отложиться" : "be deposited, secede fall away",
"отложной" : "turndown",
"отломать" : "break off",
"отломить" : "break off",
"отлучать" : "separate, wean, отлучить от церкви excommunicate, -ся leave absent o.s.",
"отлученный" : "excommunicate",
"отлучить" : "separate, wean, отлучить от церкви excommunicate, -ся leave absent o.s.",
"отлучка" : "absence",
"отмалчиваться" : "keep silence",
"отматывать" : "wind #or reel off unwind",
"отмахивать" : "drive away",
"отмахнуть" : "drive away",
"отмель" : "shoal sandbank",
"отмена" : "abolition, cancellation, countermand",
"отмененный" : "annulled",
"отменить" : "abolish, cancel countermand",
"отменный" : "s. отличный",
"отменять" : "abolish, cancel countermand",
"отмереть" : "s. отмирать",
"отмерзать" : "be frostbitten",
"отмерзнуть" : "be frostbitten",
"отмеривать" : "measure",
"отмерить" : "measure",
"отмерять" : "measure",
"отместка" : "в отместку",
"отметка" : "score",
"отмечать" : "signalize, specify",
"отмороженный" : "frostbitten",
"отмывать" : "wash",
"отмыкать" : "unlock open",
"отмыть" : "wash",
"отмычка" : "picklock",
"отнекиваться" : "deny disavow",
"отнести" : "s. относить",
"относиться" : "pertain",
"отношение" : "attitude, relationship",
"отнять от груди" : "wean",
"ото" : "from, of, off, against, for with, in, on behalf",
"отображать" : "reflect",
"отображение" : "reflection",
"отобразить" : "reflect",
"отобрать" : "take away #or off, select pick out, collect",
"отовсюду" : "from everywhere",
"отогнать" : "drive away, fig. banish",
"отогнуть" : "unbend, turn up",
"отогревать" : "warm",
"отогреть" : "warm",
"отодвигать" : "move aside away, famil. put off",
"отодвинуть" : "move aside away, famil. put off",
"отодрать" : "tear, famil. thrash, pull",
"отождествлять" : "identify",
"отожествить" : "identify",
"отозвать" : "take aside recall, -ся respond answer, speak, sound, call forth, affect, impf. smack",
"отойти" : "s. отходить",
"отомкнуть" : "unlock open",
"отомстить" : "revenge o.s. take revenge, avenge a p2",
"отопить" : "heat",
"отопление" : "heating",
"оторвать" : "s. отрывать",
"отпечаток" : "impress, imprint, overprint, print",
"отпивать" : "drink",
"отпиливать" : "saw off",
"отпилить" : "saw off",
"отпирательство" : "disavowel",
"отпирать" : "unlock unbar open, -ся open, disavow",
"отпить" : "drink",
"отпихивать" : "push off away aside back",
"отпихнуть" : "push off away aside back",
"отплата" : "repayment requital",
"отплатить" : "pay requite",
"отплачивать" : "pay requite",
"отплывать" : "sail leave, swim",
"отплытие" : "sailing off departure",
"отплыть" : "sail leave, swim",
"отповедь" : "rebuff snub",
"отполировать" : "polish burnish",
"отпор" : "repulse rebuff",
"отпороть" : "pf. rip",
"отправитель" : "sender",
"отправить" : "s. отправлять",
"отправка" : "despatch, dispatch",
"отправление" : "outset",
"отпрыск" : "offspring",
"отпугивать" : "scare",
"отпугнуть" : "scare",
"отпуск" : "leave vacation, sale, supply, allotment",
"отпускать" : "let go, release set free, dismiss, sell, provide, allot, slacken, remit, grow, famil. crack",
"отпускник" : "vacationist",
"отпускной" : "vacation... holiday..., selling",
"отпустить" : "let go, release set free, dismiss, sell, provide, allot, slacken, remit, grow, famil. crack",
"отпустить на волю" : "set free",
"отпущение" : "remission; See also: козел отпущения",
"отрабатывать" : "work off, finish work, a. waste",
"отработать" : "work off, finish work, a. waste",
"отрава" : "poison, fig. bane",
"отравить" : "poison, spoil",
"отравление" : "poisoning",
"отравлять" : "poison, spoil",
"отрада" : "comfort joy pleasure",
"отрадный" : "pleasant gratifying comforting",
"отражать" : "repel ward off, refute, reflect mirror",
"отразимый" : "resistible",
"отразить" : "repel ward off, refute, reflect mirror",
"отрасль" : "branch",
"отрастать" : "grow, grow again",
"отрасти" : "grow, grow again",
"отрастить" : "grow",
"отращивать" : "grow",
"отребье" : "rubbish, rabble",
"отредактировать" : "edit redact",
"отрез" : "pattern length",
"отрезать" : "cut off, famil. cut short",
"отрезвить" : "sober, fig. disillusion",
"отрезвлять" : "sober, fig. disillusion",
"отрезок" : "piece, stretch, math. segment",
"отрезывать" : "cut off, famil. cut short",
"отрекаться" : "disown disavow, renounce, отречься от престола abdicate",
"отрепье" : "pl.",
"отречение" : "disavowal, renunciation, abdication",
"отречься" : "disown disavow, renounce, отречься от престола abdicate"
};
