var dicctr_12 = {
"всплеск" : "splash",
"всплескивать" : "splash",
"всплеснуть" : "splash",
"всплеснуть руками" : "throw up one's arms",
"всплывать" : "rise to the surface emerge",
"всплывающий" : "supernatant",
"всплыть" : "rise to the surface emerge",
"всполошить" : "pf. startle",
"вспоминать" : "remember recall",
"вспомнить" : "remember recall",
"вспомогательный" : "auxiliary",
"вспомянуть" : "= вспомнить",
"вспорхнуть" : "pf. fly up",
"вспотеть" : "sweat  perspire",
"вспрыгивать" : "jump #or spring",
"вспрыгнуть" : "jump #or spring",
"вспрыскивать" : "sprinkle, wet, inject",
"вспрыснуть" : "sprinkle, wet, inject",
"вспугивать" : "start frighten away",
"вспугнуть" : "start frighten away",
"вспухать" : "swell",
"вспухнуть" : "swell",
"вспылить" : "pf. get angry",
"вспыльчивость" : "irascibility",
"вспыльчивый" : "quick-tempered",
"вспыхивать" : "flare up flash, blush, burst into a rage, break out",
"вспыхнуть" : "flare up flash, blush, burst into a rage, break out",
"вспышка" : "flare flash outburst outbreak",
"вставать" : "stand up, get up rise, arise",
"вставить" : "set #or put in insert",
"вставка" : "setting in insertion inset",
"вставлять" : "set #or put in insert",
"вставной" : "put in",
"вставные зубы" : "false teeth",
"встать" : "stand up, get up rise, arise",
"встрепенуться" : "pf. start shudder shake up",
"встрепка" : "reprimand; See also: задать встрепку",
"встретить" : "s. встречать",
"встреча" : "meeting, parley",
"встречать" : "met",
"вступительный" : "inaugural, initiation, introductory, opening",
"вступить в брак" : "contract marriage",
"вступить на трон" : "accede to the throne",
"вступиться" : "intercede  protect, take a pers.'s side",
"вступление" : "entry entrance, accession, beginning, introduction",
"всунуть" : "put slip",
"всучивать" : "foist",
"всучить" : "foist",
"всхлип" : "sob",
"всхлипнуть" : "sob",
"всхлипывание" : "sob",
"всхлипывать" : "sob",
"всходить" : "go #or climb  ascend rise, come up sprout, = входить",
"всходы" : "standing #or young crops",
"всхрапнуть" : "pf. nap",
"всыпать" : "pour #or put, popul. thrash",
"всюду" : "everywhere all over",
"вся" : "adj. all the whole, full life, all over, everything a. everybody, лучше всего best of all the best, при всем том #or со всем тем for all that, во всем мире all over the world, по всей стране throughout the country, всего хорошего! good luck!, во всю s. сила, все adv. always all the time, only just, все не not yet, все больше more and more, все же nevertheless yet",
"всякая всячина" : "whatnot hodgepodge",
"всякий" : "any every, any- everybody, = всяческий, all kinds #or sorts of sundry, every possible",
"всячески" : "in every way, всячески стараться take great pains",
"всячина" : "whatnot hodgepodge",
"втайне" : "in secret",
"вталкивать" : "push #or shove in",
"втаптывать" : "tramp in",
"втаскивать" : "pull #or drag in up",
"втащить" : "pull #or drag in up",
"втекать" : "flow in",
"втекающий" : "influent",
"втереть" : "s. втирать",
"втереться" : "famil. worm into",
"втечь" : "flow in",
"втирать" : "rub in, worm; See also: втирать очки",
"втирать очки" : "throw dust in eyes",
"втираться" : "famil. worm into",
"втискивать" : "press #or squeeze in",
"втиснуть" : "press #or squeeze in",
"втихомолку" : "famil. on the quiet",
"втолкнуть" : "push #or shove in",
"втоптать" : "tramp in",
"вторгаться" : "intrude invade penetrate, meddle",
"вторгнуться" : "intrude invade penetrate, meddle",
"вторжение" : "invasion incursion",
"вторить" : "mus. sing the second part, echo repeat",
"вторично" : "once more for the second time",
"вторичный" : "second repeated, secondary",
"вторник" : "Tuesday",
"второй" : "second, upper, из вторых рук second hand, & пятый",
"второкурсник" : "sophomore",
"второпях" : "in a hurry being in a great haste hastily",
"второстепенный" : "secondary minor",
"в-третьих" : "third",
"втридорога" : "famil. very dearly",
"втрое" : "three times, a. treble",
"втроем" : "three",
"втройне" : "three times  trebly",
"втуз" : "technical college institute of technology",
"втулка" : "plug",
"втуне" : "in vain, without attention",
"втыкать" : "put #or stick in",
"втягивать" : "draw #or pull in on, envolve engage",
"втягиваться" : "fall in, enter, engage in, get used",
"втянуть" : "draw #or pull in on, envolve engage",
"втянуться" : "fall in, enter, engage in, get used",
"вуаль" : "veil",
"вуз" : "university college",
"вузовец" : "college student",
"вулкан" : "volcano",
"вулканизм" : "volcanism",
"вулканический" : "volcanic",
"вульгарный" : "vulgar",
"вход" : "entrance; See also: плата за вход",
"входить" : "enter do come #or get in, go in have room #or hold, run into, penetrate into, be included in; See also: войти во вкус, войти в доверие к, войти в милость к, войти в положение, войти в привычку, войти в быт, войти в пословицу, войти в",
"входной" : "entrance... admission...",
"вцепиться" : "grasp catch hold of",
"вцепляться" : "grasp catch hold of",
"вцспс" : ", the All-Union Central Council of Trade Unions",
"вчера" : "yesterday",
"вчера вечером" : "last night",
"вчерашний" : "yesterday's yesterday",
"вчерне" : "in the rough, in a draft",
"вчетверо" : "four times",
"вчетвером" : "four",
"вчитаться" : "become absorbed in #or familiar with s.th. by reading",
"вчитываться" : "become absorbed in #or familiar with s.th. by reading",
"вшестеро" : "six times",
"вши" : "lice",
"вшивать" : "sew in",
"вшивый" : "lousy",
"вшить" : "sew in",
"вы" : "you, ~ с ним you and he, у вас ... you have ...",
"выбалтывать" : "blab #or let out",
"выбегать" : "run out",
"выбежать" : "run out",
"выбивать" : "beat #or knock out, break, smash, drive out, hollow out, stamp coin",
"выбиваться" : "break out #or forth; See also: выбиться из сил, выбиться из колеи",
"выбирать" : "choose pick out, elect, take out, find",
"выбираться" : "get out, move",
"выбить" : "beat #or knock out, break, smash, drive out, hollow out, stamp coin",
"выбиться" : "break out #or forth; See also: выбиться из сил, выбиться из колеи",
"выбиться из колеи" : "come off the beaten track",
"выбиться из сил" : "be exhausted fatigued",
"выболтать" : "blab #or let out",
"выбор" : "choice selection, pl. election; See also: всеобщие выборы, дополнительные выборы, на выбор, по выбору",
"выборка" : "selection, pl. excerpts",
"выборный" : "electoral, su. delegate",
"выбранить" : "scold rebuke abuse, -ся quarrel wrangle, swear curse",
"выбрасывать" : "throw, thrust, discard #or dismiss, exclude omit, strand, ~ деньги waste money, -ся throw o.s. out",
"выбрать" : "choose pick out, elect, take out, find",
"выбраться" : "get out, move",
"выбрить" : "shave, -ся get shaved shave",
"выбросить" : "throw, thrust, discard #or dismiss, exclude omit, strand, ~ деньги waste money, -ся throw o.s. out",
"выбывать" : "leave withdraw drop out",
"выбыть" : "leave withdraw drop out",
"вываливать" : "discharge throw out, popul. stream",
"вываливаться" : "fall out, stream out",
"вывалить" : "discharge throw out, popul. stream",
"вывалиться" : "fall out, stream out",
"вываривать" : "extract, boil down",
"выварить" : "extract, boil down",
"выведать" : "find out elicit",
"выведывать" : "find out elicit",
"вывезти" : "s. вывозить",
"вывернуть" : "unscrew, tear out, dislocate, turn, -ся, slip out extricate o.s.",
"вывертывать" : "unscrew, tear out, dislocate, turn, -ся, slip out extricate o.s.",
"вывесить" : "s. вывешивать",
"вывеска" : "sign",
"вывести" : "s. выводить",
"вывестись" : "disappear",
"выветривать" : "air, -ся weather",
"выветрить" : "air, -ся weather",
"вывешивать" : "hang out #or put up",
"вывинтить" : "unscrew",
"вывинчивать" : "unscrew",
"вывих" : "dislocation",
"вывихнуть" : "pf. dislocate sprain",
"вывод" : "withdrawal, breeding cultivation, derivation conclusion; See also: сделать вывод",
"выводить" : "take lead #or move, derive conclude, hatch, cultivate, construct, remove extirpate, write #or draw carefully, depict; See also: выводить из себя",
"выводить из себя" : "make s.b. lose his temper",
"выводиться" : "disappear",
"выводок" : "brood",
"вывоз" : "export",
"вывозить" : "remove get #or take #or bring out, export",
"вывозной" : "export...",
"выворачивать" : "= вывертывать вывернуть",
"выворотить" : "= вывертывать вывернуть",
"выгадать" : "gain #or save",
"выгадывать" : "gain #or save",
"выгиб" : "bend curve",
"выгибать" : "arch curve",
"выглядеть" : "impf. look, как она выглядит? what does she look like?, он выглядит моложе своих лет he doesn't look his age",
"выглядывать" : "look #or peep out",
"выглянуть" : "look #or peep out",
"выгнать" : "s. выгонять",
"выгнать вон" : "turn out",
"выгнуть" : "arch curve",
"выговаривать" : "pronounce, utter, famil. stipulate, famil. rebuke",
"выговор" : "pronunciation, reproof reprimand",
"выговорить" : "pronounce, utter, famil. stipulate, famil. rebuke",
"выгода" : "profit, advantage",
"выгодный" : "profitable, advantageous",
"выгон" : "pasture",
"выгонять" : "turn #or drive out, expel #or fire",
"выгораживать" : "enclose, popul. exculpate free from blame",
"выгорать" : "burn down, fade, famil. click come off",
"выгореть" : "burn down, fade, famil. click come off",
"выгородить" : "enclose, popul. exculpate free from blame",
"выгравировать" : "engrave",
"выгружать" : "unload, discharge, disembark",
"выгрузить" : "unload, discharge, disembark",
"выгрузка" : "unloading, disembarkation",
"выдавать" : "give  pay, distribute, draw #or issue, betray, extradite, ~ себя за pass for, ~ за give in marriage to",
"выдаваться" : "stand out, famil. happen #or turn out",
"выдавить" : "press #or squeeze out",
"выдавливать" : "press #or squeeze out",
"выдалбливать" : "hollow out",
"выдать" : "give  pay, distribute, draw #or issue, betray, extradite, ~ себя за pass for, ~ за give in marriage to",
"выдача" : "distribution, delivery, payment, issue, grant, betrayal, extradition; See also: день выдачи зарплаты",
"выдающийся" : "outstanding distinguished",
"выдвигать" : "pull out, put forward propose promote",
"выдвигаться" : "step forth move forward, project, advance, s. выдвижной",
"выдвиженец" : "promoted worker",
"выдвижной" : "pull-out... sliding",
"выдвинуть" : "pull out, put forward propose promote",
"выдвинуться" : "step forth move forward, project, advance, s. выдвижной",
"выделанный" : "wrought",
"выделать" : "work make, elaborate, curry",
"выделение" : "separation detachment, discharge secretion",
"выделенительный" : "excretory",
"выделить" : "separate detach, mark, emphasize, jur. allot, satisfy, med. secrete, chem. evolve, -ся  4), stand out come forth, rise above excel",
"выделка" : "manufacture, workmanship",
"выделывать" : "work make, elaborate, curry",
"выделять" : "separate detach, mark, emphasize, jur. allot, satisfy, med. secrete, chem. evolve, -ся  4), stand out come forth, rise above excel",
"выдергивать" : "pull out",
"выдержанный" : "self-restrained, consistent, mature",
"выдержать" : "stand bear endure, pass, observe; See also: выдержать характер",
"выдержать характер" : "be firm",
"выдерживать" : "stand bear endure, pass, observe; See also: выдержать характер",
"выдержка" : "self-control, extract quotation, phot. exposure; See also: на выдержку",
"выдернуть" : "pull out",
"выдирать" : "tear out, pull, pf. thrash",
"выдолбить" : "hollow out",
"выдохнуть" : "s. выдыхать",
"выдра" : "otter",
"выдрать" : "tear out, pull, pf. thrash",
"выдрессировать" : "train",
"выдубить" : "tan",
"выдуманный" : "invented, spoof",
"выдумать" : "invent contrive devise",
"выдумка" : "invention"
};
