var dicctr_59 = {
"печка" : "s. печь",
"печь" : "oven, stove",
"печь1" : "stove, oven, furnace, kiln",
"печь2" : "bake, scorch",
"печься" : "care",
"пешеход" : "pedestrian",
"пеший" : "unmounted",
"пешка" : "pawn",
"пешком" : "on foot",
"пещера" : "cave",
"пещеристый" : "cavernous",
"пианино" : "piano",
"пианиссимо" : "pianissimo",
"пианист" : "pianist",
"пивная" : "alehouse bar saloon",
"пиво" : "beer, ale",
"пивовар" : "brewer",
"пивоваренный завод" : "brewery",
"пигмент" : "pigment",
"пигментация" : "pigmentation",
"пиджак" : "coat jacket",
"пиетизм" : "pietism",
"пижама" : "pajamas pl.",
"пижма" : "tansy",
"пик" : "peak",
"пика" : "pike lance",
"пикантный" : "piquant spicy",
"пикап" : "pickup",
"пикет" : "picket",
"пики" : "spades",
"пикировать" : "pf. dive",
"пикник" : "junketing, picnic",
"пикнуть" : "pf. peep, famil. stir",
"пикофарада" : "picofarad",
"пила" : "saw",
"пила-рыба" : "sawfish",
"пилить" : "saw",
"пилот" : "pilot",
"пильщик" : "sawyer",
"пилюля" : "pill",
"пингвин" : "penguin",
"пинок" : "kick",
"пинта" : "pint",
"пинцет" : "tweezers pl.",
"пион" : "peony",
"пионер" : "pioneer (a. #member #of #Communist, #youth #organization #in #the #U.#S.#S.#R.)",
"пионерский" : "pioneer...",
"пипетка" : "dropper, pipette",
"пир" : "feast",
"пирамида" : "pyramid",
"пират" : "buccaneer, filibuster, picaroon, pirate, seadog",
"пиратство" : "piracy",
"пирит" : "pyrite, pyrites",
"пировать" : "feast banquet",
"пирог" : "pie",
"пирожник" : "pastry cook",
"пирожное" : "pastry, fancy cake",
"пирожок" : "patty",
"пироксен" : "pyroxene",
"пиролиз" : "pyrolysis",
"пирометр" : "pyrometer",
"пиротехнический" : "pyrotechnic",
"пирофосфат" : "pyrophosphate",
"пирушка" : "carousal revel",
"пируэт" : "pirouette",
"пиршество" : "feast banquet",
"писание" : "writing, Scripture",
"писарь" : "clerk",
"писатель" : "writer author",
"писательница" : "authoress",
"писать" : "write, type, paint",
"писк" : "squeak",
"пискливый" : "squeaky",
"пискнуть" : "s. пищать",
"писсуар" : "urinal",
"пистолет" : "pistol",
"пистоль" : "pistole",
"писчебумажный" : "stationery",
"писчий" : "note",
"письменность" : "literature",
"письменный" : "written, in writing, writing",
"письмо" : "letter, writing",
"письмоносец" : "postman mailman",
"питание" : "nutrition, nourishment food, board, engin. feeding",
"питательность" : "sustenance",
"питательный" : "nutritious nourishing",
"питать" : "nourish  feed, cherish  bear",
"питаться" : "feed #or live",
"питающий" : "nutritive",
"питомец" : "pupil, nursling",
"питомица" : "pupil, nursling",
"питомник" : "nursery",
"пить" : "drink, have take",
"питье" : "drink",
"питьевой" : "drinking  drinkable",
"пифагорейский" : "pythagorean",
"пихать" : "shove",
"пихнуть" : "shove",
"пихта" : "fir",
"пицца" : "pizza",
"пиццикато" : "pizzicato",
"пичкать" : "stuff",
"пишущая машинка" : "typewriter",
"пишущий" : "writing",
"пища" : "food, fare board",
"пищать" : "peep squeak cheep",
"пищеварение" : "digestion",
"пищеварительный" : "digestive, pepsin, peptic",
"пищевод" : "anat. gullet",
"пищевой" : "food",
"пиявка" : "leech",
"плавание" : "swimming, navigation, voyage trip",
"плавать" : "swim, float, sail navigate",
"плавильный" : "melting",
"плавильня" : "foundry",
"плавить" : "smelt fuse",
"плавка" : "fusion",
"плавкий" : "fusible",
"плавление" : "fusion",
"плавник" : "fin",
"плавный" : "fluent smooth, gr. liquid",
"плавучесть" : "buoyancy, floatation, flotage, flotation",
"плавучий" : "buoyant",
"плагиат" : "plagiarism",
"плагиоклаз" : "plagioclase",
"плазма" : "plasma",
"плакат" : "poster placard bill",
"плакать" : "weep  cry",
"плакать навзрыд" : "sob",
"плакаться" : "famil. complain",
"плакса" : "crybaby",
"плаксивый" : "whining",
"пламенеть" : "flame",
"пламенный" : "flaming fiery, a. ardent",
"пламя" : "flame, blaze",
"план" : "plan, draft, plane; See also: первый план, передний план, задний план",
"планер" : "glider",
"планета" : "planet",
"планетарий" : "orrery, planetarium",
"планетный" : "planetary",
"планировать1" : "за plan, спланировать av. glide",
"планировать2" : "level",
"планировка" : "planning, leveling",
"планка" : "lath",
"планктон" : "plankton",
"плановый" : "planned, plan",
"планомерный" : "systematic planned",
"плантатор" : "planter",
"плантация" : "plantation",
"пласт" : "layer stratum",
"пластика" : "plastic arts pl., plastic figure",
"пластинка" : "plate, record",
"пластичный" : "plastic",
"пластмасса" : "plastic",
"пласты" : "strata",
"пластырь" : "plaster",
"плата" : "pay, fee, wages pl., fare, rent",
"плата за вход" : "entrance #or admission fee",
"платеж" : "payment",
"платежеспособный" : "solvent",
"платежный" : "of payment",
"плательщик" : "payer",
"платина" : "platinum",
"платиновый" : "platinic, platinum",
"платить" : "pay, settle",
"платиться" : "fig. pay",
"платный" : "paid, to be paid for",
"плато" : "plateau",
"платок" : "kerchief",
"платон" : "plato",
"платформа" : "platform",
"платье" : "dress gown",
"платяной" : "clothes...",
"плафон" : "plafond",
"плаха" : "block",
"плацдарм" : "base, bridgehead",
"плацебо" : "placebo",
"плацента" : "placenta",
"плацкарта" : "reserved seat",
"плач" : "weeping",
"плачевный" : "deplorable pitiable lamentable plaintive",
"плачущий" : "tearful, wailing",
"плашмя" : "flat",
"плащ" : "raincoat, cloak",
"плебейский" : "plebeian",
"плебисцит" : "plebiscite",
"плева" : "membrane, pleura",
"плевательница" : "cuspidor spittoon",
"плевать" : "spit, famil. not care",
"плевел" : "weed",
"плевок" : "spit",
"плевра" : "pleura",
"плеврит" : "pleurisy",
"плед" : "plaid traveling rug",
"плейстоценовый" : "pleistocene",
"племенной" : "tribal, brood... stud...",
"племя" : "tribe, race, family, generation, breed, famil. brood",
"племянник" : "nephew",
"племянница" : "niece",
"плен" : "captivity; See also: взять в плен, попасть в плен",
"пленарный" : "plenary",
"пленительный" : "captivating fascinating",
"пленить" : "s. пленять",
"пленка" : "film",
"пленум" : "plenum",
"плесень" : "mildew, mold",
"плетень" : "wicker fence",
"плетка" : "lash scourge",
"плеть" : "lash scourge",
"плечо" : "shoulder, back, engin. arm, с плеч долой s.th., с плеча with all one's might, straight from the shoulder, не по плечу not be equal to a th., на плечо! shoulder arms!, правое плечо вперед! milit. left turn !, a. гора famil.",
"плешивый" : "bald",
"плешь" : "bald patch",
"плимут" : "plymouth",
"плинтус" : "baseboard, plinth, skirting",
"плиоцен" : "pliocene",
"плита" : "slab stone, plate, range, stove",
"плитка" : "tablet cake bar, hot plate",
"плов" : "pilau",
"пловец" : "swimmer",
"пловучий" : "floating",
"пловучий маяк" : "lightship, a. льдина",
"плод" : "fruit",
"плодить" : "propagate multiply",
"плодовитый" : "fruit growing",
"плодоводство" : "fruit growing",
"плодовый" : "fruit...",
"плодоносить" : "fructify",
"плодоносный" : "fructiferous",
"плодородие" : "fertility",
"плодородный" : "fertile fruitful fecund",
"плодотворный" : "fruitful productive, profitable favorable",
"пломба" : "seal, filling",
"пломбировать" : "seal",
"плоский" : "flat  plain level",
"плосковогнутый" : "planoconcave",
"плосковыпуклый" : "planoconvex",
"плоскогорье" : "plateau tableland",
"плоскогубцы" : "pliers",
"плоскостной" : "planar",
"плоскость" : "flatness, plane, level, angle, platitude",
"плот" : "raft",
"плотина" : "dam dike",
"плотник" : "carpenter",
"плотность" : "density, solidity",
"плотный" : "compact solid, dense, close thick, thickset",
"плотоядный" : "carnivorous",
"плотский" : "carnal fleshly",
"плоть" : "flesh",
"плохо" : "bad, bad famil.",
"плохой" : "bad"
};
