var dicctr_27 = {
"зевота" : "yawning",
"зевс" : "zeus",
"зеленеть" : "grow turn #or be green, impf. appear #or show green",
"зеленной" : "greengrocer's",
"зеленоватый" : "greenish",
"зеленщик" : "greengrocer",
"зеленый" : "green  verdant; See also: зеленый театр, зеленый юнец",
"зеленый театр" : "open-air stage",
"зеленый юнец" : "famil. greenhorn",
"зелень" : "verdure, green, potherbs greens pl.",
"зелье" : "herb, poison",
"земельный" : "land..., landed",
"землевладелец" : "landowner",
"землевладение" : "landed property estate",
"земледелец" : "farmer",
"земледелие" : "agriculture farming",
"земледельческий" : "agricultural",
"землекоп" : "digger, Brt. navvy",
"землемер" : "surveyor",
"землепашец" : "husbandman",
"землетрясение" : "earthquake",
"землечерпалка" : "dredge",
"землистый" : "earthy, ashy",
"земля" : "earth, land, ground soil, obsol. country, на землю to the ground",
"земляк" : "countrymen",
"земляная груша" : "artichoke",
"земляника" : "strawberry -ries pl.",
"землянка" : "dugout, hut",
"земляной" : "earth mud..., land..., ashy; See also: земляной орех, земляная груша",
"земляной орех" : "peanut",
"земноводное" : "amphibian",
"земноводный" : "amphibian",
"земной" : "earth terrestrial, earthly, fig. earthy",
"земной шар" : "globe",
"земский" : "hist. State..., county..., milit. Territorial; See also: земский собор, земский начальник",
"земский начальник" : "sheriff bailiff",
"земский собор" : "diet",
"земство" : "zemstvo county council (1864-191",
"зенит" : "zenith",
"зенитный" : "anti-aircraft...",
"зеница" : "obsol. pupil eye, беречь как зеницу ока cherish like the apple of one's eye",
"зеркало" : "looking glass mirror",
"зеркальный" : "fig. smooth, plate",
"зернистый" : "grainy granular",
"зерно" : "grain  corn seed",
"зерновой" : "grain..., pl. cereals",
"зернышко" : "pip",
"зигзаг" : "zigzag",
"зигзагообразный" : "zigzag",
"зима" : "winter",
"зимний" : "winter... wintry",
"зимовать" : "winter, hibernate",
"зимовка" : "wintering, hibernation, winter hut",
"зимовье" : "wintering, hibernation, winter hut",
"зимородок" : "kingfisher",
"зияние" : "gaping, ling. hiatus",
"зиять" : "gape",
"злак" : "herb, grass, bot. gramineous plants; See also: хлебные злаки",
"злато" : "poet. gold",
"злоба" : "malice, rancor, rancour, spite",
"злобнонасмешливый" : "sardonic",
"зловещий" : "grim, inauspicious, ominous, portentous, sinister",
"зловоние" : "fetor, mephitis, stench",
"зловонный" : "fetid, foetid, malodorous, nifty, smelly",
"злодей" : "cannibal, fiend, miscreant, villain",
"злодеяние" : "misdeed outrage villainy crime",
"злой" : "wicked evil, malicious spiteful, angry, fierce, severe, bad, mordant, med. malignant",
"злокачественный" : "malignant",
"злоключение" : "misfortune",
"злонамеренный" : "malevolent",
"злонравный" : "ill-natured",
"злопамятный" : "vindictive",
"злополучный" : "unfortunate ill-fated",
"злорадный" : "mischievous",
"злорадствовать" : "gloat",
"злословие" : "slander",
"злословить" : "slander",
"злостный" : "malicious spiteful, malevolent",
"злость" : "spite rage",
"злосчастный" : "s. злополучный",
"злоумышленник" : "plotter, malefactor",
"злоумышленный" : "malevolent",
"злоупотребить" : "abuse, excessive use",
"злоупотребление" : "abuse, excessive use",
"злоупотреблять" : "abuse, excessive use",
"змеиный" : "snake serpent serpentine",
"змеиться" : "meander wind",
"змей" : "dragon, kite, popul. = змея",
"змея" : "snake serpent",
"знак" : "sign mark token, symbol, omen, badge, signal; See also: знаки препинания, в знак",
"знаки отличия" : "decorations",
"знаки препинания" : "punctuation marks",
"знакомить" : "introduce, acquaint",
"знакомиться" : "pers.: meet make the acquaintance of, become acquainted with, o.s. with go into",
"знакомство" : "acquaintance",
"знакомый" : "familiar acquainted, known, su. acquaintance, будьте знакомы = знакомьтесь ... ... meet ...",
"знаменатель" : "denominator",
"знаменательный" : "memorable remarkable, significant suggestive, gr. notional",
"знамение" : "s. знак",
"знаменитость" : "fame renown, pers.: celebrity",
"знаменитый" : "famous renowned celebrated",
"знаменосец" : "standard bearer",
"знамя" : "banner flag, milit. standard, colors",
"знание" : "knowledge, со знанием дела with skill #or competence",
"знатный" : "noble, distinguished notable eminent",
"знаток" : "expert, connoisseur",
"знать" : "knew, know, wot",
"знать толк в" : "be a judge of",
"знать1" : "know; See also: дать знать1, дать себя знать1, дать о себе знать1, то и знай, кто его знает",
"знать2" : "nobility notables",
"знаться" : "famil. associate with, know",
"знахарь" : "quack, quacksalver",
"значение" : "meaning sense, significance importance",
"значит" : "consequently so, well",
"значительный" : "considerable, large, important, significant suggestive",
"значить" : "mean signify, matter; See also: значит",
"значиться" : "be registered, impers. say",
"значок" : "badge, sign",
"знающий" : "cognizant, informed, knowing, sciential",
"знобить" : "меня знобит I feel chilly",
"зной" : "swelter",
"знойный" : "torrid",
"зоб" : "craw",
"зодиак" : "zodiac",
"зодиакальный" : "zodiacal",
"зола" : "ash, kelp",
"золотисто-каштановый" : "auburn, titian",
"золотистый" : "aureate, golden",
"золотить" : "gild",
"золотоискатель" : "argonaut",
"золотой" : "gold",
"золотоносный" : "auric, auriferous",
"золоченый" : "gilt",
"золушка" : "cinderella",
"золь" : "sol",
"зона" : "zone",
"зональный" : "zonal",
"зонд" : "sound",
"зондировать" : "sound",
"зонт" : "umbrella, sunshade",
"зонтик" : "umbrella, sunshade",
"зоолог" : "zoologist",
"зоологический" : "zoological",
"зоология" : "zoology",
"зоопарк" : "zoo",
"зоосад" : "zoo",
"зоркий" : "sharp-sighted, observant watchful vigilant",
"зрачок" : "anat. pupil",
"зрелище" : "sight, spectacle, show",
"зрелость" : "ripeness maturity",
"зрелый" : "ripe mature, deliberate",
"зрение" : "sight; See also: поле зрения, точка зрения",
"зреть" : "созреть вызреть ripen mature, obsol. узреть see, look",
"зритель" : "spectator onlooker looker-on",
"зрительная труба" : "spyglass",
"зрительный" : "visual optic",
"зрительный зал" : "hall auditorium",
"зря" : "famil. in vain to no purpose for nothing, it's no good ...ing",
"зрячий" : "seeing",
"зуб" : "tooth, a. cog dent; See also: до зубов, не по зубам, сквозь зубы, иметь зуб, точить зуб",
"зубастый" : "large- sharp-toothed, fig. sharp-tongued",
"зубец" : "engin. = зуб, milit. battlement",
"зубило" : "chisel",
"зубная боль" : "toothache",
"зубной" : "tooth..., dental",
"зубной врач" : "dentist",
"зубочистка" : "toothpick",
"зубр" : "bison, fig. fossil",
"зубрежка" : "cramming",
"зубрить" : "зазубрить notch, зазубренный jagged, famil. вызубрить зазубрить cram learn by rote",
"зубчатый" : "engin. cog... gear..., indented",
"зубы" : "teeth",
"зуд" : "itch",
"зудеть" : "itch",
"зыбкий" : "loose, shaky, unsteady unstable, swelling rippled, vague",
"зыбучий" : "= зыбкий",
"зыбь" : "ripples pl., swell, obsol. wave",
"зычный" : "ringing",
"зябкий" : "chilly",
"зяблевый" : "winter...",
"зяблик" : "chaffinch",
"зябнуть" : "feel chilly, freeze",
"зябь" : "winter tillage",
"зять" : "son- #or brother-in-law",
"и" : "cj. and, and then, and so, but, though much as, just  very #or same, part. oh, too either, even, и ... и ... both ... and ...",
"и виду не показывать" : "seem to know nothing, look unconcerned",
"и если" : "if ever, whereas",
"и не говори" : "yes of course sure!",
"и тот и другой" : "both",
"и тп" : "abbr.: и тому подобное",
"ибис" : "ibis",
"ива" : "osier, willow",
"иволга" : "oriole",
"игла" : "needle",
"иглу" : "igloo",
"игнорировать" : "ignore",
"игра" : "pastime, play",
"играть" : "play, gamble, rage, sparkle, a. act",
"играть в кости" : "dice",
"игривый" : "playful sportive, equivocal immodest",
"игристый" : "sparkling",
"игрок" : "player gambler",
"игрушка" : "toy plaything",
"игумен" : "abbot superior",
"идеал" : "ideal",
"идеализм" : "idealism",
"идеалист" : "idealist",
"идеалистический" : "idealistic",
"идеальный" : "ideal",
"идейный" : "ideologic, ideal, high-principled",
"идентификатор" : "id, identifier",
"идеолог" : "ideologist",
"идеологический" : "ideologic",
"идеология" : "ideology",
"идет" : "all right! done!",
"идея" : "idea",
"идиллический" : "idyllic",
"идиллия" : "idyl",
"идиома" : "idiom",
"идиоматика" : "stock of idioms, idiomology",
"идиоматический" : "idiomatic",
"идиот" : "idiot",
"идиотизм" : "idiocy",
"идиотский" : "idiotic",
"идиш" : "yiddish",
"идол" : "idol, contp. blockhead",
"идолопоклонство" : "idolatry",
"идти" : "go walk, come, run pass drive sail fly etc., follow a. go for fetch, leave, move  flow drift blow, enter  join  become, proceed be in progress take place, be on, lead, attack, spread, receive, commerc. sell, engin. work, be used spent, be sent to, suit, marry, ему идет #or пошел шестой год, he is over #or past five; See also: идти в счет, идти на веслах, пойти по отцу, идет{!}, пошел{!}, пошли{!}, дело идет о, речь идет о",
"идти в счет" : "count",
"идти вразрез" : "be contrary",
"идти на веслах" : "row",
"идти навстречу" : "go to meet, fig. meet halfway",
"идти напролом" : "force one's way",
"идти под венец" : "obsol. marry",
"иегова" : "jehovah",
"иезуит" : "Jesuit",
"иероглиф" : "hieroglyph",
"иерусалим" : "Jerusalem",
"иждивенец" : "dependent",
"иждивение" : "на иждивении",
"из" : "from",
"избави бог" : "God forbid!",
"избавитель" : "rescuer saver deliverer",
"избавить" : "s. избавлять",
"избавление" : "deliverance rescue",
"избавлять" : "deliver free, save, relieve, redeem, -ся escape get rid of",
"избалованный" : "spoilt",
"избаловать" : "spoil coddle",
"избегать" : "avoid shun, escape evade",
"избегнуть" : "avoid shun, escape evade"
};
