var dicctr_36 = {
"кубок" : "goblet, #prize: cup",
"кубометр" : "cubic meter",
"кубрик" : "cockpit, orlop",
"кувалда" : "maul",
"кувейт" : "kuwait",
"куверт" : "cover, envelope",
"кувшин" : "jug, pitcher",
"кувыркаться" : "somersault tumble",
"кувыркнуться" : "somersault tumble",
"кувырком" : "s. кубарем",
"куда" : "where, what ... for, famil. very awfully how, at all, by far much, how can ..., impossible!, certainly not! what an idea! rats!, ~ ... ~ ... to some places ... to others ..., ~ вы ? where are you going?, ~ куда-либо; See also: хоть куда, куда-нибудь, куда-то",
"куда деть" : "a. what to do with how to spend",
"куда мне деваться" : "where shall I go #or stay?",
"кудахтанье" : "cluck",
"кузнец" : "smith",
"кузнечик" : "zo. grasshopper",
"кузнечный" : "blacksmith",
"кузница" : "smithy",
"кузов" : "body, box",
"кукарекать" : "crow",
"кукиш" : "fig fico",
"кукла" : "doll",
"куколка" : "dim. #of кукла, zo. chrysalis",
"кукольный" : "doll, dollish",
"кукольный театр" : "puppet show",
"кукуруза" : "corn Brt. maize",
"кукушка" : "cuckoo",
"кулак" : "fist, engin. cam, kulak",
"кулацкий" : "kulak...",
"кулачество" : "kulaks pl.",
"кулачный" : "boxing, club, engin. cam...",
"кулачок" : "tappet",
"кулек" : "bag",
"кулик" : "curlew, snipe",
"кулинария" : "cookery, gastronomy",
"кулинарный" : "culinary",
"кулиса" : "wing side scene; See also: за кулисами",
"кулич" : "Easter cake",
"кулон" : "coulomb",
"кулуары" : "lobbies",
"куль" : "sack bag",
"кульминация" : "climax",
"культ" : "cult",
"культивировать" : "cultivate",
"культработа" : "cultural & educational work",
"культура" : "culture",
"культурный" : "cultural, cultured civilized, polite well-bred",
"кум" : "godfather",
"кума" : "godmother, gossip",
"кумач" : "red bunting",
"кумир" : "idol",
"кумовство" : "sponsorship friendship, fig. nepotism",
"кумыс" : "kumiss",
"куница" : "marten",
"купальный" : "bathing; See also: купальный костюм",
"купальный костюм" : "bathing suit Brt. bathing costume",
"купальня" : "bath bathhouse",
"купальщик" : "bather",
"купание" : "bathe, bathing",
"купать" : "bath, bathe",
"купаться" : "take a bath, bathe",
"купе" : "rail. compartment",
"купель" : "font",
"купец" : "merchant",
"купеческий" : "merchant",
"купечество" : "merchants pl.",
"купить" : "s. покупать",
"купить кота в мешке" : "buy a pig in a poke",
"куплет" : "couplet stanza, song",
"купля" : "purchase",
"купол" : "cupola dome",
"купорос" : "vitriol",
"купоросный" : "vitriolic",
"купчая" : "purchase deed",
"курган" : "burial mound barrow",
"курд" : "kurd",
"курево" : "tobacco smoke, курение",
"курение" : "smoking",
"курильщик" : "smoker",
"куриный" : "chicken..., hen's, famil. short, night...",
"курительный" : "smoking",
"курить" : "smoke, distil",
"курица" : "hen, chicken fowl",
"курносый" : "snub-nosed",
"курок" : "cock",
"куропатка" : "partridge",
"курорт" : "health resort",
"курс" : "course, a. year, commerc. rate of exchange, fig. line policy, av. educ. держать курс на; See also: держать в курсе, быть в курсе",
"курсант" : "student, milit. cadet",
"курсив" : "typ. italics",
"курсировать" : "ply",
"куртизанка" : "courtesan",
"куртка" : "jacket",
"курчавый" : "curly",
"курьез" : "fun, curiosity",
"курьер" : "messenger, courier",
"курьерский" : "express",
"курьерский поезд" : "express",
"курятина" : "chicken",
"курятник" : "hen house",
"курящий" : "smoker",
"кусать" : "bite  sting",
"кусающийся" : "snappish",
"кусками" : "by the piece, на куски to pieces",
"кусковой" : "lump",
"кусок" : "piece bit morsel, scrap, lump, cake, slice",
"кусок хлеба" : "famil. living",
"кусочек" : "dim. #of кусок",
"куст" : "bush shrub",
"кустарник" : "bush shrub, a. underwood",
"кустарный" : "handicraft..., home, fig. homespun",
"кустарь" : "craftsman",
"кутать" : "muffle wrap",
"кутеж" : "binge, razzle-dazzle",
"кухарка" : "cooky",
"кухня" : "cuisine",
"кухонный" : "cooking, kitchen",
"кухонька" : "kitchenette",
"куча" : "pile",
"кучер" : "coachman, whipstitch",
"кушанье" : "dish, meal, food",
"кушать" : "eat, drink",
"кушетка" : "lounge",
"кюри" : "curie",
"лабазник" : "meadowsweet",
"лабиринт" : "labyrinth",
"лабиринтовый" : "labyrinth",
"лаборатория" : "laboratory",
"лабораторный" : "laboratory",
"лава" : "lava",
"лаванда" : "lavender",
"лавина" : "avalanche",
"лавировать" : "tack",
"лавка" : "bench, store Brt. shop",
"лавовый" : "lava",
"лавочник" : "store- shopkeeper",
"лавр" : "laurel",
"лавровый" : "laurel",
"лагерный" : "camp...",
"лагерь" : "camp, располагаться лагерем camp",
"лагуна" : "lagoon",
"лад" : "famil. harmony concord, order, way, tune, в ладу s. ладить, идти на ~ work  get on #or along",
"ладан" : "incense",
"ладить" : "get along #or on  a. make it up, manage, fix, tune, не ладить a. be at odds #or variance, out of keeping",
"ладиться" : "impf. & ладить",
"ладно" : "famil. well all right O.K.",
"ладный" : "harmonious, fine good",
"ладожское озеро" : "Lake Ladoga",
"ладонь" : "palm; See also: как на ладони, бить в ладоши",
"ладоша" : "palm; See also: как на ладони, бить в ладоши",
"ладья" : "boat, #chess: rook",
"лазарет" : "hospital",
"лазейка" : "loophole",
"лазить" : "climb, creep",
"лазурный" : "azure",
"лазурь" : "azure",
"лазутчик" : "scout spy",
"лай" : "bark yelp",
"лайка" : "Eskimo dog, kid",
"лайковый" : "kid...",
"лак" : "varnish laquer",
"лакать" : "lap",
"лакей" : "footman lackey, flunky",
"лакейский" : "lackey, fig. servile",
"лакировать" : "laquer, varnish",
"лакмус" : "litmus, turnsole",
"лаковый" : "varnish laquer, patent leather...",
"лакомиться" : "enjoy relish  eat with delight, be fond of dainties",
"лакомка" : "lover of dainties, быть лакомкой a. have a sweet tooth",
"лакомство" : "dainty delicacy, Brt. sweets",
"лакомый" : "dainty, obsol. fond of; See also: лакомый кусок",
"лакомый кусок" : "tidbit Brt. titbit",
"лаконичный" : "laconic",
"лактоза" : "lactose",
"лама" : "lama, llama",
"ла-манш" : "English Channel",
"лампа" : "lamp",
"ландо" : "barouche, landau",
"лаос" : "laos",
"лапа" : "paw",
"лапчатый" : "palmate",
"лапша" : "noodle, noodles",
"ларь" : "hutch",
"ласка" : "endearment, weasel",
"ласкательный" : "endearing pet, obsol. flattering, a. ласковый",
"ласкать" : "caress, pet fondle, impf. cherish, flatter",
"ласкаться" : "endear o.s., fawn, obsol. cherish",
"ласковый" : "affectionate tender, caressing",
"ласточка" : "swallow",
"латать" : "patch mend",
"латвийский" : "Latvian",
"латинский" : "Latin",
"латка" : "patch",
"латук" : "lettuce",
"латунь" : "brass",
"латы" : "armor",
"латынь" : "Latin",
"латыш" : "Lett",
"латышка" : "Lett",
"латышский" : "Lettish",
"лауреат" : "prize winner",
"лафет" : "gun carriage",
"лацкан" : "lapel",
"лачуга" : "hovel hut",
"лаять" : "bark",
"лгать" : "солгать lie, tell a pers. a lie, налгать defame",
"лгун" : "liar",
"лгунья" : "liar",
"лебединый" : "swan...",
"лебедка" : "windlass",
"лебедь" : "swan",
"лебезить" : "fawn",
"лев" : "lion",
"левша" : "left-handed person",
"левый" : "left  left-hand, wrong",
"легальный" : "legal",
"легенда" : "legend",
"легендарный" : "legendary",
"легион" : "legion",
"легкий" : "light, easy, slight, famil. lucky, легко  inf.; See also: легок на помине",
"легко" : "easily, lightly",
"легковая машина" : "auto car",
"легковерный" : "credulous, gullible",
"легковой" : "легковой автомобиль; See also: легковая машина",
"легкое" : "lung",
"легкомысленный" : "flippant, frivolous, harum-scarum, light-minded",
"легкомыслие" : "frivolity, levity",
"легкость" : "ease, lightness",
"лед" : "ice",
"леденец" : "lollipop",
"ледник" : "glacier",
"ледоход" : "ice drift",
"ледяной" : "ice..., icy, chilly",
"лежалый" : "stale old spoiled",
"лежать" : "lie, be, rest be incumbent, form",
"лежачий" : "lying, prostrate, turndown",
"лежащий" : "decumbent, recumbent",
"лезвие" : "edge",
"лезть" : "climb, creep, penetrate, famil. reach into, importune press, fall out, fit, popul. meddle",
"лейборист" : "Laborite",
"лейка" : "watering pot can",
"лейтенант" : "lieutenant",
"лейтмотив" : "leitmotif, leitmotiv",
"лекарственный" : "medicinal curative",
"лекарство" : "medicine remedy",
"лекарь" : "doctor",
"лексика" : "vocabulary",
"лексикография" : "lexicography",
"лексикон" : "lexicon",
"лексический" : "lexical"
};
