var dicctr_14 = {
"выразить" : "express show, выражать словами put into words",
"вырастать" : "grow, increase, develop into, emerge appear",
"вырасти" : "grow, increase, develop into, emerge appear",
"вырастить" : "grow, breed, bring up, fig. train",
"выращивать" : "grow, breed, bring up, fig. train",
"вырвать" : "s. вырывать1, s. рвать 3)",
"вырвать с корнем" : "pull up by the roots",
"вырезать" : "cut out clip, carve, engrave, slaughter",
"вырезка" : "cutting  clipping, carving, engraving, tenderloin",
"вырезной" : "carved",
"выровнять" : "level engin. plane, smooth, -ся straighten, milit. dress, develop grow up",
"выродиться" : "degenerate",
"выродок" : "degenerate, monster",
"вырождаться" : "degenerate",
"вырождение" : "degeneration",
"выронить" : "pf. drop",
"выросший" : "grow",
"вырубать" : "cut down #or fell, cut out #or carve",
"вырубить" : "cut down #or fell, cut out #or carve",
"выругать" : "abuse scold",
"выручать" : "help rescue relieve, redeem, commerc. gain",
"выручить" : "help rescue relieve, redeem, commerc. gain",
"выручка" : "rescue relief help, commerc. proceeds",
"вырывать1" : "pull out, tear out, snatch away, extort, -ся break away rush, escape",
"вырывать2" : "dig out up",
"вырыть" : "dig out up",
"высадить" : "land disembark, help out, make #or let a pers. get out, plant, -ся =, a. get out off",
"высадка" : "disembarkation landing",
"высаженный" : "upset",
"высаживать" : "land disembark, help out, make #or let a pers. get out, plant, -ся =, a. get out off",
"высасывать" : "suck out",
"высверливать" : "bore drill",
"высверлить" : "bore drill",
"высвободить" : "free",
"высвобождать" : "free",
"высевать" : "sow",
"высекать" : "hew carve, strike, s. сечь2",
"выселение" : "expulsion eviction, transfer",
"выселить" : "expel evict, transfer move",
"выселять" : "expel evict, transfer move",
"высеребрить" : "silver",
"высеченный" : "graven, hewn",
"высечь" : "hew carve, strike, s. сечь2",
"высеять" : "sow",
"высидеть" : "sit  stay, hatch",
"высиживать" : "sit  stay, hatch",
"выскабливать" : "scrub clean, erase",
"высказать" : "express tell give, -ся express o.s., express one's opinion thoughts etc., declare o.s.",
"высказывание" : "utterance",
"высказывать" : "express tell give, -ся express o.s., express one's opinion thoughts etc., declare o.s.",
"выскакивать" : "jump leap #or rush out",
"выскальзывать" : "slip out",
"выскоблить" : "scrub clean, erase",
"выскользать" : "slip out",
"выскользнуть" : "slip out",
"выскочить" : "jump leap #or rush out",
"выскочка" : "upstart, famil. forward pupil",
"выскребать" : "scrub clean, scratch out",
"выскрести" : "scrub clean, scratch out",
"выслать" : "s. высылать",
"выследить" : "track down",
"выслеживать" : "track down",
"выслуживать" : "famil. serve, obtain by #or for service, -ся advance rise, insinuate o.s.",
"выслужить" : "famil. serve, obtain by #or for service, -ся advance rise, insinuate o.s.",
"выслушать" : "listen  hear, med. auscultate",
"выслушивать" : "listen  hear, med. auscultate",
"высмеивание" : "derision",
"высмеивать" : "deride ridicule",
"высмеять" : "deride ridicule",
"высмолить" : "pitch tar",
"высморкаться" : "blow one's nose",
"высовывать" : "put out, -ся lean out",
"высовываться" : "hang out, hangout",
"высокий" : "high, tall, fig. lofty",
"высокоблагородие" : "Honor",
"высококачественный" : "high quality",
"высококвалифицированный" : "highly skilled",
"высокомерие" : "haughtiness",
"высокомерный" : "haughty arrogant",
"высокопарный" : "bombastic high-flown",
"высокопревосходительство" : "Excellency",
"высокоуважаемый" : "dear",
"высосать" : "suck out",
"высота" : "height, altitude, hill, level, fig. climax, высотой в ... #or ... в высоту ... high",
"высотомер" : "altimeter",
"высохнуть" : "s. высыхать",
"высохший" : "dried up withered",
"высочайший" : "highest, supreme imperial",
"высочество" : "Highness",
"выспаться" : "s. высыпаться",
"выспренний" : "bombastic",
"выставить" : "s. выставлять",
"выставка" : "exhibition show",
"выставлять" : "put out put forward, exhibit display expose, present, mark provide, milit. post, popul. turn out; See also: выставлять напоказ",
"выставлять напоказ" : "show off",
"выставляться" : "come out emerge",
"выставочный" : "exhibition show...",
"выстилать" : "inlaid",
"выстраивать" : "s. строить",
"выстрел" : "shot, snapshot",
"выстукивать" : "strike tap, med. percuss",
"выступ" : "projection",
"выступать" : "step forth forward, come #or stand out, appear, set out march off, speak in public, выступать с речью, deliver a speech, выступать в поход milit. take the field",
"выступающий" : "obtrusive, projecting, protrusive, salient",
"выступить" : "step forth forward, come #or stand out, appear, set out march off, speak in public, выступать с речью, deliver a speech, выступать в поход milit. take the field",
"выступление" : "appearance, departure, pol. speech declaration, thea. performance turn",
"высунуть" : "put out, -ся lean out",
"высушенный" : "dried",
"высушивать" : "dry, drain fig. exhaust",
"высушить" : "dry, drain fig. exhaust",
"высший" : "highest supreme, higher  superior, высшая мера наказания, supreme penalty capital punishment",
"высылать" : "send forward, send out away, banish",
"высылка" : "dispatch, exile",
"высыпать" : "pour out #or in on, swarm forth out",
"высыпаться" : "sleep one's fill  have a good night's rest",
"высыхать" : "dry up wither",
"высь" : "height",
"выталкиватель" : "ejector",
"выталкивать" : "push out",
"вытапливать" : "heat, melt",
"вытаращить" : "~ глаза stare",
"вытащенный" : "drawn",
"вытекающий" : "effluent, ensuing",
"вытребовать" : "pf. ask for demand order summon, obtain on demand",
"вытрясать" : "shake out",
"вытрясти" : "shake out",
"выть" : "howl",
"вытягивание" : "elongation, extension",
"вытягивать" : "draw pull #or stretch, drain, famil. elicit, endure bear, -ся stretch extend, milit. come to attention, famil. grow",
"вытяжка" : "drawing stretching, chem. extract, на вытяжку milit. at attention",
"вытянутый" : "prolate, splay",
"вытянуть" : "draw pull #or stretch, drain, famil. elicit, endure bear, -ся stretch extend, milit. come to attention, famil. grow",
"выудить" : "fish out",
"выуживать" : "fish out",
"выутюжить" : "iron, stroke",
"выучивать" : "learn memorize, teach",
"выучить" : "learn memorize, teach",
"выучиться" : "learn",
"выхаживать" : "rear bring up, nurse restore to health, go over through",
"выхватить" : "snatch away from out, snap up off",
"выхватывать" : "snatch away from out, snap up off",
"выхлоп" : "exhaust",
"выхлопной" : "exhaust...",
"выхлопотать" : "pf. obtain",
"выход" : "exit, way out, outlet, departure, withdrawal retirement, appearance publication, thea. entrance  performance, yield output; See also: выход замуж, выход в отставку",
"выход в отставку" : "retirement resignation",
"выход замуж" : "marriage",
"выходец" : "immigrant native of, come #or originate from",
"выходить" : "rear bring up, nurse restore to health, go over through",
"выходить1" : "go #or come out leave, get out off, withdraw retire, appear be published #or issued, come off, turn out result, happen arise originate, spend use up run out of, commerc. become due, окно выходит на улицу the window faces the street, из него вышел ... he has become ..., из этого ничего не выйдет nothing will come of it, famil. вышло! it's clicked!, marry; See also: выйти в офицеры, выйти в отставку, выйти на пенсию, выйти за пределы, выйти за, выйти из себя, выйти из терпения, выйти из строя",
"выходить2" : "s. выхаживать",
"выходка" : "trick prank, excess",
"выходной" : "exit..., outlet..., holiday..., festive; See also: выходной день",
"выходной день" : "holiday day off",
"выхоленный" : "well-groomed",
"выхухоль" : "desman, muskrat",
"выцвести" : "fade wither",
"выцветать" : "fade wither",
"вычеканить" : "mint coin, chase",
"вычеркивание" : "cancellation, deletion",
"вычеркивать" : "strike out obliterate",
"вычеркнуть" : "strike out obliterate",
"вычерпать" : "scoop, dredge",
"вычерпнуть" : "scoop, dredge",
"вычерпывать" : "scoop, dredge",
"вычесть" : "s. вычитать",
"вычет" : "deduction",
"вычисление" : "calculation",
"вычислить" : "calculate compute",
"вычислять" : "calculate compute",
"вычистить" : "s. вычищать",
"вычитаемое" : "subtrahend",
"вычитание" : "subtraction",
"вычитать" : "deduct, math. subtract",
"вычищать" : "clean scrub brush polish",
"вычурный" : "ornate flowery, fanciful",
"вышвырнуть" : "pf. turn out",
"выше" : "higher, above, beyond, он ~ меня he is taller than I, это ~ моего понимания that's beyond my reach",
"вышеупомянутый" : "aforementioned, aforesaid, said",
"вышибать" : "knock #or throw out",
"вышибить" : "knock #or throw out",
"вышивание" : "embroidery",
"вышивать" : "embroider",
"вышивка" : "embroidery",
"вышина" : "height, cf. высота",
"вышить" : "embroider",
"вышка" : "tower",
"выявить" : "discover uncover reveal",
"выявлять" : "discover uncover reveal",
"выяснение" : "clarification",
"выяснить" : "clear up find out ascertain, -ся turn out, come to light",
"выяснять" : "clear up find out ascertain, -ся turn out, come to light",
"вьедаться" : "eat",
"вьезд" : "entrance entry, ascent, разрешение на вьезд entry permit",
"вьезжать" : "enter ride #or drive in up/on, move in",
"вьесться" : "eat",
"вьетнам" : "vietnam",
"вьехать" : "enter ride #or drive in up/on, move in",
"вьюга" : "snowstorm",
"вьюк" : "pack bale load",
"вьюн" : "loach",
"вьюнок" : "bindweed, convolvulus",
"вьючить" : "load",
"вьючный" : "pack...",
"вьющееся растение" : "creeper",
"вьющийся" : "curly; See also: вьющееся растение",
"вяжущий" : "astringent",
"вяз" : "elm",
"вязал" : "tying",
"вязанка" : "fagot",
"вязаный" : "knitted",
"вязанье" : "knitting, crochet",
"вязать" : "tie bind, knit, crochet",
"вязаться" : "impf. match agree be in keeping, famil. make sense, work  get on",
"вязкий" : "viscous sticky, swampy marshy",
"вязкость" : "viscosity",
"вязнуть" : "sink in stick",
"вялить" : "dry sun",
"вялость" : "apathy",
"вялый" : "withered faded, flabby, fig. sluggish, dull",
"вянуть" : "wither fade, droop flag",
"г" : "abbr.: грамм",
"га" : "ha!, abbr.: гектар",
"гаага" : "The Hague",
"габардин" : "gabardine",
"гаванна" : "Havana, гаванна Havana cigar",
"гавань" : "harbor",
"гавриил" : "Gabriel",
"гаврила" : "Gabriel",
"гага" : "zo. eider",
"гагара" : "loon",
"гагарка" : "auk, razor-bill",
"гад" : "reptile",
"гадалка" : "fortuneteller",
"гадание" : "fortunetelling, guessing conjecture",
"гадать" : "погадать tell fortunes, impf. guess conjecture",
"гадина" : "= гад",
"гадить" : "нагадить загадить famil. soil, popul. harm, изгадить popul. spoil botch",
"гадкий" : "nasty ugly disgusting repulsive",
"гадливый" : "squeamish",
"гадость" : "vermin, villainy ugly thing",
"гадюка" : "zo. viper  adder",
"гаечный ключ" : "wrench",
"газ" : "gas, светильный газ coal gas, дать ~ mot. step on the gas, на полном газе at full speed, med. flatulences, gauze",
"газель" : "gazelle",
"газета" : "newspaper",
"газетный" : "news...",
"газетный киоск" : "newsstand Brt. news stall",
"газетчик" : "newsman newsboy",
"газированная вода" : "soda water"
};
