var dicctr_62 = {
"по-дружески" : "friendly",
"подружиться" : "pf. make friends",
"подрумянить" : "pf. redden",
"подручный" : "assistant, helper",
"подрыв" : "undermining, blowing up",
"подрывать" : "подрыть sap undermine, подорвать blow up blast spring, fig. undermine",
"подрывающий" : "disruptive",
"подрывной" : "blasting explosive, subversive",
"подряд" : "adv. successive running, one after another, contract",
"подрядчик" : "contractor",
"подсадить" : "help, plant",
"подсаживать" : "help, plant",
"подсаживаться" : "sit down",
"подсвечник" : "candlestick",
"подсесть" : "sit down",
"подсинить" : "blue",
"подсказать" : "prompt",
"подсказка" : "prompting",
"подсказывать" : "prompt",
"подскакать" : "pf. gallop",
"подскакивать" : "run, jump up",
"подскочить" : "run, jump up",
"подсластить" : "sweeten",
"подслащивать" : "sweeten",
"подследственный" : "on trial",
"подслеповатый" : "weak-sighted",
"подслушать" : "eavesdrop, overhear",
"подслушивать" : "eavesdrop, overhear",
"подслушивающий" : "eavesdropper",
"подсматривать" : "spy peep",
"подсмеиваться" : "laugh",
"подсмотреть" : "spy peep",
"подснежник" : "snowdrop",
"подсобный" : "subsidiary by-... side... subordinate",
"подсовывать" : "push shove, present, famil. palm",
"подсознательный" : "subconscious",
"подсолнечник" : "sunflower",
"подсолнух" : "sunflower",
"подсохнуть" : "s. подсыхать",
"подспорье" : "help support",
"подставить" : "s. подставлять",
"подставка" : "support prop stay, stand, saucer",
"подставлять" : "put place set, move up, expose, math. substitute; See also: подставлять ногу",
"подставлять ногу" : "#or ножку trip up",
"подставное лицо" : "dummy",
"подставной" : "false straw...; See also: подставное лицо",
"подстановка" : "substitution",
"подстанция" : "substation",
"подстерегать" : "lie in wait of, pf. trap",
"подстеречь" : "lie in wait of, pf. trap",
"подстилать" : "spread",
"подстилка" : "bedding, spreading",
"подстраивать" : "arch. build add, mus. tune, plot",
"подстрекатель" : "instigator monger",
"подстрекательство" : "instigation",
"подстрекать" : "incite, stir up provoke",
"подстрекнуть" : "incite, stir up provoke",
"подстреливать" : "hit wound",
"подстрелить" : "hit wound",
"подстригать" : "cut crop clip, trim lop",
"подстричь" : "cut crop clip, trim lop",
"подстроить" : "arch. build add, mus. tune, plot",
"подстрочный" : "interlinear, foot",
"подступ" : "approach",
"подступать" : "approach, rise, press",
"подступить" : "approach, rise, press",
"подсудимый" : "defendant",
"подсудность" : "jurisdiction",
"подсудный" : "cognizable, justiciable",
"подсунуть" : "push shove, present, famil. palm",
"подсчет" : "calculation computation cast",
"подсчитать" : "count  compute",
"подсчитывать" : "count  compute",
"подсылать" : "send",
"подсыпать" : "add pour",
"подсыхать" : "dry",
"подталкивать" : "push, nudge",
"подтасовать" : "shuffle, garble",
"подтасовывать" : "shuffle, garble",
"подтачивать" : "eat, wash, sharpen, fig. undermine",
"подтвердить" : "confirm corroborate, acknowledge, -ся prove true",
"подтверждать" : "confirm corroborate, acknowledge, -ся prove true",
"подтверждение" : "confirmation, acknowledgment",
"подтек" : "bloodshot spot",
"подтереть" : "s. подтирать",
"подтирать" : "wipe",
"подтолкнуть" : "push, nudge",
"подточить" : "eat, wash, sharpen, fig. undermine",
"подтрунивать" : "tease banter chaff",
"подтрунить" : "tease banter chaff",
"подтягивать" : "pull, draw, tighten, raise, wind #or key up egg on, join in, -ся chin, brace up, improve pick up",
"подтяжки" : "suspenders, Brt. braces",
"подтянуть" : "pull, draw, tighten, raise, wind #or key up egg on, join in, -ся chin, brace up, improve pick up",
"подумать" : "think, reflect meditate, intend be going to, care, famil. suspect, как ты думаешь? what do you think?, много думать о себе be conceited, не долго думая without hesitation, -ся seem appear, think",
"подумывать" : "think",
"подурнеть" : "grow plain #or ugly",
"подуть" : "blow, дует there is a draught",
"подучать" : "s. учить",
"подучить" : "s. учить",
"подушечка" : "hassock",
"подушка" : "pillow, cushion pad",
"подхалим" : "toady lickspittle",
"подхватить" : "catch, pick up, take up, join in",
"подхватывать" : "catch, pick up, take up, join in",
"подход" : "approach",
"подходить" : "approach go, arrive come, suit fit",
"подходящий" : "suitable fit appropriate, convenient",
"подцепить" : "hook, pick up catch",
"подцеплять" : "hook, pick up catch",
"подчас" : "at times sometimes",
"подчеркивать" : "underline, stress",
"подчеркнуть" : "underline, stress",
"подчинение" : "submission, subjection, gr. hypotaxis",
"подчиненный" : "subordinate",
"подчинить" : "subject subdue, subordinate, put under supervision, -ся submit, obey",
"подчинять" : "subject subdue, subordinate, put under supervision, -ся submit, obey",
"подчиняться" : "submit",
"подчищенное" : "erasure",
"подшефный" : "sponsored",
"подшивать" : "sew on, hem, file",
"подшипник" : "bearing",
"подшить" : "sew on, hem, file",
"подшутить" : "play a trick",
"подшучивание" : "persiflage",
"подшучивать" : "play a trick",
"подъем" : "acclivity, elevation, heave, heaving, hoist, lift",
"подымать" : "s. поднимать",
"подьездной" : "rail. branch",
"подьезжать" : "drive #or ride up  approach, famil. drop in, make up to",
"подьем" : "lift, ascent rise, enthusiasm, instep; See also: легок на подьем, тяжел на подьем",
"подьемная сила" : "carrying capacity",
"подьемник" : "elevator lift hoist",
"подьемные" : "pl. traveling expenses",
"подьемный" : "подьемный мост; See also: подьемная сила, подьемные",
"поезд" : "train",
"поездка" : "excursion, sally, trip",
"пожадничать" : "be greedy #or avaricious",
"пожалеть" : "pity, regret, spare, grudge",
"пожаловать" : "reward award, give, appoint, famil. like, come, -ся complain, famil. inform, jur. sue go to law",
"пожалуй" : "maybe perhaps, I suppose",
"пожалуйста" : "please, a. что, скажи пожалуйста! I say!",
"пожалуйте" : "come in please, пожалуйте сюда! this way please, & добро2",
"пожар" : "fire, conflagration",
"пожарище" : "scene of conflagration",
"пожарник" : "fireman",
"пожарный" : "fire..., su. = пожарник, cf. команда",
"пожатие" : "shake",
"пожать" : "reap harvest",
"пожелание" : "wish, request",
"пожелать" : "wish  desire, love",
"пожелтелый" : "yellow faded",
"пожелтеть" : "grow #or turn yellow, impf. appear #or show yellow",
"пожертвование" : "donation",
"пожертвовать" : "sacrifice, give",
"пожива" : "s.",
"поживать" : "famil. live, как поживаете?, how are you ?",
"поживиться" : "famil. = нажить",
"пожизненный" : "life...",
"пожилой" : "elderly",
"пожимание" : "shrug",
"пожимать" : "s. жать1",
"пожимать плечами" : "shrug one's shoulders",
"пожинать" : "s. жать2",
"пожирать" : "eat up, devour",
"пожитки" : "belongings things, со всеми пожитками with bag & baggage",
"пожрать" : "eat up, devour",
"пожурить" : "scold rebuke",
"поза" : "pose posture attitude",
"позаботиться" : "care  take care of look after, worry be anxious",
"позавидовать" : "envy  be envious",
"позавтракать" : "breakfast",
"позавчера" : "the day before yesterday",
"позади" : "behind, past",
"позапрошлый" : "the ... before last",
"позволение" : "permission  leave",
"позволительно" : "one may",
"позволительный" : "permissible",
"позволить" : "allow  permit; See also: позволять себе",
"позволь" : "may I, let, I say",
"позволять" : "allow",
"позвонок" : "vertebra",
"позвоночник" : "backbone, chine, spine",
"позвоночный" : "vertebral, vertebrate",
"позднее" : "later",
"поздний" : "late",
"поздороваться" : "greet #or salute  welcome, wish good morning etc.; See also: здороваться за руку",
"поздоровиться" : "pf.: ему не поздоровится, he will pay for it",
"поздравитель" : "congratulator",
"поздравительный" : "congratulatory",
"поздравить" : "s. поздравлять",
"поздравление" : "congratulation, pl. compliments",
"поздравлять" : "congratulate  wish, send one's compliments",
"позеленеть" : "grow turn #or be green, impf. appear #or show green",
"позер" : "poseur",
"позже" : "later, не ~ ... at the latest",
"позитивный" : "positive",
"позитрон" : "positron",
"позиционный" : "trench... position...",
"позиция" : "position, milit. line, fig. attitude",
"познавательный" : "cognitive",
"познавать" : "perceive, know",
"познакомить" : "introduce, acquaint",
"познание" : "perception, pl. knowledge",
"познания" : "knowledge",
"познать" : "perceive, know",
"позолота" : "gilding",
"позолотить" : "gild",
"позор" : "shame disgrace infamy",
"позорить" : "dishonor disgrace",
"позорный" : "shameful disgraceful infamous ignominious",
"позорный столб" : "pillory",
"позыв" : "desire, impulse",
"поиграть" : "play, gamble, rage, sparkle, a. act",
"поименный" : "of names, by call",
"поименовать" : "pf. name",
"поимка" : "capture",
"поимущественный" : "property...",
"поискать" : "look for, seek, jur. sue",
"поиски" : "search  quest",
"поистине" : "truly really",
"поить" : "water, give to drink",
"пойло" : "swill",
"поймать" : "catch, trap, grasp seize; See also: поймать на слове",
"поймать на слове" : "take at one's word",
"пойти" : "go walk, come, run pass drive sail fly etc., follow a. go for fetch, leave, move  flow drift blow, enter  join  become, proceed be in progress take place, be on, lead, attack, spread, receive, commerc. sell, engin. work, be used spent, be sent to, suit, marry, ему идет #or пошел шестой год, he is over #or past five; See also: идти в счет, идти на веслах, пойти по отцу, идет{!}, пошел{!}, пошли{!}, дело идет о, речь идет о",
"пойти по отцу" : "take after one's father",
"пока" : "for the time being, meanwhile, while, ~ until, пока! famil. so long! see you later",
"показ" : "demonstration, showing",
"показание" : "evidence, engin. indication",
"показатель" : "math. exponent, index, figure",
"показательный" : "significant, demonstrative, model, show",
"показать" : "s. показывать",
"показной" : "catchpenny, flashy, grandstand, meretricious",
"показывать" : "evince, shown",
"покарать" : "punish",
"покараулить" : "guard watch",
"покатать" : "drive ride row etc.",
"покатить" : "roll drive wheel",
"покатость" : "declivity, slope slant",
"покатый" : "slanting sloping, retreating",
"покачивание" : "jiggle, wiggle",
"покаяние" : "penance, penitence, repentance",
"покаянный" : "penitential",
"покаяться" : "repent",
"поквитаться" : "pf. settle accounts",
"покидать" : "leave quit, abandon desert",
"покинутый" : "derelict, forlorn, forsaken, lonesome, lorn",
"покинуть" : "leave quit, abandon desert",
"покладая" : "не покладая рук",
"поклон" : "bow"
};
