var dicctr_33 = {
"кокетливый" : "coquettish",
"кокетничать" : "coquet flirt",
"кокетство" : "coquetry",
"коклюш" : "whooping cough",
"кокон" : "cocoon",
"кокос" : "coco",
"кокосовый" : "coco...",
"кокс" : "coke",
"коктейль" : "cocktail",
"кол" : "stake pale, s. единица; See also: ни кола ни двора",
"кола" : "cola, kola",
"колбаса" : "sausage",
"колдовать" : "conjure",
"колдовской" : "voodoo, witching",
"колдовство" : "magic sorcery",
"колдун" : "sorcerer magician wizard",
"колдунья" : "sorceress enchantress",
"колебание" : "oscillation, vibration, fig. vacillation hesitation, fluctuation",
"колебать" : "shake, -ся shake, fluctuate, waver vacillate hesitate, oscillate vibrate",
"колебаться" : "fluctuate, hesitate, oscillate, seesaw, vacillate",
"колеблющийся" : "hesitant, vacillating, wavy",
"колебнуть" : "shake, -ся shake, fluctuate, waver vacillate hesitate, oscillate vibrate",
"колено" : "knee, стать на колени kneel, bot. joint knot, bend, engin. crank, degree branch, mus. pas, trick",
"коленчатый" : "biol. geniculate, engin. crank",
"колесико" : "trundle",
"колесить" : "travel, take a roundabout way",
"колесница" : "chariot",
"колесо" : "wheel, кружиться как белка в колесе fuss bustle about, вставлять палки в колеса put a spoke in a pers.'s wheel, ноги колесом bowlegged",
"колечко" : "annulet, ringlet",
"колея" : "rut track",
"колибри" : "hummingbird",
"колики" : "colic gripes",
"количественный" : "quantitative, gr. cardinal",
"количество" : "quantity, number, amount, по количеству quantitatively",
"колка" : "splitting chopping",
"колкий" : "prickly, biting pungent",
"колкость" : "sarcasm gibe",
"коллаж" : "collage",
"коллега" : "colleague",
"коллегиальный" : "collegiate",
"коллегия" : "board staff, college",
"коллектив" : "collective group body",
"коллективизация" : "collectivization",
"коллективный" : "collective",
"коллектор" : "el. collector",
"коллекционер" : "collector",
"коллекция" : "collection",
"колода" : "block, trough, pack deck",
"колодец" : "well, shaft pit",
"колодка" : "last, stock, engin. shoe",
"колодник" : "convict",
"колокол" : "bell",
"колокола" : "chime",
"колокольня" : "bell tower belfry",
"колокольчик" : "bell, bot. bellflower",
"колониальный" : "colonial",
"колонизация" : "colonization",
"колонизовать" : "pf. colonize",
"колонка" : "column",
"колонна" : "column",
"колоннообразный" : "columnar",
"колоратура" : "coloratura",
"колоритный" : "racy",
"колос" : "ear",
"колоситься" : "ear",
"колосник" : "grate",
"колосники" : "gridiron",
"колосс" : "colossus",
"колотить" : "knock",
"колотый" : "lump, уколоть once кольнуть prick sting, famil. taunt, заколоть stab, kill slaughter, impers. have a stitch",
"колоть" : "расколоть split cleave, break, crack, наколоть chop; See also: колотый, колоть глаза",
"колоть глаза" : "be a thorn in one's side",
"колпак" : "cap, shade, bell glass",
"колумбия" : "colombia",
"колхоз" : "collective farm kolkhoz",
"колхозник" : "collective farmer",
"колхозница" : "collective farmer",
"колхозный" : "kolkhoz...",
"колчан" : "quiver",
"колчедан" : "pyrites",
"колыбель" : "cradle",
"колыбельная" : "lullaby",
"колыхать" : "sway swing, stir, heave, flicker, колыхаться",
"колыхнуть" : "sway swing, stir, heave, flicker, колыхаться",
"колышек" : "peg",
"кольнуть" : "& impers.",
"кольраби" : "kohlrabi",
"кольцевидный" : "gyrate",
"кольцевой" : "ring..., circular",
"кольцеобразный" : "annular",
"кольцо" : "ring, circle",
"кольчатый" : "annulate",
"кольчуга" : "mail",
"колья" : "pegging",
"колючий" : "thorny prickly, barbed, s. колкий",
"колючка" : "thorn prickle, barb",
"колюшка" : "stickleback",
"коля" : "Nick",
"коляска" : "carriage victoria, baby carriage Brt. perambulator",
"ком" : "lump clod; See also: снежный ком",
"команда" : "command, detachment, nav. crew, #sport: team, company  Brt. brigade, famil. gang",
"командир" : "commander",
"командировать" : "a. откомандировать send, detach",
"командировка" : "mission, sending",
"командный" : "command, team...",
"командование" : "command",
"командовать" : "command, famil. domineer",
"командующий" : "commander",
"комар" : "mosquito gnat",
"комбайн" : "combine",
"комбинат" : "combine of complementary industrial plants",
"комбинаторный" : "combinatorial",
"комбинация" : "combination",
"комбинезон" : "overalls",
"комбинировать" : "combine",
"комедия" : "comedy, famil. farce",
"комендант" : "commandant, superintendent",
"комендатура" : "commandant's office",
"комета" : "comet",
"комизм" : "comicality",
"комик" : "comedian comic",
"коминтерн" : "Communist International (#1919-#194",
"комиссар" : "commissar, commissioner",
"комиссариат" : "commissariat",
"комиссионер" : "commissionaire, middleman",
"комиссионный" : "commission",
"комиссия" : "commission  committee",
"комитет" : "committee",
"комический" : "comic funny",
"комичный" : "comic funny",
"комкать" : "crumple",
"комковатый" : "lumpy",
"комментарий" : "comment",
"комментатор" : "commentator",
"комментировать" : "pf. comment",
"коммерсант" : "merchant",
"коммерческий" : "commercial",
"коммивояжер" : "tout",
"коммодор" : "commodore",
"коммуна" : "commune",
"коммунальный" : "municipal",
"коммунизм" : "communism",
"коммуникация" : "communication",
"коммунист" : "communist",
"коммунистический" : "communist",
"коммунистка" : "communist",
"коммутатор" : "commutator, teleph. switchboard, operator",
"коммутировать" : "commutate",
"комната" : "room",
"комнатный" : "room..., bot. indoor",
"комод" : "bureau Brt. chest of drawers",
"комок" : "lump clod",
"компания" : "company, водить компанию с associate with",
"компаньон" : "commerc. partner, famil. companion",
"компартия" : "Communist Party",
"компас" : "compass",
"компендиум" : "compendium",
"компенсация" : "compensation",
"компенсировать" : "pf. compensate",
"компетентный" : "competent",
"компетенция" : "competence, line",
"компиляция" : "compilation",
"комплекс" : "complex",
"комплексный" : "complex",
"комплект" : "set",
"комплектный" : "complete",
"комплектовать" : "complete",
"комплимент" : "compliment",
"композитор" : "composer",
"компост" : "compost",
"компостировать" : "punch",
"компот" : "sauce Brt. stewed fruit",
"компресс" : "compress",
"компрессор" : "compressor",
"компрометировать" : "compromise",
"компромисс" : "compromise",
"комсомол" : "Komsomol cf. ВЛКСМ",
"комсомолец" : "Young Communist",
"комсомолка" : "Young Communist",
"комсомольский" : "Young Communist",
"кому попало" : "to the first comer",
"комфорт" : "comfort convenience",
"комфортабельный" : "comfortable convenient",
"конвейер" : "conveyor, assembly line",
"конвенция" : "convention",
"конверт" : "envelope",
"конвоир" : "convoy",
"конвоировать" : "convoy",
"конвой" : "convoy",
"конвойный" : "convoy",
"конгресс" : "congress",
"конденсат" : "condensate",
"конденсатор" : "condenser",
"конденсировать" : "pf. condense, evaporate",
"кондитер" : "confectioner",
"кондитерская" : "confectioner's shop",
"кондитерские изделия" : "pl. confectionery",
"кондоминиум" : "condominium",
"кондрат" : "Conrad",
"кондратий" : "Conrad",
"кондуктор" : "conductor",
"коневодство" : "horse breeding",
"конек" : "skate, famil. hobby",
"конец" : "end, close, point, nav. rope, famil. distance, part, case; See also: без конца, в конец, до конца, в конце, в конце концов, в один конец, в оба конца, на худой конец, под конец, третий с конца",
"конечно" : "of course certainly",
"конечности" : "extremities",
"конечность" : "limb",
"конечный" : "#philos. math. finite, final terminal, ultimate",
"конина" : "horseflesh",
"конический" : "conic, conical, taper",
"конкремент" : "concretion",
"конкретный" : "concrete",
"конкурент" : "competitor",
"конкуренция" : "competition",
"конкурировать" : "compete",
"конкурс" : "competition, commerc. bankruptcy",
"конница" : "cavalry",
"конный" : "horse..., cavalry",
"конопатить" : "calk",
"конопля" : "hemp",
"конопляный" : "hempen",
"коносамент" : "bill of lading",
"консервативный" : "conservative",
"консерватизм" : "conservatism",
"консерватория" : "conservatory Brt. school of music conservatoire",
"консервировать" : "conserve preserve, can Brt. tin",
"консервная фабрика" : "cannery",
"консервный" : "консервная фабрика",
"консервы" : "preserve",
"конский" : "horsy",
"конспект" : "conspectus, epitome, precis",
"конституция" : "constitution",
"конструировать" : "a. сконструировать design",
"конструктор" : "designer",
"конструкция" : "design, construction",
"консул" : "consul",
"консульский" : "consular",
"консульство" : "consulate",
"консультант" : "consultant",
"консультация" : "consultation, advice, advisory board",
"консультировать" : "advise, -ся consult",
"контакт" : "contact",
"контекст" : "context",
"контингент" : "contingent quota",
"континент" : "continent",
"континентальный" : "mainland",
"контора" : "office",
"конторский" : "office...",
"конторский служащий" : "clerk",
"конторщик" : "clerk"
};
