var dicctr_32 = {
"кивер" : "shako",
"киви" : "kiwi",
"кивнуть" : "nod, beckon, point",
"кивок" : "nod",
"кидать" : "s. бросать, менякидает в жар и холод, I'm hot and cold all over",
"киев" : "kiev",
"киевлянин" : "Kiever",
"киевлянка" : "Kiever",
"киевский" : "Kiev...",
"кизил" : "dogwood",
"кий" : "cue",
"кило" : "= килограмм",
"киловатт" : "kilowatt",
"киль" : "keel",
"кимоно" : "kimono",
"кинематический" : "kinematic",
"кинетический" : "kinetic",
"кинжал" : "dagger, dirk, poniard",
"кино" : "celluloid, close-up, movie, movies",
"киноартист" : "screen actor",
"киноартистка" : "screen actress",
"киноателье" : "studio",
"киноварь" : "cinnabar",
"киножурнал" : "newsreel",
"кинозвезда" : "filmstar",
"кинокартина" : "film",
"кинолента" : "reel film",
"кинооператор" : "cameraman",
"кинопленка" : "film",
"кинорежиссер" : "film director",
"киносеанс" : "show performance",
"киносценарий" : "scenario",
"киносьемка" : "shooting  filming",
"кинотеатр" : "movie theater cinema",
"кинохроника" : "newsreel",
"кинуть" : "s. бросать, менякидает в жар и холод, I'm hot and cold all over",
"киоск" : "kiosk, newsstand",
"кипа" : "bale",
"кипарис" : "cypress",
"кипр" : "cyprus",
"кипрский" : "cyprian",
"кипящий" : "boiling, ebullient",
"кирка" : "pickaxe",
"кирпич" : "brick",
"киска" : "kitty, pussy",
"кислая капуста" : "sauerkraut",
"кислица" : "shamrock",
"кисловатый" : "sourish",
"кислород" : "oxygen",
"кислота" : "acid",
"кислотный" : "acid, acidic",
"кислый" : "sour acid...",
"киснуть" : "turn sour, fig. get rusty",
"киста" : "cyst",
"кисточка" : "brush, tassel, кисть",
"кисть" : "brush, tassel, cluster bunch, hand",
"кит" : "whale",
"китаец" : "Chinese",
"китай" : "China",
"китайская народная республика" : "Chinese People's Republic",
"китайский" : "Chinese",
"китаянка" : "Chinese",
"китель" : "jacket",
"китобой" : "whaler",
"китобойный" : "whaler",
"китовый" : "cetacean",
"китовый ус" : "whalebone",
"кичиться" : "put on airs, boast",
"кичливый" : "haughty conceited",
"кишеть" : "teem swarm",
"кишечник" : "bowels intestines pl.",
"кишечный" : "intestinal enteric, digestive",
"кишка" : "intestine  gut, famil. bowels, hose",
"клавесин" : "harpsichord",
"клавиатура" : "clavier, keyboard",
"клавиш" : "engin. key",
"клавиша" : "engin. key",
"клад" : "treasure",
"кладбище" : "cemetery",
"кладка" : "laying work",
"кладовая" : "pantry larder, stock- #or storeroom",
"кладовщик" : "stockman storekeeper",
"кладь" : "freight load",
"клаксон" : "klaxon",
"клан" : "clan, sept",
"кланяться" : "bow, greet, кланяйтесь ему от меня give him my regards, famil. cringe, present",
"клапан" : "engin. valve, mus. key stop",
"кларнет" : "clarinet",
"класс" : "class, #school: grade Brt. form, classroom",
"классик" : "classic",
"классификация" : "classification",
"классифицировать" : "pf. class",
"классический" : "classic",
"классный" : "class",
"классовый" : "class",
"класть" : "положить put, lay  deposit, apply spend, take, famil. fix, rate, make, leave, сложить lay, erect",
"класть в кучу" : "pile up",
"клевать" : "peck pick, bite; See also: клюнуть носом",
"клевер" : "clover trefoil",
"клевета" : "slander",
"клеветать" : "slander",
"клеветник" : "slanderer",
"клеветнический" : "slanderous",
"клеврет" : "accomplice",
"клеенка" : "oilcloth",
"клеенчатый" : "oilcloth",
"клеить" : "glue paste",
"клеиться" : "stick, famil. work get on #or along",
"клей" : "glue paste, рыбий клей isinglass",
"клейкий" : "sticky adhesive",
"клеймить" : "brand, a. stigmatize",
"клеймо" : "brand, fig. stigma stain, фабричное клеймо trademark",
"клен" : "maple",
"клепать" : "rivet, hammer",
"клепка" : "riveting, stave",
"клест" : "crossbill",
"клетка" : "cage, square check, biol. cell, в клетку checked Brt. chequered",
"клетчатка" : "cellulose, cellular tissue",
"клетчатый" : "checkered, cellular",
"клецка" : "doughboy",
"клешня" : "claw",
"клещи" : "pincers",
"клиент" : "client",
"клизма" : "enema",
"клик" : "cry shout, shriek",
"клика" : "clique",
"кликать" : "shriek, popul. call",
"кликнуть" : "shriek, popul. call",
"климат" : "climate",
"климатический" : "climatic",
"клин" : "wedge, gusset",
"клиника" : "clinic",
"клинок" : "blade",
"клином" : "pointed, свет не клином сошелся the world is large, there is always a way out",
"клистрон" : "klystron",
"клитор" : "clitoris",
"клич" : "call, cry",
"кличка" : "name, nickname",
"клише" : "cliche",
"клок" : "tuft, shred rag tatter piece frazzle",
"клокотать" : "seethe bubble",
"клонить" : "bend bow, fig. incline, drive at, obsol. cast down, меня клонит ко сну I am sleepy",
"клоп" : "bedbug Brt. bug",
"клоун" : "clown",
"клочок" : "wisp, scrap",
"клуб1" : "cloud puff, a. клубок",
"клуб2" : "club",
"клубень" : "tuber bulb",
"клубить" : "puff  whirl coil",
"клубника" : "strawberry -ries pl.",
"клубок" : "clew, tangle",
"клумба" : "bed",
"клык" : "tusk, canine fang",
"клюв" : "beak bill",
"клюка" : "crutch staff",
"клюква" : "cranberry -ries pl.",
"клюнуть" : "peck pick, bite; See also: клюнуть носом",
"клюнуть носом" : "famil. nod",
"ключ" : "key, mus. clef, spring source, arch. keystone, engin. = гаечный ключ; See also: английский ключ",
"ключица" : "clavicle collarbone",
"ключница" : "housekeeper",
"клюшка" : "club",
"клякса" : "blot",
"клянчить" : "beg for",
"кляп" : "gag",
"клясть" : "= проклинать cf.",
"клясться" : "swear",
"клятва" : "oath, дать клятву take an oath swear",
"клятвопреступление" : "perjury",
"кляуза" : "intrigue denunciation, obsol. captious suit, pettifoggery",
"кляча" : "jade",
"книга" : "book, teleph. directory, register",
"книгопечатание" : "printing typography",
"книгопродавец" : "bookseller",
"книгохранилище" : "archives storerooms pl., library",
"книжка" : "book, notebook, passport",
"книжный" : "book..., bookish",
"книжонка" : "trashy book",
"книзу" : "down downward",
"кнопка" : "thumbtack Brt. drawing pin, el. button, patent fastener",
"кнопочный" : "pushbutton",
"кнут" : "whip knout scourge",
"княгиня" : "princess",
"князь" : "prince, великий князь grand duke",
"коала" : "koala",
"коалиционный" : "coalition ...",
"коалиция" : "coalition",
"кобальтовый" : "cobaltic",
"кобра" : "cobra",
"кобура" : "holster, saddlebag",
"кобыла" : "mare, #sport: horse",
"кобылица" : "filly",
"кованый" : "wrought",
"коварный" : "artful guileful insidious",
"коварство" : "craft guile wile",
"ковать" : "выковать forge, подковать shoe",
"ковбой" : "cowboy",
"ковер" : "carpet rug",
"коверкать" : "distort deform, mutilate, murder",
"ковка" : "forging, shoeing",
"ковкий" : "malleable",
"коврижка" : "gingerbread",
"ковчег" : "ark; See also: Ноев ковчег",
"ковш" : "scoop, bucket, haven",
"ковыль" : "feather grass",
"ковылять" : "toddle, stump limp",
"ковырять" : "pick poke",
"когда" : "when, famil. if, ever, sometimes, cf. ни",
"когда-либо" : "some time  one day, interr. ever",
"когда-нибудь" : "some time  one day, interr. ever",
"когда-то" : "once one day sometime",
"кого" : "whom",
"коготь" : "claw",
"код" : "code",
"кода" : "coda",
"кодекс" : "code, codex",
"кое-где" : "here & there in some places",
"кое-как" : "anyhow somehow, with difficulty",
"кое-какой" : "some, any",
"кое-когда" : "off & on",
"кое-кто" : "some",
"кое-куда" : "here & there to some place somewhere",
"кое-что" : "something some things",
"кожа" : "skin, leather, из кожи лезть famil. do one's utmost",
"кожаный" : "leather...",
"кожевенный" : "leather...; See also: кожевенный завод",
"кожевенный завод" : "tannery",
"кожевник" : "tanner",
"кожица" : "peel, rind, cuticle",
"кожный" : "cutaneous, dermal",
"кожура" : "hull, peel, rind",
"коза" : "goat",
"козел" : "goat",
"козел отпущения" : "scapegoat",
"козерог" : "capricorn, ibex",
"козий" : "goat...",
"козленок" : "kid",
"козлобородник" : "salsify",
"козлы" : "box, trestle",
"козни" : "intrigues plots",
"козуля" : "roe",
"козырек" : "peak",
"козырнуть" : "trump, boast, milit. salute",
"козырь" : "trump",
"козырять" : "trump, boast, milit. salute",
"койка" : "cot, bed",
"койот" : "coyote",
"кока" : "coca",
"кокаин" : "cocaine",
"кокетка" : "coquette"
};
