var dicctr_34 = {
"контрабанда" : "contraband, заниматься контрабандой smuggle",
"контрабандист" : "smuggler",
"контрабас" : "contrabass, double bass",
"контрагент" : "contractor",
"контр-адмирал" : "real admiral",
"контракт" : "contract",
"контрапункт" : "counterpoint",
"контраст" : "contrast",
"контрастировать" : "contrast",
"контратака" : "counterattack",
"контрибуция" : "contribution",
"контролер" : "inspector",
"контролировать" : "control check",
"контроль" : "control checkup",
"контрольная работа" : "test",
"контрольный" : "control... check...",
"контрразведка" : "counterespionage secret service",
"контрреволюция" : "counterrevolution",
"контузить" : "pf. bruise contuse",
"контузия" : "contusion bruise",
"контур" : "contour outline",
"конура" : "kennel",
"конус" : "cone",
"конусообразный" : "conic",
"конфедерация" : "confederacy, confederation",
"конференция" : "conference",
"конфета" : "candy Brt. sweet",
"конфеты" : "candy",
"конфиденциальность" : "privacy",
"конфиденциальный" : "confidential",
"конфискация" : "confiscation, forfeiture, seizure, sequestration",
"конфисковать" : "pf. confiscate",
"конфитюр" : "confiture, marmalade",
"конфликт" : "conflict",
"конфронтация" : "confrontation",
"конфузить" : "embarrass confuse",
"конфузливый" : "bashful shy",
"концентрат" : "concentrate",
"концентрационный" : "s. концлагерь",
"концентрировать" : "concentrate",
"концентрический" : "concentric",
"концерт" : "concert, mus. concerto",
"концертино" : "concertina",
"концессионер" : "concessionaire",
"концлагерь" : "concentration camp",
"кончать" : "finish end, graduate from, popul. stop",
"кончаться" : "eventuate",
"кончено" : "famil. enough!",
"кончик" : "tip",
"кончина" : "demise",
"конь" : "steed",
"конькобежец" : "skater",
"коньяк" : "brandy, cognac",
"конюх" : "hostler, ostler",
"копание" : "digging",
"копать" : "dig",
"копаться" : "dig root, rummage, dawdle",
"копейка" : "kopeck",
"копенгаген" : "copenhagen",
"копи" : "mine pit",
"копилка" : "money box",
"копировальная бумага" : "carbon paper",
"копировать" : "copy",
"копировщик" : "copyist",
"копить" : "save, store up",
"копия" : "copy",
"копна" : "stack",
"копоть" : "soot lampblack",
"копошиться" : "swarm, famil. stir, mess around",
"копра" : "copra",
"коптильня" : "smokehouse",
"коптить" : "smoke, soot",
"копчик" : "coccyx",
"копыто" : "hoof",
"копье" : "spear",
"кора" : "bark, crust",
"кораблекрушение" : "shipwreck",
"кораблестроение" : "shipbuilding",
"кораблик" : "nautilus",
"корабль" : "ship, nave",
"коралл" : "coral",
"коралловый" : "coral... coralline",
"коран" : "alcoran, koran",
"корвет" : "corvette",
"кордильеры" : "Cordilleras",
"кореец" : "Korean",
"корейский" : "Korean",
"коренастый" : "thickset stocky",
"корениться" : "root",
"коренной" : "native aboriginal, fundamental radical, molar",
"корень" : "root; See also: в корне, пустить корни, вырвать с корнем",
"коренья" : "roots",
"корешок" : "rootlet, stalk, back, stub Brt. counterfoil",
"корея" : "Korea",
"кореянка" : "Korean",
"корзина" : "basket",
"коридор" : "corridor, hallway",
"коридорный" : "bellboy, boots",
"корифей" : "fig. luminary corypheus leader",
"корифена" : "dorado",
"корица" : "cinnamon",
"коричневый" : "brown",
"корка" : "crust, rind peel",
"корковый" : "cortical",
"корм" : "fodder, seed",
"корма" : "stern",
"кормилец" : "breadwinner",
"кормилица" : "wet nurse",
"кормить" : "feed; See also: кормить грудью",
"кормить грудью" : "nurse, famil. board",
"кормиться" : "live on",
"кормление" : "feeding, nursing",
"кормовой" : "feed fodder..., nav. stern...",
"корнеплоды" : "edible roots",
"корнет" : "cornet",
"корнуоллский" : "cornish",
"короб" : "basket",
"коробейник" : "hawker",
"коробить" : "warp, fig. offend sicken",
"коробка" : "box case",
"корова" : "cow, дойная корова milch cow",
"коровий" : "cow...",
"коровка" : "божья коровка",
"коровяк" : "mullein",
"королева" : "queen",
"королевский" : "kingly, queenly, regal, royal",
"королевство" : "kingdom",
"королек" : "kinglet",
"король" : "king",
"корона" : "coronet, crown, diadem",
"коронарный" : "coronary",
"коронование" : "glans",
"короткий" : "short",
"короткое замыкание" : "el. short circuit",
"короче" : "in a word in short",
"корпус" : "body, frame case, building, corps",
"корректив" : "correction",
"корректировать" : "correct, typ. proofread",
"корректный" : "correct proper",
"корректор" : "proofreader",
"корректура" : "proof, держать корректуру s. корректировать",
"корреспондент" : "correspondent",
"корреспонденция" : "correspondence",
"коррозия" : "corrosion, staining",
"корсаж" : "bodice",
"корсет" : "corset a. stays pl.",
"кортеж" : "cortege",
"кортик" : "cutlass hanger",
"корточки" : "сесть на корточки; See also: сидеть на корточках",
"корчиться" : "squirm, writhe",
"коршун" : "vulture",
"корыстный" : "selfish self-interested, корыстолюбивый",
"корыстолюбивый" : "greedy  mercenary",
"корыстолюбие" : "self-interest greed",
"корысть" : "gain profit, use, greed",
"корыто" : "trough",
"корь" : "measles",
"корявый" : "knotty gnarled, rugged rough, crooked, clumsy",
"коряга" : "snag",
"коса" : "plait braid, scythe, spit",
"косарь" : "mower",
"косвенный" : "oblique indirect, jur. circumstantial",
"косилка" : "mowing machine",
"косинус" : "cosine",
"косить" : "mow, a. покосить squint, twist  be wry, -ся покоситься, a. look askance",
"косичка" : "dim. of коса",
"косматый" : "shaggy",
"косметика" : "cosmetics pl.",
"косметический" : "cosmetic",
"космический" : "cosmic",
"космонавт" : "astronaut",
"космополитический" : "cosmopolitan",
"космос" : "cosmos, space",
"коснеть" : "persist sink fossilize",
"косность" : "sluggishness indolence, stagnation",
"коснуться" : "touch, concern, famil. be about deal #or be concerned with, дело касается s. идти`, что касается ... то as for",
"косный" : "sluggish dull, stagnant fossil",
"косо" : "aslant, aslope, asquint, bias",
"косоглазие" : "squint, squinting, strabismus",
"косоглазый" : "squint-eyed",
"косогор" : "slope",
"косой" : "slanting oblique, squint, famil. wry",
"косолапый" : "bandy-legged, s. неуклюжий",
"косоугольный" : "bevel",
"костенеть" : "ossify, stiffen grow numb, be transfixed",
"костер" : "fire bonfire, pile stake, meeting",
"костистый" : "bony",
"костлявый" : "scrawny raw-boned",
"костный" : "osseous",
"косточка" : "bone, bot. stone, stay",
"костыль" : "crutch, engin. spike",
"кость" : "bone, die, белая кость; See also: играть в кости",
"костюм" : "suit, costume",
"костюмированный бал" : "fancy ball",
"костяк" : "skeleton, framework",
"костяной" : "bone...",
"косуля" : "roe",
"косынка" : "kerchief",
"косьба" : "mowing",
"косяк" : "lintel, slant, felloe, herd, flock, shoal",
"кот" : "tomcat, a. котик; See also: купить кота в мешке, кот наплакал",
"кот наплакал" : "famil. very little",
"котел" : "boiler caldron, kitchen",
"котелок" : "kettle pot, milit. mess kit, derby Brt. bowler",
"котенок" : "kitten",
"котик" : "dim. #of кот, fur seal, seal",
"котлета" : "rissole, cutlet chop",
"котловина" : "hollow basin",
"котомка" : "knapsack, bag",
"который" : "which, who, that, what, many a, popul. some, one; See also: который раз, который час{?}, в котором часу{?}, который ему год{?}",
"который ему год" : "how old is he?",
"кофе" : "coffee",
"кофейная" : "coffee house cafe",
"кофейник" : "coffee pot",
"кофейница" : "coffee mill, coffee box",
"кофейный" : "coffee...",
"кофейня" : "coffee house cafe",
"кофта" : "jacket, blouse, jersey cardigan",
"кофточка" : "blouse",
"кочан" : "head",
"кочевать" : "wander roam, famil. move, travel",
"кочевник" : "nomad",
"кочевой" : "nomadic",
"кочегар" : "fireman stoker",
"коченеть" : "grow numb stiffen",
"кочерга" : "poker",
"кочка" : "mound hillock",
"кошачий" : "cat, feline",
"кошелек" : "purse",
"кошерный" : "kosher",
"кошка" : "cat",
"кошмар" : "nightmare",
"кошмарный" : "dreadful horrible, famil. awful",
"кощунственный" : "blasphemous",
"кощунство" : "blasphemy",
"кощунствовать" : "blaspheme",
"коэффициент" : "coefficient",
"кпсс" : ", Communist Party of the Soviet Union",
"крага" : "puttie",
"краденый" : "stolen",
"краевой" : "marginal",
"краеугольный" : "fig. corner, fundamental",
"кража" : "theft; See also: кража со взломом",
"кража со взломом" : "burglary",
"край" : "edge, rim, brink edge, end, fringe border outskirt, region land country",
"крайний" : "outermost utmost, extreme; See also: в крайнем случае",
"крайность" : "extreme, extremity, до крайности = крайне s.; See also: впадать в крайности, доходить до крайности",
"крамола" : "sedition revolt",
"кран" : "tap, engin. crane",
"крапать" : "drop drip"
};
