var dicctr_3 = {
"безнадежный" : "hopeless",
"безнадзорный" : "uncared for",
"безнаказанность" : "impunity",
"безнаказанный" : "unpunished with impunity",
"безналичный" : "безналичный расчет commerc. cashless settlement",
"безнравственный" : "immoral, reprobate, unmoral, wicked",
"безобидный" : "inoffensive",
"безопасный" : "safe, safety, secure",
"безоружный" : "unarmed, defenseless",
"безостановочный" : "continuous, nonstop...",
"безответный" : "without response, humble, dumb",
"безответственный" : "irresponsible",
"безотлагательность" : "urgency",
"безотлагательный" : "undelayable urgent",
"безотносительный" : "irrelative, irrespective",
"безотрадный" : "desolate wretched",
"безотчетный" : "unaccountable, unconscious involuntary",
"безошибочный" : "faultless",
"безработица" : "unemployment",
"безработный" : "unemployed",
"безразличие" : "indifference",
"безразличный" : "indifferent, это мне безразлично it is all the same to me",
"безрассудный" : "thoughtless reckless rash",
"безрассудство" : "desperation, temerity",
"безрезультатный" : "futile vain",
"безропотный" : "humble meek submissive",
"безрукавка" : "sleeveless jacket waistcoat",
"безударный" : "unstressed",
"безудержный" : "unrestrained, impetuous",
"безукоризненный" : "irreproachable unobjectionable",
"безумец" : "madman lunatic, madcap",
"безумие" : "madness folly",
"безумный" : "mad insane, nonsensical absurd, rash",
"безумолчный" : "incessant uninterrupted",
"безумство" : "folly",
"безупречный" : "blameless irreproachable",
"безусловно" : "certainly surely",
"безусловный" : "absolute unconditional",
"безуспешный" : "unsuccessful",
"безустанный" : "incessant, indefatigable",
"безутешный" : "disconsolate inconsolable",
"безучастный" : "indifferent",
"безымянный" : "anonymous; See also: безымянный палец",
"безымянный палец" : "ring finger",
"безыскусственный" : "unaffected unsophisticated",
"безысходный" : "hopeless desperate",
"бейрут" : "beirut",
"бейсбол" : "baseball",
"бекас" : "snipe",
"бекон" : "bacon, sowbelly",
"белая кость" : "blue blood",
"белград" : "belgrade",
"белена" : "henbane",
"беление" : "blanching, whiting",
"белесый" : "whitish",
"белеть" : "grow #or turn white, impf. appear #or show white",
"белизна" : "whiteness",
"белила" : "ceruse",
"белить" : "выбелить bleach, набелить paint, побелить whitewash",
"белка" : "squirrel",
"беллетристика" : "fiction",
"белобородый" : "white-bearded",
"белобрысый" : "flaxen-haired",
"беловатый" : "whitish",
"беловик" : "беловой экземпляр fair copy",
"беловой" : "беловой экземпляр fair copy",
"белок" : "albumen, albumin, protein",
"белые стихи" : "blank verse",
"белый" : "white, light fair, secular; See also: белый свет, белые стихи, средь бела дня",
"белый свет" : "world",
"бельгиец" : "Belgian",
"бельгийка" : "Belgian",
"бельгийский" : "Belgian",
"бельгия" : "Belgium",
"белье" : "linen; See also: нижнее белье",
"бельмо" : "wall-eye, pl. goggle-eyes, выпучить бельма famil. stare, он у меня как бельмо на глазу he is an eyesore to me",
"бельэтаж" : "thea. dress circle, second floor",
"бемоль" : "flat",
"бенгальский" : "bengal, bengali",
"бенефис" : "benefit",
"бензин" : "benzine, gasoline Brt. petrol",
"бензобак" : "gasoline #or petrol tank",
"бензозаправочная колонка" : "filling station",
"бензоколонка" : "filling station",
"бензол" : "benzol",
"бенуар" : "thea. parterre box",
"берег" : "bank shore coast, land, выйти из берегов overflow the banks, пристать к берегу land",
"берегись" : "take care! look out! attention!",
"береговичок" : "winkle",
"бережливость" : "parsimony, thrift",
"бережливый" : "frugal, parsimonious, sparing",
"береза" : "birch",
"беременная" : "enceinte, gravid, pregnant",
"берет" : "barret, beret",
"берилл" : "beryl",
"бериллий" : "beryllium",
"берлога" : "den, dig",
"беседа" : "conversation talk, conference discussion",
"беседка" : "arbor summerhouse",
"беседовать" : "converse",
"бесенок" : "imp",
"бесить" : "enrage madden",
"беситься" : "rage, romp",
"бесконечно малый" : "math. infinitesimal",
"бесконечность" : "infinity; See also: до бесконечности",
"бесконечный" : "endless infinite, unlimited boundless, eternal",
"бескорыстие" : "unselfishness",
"бескорыстный" : "disinterested",
"бескровие" : "anemia",
"бескровный" : "anemic, bloodless",
"бесноватый" : "possessed demoniac",
"бесноваться" : "rage rave",
"бесовщина" : "devilry",
"беспамятность" : "forgetfulness",
"беспамятный" : "forgetful, unconscious",
"беспамятство" : "unconsciousness swoon",
"беспартийный" : "independent, non-party",
"бесперебойный" : "uninterrupted smooth",
"беспеременный" : "invariable, unalterable",
"беспересадочный" : "through...",
"беспечность" : "carelessness",
"беспечный" : "careless",
"бесплатно" : "gratis",
"бесплатный" : "free  gratuitous",
"бесплодие" : "sterility",
"бесплодный" : "sterile, fruitless vain",
"бесповоротный" : "unalterable irrevocable",
"бесподобный" : "incomparable matchless",
"беспозвоночный" : "invertebrate",
"беспокоить" : "upset worry, disturb bother trouble",
"беспокоиться" : "worry be anxious",
"беспокойный" : "restless, uneasy",
"беспокойство" : "unrest, trouble, anxiety, простите за беспокойство sorry to trouble you",
"бесполезность" : "inefficacy",
"бесполезный" : "useless",
"бесполый" : "agamic, asexual, sexless",
"беспомощный" : "helpless",
"беспорочный" : "blameless irreproachable",
"беспорядок" : "disorder mess, pl. disorders",
"беспорядочный" : "disorderly incoherent",
"беспосадочный" : "беспосадочный перелет nonstop flight",
"беспощадный" : "inexpiable, unmerciful, unsparing",
"беспрекословный" : "absolute unquestioning implicit",
"беспрепятственный" : "unhampered unhindered",
"беспрерывный" : "uninterrupted continuous",
"беспрестанный" : "incessant continual",
"бесприбыльный" : "unprofitable",
"беспризорник" : "waif stray",
"беспризорный" : "homeless uncared-for",
"беспримерный" : "unprecedented unparalleled",
"беспринципный" : "unprincipled unscrupulous",
"беспристрастие" : "impartiality",
"беспристрастный" : "impartial unprejudiced unbiased",
"беспричинный" : "groundless, unfounded",
"бесприютный" : "homeless",
"беспробудный" : "deep, unrestrained",
"беспроволочный" : "wireless",
"беспросветный" : "pitch-dark, fig. hopeless",
"беспроцентный" : "without charge for interest",
"беспутный" : "dissolute",
"бессвязный" : "incoherent rambling",
"бессердечный" : "heartless unfeeling callous",
"бессилие" : "debility, impotence",
"бессильный" : "weak powerless impotent",
"бесславный" : "infamous disgraceful inglorious",
"бесследный" : "without leaving a trace entire",
"бессловесный" : "speechless dumb, taciturn",
"бессмертие" : "immortality",
"бессмертный" : "immortal",
"бессмысленный" : "senseless, dull",
"бессмыслица" : "nonsense",
"бессовестный" : "unscrupulous",
"бессодержательный" : "empty insipid dull",
"бессознательный" : "unconscious",
"бессонница" : "insomnia",
"бессонный" : "sleepless",
"бесспорный" : "indisputable, doubtless certain",
"бессрочный" : "termless not limited in time",
"бесстрастие" : "dispassionateness calmness",
"бесстрастный" : "dispassionate composed",
"бесстрашие" : "fearlessness",
"бесстрашный" : "fearless intrepid",
"бесстыдный" : "shameless impudent, indecent",
"бесстыдство" : "impudence insolence",
"бессчетный" : "innumerable",
"бестактный" : "indelicate, tactless",
"бесталанный" : "untalented, ill-fated",
"бестия" : "brute beast, artful dodger",
"бестолковщина" : "nonsense, mess, confusion",
"бестолковый" : "absurd confused",
"бестрепетный" : "intrepid undaunted",
"бесформенный" : "amorphous, formless, indigested, shapeless",
"бесхитростный" : "artless naive ingenuous unsophisticated",
"бесхозяйственность" : "mismanagement",
"бесхозяйственный" : "thriftless",
"бесхребетный" : "invertebrate",
"бесцветный" : "colorless",
"бесцельный" : "aimless",
"бесценный" : "invaluable priceless",
"бесценок" : "за бесценок",
"бесцеремонный" : "offhand, offhanded, unceremonious",
"бесчеловечность" : "inhumanity",
"бесчеловечный" : "inhuman cruel",
"бесчестный" : "dishonest, dishonorable",
"бесчестье" : "dishonor disgrace",
"бесчинство" : "excess outrage",
"бесчинствовать" : "behave outrageously",
"бесчисленный" : "innumerable countless",
"бесчувственный" : "insensible callous hard-hearted",
"бесчувствие" : "insensibility, unconsciousness swoon",
"бесшабашный" : "reckless careless, wanton",
"бесшумный" : "noiseless quiet",
"бетон" : "concrete",
"бетонировать" : "concrete",
"бетонный" : "concrete...",
"бечевка" : "string",
"бешенство" : "med. hydrophobia, fury rage",
"бешеный" : "rabid, furious frantic wild, enormous",
"библейский" : "Biblical, Bible...",
"библиографический" : "bibliographic",
"библиография" : "bibliography",
"библиотека" : "library",
"библиотекарь" : "librarian",
"библиотечный" : "library...",
"библиофил" : "bibliophile",
"библия" : "Bible",
"бивак" : "bivouac, стоять биваком #or стоять на биваках, bivouac",
"бивень" : "tusk",
"биение" : "pulse, throb",
"бизон" : "bison",
"билет" : "ticket",
"бильярдный" : "billiard",
"бинго" : "bingo",
"бинт" : "bandage, swathe",
"бинтовать" : "bandage dress",
"биограф" : "biographer",
"биографический" : "biographic",
"биография" : "biography",
"биолог" : "biologist",
"биологический" : "biological",
"биология" : "biology",
"биохимия" : "biochemistry",
"биплан" : "biplane",
"биржа" : "exchange; See also: биржа труда",
"биржа труда" : "labor registry office Brt. labour exchange",
"биржевик" : "stockbroker",
"биржевой маклер" : "stockbroker",
"бирка" : "tally",
"бирма" : "Burma",
"бирманец" : "Burmese"
};
