var dicctr_89 = {
"трубопровод" : "pipe line",
"трубочист" : "chimney sweep",
"трубочка" : "tubule",
"трубчатый" : "tubular",
"труд" : "labor work, pains pl. trouble, difficulty, a. transactions, famil. service",
"трудиться" : "work, toil exert o.s., trouble",
"труднодоступный" : "arduous",
"трудность" : "difficulty",
"трудный" : "difficult hard, famil. heavy",
"трудовой" : "labor..., working, workman's, earned, service...",
"трудолюбивый" : "industrious",
"трудолюбие" : "industry",
"трудоспособный" : "able-bodied able to work",
"трудящийся" : "working, su. worker",
"труженик" : "toiler worker",
"трунить" : "make fun",
"труп" : "corpse body",
"труппа" : "company troupe",
"трус" : "coward",
"трусики" : "trunks shorts",
"трусить" : "be afraid",
"трусиха" : "#of трус",
"трусливый" : "cowardly",
"трусость" : "cowardice",
"трусы" : "s. трусики",
"трут" : "tinder",
"трутень" : "drone",
"трущоба" : "slum den nest",
"трюк" : "trick famil. stunt",
"трюм" : "hold",
"трюмо" : "pier glass",
"тряпичник" : "ragpicker",
"тряпка" : "rag, duster, patch, famil. milksop",
"тряпье" : "rag",
"трясина" : "bog fen quagmire",
"тряска" : "jolting",
"тряский" : "shaky, jolty",
"трясти" : "shake, famil. jolt",
"трястись" : "shake, shiver",
"тряхнуть" : "shake, famil. jolt",
"тсс" : "hush!",
"туалет" : "toilet",
"туба" : "tuba",
"туберкулез" : "tuberculosis",
"туберкулезный" : "tubercular, tuberculous",
"тугой" : "tight taut, stiff, crammed, famil. stingy, slow hard, a. hard put to it, hard up, hard with difficulty",
"туда" : "there thither, that way",
"тужить" : "grieve, long for",
"тужурка" : "jacket",
"туз" : "ace, famil. boss",
"туземец" : "native",
"туземный" : "native",
"туловище" : "trunk",
"тулуп" : "sheepskin coat",
"туляремия" : "tularemia",
"туман" : "fog mist, haze, smog",
"туманность" : "nebula",
"туманный" : "foggy misty, fig. hazy vague",
"тумба" : "curbstone, pedestal",
"тумбочка" : "bedside table",
"тундра" : "tundra",
"тунец" : "tuna, tunny",
"тунеядец" : "parasite",
"тунис" : "Tunisia, Tunis",
"туннель" : "tunnel",
"тупеть" : "grow blunt",
"тупик" : "blind alley dead end impasse, nonplus tight corner; See also: ставить в тупик, стать в тупик",
"тупица" : "dullard, dunce, goof, thickhead",
"тупой" : "blunt, math. obtuse, fig. dull stupid, apathetic",
"тупость" : "bluntness, dullness",
"тупоумный" : "stupid",
"тур" : "round, tour, zo. aurochs",
"тура" : "rook castle",
"турбина" : "turbine",
"турбореактивный" : "turbojet",
"турецкий" : "Turkish",
"туризм" : "tourism",
"турист" : "tourist",
"туркмен" : "Turkman",
"туркменский" : "Turkmen",
"турне" : "tour",
"турник" : "horizontal bar",
"турнир" : "tournament",
"турок" : "Turk",
"турция" : "Turkey",
"турчанка" : "Turk",
"тусклость" : "tarnish",
"тусклый" : "dim, dull, dead",
"тускнеть" : "grow dim #or dull",
"тускнуть" : "grow dim #or dull",
"тут" : "famil. here, there, then, тут! present!; See also: тут же, тут как тут",
"тут же" : "there & then on the spot",
"тут как тут" : "already there",
"тутовое дерево" : "mulberry",
"туфля" : "shoe, slipper",
"тухлый" : "bad  rotten",
"тухнуть" : "потухнуть go or die out expire, протухнуть go bad",
"туча" : "cloud",
"тучный" : "corpulent obese stout fat, fertile",
"туш" : "flourish",
"туша" : "carcass",
"тушеный" : "stewed",
"тушить" : "put out extinguish, impf. stew, fig. subdue",
"тушь" : "Indian ink",
"тщательность" : "care",
"тщательный" : "careful",
"тщедушный" : "sickly",
"тщеславие" : "vanity",
"тщеславный" : "vain",
"тщетный" : "vain futile тщетно in vain",
"ты" : "you obsol. thou, быть на ~ thou  be familiar",
"тыкать" : "poke jab thrust, famil. thou",
"тыква" : "pumpkin",
"тыл" : "rear base; See also: глубокий тыл",
"тысяча" : "thousand",
"тысячелетие" : "millenium",
"тысячный" : "thousandth, of thousand",
"тычинка" : "stamen, stamina",
"тьма" : "dark, famil. lots of",
"тьфу" : "famil. fie! for shame!",
"тюбетейка" : "skullcap",
"тюбик" : "tube",
"тюль" : "tulle",
"тюльпан" : "tulip",
"тюрбан" : "turban",
"тюремщик" : "jailer, turnkey, warder",
"тюрьма" : "bastille, calaboose, gaol, prison, quod",
"тявканье" : "yip",
"тявкать" : "yap",
"тягостный" : "onerous",
"тяготение" : "gravitation, fig.",
"тяготеть" : "gravitate, weigh",
"тяготить" : "weigh upon be a burden to",
"тяготиться" : "feel the burden",
"тягучий" : "viscous, ductile, drawling lingering",
"тяжба" : "action lawsuit",
"тяжел на подьем" : "slow",
"тяжелая" : "grind",
"тяжеловес" : "heavyweight",
"тяжеловесный" : "heavy ponderous",
"тяжелый" : "heavy, difficult hard, laborious, serious, severe grave, grievous sad oppressive painful, close, тяжело feel sad",
"тяжесть" : "heaviness, weight, load, burden, gravity, seriousness, painfulness",
"тяжкий" : "heavy  cf. тяжелый",
"тянуть" : "pull draw, nav. tow, draw in, protract, drawl, attract, gravitate, drive at, long, have a mind to, would like, waft, тянет there is a draft, famil. drag, steal, take",
"тянуть жребий" : "draw lots",
"тянуть лямку" : "famil. drudge toil",
"тянуться" : "stretch, last, drag draw on, reach out",
"тянущий" : "dragging",
"у" : "at by near, with, ...'s, at pers.'s place, у меня I have, my, from, of, off, in; See also: у себя",
"у него счету нет" : "he has lots",
"у него хороший вид" : "he looks well",
"у себя" : "in one's home #or room office",
"уайтхолл" : "whitehall",
"убавить" : "lower reduce diminish decrease, -ся",
"убавлять" : "lower reduce diminish decrease, -ся",
"убаюкать" : "lull",
"убегать" : "run away, escape",
"убедительный" : "convincing, urgent",
"убедить" : "convince  persuade",
"убежать" : "run away, escape",
"убеждать" : "convince  persuade",
"убеждение" : "persuasion, conviction",
"убежище" : "shelter refuge, asylum",
"уберегать" : "save safeguard",
"уберечь" : "save safeguard",
"убивать" : "kill, murder, beat, drive into despair, blight, famil. waste",
"убийственный" : "killing, murderous, famil. deadly terrible",
"убийство" : "murder; See also: покушение на убийство",
"убийца" : "murderer, assassin",
"убирать" : "take away, gather harvest, tidy up, decorate adorn trim, dress up",
"убираться" : "famil. clear off away, убирайся ! get out of here!",
"убить" : "kill, murder, beat, drive into despair, blight, famil. waste",
"ублюдок" : "jerk",
"убогий" : "needy poor, wretched miserable, scanty, crippled",
"убожество" : "poverty",
"убой" : "slaughter",
"убор" : "attire, gear",
"убористый" : "close",
"уборка" : "harvest gathering, tidying up",
"уборная" : "lavatory toilet water closet, dressing room",
"уборочный" : "harvest",
"уборщица" : "charwoman",
"убранство" : "attire, furniture",
"убрать" : "take away, gather harvest, tidy up, decorate adorn trim, dress up",
"убывать" : "subside fall, decrease, leave, fall out",
"убыль" : "decrease fall, loss",
"убыток" : "loss damage, disadvantage",
"убыточный" : "unprofitable",
"убыть" : "subside fall, decrease, leave, fall out",
"уважаемый" : "dear",
"уважать" : "respect esteem",
"уважение" : "respect esteem",
"уважительный" : "valid",
"уведомить" : "inform notify advise",
"уведомление" : "notification commerc. advice",
"уведомлять" : "inform notify advise",
"увезти" : "s. увозить",
"увековечивать" : "immortalize",
"увековечить" : "immortalize",
"увеличение" : "increase, enlargement",
"увеличивать" : "increase, enlarge, magnify, -ся",
"увеличительный" : "opt. magnifying, gr. augmentative",
"увеличить" : "increase, enlarge, magnify, -ся",
"увенчаться" : "pf. be crowned",
"уверение" : "assurance",
"уверенность" : "firmness assurance, certainty, confidence",
"уверенный" : "firm steady, confident, positive sure certain, будьте уверены I assure you you may depend on it",
"уверить" : "s. уверять",
"увертка" : "subterfuge dodge",
"увертливый" : "evasive",
"увертываться" : "dodge",
"увертюра" : "overture",
"уверять" : "assure, make believe  persuade",
"увеселение" : "amusement",
"увеселительный" : "pleasure...",
"увеселять" : "amuse",
"увесистый" : "ponderous",
"увести" : "s. уводить",
"увечить" : "mutilate",
"увечный" : "crippled",
"увечье" : "mutilation",
"увещание" : "admonition",
"увидать" : "его давно не видать, I #or we haven't seen him for a long time, -ся meet see",
"увидеть" : "see, catch sight of; See also: увидеть во сне, видишь ли{?}, видите ли{?}",
"увидеть во сне" : "dream",
"увидеться" : "= видаться",
"увиливать" : "shirk",
"увильнуть" : "shirk",
"увлажнить" : "wet dampen",
"увлажнять" : "wet dampen",
"увлекательный" : "fascinating",
"увлекать" : "carry",
"увлекаться" : "be carried away  be enthusiastic, be absorbed, take to, fall in love",
"увлечение" : "enthusiasm passion",
"увлечь" : "drag pull, fig. attract draw; See also: влечь за собой",
"увлечься" : "be carried away  be enthusiastic, be absorbed, take to, fall in love",
"увод" : "milit. withdrawal, theft",
"уводить" : "take lead, steal, milit. withdraw",
"увозить" : "take carry drive, famil. steal kidnap",
"уволить" : "s. увольнять",
"увольнение" : "dismissal, granting",
"увольнять" : "dismiss, give, dispense  spare",
"увы" : "alas!",
"углевод" : "carbohydrate",
"углеводород" : "hydrocarbon",
"углекоп" : "s. шахтер",
"углерод" : "carbon",
"углистый" : "carbonaceous",
"угловой" : "corner..., angle...",
"углубить" : "s. углублять"
};
