var dicctr_10 = {
"возвестить" : "announce",
"возвещать" : "announce",
"возводить" : "lead up, raise elevate, erect, make",
"возврат" : "= возвращение 1) & 2), med. relapse",
"возвратить" : "s. возвращать",
"возвратный" : "reflexive, returning",
"возвращать" : "give back, retrieve",
"возвращаться" : "come back, recur, rejoin, revert",
"возвращающийся" : "recurrent",
"возвращение" : "restitution, retrieval, reversion",
"возвышать" : "upraise",
"возвышение" : "exaltation, mons, podium",
"возвышенность" : "sublimity loftiness, hill",
"возвышенный" : "elevated lofty",
"возглавить" : "head",
"возглавлять" : "head",
"возглас" : "exclamation cry",
"возгласить" : "proclaim",
"возглашать" : "proclaim",
"возгордиться" : "be proud",
"воздавать" : "reward, show do",
"воздать" : "reward, show do",
"воздать должное" : "do justice",
"воздвигать" : "erect construct raise",
"воздвигнуть" : "erect construct raise",
"воздействие" : "influence impact",
"воздействовать" : "pf. influence, act upon affect",
"возделать" : "till",
"возделывать" : "till",
"воздержание" : "abstinence, abstention",
"воздержанность" : "forbearance",
"воздержанный" : "s. воздержный",
"воздержаться" : "abstain, при двух воздержавшихся pol. with two abstentions",
"воздерживаться" : "abstain, при двух воздержавшихся pol. with two abstentions",
"воздержный" : "abstemious temperate",
"воздух" : "air, на воздухе, in the open air outdoors",
"воздухонепроницаемый" : "airtight",
"воздухоплавание" : "aeronautics",
"воздухоплавательный" : "aeronautic",
"воздушная тревога" : "air-raid warning",
"воздушно-десантный" : "airborne",
"воздушные замки" : "castles in the air",
"воздушный" : "air..., airy; See also: воздушная тревога, воздушные замки",
"воззвание" : "appeal, proclamation",
"воззвать" : "cry call, invoke, appeal",
"возить" : "drive transport",
"возиться" : "busy o.s.  mess, dawdle, fidget, romp frolic",
"возлагать" : "lay, entrust; See also: возлагать надежды на",
"возлагать надежды на" : "rest one's hopes upon",
"возле" : "by near beside",
"возлежащий" : "incumbent",
"возликовать" : "exult",
"возлияние" : "libation",
"возложить" : "lay, entrust; See also: возлагать надежды на",
"возлюбленная" : "mistress sweetheart",
"возлюбленный" : "beloved, lover",
"возмездие" : "requital",
"возместить" : "compensate recompense",
"возмещать" : "compensate recompense",
"возмещение" : "compensation indemnification",
"возможно" : "it is possible, possibly, очень возможно very likely",
"возможность" : "possibility, chance, по возможности as ... as possible",
"возможный" : "possible, сделать все возможное do one's utmost",
"возмужалый" : "mature virile",
"возмужать" : "mature grow",
"возмутительный" : "revolting shoking",
"возмутить" : "revolt, -ся be shocked #or indignant",
"возмущать" : "revolt, -ся be shocked #or indignant",
"возмущение" : "indignation, revolt",
"возмущенный" : "indignant",
"вознаградить" : "reward recompense indemnify",
"вознаграждать" : "reward recompense indemnify",
"вознаграждение" : "reward recompense",
"вознамериваться" : "intend decide",
"вознамериться" : "intend decide",
"возненавидеть" : "hate",
"вознесение" : "ascension",
"вознести" : "s. возносить",
"вознестись" : "rise, become haughty",
"возникать" : "arise originate emerge",
"возникающий" : "nascent",
"возникновение" : "rise origin",
"возникнуть" : "arise originate emerge",
"возничий" : "auriga",
"возносить" : "raise elevate, exalt",
"возноситься" : "rise, become haughty",
"возня" : "fuss bustle romp, trouble bother",
"возобновить" : "renew, resume",
"возобновление" : "renewal, resumption",
"возобновлять" : "renew, resume",
"возражать" : "object, return retort, не возражаю I don't mind",
"возражение" : "objection, rejoinder",
"возразить" : "object, return retort, не возражаю I don't mind",
"возраст" : "age",
"возрастание" : "growth increase",
"возрастать" : "grow up, increase rise",
"возрасти" : "grow up, increase rise",
"возродить" : "revive regenerate",
"возрождать" : "revive regenerate",
"возрождающийся" : "renascent, resurgent",
"возрождение" : "rebirth revival, эпоха Возрождения Renaissance",
"возчик" : "wagoner carter",
"возьмите направо" : "turn right!",
"воинственный" : "bellicose, warlike",
"вой" : "yowl",
"войлок" : "felt",
"война" : "war",
"войска" : "military, troop, troops",
"войти в азарт" : "get excited",
"войти в быт" : "become a habit",
"войти в доверие к" : "gain a pers.'s confidence",
"войти в милость к" : "gain a pers.'s favor",
"войти в положение" : "appreciate a pers.'s position",
"войти в пословицу" : "become a proverbial",
"войти в привычку" : "become a habit",
"войти во вкус" : "take a fancy to",
"вокзал" : "railroad station depot",
"вокруг" : "round; See also: вертеться вокруг да около",
"вол" : "ox",
"волан" : "shuttlecock",
"волга" : "Volga",
"волдырь" : "blister swelling",
"волейбол" : "volleyball",
"волей-неволей" : "willy-nilly",
"волжский" : "Volga...",
"волк" : "wolf, смотреть волком famil. scowl",
"волки" : "wolves",
"воллейбол" : "volleyball",
"волна" : "wave, el. длинные средние короткие волны, long medium short waves",
"волнение" : "agitation excitement unrest, pl. troubles riots",
"волнистый" : "wavy undulating",
"волновать" : "agitate excite, worry",
"волнорез" : "pier",
"волнующий" : "exciting thrilling",
"воловий" : "ox...",
"володя" : "dim. #of Владимир",
"волокита" : "red tape, a lot of fuss and trouble, lady-killer ladies' man",
"волокитство" : "flirtation",
"волокнистый" : "fibrous",
"волокно" : "fiber Brt. fibre",
"волонтер" : "volunteer",
"волос" : "hair",
"волосатый" : "hairy",
"волосок" : "hair, el. filament, быть на волосок от смерти, famil. be on the verge of death, висеть на волоске hang by #or on a thread",
"волость" : "district",
"волосяной" : "hair...",
"волочить" : "drag pull draw",
"волочиться" : "drag o.s. crawl along, famil. run after court",
"волхв" : "magician wizard",
"волчеягодник" : "daphne",
"волчий" : "wolfish, wolf...",
"волчок" : "top",
"волчонок" : "wolf cub",
"волшебник" : "magician",
"волшебница" : "sorceress",
"волшебный" : "magic fairy..., fig. enchanting",
"волшебство" : "magic witchery",
"волынка" : "bagpipe",
"вольнодумец" : "freethinker",
"вольнослушатель" : "auditor irregular student",
"вольность" : "liberty, freedom",
"вольный" : "free easy unrestricted, milit. вольно! at ease!",
"вольт" : "volt",
"вольтметр" : "voltmeter",
"вольфрам" : "wolframite",
"волюнтаризм" : "voluntarism",
"воля" : "will; See also: сила воли, воля ваша, по доброй воле, отпустить на волю, дать волю",
"воля ваша" : "as you like",
"вомбат" : "wombat",
"вон" : "famil. there; See also: вон там, пошел вон{!}, выгнать вон, вон что{!}",
"вон там" : "over there, вон! get out!",
"вон что" : "famil. you don't say!, oh that's it!",
"вонь" : "stink",
"вонючий" : "foul, stinking",
"вонять" : "stank, stunk",
"воображаемый" : "fancied, fictitious, imaginary, make-believe",
"воображать" : "envision, imagine",
"воображение" : "fantasy, imagination",
"вообразить" : "imagine fancy",
"вообще" : "generally in general, at all",
"воодушевить" : "inspire",
"воодушевление" : "enthusiasm",
"воодушевлять" : "inspire",
"вооружать" : "arm equip, stir up",
"вооружение" : "armament equipment",
"вооруженный" : "armed",
"вооружить" : "arm equip, stir up",
"воочию" : "with one's own eyes",
"во-первых" : "first",
"вопить" : "cry out bawl, lament wail",
"вопиющий" : "crying flagrant",
"воплотить" : "embody personify",
"воплощать" : "embody personify",
"воплощение" : "embodiment incarnation",
"воплощенный" : "a. incarnate",
"вопль" : "outcry clamor, wail",
"вопреки" : "contrary to, in spite of",
"вопреки закону" : "contrary to law",
"вопрос" : "question; See also: под вопросом, вопрос не в этом, спорный вопрос, что за вопрос{!}",
"вопрос не в этом" : "that's not the question",
"вопросительный" : "interrogative; See also: вопросительный знак",
"вопросительный знак" : "question mark",
"вор" : "thief",
"ворваться" : "s. врываться",
"воркование" : "coo",
"ворковать" : "coo",
"воркотня" : "grumble",
"воробей" : "sparrow, старый воробей, famil. cunning fellow",
"воробьиный" : "sparrow...",
"воровать" : "steal",
"воровка" : "thief",
"воровской" : "thievish, thieves'...",
"воровство" : "theft larceny",
"ворожить" : "tell fortunes",
"ворон" : "raven",
"ворона" : "crow, ворон считать famil. stand gaping about",
"воронка" : "funnel, crater",
"вороной" : "black, black horse",
"ворот" : "collar, windlass",
"ворота" : "gate",
"воротить" : "cf. возвращать, popul. move roll, turn off round, s. ворочать 2)",
"воротник" : "collar",
"воротничок" : "collar",
"ворох" : "pile heap",
"ворочать" : "s. воротить 2), famil. manage boss",
"ворочаться" : "toss, turn, stir",
"ворошить" : "turn",
"ворс" : "fluff",
"ворсить" : "teasel",
"ворчание" : "grumbling growl",
"ворчать" : "grumble growl",
"ворчливый" : "grumbling surly",
"ворчун" : "grumbler",
"ворчунья" : "grumbler",
"воры" : "thieves",
"восвояси" : "home",
"восемнадцатый" : "eighteenth",
"восемнадцать" : "eighteen, s. пять пятый",
"восемь" : "eight, & пятый",
"восемьдесят" : "eighty",
"восемьсот" : "eight hundred",
"восемью" : "eight times",
"воск" : "wax",
"воскликнуть" : "exclaim",
"восклицание" : "exclamation",
"восклицательный" : "exclamatory; See also: восклицательный знак",
"восклицательный знак" : "exclamation mark #or point",
"восклицать" : "exclaim",
"восковой" : "wax...",
"воскресать" : "rise, recover, Христос воскрес! Christ has arisen!, воистину воскрес! truly arisen!"
};
