var dicctr_30 = {
"испугать" : "s. пугать",
"испускать" : "utter, emit, exhale, give up",
"испустить" : "utter, emit, exhale, give up",
"испустить последний вздох" : "give up the ghost",
"испытание" : "test trial, examination",
"испытанный" : "tried",
"испытательный" : "test...",
"испытать" : "try  test, experience undergo feel",
"испытующий" : "searching",
"испытывать" : "try  test, experience undergo feel",
"исследование" : "investigation research, exploration, examination, chem. analysis, treatise paper essay",
"исследователь" : "research worker researcher, explorer",
"исследовательский" : "research...",
"исследовать" : "pf. investigate, explore, examine, chem. analyze, nav. sound",
"иссохнуть" : "s. иссыхать",
"исстари" : "= издавна cf.",
"исступление" : "ecstasy frenzy, rage",
"исступленный" : "frantic",
"иссушать" : "dry, a. exhaust wear out",
"иссушить" : "dry, a. exhaust wear out",
"иссыхать" : "dry, a. exhaust wear out",
"иссякать" : "dry, a. exhaust wear out",
"иссякнуть" : "dry, a. exhaust wear out",
"истекать" : "flow out, impf. spring, elapse  expire become due, dissolve; See also: истекать кровью",
"истекать кровью" : "bleed to death",
"истекший" : "past last",
"истерика" : "hysterics pl.",
"истерический" : "hysterical",
"истеричный" : "hysterical",
"истерия" : "hysteria",
"истец" : "plaintiff",
"истечение" : "expiration  lapse, med. discharge",
"истечение крови" : "bleeding, по истечении at the end of",
"истечь" : "flow out, impf. spring, elapse  expire become due, dissolve; See also: истекать кровью",
"истина" : "truth",
"истинный" : "true genuine, right, plain",
"истлевать" : "molder rot decay, die away",
"истлеть" : "molder rot decay, die away",
"истовый" : "true, grave, zealous",
"исток" : "source",
"истолкование" : "interpretation",
"истолковать" : "interpret expound explain",
"истолковывать" : "interpret expound explain",
"истолочь" : "pound",
"истома" : "languor",
"истомить" : "tire fatigue weary",
"истомлять" : "tire fatigue weary",
"истопник" : "stoker",
"истоптать" : "pf. trample, wear out",
"исторгать" : "wrest, draw, deliver save",
"исторгнуть" : "wrest, draw, deliver save",
"историк" : "historian",
"историография" : "historiography",
"исторический" : "historical",
"история" : "history, story, famil. affair thing, вечная история! always the same!",
"источать" : "draw, shed, exhale emit",
"источить" : "draw, shed, exhale emit",
"источник" : "spring, source",
"истощать" : "exhaust use up",
"истощение" : "depletion",
"истощенный" : "effete, emaciated, impoverished, spent",
"истощить" : "exhaust use up",
"истратить" : "spend, waste",
"истрачивать" : "s. тратить",
"истребитель" : "destroyer, av. pursuit plane fighter",
"истребительный" : "destructive, fighter...",
"истребить" : "s. истреблять",
"истребление" : "destruction, extermination",
"истреблять" : "destroy annihilate, exterminate",
"истукан" : "idol, dolt, statue",
"истый" : "true genuine, zealous",
"истязание" : "torment",
"истязать" : "torment",
"исход" : "end outcome result, way out outlet vent, obsol. exit, Bibl. Exodus, быть на исходе come to an end, run short of",
"исходить" : "come emanate, originate proceed, start from, obsol. depart, famil. go all over, a. истекать",
"исходный" : "initial of departure",
"исхудалый" : "emaciated thin",
"исцарапать" : "pf. scratch",
"исцеление" : "healing, recovery",
"исцелить" : "heal cure, -ся recover",
"исцелять" : "heal cure, -ся recover",
"исчезать" : "disappear vanish",
"исчезновение" : "disappearance",
"исчезнуть" : "disappear vanish",
"исчерпать" : "exhaust use up, settle",
"исчерпывать" : "exhaust use up, settle",
"исчерпывающий" : "exhaustive",
"исчисление" : "calculation, math. calculus",
"исчислимый" : "countable, numerable",
"исчислить" : "calculate",
"исчислять" : "calculate",
"итак" : "thus so, well then now",
"италийский" : "italic",
"италия" : "Italy",
"итальянец" : "Italian",
"итальянка" : "Italian",
"итальянская забастовка" : "sit-down strike",
"итальянский" : "Italian",
"итог" : "sum total, result, в итоге in the end, подвести итог sum up",
"итого" : "altogether, in all total",
"иттербий" : "ytterbium",
"итти" : "s. идти",
"иуда" : "judah, judas",
"иудаизм" : "judaism",
"их" : "their, cf. они",
"ишь" : "popul. look listen, there, oh, now",
"ищейка" : "bloodhound sleuthhound",
"июль" : "July",
"июльский" : "july",
"июнь" : "June",
"июньский" : "june",
"йней" : "rime",
"йог" : "yogi",
"йога" : "yoga",
"йогурт" : "yoghurt, yogurt",
"йод" : "iodine",
"йота" : "ни на йоту",
"к" : "unto",
"к слову сказать" : "by the way",
"к сожалению" : "unfortunately to regret",
"к счастью" : "fortunately",
"к тому " : "in addition  moreover, add to this",
"кабачок" : "cabaret",
"кабинетный" : "closet",
"кабриолет" : "gig",
"кабул" : "kabul",
"кавалер" : "chevalier, lady,s man",
"кавалерия" : "cavalry horse",
"кавалькада" : "cavalcade",
"каверза" : "intrigue, trick",
"каверзный" : "tricky",
"кавказ" : "Caucasus",
"кавказец" : "Caucasian",
"кавказский" : "Caucasian",
"кавычки" : "quotation marks, в кавычках iron. so-called",
"кадило" : "cencer",
"кадить" : "cence",
"кадка" : "tub vat",
"кадмий" : "cadmium",
"кадр" : "cadre key group van, skilled workers, shot, close-up",
"кадриль" : "quadrille",
"кадровый" : "milit. regular active, commanding, skilled",
"кадык" : "Adam's apple",
"каждодневный" : "daily",
"каждый" : "every each, either, su. everybody everyone",
"кажется" : "s. казаться",
"кажущийся" : "s. казаться",
"казак" : "Cossack",
"казалось бы" : "one would think",
"казарма" : "barracks pl.",
"казармы" : "barrack",
"казаться" : "seem appear look, мне кажется  что ..., it seems to me that, он кажется прав he seems to be right, a. apparently; See also: кажущийся, казалось бы",
"казах" : "Kazak",
"казахская" : "ССР Kazak Soviet Socialist Republic",
"казахский" : "Kazak",
"казахстан" : "Kazakstan",
"казацкий" : "Cossack...",
"казачий" : "Cossack...",
"казеин" : "casein",
"казенный" : "state... government..., official public, formal perfunctory, commonplace, на казенный счет gratis",
"казна" : "treasury exchequer",
"казначей" : "treasurer, milit. paymaster",
"казначейство" : "exchequer",
"казнить" : "pf. execute put to death, fig. scourge",
"казнь" : "execution, punishment",
"каир" : "Cairo",
"кайзер" : "kaiser",
"кайма" : "border",
"как" : "how, as, like, what, but, since, famil. when if, very  awfully, suddenly, я видел как он шел ... I saw him going ..., как можно скорее, as soon as possible; See also: как будто, как бы, как бы мне, как ни, как же{!}, как так{?}, как же так{?}, как ... так и ..., как когда, как не",
"как , так и " : "both ... and ...",
"как бы мне" : "how am I to ...",
"как бы ни было" : "be that as it may",
"как на ладони" : "spread before the eyes",
"как на угольях" : "famil. on tenterhooks",
"как не" : "of course ...",
"как нельзя лучше" : "in the best way possible excellently",
"как ни" : "however",
"как ни говори" : "whatever one may say",
"как по маслу" : "fig. on wheels",
"как полагается" : "properly",
"как попало" : "anyhow at random haphazard",
"как раз" : "just  the very",
"как с гуся вода" : "famil. like water off a duck's back thick-skinned",
"как снег на голову" : "all of a sudden",
"как сыр в масле" : "in clover",
"как так" : "you don't say!",
"как только" : "as soon as",
"какаду" : "cockatoo",
"какао" : "cocoa",
"каким образом" : "how",
"как-нибудь" : "somehow, anyhow, sometime",
"каков" : "how, what, what sort of, as, каков! just look !; See also: каково{?}",
"каково" : "what do you say?",
"какой" : "what",
"как-то" : "adv. somehow, somewhat, famil. once one day, part. such as",
"кактус" : "cactus",
"кал" : "excrement",
"каламбур" : "pun, quirk, wordplay",
"калейдоскоп" : "kaleidoscope",
"калека" : "cripple",
"календарь" : "almanac, calendar",
"калибр" : "caliber, calipers, calliper",
"калий" : "potassium",
"калина" : "snowball tree",
"калитка" : "gate wicket",
"калить" : "накалить раскалить heat incandesce, roast, закалить engin. temper",
"калифорний" : "californium",
"калифорния" : "california",
"каллиграфия" : "calligraphy, penmanship",
"калория" : "calorie",
"калоши" : "s. галоши",
"калька" : "tracing, tracing paper, fig. loan translation",
"калькировать" : "trace",
"калькулировать" : "commerc. calculate",
"калькуляция" : "calculation",
"калькутта" : "calcutta",
"кальсоны" : "drawers underpants",
"кальций" : "calcium",
"камбала" : "flounder",
"камбоджа" : "cambodia",
"камелия" : "camellia",
"каменеть" : "turn to stone petrify",
"каменистый" : "stony",
"каменноугольный" : "coal ...",
"каменный" : "stone..., fig. stony, rock; See also: каменный уголь",
"каменный уголь" : "coal",
"каменоломня" : "quarry",
"каменотес" : "stonemason",
"каменщик" : "bricklayer mason",
"камень" : "stone, rock, a. calculus gravel, fig. weight, камнем like a stone",
"камень преткновения" : "stumbling block",
"камера" : "cell, med. ward, rail. room office, jur. milit. chamber, phot. camera, bladder, tube",
"камера хранения ручного багажа" : "Brt. left-luggage office",
"камергер" : "chamberlain",
"камердинер" : "dresser, valet",
"камерный" : "engin. chamber...",
"камин" : "fireplace",
"камка" : "damask",
"камнеломка" : "saxifrage",
"каморка" : "closet small room",
"кампания" : "pol. campaign",
"камфара" : "camphor",
"камчатка" : "Kamchatka",
"камчатый" : "damask...",
"камыш" : "reed",
"камышовый" : "reed",
"канава" : "ditch, gutter, drain",
"канавка" : "gutter",
"канада" : "Canada",
"канадец" : "Canadian"
};
