var dicctr_38 = {
"лопаться" : "burst, crack break, tear, famil. be exhausted",
"лопнуть" : "burst, crack break, tear, famil. be exhausted",
"лопух" : "burdock",
"лорнет" : "lorgnette",
"лоск" : "luster gloss polish",
"лоскут" : "rag shred scrap frazzle",
"лоскутный" : "patchwork",
"лосниться" : "be glossy #or sleek shine",
"лоснящийся" : "sleek",
"лосось" : "salmon",
"лось" : "elk",
"лосьон" : "lotion",
"лот" : "plummet lead",
"лотерея" : "lottery",
"лотовой" : "leadsman",
"лоток" : "hawker's stand tray",
"лотос" : "lotos, lotus",
"лоханка" : "tub",
"лохань" : "tub",
"лохматый" : "shaggy disheveled",
"лохмотья" : "rags",
"лоцман" : "pilot",
"лошадиная сила" : "horsepower",
"лошадиный" : "horse...",
"лошадка" : "gee",
"лошадь" : "horse",
"лошак" : "hinny",
"лощина" : "hollow valley",
"лощить" : "gloss polish",
"лояльность" : "loyalty",
"лояльный" : "loyal",
"луб" : "liber",
"лубок" : "med. splint, cheap popular print .",
"луг" : "meadow",
"лудить" : "tin",
"лужа" : "puddle pool, сесть в лужу famil. be in a pretty pickle",
"лужайка" : "glade",
"лужица" : "puddle",
"лук" : "onion, bow",
"лукавить" : "dissemble dodge",
"лукавство" : "cunning slyness ruse",
"лукавый" : "crafty wily",
"луковица" : "bulb, onion",
"лукпорей" : "leek",
"луна" : "moon",
"лунатик" : "sleepwalker",
"лунный" : "moon, astr. lunar",
"лупа" : "magnifier magnifying glass",
"лупить" : "peel",
"луч" : "ray beam",
"лучевой" : "radial",
"лучезарный" : "radiant",
"лучеиспускание" : "radiation",
"лучина" : "chip spill",
"лучистый" : "radiant",
"лучше" : "comp. #of хорошо",
"лучший" : "better, best",
"лущить" : "shell husk",
"лыжа" : "ski",
"лыжник" : "skier",
"лыжница" : "skier",
"лыжный" : "ski...",
"лыжный спорт" : "skiing",
"лыко" : "bast",
"лысина" : "bald head, blaze",
"лысый" : "bald",
"ль" : "знает ~ он ...?, does he know ...?, whether if, ... ли ... ли whether ... or ...",
"львиный" : "lion's",
"львиный зев" : "snapdragon",
"львица" : "lioness",
"льгота" : "privilege",
"льготный" : "privileged, reduced, favorable",
"льдина" : "ice floe",
"льнуть" : "cling nestle",
"льняной" : "flax, linen...",
"льстец" : "flatterer",
"льстивый" : "flattering",
"льстить" : "flatter",
"любезничать" : "court flirt spoon",
"любезность" : "amiability kindness, favor, pl. compliments",
"любезный" : "amiable kind, dear, su. sweetheart, famil. lovely",
"любимец" : "favorite pet",
"любимица" : "favorite pet",
"любимый" : "beloved darling, favorite pet",
"любитель" : "lover fan, amateur",
"любительница" : "lover fan, amateur",
"любительский" : "amateur",
"любить" : "love, like be fond of, pf. fall in love with",
"любоваться" : "admire delight",
"любовная связь" : "amour",
"любовник" : "lover",
"любовница" : "mistress",
"любовный" : "love..., loving affectionate",
"любовь" : "love, Любовь #fem. #name",
"любознательный" : "inquisitive curious, inquiring",
"любой" : "any",
"любой ценой" : "at any price",
"любопытный" : "curious inquisitive, interesting, мне любопытно ... I wonder ...",
"любопытство" : "curiosity, interest",
"любящий" : "loving affectionate",
"люд" : "people, obsol. servants; See also: выйти в люди, на людях",
"люди" : "people, obsol. servants; See also: выйти в люди, на людях",
"людный" : "populous, crowded",
"людоед" : "cannibal, ogre",
"людской" : "man..., man's, human, servants'",
"люк" : "hatch",
"люкс" : "lux",
"люксембург" : "luxembourg",
"люлька" : "cradle",
"люстра" : "chandelier luster",
"лютеранский" : "lutheran",
"лютик" : "buttercup",
"лютый" : "fierce cruel grim",
"люцерна" : "alfalfa Brt. lucerne",
"ля" : "la",
"лягать" : "kick",
"лягушка" : "frog",
"ляжка" : "thigh, haunch",
"лязг" : "clank clang chatter",
"лязгать" : "clank clang chatter",
"лямка" : "strap; See also: тянуть лямку",
"лямки" : "sling",
"м пр" : "abbr.: между прочим",
"мавзолей" : "mausoleum",
"мавританский" : "moorish, moresque",
"маг" : "mage, magus",
"магазин" : "shop, store",
"магистраль" : "arterial, artery, mains, trunk",
"магистрат" : "magistrate",
"магнат" : "baron, magnate",
"магнетит" : "loadstone, magnetite",
"магнето" : "magneto",
"магниевый" : "magnesium",
"магнитный" : "magnet, magnetic",
"магнолия" : "magnolia",
"магометанин" : "mohammedan",
"мадагаскар" : "madagascar",
"мадам" : "madam",
"мадера" : "madeira",
"мадонна" : "madonna",
"мадрид" : "madrid",
"мазать" : "помазать намазать smear, rub, anoint, spread butter, whitewash, смазать oil lubricate, famil. замазать soil, impf. daub",
"мазня" : "daub",
"мазок" : "touch stroke, med. swab",
"мазохизм" : "masochism",
"мазурка" : "mazurka",
"мазь" : "ointment, grease",
"май" : "May",
"майка" : "sleeveless sports shirt",
"майонез" : "mayonnaise",
"майор" : "major",
"майоран" : "marjoram",
"майский" : "May...",
"мак" : "poppy",
"макака" : "macaque, toque",
"макать" : "dip",
"макет" : "model, dummy",
"макинтош" : "mackintosh",
"маклер" : "broker",
"маклерство" : "brokerage",
"макнуть" : "dip",
"макрель" : "mackerel",
"макрокоманда" : "macro",
"макроскопический" : "macroscopic",
"максвелл" : "maxwell",
"максимальный" : "maximum",
"макулатура" : "trash, wastepaper",
"макушка" : "top, crown",
"мал и стар" : "young & old",
"малагасийский" : "malagasy",
"малаец" : "Malay",
"малайзия" : "malaysia",
"малайка" : "Malay",
"малайский" : "Malay",
"малая азия" : "Asia Minor",
"малевать" : "paint daub",
"малейший" : "least slightest",
"маленькая" : "petite",
"маленький" : "little small, short, trifling petty",
"малина" : "raspberry -ries pl.",
"малиновка" : "robin",
"малиновый" : "raspberry..., crimson, soft sonorous",
"мало" : "little, few, a little, not enough, less, мало ли что, мало что; See also: мало где, мало когда, мало того, мало того что",
"мало где" : "in few places",
"мало когда" : "seldom",
"мало ли что" : "much many things anything",
"мало того" : "besides and what is more",
"мало того, что" : "not only",
"мало что" : "yes but ..., that doesn't matter even though",
"маловажный" : "insignificant trifling",
"маловато" : "famil. little not enough",
"маловероятный" : "unlikely",
"маловодный" : "shallow",
"малоговорящий" : "insignificant",
"малограмотный" : "uneducated ignorant, faulty",
"малодушный" : "pusillanimous",
"малозначащий" : "s. маловажный",
"малозначительный" : "s. маловажный",
"малоимущий" : "poor",
"малокровие" : "anemia",
"малокровный" : "anemic",
"малолетний" : "minor underage, little",
"малолюдный" : "poorly populated",
"мало-мальски" : "famil. a little bit, somewhat",
"малообщительный" : "unsociable",
"малоопытный" : "inexperienced",
"мало-помалу" : "famil. gradually little by little",
"малопонятный" : "recondite",
"малорослая" : "galloway",
"малорослый" : "undersized",
"малосодержательный" : "vapid",
"малость" : "smallness, famil. trifle, a bit",
"малоценный" : "inferior",
"малочисленность" : "paucity",
"малочисленный" : "small  few",
"малый" : "small little, short, cf. маленький, su. fellow guy, lad; See also: без малого, мал и стар, с малых лет",
"малыш" : "kid",
"мальта" : "malta, maltha",
"мальтийский" : "maltese",
"мальтоза" : "maltose",
"мальчик" : "boy, lad",
"мальчишеский" : "boyish, mischievous",
"мальчишка" : "urchin, greenhorn",
"мальчуган" : "s. малыш, a. = мальчишка",
"малютка" : "baby infant, fig. pygmy... miniature...",
"маляр" : "painter",
"малярия" : "malaria",
"мама" : "ma mum mother",
"мамаша" : "mammy mummy",
"маменька" : "mammy mummy",
"мангуста" : "mongoose",
"мандарин" : "mandarin",
"мандат" : "mandate",
"мандатный" : "mandatory",
"маневр" : "maneuver manoeuvre, rail. shunt switch",
"маневрировать" : "maneuver manoeuvre, rail. shunt switch",
"манекен" : "mannequin",
"манера" : "manner",
"манерка" : "canteen Brt. water bottle",
"манерность" : "mannerism",
"манерный" : "affected",
"манжета" : "cuff",
"маниакальный" : "maniacal",
"манифестация" : "manifestation",
"мания" : "craze, mania",
"манометр" : "manometer",
"мансарда" : "attic, cockloft",
"мантисса" : "mantissa",
"мантия" : "gown, pallium, toga",
"манхеттен" : "manhattan"
};
