var dicctr_21 = {
"дуговая лампа" : "arc light",
"дугой" : "arched",
"дудка" : "pipe, famil. дудки! fudge! rats!, плясать под дудку #or по дудке, dance to s.b.'s tune #or piping",
"дудник" : "angelica",
"дужка" : "merrythought, wishbone",
"дуло" : "muzzle, barrel",
"дума" : "thought, meditation, duma = council, elective legislative assembly",
"думать" : "think, reflect meditate, intend be going to, care, famil. suspect, как ты думаешь? what do you think?, много думать о себе be conceited, не долго думая without hesitation, -ся seem appear, think",
"дунай" : "Danube",
"дуновение" : "waft breath",
"дунуть" : "s. дуть",
"дуня" : "dim. #of Евдокия",
"дупло" : "hollow, cavity",
"дура" : "silly woman",
"дурак" : "fool simpleton",
"дурак дураком" : "arrant fool",
"дурацкий" : "foolish silly, fool's",
"дурачество" : "tomfoolery",
"дурачить" : "fool hoax",
"дурачиться" : "fool play tricks",
"дуреть" : "grow stupid, become stupefied",
"дурить" : "s. дурачиться, be naughty #or obstinate",
"дурман" : "jimson weed thorn apple, fig. narcotic",
"дурманить" : "stupefy",
"дурнеть" : "grow plain #or ugly",
"дурной" : "bad, plain ugly, popul. stupid, мне дурно I feel sick #or unwell",
"дурнота" : "giddiness sickness",
"дуршлаг" : "colander",
"дурь" : "folly caprice, trash",
"дутый" : "blown, fig. inflated, false",
"дуть" : "blow, дует there is a draught",
"дуться" : "swell, famil. sulk be angry with, o.s. airs",
"дух" : "spirit, mind, courage, ghost, famil. breath, popul. scent, духом; See also: в духе, не в духе, в моем духе, на духу, во весь дух, что есть духу",
"духи" : "perfume",
"духовенство" : "coll. clergy",
"духовка" : "oven",
"духовная" : "testament will",
"духовник" : "confessor",
"духовное лицо" : "clergyman",
"духовный" : "spiritual, mental, ecclesiastical clerical religious sacred",
"духовный отец" : "= духовник",
"духовой" : "mus. wind",
"духовой оркестр" : "brassband",
"духом" : "in a jiffy #or trice, at one draught",
"духота" : "sultriness sultry air",
"душ" : "shower, douche",
"душа" : "soul, mind disposition, temper, feeling emotion, person, hist. serf, famil. #address: dear darling, душа в пятки ушла have one's heart in one's mouth; See also: душа в душу, в глубине души, от души, по душам",
"душа в душу" : "in perfect harmony",
"душевнобольной" : "mentally sick #or deranged",
"душевный" : "mental psychic, sincere hearty",
"душенька" : "darling",
"душеприказчица" : "executrix",
"душераздирающий" : "heart-rending",
"душистый" : "fragrant, sweet",
"душить" : "задушить strangle choke, надушить perfume",
"душный" : "stuffy, sultry",
"дуэль" : "duel",
"дуэт" : "duet",
"дыбом" : "on end",
"дыбы" : "на дыбы rear  prance",
"дым" : "smoke",
"дымный" : "smoky",
"дымоход" : "flue, stovepipe",
"дыня" : "melon",
"дыра" : "hole",
"дыхание" : "breath, breathing, respiration",
"дыхательное горло" : "windpipe",
"дыхательный" : "respiratory",
"дышать" : "breathe, o.s. to indulge in, foam with, дышать свежим воздухом take the air, еле дышать #or дышать на ладан, famil. have one foot in the grave",
"дышло" : "pole",
"дьявол" : "devil",
"дьявольский" : "devilish",
"дьяк" : "clerk & chanter sexton",
"дьякон" : "deacon",
"дьяконица" : "deaconess",
"дьячок" : "clerk & chanter sexton",
"дюжий" : "sturdy",
"дюжина" : "dozen",
"дюжинами" : "by the dozen",
"дюжинный" : "common mediocre",
"дюйм" : "inch",
"дюймовый" : "inch",
"дюна" : "dune",
"дюралюминий" : "duralumin",
"дядька" : "& contp. = дядя, obsol. tutor instructor",
"дядя" : "uncle, famil. fellow guy",
"дятел" : "woodpecker",
"ева" : "Eve",
"евангелие" : "Gospel",
"евангельский" : "evangelic, evangelical",
"евгений" : "Eugene",
"евгенический" : "eugenic",
"евгения" : "Eugenia",
"евдокия" : "Eudoxia",
"евреи" : "jewry",
"еврей" : "Jew",
"еврейка" : "Jewess",
"еврейский" : "Jewish",
"европа" : "Europe",
"европеец" : "European",
"европейка" : "European",
"европейский" : "European",
"европий" : "europium",
"егерь" : "hunter, milit. chasseur",
"египет" : "Egypt",
"египетский" : "Egyptian",
"египтянин" : "Egyptian",
"египтянка" : "Egyptian",
"его" : "his, its, cf. он",
"его и след простыл" : "famil. he was off and away",
"егор" : "George",
"еда" : "food, meal",
"едва" : "hardly scarcely, a. еле, no sooner; See also: едва не, едва ли не",
"едва ли не" : "perhaps",
"едва не" : "almost nearly",
"едва только" : "no sooner ... than",
"единение" : "unity union",
"единица" : "math. one, digit, unit, famil. very bad, pl. few",
"единичный" : "single isolated",
"едино" : ":; See also: единоборство, единовластие, единовременный, единогласие, единогласный, единогласно, единодушие, единодушный, единоличный, единомыслящий, единомышленник, единообразный, единорог",
"единогласный" : "unanimous",
"единодушие" : "unanimity",
"единодушный" : "unanimous",
"единокровный" : "consanguine, consanguineous",
"единоличный" : "individual  personal",
"единомыслящий" : "like-minded",
"единомышленник" : "like-minded pers. associate confederate",
"единообразный" : "uniform",
"единорог" : "unicorn",
"единственное число" : "gr. singular",
"единственный" : "only single sole, единственный в своем роде unique",
"единство" : "unity, unanimity",
"единый" : "one single, only  sole, one whole, united, same, все до единого all to a man",
"едкий" : "caustic",
"едок" : "eater",
"ее" : "her, its, cf. она",
"еж" : "hedgehog",
"ежевика" : "blackberry -ries pl.",
"ежегодник" : "annals, yearbook",
"ежегодный" : "annual",
"ежедневный" : "daily, everyday",
"ежемесячный" : "monthly",
"ежеминутный" : "every minute, continual",
"еженедельный" : "weekly",
"ежечасный" : "hourly",
"ежиться" : "shrink, be shy",
"ежовый" : "держать в ежовых рукавицах, rule with a rod of iron",
"езда" : "drive",
"елейный" : "oleaginous, saponaceous",
"ель" : "fir",
"ельник" : "fir wood",
"емкий" : "capacious",
"емкость" : "capacity, мера емкости cubic measure",
"ему" : "him",
"енисей" : "Yenisei",
"енот" : "raccoon",
"енох" : "enoch",
"епархиальный" : "diocesan",
"епархия" : "diocese, eparchy",
"епископ" : "bishop",
"епископальный" : "episcopalian",
"епископский" : "episcopal, pontifical",
"ералаш" : "mess muddle jumble",
"ересь" : "heresy",
"еретик" : "heretic",
"еретический" : "heretical",
"ерзать" : "fidget, slip",
"ерошить" : "= взьерошивать s",
"ерунда" : "nonsense, trifle",
"если" : "if in case, once, ах #or о _ б ... oh could #or would ...; See also: а если, и если, если и, если же, если бы не, если только",
"если бы не" : "but for",
"если же" : "even though",
"естественный" : "natural, unschooled, unstudied",
"естествовед" : "naturalist scientist",
"естествоведение" : "natural science",
"естествознание" : "natural science",
"естествоиспытатель" : "s. естествовед",
"есть" : "ate, eat, eaten",
"есть такой грех" : "famil. well I own it",
"есть1" : "сьесть поесть eat  have, разьесть eat away, chem. corrode, bite, famil. поесть разьесть bite gnaw sting, popul. torment",
"есть2" : "cf. быть, am is are, there is, у меня ~ ... I have ..., так и ~ indeed!, ~ такое дело! famil. O.K., есть! milit. yes sir!",
"ефрейтор" : "private first class Brt. lance-corporal",
"ехать" : "go  ride drive, come, run, leave  go, go for fetch, поехали! s. идти",
"ехидный" : "spiteful malignant",
"ехидство" : "spite malice",
"еще" : "yet, still, another more, else, already, as early as, possibly probably, more or less somewhat; See also: еще не, все еще, еще раз, еще бы{!}",
"еще бы" : "sure! I should think so! of course!, it would be worse still if...",
"жаба" : "toad",
"жабры" : "branchiae, gill, gills",
"жаворонок" : "lark",
"жадничать" : "be greedy #or avaricious",
"жадность" : "greed avarice",
"жадный" : "greedy  avaricious",
"жажда" : "thirst",
"жаждать" : "thirst crave",
"жакет" : "jacket",
"жакетка" : "jacket",
"жалеть" : "pity, regret, spare, grudge",
"жалить" : "sting bite",
"жалкий" : "pitiable, miserable wretched",
"жалко" : "s. жаль",
"жало" : "sting",
"жалоба" : "complaint, jur. action",
"жалобный" : "mournful plaintive, complaint",
"жалобы" : "lamentation",
"жалование" : "salary",
"жалованье" : "pay salary, reward",
"жаловать" : "reward award, give, appoint, famil. like, come, -ся complain, famil. inform, jur. sue go to law",
"жаловаться" : "complain",
"жалостливый" : "compassionate, sorrowful",
"жалостный" : "mournful, compassionate",
"жалость" : "pity compassion",
"жаль" : "it is a pity, unfortunately, : мне ~ его I am sorry for him, a. regret, grudge",
"жалюзи" : "jalousie, louver",
"жанровый" : "genre",
"жар" : "heat, fever, fig. ardor",
"жара" : "heat hot weather",
"жаргон" : "argot, jargon, lingo, pidgin, slang",
"жареное" : "roast",
"жареный" : "fried, roast, a. жаркое",
"жарить" : "roast, fry, famil. burn",
"жаркий" : "hot, fig. ardent vehement intense, мне жарко I am hot",
"жаркое" : "roast meat",
"жатва" : "harvest, crop",
"жатвенный" : "reaping",
"жать1" : "& пожать press squeeze, shake, pinch, fig. oppress, -ся shrink, crowd, snuggle, famil. vacillate",
"жать2" : "reap harvest",
"жвачка" : "rumination, cud, popul. chewing gum",
"жвачные" : "ruminants",
"жвачный" : "ruminant",
"жгут" : "strap",
"жгучий" : "burning, poignant",
"жд" : "abbr.: железная дорога, cf. R.R. Ry",
"ждать" : "await, wait, wait for",
"жевать" : "munch",
"жезл" : "baton, mace",
"желаемый" : "wishful",
"желание" : "desire, wish",
"желанный" : "desired long wished for, welcome, beloved",
"желательный" : "desirable, desired, мне желательно I am anxious to",
"желатин" : "gelatin",
"желать" : "wish  desire, love",
"желающие" : "persons wishing to ...",
"желающий" : "desirous",
"желе" : "jelly",
"железа" : "gland",
"железистый" : "chalybeate, ferrous",
"железнодорожник" : "railroad man",
"железнодорожный" : "railroad... Brt. railway...",
"железный" : "iron..., rail.."
};
