var dicctr_61 = {
"подвигать" : "move, push",
"подвижной" : "mobile, movable, nimble, rail. rolling",
"подвижность" : "mobility, agility",
"подвижный" : "agile, motile",
"подвизаться" : "be active",
"подвинуть" : "move, push",
"подвластный" : "subject",
"подвода" : "cart, wagon",
"подводить" : "lead, bring get, lay, build, make, pers. down",
"подводная лодка" : "submarine",
"подводный" : "submarine; See also: подводная лодка, подводный камень",
"подводный камень" : "reef",
"подвоз" : "supplies pl.",
"подвозить" : "bring get, give a pers. a lift",
"подвыпивший" : "tipsy drunk",
"подвязать" : "tie",
"подвязка" : "garter",
"подвязывать" : "tie",
"подгибать" : "tuck, bend, -ся fail",
"подглядеть" : "peep spy",
"подглядывать" : "peep spy",
"подговаривать" : "instigate talk a pers. into",
"подговорить" : "instigate talk a pers. into",
"подгонять" : "drive #or urge on hurry, fit adapt",
"подгорать" : "burn",
"подгореть" : "burn",
"подготовительный" : "preparatory",
"подготовить" : "prepare",
"подготовка" : "preparation, training, milit. drill",
"подготовлять" : "prepare",
"подгузник" : "diaper",
"поддаваться" : "yield; See also: не поддаваться",
"поддакивать" : "say yes  consent",
"поддакнуть" : "say yes  consent",
"подданный" : "subject",
"подданство" : "nationality citizenship",
"поддаться" : "yield; See also: не поддаваться",
"подделать" : "forge",
"подделка" : "forgery counterfeit",
"подделывать" : "forge",
"поддельный" : "counterfeit..., sham...",
"поддержать" : "support, back up, uphold, maintain",
"поддерживать" : "support, back up, uphold, maintain",
"поддержка" : "support, approval",
"подействовать" : "act work, operate function, apply, have effect, get",
"поделать" : "pf. do, ничего не поделаешь there's nothing to be done, a. делать famil.",
"поделом" : "famil. rightly; See also: поделом ему",
"поделом ему" : "it serves him right",
"поделывать" : "что поделываете?, what are you doing ?",
"подержанный" : "secondhand",
"подешеветь" : "cheapen become cheaper",
"поджаривать" : "roast brown, toast",
"поджарить" : "roast brown, toast",
"поджарый" : "lean",
"поджать" : "s. поджимать",
"поджать хвост" : "famil. come down a peg",
"поджечь" : "s. поджигать",
"поджигатель" : "incendiary",
"поджигать" : "set on the fire",
"поджидать" : "wait",
"поджилки" : "hough",
"поджимать" : "cross, purse, draw in",
"поджог" : "arson, burning",
"подзаголовок" : "subtitle",
"подзадоривать" : "instigate incite",
"подзадорить" : "instigate incite",
"подзатыльник" : "cuff on the nape",
"подзащитный" : "jur. client",
"подземелье" : "vault cave, dungeon",
"подземельный" : "land... ground...",
"подземмый" : "underground",
"подземный" : "underground subterranean, cf. метро",
"подзорная труба" : "spyglass",
"подзывать" : "call beckon",
"поди" : "popul. come, go, try, I suppose",
"подивиться" : "wonder",
"подкаменщик" : "bullhead",
"подкапываться" : "undermine",
"подкарауливать" : "s. подстерегать",
"подкараулить" : "s. подстерегать",
"подкармливать" : "feed fatten",
"подкатить" : "roll #or drive up",
"подкатывать" : "roll #or drive up",
"подкашиваться" : "fail",
"подкидывать" : "s. подбрасывать",
"подкидыш" : "foundling",
"подкинуть" : "s. подбрасывать",
"подкладка" : "lining, engin. support",
"подкладывать" : "lay, add, enclose, foist",
"подклеивать" : "glue paste",
"подклеить" : "glue paste",
"подкова" : "horseshoe",
"подкованный" : "a. versed",
"подковать" : "shoe",
"подковывать" : "shoe",
"подкожный" : "hypodermic",
"подкоп" : "sap mine",
"подкопаться" : "undermine",
"подкормить" : "feed fatten",
"подкоситься" : "fail",
"подкрадываться" : "steal #or sneak up",
"подкрасить" : "touch up, make up",
"подкрасться" : "steal #or sneak up",
"подкрашивать" : "touch up, make up",
"подкрепить" : "reinforce fortify, corroborate, refresh",
"подкрепление" : "reinforcement, corroboration, refreshment",
"подкреплять" : "reinforce fortify, corroborate, refresh",
"подкуп" : "bribery",
"подкупать" : "bribe, win prepossess",
"подкупить" : "bribe, win prepossess",
"подкупной" : "corrupt",
"подладиться" : "adapt o.s., make up to",
"подлаживаться" : "adapt o.s., make up to",
"подле" : "beside by, nearby",
"подлежать" : "be subject to, be to be, не подлежит, there can be no",
"подлежащее" : "gr. subject",
"подлежащий" : "subject, ...able",
"подлезать" : "creep",
"подлезть" : "creep",
"подлетать" : "fly",
"подлететь" : "fly",
"подлец" : "scoundrel rascal",
"подливать" : "pour add",
"подливка" : "gravy, sauce",
"подлиза" : "toady",
"подлизаться" : "flatter insinuate o.s.",
"подлизываться" : "flatter insinuate o.s.",
"подлинник" : "original",
"подлинность" : "authenticity",
"подлинный" : "original, authentic genuine, true, pure",
"подлить" : "pour add",
"подличать" : "act meanly",
"подлог" : "forgery",
"подложить" : "lay, add, enclose, foist",
"подложный" : "spurious false",
"подлость" : "meanness, low act",
"подлый" : "mean base low",
"подмазать" : "grease  smear, famil. make up, -ся o.s.",
"подмазывать" : "grease  smear, famil. make up, -ся o.s.",
"подманивать" : "beckon",
"подманить" : "beckon",
"подмастерье" : "journeyman",
"подмена" : "substitution exchange",
"подменивать" : "substitute change",
"подменить" : "substitute change",
"подмести" : "sweep",
"подметать" : "sweep",
"подметить" : "s. подмечать",
"подметка" : "sole",
"подмечать" : "notice observe perceive",
"подмешать" : "mix  adulterate",
"подмешивать" : "mix  adulterate",
"подмигивать" : "wink",
"подмигнуть" : "wink",
"подмога" : "help assistance",
"подмокать" : "get wet",
"подмокнуть" : "get wet",
"подмостки" : "scaffold, stage",
"подмоченный" : "wet, famil. stained",
"подмывать" : "wash, famil. press",
"подмыть" : "wash, famil. press",
"подмышка" : "armpit",
"поднебесье" : "firmament",
"подневольный" : "dependent, forced",
"поднести" : "s. подносить",
"поднимать" : "lift, pick up, elevate, set, take up, hoist, weigh, set, give, make, scare, plow up; See also: поднять нос, поднять на ноги, поднять на смех",
"подниматься" : "rise, arise, go up, climb, set out, get agitated",
"подноготная" : "ins & outs pl.",
"подножие" : "foot bottom, pedestal",
"подножка" : "footboard, mot. running board, trip",
"подножный" : "green",
"поднос" : "tray",
"подносить" : "bring carry, offer present",
"подношение" : "gift",
"поднятие" : "raise raising, rise, elevation cf. поднимать",
"поднять" : "lift, pick up, elevate, set, take up, hoist, weigh, set, give, make, scare, plow up; See also: поднять нос, поднять на ноги, поднять на смех",
"поднять на ноги" : "alarm",
"поднять на смех" : "ridicule",
"поднять нос" : "assume airs",
"подобает" : "it becomes, ought",
"подобие" : "resemblance, image, math. similarity",
"подобный" : "similar, such; See also: и тому подобное, ничего подобного",
"подобострастный" : "servile",
"подобрать" : "pick up, tuck up, draw in, pick out select, -ся sneak up",
"подогнать" : "drive #or urge on hurry, fit adapt",
"подогнуть" : "tuck, bend, -ся fail",
"подогревать" : "warm up",
"подогреть" : "warm, heat; See also: греться на солнце",
"пододвигать" : "move",
"пододвинуть" : "move",
"подождать" : "wait, expect await, время не ждет time presses, ждать не дождаться wait impatiently",
"подозвать" : "call beckon",
"подозревать" : "suspect",
"подозрение" : "suspicion",
"подозрительный" : "suspicious",
"подоить" : "milk",
"подоконник" : "windowsill",
"подольщаться" : "wheedle",
"подонки" : "dregs",
"подопытный" : "test...",
"подорвать" : "s. подрывать",
"подорожать" : "become dearer rise in price",
"подорожная" : "hist. post-horse order",
"подорожник" : "plantain ribwort",
"подослать" : "s. подсылать",
"подоспеть" : "pf. come",
"подостлать" : "s. подстилать",
"подотдел" : "sub-division",
"подотчетный" : "accountable",
"подохнуть" : "die, popul. croak kick off",
"подоходный" : "income",
"подошва" : "sole, foot bottom",
"подпадать" : "fall",
"подпаивать" : "make drunk",
"подпалить" : "famil. = поджечь, singe",
"подпасок" : "shepherd boy",
"подпасть" : "fall",
"подпевать" : "s. вторить",
"подпереть" : "support prop",
"подпирать" : "support prop",
"подписать" : "s. подписывать",
"подпись" : "signature, signing up",
"подполковник" : "lieutenant colonel",
"подполье" : "underground",
"подпольный" : "underground",
"подпора" : "prop",
"подпорка" : "prop",
"подпруга" : "girth, surcingle",
"подпрыгивание" : "dap, skip",
"подражательный" : "mimetic",
"подражать" : "imitate",
"подразделение" : "subdivision, milit. unit",
"подразделить" : "subdivide",
"подразделять" : "subdivide",
"подразумеваемый" : "implicit, implied, tacit",
"подразумевать" : "mean  imply",
"подразумеваться" : "be implied, commerc. be understood",
"подрастать" : "grow, rise",
"подрасти" : "grow, rise",
"подраться" : "scuffle fight struggle",
"подрезать" : "cut, crop clip",
"подрезывать" : "cut, crop clip",
"подробно" : "in detail in full",
"подробность" : "detail",
"подробный" : "detailed full-length",
"подровнять" : "straighten, level, clip",
"подросток" : "teenager, youth juvenile",
"подрубать" : "cut, hem",
"подрубить" : "cut, hem",
"подруга" : "friend, playmate"
};
