var dicct_8 = {
"be touched" : "быть тронутым, быть слегка помешанным",
"be unable" : "не быть в состоянии не [с]мочь",
"be unaware of" : "ничего не знать о, не замечать [-етить]",
"be unconscious of" : "не сознать",
"be up against a task" : "стоять перед задачей",
"be up to the mark" : "быть на должной высоте",
"be well off" : "быть зажиточным быть в хорошем положении",
"be wont" : "иметь обыкновение",
"be worth" : "заслуживать стоить",
"be worth-while" : "иметь смысл",
"be wrapped up in" : "быть погруженным в",
"be wrecked" : "потерпеть аварию крушение, разрушаться [-ушиться]",
"be wrong" : "быть неправым",
"beach" : "пляж взморье, вытащить на берег, посадить на мель",
"beachhead" : "плацдарм высадки десанта",
"beacon" : "сигнальный огонь, бакен, буй",
"bead" : "бусина бисерина, капля; See also: beads",
"beadle" : "n  1) университетский педель  2) уст. церковный сторож  3) курьер при суде",
"beads" : "четки, бусы, бисер",
"beady" : "похожий на бусинку",
"beak" : "клюв, носик",
"beam" : "балка брус, луч, сиять, излучать [-чить]",
"bean" : "боб",
"bear" : "медведь, спекулянт играющий на понижение, носить [нести], [вы]терпеть выдерживать [выдержать], рождать [родить]; See also: bear down, bear out, bear self, bear up, bear on, bear upon, bring to bear",
"bear down" : "преодолеть",
"bear in mind" : "помнить не забыть",
"bear on" : "касаться [коснуться], иметь отношение к",
"bear out" : "подтверждать [-рдить]",
"bear self" : "держаться вести себя",
"bear up" : "поддерживать [-жать]",
"bear upon" : "касаться [коснуться], иметь отношение к",
"bear witness" : "свидетельствовать",
"beard" : "борода, зубец, смело выступать против; See also: ость",
"bearer" : "носильщик, податель",
"bearing" : "ношение, терпение, манера держать себя, деторождение",
"bearish" : "неотесанный",
"beast" : "зверь, скотина; See also: beastly",
"beast (bird) of prey" : "хищный зверь",
"beastie" : "n  1) шутл. зверь  2) разг. насекомое",
"beastly" : "грубый ужасный",
"beat" : "[по]бить, ударять [ударить], [по]колотить, бить, биться, [по]стучаться, удар, бой, биение, ритм; See also: beat a retreat, beat up, beat about the bush",
"beat a retreat" : "отступать [-пить]",
"beat about the bush" : "подходить к делу издалека",
"beat up" : "избить, взбить",
"beaten" : "от beat, битый побежденный, проторенный",
"beater" : "тот, кто бьет",
"beatific" : "блаженный",
"beatify" : "давать блаженство",
"beatitude" : "блаженство",
"beatnik" : "битник",
"beau" : "щеголь, кавалер",
"beau-monde" : "n  бомонд, высший свет",
"beauteous" : "прекрасный",
"beautiful" : "прекрасный красивый",
"beautify" : "украшать [украсить]",
"beauty" : "красота, красавица",
"beaver" : "бобр",
"bebop" : "n  бибоп (стиль джазовой музыки)",
"becalm" : "успокаивать",
"became" : "от become",
"because" : "потому что так как; See also: because of",
"because of" : "из-за",
"beck" : "ручей",
"beckon" : "[по]манить",
"becloud" : "затемнять",
"become" : "[ ], [с]делаться, становиться [стать], быть к лицу идти, подобать",
"become aware of" : "отдавать себе отчет в",
"becoming" : "к лицу",
"bed" : "постель, кровать, грядка клумба, класть или ложиться в постель, высаживать [высадить]; See also: bed-clothes, bedding, bedroom, bedspread, bedstead, bedtime",
"bed-clothes" : "постельное белье",
"bedazzle" : "ослепить блеском",
"bedbug" : "клоп постельный",
"bedding" : "постельные принадлежности",
"bedevil" : "[ис]терзать [из]мучить, околдовывать [-довать]",
"bedfast" : "a  амер. прикованный к постели (болезнью)",
"bedim" : "затемнять",
"bedimmed" : "See: bedim",
"bedimming" : "See: bedim",
"bedlam" : "сумасшедший дом",
"bedpost" : "столбик кровати",
"bedraggle" : "забрызгать грязью",
"bedrid" : "прикованный к постели",
"bedridden" : "прикованный к постели",
"bedrock" : "коренная порода",
"bedroom" : "спальня",
"bedside" : "n:  to sit (или to watch) at (или by) a person's bedside ухаживать за больным;  to have a good bedside manner уметь подойти к больному (о враче);  to keep books at one's bedside держать книги у изголовья кровати",
"bedspread" : "покрывало",
"bedstead" : "кровать",
"bedstraw" : "n  бот. подмаренник",
"bedtime" : "время ложиться спать",
"bee" : "пчела; See also: have a bee in one's bonnet",
"bee-line" : "прямая линия",
"beech" : "бук буковое дерево",
"beechnut" : "буковый орешек",
"beef" : "говядина; See also: beef-tea, beefy",
"beef-tea" : "крепкий бульон",
"beefsteak" : "n  бифштекс",
"beefy" : "мускулистый, мясистый",
"beehive" : "улей",
"been" : "от be",
"beep" : "небольшой джип",
"beer" : "пиво; See also: small beer",
"beet" : "свекла",
"beetle" : "жук",
"befall" : "[ ] постигать [-игнуть -ичь], случаться [-читься]",
"befallen" : "See: befall",
"befell" : "See: befall",
"befit" : "приличествовать  подходить [подойти]",
"befitting" : "See: befit",
"befog" : "затуманивать",
"befogging" : "See: befog",
"before" : "впереди вперед, раньше, прежде чем, скорее чем, перед, впереди, до; See also: long before, beforehand",
"before long" : "вскоре",
"beforehand" : "заранее заблаговременно",
"befoul" : "пачкать",
"befriend" : "относиться по-дружески к",
"befuddle" : "одурманивать",
"beg" : "[по]просить, умолять [-лить], выпрашивать [выпросить], нищенствовать",
"began" : "от begin",
"beget" : "[ ] рождать [родить] производить [-вести]",
"begetting" : "See: beget",
"beggar" : "нищий нищенка, разорять [-рить] доводить до нищеты, превосходить [-взойти]; See also: it beggars all description",
"beggary" : "нищета",
"begging" : "нищенство",
"begin" : "начать; See also: beginner, beginning",
"beginner" : "начинающий новичок",
"beginning" : "начало",
"begonia" : "n  бот. бегония",
"begot" : "от beget",
"begotten" : "от beget",
"begrudge" : "[по]завидовать",
"beguile" : "обманывать [-нуть], [с]коротать",
"begun" : "от begin",
"behalf" : "on behalf of; See also: in behalf of",
"behave" : "вести себя, поступать [-пить]",
"behavior" : "поведение",
"behaviour" : "поведение",
"behead" : "обезглавливать [-главить]",
"beheld" : "See: behold",
"behest" : "завет",
"behind" : "после, позади сзади, за, позади  сзади, после",
"behold" : "[ ], замечать [-етить] [у]видеть, смотри! вот",
"behoof" : "to behoof of; See also: for behoof of, on behoof of, to the behoof of, for the behoof of, on the behoof of",
"beige" : "бежевый",
"being" : "бытие существование",
"beirut" : "бейрут",
"belate" : "See: belated",
"belated" : "запоздалый",
"belch" : "отрыжка, столб, рыгать [рыгнуть], извергать [-ергнуть]",
"belfry" : "колокольня",
"belgian" : "бельгиец, бельгийский",
"belgium" : "бельгия",
"belgrade" : "белград",
"belie" : "изобличать",
"belief" : "вера, убеждение",
"belies" : "See: belie",
"believable" : "правдоподобный",
"believe" : "[по]верить",
"believer" : "верующий",
"belittle" : "умалять [-лить], принижать [-низить]",
"bell" : "колокол, звонок",
"belladonna" : "красавка",
"bellboy" : "коридорный",
"belle" : "красавица",
"belles-lettres" : "художественная литература беллетристика",
"bellflower" : "n  бот. колокольчик",
"bellicose" : "воинственный",
"belligerent" : "воюющая сторона, воюющий",
"bellman" : "глашатай",
"bellmen" : "See: bellman",
"bellow" : "мычание, рев, [за]мычать, [за]реветь [за]бушевать",
"bellows" : "кузнечные мехи",
"bellwether" : "n  баран-вожак с бубенчиком (в стаде); перен. вожак",
"belly" : "живот брюхо, надуть",
"bellyache" : "1. n боль в животе 2. v разг. ворчать, жаловаться, хныкать",
"belong" : "принадлежать, относиться",
"belongings" : "принадлежности, пожитки",
"beloved" : "возлюбленный любимый",
"below" : "внизу, ниже, ниже, под",
"belt" : "пояс, зона, приводной ремень, портупея, подпоясать, пороть ремнем",
"belvedere" : "n  архит. бельведер",
"belying" : "See: belie",
"bemoan" : "оплакать",
"bemuse" : "ошеломлять",
"ben" : "n  шотл. вторая комната в небольшом двухкомнатном доме;  far ben во внутренних покоях;  but and ben первая и вторая комнаты, т. е. весь дом [ср.but II]  	to be far ben with smb. быть в близких отношениях с кем-л.",
"bench" : "скамья, верстак",
"benchmark" : "отметка уровня",
"bend" : "сгиб, изгиб, излучина, узел шпангоут, сгибать [согнуть], направлять [-равить], покорять [-рить]",
"bender" : "клещи",
"beneath" : "<-> below",
"benedictine" : "n   бенедиктинец (монах)",
"benediction" : "благословение",
"benefaction" : "благодеяние",
"benefactor" : "благодетель",
"benefice" : "приход",
"beneficence" : "благотворительность",
"beneficent" : "благодетельный",
"beneficial" : "благотворный полезный",
"beneficiary" : "феодальный вассал",
"benefit" : "выгода польза, пособие, бенефис, приносить пользу, извлекать пользу",
"benevolence" : "благожелательность",
"benevolent" : "благожелательный",
"bengal" : "бенгальский",
"bengali" : "бенгальский",
"benighted" : "a  1) невежественный; отсталый  2) застигнутый ночью",
"benign" : "добрый милостивый; See also: доброкачественный",
"benjamin" : "младший сын",
"bent" : "от bend, склонность; See also: bent on",
"bent on" : "помешанный на",
"benzedrine" : "n  бензедрин, фенамин (стимулирующее средство)",
"benzene" : "бензол",
"benzine" : "бензин",
"bequeath" : "завещать",
"bequest" : "наследство",
"berate" : "ругать",
"bereave" : "лишать [-шить], отнимать [-нять]",
"bereft" : "лишать",
"beret" : "берет",
"berg" : "айсберг",
"bergamot" : "n  бот. бергамот",
"berian" : "сибирский, сибиряк",
"beriberi" : "n  бери-бери, авитаминоз",
"berlin" : "ковкое железо",
"bermudas," : "Bermuda shorts  n pl  бермуды",
"bern(e)" : "геогр. Берн",
"berne" : "See: bern(e)",
"berry" : "ягода",
"berserk" : "бешеный",
"berth" : "якорная стоянка, койка, должность",
"bertha" : "n  берта, кружевной воротник",
"beryl" : "берилл",
"beryllium" : "бериллий",
"beseech" : "умолять [-лить] упрашивать [упросить]",
"beset" : "[ ] окружать [-жить], осаждать [осадить]",
"besetting" : "постоянно преследующий",
"beside" : "рядом с  около  близ, мимо; See also: beside self, beside the question",
"beside self" : "вне себя",
"beside the question" : "некстати не по существу",
"besides" : "кроме того сверх того, кроме",
"besiege" : "осаждать [осадить]",
"besmear" : "[за]пачкать [за]марать",
"besmirch" : "пачкать",
"besom" : "метла веник",
"besotted" : "одурманенный",
"besought" : "от beseech",
"bespatter" : "забрызгать",
"bespeak" : "[ ] заказывать [-зать]; See also: bespoke tailor",
"bespectacled" : "носящий очки",
"bespoke" : "сделанный на заказ",
"bespoke tailor" : "портной работающий по заказу",
"bessemer" : "a:  Bessemer process метал. бессемеровский процесс",
"best" : "лучший, лучше всего всех, самое лучшее; See also: best man, to the best of ..., make the best of, at best",
"best man" : "шафер",
"bestial" : "скотский животный",
"bestir" : "пробуждать",
"bestirring" : "See: bestir",
"bestow" : "даровать  награждать [-радить]",
"bestowal" : "n  дар; награждение",
"bet" : "пари, держать пари, биться об заклад",
"beta" : "n  бета (вторая буква греческого алфавита)  	beta plus немного лучше второго сорта",
"betake" : "[ ]:; See also: betake self to",
"betake self to" : "[ ]:, отправляться [-авиться] в, прибегать [-егнуть] к"
};
