var dicctr_55 = {
"отрешать" : "dismiss, release, -ся relinquish",
"отрешение" : "dismissal removal, renunciation",
"отрешить" : "dismiss, release, -ся relinquish",
"отрицание" : "negation denial",
"отрицательный" : "negative",
"отрицать" : "deny",
"отрог" : "spur",
"отроду" : "famil. from birth, in one's life",
"отродье" : "spawn",
"отрок" : "boy",
"отросток" : "bot. shoot, anat. appendix",
"отроческий" : "boyish",
"отрочество" : "boyhood, adolescence",
"отрубать" : "cut off",
"отруби" : "bran",
"отрубить" : "cut off",
"отрыв" : "separation, disengagement, alienation, interruption",
"отрывать" : "оторвать, tear off away, separate, -ся come off, turn away, lose contact, milit. disengage, не отрываясь without rest, отрыть dig up out away, famil. disinter",
"отрывистый" : "abrupt",
"отрывной" : "sheet #or block",
"отрывок" : "fragment, extract passage",
"отрывочный" : "fragmentary, scrappy",
"отрыжка" : "belch, famil. survival",
"отрыть" : "s. отрывать",
"отряд" : "detachment, squadron, troop, zo. class",
"отрядить" : "detach",
"отряжать" : "detach",
"отряхивать" : "shake off",
"отряхнуть" : "shake off",
"отсадка" : "jigging",
"отсвечивать" : "shimmer",
"отсеивать" : "sift, fig. eliminate",
"отсекать" : "cut off",
"отсечение" : "cutting off",
"отсечка" : "cutoff",
"отсечь" : "cut off",
"отсеять" : "sift, fig. eliminate",
"отскакивать" : "jump off back, rebound, famil. fall off",
"отскочить" : "jump off back, rebound, famil. fall off",
"отслуживать" : "serve, be worn out, hold",
"отслужить" : "serve, be worn out, hold",
"отсоветовать" : "pf. dissuade",
"отсохнуть" : "s. отсыхать",
"отсрочивать" : "postpone, respite",
"отсрочить" : "postpone, respite",
"отсрочка" : "delay, respite, prolongation",
"отставать" : "lag fall #or remain behind, #clock: be slow, desert, leave off, come off, pf. leave alone",
"отставить" : "remove set aside, dismiss, famil. countermand",
"отставка" : "resignation retirement, dismissal, в отставке = ной",
"отставлять" : "remove set aside, dismiss, famil. countermand",
"отставник" : "retiree",
"отставной" : "retired",
"отстаивать" : "defend save, maintain assert, rush, famil. stand, tire, pf. be away, -ся settle",
"отсталость" : "backwardness",
"отсталый" : "backward",
"отстать" : "lag fall #or remain behind, #clock: be slow, desert, leave off, come off, pf. leave alone",
"отстегивать" : "unbutton unfasten",
"отстегнуть" : "unbutton unfasten",
"отстой" : "dreg",
"отстоять" : "defend save, maintain assert, rush, famil. stand, tire, pf. be away, -ся settle",
"отстоящий" : "away",
"отстраивать" : "build",
"отстранить" : "push aside remove, dismiss, debar, -ся dodge, shirk",
"отстранять" : "push aside remove, dismiss, debar, -ся dodge, shirk",
"отстроить" : "build",
"отступать" : "step back, retreat fall back, recoil, fig. recede, deviate, indent, -ся renounce",
"отступить" : "step back, retreat fall back, recoil, fig. recede, deviate, indent, -ся renounce",
"отступление" : "retreat, deviation, digression",
"отступник" : "apostate",
"отступное" : "smart money",
"отсутствие" : "absence, lack, в отсутствии absent",
"отсутствовать" : "be absent, be lacking",
"отсутствующий" : "absent, absentee",
"отсчитать" : "count",
"отсчитывать" : "count",
"отсылать" : "send, refer",
"отсылка" : "dispatch, reference",
"отсыпать" : "pour",
"отсырелый" : "damp",
"отсыреть" : "dampen",
"отсыхать" : "wither",
"отсюда" : "from here, hence",
"оттава" : "ottawa",
"оттаивать" : "thaw",
"отталкивание" : "standoff",
"отталкивать" : "push off away aside, repel",
"отталкивающий" : "repellent",
"оттаскивать" : "pull off away aside",
"оттачивать" : "sharpen",
"оттащить" : "pull off away aside",
"оттаять" : "thaw",
"оттенить" : "shade, set off emphasize",
"оттенок" : "shade nuance tinge",
"оттенять" : "shade, set off emphasize",
"оттепель" : "thaw",
"оттеснить" : "push off aside, milit. drive back, famil. oust",
"оттеснять" : "push off aside, milit. drive back, famil. oust",
"оттиск" : "impression reprint",
"оттискивать" : "print",
"оттиснуть" : "print",
"оттого" : "therefore that's why",
"оттого что" : "because",
"оттолкнуть" : "push off away aside, repel",
"оттоманский" : "ottoman",
"оттопырить" : "pf. bulge protrude",
"отточить" : "sharpen",
"оттуда" : "from there",
"оттягивать" : "draw off, delay",
"оттянуть" : "draw off, delay",
"отупеть" : "grow blunt",
"отхлынуть" : "pf. rush away back",
"отход" : "departure, milit. withdrawal, deviation, rupture",
"отходить" : "go, leave, deviate, milit. withdraw, turn away, come off, thaw, recover, expire, impers. be relieved",
"отходы" : "waste",
"отцвести" : "fade wither",
"отцветать" : "fade wither",
"отцепить" : "unhook, uncouple, famil. remove",
"отцеплять" : "unhook, uncouple, famil. remove",
"отцовский" : "paternal, fatherly",
"отцовство" : "paternity",
"отчаиваться" : "despair  despond",
"отчаливать" : "unmoor, push off, sail away",
"отчалить" : "unmoor, push off, sail away",
"отчасти" : "partly in part",
"отчаяние" : "despair",
"отчаянный" : "desperate",
"отчаяться" : "despair  despond",
"отче наш" : "Our Father, Lord's Prayer",
"отчего" : "why",
"отчего-то" : "for some reason",
"отчеканивать" : "coin, say distinctly",
"отчеканить" : "coin, say distinctly",
"отчество" : "patronymic",
"отчет" : "account  report, return, realize; See also: давать себе отчет",
"отчетливый" : "distinct clear, precise",
"отчетность" : "accounting, pl.",
"отчетный" : "of account",
"отчизна" : "fatherland",
"отчий" : "paternal",
"отчим" : "stepfather",
"отчисление" : "deduction, subscription, dismissal",
"отчислить" : "deduct, allot, dismiss",
"отчислять" : "deduct, allot, dismiss",
"отчитать" : "blow up rebuke, -ся give #or render an account",
"отчитывать" : "blow up rebuke, -ся give #or render an account",
"отчуждать" : "alienate expropriate",
"отшатнуться" : "pf. start #or shrink back",
"отшвырнуть" : "pf. hurl",
"отшельник" : "hermit",
"отшибать" : "strike",
"отшибить" : "strike",
"отшлифовать" : "grind, polish",
"отштамповать" : "stamp",
"отщепенец" : "renegade",
"отъезд" : "departure",
"отъезжающий" : "goer",
"отъявленный" : "egregious",
"отыграть" : "win back regain",
"отыгрывать" : "win back regain",
"отыскать" : "find",
"отыскивать" : "find",
"отьезд" : "departure",
"отьезжать" : "drive  depart",
"отьехать" : "drive  depart",
"отьявленный" : "notorious arch",
"отяготить" : "burden",
"отягощать" : "burden",
"офицер" : "officer",
"офицерский" : "office",
"официальный" : "official",
"официант" : "waiter",
"официантка" : "waitress",
"официозный" : "semiofficial",
"оформить" : "form shape, get up, mount, legalize, adjust",
"оформлять" : "form shape, get up, mount, legalize, adjust",
"офтальмология" : "ophthalmology",
"оффис" : "office",
"ох" : "oh! ah!",
"оханье" : "groan",
"охапка" : "armful, fagot",
"охарактеризовать" : "characterize mark",
"охать" : "groan",
"охват" : "coverage, diapason",
"охватить" : "seize grasp, embrace, envelop",
"охватывать" : "seize grasp, embrace, envelop",
"охладевать" : "cool down",
"охладеть" : "cool down",
"охладить" : "cool",
"охлаждать" : "cool",
"охлаждение" : "cooling",
"охмелить" : "intoxicate",
"охмелять" : "intoxicate",
"охнуть" : "groan",
"охота" : "hunt, chase, famil. desire  mind, охота inf.! what do ... want  inf. for?",
"охотиться" : "hunt, chase",
"охотнее" : "rather; See also: охотнее всего",
"охотнее всего" : "best of all",
"охотник" : "hunter, volunteer, lover",
"охотничий" : "hunting shooting, hunter's",
"охотно" : "willingly gladly with pleasure",
"охрана" : "guard, protection",
"охранение" : "protection, milit. outpost",
"охранитель" : "conservator",
"охранить" : "guard protect",
"охраняемый законом" : "commerc. registered",
"охранять" : "guard protect",
"охриплый" : "hoarse",
"охрипнуть" : "become hoarse",
"охрипший" : "hoarse",
"оцарапать" : "scratch",
"оцелот" : "ocelot",
"оценивать" : "appraise, evaluate",
"оценка" : "appraisal, estimate, estimation, evaluation",
"оцепеневший" : "torpid",
"оцепенение" : "catalepsy, stupefaction",
"оцинковывать" : "zing",
"очаг" : "hearth",
"очарование" : "charm, enchantment, glamor, glamour",
"очарованный" : "fascinated, spellbound",
"очаровывать" : "captivate, enchant, enthral, fascinate, spellbind",
"очевидец" : "eyewitness",
"очевидный" : "evident",
"очень" : "very much",
"очередной" : "next, regular, foremost, latest",
"очередь" : "turn, order succession, line, milit. volley; See also: ваша очередь, очередь за вами, на очереди, в свою очередь",
"очередь за вами" : "it is your turn",
"очерк" : "sketch, outline, essay",
"очернять" : "s. чернить",
"очерствелый" : "hardened",
"очертание" : "outline contour",
"очертить" : "outline sketch",
"очертя голову" : "famil. headlong",
"очерчивать" : "outline sketch",
"очистительный" : "purgative, purgatorial",
"очистить" : "clean, clear, peel, purify, evacuate quit, empty",
"очистка" : "cleaning, clearance, pl. peelings",
"очищать" : "clean, clear, peel, purify, evacuate quit, empty",
"очищающий" : "detergent",
"очищение" : "purification, purifying, refinement",
"очки" : "spectacles glasses",
"очко" : "#sport: point, #cards: spot Brt. pip, engin. eye",
"очковтирательство" : "eyewash humbug",
"очная ставка" : "confrontation",
"очнуться" : "s. опомниться",
"очумелый" : "crazy mad",
"очутиться" : "get find o.s.",
"ошалелый" : "crazy mad",
"ошейник" : "collar",
"ошеломить" : "stun stupefy",
"ошеломленный" : "aghast, bemused, perplexed"
};
