var dicctr_28 = {
"избежание" : "во избежание",
"избивать" : "slay",
"избиратель" : "elector, voter",
"избирательное собрание" : "caucus Brt. electoral assembly",
"избирательный" : "electoral, election...",
"избирательный округ" : "constituency",
"избирательный участок" : "polling place",
"избирать" : "choose, elect",
"избитый" : "fig. beaten, hackneyed trite",
"избить" : "beat thrash, obsol. slaughter extirpate, famil. damage",
"избрание" : "election",
"избранник" : "the elect",
"избранный" : "a. select",
"избрать" : "choose, elect",
"избыток" : "superfluity surplus, abundance plenty, в избытке с избытком in plenty plentiful",
"избыточный" : "superfluous surplus...",
"изваяние" : "statue, s. ваять",
"изваять" : "form cut model",
"изведать" : "learn know see, experience",
"изведывать" : "learn know see, experience",
"изверг" : "monster",
"извергать" : "cast out, vomit, erupt",
"извергаться" : "erupt",
"извергнуть" : "cast out, vomit, erupt",
"извержение" : "ejection eruption",
"извернуться" : "s. изворачиваться",
"извести" : "s. изводить",
"известие" : "news sg., information, a. bulletin, последние известия rad. news",
"известить" : "s. извещать",
"известка" : "lime",
"известковый" : "lime",
"известность" : "notoriety, reputation fame, пользоваться известностью, be renowned #or famous #or well known, ставить в известность, bring to a pers.'s notice",
"известный" : "known  familiar, well-known renowned famous, notorious, certain, известное дело of course, известно it is known, это хорошоизвестно it is a well-known fact",
"известняк" : "limestone",
"известь" : "lime",
"извещать" : "inform, notify, a. advise",
"извещение" : "notification information notice, jur. summons writ",
"извиваться" : "wind twist wriggle meander",
"извилина" : "bend curve, turn",
"извилистый" : "winding tortuous",
"извинение" : "pardon, apology excuse",
"извинительный" : "pardonable, apologetic",
"извинить" : "excuse pardon, forgive, извини! excuse me! sorry!, нет извини! oh no! on no account!",
"извиниться" : "apologize, beg to be excused, извиняюсь! popul. = извини!",
"извинять" : "excuse pardon, forgive, извини! excuse me! sorry!, нет извини! oh no! on no account!",
"извиняться" : "apologize, beg to be excused, извиняюсь! popul. = извини!",
"извиняющийся" : "apologetic",
"извлекать" : "take #or draw out, extract, derive",
"извлечение" : "extract",
"извлечь" : "take #or draw out, extract, derive",
"извне" : "from outside #or without",
"изводить" : "use up, exhaust ruin",
"извозчик" : "cabman cab driver, cab",
"изволить" : "please deign, obsol. want, изволь  vb., a. #order #admonition: please, #discontent: how can one ..., famil. изволь all right O.K., please, cf. угодно",
"изворачиваться" : "famil. dodge, shift, wriggle out",
"изворотливый" : "nimble, elusive, shifty",
"извратить" : "distort, pervert",
"извращать" : "distort, pervert",
"извращение" : "inversion, perversion",
"извращенный" : "perverted",
"изгиб" : "bend curve turn, fig. shade",
"изгибать" : "bend curve crook",
"изгладить" : "efface erase, smooth out",
"изглаживать" : "efface erase, smooth out",
"изгнание" : "expulsion banishment, exile",
"изгнанник" : "exile",
"изгнать" : "s. изгонять",
"изголовье" : "head, bolster",
"изгонять" : "drive out, oust, expel, exile banish",
"изгородь" : "fence, hedge",
"изготавливать" : "make produce manufacture, famil. prepare",
"изготовить" : "make produce manufacture, famil. prepare",
"изготовление" : "production manufacture, making",
"изготовлять" : "make produce manufacture, famil. prepare",
"издавать" : "publish, edit, issue, enact, utter emit",
"издавна" : "at all tames, from of old, long since",
"издалека" : "from afar, afar off",
"издали" : "from afar, afar off",
"издание" : "publication, edition, issue",
"издатель" : "publisher, editor",
"издательство" : "publishing house publishers pl.",
"издать" : "publish, edit, issue, enact, utter emit",
"издевательство" : "derision  scorn scoff",
"издеваться" : "jeer sneer mock, bully",
"изделие" : "make, product article, work, a. goods",
"изделия" : "ware, wares",
"издержать" : "spend, use up, -ся famil. spend much money",
"издерживать" : "spend, use up, -ся famil. spend much money",
"издержки" : "expenses, jur. costs",
"издохнуть" : "die, popul. croak kick off",
"издыхание" : "breath #or gasp",
"издыхать" : "s. дохнуть",
"изжарить" : "roast, fry, famil. burn",
"изживать" : "eliminate extirpate, complete end, endure",
"изжить" : "eliminate extirpate, complete end, endure",
"изжить себя" : "be outdated have had one's day",
"изжога" : "heartburn",
"излагать" : "state set forth expound expose",
"излечение" : "cure treatment, recovery",
"излечивать" : "cure",
"излечимый" : "curable",
"излечить" : "cure",
"изливать" : "shed",
"излить" : "shed",
"излить душу" : "unbosom o.s., #anger: vent ... on",
"излишек" : "surplus excess & = избыток",
"излишество" : "superfluity, surfeit",
"излишний" : "superfluous excessive, needless",
"излияние" : "outpouring effusion",
"изловчиться" : "pf. contrive",
"изложение" : "exposition statement",
"изложить" : "state set forth expound expose",
"изломанный" : "broken, angular, spoilt deformed unnatural",
"излучать" : "radiate",
"излучающий" : "radiate",
"излучение" : "emission, radiating",
"излучина" : "s. изгиб",
"излучить" : "radiate",
"излюбленный" : "favorite",
"измельчать" : "become small #or shallow",
"измена" : "treason, unfaithfulness",
"изменение" : "change alteration modification, впредь до изменения until further notice",
"изменить" : "s. изменять",
"изменник" : "traitor",
"изменнический" : "treasonable, treasonous",
"изменчивый" : "changeable variable, fickle",
"изменять" : "change  alter, modify, vary, betray, be unfaithful, break violate, fail  desert",
"измерение" : "measurement, math. dimension",
"измеримый" : "measurable",
"измеритель" : "meter measure measuring instrument",
"измерительный" : "metering, metrical",
"измерить" : "measure, fathom",
"измерять" : "measure, fathom",
"изможденный" : "exhausted",
"измор" : "взять измором",
"измученный" : "chivied, exhausted",
"изнашивание" : "frazzle, wastage, wear and tear",
"изнеможение" : "exhaustion weariness",
"изнеможенный" : "prostrate",
"изнемочь" : "be exhausted #or enervated, collapse",
"износ" : "wear and tear",
"износить" : "wear out, -ся",
"изнурение" : "exhaustion fatigue",
"изнурительный" : "wearisome wasting",
"изнурить" : "fatigue exhaust waste",
"изнурять" : "fatigue exhaust waste",
"изнутри" : "from within, within",
"изнывать" : "pine, a. die of be wearied #or bored to death",
"изныть" : "pine, a. die of be wearied #or bored to death",
"изо всей мочи" : "with all one's might",
"изо всех сил" : "famil. with all one's might",
"изо дня в день" : "day by day",
"изобилие" : "abundance plenty",
"изобиловать" : "abound",
"изобилующий" : "flush, full of",
"изобильный" : "rich abundant",
"изобличать" : "convict, unmask, impf. reveal show",
"изобличить" : "convict, unmask, impf. reveal show",
"изображать" : "represent  depict, describe, express; See also: изображать из себя",
"изображать из себя" : "famil. act set up for",
"изображение" : "representation, description, image picture",
"изобразительный" : "graphic descriptive, fine",
"изобразить" : "represent  depict, describe, express; See also: изображать из себя",
"изобрести" : "s. изобретать",
"изобретатель" : "inventor",
"изобретательность" : "ingenuity",
"изобретательный" : "inventive resourceful",
"изобретать" : "invent",
"изобретение" : "invention",
"изогнутый" : "arched, bent, cambered, curved",
"изогнуть" : "bend curve crook",
"изодранный" : "famil. = изорванный",
"изолировать" : "pf. isolate, a. insulate",
"изолятор" : "el. insulator, med. isolation ward, cell #or jail",
"изоляция" : "isolation, el. insulation",
"изорванный" : "torn tattered",
"изотоп" : "isobar, isotope",
"изотропный" : "isotropic",
"изохронный" : "isochronal, isochronous",
"изощренный" : "refined subtle",
"изощрить" : "refine sharpen, impf. o.s. excel",
"изощрять" : "refine sharpen, impf. o.s. excel",
"изразец" : "tile",
"израиль" : "Israel",
"израильский" : "israeli, israelite",
"израсходовать" : "spend expend, a. use up",
"изредка" : "occasionally, here & there",
"изрезать" : "cut up",
"изрезывать" : "cut up",
"изрекать" : "pronounce",
"изречение" : "aphorism maxim",
"изречь" : "pronounce",
"изрубать" : "chop mince, cut, saber",
"изрубить" : "chop mince, cut, saber",
"изрядный" : "good #or big fair",
"изувер" : "fanatic, monster",
"изувечивать" : "mutilate",
"изувечить" : "mutilate",
"изумительный" : "amazing wonderful",
"изумить" : "s. изумлять",
"изумлять" : "amaze, astonish, flabbergast, stupefy",
"изумруд" : "emerald",
"изучение" : "scrutiny",
"изъян" : "defect",
"изымать" : "eliminate",
"изыскание" : "prospect",
"изысканная" : "ladylike",
"изысканный" : "dainty, exquisite, recherche",
"изыскатель" : "prospector",
"изыскивать" : "find",
"изьездить" : "pf. travel over through",
"изьезженный" : "beaten, bumpy",
"изьявительный" : "gr. indicative",
"изьявить" : "express show, give",
"изьявлять" : "express show, give",
"изьян" : "defect, stain, loss",
"изьять" : "withdraw, seize",
"изюм" : "pl.",
"изящество" : "delicacy, elegance",
"изящная литература" : "belles-lettres pl.",
"изящное" : "su. the beautiful",
"изящный" : "graceful elegant fine; See also: изящное, изящная литература",
"иисус" : "Jesus",
"икать" : "hiccup",
"икнуть" : "hiccup",
"икона" : "icon",
"иконоборство" : "iconoclast",
"икота" : "hiccup",
"икра" : "roe spawn, caviar, pl. calf",
"ил" : "silt",
"или" : "or, or else; See also: или ... или",
"или  или" : "either ... or",
"илистый" : "slimy",
"иллюзорный" : "illusory",
"иллюминатор" : "airport, bull,s eye",
"иллюстрированный" : "illustrated, pictorial",
"иллюстрировать" : "illustrate",
"им" : "them",
"иметь" : "have",
"иметь в виду" : "have in view mean intend, remember bear in mind",
"иметь вкус" : "taste",
"иметь дело с" : "have to do with",
"иметь зуб" : "have a grudge against",
"иметь место" : "take place",
"иметь против" : "object mind",
"иметься" : "be at in #or on hand, have, there is are etc",
"имитирование" : "mimesis, mimicry",
"иммигрант" : "immigrant",
"иммигрировать" : "immigrate",
"иммунитет" : "immunity"
};
