var dicctr_44 = {
"наобум" : "famil. at random haphazardly",
"наотрез" : "bluntly categorically",
"нападать" : "attack fall on, come across #or upon, hit on, overcome",
"нападающий" : "assailant, forward",
"нападение" : "attack, aggression, forwards pl.",
"нападки" : "accusations cavils, carping faultfinding sg",
"напаивать" : "give to drink, make drunk, imbue",
"напасть" : "attack fall on, come across #or upon, hit on, overcome",
"напев" : "melody tune",
"напевать" : "hum sing, напеть record",
"наперебой" : "famil. vying with each other",
"наперевес" : "atilt",
"наперегонки" : "бежать наперегонки",
"наперед" : "s. вперед",
"напереди" : "s. спереди",
"наперекор" : "in spite #or defiance  contrary",
"наперерез" : "short cut cutting",
"наперерыв" : "famil. = наперебой",
"наперечет" : "each and all, few",
"наперсник" : "favorite, pet",
"наперсница" : "confidante",
"наперсток" : "thimble",
"наперстянка" : "digitalis, foxglove",
"наперченный" : "peppery",
"напечатать" : "print, type",
"напиваться" : "drink quench one's thirst have enough, get drunk",
"напильник" : "file",
"написанный" : "written",
"написать" : "write, type, paint",
"напитать" : "saturate soak imbue",
"напиток" : "drink beverage",
"напитывать" : "saturate soak imbue",
"напиться" : "drink quench one's thirst have enough, get drunk",
"напихать" : "cram",
"напихивать" : "cram",
"напичкать" : "stuff",
"наплыв" : "rush, deposit, excrescence",
"наплывать" : "swim  run, flow, deposit, approach cover, waft reach, gather",
"наплывной" : "s. наносный",
"наплыть" : "swim  run, flow, deposit, approach cover, waft reach, gather",
"наповал" : "outright",
"наподобие" : "like resembling",
"напоить" : "give to drink, make drunk, imbue",
"напоказ" : "for show, cf. выставлять",
"наполеоновский" : "napoleonic",
"наполненный" : "replete",
"наполнить" : "fill, crowd, imbue, a. full",
"наполнять" : "fill, crowd, imbue, a. full",
"наполовину" : "half, by halves",
"напоминание" : "reminder, dun",
"напоминать" : "remind  dun",
"напоминающий" : "reminiscent",
"напомнить" : "remind  dun",
"напор" : "pressure, charge, famil. rush push vigor",
"напоследок" : "famil. ultimately",
"напр" : "abbr.: например",
"направление" : "directing, direction",
"направленный" : "directional",
"напрасный" : "vain",
"например" : "for example #or instance",
"напрокат" : "for hire",
"напролет" : "famil. ... through[out], on end",
"напролом" : "идти напролом",
"напроситься" : "offer  solicit, provoke, fish, suggest o.s.",
"напротив" : "opposite, on the contrary, a. наперекор & наоборот",
"напрягать" : "strain, exert, stretch, bend",
"напряжение" : "tension  strain exertion, effort, close attention",
"напряженный" : "strained, tense, keen close",
"напрямик" : "famil. straight on, outright",
"напрячь" : "strain, exert, stretch, bend",
"напуганный" : "scared frightened",
"напугать" : "frighten scare",
"напудрить" : "powder",
"напускать" : "let in fill, set at, fall, famil. put on, popul. cause, -ся famil. fall on",
"напускной" : "affected",
"напустить" : "let in fill, set at, fall, famil. put on, popul. cause, -ся famil. fall on",
"напутственный" : "farewell... parting",
"напутствие" : "parting words",
"напыщенность" : "bombast, flatulence",
"напыщенный" : "pompous",
"наравне" : "on a level with, equally, together with",
"нараспашку" : "famil. unbuttoned, ~ frank candid, in grand style",
"нараспев" : "with a singing accent",
"нарастать" : "grow, accrue",
"нарасти" : "grow, accrue",
"нарасхват" : "famil. greedily, like hot cakes",
"нард" : "nard, spikenard",
"нарезать" : "cut, carve, engin. thread",
"нарезка" : "engin. thread",
"нарезывать" : "= нарезать",
"нарекание" : "blame censure",
"наречие" : "dialect, gr. adverb",
"наречный" : "adverbial",
"нарисовать" : "draw, design",
"нарицательный" : "gr. common, commerc. nominal",
"наркоз" : "narcosis",
"наркоман" : "addict, junkie, junky",
"наркотический" : "narcotic",
"народ" : "people nation",
"народиться" : "arise spring up, famil. be born, grow",
"народник" : "populist",
"народность" : "nationality",
"народный" : "people's popular folk..., national, public",
"народонаселение" : "population",
"нарождаться" : "arise spring up, famil. be born, grow",
"нарост" : "growth",
"нарочитый" : "deliberate intentional, a. on purpose, specially expressly, famil. in fun, a. = назло",
"нарочный" : "courier",
"нарты" : "sledge",
"наружность" : "appearance, exterior",
"наружный" : "external outward, outdoor outside наружу out outward abroad fig",
"наружу" : "forth, outwards",
"наручник" : "handcuff",
"наручный" : "wrist",
"нарушать" : "disturb, infringe violate, break",
"нарушение" : "violation transgression breach, disturbance",
"нарушитель" : "trespasser, disturber",
"нарушить" : "disturb, infringe violate, break",
"нарцисс" : "narcissus",
"нары" : "plank bed",
"нарыв" : "abcess, cf. гноить",
"наряд" : "attire dress, assignment commission order, milit. fatigue, detachment",
"нарядить" : "s. наряжать",
"нарядный" : "smart trim elegant, order...",
"наряду" : "together #or along with beside, side by side, a. наравне",
"наряжать" : "dress, disguise, milit. detach, assign, obsol. set up",
"нас было двое" : "we were two",
"насадить" : "plant, a. насаживать",
"насажать" : "plant, famil. set put place",
"насаждать" : "plant, a. насаживать",
"насаждение" : "planting, plantation, trees plants pl.",
"насаживать" : "plant, famil. set put place",
"насвистывать" : "whistle",
"наседать" : "set, sit down, cover, press",
"наседка" : "brood hen",
"насекомое" : "insect",
"население" : "population",
"населить" : "people populate, impf. inhabit live in",
"населять" : "people populate, impf. inhabit live in",
"насест" : "roost",
"насесть" : "set, sit down, cover, press",
"насечка" : "notch cut",
"насидеть" : "brood hatch",
"насиженный" : "a. snug habitual long-inhabited",
"насиживать" : "brood hatch",
"насилие" : "violence force coercion, rape",
"насиловать" : "violate force, rape",
"насилу" : "s. еле",
"насильно" : "by force, forcedly",
"насильственный" : "forcible forced, violent",
"наскакивать" : ", fall on, run #or strike against come across",
"наскандалить" : "row",
"насквозь" : "through, famil. through and through",
"насколько" : "as, how",
"наскоро" : "famil. hastily in a hurry",
"наскочить" : ", fall on, run #or strike against come across",
"наскучить" : "s. надоедать",
"насладиться" : "enjoy  delight",
"наслаждаться" : "enjoy  delight",
"наслаждение" : "enjoyment, delight, pleasure",
"наслаиваться" : "stratify",
"наследие" : "heritage legacy, a. наследство",
"наследник" : "heir",
"наследница" : "heiress",
"наследный" : "crown..., a. наследственный",
"наследовать" : "inherit, succeed",
"наследственность" : "heredity",
"наследственный" : "hereditary inherited",
"наследство" : "inheritance, a. наследие, vb.  в наследство, inherit",
"наслоение" : "stratification",
"наслушаться" : "pf. listen to one's heart's content, наслышаться; See also: не мочь наслушаться",
"наслышаться" : "hear a lot  much, cf. понаслышке",
"насмерть" : "to death, mortal",
"насмехаться" : "mock jeer, sneer",
"насмешка" : "mockery sneer",
"насмешливый" : "mocking",
"насмешник" : "scoffer mocker",
"насмешница" : "scoffer mocker",
"насморк" : "cold",
"насмотреться" : "cf.",
"насорить" : "litter, make dirty",
"насос" : "pump",
"наспех" : "hurriedly in a hurry",
"насплетничать" : "gossip",
"наставать" : "come",
"наставительный" : "instructive, preceptive",
"наставить" : "s. наставлять",
"наставление" : "instruction, admonition, lecture lesson fig.",
"наставлять" : "put place set, piece  add, aim level, instruct, teach",
"наставник" : "tutor mentor preceptor",
"наставнический" : "tutorial",
"настаивать" : "insist, draw extract; See also: настоять на своем",
"настать" : "come",
"настежь" : "wide",
"настигать" : "overtake, find catch",
"настигнуть" : "overtake, find catch",
"настил" : "decking",
"настилать" : "lay spread, plank pave",
"настичь" : "overtake, find catch",
"настлать" : "lay spread, plank pave",
"настой" : "infusion extract",
"настойка" : "liqueur, a. = настой",
"настойчивость" : "perseverance",
"настойчивый" : "persevering pertinacious, persistent, obstinate",
"настолько" : "so",
"настольный" : "table..., reference...",
"настораживаться" : "prick up one's ears",
"настороже" : "on the alert on one's guard",
"настороженный" : "wary",
"насторожиться" : "prick up one's ears",
"настояние" : "insistence urgent request",
"настоятельный" : "urgent pressing instant",
"настоять" : "insist, draw extract; See also: настоять на своем",
"настоять на своем" : "have one's will",
"настоящий" : "present, true real genuine; See also: по-настоящему",
"настраивать" : "build, tune, set against, a. налаживать",
"настрого" : "famil. most strictly",
"настроение" : "mood spirits pl. frame, disposition",
"настроить" : "build, tune, set against, a. налаживать",
"настройка" : "superstructure, tuning",
"наступательный" : "offensive",
"наступать" : "tread #or step, come set in, impf. attack advance, press, approach",
"наступить" : "tread #or step, come set in, impf. attack advance, press, approach",
"наступление" : "offensive attack advance, beginning ...break ...fall",
"настурция" : "nasturtium",
"насупить" : "pf. frown",
"насухо" : "adv. dry",
"насущный" : "vital, daily",
"насчет" : "famil. concerning about",
"насчитать" : "count number",
"насчитывать" : "count number",
"насчитываться" : "impf. there is/are",
"насыпать" : "pour, strew scatter, fill, throw up raise",
"насыпь" : "embankment mound",
"насытить" : "satisfy, saturate",
"насыщать" : "satisfy, saturate",
"насыщение" : "saturation",
"наталкивать" : "push, famil. prompt suggest, -ся strike against, come across",
"натворить" : "pf. do cause",
"нательный" : "under",
"натереть" : "rub, get, wax polish",
"натирать" : "rub, get, wax polish",
"натиск" : "press rush, onslaught charge, urge",
"наткнуться" : "s. натыкаться",
"натолкнуть" : "push, famil. prompt suggest, -ся strike against, come across",
"натощак" : "on an empty stomach",
"натравить" : "set  incite",
"натравливать" : "set  incite",
"натренировать" : "train coach, -ся",
"натрий" : "natrium"
};
