var dicctr_7 = {
"варенька" : "dim. #of Варвара",
"вариант" : "variant version",
"варить" : "cook boil, brew, digest",
"варка" : "cooking boiling",
"варшава" : "Warsaw",
"варьете" : "vaudeville Brt. variety",
"варьировать" : "vary",
"варя" : "dim. #of Варвара",
"варяг" : "Varangian",
"василек" : "cornflower",
"василий" : "Basil",
"вассал" : "vassal",
"вассальный" : "feudatory, vassal",
"вася" : "dim. #of Василий",
"вата" : "absorbent cotton Brt. cotton wool, wadding, на вате wadded",
"ватага" : "gang band troop",
"ватерлиния" : "water line",
"ватерпас" : "level",
"ватикан" : "vatican",
"ватный" : "cotton..., wadded",
"ватрушка" : "curd #or jam patty",
"ватт" : "watt",
"вафля" : "waffle wafer",
"вахта" : "watch, стоять на вахте keep watch",
"вахтенный" : "sailor on duty",
"вахтер" : "guard watchman",
"ваш" : "your, yours, по-вашему in your opinion, по-вашему, your own way as you like, как по-вашему? what do you think?, cf. наш",
"ваш брат" : "famil. of your kind",
"ваша" : "your, yours, по-вашему in your opinion, по-вашему, your own way as you like, как по-вашему? what do you think?, cf. наш",
"ваша очередь" : "it is your turn",
"ваше" : "your, yours, по-вашему in your opinion, по-вашему, your own way as you like, как по-вашему? what do you think?, cf. наш",
"ваши" : "your, yours, по-вашему in your opinion, по-вашему, your own way as you like, как по-вашему? what do you think?, cf. наш",
"вашингтон" : "Washington",
"ваяние" : "sculpture",
"ваятель" : "sculptor",
"ваять" : "form cut model",
"вбегать" : "run #or rush in",
"вбежать" : "run #or rush in",
"вбивать" : "drive in",
"вбирать" : "absorb imbibe",
"вбить" : "drive in",
"вбить себе в голову" : "take it into one's head",
"вблизи" : "nearby, close",
"вброд" : "переходить вброд",
"введение" : "introduction",
"ввертывать" : "screw in, fig. put in",
"вверх" : "up; See also: вверх по лестнице, вверх дном, вверх ногами, вверх тормашками, руки вверх{!}",
"вверх дном" : "upside down",
"вверх ногами" : "upside down",
"вверх по лестнице" : "upstairs",
"вверх тормашками" : "famil. headlong",
"вверху" : "above, overhead",
"вверять" : "entrust commit give in charge",
"ввести" : "s. вводить",
"ввиду" : "in view  considering; See also: ввиду того что",
"ввиду того, что" : "as since seeing that",
"ввинтить" : "screw in",
"ввинчивать" : "screw in",
"ввод" : "input, leadin",
"вводить" : "introduce, bring #or usher, вводить в курс дела acquaint with an affair, вводить в строй, engin. put into operation",
"вводный" : "introductory, вводное слово #or предложение gr. parenthesis",
"ввоз" : "import, importation",
"ввозить" : "import",
"ввозный" : "import...",
"вволю" : "famil. plenty of, to one's heart's content",
"ввязаться" : "meddle interfere, get involved",
"ввязываться" : "meddle interfere, get involved",
"вгибать" : "inflect",
"вглубь" : "inward deep",
"вглядеться" : "peer  look narrowly",
"вглядываться" : "peer  look narrowly",
"вгонять" : "drive in",
"вдаваться" : "jut out, press in, indulge  plunge #or go",
"вдавить" : "press in",
"вдавливать" : "press in",
"вдалеке" : "far off far",
"вдали" : "far off far",
"вдаль" : "into the distance",
"вдаться" : "jut out, press in, indulge  plunge #or go",
"вдвигать" : "put #or push in",
"вдвинуть" : "put #or push in",
"вдвое" : "twice, a. double",
"вдвоем" : "both #or two",
"вдвойне" : "twice  doubly",
"вдевать" : "thread",
"вделать" : "set",
"вделывать" : "set",
"вдеть" : "thread",
"вдобавок" : "in addition, into the bargain to boot",
"вдова" : "widow",
"вдовец" : "widower",
"вдоволь" : "famil. quite enough, plenty of",
"вдовство" : "widowhood",
"вдовый" : "widowed",
"вдогонку" : "after in pursuit of",
"вдоль" : "along, lengthwise; See also: вдоль и поперек",
"вдоль и поперек" : "throughout far and wide",
"вдохновение" : "inspiration",
"вдохновенный" : "inspired",
"вдохновить" : "inspire",
"вдохновиться" : "get inspired",
"вдохновлять" : "inspire",
"вдохновляться" : "get inspired",
"вдохнуть" : "inhale, fig. inspire",
"вдребезги" : "into smithereens",
"вдруг" : "suddenly all of a sudden",
"вдувать" : "blow in",
"вдуматься" : "ponder  reflect  dive",
"вдумчивый" : "thoughtful",
"вдумываться" : "ponder  reflect  dive",
"вдуть" : "blow in",
"вдыхание" : "inhalation",
"вдыхать" : "inhale, fig. inspire",
"вегетарианец" : "vegetarian",
"вегетарианский" : "vegan, vegetarian",
"вегетативный" : "vegetative",
"ведать" : "obsol. know, be in charge of manage",
"ведение" : "running directing",
"ведение книг" : "bookkeeping",
"ведомо" : "known, без моего ведома without my knowledge",
"ведомость" : "list roll, bulletin",
"ведомство" : "department administration",
"ведомый" : "driven",
"ведро" : "bucket pail; See also: ведро для мусора",
"ведро для мусора" : "garbage can Brt. dust-bin",
"ведущий" : "leading, basic",
"ведь" : "indeed sure, why well, then, you know!, ~ уже поздно it is late isn't it?",
"ведьма" : "witch hag",
"веер" : "fan",
"вежливость" : "politeness",
"вежливый" : "polite",
"везде" : "everywhere",
"вездесущий" : "omnipresent, ubiquitous",
"вездесущность" : "ubiquity",
"везти" : "drive  transport, pull, ему везет famil. he is lucky",
"век" : "century, age, life, средние века pl. Middle Ages, на моем веку in my life, ~ с тобой мы не видались we haven't met for ages",
"веко" : "eyelid",
"вековой" : "secular",
"вексель" : "bill of exchange promissory note",
"вектор" : "vector",
"велеть" : "pf., pf. #only order tell",
"великан" : "giant",
"великан-людоед" : "ogre",
"великанша" : "giantess",
"великанша-людоедка" : "ogress",
"великая пятница" : "Good Friday, Петр Великий Peter the Great",
"великий" : "great, large #or big, от мала до велика everybody young and old",
"великий пост" : "Lent",
"великобритания" : "Great Britain",
"великодушие" : "magnanimity",
"великодушный" : "magnanimous generous",
"великолепие" : "splendor magnificence",
"великолепный" : "magnificent splendid",
"великорус" : "Russian",
"великорусский" : "Russian",
"величавый" : "sublime majestic lofty",
"величать" : "praise glorify, style",
"величественный" : "majestic grand stately",
"величество" : "Majesty",
"величие" : "grandeur",
"величина" : "size, quantity, celebrity",
"величиной" : "в #or с ... big #or high",
"велогонки" : "cycle race",
"велодром" : "cycling ground",
"велосипед" : "bicycle, ездить на велосипеде cycle",
"велосипедист" : "cyclist",
"велосипедный" : "cycle... cycling...",
"вельд" : "veld, veldt",
"вельможа" : "magnate",
"велюровый" : "velours",
"велярный" : "velar",
"вена" : "anat. vein, Вена Vienna",
"венгерец" : "Hungarian",
"венгерка" : "Hungarian",
"венгерский" : "Hungarian",
"венгрия" : "Hungary",
"вендетта" : "vendetta",
"венера" : "venus",
"венерический" : "venereal",
"венесуэла" : "Venezuela",
"венец" : "wreath garland, crown, halo; See also: идти под венец",
"венецианский" : "Venetian",
"венеция" : "Venice",
"вензель" : "monogram",
"веник" : "broom besom",
"веничек" : "whisk",
"венозный" : "venous",
"венок" : "wreath garland",
"венский" : "viennese",
"вентилировать" : "ventilate air",
"вентилятор" : "ventilator fan",
"венчальный" : "wedding...",
"венчание" : "wedding",
"венчать" : "увенчать wreathe crown, обвенчать повенчать marry, -ся get married",
"венчаться" : "wed",
"вера" : "faith belief trust, religion, Вера Vera",
"веранда" : "veranda",
"верба" : "willow",
"вербейник" : "loosestrife",
"верблюд" : "camel",
"верблюжья шерсть" : "camel's hair",
"вербный" : "вербное воскресенье Palm Sunday",
"вердикт" : "verdict",
"веревка" : "cord, rope, string",
"веревки" : "cordage",
"вереск" : "heath, heather",
"веретено" : "spindle",
"верещать" : "chirp",
"верзила" : "big fellow spindlelegs",
"верить" : "believe, believe trust; See also: поверить на слово",
"вериться" : "не верится, one can hardly believe",
"вермишель" : "coll. vermicelli",
"вермут" : "vermouth",
"вернее" : "or rather",
"верно" : "adv., s. верный 1) & 2), probably",
"верность" : "faith fidelity loyalty, correctness accuracy",
"вернуть" : "s. возвращать",
"верный" : "anchored, faithful, loyal, trusty",
"вероисповедание" : "communion",
"вероника" : "speedwell",
"веронский" : "veronese",
"вероятие" : "likelihood",
"вероятность" : "probability, по всей вероятности in all probability",
"вероятный" : "probable likely",
"версия" : "version",
"верста" : "verst",
"верстак" : "workbench",
"верстать" : "typ. make up",
"вертел" : "spit",
"вертеть" : "turn, twist",
"вертеться" : "turn revolve, fidget, loaf, make subterfuges; See also: вертеться на языке",
"вертеться вокруг да около" : "famil. beat about the bush",
"вертеться на языке" : "be on the tip of one's tongue",
"вертикальный" : "vertical",
"вертлявый" : "fidgety restless",
"вертолет" : "helicopter",
"вертун" : "fidget",
"вертушка" : "light-minded woman",
"верующий" : "pious, believer",
"верфь" : "dockyard",
"верх" : "top upper part, right side, fig., summit apex pink, upper hand",
"верхи" : "heads leaders, ... в верхах summit ..., mus. high notes, surface, superficial knowledge",
"верхний" : "upper",
"верховая езда" : "riding",
"верховная власть" : "supreme power",
"верховный" : "supreme high",
"верховный главнокомандующий" : "Commander in Chief, Supreme Commander",
"верховный совет" : "Supreme Soviet",
"верховный суд" : "supreme court",
"верховой" : "riding..., rider horseman"
};
