var dicctr_17 = {
"гражданский" : "civil, civic",
"гражданство" : "citizenship, citizens pl., дать право гражданства, accept, принять ... гражданство become a ... citizen",
"грамзапись" : "recording",
"грамм" : "gram",
"грамматика" : "grammar",
"грамматист" : "grammarian",
"грамматический" : "grammatical",
"граммофон" : "gramophone",
"грамота" : "reading & writing, document, patent, diploma, obsol. letter, верительная грамота credentials, это для меня китайская грамота famil. it's Greek to me",
"грамотность" : "literacy",
"грамотный" : "literate, trained expert",
"гранат" : "pomegranate, min. garnet",
"граната" : "shell, grenade",
"грандиозный" : "mighty, grand",
"граненый" : "faceted, cut",
"гранильный" : "lapidary",
"гранит" : "granite",
"граница" : "border frontier, boundary, fig. limit verge, за границу #go abroad, из-за границы from abroad",
"границы" : "ambit, confines",
"граничить" : "border #or verge",
"гранка" : "typ. galley",
"грань" : "s. граница, math. plane, facet, edge, fig. verge",
"граф" : "earl, count",
"графа" : "column",
"график" : "diagram graph",
"графика" : "graphic arts",
"графин" : "decanter carafe",
"графиня" : "countess",
"графит" : "graphite",
"графить" : "line #or rule  draw columns",
"графический" : "graphic",
"графство" : "county, earldom, shire",
"грациозный" : "graceful",
"грация" : "grace",
"грач" : "rook",
"гребенка" : "comb, стричь под гребенку crop",
"гребень" : "comb, crest",
"гребец" : "oarsman",
"гребешок" : "s. гребень",
"гребля" : "rowing",
"гребной" : "row...",
"греза" : "dream",
"грезить" : "impf. dream, med. rave",
"грезиться" : "мне грезится I dream",
"грезы" : "daydream",
"грейпфрут" : "grapefruit",
"грелка" : "damsel, warmer",
"гренландия" : "greenland",
"греться" : "bask",
"грех" : "sin",
"греция" : "greece",
"греческий" : "Greek",
"гречиха" : "buckwheat",
"гречка" : "buckwheat",
"гречневый" : "buckwheat...",
"грешить" : "sin",
"грешник" : "sinner",
"грешница" : "sinner",
"грешно" : "shame",
"грешный" : "sinful, sh.: sorry",
"гриб" : "mushroom",
"грибок" : "dim. ofгриб, fungus",
"грива" : "mane",
"гривенник" : "ten-kopeck coin",
"григорий" : "Gregory",
"грим" : "thea. make-up",
"гримаса" : "grimace",
"гримасничать" : "make faces #or grimaces",
"гримасы" : "antic",
"гримировать" : "make up",
"гринвич" : "greenwich",
"грипп" : "influenza",
"гриф" : "fingerboard, vulture",
"грифель" : "slate pencil",
"грифельная доска" : "slate",
"гриша" : "dim. #of Григорий",
"гроб" : "casket, coffin",
"гробница" : "cist, sepulchre, shrine",
"гробовщик" : "mortician",
"гроза" : "thunderstorm",
"грозить" : "threaten",
"грозный" : "fearsome, formidable, redoubtable",
"грозовой" : "thunderous",
"гром" : "thunder",
"громадный" : "enormous, mammoth, monster, swingeing, thumping",
"громила" : "hoodlum",
"громкий" : "loud",
"громко" : "aloud",
"громкоговоритель" : "loudspeaker, megaphone",
"громкоголосный" : "vociferous",
"громогласный" : "roaring, adv. in public",
"громоздить" : "cf. взгромождать",
"громоздкий" : "unwieldy",
"грохот" : "niagara, rumble",
"грош" : "mite",
"грубая" : "gunny",
"грубиян" : "chuff, churl, curmudgeon, tike, twerp",
"грубо" : "roughly",
"грубоватый" : "gruff",
"грубость" : "asperity",
"грубый" : "coarse, rough, rude, gross",
"груда" : "pile heap mass",
"грудина" : "breastbone, sternum",
"грудинка" : "brisket, bacon",
"грудинный" : "sternal",
"грудная клетка" : "thorax chest",
"грудной" : "pectoral, sucking, thoracic",
"грудной ребенок" : "suckling",
"грудь" : "breast, bosom, стоять грудью defend bravely",
"груз" : "load freight, nav. cargo",
"груз большой скорости" : "express freight",
"груз малой скорости" : "ordinary freight",
"грузило" : "plumb, plummet",
"грузин" : "Georgian",
"грузинка" : "Georgian",
"грузинский" : "Georgian",
"грузить" : "load embark",
"грузия" : "Georgia",
"грузный" : "massive heavy",
"грузовик" : "truck Brt. lorry",
"грузовой" : "freight... goods... nav. cargo...; See also: грузовой автомобиль",
"грузовой автомобиль" : "= грузовик",
"грузоподьемность" : "carrying capacity nav. tonnage",
"грузополучатель" : "consignee",
"грузчик" : "loader nav. stevedore",
"грунт" : "soil, ground",
"грунтовой" : "ground..., unpaved",
"группа" : "group",
"группировать" : "group",
"грустный" : "melancholy, wailful",
"груша" : "pear",
"грызть" : "gnaw",
"грызун" : "rodent",
"грязевой" : "mud...",
"грязезащитное крыло" : "fender mudguard",
"грязелечебница" : "mud bath",
"грязи" : "mud",
"грязнить" : "soil, -ся get dirty",
"грязнуть" : "sink",
"грязный" : "dirty, muddy, slop...",
"грязь" : "dirt, mud; See also: в грязи, не ударить лицом в грязь",
"грянуть" : "pf. crash thunder sound ring roar, break out burst start",
"гуано" : "guano",
"губа" : "lip, bay, gulf; See also: губа не дура",
"губа не дура" : "taste isn't bad",
"губернатор" : "governor",
"губернаторский" : "gubernatorial",
"губерния" : "government province",
"губительный" : "pernicious",
"губить" : "destroy ruin, waste",
"губка" : "dim. #of a губа, sponge",
"губная гармоника" : "mouth organ harmonica",
"губная помада" : "lipstick",
"губной" : "labial",
"губчатый" : "fungous, sponge",
"гувернантка" : "governess",
"гувернер" : "tutor",
"гудение" : "ping",
"гудеть" : "buzz, honk, hoot whistle",
"гудзон" : "hudson",
"гудок" : "honk hoot signal, horn, siren whistle",
"гул" : "boom rumble, hum",
"гулкий" : "booming loud, resonant",
"гуляка" : "hellbender, roisterer",
"гулянье" : "walk, revel open-air merrymaking festival",
"гулять" : "go for a walk  stroll, fig. sweep, make merry",
"гум" : ", state department store",
"гуманистический" : "humanitarian",
"гуманность" : "humanity humaneness",
"гуманный" : "humane",
"гумно" : "farm. floor",
"гурман" : "gourmet",
"гурт" : "drove",
"гуртом" : "famil. wholesale",
"гурьба" : "crowd",
"гусеница" : "caterpillar",
"гуси" : "geese",
"гусиный" : "goose",
"густеть" : "thicken",
"густой" : "thick dense, deep rich",
"густонаселенный" : "populous",
"густота" : "thickness, density, depth",
"гусь" : "goose, хорош гусь; See also: как с гуся вода",
"гуськом" : "in single file",
"гуща" : "grounds pl., sediment, thicket, fig. center  middle",
"гэс" : "abbr.: гидростанция",
"д" : "abbr.:, деревня, дом",
"да" : "yea, yep, yes",
"давать" : "bestow, gave, give, impart",
"давка" : "throng jam",
"давление" : "pressure",
"давний" : "old",
"давнопрошедший" : "pluperfect",
"давным-давно" : "lang",
"даже" : "tho,",
"далматский" : "dalmatian",
"дальневосточный" : "Far Eastern",
"дальнейший" : "further, в дальнейшем later #or further on",
"дальний" : "distant, remote, a. далекий",
"дальний восток" : "the Far East",
"дальнобойный" : "long range",
"дальновидный" : "clear-sighted",
"дальнозоркий" : "far- long-sighted",
"дальность" : "remoteness, engin. range",
"дальше" : "farther, further, then next, дальше! go on; See also: не дальше как, не дальше чем",
"дама" : "lady, partner, queen",
"дамаск" : "damascus",
"дамба" : "dam dike",
"дамка" : "king",
"дамский" : "ladies', women's",
"даниил" : "Daniel",
"данила" : "Daniel",
"дания" : "Denmark",
"данная" : "math. quantity",
"данные" : "pl. data facts, statistics",
"данный" : "given present this",
"дантист" : "dentist",
"дань" : "tribute",
"дар" : "gift",
"даритель" : "grantor",
"дарить" : "give  present",
"дармоед" : "sponger",
"дарование" : "gift talent",
"даровать" : "confer",
"даровитый" : "gifted talented",
"даровой" : "gratis free",
"даром" : "adv. gratis for nothing, in vain; See also: даром что, это ему даром не пройдет",
"даром что" : "though",
"дарья" : "Darya",
"дата" : "date",
"дательный" : "gr. dative",
"датировать" : "pf. date",
"датский" : "Danish",
"датчанин" : "Dane",
"датчанка" : "Dane",
"датчик" : "pickoff, sensor",
"дать" : "give, let, bestow, take  pledge, make; See also: давай{!}, ни дать ни взять, давать ход делу",
"дать взятку" : "bribe popul. grease, trick",
"дать волю" : "give free rein",
"дать заказ" : "commerc. place an order",
"дать знать1" : "let know",
"дать маху" : "miss one's mark make a blunder",
"дать на чай1" : "tip",
"дать о себе знать1" : "send news",
"дать себя знать1" : "make o.s. felt",
"дача" : "giving, cottage summer residence villa; See also: на даче",
"дачник" : "summer resident",
"дачный" : "suburban, country..., garden",
"даша" : "dim. #of Дарья",
"дашка" : "dim. #of Дарья"
};
