var dicctr_74 = {
"размышление" : "reflection  thought",
"размышлять" : "reflect meditate",
"размягчать" : "soften mollify",
"размягчить" : "soften mollify",
"размякнуть" : "become soft",
"размять" : "knead, famil. stretch",
"разнашивать" : "tread out wear to shape",
"разнести" : "s. разносить",
"разнимать" : "part, take to pieces",
"разница" : "difference",
"разновидность" : "variety sort",
"разногласие" : "discord disagreement difference variance, discrepancy",
"разнокалиберный" : "s. разношерстный",
"разномастный" : "s. разношерстный",
"разнообразие" : "variety diversity multiplicity",
"разнообразить" : "diversify",
"разнообразный" : "manifold multifarious various",
"разнореч" : "s. противореч...",
"разнородность" : "promiscuity",
"разнородный" : "hybrid, mixed, promiscuous",
"разносчик" : "peddler hawker, boy man, messenger",
"разноцветный" : "multicolored",
"разношерстный" : "variegated, famil. motley mixed",
"разнузданный" : "unbridled",
"разный" : "various different diverse",
"разнюхивать" : "ferret",
"разнять" : "part, take to pieces",
"разоблачать" : "expose disclose unmask",
"разоблачение" : "exposure disclosure unmasking",
"разоблачить" : "expose disclose unmask",
"разобрать" : "take to pieces dismantle pull down, investigate inquire into, review, analyze  parse, make out decipher understand, sort out, jur. try, buy up, famil. take, impf. be particular",
"разобщенный" : "disjunct",
"разогнать" : "disperse scatter, dispel, famil. drive away",
"разогнаться" : "take a run",
"разогнуть" : "unbend straighten",
"разогревать" : "warm",
"разогреть" : "warm, heat; See also: греться на солнце",
"разодетый" : "dressed up",
"разодрать" : "impf. rend, famil. tear",
"разозлить" : "vex anger #or make angry irritate, -ся be #or feel angry, fig. rage",
"разойтись" : "s. расходиться",
"разомкнуть" : "open",
"разорванный" : "faulted, lacerated, torn",
"разорвать" : "s. разрывать",
"разоренный" : "broke, down and out",
"разочаровать" : "disappoint",
"разочаровывать" : "disappoint",
"разрабатывать" : "work up  process, work out elaborate, farm. till, mining exploit",
"разработать" : "work up  process, work out elaborate, farm. till, mining exploit",
"разработка" : "working, elaboration, farm. tillage, mining exploitation",
"разражаться" : "burst out",
"разразиться" : "burst out",
"разрастаться" : "grow, enlarge expand",
"разрастись" : "grow, enlarge expand",
"разрежать" : "rarefy",
"разреженный" : "rarefied",
"разрез" : "cut, section, angle",
"разрезать" : "cut  slit",
"разрезной нож" : "paper knife",
"разрезывать" : "s. разрезать",
"разрешать" : "permit allow, solve, release, absolve, settle",
"разрешаться" : "be solved, end burst, be delivered",
"разрешающий" : "permissive",
"разрешение" : "permission, licence, solution, settlement, absolution, delivery",
"разрешить" : "permit allow, solve, release, absolve, settle",
"разрисовать" : "pf. ornament",
"разрозненный" : "odd, isolated",
"разрубать" : "split",
"разрубить" : "split",
"разруха" : "ruin",
"разрушать" : "destroy demolish, ruin, frustrate",
"разрушаться" : "ruin",
"разрушение" : "destruction demolition devastation",
"разрушительный" : "destructive, ruinous, shattering, subversive",
"разрушить" : "destroy demolish, ruin, frustrate",
"разрыв" : "breach break rupture, explosion, gap, engin. на разрыв tensile",
"разрывать" : "разорвать, tear, break, impers. burst explode, разрыть dig up",
"разрывной" : "explosive",
"разрыдаться" : "pf. break into sobs",
"разрыть" : "s. разрывать",
"разрыхлить" : "loosen",
"разрыхлять" : "s. рыхлить",
"разряд" : "category class, discharge, unloading",
"разрядить" : "s. разряжать",
"разрядка" : "spacing space, slackening, disengagement",
"разряжать" : "unload, discharge, reduce disengage, typ. space, famil. dress up",
"разубедить" : "dissuade",
"разубедиться" : "change one's mind",
"разубеждать" : "dissuade",
"разубеждаться" : "change one's mind",
"разуваться" : "take off one's shoes",
"разуверить" : "undeceive disabuse, disappoint",
"разуверять" : "undeceive disabuse, disappoint",
"разузнавать" : "find out",
"разузнать" : "find out",
"разукрасить" : "decorate, embellish",
"разукрашивать" : "decorate, embellish",
"разукрупнить" : "diminish, decentralize",
"разукрупнять" : "diminish, decentralize",
"разум" : "reason, sense",
"разумеется" : "of course",
"разуметь" : "understand, know, mean imply",
"разуметься" : "be meant #or understood",
"разумный" : "rational, reasonable sensible, clever wise",
"разуться" : "take off one's shoes",
"разучивать" : "study learn",
"разучиваться" : "forget unlearn",
"разучить" : "study learn",
"разучиться" : "forget unlearn",
"разъедать" : "corrode, erode",
"разъедающий" : "caustic, corrosive",
"разъезд" : "turnout",
"разыграть" : "play, raffle",
"разыграться" : "break out, run high, happen",
"разыгрывать" : "play, raffle",
"разыгрываться" : "break out, run high, happen",
"разыскать" : "seek search",
"разыскивать" : "seek search",
"разьедать" : "s. есть1",
"разьедающий" : "cankerous",
"разьединить" : "separate, el. disconnect",
"разьединять" : "separate, el. disconnect",
"разьезд" : "trip journey, setting out departure, milit. horse patrol, rail. siding",
"разьезжать" : "drive ride go about, be on a journey #or trip",
"разьезжаться" : "leave, separate, pass o.a.",
"разьехаться" : "leave, separate, pass o.a.",
"разьяренный" : "enraged furious",
"разьяснение" : "explanation, clarification",
"разьяснить" : "explain elucidate",
"разьяснять" : "explain elucidate",
"рай" : "paradise",
"райком" : "district committee",
"район" : "district, region area",
"районный" : "district..., regional",
"райсовет" : "district soviet",
"рак" : "crawfish Brt. crayfish, astr. cancer; See also: морской рак",
"рака" : "reliquary",
"ракета" : "rocket",
"ракетка" : "racket",
"ракетный" : "rocket...",
"раковина" : "shell, sink, bowl",
"ракушка" : "conch",
"рама" : "frame",
"рана" : "wound",
"ранет" : "rennet",
"ранец" : "haversack, knapsack",
"рант" : "rand, welt",
"ранчо" : "ranch",
"рапира" : "rapier",
"рапорт" : "pf. report",
"рапортовать" : "pf. report",
"рапс" : "bot. rape",
"рапсодический" : "rhapsodic",
"рапсодия" : "rhapsody",
"раса" : "race",
"раскаиваться" : "repent",
"раскаивающийся" : "penitent, repentant",
"раскаленный" : "s. раскалять",
"раскалить" : "s. раскалять",
"раскалывать" : "cleave",
"раскачивать" : "swing, shake, famil. bestir",
"раскаяние" : "repentance",
"раскаяться" : "repent",
"расквартировать" : "pf. quarter",
"раскидывать" : "spread, throw out, pitch  set up",
"раскинуть" : "spread, throw out, pitch  set up",
"раскладной" : "folding collapsible",
"раскладывать" : "lay #or spread out display, lay, set up, make light, apportion repartition",
"раскланиваться" : "bow  greet, take leave",
"раскланяться" : "bow  greet, take leave",
"раскол" : "split schism",
"расколотый" : "cleft, cloven, riven",
"расколоть" : "split cleave, crack",
"раскопать" : "dig out #or up",
"раскопка" : "excavation",
"раскорчевать" : "root out",
"раскрасить" : "paint color dye, famil. накрасить paint make up, rouge",
"раскрашивать" : "s. красить",
"раскрепостить" : "emancipate liberate",
"раскрепощать" : "emancipate liberate",
"раскрепощение" : "emancipation liberation",
"раскритиковать" : "pf. scarify",
"раскричаться" : "pf. shout bawl",
"раскрывать" : "open, uncover, disclose reveal, put #one's #cards on the table",
"раскрытие" : "disclosure",
"раскрыть" : "open, uncover, disclose reveal, put #one's #cards on the table",
"раскулачить" : "pf. dispossess #or oust",
"раскупать" : "buy up",
"раскупить" : "buy up",
"раскупоривать" : "uncork, open",
"раскупорить" : "uncork, open",
"раскусить" : "crack, famil. see through get",
"раскусывать" : "crack, famil. see through get",
"раскутать" : "unwind unwrap",
"раскутывать" : "unwind unwrap",
"расовый" : "racial",
"распад" : "disintegration, decay",
"распадаться" : "fall to pieces, decay, disintegrate, break up  split",
"распадение" : "fission",
"распаковать" : "unpack",
"распаковывать" : "unpack",
"распарывать" : "s. пороть",
"распасться" : "fall to pieces, decay, disintegrate, break up  split",
"распахивать" : "распахать plow up, распахнуть throw #or fling open",
"распаять" : "pf. unsolder",
"распевать" : "sing",
"распекать" : "dress down scold call down blow up",
"распечатать" : "unseal, open",
"распечатка" : "listing, printout",
"распечатывать" : "unseal, open",
"распечь" : "dress down scold call down blow up",
"распиливать" : "saw",
"распилить" : "saw",
"распинать" : "crucify",
"расписание" : "timetable, schedule",
"расписать" : "s. расписывать",
"расписка" : "script",
"расплавленный" : "melted, molten",
"расплачиваться" : "pay off settle accounts, pay",
"расплескать" : "pf. spill",
"расплести" : "unbraid, untwist",
"расплетать" : "unbraid, untwist",
"расплодить" : "propagate multiply",
"расплываться" : "spread, run, swim about, blur, swell, famil. grow fat",
"расплывчатый" : "blurred diffuse vague",
"расплыться" : "spread, run, swim about, blur, swell, famil. grow fat",
"расплющить" : "pf. flatten",
"распознавать" : "perceive discern, find out",
"распознать" : "perceive discern, find out",
"располагать" : "dispose  arrange, place lodge, impf. dispose  have",
"располагающий" : "engaging",
"расползаться" : "creep #or crawl",
"расползтись" : "creep #or crawl",
"распологаться" : "settle, encamp, pf. be situated",
"расположение" : "arrangement order position, situation, inclination favor, mind",
"расположение духа" : "mood",
"расположенный" : "a. situated, disposed, inclined",
"расположить" : "dispose  arrange, place lodge, impf. dispose  have",
"распорка" : "ridgepole, spreader",
"распорядительность" : "administrative ability management",
"распорядительный" : "circumspect efficient",
"распорядиться" : "s. распоряжаться",
"распорядок" : "order rule regulations pl.",
"распоряжаться" : "give orders, dispose, take charge #or care, impf. manage direct",
"распоряжение" : "order instruction, decree, disposal, charge command",
"расправа" : "punishment, massacre, #short work",
"расправить" : "straighten, smooth, spread stretch",
"расправиться" : "punish avenge o.s.",
"расправлять" : "straighten, smooth, spread stretch",
"расправляться" : "punish avenge o.s."
};
