var dicctr_22 = {
"железо" : "iron, кровельное железо sheet iron, куй железо пока горячо strike while the iron is hot",
"железобетон" : "reinforced concrete",
"желоб" : "gutter",
"желобок" : "riffle",
"желтая медь" : "brass",
"желтеть" : "grow #or turn yellow, impf. appear #or show yellow",
"желтизна" : "yellow",
"желтоватый" : "yellowish",
"желток" : "yolk",
"желтуха" : "jaundice",
"желтый" : "yellow",
"желудок" : "stomach",
"желудочек" : "ventricle",
"желудочный" : "gastric stomachic",
"желудь" : "acorn",
"желчный" : "gall..., bilious",
"желчь" : "bile gall, grief",
"жеманиться" : "mince, be prim",
"жеманница" : "prude",
"жеманный" : "affected mincing prim",
"жеманство" : "primness prudery",
"жемчуг" : "pl.",
"жемчужина" : "pearl",
"жемчужный" : "pearl",
"жена" : "wife, obsol. woman",
"женатый" : "married",
"женить" : "pf. marry",
"женитьба" : "marriage",
"жениться" : "marry",
"жених" : "fiance', bridegroom, suiter, famil. marriageable young man",
"женолюб" : "lady-killer ladies' man",
"женоненавистник" : "woman hater",
"женоненавистничество" : "misogyny",
"женоподобный" : "womanlike",
"женский" : "female woman #or women's, girls', gr. feminine",
"женственность" : "femininity, muliebrity, womanhood",
"женственный" : "womanly, womanish effeminate",
"женщина" : "woman",
"женщины" : "womankind, women, womenfolk",
"жены" : "wives",
"женьшень" : "ginseng",
"жердь" : "pole",
"жеребенок" : "foal colt",
"жеребец" : "stallion",
"жеребячий" : "coltish",
"жерло" : "crater, aperture mouth, muzzle",
"жернов" : "millstone",
"жертва" : "sacrifice, victim",
"жертвенный" : "sacrificial",
"жертвователь" : "donor",
"жертвовать" : "sacrifice, give",
"жертвоприношение" : "offering",
"жест" : "gesture",
"жестикулировать" : "gesticulate",
"жесткий" : "hard, rough rude coarse harsh, tough, stiff rigid severe rigorous; See also: жесткий вагон",
"жесткий вагон" : "passenger car Brt. second-class carriage",
"жестокий" : "cruel, terrible dreadful fierce grim, rigorous violent",
"жестокосердие" : "hard-heartedness",
"жестокость" : "cruelty, severity",
"жесть" : "tin",
"жестянка" : "can Brt. tin",
"жестяной" : "tin...",
"жестянщик" : "tinsmith",
"жетон" : "counter, medal, token",
"жечь" : "burn, torment",
"живительный" : "vivifying, crisp",
"живить" : "vivify animate",
"живой" : "living, alive, lively vivid vivacious, quick nimble, real true, в живых alive, жив и здоров safe & sound, ни жив ни мертв more dead than alive, задеть за живое sting to the quick",
"живописец" : "painter",
"живописный" : "picturesque",
"живопись" : "painting",
"живость" : "vivacity, vividness",
"живот" : "popul. belly, stomach, obsol. life",
"животворный" : "vivifying",
"животноводство" : "cattle breeding",
"животное" : "animal",
"животный" : "animal, fig. brutal",
"животрепещущий" : "living, fig. burning",
"живучий" : "hardy tough, enduring",
"живущий" : "indwelling",
"живьем" : "popul. alive",
"жидкий" : "liquid fluid, watery weak thin, sparse scanty",
"жидкость" : "liquid, scantiness",
"жижа" : "slush, broth",
"жижица" : "slush, broth",
"жизненность" : "viability, vitality, vividness",
"жизненный" : "life worldly, vivid, living, vital",
"жизнеописание" : "biography",
"жизнерадостный" : "cheerful merry",
"жизнеспособный" : "viable",
"жизнь" : "life, practice, в жизнь не ... never, при жизни in a pers.'s lifetime, alive, не на жизнь а на смерть of life & death",
"жила" : "famil. sinew tendon, vein",
"жилет" : "vest Brt. waistcoat",
"жилетка" : "vest Brt. waistcoat",
"жилец" : "lodger roomer, inmate, obsol. = житель",
"жилистый" : "sinewy stringy  wiry",
"жилище" : "dwelling lodging",
"жилищный" : "housing",
"жилка" : "dim. #of жила, veinlet, vein",
"жилой" : "dwelling, inhabited, living жилплощадь",
"жилплощадь" : "living space",
"жилье" : "habitation, famil. dwelling",
"жимолость" : "honeysuckle, woodbine",
"жир" : "fat, grease; See also: рыбий жир",
"жираф" : "camelopard, giraffe",
"жиреть" : "grow fat",
"жирный" : "fat, grease greasy, bot. fleshy, fig. rich, typ. bold",
"жиро" : "endorsement",
"жировой" : "fat",
"житейский" : "worldly life, everyday",
"житель" : "inhabitant resident",
"жительница" : "inhabitant resident",
"жительство" : "residence, вид на жительство residence permit",
"житие" : "life",
"житница" : "granary",
"жить" : "live, reside lodge, exist be, как живете? how are you ?, жил-был ..., once upon a time there was ..., -ся: ему хорошо живется he is well off, be well off",
"житье" : "life living, residence stay",
"жниво" : "stubble",
"жокей" : "jockey",
"жонглировать" : "juggle",
"жужжание" : "buzz, hum",
"жук-светляк" : "firefly",
"жулик" : "bilk, faker, rogue, slicker",
"жульничать" : "con, nobble",
"журавль" : "crane, shadoof",
"журить" : "scold rebuke",
"журнал" : "magazine periodical journal, diary, nav. log",
"журналист" : "newsman journalist",
"журналистика" : "journalism",
"журчание" : "purl murmur",
"журчать" : "purl murmur",
"жуткий" : "weird uncanny dismal sinister, мне жутко I am terrified",
"жуткость" : "dismay dread",
"жуть" : "dismay dread",
"жюри" : "jury",
"за" : ": behind, over across beyond, out of, at, after, over past, before, in for during, for; See also: за то что, за что{?}",
"за бесценок" : "famil. for a song #or a trifling sum",
"за глаза" : "in s.b.'s absence behind one's back, plentifully",
"за кулисами" : "behind the scenes",
"за неимением" : "for want of",
"за последнее время" : "lately recently",
"за рубежом" : "abroad",
"за счет" : "at the expense",
"за то, что" : "because",
"за чистую монету" : "in good faith",
"за что" : "what for? why?, : behind, across beyond, at over, after, because of, with, ~ мной ... a. I owe ..., комната ~ мной I take the room",
"забавлять" : "amuse",
"забавный" : "amusing, entertaining, funny, jocund",
"забастовка" : "strike, walkout",
"забвение" : "oblivion",
"забегать вперед" : "forestall",
"забежать" : "run in get, run off away, famil. drop in",
"забетонировать" : "concrete",
"забивать" : "drive in, nail up, stop up choke, block, famil. outdo beat, spout forth, sound, famil. stuff, take, -ся famil. hide get, pf. begin to beat",
"забинтовать" : "bandage dress",
"забирать" : "take, capture seize, arrest, put, turn steer, close partition, -ся climb #or creep, steal in penetrate, hide, get",
"забитый" : "browbeaten cowed timid",
"забить" : "drive in, nail up, stop up choke, block, famil. outdo beat, spout forth, sound, famil. stuff, take, -ся famil. hide get, pf. begin to beat",
"забить гол" : "score",
"забияка" : "bully squabbler",
"заблаговременно" : "in time beforehand",
"заблаговременный" : "preliminary, timely",
"заблагорассудиться" : "think fit",
"заблеять" : "bleat",
"заблудившийся" : "stray, strayed",
"заблудиться" : "pf. lose one's way go astray",
"заблудший" : "lost, stray",
"заблуждаться" : "be mistaken err",
"заблуждающийся" : "aberrant, wrong-headed",
"заблуждение" : "error mistake, ввести в заблуждение mislead",
"забодать" : "butt gore",
"забой" : "stope",
"заболевание" : "a. = болезнь",
"заболевать" : "fall sick #or ill  be taken ill with, ache, заболевание",
"заболеть" : "fall sick #or ill  be taken ill with, ache, заболевание",
"заболоченный" : "waterlogged",
"забор" : "fence",
"заборный" : "fence..., fig. vulgar trashy",
"забота" : "care  concern anxiety worry trouble; See also: без забот",
"заботиться" : "care  take care of look after, worry be anxious",
"заботливый" : "careful provident, attentive, anxious solicitous",
"заботящийся" : "solicitous",
"забраковать" : "scrap reject",
"забрасывать" : "забросать fill up, heap, pelt, bespatter, забросить throw fling cast, neglect give up",
"забрать" : "take, capture seize, arrest, put, turn steer, close partition, -ся climb #or creep, steal in penetrate, hide, get",
"забредать" : "wander #or get",
"забредить" : "rave talk deliriously",
"забренчать" : "clink jingle, strum",
"забрести" : "wander #or get",
"забронировать" : "armor",
"забросать" : "s. забрасывать",
"забросить" : "s. забрасывать",
"заброшенный" : "deserted, unkempt",
"забрызгать" : "pf. splash sprinkle",
"забрызгивать" : "bespatter, dabble",
"забрюзжать" : "grumble growl grouch",
"забывать" : "forget",
"забывчивый" : "forgetful",
"забытый" : "forgotten",
"забыть" : "forget",
"забытье" : "unconsciousness swoon, drowsiness, slumber, reverie, frenzy",
"завал" : "heap drift, obstruction abatis",
"заваливать" : "fill #or heap, cover, block obstruct close, famil. overburden, -ся fall, sink, collapse",
"завалить" : "fill #or heap, cover, block obstruct close, famil. overburden, -ся fall, sink, collapse",
"заваривать" : "boil  make, scald, fig. concoct",
"заварить" : "boil  make, scald, fig. concoct",
"заведение" : "establishment institution, учебное заведение school",
"заведовать" : "be in charge #or the head of manage",
"заведомо" : "knowingly, admittedly certainly",
"заведомый" : "notorious indubitable",
"заведующий" : "chief head, director",
"завезти" : "s. завозить",
"завербовать" : "enlist recruit, engage hire",
"заверение" : "assurance",
"заверить" : "s. заверять",
"завернуть" : "s. завертывать",
"завертеть" : "pf. start turning",
"завертывать" : "wrap, turn, famil. drop in",
"завершать" : "finish complete accomplish, crown",
"завершение" : "conclusion end, completion",
"завершить" : "solve decide, direct, accomplish",
"заверять" : "assure, attest authenticate",
"завеса" : "curtain, screen, fig. veil",
"завесить" : "s. завешивать",
"завести" : "s. заводить",
"завестись" : "appear, nest, get have",
"завет" : "legacy, precept maxim, vow, #Bibl. ~ Testament",
"заветный" : "sacred, dear precious, fond, cherished, intimate, obsol. forbidden",
"завешивать" : "cover hang with curtain",
"завещание" : "testament will",
"завещатель" : "deviser, legator, testator",
"завещать" : "pf. bequeath, instruct leave as precept",
"завзятый" : "inveterate, enthusiastic, true genuine",
"завивать" : "wave curl, wind round",
"завивка" : "waving, холодная завивка water wave",
"завидный" : "enviable desirable, envious",
"завидовать" : "envy  be envious",
"завизжать" : "shriek, yelp",
"завилять" : "wag, fig. prevaricate shuffle",
"завинтить" : "screw up",
"завинчивать" : "screw up",
"зависеть" : "depend",
"зависимость" : "dependence, в зависимости от depending on",
"зависимый" : "dependent",
"завистливый" : "envious jealous",
"зависть" : "envy",
"завитой" : "curly",
"завиток" : "curl ringlet flourish",
"завить" : "wave curl, wind round",
"завком" : "works council"
};
