var dicctr_24 = {
"закладная" : "mortgage",
"закладной" : "pawn...",
"закладчик" : "pawner, pawnbroker",
"закладывать" : "put  lay  place, famil. mislay, heap pile, wall up, pawn pledge, harness put to get ready, mark put in, famil. obstruct  press",
"заклевать" : "peck to death #or wound, famil. wreck ruin",
"заклевывать" : "peck to death #or wound, famil. wreck ruin",
"заклеивать" : "glue #or paste up",
"заклеить" : "glue #or paste up",
"заклеймить" : "brand, a. stigmatize",
"заклепать" : "rivet",
"заклепка" : "rivet",
"заклепывание" : "clench",
"заклепывать" : "rivet",
"заклинание" : "conjuration incantation, exorcism",
"заклинатель" : "conjurer exorcist, charmer",
"заклинать" : "conjure adjure",
"заключать" : "enclose put, confine imprison, conclude (= finish with Р по Д - что, : #treaty [= make] #peace etc.), impf. contain",
"заключаться" : "consist, end",
"заключение" : "confinement imprisonment, conclusion",
"заключенный" : "prisoner",
"заключительный" : "final concluding",
"заключить" : "enclose put, confine imprison, conclude (= finish with Р по Д - что, : #treaty [= make] #peace etc.), impf. contain",
"заклятие" : "paternoster",
"заклятый" : "implacable, sworn",
"заковать" : "put in  chain, fig. freeze, prick",
"заковывать" : "put in  chain, fig. freeze, prick",
"заколачивать" : "drive in, nail up, board up, fig. beat to death, thrash",
"заколдованный круг" : "vicious circle",
"заколдовать" : "enchant, bewitch charm",
"заколдовывать" : "enchant, bewitch charm",
"заколка" : "barrette",
"заколотить" : "drive in, nail up, board up, fig. beat to death, thrash",
"заколоть" : "kill slaughter, stab, pin, у меня закололо в боку I have a stitch in the side",
"закон" : "law, rule; See also: закон божий, обьявить вне закона, по закону, вопреки закону, охраняемый законом",
"закон божий" : "Law, religion",
"закон линча" : "lynch law",
"законнорожденный" : "legitimate",
"законность" : "legality, law",
"законный" : "legal lawful legitimate",
"законовед" : "jurist jurisprudent",
"законодатель" : "legislator",
"законодательный" : "legislative",
"законодательство" : "legislation",
"законодательствовать" : "legislate",
"закономерность" : "regularity",
"закономерный" : "regular",
"законопатить" : "calk",
"законоположение" : "regulation",
"законопроект" : "bill draft",
"законсервировать" : "conserve preserve, can Brt. tin",
"законспектировать" : "outline epitomize",
"закончить" : "finish conclude",
"закопать" : "bury, fill up",
"закопошиться" : "swarm, famil. stir, mess around",
"закоптелый" : "smoky",
"закоптить" : "smoke, soot",
"закоренелый" : "deep-rooted inveterate ingrained",
"закорючка" : "flourish, trick ruse, hitch",
"закоснелость" : "obduracy",
"закоснелый" : "= закоренелый",
"закоснеть" : "persist sink fossilize",
"закоулок" : "alleyway lane, nook",
"закоченелый" : "numb stiff",
"закоченеть" : "grow numb stiffen",
"закрадываться" : "creep in",
"закрасить" : "paint over",
"закрасться" : "creep in",
"закрашивать" : "paint over",
"закрепить" : "fasten fix, strengthen consolidate fortify, secure, assign, mining strut",
"закрепление" : "fastening, strengthening, securing, assignment, milit. fortification",
"закреплять" : "fasten fix, strengthen consolidate fortify, secure, assign, mining strut",
"закрепостить" : "enslave",
"закрепощать" : "enslave",
"закрепощение" : "enslavement",
"закричать" : "cry  shout, scream",
"закройщик" : "cutter",
"закройщица" : "cutter",
"закругление" : "rounding, curve",
"закруглить" : "round",
"закруглять" : "round",
"закружить" : "turn  whirl, circle, rotate revolve spin, stray about; See also: голова кружится",
"закрутить" : "turn, twist",
"закрученный" : "involute",
"закручивать" : "turn, twist",
"закрывать" : "shut close, lock, cover hide, turn off; See also: закрывать глаза",
"закрывать глаза" : "shut one's eyes",
"закрывающий" : "occlusive",
"закрытие" : "closing close",
"закрытый" : "closed, secret, boarding, high-necked, в закрытом помещении indoor",
"закрыть" : "shut close, lock, cover hide, turn off; See also: закрывать глаза",
"закулисный" : "behind the scenes, secret",
"закупать" : "buy  purchase",
"закупить" : "buy  purchase",
"закупка" : "purchase",
"закупоривать" : "cork  bung",
"закупорить" : "cork  bung",
"закупорка" : "corking, med. embolism, constipation",
"закупщик" : "purchasing agent buyer",
"закуривать" : "light  begin to smoke, famil. smoke, закури! have a cigar!",
"закурить" : "light  begin to smoke, famil. smoke, закури! have a cigar!",
"закусить" : "bite, take #or have a snack lunch, eat; See also: закусить язык",
"закусить язык" : "stop short hold one's tongue",
"закуска" : "snack lunch, hors d'oeuvres, на закуску a. for the last bit",
"закусочная" : "lunchroom snackbar",
"закусывать" : "bite, take #or have a snack lunch, eat; See also: закусить язык",
"закутать" : "wrap up",
"закутывать" : "wrap up",
"зал" : "hall, room",
"зал ожидания" : "waiting room",
"зала" : "hall, room",
"залатать" : "patch mend",
"залаять" : "bark",
"залегание" : "geol. deposit",
"залегать" : "lie, hide, fig. root, med. be obstructed",
"заледенелый" : "icy, numb",
"заледенеть" : "freeze ice, grow numb, chill",
"залежалый" : "stale spoiled; See also: залежалый товар",
"залежалый товар" : "drug",
"залежаться" : "lie long  stale",
"залеживаться" : "lie long  stale",
"залежь" : "geol. deposit, farm. fallow",
"залезать" : "climb up in etc., hide, steal #or get in",
"залезть" : "climb up in etc., hide, steal #or get in",
"залепить" : "stop close, glue #or paste up, stick over",
"залеплять" : "stop close, glue #or paste up, stick over",
"залетать" : "fly in up far off beyond, come get",
"залететь" : "fly in up far off beyond, come get",
"залетный" : "stray, migratory, famil. visitant",
"залечивать" : "heal, famil. cure to death",
"залечить" : "heal, famil. cure to death",
"залечь" : "lie, hide, fig. root, med. be obstructed",
"залив" : "gulf bay",
"заливать" : "flood overflow, pour over cover, fill, extinguish, -ся break into #or shed, burst out, trill warble roll quaver",
"заливной" : "floodable flooded, jellied, resonant",
"залить" : "flood overflow, pour over cover, fill, extinguish, -ся break into #or shed, burst out, trill warble roll quaver",
"залог" : "pledge, pawn, security, gr. voice, дать в залог pawn pledge",
"заложить" : "put  lay  place, famil. mislay, heap pile, wall up, pawn pledge, harness put to get ready, mark put in, famil. obstruct  press",
"заложник" : "hostage",
"заложница" : "hostage",
"залп" : "volley; See also: залпом",
"залпом" : "famil. at one draught, at a stretch, at one sitting, blurt out",
"замазать" : "smear soil, paint over, putty, fig. veil hush up",
"замазка" : "putty",
"замазывать" : "smear soil, paint over, putty, fig. veil hush up",
"замалчивать" : "conceal keep secret",
"заманивать" : "lure decoy entice",
"заманить" : "lure decoy entice",
"заманчивый" : "alluring tempting",
"замарать" : "soil stain",
"замариновать" : "pickle",
"замаскировать" : "mask, disguise camouflage",
"замахиваться" : "lift one's arm  threaten",
"замахнуться" : "lift one's arm  threaten",
"замашка" : "habit manner",
"замедление" : "delay",
"замедленный" : "deferred, impaired",
"замедлитель" : "inhibitor",
"замедлить" : "slow down reduce, delay retard, не замедлять с soon",
"замедлять" : "slow down reduce, delay retard, не замедлять с soon",
"замена" : "substitution  replacement, jur. commutation, substitute",
"заменимый" : "replaceable exchangeable",
"заменитель" : "substitute",
"заменить" : "replace  substitute, jur. commute, follow",
"заменять" : "replace  substitute, jur. commute, follow",
"замереть" : "s. замирать",
"замерзание" : "freezing, точка замерзания freezing point",
"замерзать" : "freeze congeal, be frozen",
"замерзнуть" : "freeze congeal, be frozen",
"замерзший" : "frozen",
"замертво" : "dead unconscious",
"замесить" : "knead",
"замести" : "s. заметать",
"заместитель" : "deputy assistant vice-...",
"заместить" : "s. замещать",
"заметать" : "sweep, drift cover, block up, wipe out",
"заметить" : "s. замечать",
"заметка" : "mark, note, paragraph article item",
"заметно" : "a. one can see notice",
"заметный" : "noticeable perceptible, marked remarkable",
"замечание" : "remark observation, pl. criticism, reproof rebuke, достойный замечания worthy of notice",
"замечательный" : "remarkable outstanding, wonderful, noted",
"замечать" : "notice, mark, observe remark, reprove",
"замешательство" : "confusion embarrassment, в замешательстве confused disconcerted embarrassed",
"замешать" : "involve entangle, замешан в a. mixed up with, mingle in with, supervene",
"замешивать" : "involve entangle, замешан в a. mixed up with, mingle in with, supervene",
"замешкаться" : "pf. be delayed tarry",
"замещать" : "replace, substitute, act for deputize, fill",
"замещающий" : "substituting",
"замещение" : "substitution, replacement, deputizing, filling",
"заминать" : "crumple, smother hush up, -ся falter halt stick be confused stop short, flag",
"заминка" : "halt hitch",
"замирать" : "be #or stand stockstill transfixed, stop, fade die away, у меня сердце замерло my heart stood still",
"замкнутый" : "closed, secluded, reserved, cf. замыкать",
"замкнуть" : "close, obsol. lock, -ся isolate o.s., замыкаться в себе become unsociable",
"замок" : "castle",
"замок1" : "castle",
"замок2" : "lock; See also: американский замок, на замке, под замком",
"замолвить" : "pf.: замолвить слово, famil. put in a word",
"замолкать" : "become silent stop  cease break off, die away #or off",
"замолкнуть" : "become silent stop  cease break off, die away #or off",
"замолчать" : "conceal keep secret",
"замораживать" : "freeze congeal",
"заморить" : "exterminate; See also: морить голодом",
"заморозить" : "freeze congeal",
"заморозки" : "frost",
"заморский" : "oversea, foreign",
"замочить" : "wet moisten, soak step",
"замочная скважина" : "keyhole",
"замуж" : "& выходить",
"замужем" : "married",
"замужество" : "marriage",
"замужний" : "замужняя",
"замучить" : "torment to death, fatigue exhaust",
"замша" : "chamois suede",
"замшевый" : "chamois suede",
"замыкание" : "короткое замыкание",
"замышлять" : "meditate",
"замять" : "burke",
"занавеска" : "curtain, purdah",
"занести в дебет" : "pf. debit",
"занимание" : "borrowing",
"занимательный" : "interesting entertaining amusing, engaging captivating",
"занимать" : "borrow, occupy take, employ busy, reserve secure, interest engross absorb, entertain; See also: занимать дух у",
"занимать дух у" : "famil. take one's breath away",
"заниматься" : "occupy #or busy o.s., engage in, attend, learn study, set about begin to, blaze #or flare up, break dawn, a. заря",
"заново" : "anew afresh",
"заноза" : "splinter",
"занозить" : "pf. run a splinter",
"занос" : "drift",
"заносить" : "soil, wear out",
"заносчивый" : "arrogant presumptuous",
"занумеровать" : "number",
"занятие" : "occupation work business, exercise, famil. lessons school lecture, milit. capture",
"занятный" : "famil. = занимательный",
"занятой" : "busy",
"занятый" : "occupied busy engaged",
"занять" : "borrow, occupy take, employ busy, reserve secure, interest engross absorb, entertain; See also: занимать дух у",
"заодно" : "conjointly, together, at one, famil. at the same time besides too",
"заокеанский" : "transoceanic",
"заостренный" : "edgy",
"заострить" : "point sharpen, -ся taper",
"заострять" : "point sharpen, -ся taper",
"заочник" : "student of a correspondence school college etc.",
"заочное обучение" : "instruction by correspondence",
"заочное решение" : "jur. judgment by default",
"заочный" : "in a pers.'s absence, behind one's back",
"запад" : "west",
"западать" : "fall in sink, impress",
"западник" : "hist. Westerner",
"западный" : "west, occidental"
};
