var dicctr_86 = {
"суффикс" : "suffix",
"сухарь" : "cracker zwieback Brt. biscuit",
"сухожилие" : "sinew",
"сухой" : "dry, arid, lean, land..., fig. cool cold, boring dull",
"сухопутный" : "land...",
"сухость" : "dryness s. сухой",
"сухощавый" : "lean meager",
"сучить" : "twist, roll",
"сучок" : "cf.",
"суша" : "land",
"сушение" : "drying",
"сушеный" : "dried",
"сушилка" : "drying apparatus, сушильня",
"сушильня" : "drying room",
"сушить" : "высушить dry, air, иссушить wear out emaciate",
"сушка" : "drying, ring-shaped cracknel",
"существенный" : "essential substantial",
"существительное" : "noun substantive",
"существо" : "creature being, essence, по существу at bottom, to the point",
"существование" : "existence being, subsistence",
"существовать" : "exist be, live",
"существующий" : "being, existent, existing",
"сущий" : "existing, famil. plain  quite  sheer downright",
"сущность" : "essence substance, в сущности at bottom properly",
"суэцкий канал" : "Suez Canal",
"сфальшивить" : "sing out of tune play falsely, famil. cheat be false",
"сфантазировать" : "invent",
"сфера" : "sphere, field realm",
"сферический" : "globular, spheric, spherical",
"сфероид" : "spheroid",
"сфинкс" : "sphinx",
"сформировать" : "form",
"сформовать" : "mold model",
"сформулировать" : "formulate",
"сфотографировать" : "photograph",
"схватить" : "s. схватывать",
"схватка" : "scramble",
"схватывание" : "grasp",
"схема" : "diagram scheme",
"схематический" : "schematic",
"схитрить" : "dodge, fox, quibble, cf. мудрить",
"сходить" : "go down descend, get off, come off, run off, leave, disappear, famil. pass, popul. do, pass of, сходить pf. go, cf. ум",
"сходиться" : "meet, gather, become friends, agree, harmonize, coincide, approximate, famil. click",
"сходка" : "meeting",
"сходни" : "gangplank gangway",
"сходный" : "similar  like, famil. reasonable",
"сходня" : "gangplank",
"сходство" : "similarity  likeness",
"схожий" : "similar",
"сцедить" : "pf. draw off",
"сцеживать" : "decant",
"сцена" : "stage, scene",
"сценарий" : "scenario script",
"сценический" : "stage... scenic",
"сцепить" : "s. сцеплять",
"сцепиться" : "grapple",
"сцепление" : "adhesion, cohesion",
"сцеплять" : "catenate, concatenate",
"счастливо" : "famil. bye-bye so long",
"счастливо отделаться" : "have a narrow escape",
"счастливого пути" : "bon voyage!",
"счастливый" : "happy, fortunate lucky; See also: счастливого пути, счастливо, счастливо отделаться",
"счастье" : "happiness, good luck, fortune; See also: к счастью, по счастью",
"счесть" : "s. считать",
"счет" : "account, bill, count",
"счетчик" : "meter",
"счеты" : "abacus",
"сшибать" : "s. сбить",
"сшибить" : "s. сбить",
"сшивать" : "sew",
"сшить" : "sew",
"съедобный" : "comestible, eatable, edible",
"съезд" : "convention",
"сыворотка" : "whey, serum",
"сыграть" : "play, gamble, rage, sparkle, a. act",
"сыграть вничью" : "draw",
"сызнова" : "famil. anew again",
"сын" : "son, a. child",
"сыновний" : "filial",
"сынок" : "sonny",
"сыпать" : "strew scatter, pour, famil. sputter pelt crack squander",
"сыпаться" : "pour, famil. spatter hail pelt",
"сыпной тиф" : "spotted fever",
"сыпучий" : "dry, quick",
"сыпь" : "rash",
"сыр" : "cheese; See also: как сыр в масле",
"сыреть" : "dampen",
"сырец" : "шелк-сырец",
"сырный" : "cheese..., caseous",
"сыроватый" : "dampish, rare Brt. underdone",
"сырой" : "damp, moist, raw, crude, unbaked",
"сырость" : "dampness, moisture",
"сырье" : "coll. raw material",
"сыскать" : "pf. find",
"сыскаться" : "be found",
"сыскной" : "detective",
"сытный" : "substantial rich, famil. fat",
"сытый" : "satisfied, fat",
"сыч" : "horned owl",
"сыщик" : "detective policeman",
"сьедать" : "s. есть1",
"сьедобный" : "edible",
"сьежиться" : "shrink, be shy",
"сьезд" : "congress",
"сьездить" : "pf. go, fetch, visit",
"сьезжать" : "go drive down, move",
"сьезжаться" : "meet, gather",
"сьемка" : "survey, shooting",
"сьестной" : "food...",
"сьесть" : "s. есть1",
"сьехать" : "go drive down, move",
"сэкономить" : "save, economize",
"сэр" : "sir",
"сюда" : "here hither, this way",
"сюжет" : "subject, plot",
"сюрприз" : "surprise",
"сюртук" : "frock coat",
"т" : "abbr.:, товарищ, том, тонна, тысяча",
"табачный" : "tobacco",
"таблетка" : "pill",
"табличный" : "tabular",
"табурет" : "stool",
"таверна" : "tavern",
"тавро" : "earmark",
"тавтология" : "tautology",
"таз" : "basin, anat. pelvis",
"таинственность" : "mystique",
"таинственный" : "mysterious, secret",
"таинство" : "sacrament",
"таить" : "conceal",
"таиться" : "hide",
"тайвань" : "formosa",
"тайга" : "taiga",
"тайком" : "secretly, behind back",
"тайна" : "secret, mystery",
"тайник" : "hiding, recess",
"тайный" : "secret, stealthy, vague, privy",
"тайфун" : "typhoon",
"так" : "so thus, like that, as, so much, just so, then, well, yes, one way ..., a. правда, famil. properly; See also: не так, так и, так как, и так",
"так ему и надо" : "it serves him right",
"так и" : "and, famil. downright",
"так и быть" : "I don't care",
"также" : "eke, likewise, nor",
"также не" : "neither nor",
"таки" : "famil. all the same, indeed",
"таким образом" : "thus",
"таковой" : "such, like, same, был таков disappeared vanished",
"такой" : "such, so, такое su. such things, такой же the same, as ..., такой-то such-and-such, so-and-so, что такое? famil. what's the matter? what's on?, кто вы такой ? = кто вы?",
"такса" : "rate",
"такси" : "taxi",
"таксировать" : "pf. rate",
"такт" : "mus. time measure bar, fig. tact",
"тактик" : "tactician",
"тактика" : "tactics & sg.",
"тактический" : "tactical",
"тактичность" : "tactfulness",
"тактичный" : "tactful",
"талант" : "talent gift",
"талантливый" : "talented gifted",
"талисман" : "amulet, mascot, talisman",
"талия" : "waist",
"таллий" : "thallium",
"талмуд" : "talmud",
"талон" : "coupon",
"талый" : "thawed, slushy",
"тальк" : "talc, talcum",
"там" : "there, famil. then; See also: там же, там и сям",
"там же" : "in the same place, ibidem",
"там и сям" : "famil. here and there",
"таможенный" : "custom...",
"таможня" : "custom house",
"тамошний" : "of that place there",
"тампон" : "tampon",
"танго" : "tango",
"танец" : "dance",
"танк" : "tank",
"танковый" : "armored..., tank...",
"тантал" : "tantalum, tantalus",
"танцевальный" : "dancing...",
"танцевать" : "dance",
"танцовщик" : "dancer",
"танцовщица" : "dancer",
"танцор" : "dancer",
"танцорка" : "dancer",
"таня" : "dim. #of Татьяна",
"тапочка" : "sport slipper",
"тара" : "tare, packing",
"таракан" : "cockroach",
"таранить" : "ram",
"тарантул" : "tarantula",
"тарахтеть" : "rumble",
"таращить" : "~ глаза stare",
"таращиться" : "goggle",
"тарелка" : "plate",
"тариф" : "tariff",
"тарифный" : "tariff..., standard",
"таскать" : "carry, drag pull, famil. steal, popul. wear",
"таскаться" : "famil. roam, go, frequent, gad about",
"тасование" : "shuffle",
"тасовать" : "shuffle",
"тасс" : ", TASS",
"татарин" : "Tartar",
"татарка" : "Tartar",
"татарский" : "Tartar",
"татьяна" : "Tatyana",
"тафта" : "taffeta",
"тахта" : "davenport",
"тачать" : "seam sew",
"тачка" : "barrow, wheelbarrow",
"тащить" : "потащить drag pull, carry bring, famil. стащить steal pilfer",
"тащиться" : "famil. trudge drag along",
"таять" : "thaw melt, fade die, languish pine",
"тварь" : "creature, famil. wretch",
"твердеть" : "harden",
"твердить" : "reiterate repeat, talk, practice",
"твердо" : "a. well for sure",
"твердость" : "firmness, hardness",
"твердый" : "hard, solid, firm, fast steady, fixed, sound good, famil. sure",
"твердыня" : "stronghold",
"твил" : "twill",
"твое" : "your, yours, su. famil. your folks, cf. ваш",
"твои" : "your, yours, su. famil. your folks, cf. ваш",
"твой" : "your, yours, su. famil. your folks, cf. ваш",
"творение" : "work, creature",
"творец" : "creator, author",
"творительный" : "gr. instrumental",
"творить" : "create do, perform",
"твориться" : "famil. be on",
"творог" : "curd",
"творожистый" : "caseous, cheesy",
"творческий" : "creative",
"творчество" : "work creation",
"твоя" : "your, yours, su. famil. your folks, cf. ваш",
"те" : "cf.",
"театр" : "theater, theatre",
"театральный" : "stagey, stagy, theatrical",
"театральный бинокль" : "opera glasses",
"тебя" : "thee",
"тезис" : "thesis",
"тезка" : "namesake",
"текст" : "text",
"текстиль" : "pl.",
"текстильный" : "textile, cotton",
"текстуальный" : "textual",
"текстура" : "texture",
"тектонический" : "tectonic",
"текучий" : "fluid, fluctuating",
"текущий" : "current, instant, present, miscellaneous",
"телевидение" : "television",
"телевизионный" : "TV"
};
