var dicct_44 = {
"impish" : "шаловливый",
"implacable" : "неумолимый, непримиримый",
"implant" : "насаждать [насадить], внушать [-шить]",
"implantation" : "насаждение",
"implausible" : "невероятный",
"implement" : "инструмент, орудие, принадлежность, выполнять [выполнить]",
"implementation" : "n  осуществление, выполнение",
"implicate" : "вовлекать [-ечь] впутать, заключать в себе",
"implication" : "вовлечение, вывод",
"implicit" : "безоговорочный, подразумеваемый",
"implode" : "взрывать",
"implore" : "умолять [-лить]",
"imply" : "подразумевать, намекать [-кнуть] на, значить",
"impolite" : "невежливый неучтивый",
"impolitic" : "нецелесообразный",
"imponderable" : "неощутимый",
"import" : "ввоз импорт, ввозить [ввезти] импортировать, иметь значение; See also: imports",
"importance" : "значительность",
"important" : "важный значительный",
"importation" : "ввоз импорт",
"imports" : "ввозимые товары",
"importunate" : "назойливый",
"importune" : "докучать  надоедать [-есть]",
"impose" : "навязывать [-зать], облагать [обложить], impose upon, производить впечатление на  импонировать",
"imposition" : "наложение, обложение",
"impossibility" : "невозможность, невероятность",
"impossible" : "невозможный, невероятный",
"impost" : "налог",
"impostor" : "обманщик, самозванец",
"imposture" : "обман плутовство",
"impotence" : "бессилие слабость",
"impotent" : "бессильный слабый",
"impound" : "загонять",
"impoverish" : "доводить до бедности, обеднять [-нить]",
"impracticable" : "неисполнимый неосуществимый",
"impractical" : "непрактичный",
"imprecate" : "проклинать",
"impregnable" : "непоколебимый",
"impregnate" : "оплодотворять [-рить], насыщать [-ытить] пропитывать [-питать]",
"impresario" : "антрепренер",
"impress" : "отпечаток, оттиск, отпечатать, запечатлеть, внушать [-шить], производить впечатление на",
"impressible" : "впечатлительный",
"impression" : "впечатление, оттиск, печатание; See also: I am under the impression that",
"impressive" : "внушительный производящий впечатление",
"imprimatur" : "разрешение цензуры",
"imprint" : "запечатлеть, отпечатать, отпечаток, выходные сведения",
"imprison" : "заключать в тюрьму заточать [-чить]",
"imprisonment" : "заточение заключение",
"improbable" : "невероятный неправдоподобный",
"impromptu" : "импровизированный",
"improper" : "неуместный, непристойный, неправильный",
"impropriety" : "неуместность",
"improve" : "улучшать [улучшить], [у]совершенствовать, повышать ценность, улучшаться [улучшиться], [у]совершенствоваться; See also: improve upon",
"improve upon" : "улучшать [улучшить]",
"improvement" : "усовершенствование, улучшение",
"improvident" : "непредусмотрительный",
"improvisation" : "импровизация",
"improvise" : "импровизировать",
"imprudent" : "неблагоразумный, неосторожный",
"impudence" : "бесстыдство, дерзость",
"impudent" : "нахальный, бесстыдный",
"impugn" : "оспаривать",
"impulse" : "толчок, порыв, возбуждение",
"impulsion" : "толчок, порыв, возбуждение",
"impulsive" : "импульсивный",
"impunity" : "безнаказанность; See also: with impunity",
"impure" : "нечистый, с примесью",
"imputation" : "обвинение",
"impute" : "вменять [-нить], приписывать [-сать]",
"in" : "в во, внутри, внутрь, b) I am in for an examination, be in with; See also: in number, in itself, in 1949, cry out in alarm, in the street, in my opinion, in English, a novel in English, in tens, in the circumstances, a coat in velvet, in this manner, in a word, in crossing the road, be in power, be engaged in reading, be in for",
"in (good) repair" : "в исправном состоянии",
"in (great) request" : "в спросе, заявка",
"in 1949" : "в 1949-ом году",
"in a flash" : "в мгновение ока",
"in a great measure" : "в большой степени",
"in a manners" : "в некоторой степени",
"in a maze" : "быть растерянным",
"in a nutshell" : "кратко в двух словах",
"in a thin house" : "в полупустом зале",
"in a trice" : "мгновенно",
"in a word" : "одним словом",
"in abeyance" : "без владельца, временно отмененный",
"in addition" : "кроме того к тому же",
"in addition to" : "вдобавок к",
"in an undertone" : "вполголоса",
"in anticipation" : "заранее",
"in behalf of" : "для  ради, от имени",
"in bulk" : "в навалку",
"in camera" : "в кабинете судьи",
"in cold blood" : "хладнокровно",
"in collaboration" : "в сотрудничестве",
"in common" : "совместно сообща",
"in compliance with" : "в соответствии с",
"in crossing the road" : "переходя через улицу",
"in default of" : "за неимением",
"in despite of" : "вопреки, несмотря на, назло",
"in detail" : "в подробностях подробно",
"in doors" : "внутри в доме",
"in due time" : "в свое время",
"in effect" : "в действительности",
"in english" : "по-английски",
"in evidence" : "в доказательство",
"in existence" : "существующий",
"in fashion" : "модный",
"in fine" : "в общем словом, наконец",
"in front of" : "перед, впереди",
"in full" : "полностью",
"in full swing" : "в полном разгаре",
"in gear" : "включенный действующий",
"in high feather" : "в отличном настроении",
"in itself" : "само по себе",
"in lieu of" : "вместо",
"in lines with" : "в согласии с",
"in love with" : "влюбленный в",
"in midair" : "высоко в воздухе",
"in my opinion" : "по моему мнению по-моему",
"in no degree" : "ничуть нисколько",
"in no time" : "в мгновение ока",
"in number" : "в количестве  числом в",
"in one go" : "сразу",
"in one's senses" : "в своем уме",
"in order that" : "с тем чтобы",
"in order to" : "чтобы",
"in our midst" : "в нашей среде",
"in part" : "частично",
"in particular" : "в особенности",
"in pawn" : "в закладе",
"in place of" : "вместо",
"in point of" : "в отношении",
"in private" : "конфиденциально",
"in process" : "на ходу",
"in process of construction" : "строящийся",
"in pursuance of" : "согласно",
"in question" : "о котором идет речь",
"in rear of" : "позади",
"in reference to" : "относительно",
"in relation to" : "по отношению к",
"in return" : "в обмен, в ответ",
"in search of" : "в поисках",
"in secret" : "секретно тайком",
"in self-defence" : "при самозащите",
"in short" : "вкратце",
"in sign of" : "в знак",
"in single file" : "гуськом",
"in so far as" : "поскольку",
"in some degree" : "до известной степени",
"in spite of" : "несмотря на",
"in state" : "с помпой",
"in stead of" : "вместо",
"in store" : "наготове, про запас",
"in succession" : "один за другим, подряд",
"in tens" : "по десяти",
"in the bulk" : "в целом",
"in the capacity of" : "в качестве",
"in the circumstances" : "при данных условиях",
"in the employ of" : "на работе у  работающий у",
"in the end" : "в конце концов",
"in the event of" : "в случае",
"in the family way" : "в интересном положении",
"in the gross" : "оптом гуртом",
"in the long run" : "в конце концов",
"in the lump" : "оптом гуртом",
"in the main" : "в основном",
"in the market" : "в продаже",
"in the mean time" : "тем временем",
"in the midst of" : "среди",
"in the name of" : "во имя, от имени",
"in the nick of time" : "как раз во-время",
"in the open air" : "на открытом воздухе",
"in the rear of" : "позади",
"in the street" : "на улице",
"in the sunshine" : "на солнце",
"in the thick of" : "в самой гуще, в разгаре",
"in this manner" : "таким образом",
"in time" : "вовремя",
"in times of old" : "в старину",
"in tune" : "настроенный, в тон",
"in two" : "надвое пополам",
"in twos" : "попарно",
"in vain" : "напрасно тщетно",
"in view of" : "ввиду",
"in virtuee of" : "посредством, в силу",
"in witness of" : "в доказательство",
"in writing" : "письменно",
"inability" : "неспособность",
"inaccessible" : "недоступный, недосягаемый",
"inaccuracy" : "неточность",
"inaccurate" : "неточный, неаккуратный",
"inaction" : "бездействие",
"inactive" : "бездеятельный, недействующий",
"inactivity" : "бездеятельность, инертность",
"inadequacy" : "неадекватность",
"inadequate" : "несоразмерный, недостаточный",
"inadmissible" : "недопустимый неприемлемый",
"inadvertent" : "невнимательный, ненамеренный",
"inadvisable" : "нецелесообразный",
"inalienable" : "неотЙемлемый",
"inalterable" : "неизменный",
"inane" : "бессмысленный, пустой",
"inanimate" : "неодушевленный, безжизненный",
"inapplicable" : "неприменимый",
"inappreciable" : "неощутимый",
"inapproachable" : "недоступный неприступный",
"inappropriate" : "неуместный несоответствующий",
"inapt" : "неспособный, неподходящий",
"inaptitude" : "неуместность",
"inarticulate" : "нечленораздельный невнятный",
"inasmuch" : "inasmuch as",
"inasmuch as" : "так как, ввиду того что",
"inattention" : "невнимание",
"inattentive" : "невнимательный",
"inaudible" : "неслышный",
"inaugural" : "вступительный",
"inaugurate" : "открыть, вводить в должность",
"inauguration" : "вступление в должность, открытие",
"inauspicious" : "зловещий",
"inboard" : "расположенный",
"inborn" : "врожденный, природный",
"inbred" : "врожденный",
"incalculable" : "неисчислимый несчетный, ненадежный",
"incandescent" : "раскаленный, калильный",
"incantation" : "заклинание",
"incapable" : "неспособный",
"incapacitate" : "делать неспособным непригодным",
"incapacity" : "неправоспособность",
"incarcerate" : "заключать в тюрьму",
"incarnate" : "воплощенный, олицетворенный",
"incautious" : "неосторожный опрометчивый",
"incendiary" : "поджигатель, подстрекатель, зажигательный, подстрекающий",
"incense" : "ладан фимиам, [рас]сердить приводить в ярость",
"incentive" : "побудительный мотив побуждение",
"inception" : "начало",
"incessant" : "непрерывный",
"incest" : "кровосмешение",
"incestuous" : "кровосмесительный",
"inch" : "дюйм, пядь; See also: by inches",
"incidence" : "сфера действия",
"incident" : "случай случайность, происшествие, случайный, присущий",
"incidental" : "случайный, побочный, присущий",
"incidentally" : "случайно, между прочим",
"incinerate" : "сжигать [сжечь], испепелять [-лить]",
"incipient" : "зарождающийся",
"incise" : "надрезать, делать надрез на",
"incision" : "разрез надрез, насечка",
"incisive" : "режущий, острый",
"incite" : "подстрекать [-кнуть], побуждать [-удить]",
"incitement" : "подстрекательство, побуждение стимул",
"inclement" : "суровый холодный",
"inclination" : "наклон откос, отклонение, наклонность, склонность",
"incline" : "склоняться [-ниться], склонять [-нить], располагать [-ложить], наклон, склонность; See also: incline to",
"incline to" : "быть склонным к",
"inclose" : "<-> enclose",
"include" : "заключать [-чить] содержать, включать [-чить]",
"inclusion" : "включение",
"inclusive" : "включающий в себя содержащий",
"incoherence" : "несвязность",
"incoherent" : "несвязный непоследовательный",
"incombustible" : "несгораемый",
"income" : "доход",
"incommensurable" : "несоизмеримый",
"incommensurate" : "несоразмерный",
"incommode" : "[по]беспокоить"
};
