var dicctr_63 = {
"поклонник" : "worshiper, admirer",
"поклоняться" : "worship, bow",
"поклясться" : "swear",
"поковырять" : "pick poke",
"покоиться" : "rest lie, be based",
"покой" : "rest, repose peace, calm, obsol. apartment, alone",
"покойник" : "the deceased, jur. decedent",
"покойница" : "the deceased, jur. decedent",
"покойницкая" : "mortuary",
"покойный" : "quiet, calm, easy, the late, su. = покойник покойница, cf. спокойный",
"поколебать" : "shake, -ся shake, fluctuate, waver vacillate hesitate, oscillate vibrate",
"поколение" : "generation",
"покончить" : "pf. finish, do away with, commit",
"покорение" : "conquest, subjugation",
"покоритель" : "conqueror",
"покорить" : "s. покорять",
"покормить" : "feed; See also: кормить грудью",
"покорность" : "submission obedience",
"покорный" : "obedient, humble submissive, покорно a. very much",
"покоробить" : "warp, fig. offend sicken",
"покорять" : "conquer subdue, -ся submit, resign o.s.",
"покос" : "mowing, meadow",
"покраснеть" : "redden grow #or turn red, blush, impf. be ashamed, appear show red",
"покривить" : "crook, twist; See also: кривить душой",
"покрикивать" : "shout",
"покров" : "cover, hearse cloth",
"покровитель" : "patron protector",
"покровительница" : "patroness protectress",
"покровительственный" : "patronizing, commerc. protective",
"покровительство" : "protection, patronage",
"покровительствовать" : "patronize, protect",
"покрой" : "cut, kind breed",
"покрошить" : "crumb, popul. crush",
"покрывало" : "coverlet, veil",
"покрывать" : "cover, coat, beat trump, popul. call #or run down, -ся cover o.s., be covered",
"покрытие" : "cover, coat, defrayal",
"покрытый" : "coated, covered, sheeted, wreathed",
"покрыть" : "cover, coat, trump, -ся impf. lie #or consist in, be at the bottom of",
"покрышка" : "cover, famil. lid",
"покупатель" : "buyer, customer",
"покупательница" : "buyer, customer",
"покупательный" : "purchasing",
"покупать" : "buy purchase",
"покупка" : "purchase, package, за покупками shopping",
"покупной" : "purchasing, purchase",
"покурить" : "smoke, distil",
"покуситься" : "attempt, encroach",
"покушать" : "eat, drink",
"покушаться" : "attempt, encroach",
"покушение" : "attempt",
"покушение на убийство" : "murderous assault",
"пол" : "flooring, sex",
"пол1" : "floor",
"пол2" : "sex",
"пол3" : "half",
"пола" : "skirt tail",
"полагать" : "put, decide, mus. set, impf. think suppose guess, fancy, надо полагать probably, положим что ... suppose let's assume that",
"полагаться" : "rely, полагается must, be due #or proper; See also: как полагается",
"поладить" : "get along #or on  a. make it up, manage, fix, tune, не ладить a. be at odds #or variance, out of keeping",
"полакомиться" : "enjoy relish  eat with delight, be fond of dainties",
"полдень" : "noon, cf. обед",
"полдневный" : "midday...",
"полдороги" : "s. полпути",
"полдюжины" : "half dozen",
"поле" : "field, ground, pl. margin",
"поле зрения" : "range of vision eyeshot, fig. horizon",
"полевой" : "field...",
"полевой бинокль" : "field glass",
"полевой суд" : "court martial",
"полезность" : "utility",
"полезные ископаемые" : "treasures of the soil",
"полезный" : "useful of use, helpful, wholesome, engin. effective, net",
"полезть" : "climb, creep, penetrate, famil. reach into, importune press, fall out, fit, popul. meddle",
"полемизировать" : "polemize",
"полемика" : "polemic",
"полемический" : "polemic",
"полено" : "log",
"полет" : "flight; See also: бреющий полет, слепой полет",
"полететь" : "fly",
"ползать" : "creep crawl",
"ползающий" : "creepy",
"ползком" : "on all fours",
"ползти" : "creep crawl",
"ползучее растение" : "creeper climber",
"ползучий" : "creeping, repent",
"поливать" : "water, pf. start raining",
"поливка" : "watering, flushing",
"полигон" : "range",
"полимер" : "polymer",
"полимерный" : "polymeric",
"полиморфный" : "polymorph",
"полинялый" : "faded",
"полинять" : "fade, molt",
"полиомиелит" : "polio, poliomyelitis",
"полировать" : "polish burnish",
"полировка" : "polish",
"полис" : "policy",
"полисмен" : "bobby, cop",
"политбюро" : "Politburo  Political Bureau",
"политграмота" : "political primer",
"политехникум" : "polytechnic",
"политехнический" : "polytechnic",
"политзаключенный" : "political prisoner",
"политик" : "politician",
"политика" : "policy, politics pl.",
"политикан" : "politico, wirepuller",
"политический" : "political",
"политический деятель" : "politician",
"политрук" : "political instructor",
"политура" : "polish",
"политучеба" : "political instruction",
"полить" : "water, pf. start raining",
"политэкономия" : "political economy economics",
"полифония" : "polyphony",
"полицейский" : "police",
"полиция" : "police",
"поличное" : "corpus delicti; See also: с поличным",
"полк" : "regiment",
"полка" : "shelf, pan",
"полковник" : "colonel",
"полководец" : "commander general",
"полковой" : "regimental",
"полная" : "buxom",
"полнейший" : "crass",
"полнеть" : "grow stout",
"полно" : "full to the brim, famil. okay all right, never mind, enough #or no more, stop quit !",
"полновесный" : "weighty",
"полновластный" : "absolute",
"полноводный" : "deep",
"полнозвучный" : "orotund, rotund",
"полнокровие" : "plethora",
"полнокровный" : "full-blooded, med. plethoric",
"полнолуние" : "full moon",
"полномочие" : "power",
"полномочный" : "plenipotentiary, cf. полпред",
"полноправный член" : "full member",
"полностью" : "completely entirely",
"полнота" : "fullness plenitude, completeness, corpulence",
"полноценный" : "full ..., fig. full-fledged",
"полночь" : "midnight",
"полный" : "full, complete absolute, perfect, stout, chubby",
"полным-полный" : "famil. full up packed",
"поло" : "polo",
"половая зрелость" : "puberty",
"половая тряпка" : "mop",
"половик" : "mat",
"половина" : "half, половина пятого, half past four, два с половиной two & a half",
"половинка" : "half, leaf",
"половинчатый" : "fig. vague evasive",
"половица" : "deal board",
"половодье" : "high water",
"половой" : "sexual",
"половой1" : "floor...",
"половой2" : "sexual",
"половые органы" : "genitals",
"полог" : "bed curtain",
"пологий" : "slightly sloping flat",
"положа руку на сердце" : "famil. frankly",
"положение" : "position location, situation, state condition, standing, regulations pl., thesis, в положении famil. in the family way",
"положительный" : "positive, affirmative",
"положить" : "put, decide, mus. set, impf. think suppose guess, fancy, надо полагать probably, положим что ... suppose let's assume that",
"полоз" : "runner",
"поломка" : "breakage",
"полонез" : "polonaise",
"полоний" : "polonium",
"полоса" : "stripe streak, strip, belt, zone, bar, field, period",
"полосатый" : "striped",
"полоска" : "facia, strap",
"полоскание" : "gargle, rinse, rinsing",
"полоскать" : "rinse, gargle",
"полоскаться" : "paddle, flap",
"полость" : "cavity",
"полотенце" : "towel; See also: мохнатое полотенце",
"полотнище" : "width",
"полотно" : "linen, bunting, rail. roadbed, embankment, blade",
"полотняный" : "linen...",
"полоть" : "weed",
"полпред" : "ambassador",
"полпредство" : "embassy (Sov. #till #194",
"полпути" : "halfway",
"полслова" : "half a word, word, на полслове short",
"полсотни" : "fifty",
"полтина" : "half ruble 50 kopecks",
"полтинник" : "half ruble 50 kopecks",
"полтора" : "one and a half",
"полтораста" : "a hundred and fifty",
"полторы" : "one and a half",
"полубайт" : "nibble",
"полубог" : "demigod",
"полуботинки" : "shoes",
"полувоенный" : "paramilitary",
"полугласный" : "semivowel",
"полугодие" : "half year six months",
"полугодичный" : "semiannual half-yearly",
"полугодовой" : "semiannual half-yearly",
"полуграмотный" : "semiliterate",
"полуденный" : "midday..., meridional",
"полуживой" : "halt dead",
"полузащитник" : "halfback",
"полукруг" : "semicircle",
"полумесяц" : "half moon crescent",
"полумрак" : "twilight semi-darkness",
"полуночный" : "midnight...",
"полуоборот" : "half-turn",
"полуостров" : "peninsula",
"полусвет" : "twilight, demimonde",
"полуспущенный" : "half-mast",
"полустанок" : "rail. stop substation",
"полутень" : "penumbra",
"полутьма" : "= полумрак",
"получатель" : "addressee recipient",
"получать" : "receive get, obtain, catch, have, -ся come in arrive, result, prove turn out",
"получение" : "receipt, getting",
"получить" : "receive get, obtain, catch, have, -ся come in arrive, result, prove turn out",
"получить отказ" : "be refused",
"получка" : "pay",
"полушарие" : "hemisphere",
"полушубок" : "short fur coat",
"полфунта" : "half pound",
"полцены" : "за полцены at half price",
"полый" : "cored, hollow",
"полынь" : "absinthe, sagebrush, tarragon",
"пользователь" : "client",
"пользоваться большим весом" : "enjoy great credit",
"полька" : "Pole, polka",
"польский" : "Polish",
"польстить" : "flatter",
"польша" : "Poland",
"полюбоваться" : "admire delight",
"полюбовный" : "amicable",
"полюс" : "pole, a. terminal",
"поля" : "weald",
"поляк" : "Pole",
"поляна" : "glade, meadow",
"поляриметр" : "polarimeter",
"полярный" : "polar",
"поляроид" : "polaroid",
"помада" : "pomade, stick",
"помазание" : "unction",
"помазать" : "anoint, s. мазать",
"помазывать" : "anoint, s. мазать",
"помаленьку" : "famil. so-so, little by little",
"помалкивать" : "keep silent",
"поманить" : "beckon, lure entice tempt",
"помарка" : "blot erasure",
"помахивание" : "waggle",
"помахивать" : "wag, flourish",
"поменять" : "exchange barter, change, -ся",
"померещиться" : "seem, appear, loom",
"померить" : "famil. try on"
};
