var dicctr_78 = {
"самовольный" : "arbitrary",
"самогон" : "home-brew",
"самодвижущийся" : "automobile",
"самодельный" : "homemade self-made",
"самодержавие" : "autocracy",
"самодержавный" : "autocratic",
"самодержец" : "autocrat, caesar",
"самодеятельность" : "amateur performance",
"самодовольный" : "self-satisfied self-complacent",
"самодур" : "despot",
"самое большее" : "famil. at most",
"самое малое" : "famil. at least",
"самозащита" : "self-defense",
"самозванец" : "impostor usurper, pseudo...",
"самокат" : "scooter",
"самокритика" : "self-criticism",
"самолет" : "airplane  aircraft; See also: пассажирский самолет",
"самолет-снаряд" : "guided missile",
"самолюбивый" : "ambitious, vain conceited",
"самолюбие" : "ambition, vanity",
"самомнение" : "self-conceit",
"самонадеянный" : "self-confident self-assertive",
"самообладание" : "self-control",
"самообман" : "self-deception",
"самооборона" : "self-defense",
"самообслуживание" : "self-service",
"самоопределение" : "self-determination",
"самоотверженный" : "self-denying self-sacrificing",
"самоочевидный" : "axiomatic",
"самопишущий" : "fountain",
"самопожертвование" : "self-sacrifice",
"самопроизвольность" : "spontaneity",
"самопроизвольный" : "spontaneous",
"самородный" : "native pure, original",
"самородок" : "nugget",
"самосохранение" : "self-preservation",
"самостоятельность" : "independence",
"самостоятельный" : "independent",
"самосуд" : "lynch law",
"самоубийство" : "suicide",
"самоубийца" : "suicide",
"самоуверенный" : "self-confident",
"самоуправление" : "self-government",
"самоучка" : "self-taught pers.",
"самохвальство" : "boasting",
"самоходный" : "self-propelled",
"самоцель" : "end in itself",
"самочувствие" : "health",
"сампан" : "sampan",
"самсон" : "samson",
"самуил" : "samuel",
"самый" : "the most ...est, the very, the same, just right, early #or late; See also: самое большее, самое малое",
"сан" : "dignity",
"санаторий" : "sanatorium",
"сандалии" : "sandals",
"сандалия" : "sandal",
"сани" : "sled",
"санитар" : "nurse, a. hospital attendant orderly",
"санитарка" : "nurse",
"санитарный" : "sanitary",
"санкционировать" : "pf. sanction",
"санкция" : "sanction",
"сановник" : "dignitary",
"сановный" : "dignitary",
"санскритский" : "sanskrit",
"сантиметр" : "centimeter",
"сапер" : "engineer Brt. sapper",
"саперный" : "pioneer",
"сапог" : "boot",
"сапожник" : "shoemaker",
"сарай" : "shed, barn",
"саранча" : "locust",
"сарафан" : "sarafan",
"сарацин" : "saracen",
"сарделька" : "wiener",
"сардина" : "sardine",
"сардинка" : "sardine",
"саржа" : "serge",
"сарказм" : "sarcasm",
"саркастический" : "sarcastic",
"саркома" : "sarcoma",
"саркофаг" : "sarcophagus",
"сассафрас" : "sassafras",
"сатана" : "Satan",
"сатанический" : "satanic",
"сателлит" : "satellite",
"сатин" : "sateen glazed cotton",
"сатир" : "satyr",
"сатира" : "satire",
"сатирик" : "satirist",
"сатирический" : "satirical",
"сатурн" : "saturn",
"сафари" : "safari",
"сафьян" : "morocco",
"сафьяновый" : "morocco",
"сахар" : "sugar",
"сахаристый" : "sugary",
"сахарная болезнь" : "diabetes",
"сахарная пудра" : "powdered sugar",
"сахарница" : "sugar bowl",
"сахарный" : "sugar...",
"сачок" : "butterfly net",
"саша" : "dim. #of Александр -а",
"сашенька" : "dim. #of Александр -а",
"сбавить" : "s. сбавлять",
"сбавка" : "reduction",
"сбавлять" : "reduce",
"сбегать1" : "run down, pf. run away escape flee",
"сбегать2" : "pf. run",
"сбегаться" : "come running",
"сбежать" : "run down, pf. run away escape flee",
"сбежаться" : "come running",
"сберегательный" : "savings ...",
"сберегать" : "save, preserve",
"сбережение" : "saving, preservation",
"сберечь" : "save, preserve",
"сберкасса" : "savings bank",
"сбивать" : "knock down, overthrow, shoot down, whip  beat up  churn, mix, lead, confus #or puzzl, a. run o.s. off, flock",
"сбивчивый" : "confused, uneven",
"сбить" : "knock down, overthrow, shoot down, whip  beat up  churn, mix, lead, confus #or puzzl, a. run o.s. off, flock",
"сближать" : "bring #or draw together",
"сближаться" : "become friends",
"сближающийся" : "convergent",
"сближение" : "rapprochement, approach",
"сблизить" : "bring #or draw together",
"сблизиться" : "become friends",
"сбоку" : "sideways, next to it",
"сболтнуть" : "blurt",
"сбор" : "collection, gathering, harvest, levy, tax, duty, receipts pl., milit. muster, pl. preparations, milit. сборе assembled",
"сборище" : "concourse crowd",
"сборка" : "pleat tuck, engin. assemblage",
"сборник" : "collection, symposium",
"сборный" : "milit. assembly, #sport: select",
"сборочный" : "assembling",
"сборщик" : "collector",
"сбрасывать" : "throw off drop shed, discard",
"сброд" : "rabble riff-raff",
"сбросить" : "throw off drop shed, discard",
"сброшюровать" : "stitch",
"сбруя" : "harness",
"сбывать" : "sell market, get rid of, fall",
"сбываться" : "come true",
"сбыт" : "sale",
"сбыть" : "sell market, get rid of, fall",
"свадебный" : "wedding",
"свадьба" : "wedding",
"сваленный" : "felled",
"сваливать" : "knock down overthrow, fell, dump, heap up, shift",
"сваливаться" : "fall down",
"свалить" : "overturn tumble  fell, heap  dump, flock throng, снег валит it is snowing heavily",
"свалиться" : "fall down",
"свалка" : "dump, brawl",
"сваривать" : "weld",
"сварить" : "cook boil, brew, digest",
"сварка" : "welding",
"сварливый" : "quarrelsome",
"сварочный" : "welding",
"свастика" : "swastika",
"сват" : "matchmaker",
"сватать" : "seek in marriage",
"сваха" : "matchmaker",
"свая" : "pile",
"сведение" : "information, принять к сведению take notice",
"сведущий" : "expert versed",
"свежесть" : "freshness",
"свежеть" : "freshen become fresh",
"свежий" : "fresh, cool, latest, new",
"свезти" : "drive  transport, pull, ему везет famil. he is lucky",
"свекла" : "beet",
"свекор" : "father-in-law",
"свекровь" : "mother-in-law",
"свергать" : "overthrow, dethrone, shake off",
"свергнуть" : "overthrow, dethrone, shake off",
"свержение" : "overthrow",
"сверить" : "s. сверять",
"сверкание" : "glisten",
"сверкать" : "sparkle glitter, flash, молния сверкает it lightens",
"сверкнуть" : "sparkle glitter, flash, молния сверкает it lightens",
"сверление" : "drilling",
"сверлильный" : "drilling",
"сверлить" : "drill",
"сверло" : "drill",
"свернутый" : "convolute",
"свернуть" : "& сворачивать",
"сверстать" : "typ. make up",
"сверстник" : "s. ровесник",
"сверток" : "roll, parcel",
"свертывание" : "clotting, furl",
"свертывать" : "roll, turn, curtail, break up, twist",
"свертываться" : "coil up, curdle, coagulate",
"сверх" : "above beyond, over, besides; See also: сверх того",
"сверх того" : "moreover",
"сверхзвуковой" : "supersonic",
"сверхприбыль" : "surplus profit",
"сверху" : "from above",
"сверхурочный" : "overtime",
"сверхштатный" : "supernumerary",
"сверхьестественный" : "supernatural",
"сверчок" : "zo. cricket",
"свершить" : "solve decide, direct, accomplish",
"сверять" : "compare collate",
"свесить" : "s. свешивать",
"свеситься" : "hang over",
"свести" : "s. сводить",
"светило" : "luminary",
"светло-зеленый" : "chlorine",
"светло-коричневый" : "hazel",
"светлый" : "light",
"светляк" : "firebug",
"световой" : "photic",
"светокопия" : "blueprint",
"светский" : "secular worldly, of high society",
"светящийся" : "luminous",
"свеча" : "candle, el. plug",
"свешивать" : "hang down, dangle",
"свешиваться" : "hang over",
"свивать" : "braid plait, build",
"свидание" : "appointment meeting; See also: до свидания",
"свидетель" : "witness",
"свидетельница" : "witness",
"свидетельство" : "evidence, certificate, licence",
"свидетельствовать" : "testify, impf. show",
"свинарник" : "pigsty",
"свинец" : "lead",
"свинина" : "pork",
"свинка" : "mumps, морская свинка guinea pig",
"свиной" : "pig..., pork...",
"свиноподобный" : "hoggish, piggish",
"свинство" : "dirty #or rotten act smut",
"свинтить" : "screw together fasten with screws",
"свинцовый" : "lead",
"свинчивать" : "screw together fasten with screws",
"свинья" : "pig hog swine",
"свирель" : "pipe reed",
"свирепость" : "ferocity, truculence",
"свирепствовать" : "rage",
"свирепый" : "fierce furious grim",
"свисать" : "hang down, slouch",
"свист" : "whistle, hiss",
"свистать" : "whistle, popul. pilfer",
"свистеть" : "whistle, popul. pilfer",
"свистнуть" : "whistle, popul. pilfer",
"свисток" : "whistle",
"свистящий" : "sibilant, stridulous, whistling",
"свита" : "retinue suite",
"свитер" : "sweater",
"свиток" : "roll",
"свить" : "wind twist, build",
"свихнуть" : "pf. sprain",
"свихнуться" : "go mad"
};
