var dicctr_64 = {
"помериться" : "cope try conclusions with",
"померкнуть" : "fade darken",
"поместительный" : "spacious",
"поместить" : "s. помещать",
"помеха" : "handicap, hindrance, hitch, marplot, trammel",
"помечать" : "mark note",
"помешанный" : "crazy, mad",
"помешательство" : "insanity",
"помешать" : "s. мешать",
"помешаться" : "pf. go mad, famil. be mad",
"помещать" : "place, lodge accommodate, settle, invest, insert publish, -ся settle  locate, lodge, find room, hold, be placed #or invested, impf. be",
"помещение" : "lodgment premise room, investment",
"помещик" : "landowner landlord",
"помидор" : "tomato",
"помилование" : "pf. pardon, помилуй! for goodness' sake, good gracious, помилуй бог! God forbid, господи помилуй! God have mercy upon us",
"помиловать" : "pf. pardon, помилуй! for goodness' sake, good gracious, помилуй бог! God forbid, господи помилуй! God have mercy upon us",
"помимо" : "besides, in spite of; See also: помимо него",
"помимо него" : "without his knowledge",
"помин" : "mention",
"поминать" : "recollect remember, speak about mention, pray for, commemorate, поминай как звали off and away, не поминать лихом, bear no ill will",
"поминки" : "commemoration",
"поминутно" : "every minute, constantly",
"помирить" : "reconcile, -ся make it up be reconciled",
"помнить" : "remember recollect think of, мне помнится I remember",
"помножить" : "s. умножать",
"помогать" : "help, aid assist, avail",
"помои" : "slops",
"помойный" : "slop garbage dust",
"помол" : "grind",
"помолвить" : "pf. affiance",
"помолвка" : "betrothal engagement",
"помолиться" : "pray",
"помолодеть" : "grow younger",
"помост" : "dais, rostrum, scaffold",
"помочи" : "leading strings, = подтяжки",
"помочь" : "help, aid assist, avail",
"помощник" : "assistant, deputy, helper aid",
"помощница" : "assistant, deputy, helper aid",
"помощь" : "help aid assistance, med. treatment, relief, карета скорой помощи ambulance",
"помпа" : "pomp, engin. pump",
"помпезный" : "pompous",
"помпон" : "pompon",
"помрачать" : "s. омрачать",
"помрачнеть" : "darken",
"помутить" : "trouble muddle, fog, меня мутит famil. I feel sick",
"помутнение" : "turbidity",
"помутнеть" : "grow turbid, blur",
"помчать" : "rush whirl #or speed",
"по-настоящему" : "properly",
"по-нашему" : "in our way #or opinion #or language",
"понедельник" : "monday",
"понемножку" : "little, little by little gradually, a. so-so",
"понести" : "carry, bear, bring, suffer, do, drift waft speed, снести lay, famil. talk, smell; See also: несет",
"пони" : "nag",
"понижать" : "lower reduce",
"понижение" : "fall, reduction, decrease, degradation",
"понизить" : "lower reduce",
"поникать" : "hang, droop, wilt",
"поникнуть" : "hang, droop, wilt",
"понимание" : "comprehension understanding, conception",
"понимать" : "understand comprehend see, realize, appreciate",
"понимаю" : "I see",
"пономарь" : "sexton",
"понос" : "diarrhea",
"поносить" : "abuse",
"поношение" : "abuse",
"поношенный" : "worn shabby",
"понравиться" : "please, он мне нравится I like him",
"понтификат" : "pontificate",
"понтон" : "pontoon",
"понтонный" : "pontoon",
"понудить" : "force compel",
"понуждать" : "force compel",
"понуждение" : "compulsion",
"понукать" : "urge on spur",
"понурить" : "hang",
"понурый" : "downcast",
"пончик" : "doughnut",
"пончо" : "poncho",
"поныне" : "until now",
"понюхать" : "smell, scent, snuff",
"понятие" : "idea notion, concept, comprehension",
"понятливый" : "quick-witted bright",
"понятный" : "intelligible, understandable, clear plain, понятно famil. = конечно",
"понять" : "understand comprehend see, realize, appreciate",
"пообедать" : "have dinner  dine",
"поодаль" : "at some distance",
"поодиночке" : "one by one",
"поочередный" : "alternate",
"поощрение" : "encouragement",
"поощрить" : "encourage",
"поощрять" : "encourage",
"поп" : "priest",
"попадание" : "hit",
"попадать" : "get come  fall find o.s., hit, catch, become, famil. get it; See also: не попасть, как попало, кому попало, первому попавшемуся",
"попадаться" : "be caught, fall, famil. come across chance on meet, occur there is, strike (a Д на глаза, не попадаться be out of a pers.'s sight)",
"попадья" : "priest's wife",
"попарно" : "by pairs in couples",
"попасть" : "get come  fall find o.s., hit, catch, become, famil. get it; See also: не попасть, как попало, кому попало, первому попавшемуся",
"попасть в засаду" : "be ambushed",
"попасть в плен" : "be taken prisoner",
"попенять" : "blame",
"поперек" : "across crosswise, in",
"попеременно" : "by turns",
"поперечный" : "transverse transversal, cross...",
"попечение" : "care charge",
"попечитель" : "curator trustee",
"попирать" : "trample",
"попка" : "parrot",
"поплавок" : "float",
"поплатиться" : "fig. pay",
"поплин" : "poplin",
"попойка" : "booze",
"пополам" : "in half, half & half, fifty-fifty",
"поползень" : "nuthatch",
"поползновение" : "mind, pretension",
"пополнеть" : "grow stout",
"пополнить" : "replenish supplement, enrich, reman reinforce",
"пополнять" : "replenish supplement, enrich, reman reinforce",
"пополудни" : "in the afternoon p.m.",
"попона" : "horsecloth",
"попотчевать" : "famil. = угощать",
"поправимый" : "remediable, reparable",
"поправить" : "s. поправлять",
"поправлять" : "renovate",
"попранный" : "downtrodden",
"по-прежнему" : "as before",
"попрекать" : "reproach",
"попрекнуть" : "reproach",
"поприще" : "field",
"попробовать" : "try, taste",
"попросить" : "ask  request, entreat, invite, intercede, прошу просят a. please",
"попросту" : "plainly unceremoniously, downright",
"попрошайка" : "beggar",
"попугай" : "parrot",
"популярность" : "popularity",
"популярный" : "popular",
"попурри" : "pastiche",
"попустительство" : "connivance",
"попустому" : "famil. in vain to no purpose",
"попусту" : "famil. in vain to no purpose",
"попутный" : "fair favorable, passing incidental",
"попутный ветер" : "fair wind",
"попутчик" : "fellow traveler",
"попытать" : "pf. try",
"попытаться" : "try attempt",
"попытка" : "attempt",
"попятиться" : "back",
"пора1" : "time, season, weather, period, famil. prime, пора it's time, в пору in the nick of time, до поры до времени not last forever, #wait for one's opportunity, до каких пор? how long ?; See also: до сих пор, до тех пор, с тех пор, с тех пор как, на первых порах",
"пора2" : "pore",
"поработить" : "enslave subjugate",
"порабощать" : "enslave subjugate",
"поравняться" : "pf. overtake",
"порадовать" : "gladden please rejoice, -ся rejoice  be glad #or pleased, look forward",
"поражать" : "strike, defeat",
"пораженец" : "defeatist",
"поражение" : "defeat, med. affection, jur. deprivation, striking",
"пораженный" : "stricken",
"пораженчество" : "defeatism",
"поразительный" : "striking",
"поразить" : "strike, defeat",
"поранить" : "pf. wound cut",
"порвать" : "s. порывать",
"пористость" : "porosity",
"пористый" : "honeycombed, mushy, poriferous, porous, spongy",
"порицание" : "animadversion, reprehension",
"порка" : "flogging, lashing",
"порнография" : "porn, pornography",
"порог" : "sill, threshold",
"порода" : "breed",
"породистый" : "highbred",
"порождать" : "generate, procreate",
"порознь" : "asunder",
"поросенок" : "young pig",
"пороть" : "распороть undo unpick, famil. talk, famil. выпороть whip flog",
"порох" : "gunpowder",
"пороховой" : "powder...",
"порочить" : "discredit, defile",
"порочный" : "vicious",
"порошкообразный" : "powdery",
"порошок" : "powder",
"порт" : "port, harbor",
"портальный" : "gantry, portal",
"портативный" : "portable",
"портик" : "portico",
"портить" : "spoil",
"портландцемент" : "portland",
"портниха" : "dressmaker",
"портной" : "tailor",
"портовик" : "longshoreman a. docker",
"портовый" : "port... dock...",
"портовый город" : "seaport",
"портретный" : "iconic",
"портсигар" : "cigar case",
"портсмут" : "portsmouth",
"португалец" : "Portuguese",
"португалия" : "Portugal",
"португалка" : "Portuguese",
"португальский" : "Portuguese",
"портулак" : "purslane",
"портупея" : "sword knot",
"портфель" : "brief case, portfolio",
"портьера" : "drape",
"портянка" : "foot wrap",
"портящийся" : "corruptible",
"поругание" : "abuse affront",
"порука" : "bail  security, guarantee, responsibility",
"поручать" : "charge, commission bid tell, entrust",
"поручение" : "commission, instruction, message, mission, order",
"поручень" : "handhold",
"поручик" : "lieutenant",
"поручитель" : "bail surety",
"поручительство" : "affidavit, guarantee",
"поручить" : "charge, commission bid tell, entrust",
"поручиться" : "warrant guarantee vouch for",
"порфир" : "porphyry",
"порхать" : "flit",
"порхнуть" : "flit",
"порция" : "portion helping",
"порча" : "spoiling spoilage, damage",
"поршень" : "piston",
"порыв" : "gust squall, fit outburst, impulse",
"порывать" : "tear, break, -ся, impf. jerk, strive, a. рвать",
"порывистый" : "gusty, jerky, impulsive",
"порядковый" : "current, gr. ordinal",
"порядком" : "famil. rather, properly",
"порядок" : "order, way  form, course, pl. conditions, kind; See also: порядок дня, по порядку",
"порядок дня" : "agenda",
"порядочный" : "orderly decent, fair",
"посадить" : "& садить",
"посадка" : "planting, embarkation boarding, av. landing alighting",
"посадочный" : "landing...",
"посватать" : "seek in marriage",
"посвежеть" : "freshen become fresh",
"посветлеть" : "brighten, grow light",
"по-своему" : "in one's own way",
"посвятить" : "devote, dedicate, initiate, ordain, knight",
"посвящать" : "devote, dedicate, initiate, ordain, knight",
"посвящение" : "dedication, initiation",
"посев" : "sowing, crop",
"посевной" : "sowing",
"поседелый" : "gray Brt. grey",
"поседеть" : "turn gray",
"поселенец" : "settler",
"поселение" : "colony",
"поселить" : "settle, inspire",
"поселять" : "settle, inspire",
"посеребрить" : "silver",
"посередине" : "in the middle #or midst",
"посереть" : "turn gray"
};
