var dicct_0 = {
"a" : "неопределенный артикль, как правило не переводится, первоклассный, прекрасно; See also: a table",
"a bad break" : "неудача",
"a coat in velvet" : "бархатное пальто",
"a dead shot" : "стрелок не дающий промаха",
"a few" : "несколько",
"a good deal" : "весьма много",
"a good hand at" : "искусный в",
"a good many" : "порядочное количество",
"a great deal" : "очень много",
"a great many" : "громадное количество",
"a house of one's own" : "собственный дом",
"a little" : "немного",
"a little one" : "малыш",
"a man of mark" : "выдающийся человек",
"a man of parts" : "способный человек",
"a minor" : "ля минор",
"a mint of money" : "большая сумма",
"a novel in english" : "роман на английском языке",
"a pair of clippers" : "ножницы, секатор, клиппер",
"a pair of compasses" : "циркуль",
"a pair of drawers" : "кальсоны",
"a pair of eye-glasses" : "очки, лорнет",
"a pair of glasses" : "очки",
"a pair of goggles" : "защитные очки",
"a pair of lungs" : "легкие",
"a pair of nippers" : "щипцы",
"a pair of scales" : "весы",
"a pair of scissors" : "ножницы",
"a poor hand at" : "неискусный в",
"a solid hour" : "целый час",
"a sprinkling" : "немного",
"a table" : "стол, десять рублей дюжина",
"a trifle" : "немножко",
"a world of" : "множество куча",
"a year ago" : "год тому назад",
"a year hence" : "через год",
"a.s." : "(сокр. от Anglo-Saxon) англо-саксонский",
"aaas" : "(сокр. от American Association for Advancement of Science) Американская ассоциация содействия развитию науки",
"aback" : "назад",
"abacus" : "счеты",
"abandon" : "отказываться [-заться] от, оставлять [-авить] покидать [-инуть]",
"abandoned" : "покинутый, распутный",
"abandonment" : "оставление",
"abase" : "унижать [унизить]",
"abasement" : "унижение",
"abash" : "смущать [смутить]",
"abashment" : "смущение",
"abate" : "уменьшать [-еньшить], утихать [утихнуть]",
"abatement" : "уменьшение, скидка",
"abattoir" : "скотобойня",
"abbess" : "настоятельница монастыря",
"abbey" : "монастырь",
"abbot" : "аббат настоятель",
"abbreviate" : "сокращать [-ратить]",
"abbreviation" : "сокращение",
"abc" : "простой",
"abdicate" : "отрекаться от престола, отказываться [-заться] от",
"abdication" : "отречение от престола",
"abdomen" : "живот, брюшная полость",
"abdominal" : "a  1) абдоминальный, брюшной;  abdominal cavity брюшная полость;  abdominal operation полостная операция  2) брюхопёрый (о рыбах)",
"abduct" : "похищать [-итить]",
"abed" : "в постели",
"abel" : "авель",
"aberrant" : "заблуждающийся",
"aberration" : "заблуждение; See also: аберрация",
"abet" : "подстрекать [-кнуть], [по]содействовать",
"abetted" : "See: abet",
"abetting" : "See: abet",
"abettor" : "подстрекатель",
"abeyance" : "состояние неизвестности; See also: in abeyance",
"abhor" : "ненавидеть",
"abhorred" : "See: abhor",
"abhorrence" : "отвращение",
"abhorrent" : "отвратительный",
"abide" : "пребывать, not abide; See also: abide by",
"abide by" : "твердо держаться",
"ability" : "способность",
"abject" : "презренный жалкий",
"abjure" : "отрекаться [-ечься] от",
"ablaze" : "возбужденный",
"able" : "способный; See also: be able",
"able-bodied" : "здоровый, годный",
"ablution" : "промывка",
"abnegate" : "отказывать [-зать] себе в, отрицать",
"abnegation" : "отрицание, отречение",
"abnormal" : "ненормальный",
"aboard" : "на корабль на корабле",
"abode" : "от abide, местопребывание, жилище",
"abolish" : "отменять [-нить], упразднять [-нить]",
"abolition" : "отмена",
"abominable" : "отвратительный",
"abominate" : "питать отвращение к",
"abomination" : "отвращение",
"aboriginal" : "туземный, туземец",
"aborigine" : "= aboriginal 2",
"abort" : "выкидыш",
"abortion" : "выкидыш аборт",
"abound" : "изобиловать",
"about" : "вокруг, около, о  об  обо  насчет, у, про, вокруг везде, приблизительно; See also: I had no money about me, be about to do",
"above" : "над, выше, свыше, наверху наверх, выше, вышесказанный; See also: above all",
"above all" : "главным образом",
"aboveboard" : "1. a predic. честный, открытый, прямой 2. adv честно, открыто",
"aboveground" : "1. a  1) живущий  2) наземный 2. adv в живых",
"abovementioned" : "a  вышеупомянутый",
"abrade" : "шлифовать",
"abrasion" : "ссадина",
"abrasive" : "обдирающий",
"abreast" : "в ряд",
"abridge" : "сокращать [-ратить]",
"abridgement" : "сокращение",
"abridgment" : "сокращение",
"abroad" : "за границей за границу; See also: there is a report abroad",
"abrogate" : "отменять [-нить], аннулировать",
"abrupt" : "обрывистый, внезапный, резкий",
"abscess" : "нарыв",
"abscissa" : "n (pl -s , -ae)  мат. абсцисса",
"abscissae" : "See: abscissa",
"abscond" : "скрыться",
"absence" : "отсутствие, отлучка; See also: absence of mind",
"absence of mind" : "рассеянность",
"absent" : "отсутствующий; See also: absent self",
"absent self" : "отлучаться [-читься]",
"absent-minded" : "рассеянный",
"absentee" : "отсутствующий",
"absenteeism" : "невыход на работу",
"absentia" : "лат. n:  in absentia в отсутствие; заочно;  to be tried in absentia юр. быть судимым заочно",
"absentminded" : "a  рассеянный",
"absinthe" : "полынь",
"absolute" : "абсолютный, беспримерный",
"absolution" : "отпущение грехов",
"absolve" : "прощать [простить], освобождать [-бодить]",
"absorb" : "впитывать [впитать], абсорбировать",
"absorbent" : "поглощающий",
"absorption" : "всасывание впитывание, погруженность",
"absorptive" : "a  впитывающий, всасывающий; поглощающий;  absorptive power поглотительная (или абсорбирующая) способность",
"abstain" : "воздерживаться [-жаться]",
"abstemious" : "воздержанный умеренный",
"abstention" : "воздержание",
"abstinence" : "умеренность, трезвость",
"abstinent" : "умеренный воздержанный непьющий",
"abstract" : "отвлеченный абстрактный, конспект, извлечение, отвлеченное имя существительное, отвлекать [-ечь], резюмировать",
"abstracted" : "отвлеченный",
"abstraction" : "абстракция",
"abstruse" : "непонятный темный",
"absurd" : "нелепый",
"abundance" : "избыток изобилие",
"abundant" : "обильный богатый",
"abuse" : "злоупотребление, оскорбление, брань, злоупотреблять [-бить], [вы]ругать",
"abusive" : "оскорбительный",
"abut" : "граничить",
"abutted" : "See: abut",
"abutting" : "примыкающий",
"abysmal" : "бездонный",
"abyss" : "бездна",
"ac," : "ac (сокр. от alternating current) переменный ток",
"academic" : "академический",
"academical" : "академический",
"academician" : "академик",
"academy" : "академия",
"acanthus" : "n (pl -ses , -thi)  1) бот. акант, медвежья лапа  2) архит. акант (орнамент)",
"accede" : "соглашаться",
"accede to" : "вступать [-пить] в",
"accelerate" : "ускорять [-орить]",
"accelerator" : "ускоритель",
"accent" : "ударение, произношение акцент, делать или ставить ударение на",
"accentual" : "относящийся к ударению",
"accentuate" : "делать или ставить ударение на, подчеркивать [-черкнуть]",
"accept" : "принимать [-нять], соглашаться [-гласиться] с",
"acceptable" : "приемлемый, приятный",
"acceptance" : "прием принятие, акцепт",
"acceptor" : "n  ком. акцептант",
"access" : "доступ, проход; See also: приступ, easy of access",
"accessary" : "соучастник",
"accessible" : "доступный достижимый",
"accession" : "вступление, доступ; See also: accession to the throne",
"accession to the throne" : "вступление на престол",
"accessory" : " добавочный второстепенный, принадлежности",
"accident" : "случайность, катастрофа авария",
"accidental" : "случайный",
"acclaim" : "шумно приветствовать, аплодировать",
"acclamation" : "шумное одобрение",
"acclimate" : "акклиматизация",
"acclimatize" : "акклиматизировать",
"acclivity" : "подЙем",
"accolade" : "n  1) знак одобрения или почтения  2) восторженная похвала  3) ист. акколада (обряд посвящения в рыцари)  4) муз. акколада",
"accommodate" : "приспособлять [-пособить], давать жилье",
"accommodation" : "приют, помещение",
"accompaniment" : "аккомпанемент, сопровождение",
"accompanist" : "n  аккомпаниатор",
"accompany" : "аккомпанировать, сопровождать [-водить]",
"accomplice" : "соучастник",
"accomplish" : "выполнять [выполнить], достигать [-игнуть]",
"accomplishment" : "выполнение, достижение",
"accomplishments" : "образованность",
"accord" : "соглашение, гармония, согласовываться [-соваться], гармонировать, представлять [-ставить]; See also: with one accord",
"accordance" : "согласие",
"accordant" : "согласный",
"according to" : "согласно",
"accordingly" : "соответственно, таким образом",
"accordion" : "гармонь",
"accost" : "заговаривать [-ворить] с",
"account" : "счет, отчет, отвечать [-етить] за, обьяснять [-нить], считать [счесть]; See also: of no account, on no account, on account of, take into account, take account of, turn to account, call to account, make account of, account for, be much accounted of",
"account for" : "иметь хорошую репутацию",
"accountable" : "обЙяснимый",
"accountant" : "счетовод; See also: certified public accountant",
"accounting" : "отчетность, учет",
"accra" : "геогр. Аккра",
"accredit" : "аккредитовать, приписывать [-сать]",
"accretion" : "прирост",
"accrue" : "накопляться [-питься], происходить [произойти]",
"accumulate" : "накапливать [-копить], скоплять [-пить]",
"accumulation" : "накопление, скопление",
"accuracy" : "точность, тщательность",
"accurate" : "[-rit] точный, тщательный",
"accursed" : "проклятый",
"accurst" : "проклятый",
"accusation" : "обвинение",
"accusative" : "грам.  1. a винительный 2. n аккузатив, винительный падеж",
"accusatory" : "обвинительный",
"accuse" : "обвинять [-нить]",
"accuser" : "обвинитель",
"accustom" : "приучать [-чить]; See also: get accustomed",
"accustomed" : "привычный, приученный",
"ace" : "туз, первоклассный летчик",
"acerbic" : "a  1) кислый, терпкий  2) резкий, неприятный (о человеке, манере)",
"acerbity" : "терпкость",
"acetate" : "n  хим.  1) соль уксусной кислоты, ацетат  2) attr. ацетатный;  acetate silk ацетатный, искусственный шёлк",
"acetic" : "уксусный",
"acetify" : "окислять [-лить]",
"acetone" : "ацетон",
"acetylene" : "ацетилен",
"ache" : "боль, болеть",
"achieve" : "достигать [-игнуть]",
"achievement" : "достижение",
"achilles" : "n  греч. миф. Ахиллес",
"aching" : "See: ache",
"achromatic" : "бесцветный",
"acid" : "кислый, едкий",
"acidic" : "кислотный",
"acidity" : "кислота, едкость",
"acidulous" : "кисловатый",
"acknowledge" : "подтверждать [-ердить], признать",
"acknowledgement" : "признание, расписка",
"acknowledgment" : "признание, расписка",
"acme" : "высшая точка, кризис",
"acolyte" : "служитель",
"acorn" : "желудь",
"acoustic" : "слуховой",
"acoustics" : "акустика",
"acquaint" : "[по]знакомить; See also: be acquainted with",
"acquaintance" : "знакомство, знакомый",
"acquiesce" : "молча или неохотно соглашаться",
"acquiescement" : "молчаливое или неохотное согласие",
"acquiescent" : "уступчивый",
"acquire" : "приобретать [-ести], достигать [-игнуть]",
"acquirement" : "приобретение",
"acquisition" : "приобретение",
"acquisitive" : "восприимчивый",
"acquit" : "оправдывать [-дать]; See also: acquit of, acquit self well",
"acquit of" : "освобождать [-бодить] от, выполнять [выполнить]",
"acquit self well" : "хорошо справляться с работой",
"acquittal" : "оправдание"
};
