var dicct_61 = {
"on call" : "по требованию",
"on end" : "стоймя, дыбом, беспрерывно подряд",
"on foot" : "пешком, в ходу",
"on good authority" : "из достоверного источника",
"on hand" : "имеющийся в продаже в распоряжении",
"on hearing it" : "услышав это",
"on his arrival" : "по его прибытии",
"on horseback" : "верхом",
"on loan" : "взаймы",
"on no account" : "ни в коем случае",
"on no consideration" : "ни под каким видом",
"on pain of" : "под страхом",
"on principle" : "из принципа",
"on purpose" : "нарочно",
"on record" : "зарегистрированный",
"on second thoughts" : "по зрелом размышлении",
"on shipboard" : "на корабле",
"on shore" : "на берег на берегу, подпорка",
"on the 10th instant" : "10-го текущего месяца",
"on the 1st of april" : "первого апреля",
"on the alert" : "настороже",
"on the authority of" : "на основании, по утверждению",
"on the behoof of" : "в пользу  за",
"on the contrary" : "наоборот",
"on the eve of" : "накануне",
"on the face of it" : "с первого взгляда",
"on the go" : "на ходу, на ногах",
"on the ground of" : "на основании",
"on the grounds of" : "на основании",
"on the level" : "честно правдиво",
"on the mend" : "на поправку",
"on the move" : "на ходу",
"on the occasion of" : "по случаю",
"on the one hand" : "с одной стороны",
"on the other hand" : "с другой стороны",
"on the part of" : "со стороны",
"on the plea" : "под предлогом",
"on the right" : "направо",
"on the score of" : "по причине",
"on the shelf" : "сданный в архив",
"on the sly" : "тайком",
"on the spot" : "на месте, сразу немедленно",
"on the strength of" : "в силу, на основании",
"on the verge of" : "на грани",
"on the wall" : "на стене",
"on the way" : "в пути, по дороге",
"on the whole" : "в целом, в общем",
"on the wing" : "на лету",
"on the wireless" : "по радио",
"on this model" : "по этому образцу",
"on time" : "вовремя",
"on tiptoe" : "на цыпочках",
"on top" : "наверху",
"on trial" : "на испытании на испытание, под судом",
"on trust" : "в кредит, на веру",
"on view" : "для обозрения",
"once" : "раз, некогда когда-то, как только; See also: at once, once for all, once in a while, this once",
"once for all" : "раз навсегда",
"once in a while" : "изредка",
"once more" : "еще раз",
"oncology" : "онкология",
"oncoming" : "надвигающийся",
"one" : "один, единый, единственный, какой-то, один, единица; See also: one day, one never knows, the little ones, one another, at one, one by ~, I for one",
"one another" : "друг друга",
"one by ~" : "один за другим",
"one day" : "однажды",
"one never knows" : "никогда не знаешь",
"one-sided" : "односторонний",
"one-way" : "one-way street",
"one-way street" : "улица одностороннего движения",
"onerous" : "обременительный",
"oneself" : "-ся -сь себя",
"onetime" : "бывший",
"ongoings" : "= goings-on",
"onion" : "лук луковица",
"onlooker" : "зритель, наблюдатель",
"only" : "единственный, единственно, только, исключительно, но; See also: only yesterday, only that",
"only that" : "если бы не то что ...",
"only yesterday" : "только вчера",
"onomatopoeia" : "n  лингв. звукоподражание, ономатопея (напр., cuckoo, buzz)",
"onomatopoeic" : "a  звукоподражательный",
"onrush" : "натиск",
"onset" : "атака натиск нападение",
"onslaught" : "атака натиск нападение",
"onto" : "на",
"ontogeny" : "онтогенез",
"ontology" : "онтология",
"onus" : "ответственность",
"onward" : "продвигающийся вперед, вперед, впереди",
"onyx" : "оникс",
"oodles" : "огромное количество",
"ooze" : "ил тина, просачиваться [-сочиться]; See also: ooze away",
"ooze away" : "убыть",
"opacity" : "затененность",
"opal" : "опал",
"opalescent" : "опаловый",
"opaque" : "непрозрачный",
"open" : "открытый, откровенный, явный, открыть, начать, открыться, начаться; See also: open to, in the open air, bring into the open, open into, open on to",
"open into" : "открыться в",
"open on to" : "выходить на",
"open to" : "доступный",
"open-handed" : "щедрый",
"open-minded" : "непредубежденный",
"opening" : "отверстие, начало, открытие",
"opera" : "опера",
"opera-glass" : "бинокль",
"operable" : "действующий",
"operand" : "операнд",
"operate" : "управлять, Am приводить в действие, оперировать, оказывать влияние, работать, действовать",
"operatic" : "оперный",
"operation" : "действие, операция, процесс; See also: be in operation",
"operative" : "действующий, действительный, оперативный, рабочий",
"operator" : "оператор, телеграфист",
"operetta" : "оперетта",
"ophthalmic" : "глазной",
"ophthalmology" : "офтальмология",
"opiate" : "содержащий опиум",
"opine" : "высказывать мнение",
"opinion" : "мнение, взгляд; See also: in my ~",
"opium" : "опиум",
"opossum" : "опоссум",
"opponent" : "оппонент противник",
"opportune" : "благоприятный, подходящий, своевременный",
"opportunity" : "удобный случай возможность",
"oppose" : "противопоставлять [-ставить], [вос]противиться",
"opposed" : "противопоставленный; See also: be opposed to",
"opposite" : "противоположный, напротив против, противоположность",
"opposition" : "сопротивление, оппозиция, контраст",
"oppress" : "притеснять [-нить] угнетать",
"oppression" : "притеснение угнетение, угнетенность",
"oppressive" : "гнетущий угнетающий, душный",
"oppressor" : "n  угнетатель, притеснитель",
"opprobrium" : "позор",
"opt" : "выбирать",
"optic" : "глазной зрительный",
"optical" : "оптический",
"optician" : "оптик",
"optima" : "See: optimum",
"optimal" : "наилучший",
"optimism" : "оптимизм",
"optimist" : "оптимист",
"optimistic(al)" : "a  оптимистичный, оптимистический",
"optimum" : "оптимальный",
"option" : "выбор право выбора; See also: option right",
"option right" : "право преимущественной покупки",
"optional" : "необязательный факультативный",
"optometry" : "оптометрия",
"opulence" : "богатство",
"opulent" : "состоятельный",
"opus" : "опус",
"or" : "или; See also: ~ else",
"or else" : "а то, или же",
"oracle" : "оракул",
"oracular" : "пророческий",
"oral" : "устный, словесный",
"orange" : "апельсин, оранжевый цвет, оранжевый",
"orangutan" : "орангутанг",
"orate" : "произносить речь",
"oration" : "речь",
"orator" : "оратор",
"oratorical" : "ораторский",
"oratorio" : "оратория",
"oratory" : "красноречие, часовня",
"orb" : "шар, орбита, небесное светило, держава",
"orbit" : "глазная впадина",
"orbital" : "глазничный",
"orchard" : "фруктовый сад",
"orchestra" : "оркестр",
"orchestral" : "a  оркестровый",
"orchestrate" : "инструментовать",
"orchid" : "орхидея",
"orchis" : "ятрышник",
"ordain" : "посвящать в духовный сан, предписывать [-сать]",
"ordeal" : "испытание",
"order" : "порядок, знак отличия, приказ, заказ, ранг, строй, standing orders, приказывать [-зать], назначать [-начить], заказывать [-зать]; See also: take orders, take holy orders, in order to, in order that, make to order",
"orderly" : "аккуратный, спокойный, регулярный, вестовой ординарец",
"ordinal" : "порядковый",
"ordinance" : "указ декрет",
"ordinary" : "обыкновенный, заурядный",
"ordinate" : "ордината",
"ordnance" : "артиллерийские орудия, артиллерийское и техническое снабжение",
"ordure" : "навоз, отбросы, грязь",
"ore" : "руда",
"oregano" : "n  бот. ореган",
"organ" : "орган, голос; See also: орган",
"organdie," : "organdy  n  тонкая кисея, органди",
"organgrinder" : "шарманщик",
"organic" : "органический",
"organically" : "органический",
"organization" : "организация",
"organize" : "организовать",
"organizer" : "организатор",
"orgasm" : "оргазм",
"orgiastic" : "разнузданный",
"orgy" : "оргия",
"orient" : "восток, Восток восточные страны, ориентировать",
"oriental" : "восточный азиатский, житель Востока",
"orientate" : "ориентировать",
"orifice" : "отверстие, устье",
"origin" : "источник, происхождение, начало",
"original" : "первоначальный, оригинальный, подлинный, оригинал подлинник, чудак",
"originality" : "оригинальность",
"originate" : "давать начало  порождать [породить], происходить [-изойти]",
"originator" : "создатель, инициатор",
"orinoco" : "ориноко",
"oriole" : "иволга",
"orion" : "созвездие ориона",
"orkney" : "Islands геогр. Оркнейские острова",
"ornament" : "украшение орнамент, краса, украшать [украсить]",
"ornamental" : "декоративный",
"ornamentation" : "украшение",
"ornate" : "разукрашенный, витиеватый",
"ornery" : "посредственный",
"orography" : "орография",
"orphan" : "сирота, осиротелый",
"orphanage" : "приют для сирот",
"orphanasylum" : "приют для сирот",
"orpheus" : "орфей",
"orphic" : "мистический",
"orthodontist" : "n  ортодонт",
"orthodox" : "правоверный, православный",
"orthodoxy" : "православие",
"orthogonal" : "прямоугольный",
"orthography" : "орфография",
"orthopedic" : "ортопедический",
"oscar" : "n  1) амер. «Оскар» (ежегодная премия американской киноакадемии)  2) «Оскар» (премия лучшему шахматисту года)",
"oscillate" : "вибрировать, колебаться",
"oscillatory" : "a  колебательный;  oscillatory circuit радио колебательный контур",
"oscilloscope" : "осциллоскоп",
"osier" : "ива",
"osiris" : "озирис",
"oslo" : "осло",
"osmium" : "осмий",
"osmosis" : "осмос",
"osmotic" : "a  физ. осмотический",
"osprey" : "скопа",
"osseous" : "костный",
"ossify" : "[о]костенеть",
"ostensible" : "очевидный",
"ostentation" : "хвастовство, выставление напоказ",
"ostentatious" : "показной",
"osteology" : "остеология",
"osteopathy" : "остеопатия",
"osteoporosis" : "остеопороз",
"ostler" : "конюх",
"ostracism" : "остракизм",
"ostrich" : "страус",
"otch" : "шотландский, шотландский диалект; See also: the otch",
"otchman" : "шотландец",
"other" : "другой, иной; See also: the other day, the other morning, every other day",
"otherwise" : "иначе, или же",
"otherworldly" : "духовный",
"otiose" : "бесполезный",
"ottawa" : "оттава",
"otter" : "выдра",
"otto" : "эфирное масло",
"ottoman" : "оттоманский",
"ouch" : "оправа драгоценного камня",
"ought" : "I ought to; See also: you ought to have done it",
"ounce" : "унция",
"our" : "наш наша наше, наши",
"ourselves" : " себя -ся -сь, сами"
};
