var dicctr_49 = {
"обедневший" : "impoverished",
"обеднеть" : "grow poor",
"обедня" : "mass",
"обезболивание" : "anesthetization",
"обезвоживать" : "dehydrate",
"обезвредить" : "neutralize",
"обезвреживать" : "neutralize",
"обезглавить" : "behead",
"обезглавливать" : "behead",
"обездоленный" : "wretched miserable",
"обеззараживание" : "disinfection",
"обезличивать" : "deprive of personal character assignment #or responsibility",
"обезличить" : "deprive of personal character assignment #or responsibility",
"обезлюдеть" : "pf. become deserted",
"обезнадеживать" : "bereave of hope",
"обезнадежить" : "bereave of hope",
"обезображивать" : "disfigure",
"обезобразить" : "disfigure",
"обезопасить" : "pf. secure",
"обезоруживать" : "disarm",
"обезоружить" : "disarm",
"обезумевший" : "distraught",
"обезуметь" : "pf. lose one's senses go mad",
"обезьяна" : "monkey, ape",
"обезьяний" : "monkey, apish apelike",
"обезьянничать" : "ape",
"обелиск" : "obelisk",
"оберегать" : "guard  protect",
"оберечь" : "guard  protect",
"обернуть" : "s. обертывать",
"обертывать" : "envelop",
"обеспечивать" : "provide, secure guarantee, protect",
"обеспечить" : "provide, secure guarantee, protect",
"обеспокоить" : "upset worry, disturb bother trouble",
"обесценивать" : "depreciate, devaluate, devalue, disesteem",
"обещание" : "promise, troth",
"обещать" : "famil. a. пообещать promise",
"обжалование" : "appeal",
"обжечь" : "burn, scorch, engin. bake calcine, -ся burn o.s.",
"обжигательная печь" : "kiln",
"обжигать" : "burn, scorch, engin. bake calcine, -ся burn o.s.",
"обжора" : "glutton",
"обжорливый" : "gluttonous",
"обжорство" : "gluttony",
"обзавестись" : "provide o.s.  acquire get",
"обзаводиться" : "provide o.s.  acquire get",
"обзор" : "survey, review",
"обзывать" : "call",
"оби" : "obi",
"обивать" : "upholster, strike off, famil. wear out; See also: обивать пороги",
"обивать пороги" : "importune",
"обивка" : "upholstery",
"обида" : "insult, не в обиду будь сказано no offence meant; See also: не дать в обиду",
"обидеть" : "s. обижать",
"обидный" : "offensive insulting, обидно it is a shame #or vexing",
"обидчивый" : "touchy",
"обидчик" : "offender",
"обижать" : "offend hurt, wrong, overreach",
"обиженный" : "offended",
"обилие" : "abundance wealth",
"обильный" : "abundant  plentiful rich",
"обиняк" : "говорить обиняками",
"обкорнать" : "lop",
"облава" : "battue, raid",
"облагать" : "impose, tax, fine",
"облагораживать" : "ennoble refine, finish",
"облагородить" : "ennoble refine, finish",
"обладание" : "possession",
"обладать" : "possess, command, be in; See also: обладать собой",
"обладать собой" : "control o.s.",
"облако" : "cloud",
"обламывать" : "break off",
"облапошить" : "diddle",
"обласкать" : "pf. treat kindly",
"областной" : "regional",
"область" : "region, province sphere field",
"облатка" : "wafer, capsule",
"облачение" : "pl.",
"облачный" : "cloudy",
"облегать" : "cover, fit",
"облегчать" : "lighten, facilitate, ease relieve",
"облегчить" : "lighten, facilitate, ease relieve",
"обледенелый" : "ice-covered",
"облезлый" : "mangy shabby",
"облекать" : "dress, invest, put express, -ся put on, be invested",
"облепить" : "stick all over, besiege",
"облеплять" : "stick all over, besiege",
"облетать" : "fly round, fall",
"облететь" : "fly round, fall",
"облечь" : "cover, fit",
"обливать" : "pour over wet, flood, soak, -ся pour over o.s., shed, be dripping #or covered, bleed",
"облигация" : "bond",
"облизать" : "lick, -ся lick one's lips",
"облизывать" : "lick, -ся lick one's lips",
"облик" : "face look, figure",
"облить" : "pour over wet, flood, soak, -ся pour over o.s., shed, be dripping #or covered, bleed",
"облицевать" : "face",
"облицовывать" : "face",
"обличать" : "unmask, reveal, convict",
"обличение" : "exposure, conviction",
"обличительный" : "accusatory incriminating",
"обличить" : "unmask, reveal, convict",
"обложение" : "taxation, milit. siege",
"обложить" : "lay round, face cover, med. fur, pf. besiege, s. облагать",
"обложка" : "cover jacket",
"облокачиваться" : "lean one's elbows",
"облокотиться" : "lean one's elbows",
"обломать" : "break off",
"обломить" : "break off",
"обломок" : "fragment, pl. debris wreckage",
"облупить" : "peel",
"облучать" : "ray",
"облучить" : "ray",
"облучок" : "box",
"облюбовать" : "pf. take a fancy to",
"обмазать" : "besmear, plaster coat cement",
"обмазывать" : "besmear, plaster coat cement",
"обмакивать" : "dip",
"обмакнуть" : "dip",
"обман" : "deception, deceit fraud; See also: обман зрения",
"обман зрения" : "optical illusion",
"обманный" : "deceitful fraudulent",
"обмануть" : "s. обманывать",
"обманчивый" : "captious, deceitful, deceptive, delusive",
"обманщик" : "trickster",
"обманывать" : "bamboozle, beguile, defraud, delude, hoodwink",
"обмен" : "exchange, interchange, metabolism, swop",
"обменивать" : "swap",
"обменить" : "exchange",
"обменять" : "exchange barter, change, -ся",
"обмереть" : "s. обмирать",
"обмести" : "sweep  dust",
"обметать" : "sweep  dust",
"обмирать" : "be struck #or stunned",
"обмолвиться" : "pf. make a slip, mention say",
"обмолвка" : "slip of the tongue",
"обмолот" : "thresh",
"обморожение" : "chilblain",
"обморозить" : "pf. frostbite",
"обморок" : "faint swoon",
"обмотать" : "wind",
"обмотка" : "el. winding, pl. puttees",
"обмундирование" : "pf. uniform outfit",
"обмундировать" : "pf. uniform outfit",
"обмывание" : "a. ablution",
"обмывать" : "wash",
"обмыть" : "wash",
"обнадеживать" : "assure encourage raise hopes",
"обнадежить" : "assure encourage raise hopes",
"обнажать" : "bare strip, lay bare, uncover, unsheathe",
"обнажить" : "bare strip, lay bare, uncover, unsheathe",
"обнародовать" : "pf. promulgate",
"обнаруживать" : "disclose show reveal, discover detect, -ся appear show, come to light, be found discovered",
"обнаружить" : "disclose show reveal, discover detect, -ся appear show, come to light, be found discovered",
"обнести" : "s. обносить",
"обнимать" : "embrace hug clasp",
"обнищалый" : "impoverished",
"обнова" : "new thing novelty",
"обнюхивать" : "smell at",
"обнять" : "embrace hug clasp",
"обо" : "about of, on, with, against on, by in",
"обобрать" : "rob, popul. gather",
"обобщать" : "generalize",
"обобществить" : "socialize",
"обобществлять" : "socialize",
"обобщить" : "generalize",
"обогатить" : "enrich",
"обогащать" : "enrich",
"обогнать" : "distance outstrip",
"обогнуть" : "s. огибать",
"обоготворять" : "s. боготворить",
"обогревать" : "s. греть",
"обогреть" : "warm, heat; See also: греться на солнце",
"обод" : "rim felloe",
"ободок" : "rim",
"ободранный" : "ragged shabby",
"ободрать" : "bark peel, tear",
"ободрение" : "encouragement",
"ободрить" : "encourage, -ся take courage",
"ободрять" : "encourage, -ся take courage",
"обожать" : "adore worship",
"обождать" : "famil. = подождать",
"обожествить" : "deify",
"обожествлять" : "deify",
"обожженный" : "burnt",
"обоз" : "train  carts pl.",
"обозвать" : "call",
"обозлить" : "vex anger #or make angry irritate, -ся be #or feel angry, fig. rage",
"обозначать" : "denote designate mark, -ся appear",
"обозначение" : "designation",
"обозначить" : "denote designate mark, -ся appear",
"обозревать" : "survey, review",
"обозрение" : "survey, review",
"обозреть" : "survey, review",
"обои" : "wallpaper",
"обойти" : "s. обходить",
"оболочка" : "integument, involucre, tegument",
"обольщать" : "blandish, seduce",
"обонятельный" : "olfactory",
"оборвать" : "s. обрывать",
"оборка" : "frill ruffle",
"оборона" : "defense",
"оборонительный" : "defensive defense...",
"оборонный" : "defense... armament...",
"обороноспособность" : "defensive capacity",
"оборонять" : "defend",
"оборот" : "revolution, rotation, circulation, turn, turnover, transaction, back reverse, на обороте p.t.o.; See also: в оборот",
"оборотить" : "s. обернуть",
"оборудованный" : "equipped",
"обосновывать" : "prove substantiate, -ся settle down",
"обособить" : "segregate isolate detach",
"обособленный" : "insular",
"обособлять" : "segregate isolate detach",
"обострить" : "aggravate strain, refine",
"обострять" : "aggravate strain, refine",
"обоюдный" : "mutual",
"обоюдоострый" : "double-edged",
"обрабатывать" : "work process, farm. till, elaborate finish polish, treat, adapt, famil. work, engin. manufacturing",
"обработать" : "work process, farm. till, elaborate finish polish, treat, adapt, famil. work, engin. manufacturing",
"обработка" : "processing, farm. cultivation, elaboration, adaptation",
"обрадовать" : "gladden please rejoice, -ся rejoice  be glad #or pleased, look forward",
"образ" : "manner way  mode, form, figure, character, image, icon; See also: каким образом, таким образом, никоим образом",
"образец" : "specimen sample, model example, pattern, fashion way",
"образность" : "imagery",
"образный" : "graphic vivid",
"образование" : "formation, constitution, education",
"образованность" : "erudition",
"образованный" : "educated",
"образовательный" : "formative",
"образовать" : "form, constitute, educate, cultivate",
"образовывать" : "form, constitute, educate, cultivate",
"образумить" : "pf. bring to one's senses",
"образумиться" : "pf. come to one's senses",
"образующий" : "formative, forming",
"образцовый" : "exemplary model...",
"образчик" : "s. образец",
"обрамить" : "frame",
"обрамлять" : "frame",
"обрастать" : "overgrow, be overgrown",
"обрасти" : "overgrow, be overgrown",
"обратимый" : "convertible, reversible",
"обратить" : "s. обращать",
"обратно" : "back, conversely",
"обратный" : "back return... reverse inverse, jur. retroactive",
"обратный билет" : "round-trip ticket Brt. return-ticket",
"обращать" : "turn, direct, convert, employ, draw #or pay #or attract, не обращать внимания disregard, -ся turn, address o.s.  apply, appeal, take, impf. treat handle, circulate",
"обращаться" : "apply",
"обращение" : "conversion, transformation, circulation, treatment  management, manners pl., address, appeal",
"обрез" : "edge",
"обрезание" : "circumcision"
};
