var dicctr_93 = {
"феноменальный" : "phenomenal",
"фенотип" : "phenotype",
"феодальный" : "feudal",
"ферзь" : "queen",
"ферма" : "farm",
"фермент" : "ferment",
"фермер" : "farmer",
"фестиваль" : "festival",
"фетр" : "felt",
"фетровый" : "felt...",
"фехтовальщик" : "fencer",
"фехтование" : "fencing",
"фехтовать" : "fence",
"фея" : "pixy, sprite",
"фиалка" : "violet",
"фибра" : "fiber Brt. fibre",
"фига" : "fig",
"фиговый" : "fig",
"фигура" : "figure, man",
"фигуральный" : "figurative",
"фигурировать" : "figure appear",
"фигурный" : "figured, trick... stunt...",
"физик" : "physicist",
"физика" : "physics",
"физиология" : "physiology",
"физиономия" : "physiognomy",
"физиотерапия" : "physiatrics, physiotherapy",
"физический" : "physical, manual",
"физкультура" : "physical culture, gymnastics",
"физкультурник" : "sportsman gymnast",
"физкультурница" : "sportsman gymnast",
"фиксаж" : "fixative",
"фиксировать" : "fix",
"фиктивный" : "fictitious",
"филадельфия" : "philadelphia",
"филантроп" : "philanthropist",
"филантропический" : "philanthropic, philanthropical",
"филантропия" : "philanthropy",
"филармонический" : "philharmonic",
"филе" : "tenderloin fillet",
"филиал" : "branch",
"филиальный" : "branch...",
"филигрань" : "filigree",
"филин" : "eagle owl",
"филиппинский" : "philippine",
"филиппины" : "Philippines",
"филистер" : "philistine",
"филогения" : "phylogeny",
"филолог" : "philologist",
"филологический" : "philological",
"филология" : "philology",
"философ" : "philosopher",
"философия" : "philosophy",
"философский" : "philosophical",
"философствовать" : "philosophize",
"фильм" : "film",
"фильтр" : "filter",
"фильтрат" : "filtrate",
"фильтровать" : "filter",
"фимиам" : "incense",
"финал" : "final, mus. finale",
"финансировать" : "pf. finance",
"финансист" : "financier",
"финансовый" : "financial",
"финансы" : "finance",
"финик" : "date",
"финиковый" : "date...",
"финка" : "Finn",
"финляндия" : "finland",
"финский" : "finnic, finnish",
"фиолетовый" : "violet",
"фита" : "phi",
"фитиль" : "wick",
"флаг" : "flag, flagstone",
"флакон" : "phial, vial",
"фламандский" : "flemish",
"фламинго" : "flamingo",
"фланг" : "flank",
"фланелевый" : "flannel",
"флегматичный" : "phlegmatic",
"флейта" : "flute",
"флейтист" : "flautist, flutist, piper",
"флигель" : "wing",
"флирт" : "flirtation",
"флиртовать" : "flirt",
"флокс" : "phlox",
"флора" : "flora",
"флорида" : "florida",
"флот" : "fleet, marine, navy, force",
"флотилия" : "flotilla",
"флотский" : "naval, famil. sailor",
"флоэма" : "phloem",
"флюгер" : "weathercock weather vane",
"флюоресцентный" : "fluorescent",
"флюс" : "gumboil",
"фляга" : "flask, canteen Brt. water bottle",
"фляжка" : "flask, canteen Brt. water bottle",
"фойе" : "thea. lobby foyer",
"фокстрот" : "fox trot",
"фокус" : "hocus-pocus trick sleight of hand, famil. trick, freak whim",
"фокусник" : "juggler conjurer",
"фокусничать" : "trick",
"фокусный" : "focal",
"фокусы" : "legerdemain",
"фольга" : "foil",
"фольклор" : "folklore",
"фольклорный" : "folklore",
"фома" : "Thomas",
"фон" : "background",
"фонарик" : "flashlight Brt. torch",
"фонарь" : "lantern, lamp, light, s. синяк",
"фонд" : "fund",
"фонема" : "phoneme",
"фонематический" : "phonemic",
"фонетика" : "phonetics",
"фонетический" : "phonetic",
"фонограф" : "phonograph",
"фонография" : "phonography",
"фонология" : "phonology",
"фонон" : "phonon",
"фонтан" : "fountain",
"форель" : "trout",
"форма" : "form shape, model, engin. mold, milit. uniform, dress",
"формалист" : "prig",
"формальность" : "formality",
"формальный" : "formal",
"формат" : "size, form",
"форменная одежда" : "uniform",
"форменный" : "formal, famil. downright",
"формировать" : "form",
"формовать" : "mold model",
"формула" : "formula",
"формулировать" : "formulate",
"формулировка" : "formulation",
"формуляр" : "form",
"форпост" : "advanced post",
"форсировать" : "pf. force",
"форт" : "fort",
"фортепьяно" : "piano, pianoforte",
"форточка" : "window leaf",
"фосген" : "phosgene",
"фосфид" : "phosphide",
"фосфин" : "phosphine",
"фосфор" : "phosphorus",
"фосфоресценция" : "phosphoresce, phosphorescence",
"фосфористый" : "phosphorous, phosphorus",
"фосфорический" : "phosphoric",
"фосфорнокислый" : "phosphate",
"фото" : "photo",
"фотоаппарат" : "camera",
"фотогеничный" : "photogenic",
"фотограф" : "photographer",
"фотографировать" : "photograph",
"фотографический" : "photographic, cf. фотоаппарат",
"фотография" : "photograph, photography, photographer's",
"фотолиз" : "photolysis",
"фотометрия" : "photometry",
"фотон" : "photon",
"фраза" : "phrase, empty talk",
"фразеология" : "phraseology",
"фрак" : "dress coat",
"фракционировать" : "fractionate",
"фракционный" : "factious",
"фракция" : "faction",
"фрамуга" : "fanlight, transom",
"франк" : "franc",
"франкировать" : "pf. stamp",
"франт" : "dandy fop",
"франтить" : "overdress",
"франтовской" : "dandyish dudish",
"франция" : "France",
"француженка" : "Frenchwoman",
"француз" : "Frenchman",
"французский" : "French",
"фрахт" : "freight",
"фрахтовать" : "freight",
"фрг" : "Federal Republic of Germany",
"фрегат" : "frigate",
"фрезер" : "milling cutter",
"френч" : "jacket",
"фреска" : "fresco",
"фронт" : "front",
"фронтовой" : "front...",
"фронтон" : "gable, pediment",
"фрукт" : "fruit",
"фруктовый" : "fruit...",
"фруктовый сад" : "orchard",
"фруктоза" : "fructose",
"фтор" : "fluor, fluorine",
"фу" : "fie! ugh!",
"фундамент" : "groundwork, substruction, substructure",
"функционировать" : "function",
"фунт" : "round",
"фураж" : "fodder",
"фуражка" : "cap",
"фургон" : "van",
"фурия" : "fury",
"фурор" : "furor",
"фурункул" : "furuncle boil",
"футбол" : "soccer a. association football",
"футболист" : "soccer player",
"футбольный" : "soccer... football...",
"футляр" : "case, sheath, box",
"фуфайка" : "jersey",
"фыркать" : "snort",
"фыркнуть" : "snort",
"фюзеляж" : "fuselage",
"хаки" : "khaki",
"халат" : "dressing gown bathrobe, smock",
"халатный" : "careless negligent, sluggish",
"халва" : "halvah",
"халтура" : "botch bungle",
"хам" : "cad boor churl",
"хамелеон" : "chameleon",
"хандра" : "melancholy blues pl.",
"хандрить" : "be in the dumps",
"ханжа" : "hypocrite",
"ханжеский" : "hypocrite",
"ханжество" : "hypocrisy bigotry",
"ханой" : "hanoi",
"хаос" : "chaos",
"хаотический" : "chaotic",
"хаотичный" : "chaotic",
"характер" : "character nature, temper disposition, principles pl.",
"характеризовать" : "characterize mark",
"характеристика" : "character, characterization",
"характерный" : "characteristic",
"харкать" : "spit",
"харкнуть" : "spit",
"харчевня" : "tavern",
"харчи" : "food grub, board",
"харя" : "mug phiz",
"хата" : "hut",
"хвала" : "praise",
"хвалебный" : "laudatory",
"хвалить" : "praise",
"хвалиться" : "boast",
"хвастать" : "boast brag",
"хвастаться" : "boast brag",
"хвастливый" : "boastful",
"хвастовство" : "boasting",
"хвастун" : "boaster braggart",
"хватание" : "prehension",
"хватать" : "хватить snatch, grasp seize, famil., хватить suffice be sufficient, have enough, last, хватит enough, famil. hit knock strike, drink eat, take, go",
"хватка" : "clutch",
"хвойный" : "coniferous",
"хворать" : "be sick #or ill",
"хворост" : "brushwood",
"хвост" : "tail, brush, famil. train, line Brt. queue; See also: в хвосте, поджать хвост",
"хвоя" : "needle"
};
