var dicctr_53 = {
"осадить" : "& осаживать",
"осадки" : "pl. precipitations",
"осадный" : "of siege #or martial law",
"осадок" : "sediment, fig. aftertaste",
"осадочный" : "sedimentary",
"осаждать" : "besiege, chem. precipitate, famil. importune",
"осаждение" : "sedimentation",
"осаживать" : "check snub",
"осанистый" : "dignified stately",
"осанка" : "bearing",
"осваивать" : "master, open up, bot. acclimate, -ся accustom o.s., familiarize o.s.",
"осведомить" : "inform, -ся inquire",
"осведомленный" : "informed, versed",
"осведомлять" : "inform, -ся inquire",
"освежать" : "refresh, freshen #or touch up, brush up",
"освежительный" : "refreshing",
"освежить" : "refresh, freshen #or touch up, brush up",
"осветить" : "light  illuminate, fig. elucidate illustrate",
"освещать" : "light  illuminate, fig. elucidate illustrate",
"освещенность" : "luminosity",
"освидетельствование" : "examination",
"освидетельствовать" : "pf. examine",
"освистать" : "hiss",
"освистывать" : "hiss",
"освободитель" : "liberator",
"освободительный" : "emancipatory",
"освободить" : "free release, liberate deliver, emancipate, exempt excuse, clear, vacate quit",
"освобождать" : "free release, liberate deliver, emancipate, exempt excuse, clear, vacate quit",
"освобождение" : "liberation, release, emancipation, exemption",
"освобожденный" : "freed, released",
"освоение" : "mastering, opening up",
"освоить" : "master, open up, bot. acclimate, -ся accustom o.s., familiarize o.s.",
"освятить" : "consecrate",
"освящать" : "consecrate",
"освященный" : "consecrate",
"осевое" : "thrust",
"осевой" : "axial, pivotal",
"оседать" : "subside settle",
"оседлать" : "saddle",
"оседлый" : "settled",
"осел" : "donkey ass",
"осенить" : "s. осенять",
"осенний" : "autumnal fall...",
"осень" : "fall Brt. autumn",
"осенять" : "shade, invest, bless make, flash on",
"осесть" : "subside settle",
"осетр" : "sturgeon",
"осечка" : "misfire",
"осиливать" : "s. одолевать",
"осилить" : "s. одолевать",
"осина" : "asp",
"осиновый" : "asp",
"осиный" : "waspish",
"осипнуть" : "pf. grow hoarse",
"осиротелый" : "orphan",
"оскаливать" : "show",
"оскалить" : "show",
"осквернить" : "profane desecrate defile",
"осквернять" : "profane desecrate defile",
"осколки" : "smithereens",
"осколок" : "splinter",
"оскорбительный" : "offensive insulting",
"оскорбить" : "offend insult",
"оскорбление" : "insult offence",
"оскорблять" : "offend insult",
"оскудевать" : "become poor #or scanty",
"оскудеть" : "become poor #or scanty",
"ослабевать" : "grow weak #or feeble languish, slacken, abate",
"ослабеть" : "grow weak #or feeble languish, slacken, abate",
"ослабить" : "s. ослаблять",
"ослабление" : "weakening, relaxation",
"ослаблять" : "weaken enfeeble, relax slacken loosen",
"ослепительный" : "dazzling",
"ослепить" : "blind, dazzle",
"ослеплять" : "blind, dazzle",
"ослепнуть" : "grow blind",
"ослик" : "burro",
"ослиный" : "asinine",
"осло" : "oslo",
"осложнение" : "complication",
"осложнить" : "complicate",
"осложнять" : "complicate",
"ослушаться" : "disobey",
"ослушиваться" : "disobey",
"ослушник" : "disobedient pers.",
"ослышаться" : "pf. hear amiss",
"осматривать" : "view examine, inspect, see, -ся look round, take a view of",
"осмеивать" : "laugh at ridicule deride",
"осмеливаться" : "dare venture, beg #to",
"осмелиться" : "dare venture, beg #to",
"осмеяние" : "ridicule derision",
"осмеять" : "laugh at ridicule deride",
"осмий" : "osmium",
"осмос" : "osmose, osmosis",
"осмотр" : "examination inspection, seeing, visit",
"осмотреть" : "view examine, inspect, see, -ся look round, take a view of",
"осмотрительность" : "circumspection prudence",
"осмотрительный" : "circumspect prudent",
"осмотрительость" : "discretion",
"осмысленный" : "sensible, intelligent",
"осмысливать" : "comprehend conceive, grasp make sense of",
"осмыслить" : "comprehend conceive, grasp make sense of",
"осмыслять" : "comprehend conceive, grasp make sense of",
"оснастить" : "rig",
"оснастка" : "rigging",
"оснащать" : "rig",
"оснащение" : "equipment",
"основа" : "basis foundation, fundamental essential principle, gr. stem, text. warp",
"основание" : "foundation basis, arch. chem. base, fundamental, ground reason, argument",
"основанный" : "founded",
"основатель" : "founder",
"основательный" : "valid, sound solid, thorough",
"основать" : "s. основывать",
"основной" : "fundamental basic principal primary, commerc. original",
"основоположник" : "founder",
"основывать" : "found, establish, -ся be based rest, settle",
"особа" : "person, personage",
"особенность" : "peculiarity",
"особенный" : "special particular peculiar",
"особняк" : "villa private residence",
"особняком" : "apart, aloof, separate",
"особый" : "s. особенный, separate",
"осознавать" : "realize",
"осознать" : "realize",
"осока" : "sedge",
"оспа" : "smallpox",
"оспаривать" : "contest dispute, contend",
"оспопрививание" : "vaccination",
"оспорить" : "contest dispute, contend",
"осрамить" : "disgrace shame compromise",
"оставаться" : "remain stay, be left, keep, stick, be, have to, go get off, ~ get win, reserve take, owe; See also: остаться без, остаться с носом",
"оставить" : "leave, give up, drop stop, let, keep; See also: оставлять за собой",
"оставлять" : "leave, give up, drop stop, let, keep; See also: оставлять за собой",
"оставлять за собой" : "reserve to o.s.",
"оставшийся" : "residuary",
"остальное" : "remainder",
"остальной" : "remaining, a. the others, & a. su. the rest",
"останавливать" : "stop bring to a stop, fix, -ся stop, put up, dwell",
"останки" : "remains",
"остановить" : "stop bring to a stop, fix, -ся stop, put up, dwell",
"остановка" : "stop, break, остановка за ..., ... is wanting",
"остатки" : "oddments, pickings, remains",
"остаток" : "remainder  rest, remnant, pl. remains",
"остаточный" : "remaining, residual, vestigial",
"остаться" : "remain stay, be left, keep, stick, be, have to, go get off, ~ get win, reserve take, owe; See also: остаться без, остаться с носом",
"остаться без" : "lose have no",
"остаться с носом" : "famil. get nothing",
"остеклить" : "glaze",
"остеклять" : "glaze",
"остеология" : "osteology",
"остеопатия" : "osteopathy",
"остеопороз" : "osteoporosis",
"остервенелый" : "furious",
"остерегаться" : "beware of be careful of",
"остеречься" : "beware of be careful of",
"остов" : "skeleton framework",
"остолбенелый" : "stunned",
"остолбенеть" : "petrify",
"остолоп" : "dolt dunce",
"осторожно" : "look out, with care!",
"осторожность" : "caution heed",
"осторожный" : "cautious careful wary, prudent",
"остракизм" : "ostracism",
"остригать" : "cut, crop, shear, pare",
"острие" : "point, edge",
"острием" : "edgeways, edgewise",
"острить" : "sharpen",
"остричь" : "cut, crop, shear, pare",
"остров" : "island, isle",
"островитянин" : "islander",
"островок" : "islet",
"острог" : "prison, hist. burg",
"острога" : "gaff, leister",
"остроглазый" : "sharp-sighted",
"остроконечный" : "pointed",
"остролист" : "holly",
"острота" : "sharpness keenness acuteness, witticism, joke",
"остроумие" : "wit, sagacity",
"остроумный" : "witty, ingenious",
"острый" : "sharp pointed, keen, acute, critical",
"остряк" : "wit",
"оступаться" : "stumble",
"оступиться" : "stumble",
"остывать" : "s. стынуть",
"остыть" : "cool",
"ость" : "awn",
"осуждать" : "censure, condemn",
"осуждение" : "conviction, damnation, denunciation, dispraise",
"осужденный" : "condemned, convict, convicted",
"осушение" : "drainage",
"осуществимый" : "practicable, workable",
"осциллоскоп" : "oscilloscope",
"ось" : "axis, axle, kingbolt",
"осьминог" : "devilfish, octopus",
"осязаемый" : "palpable, tangible",
"осязание" : "sense of touch",
"осязательный" : "of touch, palpable",
"осязать" : "touch feel",
"от" : "from, of, off, against, for with, in, on behalf",
"от альфы до омеги" : "from beginning to end",
"от времени до времени" : "from time to time now and then sometimes",
"от всего сердца" : "whole-heartedly",
"от доски до доски" : "from cover to cover",
"от души" : "from one's heart",
"отапливать" : "heat",
"отбавить" : "take away #or off, diminish",
"отбавлять" : "take away #or off, diminish",
"отбегать" : "run off",
"отбежать" : "run off",
"отбеливать" : "bleach",
"отбивать" : "beat strike off, milit. repel, deliver, snatch away, break off, -ся ward off, get lost drop behind, break off, famil. get rid",
"отбирать" : "take away #or off, select pick out, collect",
"отбить" : "beat strike off, milit. repel, deliver, snatch away, break off, -ся ward off, get lost drop behind, break off, famil. get rid",
"отблагодарить" : "thank",
"отблеск" : "reflection, vestige",
"отбой" : "milit. retreat, all clear, teleph. ring off",
"отбор" : "selection choice",
"отборный" : "select choice picked",
"отбрасывать" : "throw off #or away, milit. throw back, reject",
"отбросить" : "throw off #or away, milit. throw back, reject",
"отбросы" : "refuse waste",
"отбывать" : "leave depart, serve, do",
"отбытие" : "departure",
"отбыть" : "leave depart, serve, do",
"отвага" : "bravery valor",
"отваживаться" : "venture dare",
"отважиться" : "venture dare",
"отважный" : "valiant brave",
"отвал" : "до отвала",
"отвернуть" : "& отворачивать",
"отверстие" : "aperture, foramen, meatus, orifice, pore, vent",
"отвертка" : "screwdriver",
"отвесный" : "bluff",
"ответ" : "answer, answerback, rejoinder, replay, reply",
"ответный" : "responsive",
"ответственность" : "onus, responsibility",
"ответственный" : "accountable, amenable, answerable, liable",
"отвечать" : "respond",
"отвечающий" : "respondent",
"отвешивать" : "weigh out, make",
"отвинтить" : "unscrew unfasten",
"отвинчивать" : "unscrew unfasten",
"отвисать" : "hang down lop",
"отвислый" : "loppy",
"отвиснуть" : "hang down lop",
"отвлекать" : "divert distract, abstract",
"отвлеченный" : "abstract",
"отвлечь" : "divert distract, abstract",
"отвод" : "allotment, rejection",
"отводить" : "lead get take, turn off avert, parry, reject, allot"
};
