var dicct_3 = {
"america" : "геогр. Америка North America — Северная Америка South America — Южная Америка",
"american" : "американец, американский",
"americana" : "n pl  американские реалии, американские издания, документы и т. п.",
"americanism" : "американизм",
"americanize" : "американизировать",
"amethyst" : "аметист",
"amethystine" : "a  аметистовый",
"amiable" : "дружелюбный, добродушный",
"amicable" : "дружеский дружественный",
"amid" : "среди  посреди  между",
"amide" : "n  хим. амид",
"amidst" : "среди  посреди  между",
"amino" : "acid(s){}  n  хим. аминокислоты",
"amiss" : "плохо неправильно, некстати, несвоевременно; See also: take amiss",
"amity" : "дружба",
"ammeter" : "амперметр",
"ammo" : "боеприпасы",
"ammonia" : "аммиак",
"ammoniac" : "аммиачный",
"ammonium" : "n  хим.  1) аммоний  2) attr.:  ammonium chloride нашатырный спирт, хлористый аммоний",
"ammunition" : "боеприпасы",
"amnesia" : "n  мед. потеря памяти, амнезия",
"amnesty" : "амнистия, амнистировать",
"amoeba" : "амеба",
"amoebae" : "See: amoeba",
"amok" : "вне себя",
"among" : "среди  между",
"amongst" : "среди  между",
"amoral" : "аморальный",
"amorous" : "влюбленный, влюбчивый",
"amorphous" : "бесформенный",
"amount" : "amount to, сумма, количество",
"amount to" : "равняться",
"amperage" : "ток",
"ampere" : "ампер",
"ampersand" : "n  знак &amp; (= and)",
"amphetamine" : "n  мед. амфетамин (возбуждающее средство)",
"amphibian" : "земноводное",
"amphibious" : "земноводный",
"amphibology" : "n  двусмысленное выражение",
"ample" : "достаточный обильный, просторный",
"amplification" : "расширение, увеличение, усиление",
"amplifier" : "phys. усилитель",
"amplify" : "усилить, распространять [-нить]",
"amplitude" : "широта размах, phys. амплитуда",
"amply" : "adv  1) обильно; полно, достаточно  2) пространно",
"amputate" : "ампутировать  отнимать [-нять]",
"amputee" : "n  человек с ампутированной ногой или рукой",
"amsterdam" : "амстердам",
"amulet" : "талисман",
"amuse" : "забавлять позабавить  развлекать [-ечь]",
"amusement" : "развлечение забава",
"an" : "неопределенный член",
"an understood thing" : "решенное дело",
"ana" : "сборник воспоминаний",
"anabaptist" : "n  анабаптист",
"anachronism" : "анахронизм",
"anaconda" : "удав",
"anaesthetic" : "наркотик",
"anagram" : "n  анаграмма",
"analgesic" : "болеутоляющий",
"analogous" : "аналогичный сходный",
"analogue" : "аналог",
"analogy" : "аналогия сходство",
"analyse" : "анализировать  [про-]",
"analyses" : "анализировать",
"analysis" : "анализ",
"analyst" : "аналитик",
"analytic" : "аналитический",
"anarchic(al)" : "a  анархический",
"anarchy" : "анархия",
"anastomosis" : "n (pl -ses)  анат., бот. анастомоз",
"anathema" : "проклятие",
"anatomic" : "анатомический",
"anatomize" : "анатомировать, [про]анализировать",
"anatomy" : "анатомия",
"ancestor" : "предок",
"ancestral" : "наследственный родовой",
"ancestress" : "прародительница",
"ancestry" : "происхождение, предки",
"anchor" : "якорь, ставить на якорь; See also: at anchor",
"anchorage" : "якорная стоянка",
"anchorite" : "отшельник",
"anchovy" : "анчоус",
"ancient" : "древний, античный; See also: the ancients",
"ancillary" : "вспомогательный",
"and" : "и а",
"and so on" : "и так далее",
"andes" : "геогр. Анды",
"andiron" : "n  железная подставка для дров в камине",
"andrews" : "See: merry-andrew",
"anecdotal" : "a  1) анекдотичный  2) изобилующий анекдотами",
"anecdote" : "рассказ",
"anemone" : "n  бот. анемон, ветреница",
"anesthetic" : "наркотик",
"anew" : "снова сызнова, по-новому",
"angel" : "ангел",
"angelic" : "ангельский",
"angelica" : "дудник",
"angelical" : "ангельский",
"anger" : "гнев, [рас]сердить",
"angle" : "угол, точка зрения, удить, удить рыбу, закидывать удочку",
"angles" : "See: angle",
"anglican" : "член англиканской церкви, англиканский",
"angling" : "See: angle",
"anglo" : "See: anglo-saxon",
"anglo-saxon" : "англосакс, англосаксонский",
"anglophobia" : "n  англофобия",
"angola" : "ангорская кошка",
"angora" : "ангорская кошка",
"angry" : "сердитый",
"angst" : "нем. n страх, беспокойство",
"angstrom" : "unit  n  физ. ангстрем",
"anguish" : "мука",
"angular" : "угловой угольный, угловатый, неловкий",
"anhydride" : "n  хим. ангидрид",
"anhydrite" : "n  мин. ангидрит",
"anhydrous" : "безводный",
"ani" : "See: anus",
"aniard" : "испанец",
"aniline" : "анилин",
"animadversion" : "порицание",
"animadvert" : "критиковать",
"animal" : "животное, животный, скотский",
"animate" : "оживлять [-вить], воодушевлять [-вить]",
"animation" : "живость, оживление",
"animism" : "n  филос. анимизм",
"animosity" : "враждебность",
"anise" : "анис",
"anish" : "испанский",
"ankara" : "анкара",
"ankle" : "лодыжка",
"anna" : "анна",
"annal" : "See: annals",
"annals" : "летопись",
"anneal" : "закалять",
"annex" : "аннексировать, присоединять [-нить], пристройка, приложение",
"annexation" : "аннексия",
"annihilate" : "уничтожать [-ожить] истреблять [-бить]",
"anniversary" : "годовщина",
"annotate" : "аннотировать, снабжать примечаниями",
"annotation" : "примечание",
"announce" : "обЙявлять [-вить], давать знать, заявлять [-вить]",
"announcement" : "обЙявление",
"announcer" : "диктор",
"annoy" : "надоедать [-есть], досаждать [досадить]",
"annoyance" : "досада, раздражение, неприятность",
"annual" : "ежегодный, годовой, ежегодник, однолетнее растение",
"annuity" : "годовая рента",
"annul" : "аннулировать, отменять [-нить]",
"annular" : "кольцеобразный",
"annulled" : "отмененный",
"annulling" : "See: annul",
"annulment" : "аннулирование",
"annulus" : "кольцо",
"annunciate" : "возвещать",
"anode" : "анод",
"anoint" : "намазать, помазать",
"anomalous" : "аномальный неправильный",
"anomaly" : "аномалия",
"anomie" : "беззаконие",
"anonymity" : "анонимность",
"anonymous" : "анонимный",
"anorexia" : "отсутствие аппетита",
"another" : "другой, еще один",
"answer" : "отвечать [-етить], удовлетворять [-рить], отвечать [-етить], ответ; See also: answer the bell, answer the door, answer for",
"answer for" : "отвечать [-етить] за",
"answer the bell" : "открывать дверь на звонок",
"answer the door" : "открывать дверь на звонок",
"answerable" : "ответственный",
"ant" : "муравей",
"antacid" : "мед.  1. n нейтрализующее кислоту средство 2. a нейтрализующий кислоту",
"antaeus" : "n  греч. миф. Антей",
"antagonism" : "антагонизм вражда",
"antagonist" : "антагонист противник",
"antagonistic" : "a  1) антагонистический; враждебный  2) противодействующий",
"antarctic" : "антарктический",
"ante" : "n  1) ставка (в карточной игре)  2) разг. доля, часть, взнос",
"ante-room" : "передняя",
"anteater" : "муравьед",
"antebellum" : "довоенный",
"antecedent" : "предшествующий предыдущий, ~s, прошлое",
"antedate" : "датировать задним числом",
"antelope" : "антилопа",
"antenna" : "антенна",
"antennae" : "See: antenna",
"anterior" : "предшествующий, передний",
"anteroom" : "передняя",
"anthem" : "гимн",
"anther" : "пыльник",
"anthology" : "антология",
"anthracite" : "n  антрацит",
"anthropology" : "антропология",
"anthropomorphism" : "n  антропоморфизм",
"anti" : "анти",
"anti-aircraft" : "противовоздушный; See also: anti-aircraft alarm, anti-aircraft defence",
"anti-aircraft alarm" : "воздушная тревога",
"anti-aircraft defence" : "противовоздушная оборона",
"anti..." : "противо... анти...",
"antic" : "шутовской, гротеск; See also: antics",
"anticipate" : "предвкушать [-усить], предчувствовать, предупреждать [-редить]",
"anticipation" : "ожидание, предчувствие; See also: in anticipation",
"anticipatory" : "a  предварительный; предупреждающий",
"antics" : "ужимки, шалости",
"antidote" : "противоядие",
"antigen" : "n  физиол. антиген",
"antimony" : "парадокс",
"antipathy" : "антипатия",
"antiperspirant" : "n  дезодорант",
"antipode" : "See: antipodes",
"antipodes" : "противоположности",
"antiquarian" : "антикварный",
"antiquary" : "антиквар",
"antiquated" : "устарелый, старомодный",
"antique" : "античный, старинный, античное произведение искусства, антикварная вещь",
"antiquity" : "древность, старина, античность",
"antithetic" : "прямо противоположный",
"antler" : "олений рог",
"antlers" : "оленьи рога",
"antonym" : "антоним",
"anus" : "заднепроходный канал",
"anvil" : "наковальня",
"anxiety" : "беспокойство, страстное желание, опасение",
"anxious" : "озабоченный, беспокоящийся",
"any" : "какой-нибудь, всякий любой, сколько-нибудь, несколько; See also: not any",
"anybody" : "кто-нибудь, всякий",
"anyhow" : "как-нибудь, так или иначе во всяком случае",
"anyone" : "кто-нибудь, всякий",
"anything" : "что-нибудь; See also: anything but",
"anything but" : "далеко не ... совсем не ...",
"anyway" : "в любом случае",
"anywhere" : "где-нибудь куда-нибудь",
"aorta" : "аорта",
"apace" : "быстро",
"apart" : "отдельно, порознь; See also: apart from",
"apart from" : "кроме",
"apartment" : "комната",
"apartments" : "квартира; See also: apartments house",
"apartments house" : "многоквартирный дом",
"apathetic" : "безразличный",
"apathy" : "вялость",
"apatite" : "n  мин. апатит",
"ape" : "обезьяна, подражать  [с]обезьянничать",
"aperient" : "слабительное средство",
"aperture" : "отверстие, проем",
"apex" : "верхушка",
"aphasia" : "потеря речи",
"aphelion" : "n  астр. афелий",
"aphid" : "тля растительная",
"aphorism" : "афоризм",
"aphrodite" : "n  греч. миф. Афродита",
"apices" : "See: apex",
"apiculture" : "пчеловодство",
"apiece" : "за штуку, за каждого с человека",
"apish" : "обезьяний, глупый",
"aplomb" : "отвесное положение",
"apocalypse" : "пророческое предвидение",
"apocalyptic" : "a  апокалипсический, апокалиптический",
"apocrypha" : "n pl  рел. апокрифические книги",
"apocryphal" : "недостоверный",
"apogee" : "апогей",
"apollo" : "аполлон"
};
