var dicctr_1 = {
"анкета" : "questionnaire, form",
"анна" : "anna",
"аннексировать" : "pf. annex",
"аннексия" : "annexation",
"аннулировать" : "pf. annul",
"анод" : "anode",
"анодный" : "anodic",
"аномалия" : "anomaly",
"анонимность" : "anonymity",
"анонимный" : "anonymous",
"ансамбль" : "ensemble",
"антагонизм" : "antagonism",
"антарктида" : "Antarctica",
"антарктика" : "Antarctic",
"антарктический" : "Antarctic",
"антенна" : "aerial, zo. antenna",
"анти" : "anti",
"антиквар" : "antiquary, dealer in antiquarian goods",
"антикварный" : "antiquarian",
"антилопа" : "antelope",
"антипатичный" : "antipathetic",
"антипатия" : "antipathy",
"антисанитарный" : "insanitary",
"антисептика" : "antisepsis, antiseptic",
"антитеза" : "antithesis",
"античность" : "antiquity",
"античный" : "antique",
"антология" : "anthology",
"антон" : "Anthony",
"антоним" : "antonym",
"антонина" : "Antonia",
"антракт" : "intermission Brt. interval, interlude",
"антрепренер" : "impresario",
"антрополог" : "anthropologist",
"антропология" : "anthropology",
"антураж" : "entourage",
"анчоус" : "anchovy",
"анютины глазки" : "pl. pansy, bot. bud, zo. ocellus eye, peephole",
"аорта" : "aorta",
"апатичный" : "apathetic",
"апатия" : "apathy",
"апеллировать" : "pf. appeal",
"апеллирующий" : "appellant",
"апелляционная жалоба" : "appeal",
"апелляционный" : "of appeal",
"апелляция" : "appeal",
"апельсин" : "orange",
"аплодировать" : "applaud",
"аплодисменты" : "applause",
"апогей" : "apogee",
"аполитичность" : "indifference toward politics",
"аполитичный" : "indifferent to politics",
"аполлон" : "apollo",
"апологический" : "apologetic",
"апология" : "apologia",
"апоплексия" : "apoplexy",
"апостол" : "apostle",
"апофеоз" : "apotheosis",
"аппарат" : "apparatus, camera",
"аппендикс" : "anat. appendix",
"аппендицит" : "appendicitis",
"апперкот" : "uppercut",
"аппетит" : "appetite, приятного аппетита! bon appetit!",
"аппетитный" : "appetizing",
"апрель" : "April",
"аптека" : "drugstore Brt. chemist's shop",
"аптекарь" : "druggist Brt. chemist",
"араб" : "Arab",
"арабка" : "Arab",
"арабский" : "Arabian Arabic, Arab",
"арап" : "Moor Negro",
"арапник" : "quirt",
"арахис" : "peanut",
"арбитр" : "arbiter, umpire",
"арбитраж" : "arbitration",
"арбуз" : "watermelon",
"аргентина" : "Argentina",
"аргентинец" : "Argentine",
"аргентинка" : "Argentine",
"аргентинский" : "Argentine",
"арго" : "argot",
"аргумент" : "argument",
"аргументация" : "argumentation",
"аргументировать" : "pf. argue",
"арена" : "arena, sphere",
"аренда" : "lease rent, сдавать в аренду lease",
"арендатор" : "lessee, tenant",
"арендованный" : "leased, leasehold",
"арендовать" : "pf. rent",
"арест" : "arrest",
"арестант" : "prisoner",
"арестантка" : "prisoner",
"арестованный" : "remand",
"арестовать" : "arrest",
"арестовывать" : "arrest",
"аристократ" : "aristocrat",
"аристократический" : "patrician",
"аристократия" : "aristocracy",
"арифметика" : "arithmetic",
"арифметический" : "arithmetic",
"ария" : "aria, air",
"арка" : "arc, arch",
"аркада" : "arcade",
"аркан" : "lariat, lasso",
"арктика" : "Arctic",
"арктический" : "arctic",
"армада" : "armada",
"арматура" : "fittings armature",
"армения" : "Armenia",
"армия" : "army",
"армянин" : "Armenian",
"армянка" : "Armenian",
"армянский" : "Armenian",
"аромат" : "aroma perfume fragrance",
"ароматический" : "aromatic fragrant",
"ароматный" : "aromatic fragrant",
"арсенал" : "arsenal",
"артель" : "workmen's cooperative association",
"артерия" : "artery",
"артикулировать" : "articulate",
"артиллерийский" : "artillery...",
"артиллерист" : "artilleryman",
"артиллерия" : "artillery",
"артист" : "artist, actor",
"артистка" : "artist, actress",
"артишок" : "artichoke",
"артрит" : "arthritis",
"арфа" : "harp",
"архаизм" : "archaism",
"архаический" : "archaic",
"архангел" : "archangel",
"археолог" : "archeologist",
"археологический" : "archeologic",
"археология" : "archeology",
"архив" : "archives pl.",
"архивариус" : "archivist, registrar",
"архивный" : "archival",
"архиепископ" : "archbishop",
"архипелаг" : "archipelago",
"архитектор" : "architect",
"архитектура" : "architecture",
"архитектурный" : "architectonic",
"аршин" : "arshine",
"арьергард" : "rear guard",
"асбест" : "asbestos",
"асептика" : "asepsis",
"асимметрия" : "asymmetry",
"аскетизм" : "asceticism",
"аскетический" : "ascetic",
"аспирант" : "candidate",
"аспирантский" : "postgraduate",
"аспирин" : "aspirin",
"ассамблея" : "Генеральная Ассамблея Организации Обьединенных Наций, United Nations General Assembly",
"ассортимент" : "assortment",
"ассоциация" : "association",
"ассоциировать" : "pf. associate",
"асср" : ", Autonomous Soviet Socialist Republic",
"астигматизи" : "astigmatism",
"астра" : "aster",
"астрология" : "astrology",
"астронавт" : "astronaut",
"астроном" : "astronomer",
"астрономический" : "astronomic",
"астрономия" : "astronomy",
"асфальт" : "asphalt",
"атавизм" : "atavism",
"атака" : "attack charge",
"атаковать" : "pf. attack charge",
"атаман" : "hetman",
"атеизм" : "atheism",
"атеист" : "atheist, infidel",
"ателье" : "studio atelier",
"атлантический" : "Atlantic...",
"атланты" : "atlantes",
"атлас" : "atlas, satin",
"атлас1" : "atlas",
"атлас2" : "satin",
"атлет" : "athlete",
"атлетика" : "athletics",
"атлетический" : "athletic",
"атмосфера" : "atmosphere",
"атмосферный" : "atmospheric",
"атом" : "atom",
"атомный" : "atomic",
"атональный" : "atonal",
"атрибут" : "apanage, appanage",
"атрибутивный" : "attributive",
"атташе" : "attache",
"аттестат" : "certificate",
"аудиенция" : "audience",
"аудитория" : "lecture hall, audience",
"аукцион" : "auction",
"аутизм" : "autism",
"афанасий" : "Athanasius",
"афганистан" : "Afghanistan",
"афганский" : "afghan",
"афера" : "speculation fraud shady deal",
"аферист" : "speculator swindler",
"аферистка" : "speculator swindler",
"афина" : "athena, athene",
"афины" : "Athens",
"афиша" : "playbill poster",
"афоризм" : "aphorism",
"африка" : "Africa",
"африканец" : "African",
"африканка" : "African",
"африканский" : "African",
"ах" : "ah!",
"ахать" : "groan lament, be amazed",
"ахнуть" : "groan lament, be amazed",
"ацетилен" : "acetylene",
"ацетон" : "acetone",
"аэробика" : "aerobic",
"аэродинамика" : "aerodynamics",
"аэродинамический" : "aerodynamic",
"аэродром" : "airdrome",
"аэрозоль" : "aerosol",
"аэронавигация" : "aerial navigation",
"аэроплан" : "airplane",
"аэропорт" : "airport",
"аэропочта" : "air mail",
"аэросани" : "snowmobile",
"аэроснимок" : "aerial view",
"аэростат" : "balloon",
"аэросьемка" : "aerial photography",
"баба" : "tup",
"бабенка" : "jane",
"бабий" : "womanish effeminate",
"бабка" : "grandmother, повивальная бабка midwife, pl. knucklebones",
"бабочка" : "butterfly",
"бабуин" : "baboon",
"бабушка" : "grandmother, granny, вот тебе бабушка и Юрьев день!, a pretty business this!",
"бабье лето" : "Indian summer",
"бабьи сказки" : "old wives' tales",
"багаж" : "baggage Brt. luggage, ручной багаж small baggage; See also: сдать в багаж",
"багажный" : "багажный вагон baggage car Brt. luggage van",
"багдад" : "baghdad",
"багровый" : "mulberry, murrey",
"бадминтон" : "badminton",
"базальт" : "basalt",
"базилик" : "basil",
"байка" : "baize",
"байт" : "byte",
"бак" : "fo,c,s,le, forecastle, tank",
"бакалавр" : "bachelor",
"бакалейные товары" : "= бакалея",
"бакалейный" : "бакалейный магазин; See also: бакалейная лавка, бакалейные товары",
"бакалейщик" : "grocer",
"бакен" : "buoy",
"баклажан" : "aubergine, eggplant"
};
