var dicctr_51 = {
"огрубелый" : "coarse hardened",
"огрубеть" : "harden become callous",
"огрызаться" : "snap",
"огрызнуться" : "snap",
"огрызок" : "bit end, stump stub",
"огузок" : "rump",
"огульный" : "wholesale indiscriminate, unfounded, a. in the lump",
"огурец" : "cucumber",
"ода" : "ode",
"одалживать" : "lend, borrow, oblige",
"одаренный" : "gifted",
"одаривать" : "present gift, fig. endow",
"одарить" : "present gift, fig. endow",
"одевать" : "dress",
"одежда" : "clothes pl. clothing",
"одеколон" : "cologne",
"оделить" : "s. одаривать",
"оделять" : "s. одаривать",
"одер" : "oder",
"одеревенелый" : "numb",
"одеревенеть" : "stiffen, grow numb",
"одержать" : "gain win",
"одерживать" : "gain win",
"одержимость" : "obsession",
"одержимый" : "obsessed  afflicted",
"одесса" : "odessa",
"одеть" : "dress",
"одеяло" : "blanket cover",
"одеяние" : "habiliment, vestment, vesture",
"один" : "one, alone, only, a a certain some, одно etc., & пятый; See also: один на один, все до одного, все как один",
"один на один" : "face to face, tete-a-tete, hand to hand",
"одинаковый" : "equal identical the same",
"одинешенек" : "famil. quite alone",
"одиннадцатый" : "eleventh, cf. пятый",
"одиннадцать" : "eleven, cf. пять",
"одинокий" : "lonely, single, lonesome",
"одиночество" : "solitude loneliness",
"одиночка" : "lone person, individualist, one-man boat",
"одиночкой" : "alone",
"одиночный" : "single solitary, individual, one-man...",
"одиссей" : "odysseus",
"одиссея" : "odyssey",
"одичалый" : "wild",
"одичать" : "run wild, fig. grow shy unsociable, shun",
"одна" : "one, alone, only, a a certain some, одно etc., & пятый; See also: один на один, все до одного, все как один",
"однажды" : "once one day",
"однако" : "however yet still",
"однако ж" : "however yet still",
"одновалентный" : "monovalent, univalent",
"одновременный" : "simultaneous",
"одноглазый" : "one-eyed",
"однодневный" : "one-day",
"однозвучный" : "monotonous",
"однозначный" : "synonymous  math. simple of one place",
"одноименный" : "of the same name",
"одноклассник" : "classmate",
"одноколейный" : "single-track",
"однокоренной" : "cognate",
"однократный" : "occurring once single gr. momentary",
"однолетний" : "one-year bot. annual",
"однолеток" : "coeval",
"одноместный" : "single-seated",
"однообразный" : "monotonous",
"однополюсный" : "unipolar",
"однорогий" : "unicorn",
"однородность" : "homogeneity",
"однородный" : "homogeneous",
"однорукий" : "one-armed",
"односложный" : "monosyllabic",
"односторонний" : "one-sided  unilateral",
"однофамилец" : "namesake",
"одноцветный" : "monochromatic plain",
"одночленный" : "monomial",
"одноэтажный" : "one-storied",
"одобрение" : "approval approbation",
"одобренный" : "approved, authorized",
"одобрительный" : "approving",
"одобрить" : "approve",
"одобрять" : "approve",
"одолевать" : "overcome defeat, famil. exhaust, master",
"одолеть" : "overcome defeat, famil. exhaust, master",
"одолжение" : "favor",
"одолжить" : "lend, borrow, oblige",
"одометр" : "odometer",
"одр" : "bed couch, bier",
"одуванчик" : "dandelion",
"одуматься" : "change one's mind",
"одумываться" : "change one's mind",
"одурачить" : "fool hoax",
"одуреть" : "grow stupid, become stupefied",
"одурманенный" : "besotted, dopey",
"одурманивать" : "stupefy",
"одурманить" : "stupefy",
"одурь" : "stupor",
"одурять" : "stupefy",
"одутловатый" : "puffed up",
"одухотворить" : "inspire",
"одухотворять" : "inspire",
"одушевить" : "animate inspire",
"одушевленный" : "gr. animate",
"одушевлять" : "animate inspire",
"одышка" : "short wind",
"ожерелье" : "necklace",
"ожесточать" : "harden, exasperate",
"ожесточение" : "exasperation, bitterness",
"ожесточенный" : "a. violent fierce bitter",
"ожесточить" : "harden, exasperate",
"оживать" : "revive",
"оживить" : "vivify animate",
"оживление" : "animation",
"оживленно" : "lifelike",
"оживленность" : "ginger",
"оживленный" : "animated lively, bright",
"оживлять" : "enliven animate resuscitate, -ся quicken revive, brighten",
"ожидание" : "expectation; See also: зал ожидания",
"ожидать" : "wait, expect await",
"ожидающий" : "expectant",
"ожиреть" : "grow fat",
"ожить" : "revive",
"ожог" : "burn, scald",
"озаботить" : "disquiet alarm, -ся attend to",
"озабоченность" : "solicitude",
"озабоченный" : "anxious solicitous, preoccupied",
"озабочивать" : "disquiet alarm, -ся attend to",
"озаглавить" : "entitle supply with a title",
"озаглавливать" : "entitle supply with a title",
"озадачивать" : "puzzle perplex",
"озадачить" : "puzzle perplex",
"озарить" : "illuminate light up, brighten lighten",
"озарять" : "illuminate light up, brighten lighten",
"озвереть" : "pf. become brutal",
"оздоровить" : "reorganize reform improve",
"оздоровлять" : "reorganize reform improve",
"озерный" : "lacustrine",
"озеро" : "lake",
"озимый" : "winter",
"озираться" : "look",
"озирис" : "osiris",
"озлобить" : "exasperate embitter",
"озлобление" : "exasperation",
"озлоблять" : "exasperate embitter",
"ознакомить" : "familiarize",
"ознакомлять" : "familiarize",
"ознаменование" : "commemoration",
"ознаменовать" : "mark commemorate celebrate",
"ознаменовывать" : "mark commemorate celebrate",
"означать" : "signify mean",
"означающий" : "denotative",
"озноб" : "chill",
"озон" : "ozone",
"озорник" : "s. шалун, popul. ruffian",
"озорница" : "s. шалун, popul. ruffian",
"озорничать" : "s. шалить, popul. behave outrageously",
"озорной" : "mischievous naughty",
"озорство" : "mischief, outrage excess",
"озябнуть" : "feel chilly, freeze",
"окаменевать" : "petrify",
"окаменелый" : "fossil",
"окаменение" : "calcification, petrifaction",
"окапывать" : "dig round, entrench",
"окарина" : "ocarina",
"окаянный" : "damned cursed",
"океан" : "ocean",
"океанография" : "oceanography",
"океанский" : "ocean",
"окидывать" : "take a view of look at",
"окинуть" : "take a view of look at",
"окислитель" : "oxidant",
"окислить" : "oxidize",
"окислять" : "oxidize",
"окись" : "oxide",
"оккупационный" : "occupation...",
"оккупировать" : "pf. occupy",
"оклад" : "salary, tax rate",
"окладистый" : "full",
"оклеветать" : "slander",
"оклеивать" : "paste, paper",
"оклеить" : "paste, paper",
"оклик" : "call hail",
"окликать" : "call hail",
"окликнуть" : "call hail",
"окно" : "window",
"око" : "eye",
"оковать" : "s. оковывать",
"оковы" : "fetters",
"оковывать" : "bind, fetter",
"околдовать" : "pf. bewitch",
"околевать" : "die",
"околеть" : "die",
"околица" : "& обиняк",
"около" : "about around, by at near, nearby",
"околыш" : "cap-band",
"окольный" : "roundabout",
"оконный" : "window...",
"окончание" : "end close termination completion  conclusion",
"окончательный" : "final definitive",
"окончить" : "finish end",
"окоп" : "trench",
"окопать" : "dig round, entrench",
"окорок" : "ham",
"окостенелый" : "ossified, hardened, окоченелый",
"окостенеть" : "ossify, stiffen grow numb, be transfixed",
"окот" : "lambing",
"окоченелый" : "numb",
"окоченеть" : "grow numb stiffen",
"окошечко" : "dim. #of окно",
"окошко" : "dim. #of окно",
"окраина" : "outskirts pl.",
"окрасить" : "paint color dye, famil. накрасить paint make up, rouge",
"окровавленный" : "gory",
"округлый" : "roundish",
"округлять" : "round",
"окружать" : "surround",
"окружающий" : "surrounding",
"окружение" : "environment, environs pl. neighborhood, encirclement, circle company",
"окружить" : "surround",
"окружной" : "district..., circular",
"окружность" : "circumference, circle, obsol. vicinity",
"окрылить" : "fig. wing encourage",
"окрылять" : "fig. wing encourage",
"оксфордский" : "oxford, oxonian",
"октава" : "octave",
"октановый" : "octane",
"октет" : "octet",
"октябрь" : "October",
"октябрьский" : "October",
"окукливаться" : "pupate",
"окулировать" : "pf. graft",
"окуляр" : "eyepiece",
"окунать" : "dip plunge",
"окунуть" : "dip plunge",
"окунь" : "perch",
"окупать" : "offset recompense compensate",
"окупить" : "offset recompense compensate",
"окуривать" : "fumigate",
"окурок" : "cigarette end cigar stub",
"окутать" : "wrap",
"окутывать" : "wrap",
"оладьи" : "fritter",
"оладья" : "fritter",
"олеандр" : "oleander",
"оледенелый" : "frozen iced",
"оледенеть" : "freeze ice, grow numb, chill",
"оледенить" : "freeze ice, chill",
"олененок" : "fawn",
"олений" : "cervine, reindeer",
"оленина" : "venison",
"олень" : "deer",
"олень-самец" : "buck, hart, stag",
"олеомаргарин" : "oleomargarine"
};
