var dicctr_70 = {
"проезжать" : "проехать, pass drive #or ride through, travel; See also: проезжаться",
"проезжаться" : "famil. take a drive #or ride, проездить break in, famil. spend",
"проезжая дорога" : "highway",
"проезжий" : "traveller transient; See also: проезжая дорога",
"проект" : "project plan scheme, draft",
"проектировать" : "project plan",
"проектировщик" : "projector",
"проекционный аппарат" : "projector",
"проесть" : "eat away #or through, famil. spend, eat",
"проехать" : "s. проезжать",
"прожектор" : "searchlight",
"прожекторный" : "searchlight",
"прожечь" : "burn; See also: прожигать жизнь",
"проживать" : "live, famil. spend",
"прожигать" : "burn; See also: прожигать жизнь",
"прожигать жизнь" : "famil. live fast",
"прожиточный минимум" : "living wage",
"прожить" : "live, famil. spend",
"прожорливость" : "gluttony voracity",
"прожорливый" : "gluttonous",
"проза" : "prose",
"прозаик" : "prose writer",
"прозаический" : "prosaic",
"прозвать" : "s. прозывать",
"прозвенеть" : "ring jingle clink, у меня звенит в ушах my ears ring",
"прозвище" : "nickname; See also: по прозвищу",
"прозвучать" : "sound, ring, clang",
"прозевать" : "pf. miss, let slip",
"прозорливый" : "perspicacious",
"прозрачный" : "transparent",
"прозреть" : "pf. recover one's sight, see perceive",
"прозывать" : "nickname",
"прозябать" : "vegetate",
"прозябнуть" : "s. продрогнуть",
"проиграть" : "lose, famil. play, -ся lose all one's money",
"проигрывать" : "lose, famil. play, -ся lose all one's money",
"проигрыш" : "loss",
"произведение" : "work product",
"произвести" : "s. производить",
"производитель" : "producer",
"производительность" : "productivity, output",
"производительный" : "productive",
"производить" : "make  carry out execute effect, produce, bring forth, promote, impf. derive",
"производный" : "derivative",
"производственный" : "production..., manufacturing, works..., industrial",
"производство" : "production manufacture, plant works factory, execution, promotion",
"произвол" : "arbitrariness, mercy, despotism tyranny",
"произвольный" : "arbitrary",
"произнести" : "pronounce, deliver make, utter",
"произносимый" : "vocable",
"произносить" : "pronounce, deliver make, utter",
"произношение" : "pronouncing, pronunciation",
"произношение n" : "pronunciation",
"произойти" : "s. происходить",
"проинформировать" : "inform",
"происки" : "intrigues",
"происходить" : "take place happen, arise originate, descend",
"происхождение" : "origin  descent",
"происшествие" : "incident occurrence event",
"пройти" : "& прохаживаться",
"прокаженный" : "leper, leprous",
"проказа" : "leprosy",
"проказливый" : "arch, elfin",
"проказничать" : "s. шалить",
"прокалывать" : "pierce stick stab",
"прокапывать" : "dig",
"прокармливать" : "support nourish, feed",
"прокармливаться" : "famil. subsist",
"прокат" : "hire  lease, distribution; See also: отдать в прокат",
"прокатать" : "mangle, engin. roll, ride, -ся s. прокатиться",
"прокатить" : "pf. give a drive #or ride",
"прокладка" : "laying",
"проклинать" : "anathematize, execrate, imprecate",
"проклясть" : "curse damn",
"проклятие" : "damnation",
"проклятый" : "cursed damned",
"прокол" : "perforation",
"проколоть" : "pierce stick stab",
"прокомпостировать" : "punch",
"проконсультировать" : "advise, -ся consult",
"проконтролировать" : "control check",
"прокопать" : "dig",
"прокормить" : "fig. maintain support",
"прокормление" : "support",
"прокорректировать" : "correct, typ. proofread",
"прокрадываться" : "steal, go stealthily",
"прокрасться" : "steal, go stealthily",
"прокрустов" : "procrustean",
"проксимальный" : "proximal",
"прокурор" : "public prosecutor",
"пролагать" : "s. прокладывать",
"проламывать" : "break, fracture",
"пролегать" : "run",
"пролезать" : "creep #or get",
"пролезть" : "creep #or get",
"пролепетать" : "babble prattle",
"пролет" : "passage, flight, arch. span, well",
"пролетариат" : "proletariat",
"пролетарий" : "proletarian",
"пролетарский" : "proletarian",
"пролетать" : "fly  pass",
"пролететь" : "fly  pass",
"пролетка" : "droshky",
"пролив" : "strait",
"проливать" : "spill, shed",
"проливной дождь" : "downpour cloudburst",
"пролить" : "spill, shed",
"пролог" : "prologue",
"проложить" : "lay, fig. pave, force  interlay, draw",
"пролом" : "breach, fracture",
"проломать" : "break, fracture",
"проломить" : "break, fracture",
"промах" : "miss, blunder",
"промахиваться" : "miss, blunder",
"промахнуться" : "miss, blunder",
"промедление" : "delay",
"промедлить" : "delay linger be slow #or tardy hesitate",
"промежуток" : "interval, period",
"промежуточный" : "intermediate",
"промелькнуть" : "s. мелькать",
"променивать" : "exchange",
"променять" : "exchange",
"промерзать" : "freeze, s. продрогнуть",
"промерзнуть" : "freeze, s. продрогнуть",
"прометей" : "prometheus",
"промешкать" : "= медлить",
"промокательная бумага" : "blotting paper",
"промокать" : "get wet #or drenched",
"промокнуть" : "become wet, soak",
"промокший" : "saturate",
"промолчать" : "pf. keep silent",
"промочить" : "pf. wet drench",
"промтовары" : "s. ширпотреб",
"промчаться" : "pf. dash #or fly",
"промывать" : "wash, med. irrigate",
"промывка" : "ablution, flushing",
"промысел" : "trade business, field, works",
"промысловый" : "trade ...",
"промыть" : "wash, med. irrigate",
"промышленник" : "industrialist",
"промышленность" : "industry",
"промышленный" : "industrial",
"пронести" : "s. проносить",
"пронзать" : "pierce, transfix",
"пронзительный" : "goring, keen, penetrative, piercing, piping",
"проникать" : "penetrate",
"проницаемый" : "penetrable, permeable, pervious",
"проницательность" : "acumen, discernment, discrimination, insight",
"проницательный" : "penetrating searching, acute shrewd",
"проницать" : "s. проникать",
"проносить" : "пронести, carry, speed, famil. wear out",
"проноситься" : "fly  pass #or spread",
"пронумеровать" : "number",
"пронырливый" : "crafty",
"пронюхать" : "smell out",
"прообраз" : "prototype",
"пропаганда" : "propaganda",
"пропагандировать" : "propagandize",
"пропагандистский" : "propagandist..., propaganda...",
"пропадать" : "get #or be lost be gone, be, lose fail, vanish, perish die",
"пропажа" : "loss",
"пропасть" : "get #or be lost be gone, be, lose fail, vanish, perish die",
"пропасть1" : "s. пропадать",
"пропасть2" : "precipice abyss, chasm gap, disaster, famil. lots #or a lot",
"пропивать" : "spend, drink",
"прописать" : "s. прописывать",
"пропитанный" : "sodden",
"пропитывать" : "soak",
"проповедовать" : "preach",
"проповедь" : "gospel, homily, preaching, preachment, sermon",
"проползти" : "creep",
"прополка" : "weeding",
"прополоскать" : "rinse, gargle",
"прополоть" : "weed",
"пропорциональный" : "proportional proportionate",
"пропорция" : "ratio",
"пропуск" : "omission blank, absence, pass, milit. password",
"пропускать" : "let pass, pass, omit, miss, let slip, impf. leak",
"пропускать мимо ушей" : "turn a deaf ear",
"пропускной" : "blotting",
"пропустить" : "let pass, pass, omit, miss, let slip, impf. leak",
"прорабатывать" : "study",
"проработать" : "study",
"прорастать" : "grow, come up",
"прорасти" : "grow, come up",
"прорвать" : "s. прорывать",
"прорезать" : "cut",
"прорезаться" : "cut",
"прорезиненный" : "gummed",
"прорезываться" : "teethe",
"прорезь" : "slit, slot",
"прорепетировать" : "rehearse",
"прореха" : "slit hole tear",
"прорецензировать" : "review",
"прорицатель" : "augur, python",
"пророк" : "prophet",
"проронить" : "pf. utter",
"пророческий" : "prophetic",
"пророчество" : "prophecy",
"пророчить" : "prophesy",
"прорубать" : "cut",
"прорубить" : "cut",
"прорубь" : "ice-hole",
"прорыв" : "break, breach, gap arrear hitch",
"прорывать" : "прорвать, tear, break through, прорыть dig",
"просачивание" : "infiltration, seepage",
"просачиваться" : "ooze  percolate",
"просверливать" : "perforate",
"просверлить" : "pf. bore",
"просвет" : "gleam glimpse, chink, arch. bay opening, fig. hope",
"просветительный" : "of enlightenment, educational",
"просветить" : "& просвечивать",
"просветлеть" : "pf. clear up brighten",
"просвечивать" : "shine through be seen, просветить radiograph X-ray, test",
"просвечивающий" : "translucent",
"просвещать" : "enlighten educate instruct",
"просвещение" : "enlightenment education instruction",
"просвирник" : "mallow",
"проседь" : "grayish  grizzly",
"просеивать" : "sift",
"просека" : "glade",
"проселок" : "by-road field path",
"проселочная дорога" : "by-road field path",
"просеять" : "sift",
"просидеть" : "sit, stay remain, spend, famil. wear out",
"просиживать" : "sit, stay remain, spend, famil. wear out",
"проситель" : "petitioner applicant",
"просительница" : "petitioner applicant",
"просить" : "ask  request, entreat, invite, intercede, прошу просят a. please",
"просить слово" : "ask permission to speak",
"проситься" : "ask, leave [to enter go]???, o.s.",
"просиять" : "pf. shine forth brighten",
"проскользнуть" : "pf. slip",
"проскочить" : "pf. jump #or slip",
"проскрипеть" : "creak, scratch, grit gnash",
"прославить" : "glorify make famous",
"прославление" : "apotheosis",
"прославлять" : "glorify make famous",
"проследить" : "pf. follow up",
"прослезиться" : "pf. shed tears",
"прослойка" : "streak layer",
"прослушать" : "pf. hear, med. auscultate, famil. miss",
"прослушивание" : "audition",
"прослыть" : "pass for have the reputation of",
"просматривать" : "look through #or over, overlook",
"просмотр" : "examination review revision, oversight",
"просмотреть" : "look through #or over, overlook",
"проснуться" : "s. просыпаться",
"просо" : "millet",
"просовывать" : "pass #or push"
};
