var dicctr_45 = {
"натуга" : "strain effort",
"натуго" : "famil. tight",
"натуживать" : "strain exert",
"натужить" : "strain exert",
"натура" : "nature, model; See also: натурой, в натуре, с натуры",
"натуральный" : "natural",
"натурой" : "in kind",
"натурщик" : "model",
"натурщица" : "model",
"натыкаться" : "run against across",
"натягивать" : "stretch strain, pull, draw in",
"натяжка" : "strain, affectation forced #or strained argument detail trait etc., с натяжкой a. with great reserve",
"натянутый" : "strained forced affected far-fetched, tense bad",
"натянуть" : "stretch strain, pull, draw in",
"наугад" : "at random",
"наудачу" : "at random",
"наука" : "science, lesson",
"наутек" : "famil. to one's heels",
"наутро" : "the next morning",
"научать" : "teach, -ся learn",
"научить" : "teach, -ся learn",
"научный" : "scientific",
"научный деятель" : "scientist",
"наушник" : "informer",
"наушники" : "earflaps, headphones",
"нахал" : "impudent fellow",
"нахальный" : "impudent insolent",
"нахальство" : "impudence insolence",
"нахватать" : "snatch  pick up",
"нахватывать" : "snatch  pick up",
"нахлынуть" : "pf. rush",
"нахмуривать" : "= хмурить cf.",
"нахмурить" : "knit",
"находить" : "find, come, cover, be seized with, impf. take",
"находиться" : "be, happen to have, not to be at a loss",
"находка" : "find, famil. discovery; See also: бюро находок",
"находчивый" : "resourceful, ready-witted smart",
"нацизм" : "nazism",
"национализовать" : "pf. nationalize",
"нацистский" : "nazi",
"нация" : "nation",
"начало" : "beginning, commencement, inception, proem, start",
"начальник" : "chief, superintendent, warden",
"начальный" : "inceptive, initiatory, primary",
"начатки" : "pl.",
"начать" : "s. начинать",
"начинать" : "began, begin, begun, commence",
"начинающий" : "beginner, catechumen",
"начитаться" : "read, have enough; See also: не мочь начитаться",
"наш" : "our, ours; See also: по-нашему, наша взяла{!}",
"наш брат" : "famil. we",
"наша" : "our, ours; See also: по-нашему, наша взяла{!}",
"наша взяла" : "we've won!",
"нашептывать" : "earwig",
"нащупывать" : "fumble, grope",
"наяву" : "in reality, waking, not, no; See also: наяву то",
"наяву то" : "famil. else",
"наяда" : "naiad",
"не" : "non, not",
"не более" : "at most",
"не в духе" : "in a bad temper #or in low spirits in no mood to",
"не в силах" : "unable",
"не выпускать из виду" : "keep in view",
"не говоря уже о" : "let alone",
"не дай бог" : "God forbid!",
"не дальше как" : "this very, only",
"не дальше чем" : "this very, only",
"не дать в обиду" : "let not be offended",
"не за что" : "welcome Brt. don't mention it",
"не иначе, как" : "just",
"не к месту" : "out of place",
"не может быть" : "that's impossible!",
"не раз" : "repeatedly",
"не стоит благодарности" : "you are welcome Brt. don't mention it",
"не так" : "wrong",
"не терять из виду" : "keep in view",
"не то, чтобы" : "not that",
"не тот" : "wrong",
"не ударить лицом в грязь" : "save one's face",
"неадекватность" : "inadequacy",
"неаккуратный" : "careless, inaccurate, unpunctual",
"неаполитанский" : "neapolitan",
"небез" : "rather ... not without ...",
"небезопасный" : "insecure",
"неблагодарность" : "ingratitude",
"неблагодарный" : "ingrate, thankless, ungrateful, unthankful",
"неблагонадежный" : "unreliable",
"неблагополучный" : "unfortunate adverse bad, adv. not well wrong",
"неблагоприятный" : "unfavorable negative",
"неблагоразумный" : "imprudent, unreasonable",
"неблагородный" : "ignoble, indelicate",
"неблагосклонный" : "unkindly, unfavorable",
"небный" : "palatine",
"небо" : "heaven, palate, sky, welkin",
"небо1" : "sky, heaven, air",
"небо2" : "palate",
"небогатый" : "modest, poor",
"небольшой" : "small, short, ... с небольшим ... odd",
"небосвод" : "firmament, horizon",
"небоскреб" : "skyscraper",
"небось" : "famil. I suppose, sure",
"небрежный" : "careless negligent",
"небывалый" : "unheard-of unprecedented",
"небылица" : "tale fable invention",
"небьющийся" : "unbreakable",
"нева" : "Neva",
"неважный" : "unimportant trifling, famil. poor bad",
"невдалеке" : "not far off #or from",
"неведение" : "ignorance",
"неведомый" : "unknown",
"невежа" : "boor",
"невежда" : "ignoramus",
"невежественный" : "ignorant, unintelligent",
"невежество" : "ignorance",
"невежливость" : "incivility",
"невежливый" : "impolite uncivil",
"неверие" : "unbelief",
"неверный" : "incorrect, false, unfaithful, unsteady, su. infidel",
"невероятный" : "incredible",
"неверующий" : "unbelieving",
"невесомый" : "imponderable",
"невеста" : "fiancee bride, famil. marriageable girl",
"невестка" : "daughter-in-law, sister-in-law",
"невзгода" : "adversity misfortune, affliction",
"невзгоды" : "misery",
"невзирая" : "in spite of despite, without respect",
"невзначай" : "famil. unexpectedly by chance",
"невзрачный" : "plain homely mean",
"невзыскательный" : "unpretentious",
"невиданный" : "singular unprecedented",
"невидимый" : "invisible",
"невинный" : "innocent, virgin",
"невкусный" : "insipid",
"невменяемый" : "irresponsible",
"невмешательство" : "nonintervention",
"невнимание" : "inattention",
"невнимательный" : "inattentive",
"невнятный" : "in distinct inarticulate, unintelligible",
"невод" : "seine",
"невозвратимый" : "irretrievable irreparable",
"невозвратный" : "irretrievable irreparable",
"невозвращенец" : "non-returnee",
"невозделанный" : "fallow",
"невоздержанность" : "insobriety, intemperance",
"невоздержанный" : "intemperate, unbridled uncontrolled",
"невозможный" : "impossible",
"невозмутимый" : "imperturbable",
"неволить" : "force compel",
"невольник" : "slave, captive",
"невольный" : "involuntary, forced",
"неволя" : "captivity, bondage, need necessity",
"невообразимый" : "unimaginable",
"невооруженный" : "unarmed",
"невооруженным глазом" : "with the naked eye",
"невоспитанный" : "ill-bred",
"невосприимчивый" : "immune, insusceptible, unsusceptible",
"невпопад" : "s. некстати",
"невралгия" : "neuralgia",
"невральный" : "neural",
"невредимый" : "sound unhurt",
"неврит" : "neuritis",
"невроз" : "neurosis",
"неврология" : "neurology",
"невропатология" : "neuropathology",
"невротический" : "neurotic",
"невыгодный" : "unprofitable, disadvantageous",
"невыдержанный" : "unbalanced uneven, unseasoned",
"невыносимый" : "unbearable intolerable",
"невыполнение" : "nonfulfillment",
"невыполнимый" : "s. неисполнимый",
"невыраженный" : "ulterior, wordless",
"невыразимый" : "inexpressible ineffable",
"невыразительный" : "inexpressive",
"невысокий" : "low small, short, inferior slight",
"нега" : "luxury comfort, bliss delight, affection",
"негармоничный" : "inharmonious",
"негде" : "there is no",
"негибкий" : "inflexible",
"негласный" : "secret private",
"негодный" : "useless, unfit, famil. nasty",
"негодование" : "indignation",
"негодовать" : "be indignant",
"негодующий" : "indignant",
"негодяй" : "scoundrel rascal",
"негостеприимный" : "inhospitable",
"негр" : "Negro",
"неграмотность" : "s. безграмотность",
"неграмотный" : "s. безграмотный",
"негритянка" : "Negress",
"негритянский" : "Negro...",
"негроидный" : "negroid",
"негуманный" : "inhumane",
"недавний" : "recent, с недавних пор of late",
"недавно" : "recently",
"недалекий" : "near close, short, not far, recent, dull stupid",
"недальновидный" : "short-sighted",
"недаром" : "not in vain not without reason, justly",
"недвижимый" : "immovable",
"недействительный" : "invalid void, ineffective ineffectual",
"недействующий" : "inofficious, inoperable",
"неделимый" : "indivisible",
"недельный" : "a week's weekly",
"неделя" : "week, в неделю a #or per week, на этой неделе this week",
"недоброжелательный" : "unkindly ill-natured",
"недоброкачественный" : "inferior off-grade",
"недобросовестный" : "unfair, unprincipled, careless",
"недобрый" : "unkind hostile, evil bad ill",
"недоверие" : "distrust",
"недоверчивость" : "incredulity",
"недоверчивый" : "distrustful",
"недовольный" : "dissatisfied discontented",
"недовольство" : "discontent dissatisfaction",
"недогадливый" : "slow-witted",
"недоедание" : "malnutrition",
"недоедать" : "not eat enough",
"недоимки" : "arrears",
"недолго" : "not long short, famil. easily",
"недомогание" : "indisposition, malaise",
"недомогать" : "be unwell sick",
"недомолвка" : "omission",
"недоносок" : "abortion",
"недооценивать" : "underestimate undervalue",
"недооценить" : "underestimate undervalue",
"недопустимый" : "inadmissible, intolerable impossible",
"недоразвитый" : "underdeveloped",
"недоразумение" : "misunderstanding",
"недорогой" : "inexpensive",
"недоросль" : "greenhorn, ignoramus",
"недослышать" : "pf. fail to hear",
"недосмотр" : "oversight inadvertence",
"недосмотреть" : "pf. overlook",
"недоставать" : "impers.: lack want, be short #or in want of, miss, этого еще недоставало! and that too!",
"недостаток" : "want  lack shortage, deficiency, defect shortcoming, privation",
"недостаточный" : "insufficient deficient inadequate, gr. defective",
"недостать" : "impers.: lack want, be short #or in want of, miss, этого еще недоставало! and that too!",
"недостижимый" : "unattainable",
"недостоверный" : "apocryphal",
"недостойный" : "unworthy",
"недоступный" : "inaccessible",
"недосуг" : "lack of time; See also: мне недосуг",
"недосягаемый" : "unattainable",
"недоуздок" : "halter",
"недоумевать" : "puzzle",
"недоумение" : "bewilderment; See also: в недоумении",
"недочет" : "deficit, defect",
"недра" : "bosom entrails",
"недружелюбный" : "unfriendly",
"недуг" : "ailment infirmity",
"недурной" : "not bad pretty nice handsome",
"недюжинный" : "remarkable"
};
