var dicctr_65 = {
"посетитель" : "visitor caller",
"посетительница" : "visitor caller",
"посетить" : "s. посещать",
"посещаемость" : "attendance",
"посещать" : "visit call on, impf. attend",
"посещение" : "visit  call",
"посеять" : "sow",
"посильный" : "according to one's strength #or possibilities adequate equal to",
"посинеть" : "turn blue",
"поскользнуться" : "pf. slip",
"поскольку" : "inasmuch as as",
"поскупиться" : "be stingy  stint",
"послабление" : "indulgence",
"посланец" : "missionary",
"послание" : "message, epistle",
"посланник" : "envoy, messenger",
"послать" : "s. посылать",
"после" : "after; See also: после чего",
"после чего" : "whereupon, adv. after later",
"послевоенный" : "postwar",
"последний" : "last, latest, ultimate final, latter, worst, highest",
"последователь" : "follower",
"последовательность" : "consecution, consistency, sequence, succession",
"последовательный" : "consistent, successive",
"последствие" : "consequence",
"последующий" : "following",
"послезавтра" : "the day after tomorrow",
"послеоперационный" : "postoperative",
"послесловие" : "epilogue",
"пословица" : "proverb",
"послужить" : "serve, work, be",
"послушание" : "obedience",
"послушать" : "listen  hear, attend, med. auscultate; See also: слушай{!}, слушаю{!}",
"послушник" : "novice",
"послушный" : "obedient, docile",
"посматривать" : "look",
"посмеиваться" : "chuckle, laugh",
"посмертный" : "posthumous",
"посметь" : "dare venture, beg",
"посмешище" : "laughingstock",
"посмеяние" : "ridicule",
"посмотреть" : "look  gaze, view see watch, examine inspect, mind, look out",
"пособие" : "grant, relief dole benefit, aid means, textbook manual",
"пособить" : "help remedy",
"пособлять" : "help remedy",
"посоветовать" : "advise",
"посодействовать" : "assist help cooperate, contribute  further promote",
"посол" : "ambassador",
"посольство" : "embassy",
"посох" : "staff stick",
"поспать" : "pf. nap",
"поспевать" : "ripen, famil. = успевать, be done, get ready",
"поспеть" : "ripen, famil. = успевать, be done, get ready",
"поспешность" : "haste",
"поспешный" : "hasty hurried, rash",
"поспорить" : "dispute argue debate, quarrel, famil. bet, poet. fight",
"поспособствовать" : "promote further contribute to",
"посреди" : "amid in the middle",
"посредник" : "mediator intermediary middleman",
"посреднический" : "intermediary",
"посредничество" : "mediation",
"посредственность" : "mediocrity",
"посредственный" : "middling, mediocre, посредственно a. fair satisfactory C",
"посредство" : "при посредстве; See also: через посредство, посредством",
"посредством" : "by means of",
"поставить" : "affix",
"поставщик" : "procurer, provider, purveyor, shipper",
"постановление" : "bylaw",
"постановлять" : "decide, decree",
"постановщик" : "stage manager director",
"постараться" : "endeavor try, strive",
"постелить" : "s. стлать",
"постель" : "bed",
"постепенный" : "gradual",
"постесняться" : "feel shy self-conscious #or embarrassed, be ashamed of, hesitate",
"постигать" : "comprehend grasp, overtake",
"постигнуть" : "comprehend grasp, overtake",
"постижимый" : "conceivable",
"постилать" : "s. стлать",
"поститься" : "fast",
"постичь" : "comprehend grasp, overtake",
"постлать" : "spread lay, make",
"постный" : "fast..., vegetable, famil. lean, fig. sour, sanctimonious",
"постовой" : "sentry",
"постой" : "quarters billets pl.",
"постольку" : "insomuch",
"посторониться" : "make way step aside, avoid shun; See also: сторонись{!}",
"посторонний" : "strange outside foreign, unauthorized, accessory secondary",
"постоялый двор" : "inn",
"постоянный" : "constant permanent, continual continuous, steady, milit. standing, el. direct",
"постоянство" : "constancy",
"пострадавший" : "injured",
"пострадать" : "suffer, famil. be poor",
"пострел" : "scapegrace rogue",
"постригать" : "cut, make a monk #or nun",
"постричь" : "cut, make a monk #or nun",
"построение" : "construction, building",
"построиться" : "be built, build a house, milit. fall in",
"постройка" : "construction, building",
"постскриптум" : "postscript",
"постулат" : "postulate",
"поступательный" : "progressive",
"поступать" : "act, treat deal  handle, enter join matriculate, become, come in be received",
"поступаться" : "renounce",
"поступить" : "act, treat deal  handle, enter join matriculate, become, come in be received",
"поступить на военную службу" : "enlist join",
"поступиться" : "renounce",
"поступление" : "entrance entry, matriculation, receipt",
"поступок" : "act, behavior conduct",
"поступь" : "gait step",
"постучать" : "knock, rap tap, throb, chatter, clatter rattle, стучат there's a knock at the door, стукнуть s. исполниться",
"постыдиться" : "be ashamed",
"постыдный" : "shameful",
"постылый" : "odious",
"постящийся" : "abstinent, fasting",
"посуда" : "crockery, service pl., famil. vessel",
"посудный" : "cup, dish",
"посудомойка" : "dishwasher",
"посулить" : "promise",
"посуточный" : "daily, 24 hours'",
"посчастливиться" : "pf.: ему посчастливилось, he succeeded #or was lucky",
"посылать" : "send, dispatch",
"посылка" : "dispatch sending, package parcel, premise, a. побегушки",
"посыльный" : "messenger",
"посыпать" : "strew, sprinkle",
"посыпаться" : "pf. fall down, famil. shower",
"посягательство" : "encroachment",
"посягать" : "encroach  attempt",
"посягнуть" : "encroach  attempt",
"пот" : "sweat, весь в поту sweating all over",
"потайной" : "secret",
"потакать" : "connive",
"потасовка" : "scuffle, thrashing",
"поташ" : "potash",
"потворство" : "indulgence connivance",
"потворствовать" : "indulge connive",
"потемки" : "darkness",
"потенциал" : "potential",
"потенциальный" : "potential",
"потенциометр" : "potentiometer",
"потеплеть" : "grow warm",
"потерпевший" : "wrecked",
"потерпеть" : "suffer endure, tolerate bear stand, not press permit of delay, не -ся impf. be impatient #or eager",
"потертый" : "shabby worn",
"потеря" : "loss, waste",
"потерянный" : "lost",
"потерять" : "lose, waste, shed, give up",
"потеть" : "sweat  perspire",
"потеха" : "fun famil. lark",
"потешать" : "entertain amuse",
"потешить" : "entertain amuse",
"потешный" : "funny amusing",
"потирать" : "rub",
"потихоньку" : "famil. slowly, silently, secretly on the sly",
"потный" : "sweaty",
"поток" : "stream, torrent, flow",
"потолок" : "ceiling",
"потолстеть" : "grow stout",
"потом" : "afterward, then",
"потомок" : "descendant offspring",
"потомственный" : "hereditary",
"потомство" : "posterity descendants pl.",
"потому" : "therefore; See also: потому что",
"потому что" : "because",
"потоп" : "flood deluge",
"потоптать" : "trample tread",
"поторопить" : "hasten hurry up",
"потратить" : "spend, waste",
"потребитель" : "consumer, buyer",
"потребить" : "s. потреблять",
"потребление" : "consumption, use",
"потреблять" : "consume, use",
"потребность" : "need want  requirement",
"потребный" : "necessary",
"потребовать" : "demand, require, claim, cite summon, call",
"потрепанный" : "shabby worn",
"потрескаться" : "burst, crack split, chap",
"потроха" : "giblets, bowels",
"потрошить" : "draw disembowel",
"потрудиться" : "work, toil exert o.s., trouble",
"потрясать" : "shake",
"потрясающий" : "tremendous",
"потрясение" : "shock shake",
"потрясти" : "shake",
"потряхивание" : "joggle",
"потуги" : "travail labor",
"потупить" : "cast down, hang",
"потупленный" : "downcast",
"потуплять" : "cast down, hang",
"потускнеть" : "grow dim #or dull",
"потухание" : "extinction",
"потухать" : "s. тухнуть",
"потушить" : "put out extinguish, impf. stew, fig. subdue",
"потчевать" : "famil. = угощать",
"потягивать" : "s. тянуть",
"похвала" : "commendation, praise",
"похвальный" : "creditable, laudable, meritorious, praiseworthy",
"похищать" : "abduct, kidnap, purloin",
"похищение" : "kidnapping",
"похлебка" : "pottage",
"поход" : "campaign, march, cruise; See also: крестовый поход",
"походатайствовать" : "intercede, petition",
"походить" : "be like resemble",
"походка" : "gait",
"походный" : "marching, camp..., battle...",
"похождение" : "adventure",
"похожий" : "like resembling, similar; See also: быть похожим, ни на что не похоже",
"похолодеть" : "grow cold chill",
"похоронить" : "bury",
"похоронный" : "funeral..., dead, undertaker's",
"похороны" : "funeral burial",
"похорошеть" : "grow prettier",
"похотливость" : "concupiscence, lubricity",
"похотливый" : "lustful lewd",
"похоть" : "lust",
"похудеть" : "grow thin",
"поцеловать" : "kiss",
"поцелуй" : "kiss",
"поцеремониться" : "stand on ceremony be ceremonious",
"почасно" : "hourly",
"почва" : "soil ground",
"почем" : "famil. how much, how should",
"почему" : "why",
"почему-то" : "for some reason",
"почерк" : "handwriting",
"почернеть" : "blacken grow black, impf. show black",
"почерпать" : "gather derive, obtain",
"почерпнуть" : "gather derive, obtain",
"почерстветь" : "grow stale, harden",
"почесть1" : "honor",
"почесть2" : "s. почитать",
"почет" : "honor esteem",
"почетный" : "honorary, honorable, of honor",
"почечный" : "kidney, nephric, nephritic, nephrogenic, renal",
"почивать" : "rest repose, famil. sleep",
"почин" : "initiative, commerc. start",
"починка" : "repair",
"починять" : "s. чинить a)",
"почитатель" : "votary",
"почитать1" : "почтить esteem respect honor, worship, commerc. favor, почесть, esteem consider",
"почитать2" : "pf. read",
"почитаться" : "be held #or reputed",
"почить" : "rest repose, famil. sleep",
"почка" : "bot. bud, anat. kidney",
"почта" : "mail Brt. post, post, a. = почтамт",
"почтальон" : "mailman postman",
"почтамт" : "post office",
"почтение" : "respect  esteem obeisance, famil. compliments, с совершенным почтением respectfully yours yours faithfully",
"почтенный" : "respectable, venerable",
"почти" : "almost nearly all but"
};
