var dicctr_5 = {
"больница" : "hospital",
"больничная касса" : "sick-fund",
"больничный" : "hospital...",
"больничный листок" : "medical certificate",
"больно" : "painful, popul. very, мне больно it hurts me, глазам больно my eyes smart",
"больное место" : "tender spot",
"больной" : "sick ill  sore, patient invalid, fig. delicate burning, tender",
"больше" : "bigger, more; See also: больше всего, больше не {...}, как можно больше",
"больше всего" : "most of all, above all",
"больше не " : "no more #or longer",
"большевизм" : "Bolshevism",
"большевик" : "Bolshevik",
"большевистский" : "Bolshevist",
"большевичка" : "Bolshevik",
"больший" : "bigger greater",
"большинство" : "majority, most",
"большой" : "big large great, grownup",
"бомба" : "bomb",
"бомбардировать" : "bomb shell, bombard",
"бомбардировка" : "bombardment bombing",
"бомбардировщик" : "bomber",
"бомбежка" : "= бомбардировка",
"бомбей" : "bombay",
"бомбить" : "bomb",
"бомбовоз" : "= бомбардировщик",
"бомбоубежище" : "air-raid shelter",
"бонбоньерка" : "bonbonniere box for candies",
"бондарь" : "cooper",
"бор" : "pine wood #or forest, chem. boron",
"бордо" : "claret",
"бордюр" : "border trimming",
"борец" : "fighter, wrestler, fig. champion partisan",
"борзая" : "borzoi greyhound",
"борзой" : "swift fleet",
"борзый" : "brisk swift",
"борис" : "Boris",
"бормотание" : "burble, gabble, haw, mumble, mumbling, mutter",
"бормотать" : "murmur mutter",
"борный" : "boracic, boric",
"боров" : "boar",
"борода" : "beard",
"бородавка" : "wart",
"бородатый" : "bearded",
"бородач" : "bearded man",
"бородка" : "small beard, bit",
"борозда" : "furrow",
"бороздить" : "furrow",
"борона" : "harrow",
"боронить" : "harrow",
"бороновать" : "harrow",
"бороться" : "fight struggle, wrestle",
"борт" : "braid lace, border, board; See also: на борту судна, бросить за борт, человек за бортом{!}",
"бортовой" : "board...",
"борщ" : "borsch red-beet soup",
"борьба" : "strife, struggle, tussle, wrestle, wrestling",
"боря" : "dim. #of Борис",
"босиком" : "barefoot",
"босой" : "barefooted, на босу ногу = босиком",
"босоногий" : "= босой",
"босфор" : "Bosporus",
"босяк" : "tramp vagabond",
"ботаник" : "botanist",
"ботаника" : "botany",
"ботанический" : "botanic",
"ботинок" : "shoe Brt. boot",
"ботулизм" : "botulism",
"ботфорт" : "jackboot",
"ботфорты" : "jackboots",
"боты" : "overshoes",
"боцман" : "boatswain",
"бочар" : "cooper",
"бочка" : "cask tun",
"бочком" : "sideway sidewise",
"бочонок" : "barrel",
"бочоночный" : "бочоночное пиво draught beer",
"боярышник" : "hawthorn",
"брак" : "marriage, waster, wastrel",
"браконьерствовать" : "poach",
"бранить" : "chide, objurgate, scold, vituperate",
"бранный" : "abusive, battle... military",
"бранчливый" : "quarrelsome",
"брань" : "abuse quarrel, invective, battle fight",
"браслет" : "bracelet",
"брат" : "brother, old boy!; See also: ваш брат, наш брат",
"братание" : "fraternization",
"брататься" : "fraternize",
"братец" : "dear brother, old fellow! dear friend!",
"братия" : "fraternity, friary; See also: нищая братия",
"братоубийство" : "fratricide",
"братоубийца" : "fratricide",
"братский" : "brotherly fraternal",
"братство" : "brotherhood fraternity fellowship",
"брать" : "take, a. взимать, его взяла охота писать he took a fancy to writing, он взял да сказал famil. he said it without further consideration; See also: взять напрокат, взять пример, взять верх над, взять на поруки, взять слово, взять слово, взять обратно, взять себя в руки, взять на себя, взять за правило, возьмите направо{!}",
"брать боем" : "take by assault",
"брать взаймы" : "borrow",
"брать с бою" : "take by assault",
"браться" : "undertake, set about, take hold of seize, откуда это берется? where does that come from?, откуда у него деньги берутся?, wherever does he get his money from?; See also: взяться за руки, взяться за книгу, откуда ни возьмись",
"брачный" : "matrimonial conjugal",
"бревенчатый" : "log...",
"бревно" : "log, beam",
"бред" : "delirium",
"бредень" : "dragnet",
"бредить" : "rave talk deliriously",
"бредни" : "nonsense fantasies, raving",
"бредовый" : "delirious",
"брезгать" : "disdain",
"брезгливость" : "squeamishness disgust",
"брезгливый" : "squeamish fastidious",
"брезент" : "tarpaulin",
"брезжить" : "glimmer, dawn",
"брезжиться" : "glimmer, dawn",
"бремя" : "burden load",
"бренчание" : "strum, strumming",
"бренчать" : "clink jingle, strum",
"брести" : "drag lag, grope",
"брешь" : "breach, gap",
"бреющий полет" : "low-level flight",
"бригада" : "brigade  team group of workers, ударная бригада shock brigade",
"бригадир" : "brigadier, foreman",
"бриджи" : "breeches",
"бриллиант" : "brilliant",
"бриллиантовый" : "brilliant",
"британец" : "Briton Britisher",
"британия" : "Britain",
"британская империя" : "British Empire",
"британские острова" : "/pl. British Isles",
"британский" : "British; See also: Британская Империя, Британские острова",
"бритва" : "razor",
"бритвенный прибор" : "shaving things",
"брить" : "shave, -ся get shaved shave",
"бритье" : "shaving",
"бровь" : "eyebrow, хмурить брови frown, он и бровью не повел famil. he did not turn a hair, попасть не в бровь а в глаз famil. hit the nail on the head",
"брод" : "ford",
"бродить" : "побродить wander roam, ferment",
"бродяга" : "tramp vagabond",
"бродяжничать" : "stroll tramp",
"бродяжничество" : "vagrancy",
"бродячий" : "vagrant",
"бродящий" : "yeasty",
"брожение" : "fermentation, fig. agitation unrest",
"броква" : "rutabaga",
"брокколи" : "broccoli",
"бром" : "bromine",
"броневик" : "armored car",
"броневой" : "armored",
"броненосец" : "battleship",
"бронепоезд" : "armored train",
"бронетанковые части" : "armored troops",
"бронза" : "bronze",
"бронзовый" : "bronzy bronze...",
"бронировать1" : "armor",
"бронировать2" : "reserve secure",
"бронх" : "bronchus",
"бронхи" : "bronchi pl.",
"бронхиальный" : "bronchial",
"бронхит" : "bronchitis",
"броня" : "armour",
"броня1" : "armor",
"броня2" : "reservation",
"бросать" : "throw cast fling, leave abandon desert, give up quit leave off, break into be seized with, lay down, famil. waste squander, брось ...! famil. stop ...!",
"бросать деньги на ветер" : "waste money",
"бросать жребий" : "cast lots",
"бросать слова на ветер" : "waste words",
"бросаться" : "dash rush plunge dart, fall on, go to; See also: бросаться в глаза",
"бросаться в глаза" : "strike the eye",
"бросить" : "throw cast fling, leave abandon desert, give up quit leave off, break into be seized with, lay down, famil. waste squander, брось ...! famil. stop ...!",
"бросить за борт" : "throw overboard",
"броситься" : "dash rush plunge dart, fall on, go to; See also: бросаться в глаза",
"броситься врассыпную" : "disperse",
"бросовый" : "catchpenny, under",
"бросовый экспорт" : "dump",
"бросок" : "hurl throw",
"брошка" : "brooch",
"брошь" : "broach, brooch",
"брошюра" : "brochure pamphlet",
"брошюровать" : "stitch",
"брус" : "beam, bar, pl. parallel bars",
"брусковый" : "bar...",
"брусника" : "red bilberry -ries pl.",
"брусок" : "bar, whetstone",
"бруствер" : "breastwork",
"брутто" : "gross",
"брызгать" : "splash spatter sprinkle, gush",
"брызги" : "splash spray",
"брызнуть" : "splash spatter sprinkle, gush",
"брыкать" : "kick",
"брыкнуть" : "kick",
"брюзга" : "grumbler griper grouch",
"брюзгливый" : "morose sullen peevish grouchy",
"брюзжать" : "grumble growl grouch",
"брюква" : "turnip",
"брюки" : "trousers pants",
"брюнет" : "brunet",
"брюнетка" : "brunette",
"брюссель" : "Brussels",
"брюссельская капуста" : "Brussels sprouts",
"брюхо" : "belly paunch",
"брюшина" : "peritoneum",
"брюшной" : "abdominal",
"брюшной тиф" : "typhoid fever",
"брякать" : "clink, plump",
"брякнуть" : "clink, plump",
"бряцать" : "clank jingle, rattle",
"бсср" : ", Byelorussian Soviet Socialist Republic",
"бубен" : "tambourine",
"бубенец" : "jingle small bell",
"бубенчик" : "jingle small bell",
"бублик" : "cracknel",
"бубны" : "diamonds",
"бугор" : "hillock",
"бугорок" : "knoll, tubercle",
"будапешт" : "Budapest",
"будда" : "buddha",
"буддизм" : "buddhism",
"будет" : "enough! that'll do!",
"будильник" : "alarm clock",
"будить" : "разбудить wake waken, пробудить fig. rouse",
"будка" : "booth box",
"будни" : "weekdays, everyday life monotony",
"будничный" : "everyday, humdrum",
"будоражить" : "excite",
"будто" : "as if as though, that, allegedly",
"будущее" : "future",
"будущий" : "future",
"будущность" : "futurity future",
"будь добр" : "will you be so kind",
"буйвол" : "buffalo",
"буйный" : "impetuous violent vehement, unbridled, exuberant",
"буйство" : "mischief rage outrage violence",
"буйствовать" : "behave outrageously rage",
"бук" : "beech",
"буква" : "letter, прописная буква capital letter",
"буквальный" : "literal verbal",
"букварь" : "ABC book primer",
"буквоед" : "pedant",
"букет" : "bouquet, corsage",
"букинист" : "second-hand bookseller",
"буковый" : "beechen beech...",
"букс" : "box",
"буксир" : "tug, tow; See also: взять на буксир",
"буксирный" : "tug...",
"буксировать" : "tow tug",
"буксировка" : "tow, towage",
"булавка" : "pin; See also: английская булавка",
"буланый" : "dun",
"булат" : "Damascus steel",
"булатный" : "steel..., damask...",
"булинь" : "bowline",
"булка" : "small loaf, roll",
"булочка" : "roll, bun"
};
