var dicctr_18 = {
"два" : "two",
"двадцатый" : "twentieth",
"двадцать" : "twenty, cf. пять",
"дважды" : "twice; See also: дважды два, как дважды два",
"дважды два" : "math. two by two",
"две" : "two, & пятый; See also: в две счета",
"двенадцати" : "twelve-..., dodec..., duodecimal -denary",
"двенадцатый" : "twelfth",
"двенадцать" : "twelve",
"дверь" : "door",
"двигательный" : "locomotor, motive, propeller",
"движение" : "motion, move, movement, traffic",
"движущий" : "locomotive, propellent, propelling",
"двоебрачие" : "bigamy",
"двоеженство" : "bigamy",
"двоеточие" : "colon",
"двоиться" : "bifurcate",
"двойка" : "two, pair, cf.",
"двойник" : "double",
"двойной" : "double",
"двойня" : "twins pl.",
"двойственность" : "dualism, duality",
"двойственный" : "double twofold -faced, dual",
"двор" : "yard, farm, court; See also: на дворе",
"дворец" : "palace",
"дворецкий" : "butler",
"дворник" : "janitor street cleaner, mot. windshield wiper",
"дворня" : "obsol. servants domestics pl.",
"дворняга" : "mongrel, watchdog",
"дворняжка" : "mongrel, watchdog",
"дворовый" : "yard... house..., servant...",
"дворцовый" : "court..., palace...",
"дворянин" : "nobleman",
"дворянка" : "noblewoman",
"дворянский" : "noble",
"дворянство" : "nobility",
"двоюродный" : "двоюродный брат двоюродная сестра, cousin",
"двояковогнутый" : "biconcave",
"двуглазный" : "binocular",
"двуличность" : "duplicity",
"двусмысленность" : "ambiguity, equivoke, equivoque",
"двусмысленный" : "ambiguous, equivocal",
"двустволка" : "double-barreled gun",
"двуствольное ружье" : "double-barreled gun",
"двустворчатая дверь" : "folding doors",
"двустворчатый" : "bivalve",
"двусторонний" : "bilateral, two-way, reversible",
"двууглекислый" : "bicarbonate",
"двух" : ":; See also: двухдневный, двухколейный, двухколесный, двухлетний, двухместный, двухмесячный, двухмоторный, двухнедельный, двухсотый, двухэтажный",
"двухатомный" : "diatomic",
"двухлетний" : "biannual, biennial",
"двухпалатный" : "bicameral",
"двухпартийный" : "bipartisan",
"двухполюсный" : "bipolar",
"двухсотлетие" : "bicentenary, bicentennial",
"двухфокусный" : "bifocal",
"двухэтажный" : "two-storied",
"двучленный" : "binomial",
"двуязычный" : "bilingual",
"дебатировать" : "debate",
"дебаты" : "debate",
"дебелый" : "plump fat",
"дебет" : "debit; See also: занести в дебет, дебетовать",
"дебетовать" : "pf. debit",
"дебитор" : "debtor",
"дебош" : "riot row",
"дебри" : "thicket, wilderness",
"дебют" : "debut, opening",
"дебютантка" : "deb, debutante",
"дева" : "maid; See also: старая дева",
"девиз" : "motto",
"девический" : "girlish",
"девичий монастырь" : "nunnery",
"девка" : "wench, popul. maid, popul. whore",
"девочка" : "girl",
"девственница" : "virgin",
"девственный" : "maiden, virgin..., primeval",
"девушка" : "girl, obsol. parlormaid",
"девчонка" : "slut, girl",
"девчонка-сорванец" : "hoyden",
"девяносто" : "ninety",
"девяностый" : "ninetieth, cf. пятый",
"девятисотый" : "ninehundredth",
"девятка" : "nine",
"девятнадцатый" : "nineteenth, & пятый",
"девятнадцать" : "nineteen, cf.пять",
"девятый" : "ninth, cf. пятый",
"девять" : "nine, cf. пять",
"девятьсот" : "nine hundred",
"девятью" : "nine times",
"дегазировать" : "degas",
"дегенерат" : "degenerate",
"деготь" : "tar",
"дед" : "grandfather, old man, a. forefathers",
"дед мороз" : "Jack Frost, Santa Claus Father Christmas",
"дедуктивный" : "inferential",
"дедушка" : "grandfather, old man, a. forefathers",
"деепричастие" : "gr. gerund",
"дежурить" : "be on duty, sit up watch",
"дежурный" : "on duty",
"дежурство" : "duty, watch",
"дезертир" : "deserter",
"дезертировать" : "pf. desert",
"дезертирство" : "desertion",
"дезинфекция" : "disinfection",
"дезинфицировать" : "pf. disinfect",
"дезорганизовать" : "disorganize",
"дезорганизовывать" : "disorganize",
"действенный" : "efficient",
"действие" : "action, activity, engin. math. operation, thea. act, effect, efficacy, influence impact, место действия scene, свобода действий free play",
"действительно" : "really, indeed",
"действительность" : "reality, validity",
"действительный" : "real actual, valid, gr. active",
"действовать" : "act work, operate function, apply, have effect, get",
"действующее лицо" : "character personage",
"действующий" : "active, acting, milit. field...",
"декабрь" : "December",
"декан" : "dean",
"декламировать" : "declaim",
"декларативнй" : "declaratory",
"декларативный" : "declarative",
"декларация" : "declaration",
"декольте" : "decollete'",
"декольтированный" : "low-necked",
"декоративный" : "decorative, ornamental, scenic",
"декоратор" : "decorator",
"декорации" : "scenery",
"декорация" : "decoration, thea. scenery",
"декрет" : "decree edict",
"декретировать" : "pf. decree",
"деланный" : "affected forced",
"делать" : "make do; See also: делать нечего",
"делать вид" : "pretend",
"делать нечего" : "famil. it can't be helped",
"делать упор" : "lay stress #or emphasis",
"делаться" : "become grow turn, happen  be going on, что с ним сделалось? what has become of him?",
"делегат" : "delegate",
"делегация" : "delegation",
"делегировать" : "depute",
"дележ" : "distribution sharing",
"деление" : "division, partition, point",
"делец" : "businessman moneymaker",
"дели" : "delhi",
"деликатесы" : "delicatessen",
"деликатность" : "tact delicacy",
"деликатный" : "delicate",
"делимое" : "math. dividend",
"делимый" : "divisible, partible",
"делитель" : "math. divisor",
"делить" : "разделить поделить, divide  math., поделить share",
"делиться" : "share  exchange, confide  tell, math. be divisible",
"делишки" : "business",
"дело" : "affair matter concern, work business  line, art #or science, deed act, jur. case cause, file, milit. action battle, говорить дело famil. talk sense, делать дело fig. do serious work, то и дело continually incessantly, в чем дело? what's the matter?, в том то и дело famil. that's just the point, что вам за дело? #or это не ваше дело that's no business of yours, на деле in practice, на самом деле in reality in fact, really indeed, по делам on business, как дела? famil. how are you?, дело идет cf. идти",
"дело идет о" : "the question #or matter is, it is a question #or matter, ... is at stake",
"деловитый" : "businesslike, expert",
"деловой" : "businesslike, expert",
"делопроизводитель" : "secretary",
"дельный" : "competent, sensible",
"дельта" : "delta",
"дельфин" : "dolphin",
"демагог" : "demagogue",
"демагогический" : "demagogic",
"демаркационный" : "demarcation",
"демилитаризовать" : "pf. demilitarize",
"демобилизовать" : "pf. demobilize",
"демография" : "demography",
"демократ" : "democrat",
"демократический" : "democratic",
"демократия" : "democracy",
"демон" : "daemon, demon, incubus",
"демонстрация" : "demonstration",
"демонстрировать" : "demonstrate, show project",
"демонтаж" : "dismantling",
"денежный" : "money... monetary pecuniary, currency..., famil. rich",
"день" : "day, три часа дня 3 p.m. 3 o'clock in the afternoon, cf. днем; See also: в день, в этот день, день за день, изо дня в день, день ото дня, весь день, на днях",
"день выдачи зарплаты" : "payday",
"день за день" : "day after day",
"день ото дня" : "from day to day",
"деньги" : "money",
"департамент" : "department",
"депеша" : "dispatch wire",
"депозит" : "deposit",
"депутат" : "deputy delegate, member of the Supreme Soviet",
"дерби" : "derby",
"дергать" : "pull tug  jerk twist, pers. hard importune",
"деревенеть" : "stiffen, grow numb",
"деревенский" : "village... country... rural rustic",
"деревенский житель" : "villager",
"деревенщина" : "hayseed, lout, rube, swain, yahoo, yokel",
"деревня" : "village, country",
"дерево" : "tree, sg. wood; See also: красное дерево, черное дерево, резьба по дереву",
"деревянный" : "wooden",
"держава" : "power, hist. orb",
"держатель" : "retinaculum, tenaculum",
"держать" : "hold, keep, support, have, read; See also: держать сторону, держать себя в руках, держать кого-либо в руках, держать себя",
"держать в курсе" : "keep posted on",
"держать кого-либо в руках" : "control a pers.",
"держать курс на" : "head for",
"держать нос по ветру" : "be a timeserver",
"держать себя" : "conduct o.s. behave = держаться, удержаться hold, fig. stick, keep, hold out stand",
"держать себя в руках" : "control o.s.",
"держать сторону" : "side with",
"держать ухо востро" : "s. настороже",
"держать язык за зубами" : "hold one's tongue",
"дерзать" : "dare venture",
"дерзкий" : "impudent insolent, bold daring audacious",
"дерзнуть" : "dare venture",
"дерзость" : "impudence cheek",
"дерн" : "turf",
"дернуть" : "pull tug  jerk twist, pers. hard importune",
"десант" : "landing, troops pl. landed",
"десерт" : "dessert",
"дескриптор" : "descriptor",
"десна" : "gum",
"деспот" : "despot",
"десятиборье" : "decathlon",
"десятидневный" : "ten days'",
"десятикратный" : "tenfold",
"десятилетие" : "decade, tenth anniversary",
"десятилетка" : "ten-grades standard school",
"десятилетний" : "ten years', ten-years-old",
"десятина" : "obsol. = #approx. 2 3/4 #acres, tithe",
"десятичный" : "decimal",
"десятка" : "ten",
"десятник" : "foreman",
"десяток" : "ten, pl. dozens of many, s. идти, не робкого десятка famil. not a craven",
"десятый" : "tenth, cf. пятый, из пятого в десятое discursively in a ramblingmanner",
"десять" : "ten, & пятый",
"десятью" : "ten times",
"деталь" : "detail, engin. part",
"детально" : "in detail",
"детальный" : "detailed minute",
"детвора" : "famil. = дети",
"детеныш" : "young one, cub etc.",
"дети" : "children kids, двое детей two children, cf.",
"детородный" : "copulative, genital",
"детская" : "nursery",
"детский" : "child's infant, childlike, childish; See also: детский дом, детский сад, детская",
"детский дом" : "boarding school",
"детский сад" : "kindergarten",
"детство" : "childhood",
"деть" : "put, place, leave mislay; See also: куда деть",
"дефективный" : "defective",
"дефис" : "hyphen",
"дефицит" : "deficit",
"дефицитный" : "unprofitable, scarce",
"деформированный" : "misshapen",
"децибел" : "decibel",
"дешеветь" : "cheapen become cheaper",
"дешевизна" : "cheapness low price"
};
