var dicctr_82 = {
"снаряд" : "shell, missile projectile, apparatus, tool equipment, tackle",
"снарядить" : "equip fit out",
"снаряжать" : "equip fit out",
"снаряжение" : "equipment, munitions pl.",
"снасти" : "tackle",
"снасть" : "tackle, rigging",
"сначала" : "at first, first, over again",
"снег" : "snow, ~ идет it is snowing",
"снегирь" : "bullfinch",
"снегопад" : "snowfall",
"снежинка" : "snowflake",
"снежная баба" : "snowman",
"снежный" : "snow",
"снежный ком" : "snowball",
"снежок" : "dim. #of снег, snowball",
"снести" : "s. сносить",
"снизойти" : "condescend",
"снимать" : "dismast, doff, pull off, uncover",
"снимать сливки" : "skim",
"сниматься" : "take off, weigh, have a picture of o.s. taken, be struck off",
"снимок" : "photograph picture",
"снискать" : "get win",
"снискивать" : "get win",
"снисходительность" : "condescension, lenience",
"снисходительный" : "indulgent, condescending",
"снисходить" : "condescend",
"снисхождение" : "indulgence leniency, condescension",
"сниться" : "impers.: dream",
"сноб" : "snob",
"снобизм" : "snobbery",
"снова" : "again anew",
"сновать" : "scurry whisk",
"сновидение" : "vision dream",
"сноп" : "sheaf",
"сноровка" : "knack skill",
"сносить" : "carry  take, pull down demolish, endure bear tolerate, a. нести",
"сноситься" : "communicate, get in touch contact",
"сноска" : "footnote",
"сносный" : "tolerable",
"снотворный" : "hypnotic, somnifacient, somniferous, soporific",
"сноха" : "daughter-in-law",
"сношение" : "intercourse, relations",
"снятие" : "taking down, raising, removal, dismissal",
"снятой" : "skim",
"снять" : "take, remove discard dismiss, withdraw, cut, rent, photograph, reap gather cancel strike off, deprive, release, raise, strike, make; See also: снимать сливки",
"со" : "from, since, with, for, about, with, of, to",
"со временем" : "in the course of time",
"соавтор" : "coauthor",
"собака" : "dog, hound",
"собаки" : "canis",
"собачий" : "dog",
"собеседник" : "interlocutor",
"собиратель" : "collector",
"собирательный" : "gr. collective",
"собирать" : "gather collect, engin. assemble, prepare",
"собираться" : "gather assemble, prepare make o.s. #or be ready to start, be going intend collect, brace up",
"соблазн" : "temptation",
"соблазнитель" : "seducer temper",
"соблазнительный" : "tempting seductive",
"соблазнить" : "tempt, seduce",
"соблазнять" : "tempt, seduce",
"соблюдать" : "observe obey adhere, maintain",
"соблюдающий" : "observant, observer",
"соблюдение" : "observance, maintenance",
"соблюсти" : "observe preserve maintain, watch",
"соболезнование" : "condolence",
"соболезновать" : "condole",
"соболь" : "sable",
"собор" : "cathedral, council, diet",
"соборовать" : "administer extreme unction",
"собрание" : "assembly, congregation",
"собратья" : "brethren",
"собственнический" : "proprietary",
"собственность" : "ownership, property",
"собственный" : "own",
"сова" : "owl",
"совершать" : "accomplish, commit, make, strike  effect, celebrate do",
"совершаться" : "happen take place, be effected etc.",
"совершенно" : "absolutely, perfectly",
"совершеннолетие" : "majority full age",
"совершеннолетний" : "of age",
"совершенный" : "perfect, absolute complete a. quite",
"совершенство" : "perfection; See also: в совершенстве",
"совершенствовать" : "perfect  improve polish up",
"совершить" : "accomplish, commit, make, strike  effect, celebrate do",
"совестливый" : "conscientious",
"совестно" : "ashamed",
"совесть" : "conscience; See also: по совести",
"совет" : "advice counsel, council board, #USSR a. soviet; See also: Верховный Совет",
"советник" : "councilor",
"советовать" : "advise",
"советоваться" : "consult deliberate",
"советский" : "Soviet",
"советский союз" : "Soviet Union cf. СССР",
"советчик" : "adviser",
"совещание" : "conference  meeting, deliberation consultation",
"совещательный" : "advisory consultative",
"совещаться" : "confer consult deliberate",
"совладать" : "pf. master",
"совместимый" : "compatible",
"совместить" : "s. совмещать",
"совместно" : "together conjointly",
"совместный" : "joint combined, co",
"совмещать" : "combine, unite, reconcile",
"совок" : "scoop",
"совокупность" : "total aggregate whole",
"совокупный" : "joint",
"совпадать" : "coincide, agree, math. be congruent",
"совпадающий" : "coincident, concurrent",
"совпадение" : "coincidence s. vb",
"совпасть" : "coincide, agree, math. be congruent",
"соврать" : "lie, make a mistake, be inaccurate, tell",
"современник" : "contemporary",
"современный" : "modern, present-day up-to-date, a. современник",
"совсем" : "quite entirely, at all",
"совхоз" : "state farm, cf. колхоз",
"согласие" : "consent, agreement, harmony concord, accordance",
"согласиться" : "s. соглашаться",
"согласно" : "according to in accordance with",
"согласный" : "agreeable accordant, harmonious, я согласен I agree, consonant",
"согласование" : "coordination, gr. agreement concord",
"согласованность" : "consensus, harmony",
"согласованный" : "agreed, concerted, coordinate",
"согласовать" : "s. согласовывать",
"согласоваться" : "pf. conform, agree",
"согласовывать" : "coordinate, adjust, make agree",
"согласовываться" : "cohere",
"согласующийся" : "consistent",
"соглашательский" : "conciliatory",
"соглашаться" : "agree  consent  assent, famil. admit",
"соглашение" : "agreement understanding, consent",
"согнать" : "drive",
"согнуть" : "bend curve, bow, famil. drive, fig. bully",
"согревать" : "warm heat",
"согреть" : "warm, heat; See also: греться на солнце",
"согрешить" : "sin",
"сода" : "soda",
"содействие" : "assistance help",
"содействовать" : "assist help cooperate, contribute  further promote",
"содействующий" : "coefficient, subservient",
"содержание" : "content, maintenance support upkeep, cost, salary",
"содержатель" : "holder owner",
"содержательный" : "pithy substantial",
"содержать" : "contain hold, maintain support, keep",
"содержаться" : "be contained etc.",
"содержимое" : "contents pl.",
"содрать" : "pull, tweak, cf. выдирать & раздирать",
"содрогание" : "shudder",
"содрогаться" : "shudder",
"содрогнуться" : "shudder",
"содружество" : "community",
"соединение" : "union junction  connection, combination, chem. compound, milit. formation",
"соединенный" : "amalgamated, conjoint, conjunct, incorporate",
"соединительный" : "connective, a. copulative",
"соединить" : "unite join, connect, combine, cf. США",
"соединять" : "unite join, connect, combine, cf. США",
"сожаление" : "regret, pity; See also: к сожалению",
"сожалеть" : "regret",
"сожалеющий" : "sorry",
"сожжение" : "burning",
"сожительство" : "cohabitation",
"сожрать" : "eat, devour gorge gobble",
"созвать" : "s. созывать",
"созвездие" : "constellation",
"созвониться" : "pf. phone",
"созвучный" : "conformable accordant, concordant",
"создавать" : "create, produce, build up, prepare",
"создаваться" : "arise form",
"создание" : "creation, creature",
"создатель" : "creator, founder",
"создать" : "create, produce, build up, prepare",
"созерцательный" : "contemplative",
"созерцать" : "contemplate",
"созидательный" : "creative",
"сознавать" : "realize  see",
"сознаваться" : "confess avow own",
"сознание" : "consciousness, realization perception awareness, confession; See also: без сознания",
"сознательный" : "conscious, class conscious, conscientious",
"сознать" : "realize  see",
"сознающий" : "conscious",
"созревание" : "aging",
"созыв" : "convocation",
"созывать" : "call invite, convoke convene summon",
"соизволить" : "deign",
"соизмеримый" : "commensurable",
"сойти" : "s. сходить",
"сок" : "juice",
"сокол" : "falcon, mortarboard, tercel, tiercel",
"сокращать" : "abbreviate, abridge, curtail, retrench, shorten",
"сокращение" : "abbreviation, abridgement, cutback, cutting down",
"сокровище" : "treasure",
"сокровищница" : "treasury",
"сокрушительный" : "crushing, slashing, sledgehammer, smashing",
"сокрушить" : "smash break, distress afflict",
"сокрушиться" : "impf. grieve be distressed",
"солдат" : "soldier",
"солдатский" : "soldier's",
"соление" : "salting",
"соленоид" : "solenoid",
"соленый" : "salt, saline, pickled, corned, fig. spicy",
"солидарность" : "solidarity",
"солидарный" : "solidary, in sympathy with",
"солидность" : "solidity",
"солидный" : "solid firm sound, respectable",
"солист" : "soloist",
"солистка" : "soloist",
"солитер" : "tapeworm",
"солить" : "посолить salt, засолить pickle",
"солнечный" : "sun, solar",
"солнце" : "sun",
"солнцестояние" : "solstice",
"соловей" : "nightingale",
"солод" : "malt",
"солодовый" : "malt",
"солома" : "straw, thatch",
"соломенный" : "straw..., thatched, grass",
"соломинка" : "straw",
"солонина" : "corned beef",
"солонка" : "saltcellar",
"солоноватый" : "brackish",
"соль" : "salt, famil. point",
"сольный" : "solo",
"соляной" : "salt..., hydrochloric",
"сом" : "catfish sheatfish",
"сомкнуть" : "close",
"сомневаться" : "doubt",
"сомнение" : "doubt, question",
"сомнительный" : "doubtful, dubious",
"сомножитель" : "multiplicand",
"сон" : "sleep, dream",
"соната" : "sonata",
"сонет" : "sonnet",
"сонливый" : "sleepy",
"сонная тетеря" : "sleepyhead",
"сонный" : "sleeping, sleepy drowsy, soporific",
"соня" : "sleepyhead",
"соображать" : "consider weigh think, grasp understand",
"соображение" : "consideration, reason, grasp understanding",
"сообразительность" : "sagacity",
"сообразительный" : "sharp quick-witted",
"сообразить" : "consider weigh think, grasp understand",
"сообразный" : "conformable, a. according",
"сообразовать" : "pf. conform adapt  coordinate",
"сообразоваться" : "conform",
"сообща" : "together conjointly",
"сообщать" : "communicate  report, inform, impart",
"сообщение" : "communication, report statement announcement information",
"сообщество" : "community, company",
"сообщить" : "communicate  report, inform, impart",
"сообщник" : "accomplice"
};
