var dicctr_96 = {
"чибис" : "lapwing",
"чиж" : "siskin",
"чижик" : "siskin",
"чикаго" : "Chicago",
"чили" : "Chile",
"чилиец" : "Chilean",
"чин" : "rank grade, station, order ceremony, official",
"чинить" : "a) починить mend repair, b) очинить sharpen point, учинить raise cause, administer",
"чинный" : "proper, sedate",
"чиновник" : "official, bureaucrat",
"чирикать" : "chirp",
"чирикнуть" : "chirp",
"чиркать" : "strike",
"чиркнуть" : "strike",
"численность" : "number, milit. strength",
"численный" : "numerical",
"числитель" : "numerator",
"числительное" : "gr. numeral",
"числиться" : "be on the ... list",
"число" : "number, date, day, которое сегодня число?, what date is today?, в числе  в том числе including",
"числовой" : "numeral, numerical",
"чистильщик" : "black",
"чистить" : "почистить вычистить clean, brush, polish, очистить peel, pol. purge",
"чистка" : "cleaning, polish, pol. purge",
"чистокровный" : "thoroughbred, fig. genuine",
"чистоплотный" : "cleanly, fig. clean",
"чистосердечный" : "open-hearted frank sincere",
"чистота" : "cleanness, purity",
"чистотел" : "celandine",
"чистый" : "clean, pure, neat cleanly, clear, net, blank, fine faultless, genuine, sheer, plain, mere, hard, free open",
"читальный зал" : "reading room",
"читальня" : "reading room",
"читатель" : "reader",
"читать" : "read recite, give  deliver lecture, teach",
"читать по складам" : "spell",
"читка" : "reading",
"чихать" : "sneeze",
"чихнуть" : "sneeze",
"чк" : ", Cheka",
"член" : "member, limb, gr. article, part",
"членораздельный" : "articulate",
"членский" : "member...",
"членство" : "membership",
"чмокать" : "smack",
"чмокнуть" : "smack",
"чокаться" : "touch",
"чокнутый" : "wacky",
"чокнуться" : "touch",
"чопорный" : "prim prudish",
"чорт" : "s. черт",
"чреватый" : "pregnant",
"чрево" : "womb",
"чрез" : "s. через",
"чрезвычайный" : "extraordinary, extreme, special",
"чрезмерный" : "excessive",
"чтение" : "reading, recital",
"чтец" : "reader",
"чтить" : "s. почитать",
"что" : "pron. what, that which, how, why, what about, what's the matter, famil. а что? well?, how much how many, cf. ни, s. что-нибудь что-то; See also: вот что, что до меня, что вы{!}, не за что, ни за что, ну что же{?}, {уж }на что, с чего{?}, что и говорить",
"что вы" : "you don't say! what next!",
"что есть духу" : "at full speed with all one's might",
"что есть мочи" : "with all one's might",
"что за вопрос" : "of course!",
"что-либо" : "something",
"чувственный" : "carnal, sensual, sensuous",
"чувствительность" : "sensibility, sensitivity, sentience",
"чувствительный" : "feeling, sensitive, sensory",
"чувство" : "sense",
"чувствовать" : "feel",
"чувствоваться" : "be felt",
"чувствующий" : "sentient",
"чугун" : "cast iron",
"чугунный" : "cast-iron",
"чугунолитейный завод" : "iron foundry",
"чудак" : "crank character",
"чудачество" : "eccentricity",
"чудесный" : "wonderful marvelous, miraculous",
"чудить" : "s. дурить",
"чудиться" : "famil. = мерещиться",
"чудной" : "queer odd strange, funny",
"чудный" : "wonderful marvelous",
"чудо" : "miracle marvel, wonder, a. = чудно",
"чудовище" : "monster",
"чудовищность" : "monstrosity",
"чудовищный" : "monstrous",
"чудотворец" : "wonderworker",
"чужбина" : "foreign country",
"чуждаться" : "shun avoid",
"чуждый" : "foreign, strange alien, free",
"чужеземец" : "foreigner",
"чужой" : "someone else's alien, strange foreign, a. stranger outsider",
"чулан" : "closet, pantry",
"чулок" : "stocking",
"чума" : "plague pestilence",
"чумазый" : "dirty",
"чумной" : "pestilential",
"чурбан" : "block, blockhead",
"чуткий" : "sensitive  keen, light, vigilant watchful, wary, quick, responsive, sympathetic",
"чуткость" : "keenness, delicacy",
"чуточку" : "famil. a bit",
"чуть" : "hardly scarcely, a little; See also: чуть не, чуть ли не, чуть что",
"чуть ли не" : "famil. seem",
"чуть не" : "nearly almost",
"чуть свет" : "at dawn",
"чуть что" : "famil. on the least occasion",
"чутье" : "instinct, scent flair",
"чуть-чуть" : "s. чуть",
"чучело" : "stuffed animal #or bird, scarecrow; See also: чучело гороховое",
"чучело гороховое" : "fig. scarecrow, boor merry-andrew",
"чушь" : "bosh baloney",
"чуять" : "scent feel",
"чье" : "whose, чей это дом? whose house is this?",
"чьи" : "whose, чей это дом? whose house is this?",
"чья" : "whose, чей это дом? whose house is this?",
"шабаш" : "off-time, int. enough! no more!",
"шабашить" : "knock off",
"шаблон" : "stencil pattern cliche'",
"шаблонный" : "trite hackneyed",
"шаг" : "step, pace, stride, demarche, ни шагу no step further, на каждом шагу everywhere on end",
"шагать" : "step stride, march, walk, advance, cross, a. take a step, далеко шагнуть fig. make great progress",
"шагнуть" : "step stride, march, walk, advance, cross, a. take a step, далеко шагнуть fig. make great progress",
"шагом" : "at a slow pace slowly",
"шайба" : "disk",
"шайка" : "gang",
"шакал" : "jackal",
"шалаш" : "hut, tent",
"шалить" : "be naughty frolic romp, fool  play, be up to mischief, buck, шалишь! popul. fiddlesticks! on no account!",
"шаловливый" : "frolicsome playful",
"шалопай" : "good-for-nothing",
"шалость" : "prank",
"шалот" : "shallot",
"шалун" : "naughty boy",
"шалунья" : "tomboy madcap",
"шаль" : "shawl",
"шальной" : "mad crazy, stray...",
"шамкать" : "mumble",
"шампанское" : "champagne",
"шампунь" : "shampoo",
"шанс" : "chance prospect",
"шантаж" : "blackmail",
"шантажировать" : "blackmail",
"шапка" : "cap, heading",
"шар" : "sphere, ball, воздушный шар balloon; See also: земной шар",
"шарахаться" : "rush  recoil, shy, plop",
"шарахнуться" : "rush  recoil, shy, plop",
"шарж" : "cartoon caricature",
"шарик" : "dim. #of шар, corpuscle",
"шариковый" : "ball",
"шарикоподшипник" : "ball bearing",
"шарить" : "rummage",
"шаркать" : "scrape, bow",
"шаркнуть" : "scrape, bow",
"шарлотка" : "charlotte",
"шарманка" : "hand organ",
"шарнир" : "hinge joint",
"шарнирный" : "articulated, hinged, swivel",
"шаровары" : "baggy trousers",
"шаровидный" : "spherical globular",
"шарообразный" : "spherical globular",
"шарф" : "scarf neckerchief",
"шасси" : "chassis, av. undercarriage",
"шатать" : "shake, rock",
"шататься" : "a. stagger reel totter, famil. lounge #or loaf gad about",
"шатер" : "tent",
"шаткий" : "shaky rickety tottering, fig. unsteady fickle",
"шатнуть" : "shake, rock",
"шафер" : "groomsman",
"шафран" : "crocus, saffron",
"шах" : "shah",
"шахматы" : "chess",
"шахта" : "mine, pit",
"шахтер" : "pitman",
"шахтерский" : "miner's",
"шашка" : "saber Brt. sabre, checker draughtsman, Brt. draughts",
"швабра" : "mop, swab",
"швед" : "Swede",
"шведка" : "Swede",
"шведский" : "Swedish",
"швейный" : "sewing",
"швейцар" : "doorman doorkeeper porter",
"швейцарец" : "Swiss",
"швейцария" : "Switzerland",
"швейцарка" : "Swiss",
"швейцарский" : "Swiss, doorman's porter's",
"швеция" : "Sweden",
"швея" : "seamstress",
"швырнуть" : "hurl fling, squander",
"швырять" : "hurl fling, squander",
"шевелить" : "stir move, turn",
"шевельнуть" : "stir move, turn",
"шевелюра" : "shag",
"шедевр" : "masterpiece",
"шейный" : "jugular",
"шейх" : "sheik",
"шелест" : "rustle",
"шелестеть" : "rustle",
"шелк" : "silk",
"шелковистый" : "silky",
"шелковица" : "mulberry",
"шелковичный червь" : "silkworm",
"шелковый" : "silk",
"шелк-сырец" : "raw silk",
"шелохнуться" : "pf. stir",
"шелуха" : "peel husk",
"шелушить" : "peel husk",
"шельма" : "rascal rogue",
"шепелявить" : "lisp",
"шепелявый" : "lisping",
"шепнуть" : "whisper",
"шепот" : "whisper",
"шептать" : "whisper",
"шербет" : "sherbet",
"шеренга" : "file rank",
"шериф" : "sheriff",
"шероховатый" : "rough",
"шерсть" : "wool, coat, fleece",
"шерстяной" : "wool",
"шершавый" : "rough, shaggy",
"шест" : "pole",
"шествие" : "procession",
"шествовать" : "step stride go walk",
"шестерка" : "six",
"шестерня" : "pinion, cogwheel",
"шестеро" : "six",
"шестидесятый" : "sixtieth, cf. пятый",
"шестикратный" : "sextuple",
"шестимесячный" : "six-months'",
"шестисотый" : "six hundredth",
"шестиугольник" : "hexagon",
"шестиугольный" : "hexagonal",
"шестнадцатиричный" : "hexadecimal",
"шестнадцатый" : "sixteenth, cf. пятый",
"шестнадцать" : "sixteen, cf. пять",
"шестой" : "sixth, cf. пятый",
"шесть" : "six, cf. пять",
"шестьдесят" : "sixty",
"шестьсот" : "six hundred",
"шестью" : "six times",
"шеф" : "chief head famil. boss, patron sponsor",
"шефповар" : "chef",
"шефство" : "patronage sponsorship",
"шея" : "neck, back",
"шибко" : "popul. swiftly, very",
"шиворот" : "взять за шиворот collar",
"шизоид" : "schizoid",
"шизофрения" : "schizophrenia",
"шикарный" : "posh, stylish, swanky, swell",
"шило" : "awl, bodkin, bradawl, prod",
"шимпанзе" : "chimpanzee",
"шина" : "splint, tire, tyre"
};
