var dicctr_41 = {
"многоэтажный" : "many-storied",
"многоязычный" : "polyglot",
"множественный" : "plural",
"множество" : "multitude",
"множимое" : "multiplicand",
"множитель" : "multiplier",
"множить" : "s. умножать",
"мо" : "mho",
"мобилизовать" : "pf. mobilize",
"мобильность" : "mobility",
"мобильный" : "mobile",
"могила" : "grave",
"могильный" : "tomb..., = могильщик",
"могильщик" : "grave digger",
"могол" : "mogul",
"могучий" : "mighty powerful",
"могущественный" : "mighty powerful",
"могущество" : "might",
"мода" : "fashion vogue",
"модальный" : "modal",
"модель" : "model, engin. mold",
"модем" : "modem, modulator",
"модернизировать" : "pf. modernize",
"модистка" : "milliner",
"модифицировать" : "pf. modify",
"модный" : "fashionable stylish, fashion...",
"модулировать" : "modulate",
"модуль" : "mod, module",
"модульный" : "modular",
"мое" : "my, mine, su. famil. my folks, s. ваш",
"может быть" : "perhaps maybe",
"можжевельник" : "juniper",
"можно" : "one can #or may, it is possible, cf. как",
"мозаика" : "mosaic",
"мозаичный" : "mosaic, tessellated",
"мозг" : "brain, marrow, cord",
"мозговитый" : "brainy",
"мозговой" : "cerebral",
"мозжечок" : "cerebellum",
"мозолистый" : "horny callous",
"мозолить глаза" : "famil. be an eyesore to",
"мозоль" : "callosity, corn",
"мои" : "my, mine, su. famil. my folks, s. ваш",
"моисей" : "moses",
"мой" : "my, mine, su. famil. my folks, s. ваш",
"мокко" : "mocha",
"мокнуть" : "become wet, soak",
"мокрота1" : "phleghm",
"мокрота2" : "wet humidity",
"мокрый" : "wet, moist",
"мол" : "jetty mole",
"молва" : "rumor, talk",
"молвить" : "pf. промолвить say utter",
"молдаванин" : "Moldavian",
"молдаванка" : "Moldavian",
"молебен" : "thanksgiving  Te Deum",
"молекула" : "molecule",
"молекулярный" : "molecular",
"молибден" : "molybdenum",
"молитва" : "prayer",
"молитвенник" : "prayer book",
"молить" : "implore  entreat beseech",
"молиться" : "pray",
"моллюск" : "mollusc, mollusk, shellfish",
"молниеносный" : "flash-like, blazing, thunder, violent, milit. blitz...",
"молния" : "lightning, flash, zipper zip fastener",
"молодежь" : "youth young people pl.",
"молодеть" : "grow younger",
"молодец" : "fine fellow brick, well done!",
"молодецкий" : "brave valiant, smart",
"молодить" : "rejuvenate",
"молодняк" : "offspring, underwood, saplings pl.",
"молодожены" : "newly wedded couple",
"молодой" : "young, new, pl. a.= молодожены",
"молодость" : "youth adolescence",
"молодцеватый" : "smart",
"моложавый" : "youthful young-looking",
"молоки" : "milt",
"молоко" : "milk",
"молокосос" : "greenhorn",
"молот" : "hammer",
"молотилка" : "threshing machine",
"молотить" : "thresh",
"молоток" : "hammer, с молотка by auction",
"молоть" : "grind, impf. talk",
"молотьба" : "threshing",
"молох" : "moloch",
"молочай" : "spurge",
"молочная" : "dairy creamery",
"молочник" : "milk jug, famil. milkman",
"молочный" : "milk..., dairy...",
"молча" : "silently tacitly",
"молчаливый" : "taciturn",
"молчание" : "silence",
"молчать" : "be silent, молчи! shut up!",
"моль" : "moth, mus. minor",
"мольба" : "entreaty, prayer",
"молярный" : "molal",
"молящийся" : "prayer",
"момент" : "moment instant",
"моментальный" : "momentary instantaneous, snap",
"монарх" : "monarch",
"монархия" : "monarchy",
"монастырь" : "monastery convent",
"монах" : "monk",
"монахиня" : "nun",
"монашеский" : "monastic, monk's",
"монголия" : "mongolia",
"монгольский" : "Mongolian",
"монета" : "coin, money cash; See also: той же монетой, за чистую монету",
"монетный" : "monetary",
"монетный двор" : "mint",
"монитор" : "monitor",
"моногамия" : "monogamy",
"монограмма" : "monogram",
"монолит" : "monolith",
"монолог" : "monologue",
"мономер" : "monomer",
"монооксид" : "monoxide",
"монополизировать" : "pf. monopolize",
"монополия" : "monopoly",
"монотонный" : "monotonous",
"монтаж" : "assembling assemblage, cutting, montage",
"монтер" : "assembler mechanic, electrician",
"монтировать" : "assemble install, cut",
"монумент" : "monument",
"мопс" : "pug",
"мораль" : "morals pl., morality, moral, famil. lecture lecturing",
"моральное состояние" : "morale",
"моральный" : "moral",
"мораторий" : "moratorium",
"морг" : "morgue",
"моргание" : "wink",
"моргать" : "blink",
"моргнуть" : "blink",
"морда" : "muzzle snout",
"мордастый" : "jowly",
"море" : "sea, seaside",
"морем" : "by sea, за морем overseas",
"морена" : "moraine",
"мореплавание" : "navigation",
"мореплаватель" : "seafarer",
"моретрясение" : "seaquake",
"морж" : "walrus",
"моржовый" : "walrus",
"морить" : "exterminate; See also: морить голодом",
"морить голодом" : "starve torment exhaust",
"морковь" : "carrot",
"мороженое" : "ice cream",
"мороз" : "frost",
"морозить" : "freeze",
"морозный" : "frosty",
"моросить" : "drizzle",
"морочить" : "fool beguile",
"морская звезда" : "zo. starfish",
"морской" : "sea... maritime, naval, nautical, seaside...",
"морской волк" : "old salt",
"морской рак" : "lobster",
"морской флот" : "navy",
"морфема" : "morpheme",
"морфий" : "morphine morphia",
"морфология" : "morphology",
"морщина" : "wrinkle",
"морщинистый" : "wrinkled",
"морщить" : "wrinkle frown, distort",
"моряк" : "seaman sailor",
"москательный" : "drug",
"москва" : "Moscow",
"москвич" : "Moscower",
"москвичка" : "Moscower",
"москит" : "mosquito",
"московский" : "Moscow...",
"мост" : "bridge",
"мостить" : "pave",
"мостки" : "planked footway footbridge",
"мостовая" : "pavement",
"мостовой" : "bridge...",
"мостовщик" : "pavior",
"мосье" : "monsieur",
"мот" : "spendthrift prodigal",
"мотать" : "reel wind, once мотнуть shake wag, beckon point, jerk, famil. промотать squander waste",
"мотаться" : "impf. dangle, popul. knock about",
"мотель" : "motel",
"мотив" : "motiv motif",
"мотивировать" : "pf. motivate",
"мотовство" : "extravagance",
"моток" : "skein",
"мотор" : "motor engine",
"моторизовать" : "pf. motorize",
"мотоцикл" : "motorcycle",
"мотоциклет" : "motorcycle",
"мотоциклист" : "motorcyclist",
"мотыга" : "hoe mattock",
"мотылек" : "butterfly",
"мох" : "moss",
"мохнатое полотенце" : "Turkish towel",
"мохнатый" : "shaggy hairy",
"моховой" : "mossy",
"моча" : "urine",
"мочалка" : "bast whisp",
"мочевина" : "carbamide, urea",
"мочевой" : "uric, urinary, urinose, urinous",
"мочевой пузырь" : "bladder",
"мочи нет" : "impossible I etc. can't, awfully",
"мочить" : "wet moisten, soak step",
"мочка" : "lobe",
"мочь" : "could",
"мочь1" : "can be able, may, я не могу не  inf. I can't help ...ing, не могу знать... I don't know; See also: не может быть{!}",
"мочь2" : "во всю мочь; See also: изо всей мочи, что есть мочи, мочи нет",
"мошенник" : "rapscallion, rascal, rook, swindler",
"мошенничество" : "gyp, knavery, rascality, roguery",
"мошка" : "midge",
"мошонка" : "scrotum",
"мощный" : "forceful, mighty, vigorous",
"мракобесие" : "obscurantism",
"мрамор" : "marble",
"мрачнеть" : "darken",
"мрачность" : "gloom",
"мрачный" : "dark, obscure, gloomy somber",
"мститель" : "avenger",
"мстительный" : "revengeful",
"мстить" : "revenge o.s. take revenge, avenge a p2",
"мтс" : ", machine and tractor station",
"муар" : "moire",
"мудреного нет" : "no wonder",
"мудреный" : "difficult hard intricate, fanciful, queer; See also: мудреного нет",
"мудрец" : "sage",
"мудрить" : "subtilize, quibble, trick, bully",
"мудрость" : "wisdom, зуб мудрости wisdom tooth, famil. trick",
"мудрствовать" : "s. мудрить",
"мудрый" : "wise sage",
"муж" : "husband, obsol. man",
"мужать" : "mature grow",
"мужаться" : "impf. take courage",
"муженек" : "hubby",
"мужеподобная" : "mannish",
"мужественный" : "courageous, manly",
"мужество" : "courage spirit",
"мужик" : "peasant, popul. boor, man",
"мужицкий" : "peasant's rustic",
"мужичий" : "peasant's rustic",
"мужской" : "male masculine, man",
"мужчина" : "man",
"муза" : "muse",
"музей" : "museum",
"музыка" : "music, popul. business",
"музыкальный" : "musical",
"музыкант" : "musician",
"музыковедение" : "musicology",
"мука" : "farina, flour, martyrdom"
};
