var dicctr_83 = {
"сообщница" : "accomplice",
"соорудить" : "build construct erect raise",
"сооружать" : "build construct erect raise",
"сооружение" : "construction building structure",
"соответственный" : "corresponding, a. according  in accordance",
"соответствие" : "conformity accordance",
"соответствовать" : "correspond conform  agree comply",
"соответствующий" : "corresponding respective, suitable",
"соотечественник" : "compatriot fellow countryman",
"соотечественница" : "compatriot fellow countryman",
"соотношение" : "correlation",
"сопение" : "sniff",
"соперник" : "rival",
"соперничал" : "vying",
"соперничать" : "compete rival vie, be a match",
"соперничающий" : "competitive",
"соперничество" : "rivalry",
"сопеть" : "wheeze",
"сопли" : "snot",
"сопливый" : "snotty",
"сопляк" : "snot nose",
"сопоставить" : "compare",
"сопоставление" : "comparison",
"сопоставлять" : "compare",
"сопрано" : "soprano",
"соприкасаться" : "adjoin, touch",
"соприкосновение" : "contact touch",
"соприкоснуться" : "adjoin, touch",
"сопроводительный" : "covering",
"сопровождать" : "accompany, escort, сопроводить provide",
"сопровождаться" : "impf. be accompanied, entail",
"сопровождающий" : "accompanying, attendant, concomitant",
"сопровождение" : "accompaniment; See also: в сопровождении",
"сопротивление" : "resistance",
"сопротивляться" : "resist oppose",
"сопряженный" : "connected",
"сопутствовать" : "accompany",
"сор" : "rubbish litter",
"соразмерно" : "in proportion",
"соразмерный" : "commensurate, proportionate",
"соратник" : "brother-in-arms",
"сорванец" : "madcap",
"сорвать" : "s. срывать",
"сорняк" : "weed",
"сородич" : "tribesman",
"сорок" : "forty",
"сорока" : "magpie",
"сороковой" : "fortieth",
"сорокопут" : "falconet, shrike",
"сортир" : "john",
"сортировка" : "sorting",
"сортировочный" : "rail. switching",
"сосать" : "suck",
"сосед" : "neighbor",
"соседка" : "neighbor",
"соседний" : "neighboring adjoining",
"соседский" : "neighbor's",
"соседство" : "neighborhood",
"сосиска" : "sausage",
"соска" : "dummy",
"соскакивать" : "jump #or spring",
"соскальзывать" : "slide, slip",
"соскользнуть" : "slide, slip",
"соскочить" : "jump #or spring",
"соскребать" : "raze",
"соскучиться" : "pf. become bored, s. скучать",
"сослагательный" : "gr. subjunctive",
"сосланный" : "deportee",
"сослать" : "s. ссылать",
"сословие" : "estate",
"сослуживец" : "colleague",
"сосновый" : "pine, piny",
"сосок" : "dug, papilla, teat",
"сосредоточивать" : "focus",
"составление" : "composition",
"составлять" : "compose, draw up",
"составной" : "component, composite, compound, constitutive",
"состояние" : "condition, fettle",
"состоятельный" : "well-to-do well-off, solvent, valid sound well-founded",
"состоять" : "consist, be, occupy  work",
"состояться" : "pf. take place, come about",
"сострадание" : "compassion",
"сострить" : "joke be witty",
"состряпать" : "cook",
"состязание" : "contest competition, match",
"состязаться" : "compete vie contend",
"сосуд" : "vessel",
"сосудистый" : "vascular",
"сосулька" : "icicle",
"сосуществование" : "coexistence",
"сосуществовать" : "coexist",
"сосчитать" : "count, consider regard  hold think",
"сотворение" : "creation",
"сотворить" : "create do, perform",
"соткать" : "weave",
"сотня" : "a hundred",
"сотообразный" : "cellular",
"сотрудник" : "collaborator, employee member, pl. staff, contributor, colleague",
"сотрудничать" : "collaborate cooperate",
"сотрудничество" : "collaboration cooperation",
"сотрясение" : "concussion",
"соты" : "honeycomb",
"сотый" : "hundredth, cf. пятый, две целых и двадцать пять сотых 25",
"соус" : "sauce, gravy",
"соучастие" : "complicity",
"соучастник" : "accomplice",
"соученик" : "schoolmate",
"софизм" : "sophism",
"софистика" : "chicanery, sophistry",
"софья" : "Sophia",
"соха" : "plow plough",
"сохнуть" : "высохнуть dry, засохнуть fade wither, impf. pine away",
"сохранение" : "preservation conservation, charge",
"сохрани бог" : "God forbid!",
"сохранить" : "s. сохранять",
"сохранять" : "keep, preserve, retain, maintain, reserve, forbid!",
"сохраняться" : "be preserved, keep",
"социал-демократ" : "Social Democrat",
"социал-демократический" : "Social Democrat",
"социализм" : "socialism",
"социалист" : "socialist",
"социалистический" : "socialist",
"социальный" : "social",
"социология" : "sociology",
"соцсоревнование" : "socialist competition",
"соцстрах" : "social insurance",
"сочельник" : "Eve",
"сочетание" : "combination, union",
"сочетать" : "combine, unite",
"сочинение" : "composition, writing work, thesis, gr. parataxis coordination",
"сочинитель" : "author",
"сочинить" : "compose write, invent, gr. coordinate",
"сочинять" : "compose write, invent, gr. coordinate",
"сочиться" : "ooze; See also: сочиться кровью",
"сочиться кровью" : "bleed",
"сочный" : "juicy, rich",
"сочувственный" : "sympathetic sympathizing",
"сочувствие" : "sympathy",
"сочувствовать" : "sympathize feel with, approve",
"сочувствующий" : "sympathizer",
"союз" : "union, alliance, confederacy, league, gr. conjunction; See also: Советский Союз",
"союзка" : "vamp",
"союзник" : "ally",
"союзный" : "allied, Union",
"соя" : "soy",
"спагетти" : "spaghetti",
"спад" : "wane",
"спадать" : "fall",
"спазма" : "spasm",
"спаивать" : "спаять solder, famil. споить make drunk",
"спайка" : "solder",
"спалзывать" : "s. сползать",
"спальный" : "sleeping, bed...",
"спальня" : "bedroom",
"спаржа" : "asparagus",
"спартанский" : "spartan",
"спасательный" : "life...",
"спасать" : "save rescue, redeem",
"спасаться" : "a. escape",
"спасение" : "rescue, redemption",
"спасибо" : "thank you, thanks",
"спаситель" : "savior rescuer",
"спасительный" : "saving",
"спасти" : "save rescue, redeem",
"спастись" : "a. escape",
"спастический" : "spastic",
"спасть" : "fall",
"спать" : "sleep, go to bed, мне не спится famil. I can't sleep",
"спаять" : "s. спаивать",
"спекаться" : "s. запекаться, engin. conglomerate",
"спектакль" : "performance",
"спектр" : "spectrum",
"спектральный" : "spectral",
"спектрограф" : "spectrograph",
"спектрометр" : "spectrometer",
"спектроскоп" : "spectroscope",
"спекулировать" : "speculate",
"спекулянт" : "speculator",
"спекулятивный" : "theoretic",
"спекуляция" : "profiteering, spec",
"спеленать" : "swaddle",
"спелый" : "ripe",
"спенсер" : "spencer",
"сперва" : "famil. first",
"спереди" : "in front",
"сперма" : "semen, sperm",
"сперматический" : "seminal",
"спертый" : "stuffy close",
"спесивый" : "haughty",
"спесь" : "hubris",
"спеть" : "ripen, a. петь",
"спех" : "haste hurry",
"специализироваться" : "pf. specialize",
"специалист" : "specialist expert",
"специальность" : "specialty line profession",
"специальный" : "special, express",
"специфический" : "specific",
"специя" : "spice",
"спецодежда" : "overalls pl.",
"спешить" : "hurry  hasten, #clock: be fast",
"спешиться" : "pf. dismount",
"спешка" : "haste hurry",
"спешный" : "urgent pressing, special express",
"спидометр" : "speedometer",
"спина" : "back",
"спинка" : "back",
"спинной" : "spinal, vertebral  back",
"спираль" : "spiral",
"спиральный" : "spiral",
"спирт" : "spirit alcohol",
"спиртной" : "alcoholic strong",
"списать" : "s. списывать",
"список" : "list register, copy",
"списывать" : "copy, write, plagiarize crib, nav. pay off",
"спихивать" : "push",
"спихнуть" : "push",
"спица" : "spoke, knitting needle",
"спичка" : "match",
"сплав" : "alloy, float",
"сплавить" : "float, alloy",
"сплавлять" : "float, alloy",
"сплачивать" : "rally, fasten",
"сплести" : "braid plait, weave, spin, famil. twaddle, lie, -сь famil. drag lag",
"сплетать" : "plait braid, lace, famil. invent",
"сплетение" : "interlacement texture",
"сплетни" : "gossip, tittle-tattle",
"сплетник" : "scandalmonger",
"сплетница" : "scandalmonger",
"сплетничать" : "gossip",
"сплетня" : "gossip, pl. scandal",
"сплотить" : "rally, fasten",
"сплоховать" : "pf. blunder",
"сплочение" : "rallying",
"сплошать" : "blunder",
"сплошной" : "solid compact, sheer complete, continuous",
"сплошь" : "throughout entirely everywhere, quite often",
"сплутовать" : "trick cheat",
"сплющить" : "pf. flatten",
"сплясать" : "dance",
"сподвижник" : "s. соратник",
"сподличать" : "act meanly",
"споить" : "s. спаивать",
"спокойный" : "calm quiet tranquil, composed, спокойно s. смело famil., спокойной ночи! good night!, будьте спокойны! don't worry!",
"спокойствие" : "calm tranquility, composure, peace order",
"сползать" : "climb #or slip",
"сползти" : "climb #or slip",
"сполна" : "... wholly whole ... total ...",
"сполоснуть" : "pf. rinse",
"спор" : "dispute controversy argument, wrangle quarrel; See also: спору нет",
"спора" : "spore"
};
