var dicctr_95 = {
"ценить" : "appreciate",
"ценность" : "feck, value",
"ценный" : "valuable, money; See also: ценные бумаги",
"цент" : "cent",
"центнер" : "centner",
"центр" : "center Brt. centre",
"централизовать" : "pf. centralize",
"центральный" : "central, & ЦК",
"центральный комитет" : "Central Committee, cf. ЦИК",
"центрифуга" : "centrifuge",
"центробежный" : "centrifugal",
"центростремительный" : "afferent, centripetal",
"центрофугированный" : "spun",
"цены нет" : "be invaluable",
"цеп" : "flail",
"цепенеть" : "grow numb stiffen, be transfixed",
"цепкий" : "clinging, tenacious",
"цепкость" : "tenacity",
"цепляться" : "cling",
"цепной" : "chain",
"цепочка" : "chain",
"цепь" : "chain, milit. line, el. circuit",
"церемониться" : "stand on ceremony be ceremonious",
"церемония" : "ceremony",
"церемонный" : "ceremonious",
"церковник" : "churchman",
"церковный" : "church...",
"церковь" : "church",
"цех" : "ыhop section, obsol. guild",
"цивилизованный" : "civilized",
"цивилизовать" : "pf. civilize",
"цик" : ", Central Executive Committee, cf. ЦК",
"цикл" : "cycle, course set",
"циклический" : "cyclic",
"циклон" : "cyclone",
"циклоп" : "cyclops",
"циклопический" : "cyclopean",
"цикорий" : "chicory",
"цилиндр" : "cylinder, top hat",
"цилиндрический" : "cylindrical",
"цинга" : "scurvy",
"цинизм" : "cynicism",
"циник" : "cynic",
"циничный" : "cynical",
"цинк" : "zinc",
"цинковый" : "zinc ...",
"циновка" : "mat",
"цирк" : "circus",
"цирковой" : "circus",
"циркулировать" : "circulate",
"циркуль" : "compasses pl.",
"циркуляр" : "circular",
"цистерна" : "cistern tank",
"цитадель" : "citadel, stronghold",
"цитата" : "quotation",
"цитировать" : "quote",
"цитрусовые" : "citrus",
"циферблат" : "dial face",
"цифра" : "figure",
"цк" : "Central Committee, cf. ЦИК",
"цоколь" : "arch. socle, engin. socket",
"цунами" : "tsunami",
"цыган" : "Gypsy Brt. Gipsy",
"цыганка" : "Gypsy Brt. Gipsy",
"цыганский" : "Gypsy Brt. Gipsy",
"цыпленок" : "chicken",
"цыпочки" : "на цыпочках на цыпочки on tiptoe",
"чавканье" : "champ, chaw",
"чад" : "chad",
"чаевые" : "tip",
"чай" : "char, tea",
"чай1" : "tea, tea party; See also: дать на чай1",
"чай2" : "popul. perhaps I suppose",
"чайка" : "gull mew",
"чайник" : "teapot, teakettle",
"чайница" : "caddy",
"чайный" : "tea",
"чалма" : "turban",
"чан" : "tub vat",
"чарка" : "glass",
"чарли" : "charlie",
"чарльстон" : "charleston",
"чаровать" : "charm",
"чародей" : "magician",
"чародейка" : "enchantress",
"чарующий" : "glamorous",
"час" : "hour, o'clock, time moment, an hour's ..., второй ~ past one, в пятом часу between four & five; See also: час от часу, с часу на час, на часах",
"час от часу" : "hourly",
"часовня" : "chapel",
"часовой" : "hour's, by the hour, watch... clock... su. sentry sentinel",
"часовой мастер" : "watchmaker",
"часовщик" : "watchmaker",
"частица" : "particle",
"частичный" : "partial",
"частное" : "quotient",
"частность" : "particular",
"частный" : "private, particular, individual",
"часто" : "frequently, oft, often, oftentimes",
"частокол" : "palisade",
"частота" : "frequency",
"частушка" : "couplet",
"частый" : "frequent, thick dense, close, quick, rapid",
"часть" : "part, share, piece, department section  famil. line branch, milit. unit, obsol. police station, большей частью по большей части for the most part mostly",
"часы" : "watch, clock, dial, на моих часах by my watch",
"чахлый" : "sickly, stunted",
"чахнуть" : "wither shrivel, grow stunted",
"чахотка" : "consumption",
"чахоточный" : "consumptive",
"чаша" : "cup chalice, bowl",
"чашелистник" : "sepal",
"чашка" : "cup, pan, cap; See also: надколенная чашка",
"чаща" : "thicket",
"чаще" : "more often",
"чаяние" : "expectation  hope dream",
"чваниться" : "brag blow swagger",
"чванство" : "brag blow swagger",
"чего доброго" : "after all",
"чей" : "whose, чей это дом? whose house is this?",
"чек" : "check Brt. cheque",
"чеканить" : "mint coin, chase",
"чеканка" : "minting coinage, chase",
"чекист" : "member of ЧК cf.",
"чековый" : "check...",
"челка" : "quiff",
"челн" : "boat, canoe",
"челнок" : "dim. #of челн, a. shuttle",
"чело" : "forehead brow",
"человек" : "man human being, person individual, one, obsol. servant, waiter, русский человек Russian",
"человек за бортом" : "man overboard!",
"человеконенавистник" : "misanthrope, misanthropist",
"человеконенавистнический" : "misanthropic",
"человекоубийство" : "manslaughter",
"человеческий" : "human",
"человечество" : "humanity, humankind, mankind",
"челюсть" : "jaw, jowl",
"чем" : "than",
"чемодан" : "portmanteau, suitcase, valise",
"чемпион" : "champion",
"чемпионат" : "championship",
"чепец" : "cap",
"чепуха" : "nonsense, trifle",
"чепчик" : "cap",
"черви" : "hearts",
"червивый" : "worm-eaten",
"червонец" : "10 rubles",
"червы" : "hearts",
"червь" : "worm",
"червяк" : "worm",
"чердак" : "garret attic loft",
"черед" : "turn, course",
"чередование" : "alternation",
"чередовать" : "alternate",
"чередующийся" : "alternate",
"через" : "across, trans, via",
"череп" : "cranium, skull",
"черепаха" : "tortoise, turtle, tortoise shell",
"черепаховый" : "tortoise...",
"черепаший" : "tortoise's snail's",
"черепица" : "tile",
"черепичный" : "tiled",
"черепок" : "fragment piece",
"чересчур" : "too too much",
"черешня" : "cherry",
"черкнуть" : "pf.: ~ пару слов drop a line",
"чернеть" : "blacken grow black, impf. show black",
"чернец" : "monk",
"черника" : "bilberry -ries pl.",
"чернила" : "ink",
"чернильница" : "inkwell  inkstand",
"чернильный" : "ink...",
"чернить" : "начернить blacken, очернить blacken  denigrate slander",
"черновик" : "rough copy, draft",
"черновой" : "draft..., rough, waste",
"черноволосый" : "black-haired",
"черноглазый" : "black-eyed",
"черногорец" : "Montenegrin",
"черное дерево" : "ebony",
"чернозем" : "chernozem black earth",
"чернокожий" : "Negro",
"черномазый" : "swarthy",
"черноморский" : "Black Sea ...",
"чернорабочий" : "unskilled worker",
"чернослив" : "prune",
"чернота" : "blackness",
"черный" : "black, brown, ferrous, rough, back, leafy; See also: на черный день, черным по белому",
"черным по белому" : "in black & white",
"чернь" : "mob rabble",
"черпать" : "scoop draw, gather",
"черпнуть" : "scoop draw, gather",
"черстветь" : "grow stale, harden",
"черствый" : "stale hard, callous",
"черт" : "devil, a. ступай убирайся, take: возьми побери [по]дери a. confound blast damn it!); See also: к черту, на кой черт, ни черта",
"черта" : "line, trait feature, precincts pl., term",
"чертеж" : "drawing draft  design",
"чертежник" : "draftsman Brt. draughtsman",
"чертежный" : "drawing",
"чертить" : "draw design",
"чертовский" : "devilish",
"чертополох" : "thistle",
"черточка" : "hyphen",
"черчение" : "drawing",
"чесать" : "почесать scratch, причесать famil. comb, impf. hackle card, чесаться famil. itch",
"чеснок" : "garlic",
"чесотка" : "itch",
"чесоточный" : "mangy, scabious",
"чествование" : "celebration",
"чествовать" : "celebrate honor",
"честность" : "honesty",
"честный" : "honest of honor, fair",
"честолюбивый" : "ambitious",
"честолюбие" : "ambition",
"честь" : "honor, credit, по чести famil. honestly, честь честью famil. properly well",
"чета" : "couple pair, famil. match",
"четверг" : "Thursday",
"четвереньки" : "all fours",
"четверка" : "four, cf.",
"четверо" : "four",
"четвероногий" : "four-footed",
"четверостишие" : "quatrain",
"четвертичный" : "quaternary",
"четвертый" : "fourth, cf. пятый",
"четверть" : "fourth, quarter",
"четкий" : "distinct clear, legible, exact accurate",
"четный" : "even",
"четыре" : "four, cf. пять",
"четырежды" : "four times",
"четыреста" : "four hundred",
"четырехвалентный" : "quadrivalent, tetravalent",
"четырехглавый" : "quadriceps",
"четырехгранник" : "tetrahedron",
"четырехлетний" : "four-years'",
"четырехместный" : "four-seated",
"четырехсотый" : "four hundredth",
"четырехсторонний" : "quadrilateral",
"четырехугольник" : "quadrangle",
"четырехугольный" : "quadrangular",
"четырехэтажный" : "four-storied",
"четырнадцатый" : "fourteenth, cf. пятый",
"четырнадцать" : "fourteen, cf. пять",
"чех" : "Czech",
"чехарда" : "leapfrog",
"чехол" : "case cover",
"чехословакия" : "Czechoslovakia",
"чехословацкий" : "Czechoslovak",
"чечевица" : "lentil",
"чечетка" : "redpoll",
"чешка" : "Czech",
"чешский" : "Czech",
"чешуйчатый" : "scaly, squamous",
"чешуя" : "scales pl."
};
