var dicctr_81 = {
"скромность" : "modesty",
"скромный" : "modest, frugal",
"скрупулезный" : "scrupulous",
"скрутить" : "twist, twirl, roll, turn, whirl, impf. trick",
"скручивание" : "torsion, wring",
"скручивать" : "braid, roll, bind, popul. bend",
"скрывать" : "hide conceal",
"скрываться" : "disappear, hide",
"скрытность" : "reserve",
"скрытный" : "reserved reticent",
"скрытый" : "concealed, latent, secret",
"скрыть" : "hide conceal",
"скрыться" : "abscond, welch",
"скряга" : "miser",
"скуба" : "scuba",
"скудный" : "scanty poor",
"скука" : "boredom ennui",
"скула" : "cheekbone",
"скуластый" : "with high cheekbones",
"скулить" : "whimper",
"скульптор" : "sculptor",
"скульптура" : "sculpture",
"скумбрия" : "mackerel",
"скунс" : "skunk",
"скупать" : "buy up",
"скупить" : "buy up",
"скупиться" : "be stingy  stint",
"скупой" : "avaricious stingy, sparing, scanty poor, taciturn, su. miser",
"скупость" : "avarice",
"скучать" : "be bored, long  miss",
"скучный" : "boring tedious dull, sad, скучно feel bored",
"слабеть" : "weaken slacken",
"слабеющий" : "failing, fainting, flagging",
"слабительный" : "laxative",
"слабовольный" : "weak-willed",
"слабосильный" : "s. слабый",
"слабость" : "weakness, infirmity",
"слабоумный" : "feeble-minded",
"слабохарактерный" : "flabby",
"слабый" : "weak  feeble, faint, infirm, delicate, flabby, poor",
"слава" : "glory, fame renown, reputation repute, hail, long live; See also: слава богу{!}, на славу",
"слава богу" : "God be praised! thank goodness!",
"славянский" : "slav, slavic, slavonic",
"слагаемое" : "addend, augend",
"сладкий" : "sweet",
"сладкозвучный" : "dulcet",
"сладострастие" : "voluptuousness",
"сладострастный" : "voluptuous",
"сладость" : "sweetness, delight, cf. сласти",
"слаженный" : "harmonious",
"сланец" : "slate",
"сласти" : "candy Brt. a. sweets",
"слать" : "send",
"слащавый" : "sugary",
"слева" : "on to the left",
"слегка" : "slightly, in passing",
"след" : "trace  track, footprint footstep, print, scent; See also: следом, его и след простыл",
"следить" : "watch follow, look after, shadow, trace",
"следователь" : "examining magistrate",
"следовательно" : "consequently therefore, so",
"следовать" : "follow, ensue, go move, impers. should ought to, be to be, как следует properly duly, famil. downright thoroughly, as it should be, кому #or куда следует to the proper pers. #or quarter, сколько с меня следует? how much do I have to pay?",
"следом" : "behind",
"следствие" : "consequence, inquest trial",
"следующий" : "following next",
"слежка" : "shadowing",
"слеза" : "tear",
"слезать" : "climb #or get down, dismount alight, get out, famil. come off",
"слезиться" : "water",
"слезливый" : "tearful lachrymose",
"слезоточивый" : "tear, watering",
"слезть" : "climb #or get down, dismount alight, get out, famil. come off",
"слепень" : "gadfly",
"слепец" : "blind man",
"слепить" : "sculpture model mold, famil. налепить stick",
"слепнуть" : "grow blind",
"слепой" : "blind, dull, indistinct, su. blind man",
"слепой полет" : "blind flying",
"слепок" : "mould cast",
"слепота" : "blindness",
"слесарь" : "locksmith, fitter mechanic",
"слет" : "flight, rally meeting",
"слетать" : "fly, famil. fall",
"слетаться" : "fly together, famil. gather",
"слететь" : "fly, famil. fall",
"слететься" : "fly together, famil. gather",
"слечь" : "pf. fall ill",
"слива" : "plum",
"сливать" : "pour, fuse merge amalgamate",
"сливающийся" : "confluent, joining",
"сливки" : "cream",
"сливочный" : "creamy, cream",
"слизистый" : "mucous, slimy",
"слизняк" : "slug",
"слизь" : "slime, mucus phlegm",
"слипаться" : "stick together, close",
"слитно" : "a. together, in one word",
"слитный" : "conjoint, continuous",
"слиток" : "ingot",
"слить" : "pour, fuse merge amalgamate",
"сличать" : "compare collate",
"сличить" : "compare collate",
"слишком" : "too too much, это ~ famil. that beats everything",
"слияние" : "confluence, fusion amalgamation, blending",
"словак" : "Slovak",
"словарный состав" : "stock of words",
"словарь" : "dictionary, vocabulary glossary, lexicon",
"словацкий" : "Slovak",
"словачка" : "Slovak",
"словенец" : "Slovene",
"словенка" : "Slovene",
"словенский" : "Slovene",
"словесность" : "literature, lore, philology",
"словесный" : "verbal oral, literary, philologic",
"словно" : "as if, like, famil. as it were",
"слово" : "word, term, speech; See also: к слову сказать, на словах, по словам, просить слово, предоставить слово",
"словоизменение" : "inflection",
"словоохотливый" : "talkative",
"слог" : "syllable, style",
"слоговой" : "syllabic",
"слоеный" : "puff",
"сложение" : "addition, composition, constitution, build, laying down, resignation",
"сложить" : "lay #or put, pile up, pack, fold, add, compose, lay down, сложа руки idle",
"сложность" : "complexity complicacy complication",
"сложный" : "complicated complex intricate, compound",
"слоистый" : "stratiform, flaky",
"слой" : "layer stratum, coat",
"слом" : "demolition destruction",
"сломать" : "break, pull  tear; See also: ломать голову",
"сломить" : "pf. break overcome, overpower",
"сломя голову" : "famil. headlong",
"слон" : "elephant, bishop",
"слоновая кость" : "ivory",
"слоняться" : "linger loaf",
"слуга" : "servant",
"служанка" : "maidservant",
"служащий" : "employee",
"служба" : "service, employment job, office work, duty",
"служебный" : "office..., official, secondary subordinate subservient, gr. relational",
"служение" : "service",
"служитель" : "acolyte",
"служить" : "serve, work, be",
"слукавить" : "dissemble dodge",
"слух" : "hearing, ear, rumor hearsay, news sign",
"слуховой" : "of hearing, acoustic, ear..., dormer",
"случай" : "case, occurrence event, occasion  opportunity chance, несчастный случай; See also: на всякий случай, по случаю",
"случайность" : "chance fortuity",
"случайный" : "accidental casual chance",
"случаться" : "happen, come, take place, famil. be",
"случиться" : "happen, come, take place, famil. be",
"слушай" : "milit. attention!",
"слушать" : "hark, harken, hearken, listen",
"слушаться" : "obey",
"слышать" : "hear, heard",
"слышимый" : "audible",
"слюда" : "mica",
"слюна" : "saliva, spittle, sputum",
"слюнки" : "/pl.: слюнки текут, mouth waters",
"слюнный" : "salivary",
"слюнявый" : "slobbery",
"слякоть" : "slush",
"см" : "abbr.: смотри see v",
"смазка" : "greasing, lubricant",
"смазывать" : "anoint, lubricate",
"смачивать" : "humect, moisten",
"смежность" : "contiguity",
"смежный" : "adjacent, communicating, conterminous",
"смелый" : "bold, courageous, mettlesome, venturous",
"смена" : "shift, milit. relief, change, supersession, successors pl., прийти на смену s. смениться",
"сменить" : "supersede milit. relieve, replace substitute, change",
"сменять" : "supersede milit. relieve, replace substitute, change",
"смерить" : "measure",
"смеркаться" : "grow dusky #or dark",
"смеркнуться" : "grow dusky #or dark",
"смертельный" : "mortal fatal deadly",
"смертность" : "mortality death rate",
"смертный" : "mortal  deadly fatal, death ..., jur. capital",
"смертоносный" : "lethal",
"смерть" : "death, famil. deadly utterly; See also: при смерти",
"смерч" : "waterspout, tornado",
"смесить" : "knead",
"смести" : "s. сметать",
"сместить" : "s. смещать",
"смесь" : "mixture, blend, alloy, miscellanies pl.",
"смета" : "estimate",
"сметана" : "sour cream",
"сметать" : "sweep away, sweep together, wipe off",
"сметливый" : "sharp",
"сметывать" : "baste",
"сметь" : "dare venture, beg",
"смех" : "laughter, joke fun, cf. шутка",
"смехотворный" : "ludicrous, ragtime",
"смешанный" : "mixed",
"смешать" : "s. смешивать",
"смешение" : "amalgamation, blend, commixture, compounding",
"смешивать" : "commingle, intermix, mingle",
"смешливый" : "risible",
"смещать" : "depose, dislocate, displace, translocate",
"смещенный" : "offset",
"смирно" : "shun",
"смог" : "smog",
"смокинг" : "tuxedo dinner jacket",
"смоковница" : "sycamine",
"смола" : "resin, pitch, tar",
"смолистый" : "resinous",
"смолить" : "pitch tar",
"смолкать" : "grow silent, cease",
"смолкнуть" : "grow silent, cease",
"смолоду" : "famil. from one's youth",
"смолотить" : "thresh",
"смолоть" : "grind, impf. talk",
"смоляной" : "pitch... tar...",
"смонтировать" : "assemble install, cut",
"сморкаться" : "blow one's nose",
"смородина" : "currant",
"сморчок" : "morel",
"сморщить" : "wrinkle frown, distort",
"смотать" : "reel wind, once мотнуть shake wag, beckon point, jerk, famil. промотать squander waste",
"смотр" : "review, parade show, inspection",
"смотреть" : "look  gaze, view see watch, examine inspect, mind, look out",
"смотреть в оба" : "be all eyes",
"смотри" : "vide",
"смотритель" : "inspector, master",
"смотря" : "it depends  according",
"смочить" : "moisten",
"смочь" : "can be able, may, я не могу не  inf. I can't help ...ing, не могу знать... I don't know; See also: не может быть{!}",
"смошенничать" : "swindle",
"смрад" : "stench",
"смрадный" : "stinking",
"смуглый" : "swarthy",
"смудрить" : "subtilize, quibble, trick, bully",
"смутить" : "s. смущать",
"смутный" : "hazy, nebulous",
"смущать" : "abash, disconcert, embarrass, flummox",
"смущение" : "confusion, embarrassment",
"смыв" : "washout",
"смычковый" : "mus. stringed",
"смычок" : "mus. bow",
"смышленый" : "clever bright",
"смягчать" : "soften, mitigate alleviate, extenuate, phon. palatalize",
"смягчающий" : "jur. extenuating",
"смягчение" : "mitigation, extenuation, palatalization",
"смягчить" : "soften, mitigate alleviate, extenuate, phon. palatalize",
"смягчиться" : "a. relent",
"смятение" : "confusion",
"смять" : "rumple press, knead wrinkle, trample",
"снабдить" : "supply furnish provide",
"снабжать" : "supply furnish provide",
"снабжение" : "supply provision, purchasing",
"снайпер" : "sharpshooter",
"снаружи" : "from outside"
};
