var dicctr_2 = {
"бактерии" : "bacteria",
"бактерия" : "bacterium",
"баку" : "baku",
"балагур" : "joker",
"балагурить" : "joke crack jokes",
"балалайка" : "balalaika",
"баламутить" : "trouble stir up",
"баланс" : "balance, торговый баланс balance of trade",
"балансировать" : "balance",
"балансовый" : "balance...",
"балбес" : "simpleton booby",
"балда" : "blockhead dolt",
"балдахин" : "canopy",
"балерина" : "ballet dancer",
"балет" : "ballet",
"балетоман" : "balletomane",
"балка" : "beam, hollow",
"балканский" : "Balkan...",
"балкон" : "balcony",
"балл" : "grade mark, point",
"баллада" : "ballad",
"балласт" : "ballast",
"баллистический" : "ballistic",
"баллон" : "balloon",
"баллотировать" : "ballot",
"баллотировка" : "vote poll",
"балованный" : "spoilt",
"баловать" : "be naughty, trifle",
"баловень" : "darling pet",
"баловник" : "urchin brat",
"баловница" : "tomboy",
"баловство" : "naughtiness spoiling trifling",
"балтийский" : "Baltic...",
"бальзам" : "balm",
"бальзамировать" : "embalm",
"балюстрада" : "balustrade",
"бамбук" : "bamboo",
"банальность" : "banality, commonplace",
"банальный" : "banal trite",
"банан" : "banana",
"бангкок" : "bangkok",
"банда" : "gang",
"бандаж" : "bandage, truss",
"бандероль" : "wrapper",
"бандит" : "bandit gangster",
"бандит-вымогатель" : "racketeer",
"банк" : "bank",
"банка" : "jar, can Brt. tin",
"банкет" : "banquet",
"банкир" : "banker",
"банкнот" : "bank note",
"банкнота" : "bank note",
"банкрот" : "bankrupt",
"банкротиться" : "go bankrupt",
"банкротство" : "bankruptcy",
"бант" : "bow",
"банщик" : "attendant",
"банщица" : "attendant",
"баня" : "bath",
"баптист" : "baptist",
"бар" : "saloon bar",
"барабан" : "drum",
"барабанить" : "drum",
"барабанный" : "барабанный бой beat of the drum, барабанная перепонка eardrum",
"барак" : "hut",
"барбарис" : "barberry",
"барбекю" : "barbecue",
"баржа" : "barge, hoy",
"барий" : "barium",
"баритон" : "baritone, barytone",
"баркас" : "launch",
"барометр" : "barometer",
"баронесса" : "baroness",
"баронский" : "baronial",
"баррикада" : "barricade",
"барс" : "panther",
"барский" : "lordly, manorial, жить на барскую ногу live in grand style",
"барство" : "the noble class, gentility, idleness, haughtiness",
"барсук" : "badger",
"бархат" : "velvet",
"бархатистый" : "velvety",
"бархатный" : "velvet",
"барщина" : "statute labor corve'e",
"барыня" : "lady, mistress, madam ma'am",
"барыш" : "profit gain",
"барышник" : "forestaller, horsedealer",
"барышничать" : "buy up practise usury",
"барышничество" : "forestallment",
"барышня" : "young lady, miss",
"барьер" : "barrier",
"барьерный бег" : "hurdle race",
"бас" : "bass",
"баск" : "Basque",
"баскетбол" : "basketball",
"баснописец" : "fabulist",
"баснословный" : "fabulous incredible",
"басня" : "fable",
"басовый" : "bass",
"басон" : "galloon lace",
"бассейн" : "basin, region; See also: бассейн для плавания",
"бассейн для плавания" : "swimming-pool",
"баста" : "that will do, no more of this!",
"бастард" : "bastard, hybrid",
"бастион" : "bastion",
"бастовать" : "strike",
"батальон" : "battalion",
"батальонный" : "battalion..., батальонный battalion commander",
"батарейка" : "flashlight",
"батарейный" : "battery",
"батарея" : "milit. battery",
"батист" : "cambric",
"батистовый" : "of cambric",
"батрак" : "day laborer farm hand",
"батюшка" : "father papa, priest, dear friend old boy, как вас по батюшке? what's your father's name?; See also: батюшки{!}",
"батюшки" : ", good gracious! o dear!",
"бахрома" : "fimbria, fringe, thrum",
"бахус" : "bacchus",
"бацилла" : "bacillus",
"башка" : "coco, cocoanut, nob, noddle",
"башмак" : "chock",
"башня" : "turret",
"бдительный" : "alert, vigilant, watchful",
"беганье" : "running, беганье на коньках skating",
"бегать" : "run, famil. shun, fig. run after; See also: бегать взапуски",
"бегать взапуски" : "famil. race vie in a run",
"бегемот" : "hippopotamus",
"беглец" : "runaway",
"беглость" : "fluency agility, cursoriness",
"беглый" : "fluent agile, cursory, fugitive",
"беговая дорожка" : "race track",
"беговой" : "race...",
"бегом" : "in full career",
"беготня" : "running about bustle",
"бегство" : "flight  escape stampede",
"бегун" : "runner, trotter",
"бегущий" : "running",
"беда" : "misfortune disaster mischief, что за беда? what does it matter?, не беда it doesn't matter, беда не велика there's no harm in that, в том-то и беда that's the trouble, на беду famil. unluckily, беда как famil. awfully",
"бедненький" : "poor pitiable",
"беднеть" : "grow poor",
"бедность" : "poverty",
"беднота" : "the poor coll.",
"бедный" : "poor",
"бедняга" : "poor fellow wretch",
"бедняжка" : "poor fellow wretch",
"бедняк" : "poor man pauper, small farmer",
"бедро" : "thigh, hip, loin",
"бедственное положение" : "distress emergency",
"бедственный" : "disastrous miserable; See also: бедственное положение",
"бедствие" : "distress disaster",
"бедствовать" : "suffer want live in misery",
"бедуин" : "bedouin",
"бежать" : "run, flee, avoid shun, бежать сломя голову, famil. run for one's life #or head over heels",
"бежать наперегонки" : "race, chase each other",
"бежевый" : "beige",
"беженец" : "refugee",
"беженка" : "refugee",
"без" : ", without ...less, out of, less, to; See also: безо всего, без вас ...",
"без зазрения" : "without remorse #or shame",
"без запинки" : "fluently smoothly",
"без конца" : "endless",
"без малого" : "almost just short of",
"без оглядки" : "headlong hastily",
"без памяти" : "unconscious, famil. mad",
"без сознания" : "unconscious",
"без умолку" : "incessantly",
"без утайки" : "frankly",
"без чувств" : "unconscious senseless",
"безалаберный" : "slovenly disorderly",
"безалкогольный" : "nonalcoholic",
"безапелляционный" : "unappealable, peremptory",
"безбедный" : "well off",
"безбилетный" : "безбилетный пассажир",
"безбилетный пассажир" : "stowaway",
"безбожие" : "atheism ungodliness",
"безбожник" : "atheist",
"безбожница" : "atheist",
"безбожность" : "atheism ungodliness",
"безбожный" : "atheistic godless impious, unscrupulous, famil. awful",
"безболезненный" : "painless",
"безбородый" : "beardless",
"безбоязненный" : "fearless",
"безбрачие" : "celibacy",
"безбрачный" : "unmarried",
"безбрежный" : "shoreless boundless",
"безверие" : "unbelief",
"безвестный" : "unknown",
"безветренный" : "calm",
"безветрие" : "calm",
"безвинный" : "guiltless innocent",
"безвкусие" : "tastelessness bad taste",
"безвкусица" : "tastelessness bad taste",
"безвкусный" : "tasteless insipid",
"безвластие" : "anarchy",
"безводный" : "arid",
"безвозвратный" : "irretrievable",
"безвоздушный" : "void of air",
"безвозмездный" : "gratuitous, without compensation",
"безволосый" : "hairless bald",
"безвольный" : "lacking willpower weak-willed",
"безвредный" : "harmless",
"безвременный" : "premature",
"безвыездный" : "permanent",
"безвыходный" : "continual, desperate hopeless",
"безголовый" : "headless, stupid, forgetful",
"безграмотность" : "illiteracy ignorance",
"безграмотный" : "illiterate, faulty",
"безграничный" : "boundless unlimited",
"бездарный" : "untalented dull, bungling",
"бездействие" : "inactivity",
"бездействовать" : "be inactive idle",
"бездействующий" : "dormant, inactive",
"безделица" : "trifle, nick-nack",
"безделка" : "trifle, nick-nack",
"безделушка" : "trifle, nick-nack",
"безделушки" : "whatnot",
"безделье" : "idleness",
"бездельник" : "idler, good-for-nothing",
"бездельница" : "idler, good-for-nothing",
"бездельничать" : "idle lounge",
"безденежье" : "want of money",
"бездетный" : "childless",
"бездеятельный" : "inactive",
"бездна" : "abyss, famil. lots",
"бездомный" : "homeless",
"бездонный" : "bottomless, fig. unfathomable",
"бездорожный" : "impassable",
"бездорожье" : "impassability",
"бездоходный" : "unprofitable",
"бездушный" : "soulless, heartless",
"безжалостный" : "ruthless",
"безжизненный" : "lifeless, fig. dull",
"беззаботный" : "careless, carefree",
"беззаветный" : "unselfish, unreserved",
"беззаконие" : "lawlessness, anarchy",
"беззаконность" : "illegality",
"беззаконный" : "illegal, lawless",
"беззастенчивый" : "shameless, impudent, unscrupulous",
"беззащитный" : "defenseless, unprotected",
"беззвездный" : "starless",
"беззвучный" : "soundless, silent, mute",
"безземельный" : "landless",
"беззлобный" : "good-natured",
"беззубый" : "toothless",
"безличный" : "impersonal",
"безлюдный" : "deserted uninhabited",
"безмерный" : "immeasurable, immense",
"безмозглый" : "brainless stupid",
"безмолвие" : "silence",
"безмолвный" : "silent",
"безмятежный" : "quiet calm, undisturbed"
};
