var dicctr_97 = {
"шип" : "calk, gudgeon, tenon, thorn",
"шипение" : "fizz, hiss, sizzle, sputter",
"шиповник" : "briar, brier, sweetbrier",
"шипящий" : "sibilant",
"ширина" : "width breadth, шириной в #or ... в ширину ... wide",
"ширить" : "widen spread",
"шириться" : "widen spread",
"ширма" : "screen",
"широкий" : "broad, wide, vast, large, great, mass..., large-scale, phon. open; See also: на широкую ногу",
"широковещательный" : "broadcasting, promising",
"широкоплечий" : "broad-shouldered",
"широта" : "breadth, geogr. latitude",
"ширпотреб" : "consumer's goods",
"ширь" : "breadth width, open",
"шить" : "sew, embroider, have made",
"шитье" : "sewing, embroidery",
"шиферный" : "slate",
"шифр" : "cipher code, pressmark",
"шифровальщик" : "cryptographer",
"шифровать" : "cipher code",
"шиш" : "fig",
"шишка" : "bump lump, bot. cone, knot, famil. bigwig",
"шкала" : "scale",
"шкатулка" : "casket",
"шкаф" : "cupboard, wardrobe, case, несгораемый шкаф safe",
"шкафчик" : "cabinet",
"шквал" : "squall gust",
"шкив" : "pulley",
"школа" : "school, высшая школа academy, university",
"школьник" : "schoolboy",
"школьница" : "schoolgirl",
"школьный" : "school...",
"шкура" : "skin  hide",
"шкурник" : "self-seeker",
"шлагбаум" : "barrier turnpike",
"шлак" : "slag scoria, cinder",
"шлаковый" : "slag",
"шланг" : "hose",
"шлем" : "helmet",
"шлеп" : "famil. crack",
"шлепать" : "slap, shuffle, plump",
"шлепнуть" : "slap, shuffle, plump",
"шлепнуться" : "flop",
"шлепок" : "slap, spank",
"шлифовать" : "grind, polish",
"шлюз" : "sluice lock",
"шлюзовый" : "sluice",
"шлюпка" : "boat, launch",
"шляпа" : "hat, famil. milksop",
"шляпка" : "dim. #of шляпа, hat, head",
"шляпный" : "hat..., hatter's, milliner's",
"шляпочник" : "hatter",
"шляться" : "s. шататься",
"шмель" : "bumblebee",
"шмыг" : "quick!",
"шмыгать" : "whisk scurry slip",
"шмыгнуть" : "whisk scurry slip",
"шницель" : "cutlet",
"шнур" : "cord",
"шнуровать" : "lace up",
"шнурок" : "shoestring lace",
"шнырять" : "poke about",
"шов" : "seam, a. joint",
"шоколад" : "chocolate",
"шомпол" : "ramrod",
"шопот" : "s. шепот",
"шорник" : "saddler",
"шорох" : "rustle",
"шоссе" : "high road",
"шотландец" : "Scotchman pl. the Scotch",
"шотландия" : "Scotland",
"шотландка" : "Scotchwoman",
"шотландский" : "Scotch Scottish",
"шофер" : "driver chauffeur",
"шпага" : "sword",
"шпагат" : "packthread string",
"шпала" : "cross tie Brt. sleeper",
"шпалера" : "trellis, lane",
"шпаргалка" : "pony Brt. crib",
"шпат" : "min. spar",
"шпатель" : "spatula",
"шпатовый" : "spathic",
"шпиговать" : "lard",
"шпик" : "slab bacon fat, famil. sleuth",
"шпиль" : "spire",
"шпилька" : "hairpin, hat pin, tack, fig. taunt twit",
"шпинат" : "spinach",
"шпион" : "spy",
"шпионаж" : "espionage",
"шпионить" : "spy",
"шпионка" : "spy",
"шпиц" : "Pomeranian",
"шпонка" : "spline",
"шпора" : "spur",
"шпорить" : "spur",
"шприц" : "syringe squirt",
"шпрот" : "sprat brisling",
"шпулька" : "spool bobbin",
"шпунтовать" : "rabbet",
"шрам" : "scar",
"шрапнель" : "shrapnel",
"шрифт" : "type print",
"штаб" : "staff, headquarters",
"штабель" : "pile",
"штабной" : "staff...",
"штамп" : "stamp",
"штамповать" : "stamp",
"штамповка" : "stamping",
"штанга" : "engin. pole, #sport: weight",
"штаны" : "pants trousers",
"штат" : "state, staff, cf. США",
"штатив" : "support, phot. tripod",
"штатный" : "staff",
"штатский" : "civil, civilian, plain",
"штемпелевать" : "stamp, postmark",
"штемпель" : "stamp, postmark",
"штепсель" : "plug, jack",
"штиль" : "calm",
"штифт" : "pin",
"штопать" : "darn",
"штопка" : "darning",
"штопор" : "corkscrew, av. spin",
"штора" : "blind, curtain",
"шторм" : "storm",
"штоф" : "quart bottle, damask",
"штраф" : "fine penalty mulct",
"штрафной" : "fine..., penalty..., convict...",
"штрафовать" : "fine",
"штрейкбрехер" : "strikebreaker",
"штрих" : "stroke, trait, touch",
"штриховать" : "hatch, shade",
"штудировать" : "study",
"штука" : "piece, famil. thing, fish, trick, story, business, point",
"штукатурить" : "plaster",
"штукатурка" : "plaster",
"штурвал" : "steering wheel",
"штурм" : "storm onslaugt",
"штурман" : "navigator",
"штурмовать" : "storm assail",
"штурмовик" : "battleplane",
"штучный" : "piece",
"штык" : "bayonet",
"шуба" : "fur",
"шулер" : "sharper",
"шум" : "noise, din, rush, bustle, buzz, famil. hubbub row ado; See also: шум и гам, наделать шуму",
"шум и гам" : "hullabaloo",
"шуметь" : "make a noise, rustle, rush, roar, bustle, buzz",
"шумиха" : "sensation clamor",
"шумливый" : "clamorous",
"шумный" : "noisy loud, sensational",
"шумовой" : "noise..., jazz...",
"шумок" : "famil. on the sly",
"шура" : "dim. #of Александр",
"шурин" : "brother-in-law",
"шуршать" : "rustle",
"шустрый" : "nimble",
"шут" : "fool jester clown buffoon, famil. deuce",
"шут гороховый" : "fig. scarecrow, boor merry-andrew",
"шутить" : "joke jest, make fun",
"шутка" : "joke jest, fun, trick, famil. trifle, кроме шуток joking apart, are you in earnest?, не на шутку serious, не до шуток be in no laughing mood",
"шутливый" : "jocose playful",
"шутник" : "joker wag",
"шуточный" : "jocose sportive comic, laughing",
"шутя" : "jokingly",
"шушукать" : "whisper",
"шхуна" : "schooner",
"ш-ш" : "hush!",
"щавелевый" : "oxalic",
"щебетание" : "chirp",
"щегол" : "goldfinch",
"щеголеватый" : "spruce",
"щеголь" : "beau, coxcomb, fop",
"щедрость" : "bounty, generosity, largess, largesse",
"щедрый" : "bounteous, bountiful, freehanded, generous",
"щека" : "cheek",
"щеколда" : "heck, latch",
"щекотать" : "titillate",
"щекотка" : "tickle, tickling",
"щекотливый" : "ticklish",
"щелкнуть" : "click, snap  crack, chatter, warble sing, fillip, crack",
"щелок" : "lye",
"щелочной" : "alkaline",
"щелочь" : "alkali",
"щелчок" : "fillip, crack",
"щель" : "chink crack crevice, slit; See also: голосовая щель",
"щемить" : "press, fig. oppress",
"щенок" : "puppy whelp",
"щепетильный" : "scrupulous punctilious squeamish fancy...",
"щепка" : "chip, fig. lath",
"щепотка" : "pinch",
"щетина" : "bristle",
"щетинистый" : "bristly",
"щетиниться" : "bristle up",
"щетка" : "brush",
"щи" : "cabbage soup",
"щиколотка" : "ankle",
"щипать" : "pinch tweak  nip, bite, twitch, pluck, browse",
"щипнуть" : "pinch tweak  nip, bite, twitch, pluck, browse",
"щипок" : "nip, pinch, tweak",
"щипцы" : "barnacle, forceps, tongs",
"щипчики" : "tweezers",
"щит" : "shield, buckler, screen guard protection, shed, board, sluice gate, shell",
"щитовидный" : "thyroid",
"щиток" : "scute, scutum",
"щука" : "pike",
"щупальце" : "feeler tentacle",
"щупать" : "feel, touch, fig. sound",
"щуплый" : "puny",
"щурить" : "screw up",
"эвакуировать" : "pf. evacuate",
"эвкалипт" : "eucalyptus",
"эвклид" : "euclid",
"эволюционный" : "evolution",
"эвристический" : "heuristic",
"эгоизм" : "egoism selfishness",
"эгоист" : "egoist",
"эгоистический" : "selfish",
"эгоистичный" : "selfish",
"эгоистка" : "egoist",
"эгоцентричный" : "egocentric, self-centered",
"эдинбург" : "Edinburgh",
"эдип" : "oedipus",
"эй" : "halloo! hullo! hey!",
"эквадор" : "ecuador",
"экваториальный" : "equatorial",
"эквивалентный" : "equivalent",
"эквидистантный" : "equidistant",
"экзамен" : "examination",
"экзаменатор" : "examiner",
"экзаменовать" : "examine",
"экзаменоваться" : "be examined  have one's examination, p.pr.p. examinee",
"экземпляр" : "copy, specimen",
"экзотический" : "exotic",
"экий" : "what",
"экипаж" : "carriage, av. crew",
"экипировать" : "pf. fit out equip",
"экономика" : "economy, economics",
"экономист" : "economist",
"экономить" : "save, economize",
"экономический" : "economic",
"экономия" : "economy, saving",
"экономный" : "economical thrifty",
"экран" : "screen",
"экскаватор" : "dredge",
"экскурсант" : "excursionist",
"экскурсионный" : "sightseeing",
"экскурсия" : "excursion outing trip",
"экскурсовод" : "guide",
"экспансивный" : "effusive, expansive",
"экспедитор" : "forwarding agent"
};
