var dicctr_67 = {
"президиум" : "presidium",
"презирать" : "despise",
"презрение" : "contempt",
"презренный" : "contemptible despicable",
"презреть" : "scorn disdain",
"презрительный" : "contemptuous scornful",
"преимущественно" : "predominantly mainly",
"преимущественный" : "preemptive",
"преимущество" : "advantage, preference, privilege, по преимуществу = преимущественно",
"прейскурант" : "price list",
"преклонение" : "inclination, admiration",
"преклониться" : "s. преклоняться",
"преклонный" : "old advanced, senile",
"преклоняться" : "bow, admire",
"прекословить" : "contradict",
"прекрасный" : "beautiful, fine splendid excellent, a. very well",
"прекратить" : "stop cease end, break off",
"прекращать" : "stop cease end, break off",
"прекращение" : "cessation stoppage",
"прелестный" : "lovely charming delightful",
"прелесть" : "charm, s. прелестный",
"преломить" : "refract",
"преломление" : "refraction",
"преломлять" : "refract",
"прелый" : "rotten putrid",
"прельстить" : "charm tempt entice seduce",
"прельщать" : "charm tempt entice seduce",
"прелюбодеяние" : "adultery",
"прелюдия" : "prelude",
"преминуть" : "pf. fail",
"премировать" : "pf. award a prize",
"премия" : "prize, bonus, premium, rate",
"премьер" : "premier prime minister",
"премьера" : "premiere first night",
"пренебрегать" : "neglect disregard disdain scorn slight",
"пренебрежение" : "neglect disregard disdain scorn slight",
"пренебрежительный" : "slighting scornful disparaging",
"пренебречь" : "neglect disregard disdain scorn slight",
"прения" : "debate discussion",
"преобладание" : "predominance",
"преобладать" : "prevail predominate",
"преобладающий" : "predominant, prevalent, regnant",
"преображать" : "change transform",
"преображение" : "transformation, eccl. Transfiguration",
"преобразить" : "change transform",
"преобразование" : "transformation, reorganization, reform",
"преобразователь" : "reformer",
"преобразовать" : "reform reorganize, transform",
"преобразовывать" : "reform reorganize, transform",
"преодолевать" : "overcome subdue, surmount",
"преодолеть" : "overcome subdue, surmount",
"препарат" : "preparation",
"препирательство" : "wrangle",
"препираться" : "altercate",
"преподавание" : "teaching instruction",
"преподаватель" : "teacher instructor",
"преподавательница" : "teacher instructor",
"преподавать" : "teach",
"преподнести" : "present offer",
"преподносить" : "present offer",
"препроводить" : "forward send, spend pass",
"препровождать" : "forward send, spend pass",
"препятствие" : "obstacle hindrance, бег с препятствиями steeplechase",
"препятствовать" : "hinder prevent",
"прервать" : "s. прерывать",
"пререкания" : "brabble, wrangle",
"прерывать" : "interrupt",
"пресекать" : "cut short, suppress",
"пресекаться" : "break, stop",
"пресечь" : "cut short, suppress",
"преследование" : "pursuit, persecution, jur. prosecution",
"преследовать" : "pursue, persecute, haunt, jur. prosecute",
"преследующий" : "haunting",
"пресловутый" : "notorious",
"пресмыкаться" : "creep crawl, fig. cringe",
"пресмыкающееся" : "reptile",
"пресмыкающиеся" : "reptiles",
"пресноводный" : "freshwater, landlocked, limnetic",
"пресный" : "fresh, unleavened, stale",
"пресс" : "engin. press",
"пресса" : "press",
"пресс-конференция" : "press conference",
"пресс-папье" : "paperweight",
"престарелый" : "aged",
"престиж" : "prestige",
"престижный" : "prestigious",
"престо" : "presto",
"престол" : "throne, altar",
"преступать" : "break infringe",
"преступить" : "break infringe",
"преступление" : "crime, на месте преступления red-handed",
"преступник" : "criminal delinquent",
"преступность" : "criminality delinquency",
"преступный" : "criminal, culpable, felon, felonious, flagitious",
"пресытить" : "surfeit  satiate",
"пресыщать" : "surfeit  satiate",
"пресыщение" : "satiety",
"пресыщенный" : "blase, satiate",
"претворить" : "change transform",
"претворять" : "change transform",
"претворять в жизнь" : "put into practice realize",
"претендовать" : "claim",
"претензия" : "claim pretension title, быть в претензии take amiss #or ill",
"претенциозный" : "pretentious",
"преувеличение" : "exaggeration",
"преувеличенный" : "exaggerated, hyperbolic, hyperbolical, overdone",
"преувеличивать" : "exaggerate",
"преувеличить" : "exaggerate",
"преуспевать" : "succeed, thrive prosper",
"преуспеть" : "succeed, thrive prosper",
"префект" : "prefect",
"префектура" : "prefecture",
"преходящий" : "ephemeral, transient",
"прецессия" : "precession",
"при" : "by at near, of, under in the time of, in a pers.'s presence, about  with, in, for, when on, при сем; See also: при всем том, быть при, при этом, быть ни при чем",
"при виде" : "at the sight of",
"при всем том" : "for all that",
"при посредстве" : "by means of",
"при сем" : "herewith",
"при смерти" : "at death's door",
"при этом" : "at that",
"прибавить" : "s. прибавлять",
"прибавлять" : "append, intercalate",
"прибавь" : "add",
"прибаутка" : "byword saying",
"прибегать" : "прибежать come running, прибегнуть resort have recourse",
"приберегать" : "save reserve",
"приберечь" : "save reserve",
"прибивать" : "fasten nail, beat, throw",
"прибирать" : "tidy #or clean; See also: прибрать к рукам",
"прибираться" : "o.s. up",
"прибить" : "fasten nail, beat, throw",
"приближать" : "approach draw near, approximate",
"приближение" : "approach, approximation",
"приближенный" : "confidant, приблизительный",
"приблизительный" : "approximate",
"приблизить" : "approach draw near, approximate",
"приблизиться" : "approach",
"прибой" : "surf",
"прибор" : "apparatus instrument, set, cover, service, ware, utensils pl.",
"приборный" : "instrument",
"прибрать" : "tidy #or clean; See also: прибрать к рукам",
"прибрать к рукам" : "appropriate",
"прибрежный" : "littoral",
"прибывать" : "arrive, increase rise",
"прибыль" : "profit gains pl., rise",
"прибыльный" : "profitable",
"прибытие" : "arrival",
"прибыть" : "arrive, increase rise",
"привал" : "halt rest",
"приведение" : "putting, math. reduction",
"привезти" : "s. привозить",
"привередливый" : "fastidious",
"приверженец" : "adherent",
"приверженный" : "attached",
"привести" : "s. приводить",
"привестись" : "vb. famil. happen, have to",
"привет" : "greeting, milit. salute, regards compliments pl., famil. hello! hi!",
"приветливый" : "affable",
"приветственный" : "of welcome",
"приветствие" : "greeting welcome",
"приветствовать" : "greet salute, welcome",
"прививать" : "inoculate vaccinate, bot. graft",
"прививаться" : "take",
"прививка" : "inoculation vaccination, grafting",
"привидение" : "ghost specter  apparition",
"привилегированный" : "privileged",
"привилегия" : "privilege",
"привинтить" : "screw on",
"привинчивать" : "screw on",
"привить" : "inoculate vaccinate, bot. graft",
"привкус" : "smack",
"привлекательный" : "attractive",
"привлекать" : "draw attract, engage, call, bring",
"привлечение" : "attraction, calling",
"привлечь" : "draw attract, engage, call, bring",
"привод" : "bringing, engin. drive",
"приводить" : "bring, lead, result, quote cite, math. reduce, put set, drive throw",
"приводиться" : "vb. famil. happen, have to",
"приводной" : "driving",
"привозить" : "bring, import",
"привозной" : "imported",
"привозный" : "imported",
"приволье" : "open  expanse, freedom, ease comfort, в приволье a. in clover",
"привратник" : "doorkeeper, doorman, gatekeeper, pylorus",
"привыкать" : "get #or be accustomed #or used",
"привыкнуть" : "get #or be accustomed #or used",
"привычка" : "habit, custom",
"привычный" : "habitual",
"привязанность" : "attachment",
"привязать" : "s. привязывать",
"привязывать" : "fasten, tie up",
"приглашать" : "invite",
"приглашение" : "invitation",
"приглашенный" : "invitee",
"приговор" : "condemnation",
"пригодный" : "available, serviceable",
"пригонять" : "drive, fit adjust",
"пригорать" : "burn",
"пригореть" : "burn",
"пригород" : "suburb",
"пригородный" : "suburban",
"пригоршня" : "hand",
"приготавливать" : "s. приготовлять",
"приготовительный" : "prep",
"приготовление" : "preparative",
"приданое" : "dower, trousseau",
"придаток" : "appendage, appurtenance",
"придаточный" : "gr. subordinate",
"придать" : "add, give, attach",
"придача" : "в придачу",
"придворный" : "courtier",
"придерживался" : "upheld",
"придираться" : "upbraid",
"придирка" : "cavil",
"придорожный" : "wayside",
"придумывать" : "think out devise contrive",
"придыхание" : "aspiration",
"приезд" : "arrival",
"приезжать" : "arrive",
"приезжий" : "visitant... guest...",
"прием" : "reception, acceptance admission, consultation, engagement milit. enlistment, taking, dose, movement, draught, sitting, device trick, method way",
"приемник" : "receiver receiving set, s. радиоприемник",
"приемный" : "reception, receiving consultation... office, entrance, foster",
"приехать" : "arrive",
"прижать" : "s. прижимать",
"прижигать" : "cauterize, sear",
"приз" : "prize",
"призванный" : "conscript",
"призвать" : "s. призывать",
"приземистый" : "stocky",
"приземление" : "landing",
"приземлиться" : "land",
"приземляться" : "land",
"призма" : "prism",
"призматический" : "prismatic",
"признавать" : "recognize acknowledge, see admit own, find consider declare, -ся confess  avow admit, признаться #or признаюсь, to tell the truth frankly speaking",
"признак" : "sign, feature characteristic",
"признание" : "acknowledgment recognition, confession, declaration",
"признательность" : "gratitude",
"признательный" : "grateful thankful",
"признать" : "recognize acknowledge, see admit own, find consider declare, -ся confess  avow admit, признаться #or признаюсь, to tell the truth frankly speaking",
"призрак" : "phantom specter",
"призрачный" : "ghostly, illusive",
"призыв" : "appeal call  summons, milit. draft conscription",
"призывать" : "call  appeal, milit. draft call out #or up, призванный a. qualified",
"призывник" : "draftee conscript",
"призывной" : "milit. draft...",
"прииск" : "mine field",
"прийти" : "s. приходить"
};
