var dicctr_71 = {
"просодия" : "prosody",
"просопопея" : "prosopopoeia",
"просохнуть" : "s. просыхать",
"просочиться" : "ooze  percolate",
"проспать" : "s. просыпать",
"проспект" : "avenue, prospectus",
"проспрягать" : "gr. conjugate",
"просрочивать" : "let lapse expire, exceed",
"просрочить" : "let lapse expire, exceed",
"просрочка" : "expiration, exceeding",
"простаивать" : "stand, stay",
"простак" : "simpleton",
"простата" : "prostate",
"простенок" : "pier",
"простереть" : "stretch  extend",
"простирать" : "stretch  extend",
"простительный" : "pardonable excusable venial",
"проститутка" : "prostitute",
"проституция" : "prostitution, whoredom",
"простить" : "s. прощать",
"просто" : "simply",
"простой" : "abc, childlike, demurrage, homely, outage, simple",
"просторный" : "airy, commodious, roomy, spacious",
"простосердечный" : "s. простодушный",
"простота" : "simplicity, naivete', silliness",
"простофиля" : "ninny",
"простоять" : "stand, stay",
"пространный" : "vast, diffuse",
"пространственный" : "spatial, steric",
"пространство" : "space, room, area",
"прострел" : "lumbago",
"простреливать" : "shoot",
"прострелить" : "shoot",
"простуда" : "cold",
"простудить" : "chill",
"простудиться" : "catch a cold",
"простуживать" : "chill",
"простуживаться" : "catch a cold",
"проступок" : "offence",
"простым глазом" : "with the naked eye",
"простыня" : "sheet",
"просунуть" : "pass #or push",
"просушивать" : "dry",
"просушить" : "dry",
"просфора" : "eccl. Host",
"просчитаться" : "pf. miscalculate",
"просыпать" : "oversleep, sleep, famil. miss",
"просыпаться" : "awake wake up",
"просыхать" : "dry",
"просьба" : "request, entreaty, obsol. petition, please, ~ ask a favor",
"протактиний" : "protactinium",
"проталкивать" : "push, -ся force one's way",
"протаптывать" : "tread, famil. wear out #or down",
"протаранить" : "ram",
"протаскивать" : "carry #or drag, famil. smuggle in",
"протащить" : "carry #or drag, famil. smuggle in",
"протеаза" : "protease",
"протеже" : "protege",
"протез" : "artificial limb",
"протезный" : "prosthetic",
"протекать" : "flow, leak, pass elapse, take a ... course",
"протекторат" : "protectorate, suzerainty",
"протекция" : "patronage",
"протереть" : "s. протирать",
"протест" : "protest",
"протестантский" : "protestant",
"протестовать" : "protest",
"протечь" : "flow, leak, pass elapse, take a ... course",
"против" : "against, opposite; See also: быть против, иметь против",
"противиться" : "oppose object",
"противник" : "opponent adversary, enemy",
"противный" : "repugnant disgusting offensive nasty, opposite contrary; See also: мне противно, в противном случае",
"противовес" : "counterbalance",
"противовоздушный" : "anti-aircraft  air-raid",
"противогаз" : "gas mask",
"противодействие" : "counteraction, resistance",
"противодействовать" : "counteract, resist",
"противодействующий" : "reactionary",
"противоестественный" : "unnatural",
"противозаконный" : "unlawful illegal",
"противомоскитный" : "mosquito",
"противообщественный" : "antisocial",
"противоположное" : "reverse",
"противоположности" : "antipodes",
"противоположность" : "contrast opposition, antithesis",
"противоположный" : "opposite, contrary opposed",
"противопоставить" : "oppose",
"противопоставление" : "opposition",
"противопоставлять" : "oppose",
"противоречивый" : "contradictory",
"противоречие" : "contradiction",
"противоречить" : "contradict",
"противостоять" : "withstand, stand against",
"противотанковый" : "antitank...",
"противохимический" : "gas...",
"противоядие" : "antidote",
"протирать" : "rub, wipe",
"проткнуть" : "s. протыкать",
"проток" : "duct",
"протокол" : "minutes pl. record, a. protocol",
"протолкать" : "push, -ся force one's way",
"протолкнуть" : "push, -ся force one's way",
"протон" : "proton",
"протоплазма" : "protoplasm",
"протоптать" : "tread, famil. wear out #or down",
"проторенный" : "beaten  trodden",
"прототип" : "prototype",
"проточный" : "flowing running",
"протрезвиться" : "sober",
"протрезвляться" : "sober",
"протрубить" : "blow",
"протыкать" : "pierce",
"протягивать" : "stretch  extend hold out, pass, drawl, popul. turn up",
"протяжение" : "extent stretch, course",
"протяженность" : "extent",
"протяжный" : "drawling lingering",
"протянуть" : "stretch  extend hold out, pass, drawl, popul. turn up",
"проучить" : "pf. teach a lesson",
"профессиональный" : "professional, trade",
"профессия" : "profession  calling trade",
"профессор" : "professor",
"профессура" : "professorship, professorate",
"профилактический" : "prophylactic",
"профиль" : "profile",
"проформа" : "formality",
"профсоюз" : "trade union",
"профсоюзный" : "trade union",
"прохаживаться" : "walk stroll, famil. pass, mock",
"прохватить" : "pierce, blow up",
"прохватывать" : "pierce, blow up",
"прохвост" : "scoundrel",
"прохлада" : "cool",
"прохладительный" : "refreshing cooling",
"прохладный" : "cool  fresh",
"прохлаждаться" : "dally",
"проход" : "passage pass, anat. duct",
"проходимец" : "impostor villain",
"проходимость" : "passableness, maneuverability",
"проходить" : "pass go, take a ... course be, spread",
"проходить красной нитью" : "stand out",
"проходной" : "through passage",
"прохождение" : "passing #or going",
"прохожий" : "passer-by, traveller",
"процветать" : "prosper thrive",
"процветающий" : "bonanza, flourishing, prosperous",
"процедить" : "filter",
"процедура" : "procedure",
"процедурный" : "procedural",
"процеживать" : "filter",
"процент" : "percent, interest",
"процесс" : "process, jur. trial",
"процессия" : "procession",
"процитировать" : "quote",
"прочесть" : "s. прочитывать",
"прочесывать" : "scour",
"прочий" : "other, & a. su. the rest; See also: и прочее, между прочим",
"прочистить" : "s. прочищать",
"прочитать" : "read, recite",
"прочитать прочесть" : "read recite, give  deliver lecture, teach",
"прочитывать" : "read, recite",
"прочить" : "designate",
"прочищать" : "clean",
"прочность" : "durability",
"прочный" : "firm solid strong, lasting",
"прочтение" : "reading perusal",
"прочь" : "away off, cf. долой, я не ~  famil. I wouldn't mind ...ing",
"прошедший" : "past  gr. last",
"прошение" : "petition application",
"прошептать" : "whisper",
"прошествие" : "s. истечение",
"прошипеть" : "hiss, spit, whiz",
"прошлогодний" : "last year's",
"прошлое" : "antecedents",
"прошлый" : "past  last",
"прошмыгнуть" : "pf. slip whisk",
"проштудировать" : "study",
"прощай" : "farewell! goodby! adieu!",
"прощальный" : "farewell, parting, valedictory",
"прощание" : "adieu, goodbye, valediction",
"прощать" : "absolve, forgave, forgive, forgiven, remit",
"прощение" : "absolution, amnesty, forgiveness, remission",
"проэкзаменовать" : "examine",
"проявитель" : "phot. developer",
"проявить" : "s. проявлять",
"прояснить" : "clarify",
"пруд" : "pond",
"прутик" : "twig",
"прыгать" : "cavort, sprang",
"прыжок" : "capriole, frisk, gambol, hop, jump, leap, pounce",
"прыщ" : "pimple",
"прыщик" : "pimple",
"прядильный" : "spinning",
"прядильщик" : "spinner",
"прядильщица" : "spinner",
"прядь" : "lock tress strand",
"пряжа" : "yarn",
"пряжка" : "buckle",
"прялка" : "spinning wheel",
"прямая кишка" : "rectum",
"прямизна" : "straightness",
"прямо" : "directly, endlong, spang",
"прямодушие" : "s. прямота",
"прямодушный" : "fig.",
"прямой" : "straight, direct, rail. through..., math. right, fig. straight downright outspoken frank",
"прямолинейный" : "rectilinear, s. прямой fig.",
"прямота" : "straightforwardness frankness",
"прямоугольник" : "rectangle",
"прямоугольный" : "rectangular",
"пряник" : "gingerbread",
"пряность" : "spice pl. spicery, spiciness",
"пряный" : "spicy piquant",
"прясть" : "spin",
"прятать" : "hide  conceal",
"прятки" : "hide-and-seek",
"пряха" : "spinner",
"псалом" : "psalm",
"псаломщик" : "s. дьяк",
"псалтерион" : "psaltery",
"псалтырь" : "Psalter",
"псарня" : "kennel",
"псевдоним" : "pseudonym",
"психиатор" : "psychiatrist",
"психиатр" : "psychiatrist",
"психиатрия" : "psychiatry",
"психика" : "mind psyche, mentality",
"психический" : "mental psychic",
"психоанализ" : "psychoanalysis",
"психолог" : "psychologist",
"психология" : "psychology",
"психометрия" : "psychometry",
"психопат" : "psychopath",
"психопатический" : "psychopathic",
"психосоматический" : "psychosomatic",
"психотерапия" : "psychotherapy",
"психотический" : "psychotic",
"птенец" : "nestling",
"птеродактиль" : "pterodactyl",
"птица" : "bird; See also: домашняя птица",
"птицеводство" : "aviculture, poultry",
"птичий" : "bird, poultry...; See also: вид с птичьего полета",
"птичка" : "birdie",
"птичник" : "aviary",
"птолемеев" : "ptolemaic",
"публика" : "audience, public",
"публикация" : "publication, advertisement",
"публиковать" : "publish",
"публицист" : "publicist",
"публичная женщина" : "prostitute",
"публичность" : "publicity",
"публичный" : "public"
};
