var dicctr_92 = {
"устои" : "foundations",
"устойчивость" : "stability",
"устойчивый" : "stable",
"устоять" : "keep one's balance, hold one's ground, resist",
"устраивать" : "arrange, organize set up, furnish, construct, make, provide, famil. suit",
"устраиваться" : "be settled, settle, get a job",
"устранение" : "removal, elimination",
"устранить" : "remove, eliminate",
"устранять" : "remove, eliminate",
"устрашать" : "s. страшить",
"устрица" : "oyster",
"устроить" : "arrange, organize set up, furnish, construct, make, provide, famil. suit",
"устройство" : "arrangement, establishment, equipment, installation, organization, system, mechanism",
"уступ" : "ledge, projection, step, terrace",
"уступать" : "cede let have, yield, be inferior to, sell, abate; See also: уступать дорогу",
"уступать дорогу" : "let pers. pass give way",
"уступительный" : "gr. concessive",
"уступить" : "cede let have, yield, be inferior to, sell, abate; See also: уступать дорогу",
"уступка" : "concession, cession, commerc. abatement reduction",
"уступчивый" : "compliant pliant",
"устыдить" : "ashame",
"устыжать" : "ashame",
"устье" : "mouth",
"усугубить" : "increase redouble",
"усугублять" : "increase redouble",
"усы" : "s. ус",
"усылать" : "send",
"усыновить" : "adopt",
"усыновлять" : "adopt",
"усыпать" : "strew",
"усыпительный" : "soporific, drowsy",
"усыпить" : "lull, med. narcotize",
"усыплять" : "lull, med. narcotize",
"утаивать" : "conceal hide, embezzle",
"утаить" : "conceal hide, embezzle",
"утайка" : "без утайки",
"утаптывать" : "tread #or trample",
"утаскивать" : "carry drag #or take, famil. pilfer",
"утащить" : "carry drag #or take, famil. pilfer",
"утварь" : "implements utensils pl.",
"утвердительный" : "affirmative",
"утвердить" : "confirm, consolidate, impf. affirm assert maintain",
"утверждать" : "confirm, consolidate, impf. affirm assert maintain",
"утверждение" : "confirmation, affirmation assertion, consolidation",
"утекать" : "flow, famil. escape",
"утенок" : "duckling",
"утереть" : "s. утирать",
"утерпеть" : "pf.: не утерпел чтобы не, could not help ...ing",
"утес" : "cliff rock",
"утечка" : "leakage escape",
"утечь" : "flow, famil. escape",
"утешать" : "console comfort",
"утешаться" : "a. take comfort",
"утешение" : "comfort consolation",
"утешительный" : "comforting consolatory",
"утешить" : "console comfort",
"утешиться" : "a. take comfort",
"утилитарный" : "utilitarian",
"утиль" : "scrap",
"утильсырье" : "scrap",
"утирать" : "wipe",
"утихать" : "subside abate, cease, calm down",
"утихнуть" : "subside abate, cease, calm down",
"утка" : "duck, canard",
"уткнуть" : "pf. thrust, hide, put, be engrossed",
"утконос" : "duckbill, platypus",
"утолщение" : "thickening",
"утолять" : "quench, appease, allay still",
"утомительный" : "wearisome tiresome",
"утомить" : "s. утомлять",
"утомление" : "distress, fatigue",
"утомленный" : "weary",
"утомлять" : "irk, wear down",
"утонченность" : "nicety",
"утопический" : "utopian",
"утопия" : "never-never, utopia",
"утопленник" : "bloat",
"утопленный" : "sunk",
"утраивать" : "triplicate",
"утрамбовать" : "ram",
"утрата" : "loss",
"утратить" : "lose",
"утрачивать" : "lose",
"утренний" : "morning",
"утренник" : "matinee, morning frost",
"утро" : "morning, ... утра a. ... a.m.",
"утроба" : "womb",
"утробный" : "fetal, uterine",
"утроить" : "treble, -ся",
"утрудить" : "trouble bother",
"утруждать" : "trouble bother",
"утюг" : "iron",
"утюжить" : "iron, stroke",
"уха" : "fish soup",
"ухаб" : "hole",
"ухабистый" : "bumpy",
"ухаживать" : "nurse look after, court  woo",
"ухарский" : "dashing",
"ухать" : "boom",
"ухватить" : "seize grasp",
"ухватиться" : "snatch, cling to",
"ухватывать" : "seize grasp",
"ухватываться" : "snatch, cling to",
"ухитриться" : "contrive manage",
"ухитряться" : "contrive manage",
"ухищрение" : "shift",
"ухищряться" : "shift",
"ухмыльнуться" : "grin smile",
"ухмыляться" : "grin smile",
"ухнуть" : "boom",
"ухо" : "ear; See also: по уши, пропускать мимо ушей, держать ухо востро",
"уход" : "departure, care tendance, nursing",
"уходить" : "leave  depart  go, pass, escape, evade, resign, retire, be lost, fail, take, sink, plunge, famil. be spent",
"ухудшать" : "deteriorate",
"ухудшаться" : "deteriorate",
"ухудшение" : "deterioration, change for the worse",
"ухудшить" : "deteriorate",
"уцелеть" : "pf. escape, be spared",
"уцепиться" : "s. ухватиться",
"участвовать" : "participate take part",
"участвующий" : "s. участник",
"участие" : "participation, interest  sympathy",
"участить" : "s. учащать",
"участник" : "partaker, participant",
"участок" : "zone",
"учащийся" : "scholar",
"учебник" : "textbook",
"учебный" : "sparring",
"учение" : "doctrine, learning",
"ученик" : "apprentice",
"ученость" : "learning",
"ученый" : "learned, su. scholar",
"учесть" : "s. учитывать",
"учет" : "calculation, registration, inventory, discount, list, fig. consideration regard; See also: вести учет, взять на учет",
"учетверенный" : "quadruple",
"училище" : "school",
"учинять" : "s. чинить",
"учитель" : "teacher instructor",
"учительница" : "teacher instructor",
"учительский" : "teachers",
"учитывать" : "take into account consider, calculate, register, commerc. take late, stock, discount",
"учить" : "научить обучить выучить teach  instruct, milit. drill, train, выучить learn study",
"учиться" : "learn",
"учредитель" : "founder",
"учредительный" : "constituent",
"учредить" : "found constitute, establish introduce",
"учреждать" : "found constitute, establish introduce",
"учреждение" : "foundation constitution, institution, institute office",
"учтивость" : "courtesy",
"учтивый" : "polite, obliging",
"ушат" : "tub bucket",
"ушедший" : "gone",
"ушиб" : "bruise, injury",
"ушибать" : "hurt bruise",
"ушибить" : "hurt bruise",
"ушко" : "eye",
"ушной" : "ear...",
"ущелье" : "gorge ravine",
"ущемить" : "pinch jam, fig. restrain, famil. wound impair",
"ущемлять" : "pinch jam, fig. restrain, famil. wound impair",
"ущерб" : "damage, wane",
"ущипнуть" : "s. щипать",
"уэльс" : "Wales",
"уют" : "coziness",
"уютный" : "snug cozy comfortable",
"уязвимый" : "vulnerable",
"уязвить" : "wound sting, fig. hurt",
"уязвлять" : "wound sting, fig. hurt",
"уяснить" : "comprehend, make clear clear up",
"уяснять" : "comprehend, make clear clear up",
"фа" : "fa",
"фабзавком" : "s. завком",
"фабрика" : "factory, mill",
"фабрикант" : "manufacturer",
"фабрикат" : "product",
"фабричный" : "factory, trade",
"фабула" : "plot",
"фагоцит" : "phagocyte",
"фаза" : "phase",
"фазан" : "pheasant",
"фазис" : "phase",
"факел" : "torch",
"факт" : "fact; See also: факт тот",
"факт тот" : "the matter is",
"фактический" : "actual real, a. in fact",
"фактор" : "factor",
"фактура" : "invoice",
"факультет" : "faculty",
"фальсифицированный" : "adulterate",
"фальсифицировать" : "pf. falsify forge, adulterate",
"фальшивить" : "sing out of tune play falsely, famil. cheat be false",
"фальшивка" : "forgery",
"фальшивомонетчик" : "forgery",
"фальшивый" : "false, forged counterfeit, base",
"фальшь" : "falseness, hypocrisy, deceit",
"фамилия" : "surname family name, как ваша фамилия? what is your name?",
"фамильярный" : "familiar",
"фанатизм" : "fanaticism",
"фанатик" : "zealot",
"фанатический" : "fanatical",
"фанатичный" : "fanatical",
"фанера" : "plywood, veneer",
"фанерный" : "plywood, veneer",
"фантазер" : "visionary",
"фантазировать" : "indulge in fancies dream",
"фантазия" : "imagination, fancy, invention fib, mus. fantasia, famil. whim freak",
"фантастический" : "fantastic",
"фантастичный" : "fantastic",
"фанфара" : "fanfare",
"фара" : "headlight",
"фарада" : "farad",
"фараон" : "faro, pharaoh",
"фарватер" : "waterway fairway, fig. track",
"фармакология" : "pharmacology",
"фармакопея" : "pharmacopeia, pharmacopoeia",
"фармацевт" : "pharmacist",
"фармацевтический" : "pharmaceutic, pharmaceutical",
"фарс" : "farce",
"фартук" : "apron",
"фарфор" : "china porcelain",
"фарфоровый" : "china porcelain",
"фарш" : "stuffing, forcemeat",
"фаршировать" : "stuff",
"фасад" : "facade, frontage",
"фасоль" : "string bean",
"фасон" : "cut style",
"фат" : "dandy fop dude",
"фатальный" : "fatal",
"фатоватый" : "foppish",
"фауна" : "fauna",
"фашизм" : "fascism",
"фашист" : "fascist",
"фашистский" : "fascist...",
"фаянс" : "faience",
"фаянсовый" : "faience",
"февраль" : "February",
"федеральный" : "federal",
"федеративная республика германии" : "Federal Republic of Germany",
"федеративный" : "federative federal",
"федор" : "Theodore",
"феерический" : "fairylike",
"фейерверк" : "firework",
"фельдмаршал" : "field marshal",
"фельдфебель" : "sergeant",
"фельдшер" : "medical assistant",
"фельетон" : "feuilleton",
"феминизм" : "feminism",
"феминист" : "feminist",
"фенол" : "phenol",
"феномен" : "phenomenon"
};
