var dicctr_23 = {
"завладевать" : "take possession #or hold of seize",
"завладеть" : "own possess, rule govern, master, manage; See also: владеть собой",
"завлекательный" : "enticing tempting",
"завлекать" : "lure entice tempt, involve, carry away",
"завлечь" : "lure entice tempt, involve, carry away",
"завод" : "plant, works",
"завод1" : "works factory plant, stud",
"завод2" : "winding mechanism, typ. edition",
"заводить" : "take bring lead, put, establish set up found, form contract, get procure acquire, start  begin, wind up",
"заводиться" : "appear, nest, get have",
"заводной" : "engin. starting, mechanical",
"заводский" : "works... factory..., stud...",
"заводской" : "works... factory..., stud...",
"заводь" : "backwater",
"завоевание" : "conquest, fig. achievement",
"завоеватель" : "conqueror",
"завоевать" : "conquer, win gain",
"завоевывать" : "conquer, win gain",
"завозить" : "take bring drive, leave famil. deliver",
"заволакивать" : "cover overcast, get cloudy",
"заволочь" : "cover overcast, get cloudy",
"завопить" : "cry out bawl, lament wail",
"заворачивать" : "turn, direct",
"заворковать" : "coo",
"заворотить" : "turn, direct",
"заворчать" : "grumble growl",
"завсегдатай" : "habitue'",
"завтра" : "tomorrow",
"завтрак" : "breakfast, lunch",
"завтракать" : "breakfast",
"завтрашний" : "tomorrow's",
"завтрашний день" : "tomorrow, fig. future",
"завывать" : "howl",
"завыть" : "howl",
"завязать" : "tie  bind fasten, fig. begin start, entangle knit",
"завязать1" : "sink in stick, fig. get stuck #or involved in",
"завязать2" : "s. завязывать",
"завязка" : "string tie, beginning starting point, entanglement plot",
"завязнуть" : "sink in stick",
"завязывать" : "tie  bind fasten, fig. begin start, entangle knit",
"завязь" : "ovary",
"завянуть" : "wither fade, droop flag",
"загадать" : "s. загадывать",
"загадить" : "s. загаживать",
"загадка" : "riddle enigma",
"загадочный" : "enigmatic, mysterious",
"загадывать" : "propose, try to find out, famil. fix upon, plan",
"загаживать" : "soil befoul",
"загалдеть" : "clamor din",
"загар" : "sunburn tan",
"загасить" : "extinguish put #or blow out, slake",
"загвоздка" : "hitch trouble",
"загиб" : "bend, dog-ear, pol. deviation",
"загибать" : "bend fold  turn",
"загипнотизировать" : "hypnotize",
"заглавие" : "title",
"заглавная буква" : "capital letter",
"заглавный" : "title...; See also: заглавная буква",
"загладить" : "smooth, press iron, fig. make up for expiate",
"заглаживать" : "smooth, press iron, fig. make up for expiate",
"заглатывать" : "gulp",
"заглохнуть" : "s. глохнуть",
"заглохший" : "deserted desolate",
"заглушать" : "s. глушить",
"заглушить" : "s. глушить",
"заглядеться" : "gaze gape #or stare  feast one's eyes #or gloat",
"заглядывать" : "glance, peep, look, have a look, famil. drop in #or call",
"заглядываться" : "gaze gape #or stare  feast one's eyes #or gloat",
"заглянуть" : "glance, peep, look, have a look, famil. drop in #or call",
"загнать" : "s. загонять",
"загнуть" : "bend fold  turn",
"заговаривать" : "begin start to talk #or speak, tire with one's talk, exorcise, -ся famil. drivel talk nonsense, be confused, talk long much",
"заговор" : "conspiracy plot, exorcism, составля'ть заговор conspire plot",
"заговорить" : "begin start to talk #or speak, tire with one's talk, exorcise, -ся famil. drivel talk nonsense, be confused, talk long much",
"заговорщик" : "conspirator",
"заговорщический" : "conspiratorial",
"загоготать" : "cackle, popul. roar",
"заголовок" : "heading title",
"загон" : "enclosure, быть в загоне famil. suffer neglect",
"загонять" : "drive, exhaust fatigue",
"загораживать" : "enclose shut in, block  bar, -ся fence protect",
"загорать" : "become sunburnt, -ся catch #or take fire light up kindle flash, blush blaze up, fig. inflame, break out",
"загорелый" : "sunburnt",
"загореть" : "become sunburnt, -ся catch #or take fire light up kindle flash, blush blaze up, fig. inflame, break out",
"загорланить" : "bawl",
"загородить" : "enclose shut in, block  bar, -ся fence protect",
"загородка" : "fence enclosure, partition",
"загородный" : "country, out-of-town",
"заготавливать" : "prepare, store up, lay in",
"заготовить" : "prepare, store up, lay in",
"заготовка" : "storage laying in",
"заготовление" : "storage laying in",
"заготовлять" : "prepare, store up, lay in",
"заградительный" : "milit. curtain  barrage",
"заградить" : "block  bar",
"заграждать" : "block  bar",
"заграждение" : "block obstruction, проволочное заграждение wire entanglement",
"заграничный" : "foreign, ... abroad",
"загребать" : "s. грести",
"загреметь" : "thunder peal, rattle clank tinkle, clatter, fig. ring, be famous",
"загрести" : "s. грести",
"загримировать" : "make up",
"загробная жизнь" : "the beyond",
"загробный" : "sepulchral",
"загробный мир" : "the other world",
"загромождать" : "block  cumber crowd, overload",
"загромождение" : "blocking, overloading",
"загромоздить" : "block  cumber crowd, overload",
"загрохотать" : "rumble, popul. roar",
"загрубелый" : "callous coarse",
"загрубеть" : "harden become callous",
"загружать" : "load, engin. charge, famil. busy assign work to, be occupied by work",
"загрузить" : "load embark",
"загрузка" : "load charge",
"загрызать" : "bite to death kill",
"загрызть" : "bite to death kill",
"загрязнение" : "soiling, pollution, infection",
"загрязнить" : "soil, -ся get dirty",
"загрязнять" : "soil pollute  infect",
"загс" : ", registrar's office",
"загудеть" : "buzz, honk, hoot whistle",
"загустеть" : "thicken",
"зад" : "back rear #or hinder part, posterior rump, famil. things already known #or learned; See also: задом наперед",
"задабривать" : "insinuate o.s.  gain upon",
"задавать" : "set assign, give  famil. dress, ask, -ся целью, take it into one's head set one's mind on doing s.th., famil. happen to be",
"задавить" : "crush, run over knock down, fig. suppress, popul. strangle kill",
"задавливать" : "crush, run over knock down, fig. suppress, popul. strangle kill",
"задание" : "assignment task, mission; See also: домашнее задание",
"задаток" : "earnest money, deposit, pl. rudiments",
"задать" : "set assign, give  famil. dress, ask, -ся целью, take it into one's head set one's mind on doing s.th., famil. happen to be",
"задать встрепку" : "popul. bowl out blow up",
"задача" : "problem, task, object aim end",
"задачник" : "book of problems",
"задвигать" : "push, shut, draw, slide",
"задвижка" : "bolt",
"задвижной" : "sliding, sash",
"задвинуть" : "push, shut, draw, slide",
"задворки" : "backyards",
"задевать" : "be caught  brush against touch, excite, hurt wound, med. affect",
"заделать" : "stop up choke, wall up",
"заделывать" : "stop up choke, wall up",
"задергать" : "pf. overdrive, famil. harass",
"задергивать" : "draw, cover",
"задеревенеть" : "stiffen, grow numb",
"задержание" : "arrest",
"задержанный" : "delayed, detainee",
"задержаный" : "handicapped",
"задержать" : "detain hold back #or up stop, delay check, arrest, slow down, -ся stay, be delayed, linger, stop, be late",
"задерживать" : "detain hold back #or up stop, delay check, arrest, slow down, -ся stay, be delayed, linger, stop, be late",
"задержка" : "delay, trouble break",
"задернуть" : "draw, cover",
"задеть" : "be caught  brush against touch, excite, hurt wound, med. affect",
"задеть за больное место" : "touch on the raw",
"задира" : "bully, hector, teaser",
"задирать" : "lift #or pull, stretch, impf. provoke vex pick a quarrel; See also: задрать нос",
"задний" : "back hind, reverse",
"задний план" : "background",
"задник" : "backdrop",
"задобрить" : "insinuate o.s.  gain upon",
"задолго" : "long before",
"задолжать" : "pf. run into debt, owe",
"задолженность" : "debts pl. indebtedness",
"задом" : "backward, cf. зад",
"задом наперед" : "back to front",
"задор" : "fervor, quick temper, provocative tone #or behavior",
"задорный" : "fervent, provoking teasing, frolicsome",
"задохнуться" : "gasp pant, choke",
"задрапировать" : "drape",
"задрать" : "lift #or pull, stretch, impf. provoke vex pick a quarrel; See also: задрать нос",
"задрать нос" : "be haughty turn up one's nose",
"задумчивый" : "broody, pensive, reflective, thoughtful",
"задумывать" : "conceive",
"задыхаться" : "choke, gasp, suffocate",
"заем" : "loan",
"заехать" : "call on  drive, go #or come, pick up fetch, get",
"зажарить" : "roast, fry, famil. burn",
"зажать" : "s. зажимать",
"зажечь" : "s. зажигать",
"заживать" : "heal, close skin, pf. begin to live",
"заживо" : "alive",
"зажигалка" : "lighter",
"зажигание" : "lighting, ignition",
"зажигательный" : "incendiary",
"зажигать" : "light kindle, strike, turn on, -ся light  kindle",
"зажим" : "engin. clamp, fig. suppression",
"зажимать" : "press squeeze, clutch, famil. press, stop  hold  close",
"зажиточность" : "prosperity",
"зажиточный" : "prosperous",
"зажить" : "heal, close skin, pf. begin to live",
"зажмурить" : "screw up #or contract",
"зазвенеть" : "ring jingle clink, у меня звенит в ушах my ears ring",
"заздравный" : "health",
"зазеваться" : "gape, be heedless absent",
"зазеленеть" : "grow turn #or be green, impf. appear #or show green",
"заземление" : "Brt. earth",
"заземлить" : "Brt. earth",
"заземлять" : "Brt. earth",
"зазимовать" : "winter, hibernate",
"зазнаваться" : "be presumptuous put on airs",
"зазнаться" : "be presumptuous put on airs",
"зазорный" : "popul. shameful scandalous",
"зазрение" : "без зазрения",
"зазубринка" : "indent",
"заикание" : "stutter, stuttering",
"заикаться" : "stammer",
"заимствование" : "borrowing taking, loan word",
"заимствовать" : "a. позаимствовать borrow take",
"заиндевелый" : "frosty",
"заинтересовать" : "interest rouse a pers.'s interest, я заинтересован I am interested",
"заинтересоваться" : "be interested in, я заинтересован I am interested",
"заинтересовывать" : "interest rouse a pers.'s interest, я заинтересован I am interested",
"заинтересовываться" : "be interested in, я заинтересован I am interested",
"заинтриговать" : "intrigue",
"заискивать" : "ingratiate o.s.",
"зайти" : "s. заходить",
"зайчик" : "dim. of заяц, famil. speck",
"закабалить" : "enslave",
"закабалять" : "enslave",
"закавказский" : "Transcaucasian",
"закадычный" : "bosom",
"заказ" : "order; See also: дать заказ, заказать, на заказ, заказной",
"заказать" : "s. заказывать",
"заказное" : "registered",
"заказной" : "made to order",
"заказной лес" : "reserve",
"заказчик" : "customer",
"заказывать" : "order, obsol. forbid",
"закал" : "engin. tempering, fig. hardening, endurance hardiness, breed kind",
"закаленный" : "tempered, fig. hardened tried experienced",
"закалить" : "engin. temper, fig. harden",
"закалка" : "engin. tempering, fig. hardening, endurance hardiness, breed kind",
"закалывать" : "kill slaughter, stab, pin, у меня закололо в боку I have a stitch in the side",
"закалять" : "engin. temper, fig. harden",
"заканчивать" : "finish conclude",
"закапывать" : "bury, fill up",
"закат" : "sunset, fig. decline, end",
"закатывать" : "закатать roll up, закатить roll, turn up",
"закатываться" : "roll, set, fig. end, famil. burst",
"заквасить" : "sour",
"закваска" : "ferment, leaven, famil. breed",
"заквашивать" : "sour",
"закидывать" : "закидать famil. fill up cover, fig. ply assail pelt, закинуть, throw (in[to] on over behind В, a. out [#net] back [#head]), fling cast",
"закинуть удочку" : "fig. drop a hint",
"закипание" : "simmer",
"закипать" : "begin to boil, cf. кипеть",
"закипеть" : "begin to boil, cf. кипеть",
"закисать" : "turn sour",
"закиснуть" : "turn sour",
"заклад" : "obsol. = залог, a. биться",
"закладка" : "laying, walling, harnessing putting to, bookmark"
};
