var dicctr_80 = {
"сечь2" : "whip flog",
"сечься" : "split, ravel",
"сеялка" : "seeder",
"сеянец" : "seedling",
"сеять" : "sow",
"сжалиться" : "pf. have #or take pity  pity",
"сжарить" : "roast, fry, famil. burn",
"сжатие" : "pressure, compression",
"сжатый" : "compact concise terse",
"сжать" : "& пожать press squeeze, shake, pinch, fig. oppress, -ся shrink, crowd, snuggle, famil. vacillate",
"сжечь" : "burn, torment",
"сжигать" : "cf. жечь",
"сжижение" : "liquefaction",
"сжимать" : "press squeeze, clench",
"сжиматься" : "contract, shrink, become clenched",
"сжимающийся" : "compressible",
"сжульничать" : "cheat trick",
"сзади" : "behind",
"сзывать" : "s. созывать",
"сиамский" : "siamese",
"сибирский" : "Siberian",
"сибирский кедр" : "cembra pine",
"сибирь" : "Siberia",
"сибиряк" : "Siberian",
"сибирячка" : "Siberian",
"сивый" : "gray",
"сигара" : "cigar",
"сигнальный" : "signal",
"сиденье" : "pew, seat",
"сидеть" : "sat, sit",
"сидячий" : "sedentary, sitting",
"сие" : "this, cf. пора; See also: сим, при сем, сего года",
"сиеста" : "siesta",
"сизый" : "gray Brt. grey, dove-colored",
"сии" : "this, cf. пора; See also: сим, при сем, сего года",
"сил нет" : "famil. awfully",
"сила" : "strength, force, power might, vigor, intensity, efficacy, energy, volume; See also: своими силами, в силу, не в силах, не по силам, сил нет, изо всех сил",
"сила воли" : "will power, liberty freedom",
"силач" : "athlete",
"силикат" : "silicate",
"силиться" : "try endeavor",
"силлогизм" : "syllogism",
"силовой" : "power...",
"силок" : "snare noose",
"силос" : "ensilage, silage, silo",
"силуэт" : "silhouette",
"сильно" : "a. very much, hard",
"сильнодействующий" : "drastic",
"сильный" : "strong, powerful mighty, intense, heavy, bad, great, el. power...",
"сим" : "herewith hereby",
"симбиоз" : "symbiosis",
"символ" : "symbol",
"символический" : "symbolic",
"символичный" : "symbolic",
"симметричный" : "symmetrical",
"симметрия" : "symmetry",
"симпатизировать" : "sympathize",
"симпатичный" : "nice sympathetic, он мне симпатичен I like him",
"симпатия" : "sympathy",
"симптом" : "symptom",
"симптоматический" : "symptomatic",
"симулировать" : "pf. feign sham, malinger",
"симулянт" : "simulator",
"симулянтка" : "simulator",
"симфонический" : "symphonic symphony...",
"симфония" : "symphony",
"синагога" : "synagogue",
"синдикат" : "syndicate",
"синдром" : "syndrome",
"синева" : "blue",
"синеватый" : "bluish",
"синеть" : "turn blue",
"синий" : "blue",
"синильный" : "hydrocyanic prussic",
"синить" : "blue",
"синица" : "titmouse",
"синод" : "synod",
"синоним" : "synonym",
"синонимика" : "synonymy",
"синонимический" : "synonymous",
"синоптический" : "synoptic",
"синтаксис" : "syntax",
"синтаксический" : "syntactic",
"синтез" : "synthesis",
"синтетический" : "synthetic",
"синус" : "ogee, sinus",
"синусоидальный" : "sine",
"синхронизировать" : "pf. synchronize",
"синхронизм" : "synchronism",
"синь" : "blue",
"синька" : "blue",
"синяк" : "livid spot bruise",
"сион" : "zion",
"сионизм" : "zionism",
"сипай" : "sepoy",
"сиплый" : "hoarse",
"сирена" : "siren",
"сиреневый" : "lilac",
"сирень" : "lilac",
"сироп" : "syrup",
"сирота" : "orphan",
"сиротский" : "orphan",
"система" : "system",
"систематический" : "systematic",
"систематичный" : "systematic",
"ситец" : "chintz cotton",
"сито" : "sieve",
"сицилия" : "Sicily",
"сия" : "this, cf. пора; See also: сим, при сем, сего года",
"сияние" : "radiance, light shine, halo",
"сиять" : "shine beam, radiate",
"сказание" : "legend, saga, story",
"сказано на мой счет" : "aimed at me",
"сказать" : "speak #or talk, say tell; See also: говорят, говорится, говорить по-русски, иначе говоря, не говоря уже о, по правде говоря, по совести говоря, что вы говорите{!}, что ни говори, как ни говори, что и говорить, и не говори{!}",
"сказка" : "fairy tale, tale, fib",
"сказочный" : "fabulous fantastic, fairy ...",
"сказуемое" : "gr. predicate",
"скакать" : "skip hop leap, gallop, race",
"скаковой" : "race..., racing",
"скала" : "rock cliff crag",
"скалистый" : "rocky cliffy",
"скалить" : "show bare, impf. grin, jeer",
"скалка" : "rolling pin",
"скалывать" : "pin together, split, prick",
"скалькировать" : "trace",
"скалькулировать" : "commerc. calculate",
"скалярный" : "scalar",
"скамеечка" : "footstool, dim. #of скамейка",
"скамейка" : "bench; See also: скамья подсудимых",
"скамья" : "bench; See also: скамья подсудимых",
"скамья подсудимых" : "dock",
"скандал" : "scandal, row, famil. shame",
"скандалить" : "row",
"скандальный" : "scandalous, famil. wretched",
"скандий" : "scandium",
"скандинавский" : "Scandinavian",
"скапливать" : "s. скоплять",
"скатерть" : "tablecloth",
"скатываться" : "slither",
"скачки" : "horserace",
"скачок" : "s. прыжок",
"скашивать" : "mow off #or down, slope, bevel",
"скважина" : "chink crack, pore, engin. hole; See also: замочная скважина",
"сквер" : "square park",
"сквернословить" : "talk smut",
"скверный" : "nasty foul",
"сквозит" : "there is a draft Brt. draught",
"сквозить" : "shine through appear",
"сквозной" : "through..., thorough..., transparent",
"сквозняк" : "draft Brt. draught",
"сквозь" : "through",
"сквозь зубы" : "through clenched teeth, indistinctly",
"сквозь огонь и воду" : "through thick & thin",
"скворец" : "starling",
"скворечница" : "nestling box",
"скелет" : "skeleton",
"скелетный" : "skeletal",
"скептик" : "skeptic",
"скептический" : "skeptic",
"скидка" : "discount rebate",
"скидывать" : "throw off #or down, take #or put off, discount reduce",
"скинуть" : "throw off #or down, take #or put off, discount reduce",
"скипетр" : "scepter Brt. -tre",
"скипидар" : "turpentine",
"скирд" : "haystack",
"скисать" : "turn sour",
"скиснуть" : "turn sour, fig. get rusty",
"скиталец" : "wanderer",
"скитаться" : "wander rove",
"склад" : "warehouse storehouse, milit. depot, constitution disposition turn, breed, way, famil. harmony, sense",
"складка" : "pleat fold, crease, wrinkle",
"складки" : "pleating",
"складной" : "fold collapsible, camp...., falt",
"складный" : "harmonious, coherent, fluent smooth, popul. well-made, accommodating",
"складчина" : "в складчину",
"складывать" : "stow",
"склеенный" : "agglutinate",
"склеп" : "crypt vault",
"склероз" : "sclerosis",
"склеротический" : "sclerotic",
"склока" : "squabble",
"склон" : "slope",
"склонение" : "inclination, gr. declension, astr. declination",
"склонить" : "bend bow, fig. incline, drive at, obsol. cast down, меня клонит ко сну I am sleepy",
"склонность" : "inclination  disposition",
"склонный" : "inclined  disposed",
"склонять" : "склонить, bend incline, persuade, просклонять gr. decline",
"скоба" : "cramp",
"скобка" : "cramp, typ. bracket parenthesis",
"скоблить" : "scrape",
"скобяной" : "hard",
"сковать" : "s. сковывать",
"сковорода" : "frying pan",
"сковывать" : "forge, weld, fetter chain, bind, arrest",
"сколоть" : "pin together, split, prick",
"скольжение" : "glide, glissade, slide, slip, slipping",
"скользить" : "slide glide slip",
"скользкий" : "slippery",
"скользнуть" : "slide glide slip",
"сколько" : "how much many, ~ лет ~ зим famil.",
"сколько времени" : "how long?, what's the time?",
"скопа" : "osprey",
"скопление" : "agglomerate, agglomeration, conglomeration",
"скопляться" : "conglomerate",
"скорбный" : "doleful, sorrowful, woeful",
"скорее" : "rather",
"скорее всего" : "famil. most probably",
"скорлупа" : "shell",
"скорняк" : "furrier",
"скоро" : "a. soon",
"скороговорка" : "tongue twister, rapid speech sputter",
"скоромный" : "meat milk",
"скоропись" : "cursive",
"скоропостижный" : "sudden",
"скороспелый" : "early, precocious",
"скоростной" : "speed...",
"скорость" : "speed, rate, mot. gear; See also: груз большой скорости, груз малой скорости",
"скоротать" : "while away, beguile",
"скоротечный" : "transient, med. galloping",
"скорпион" : "scorpio, scorpion",
"скорчить" : "impers. writhe, convulse, famil. make, play pose put on airs set up for",
"скорый" : "quick fast rapid swift, speedy prompt, first, near, early; See also: скоро, скорее всего, на скорую руку",
"скосить" : "mow, a. покосить squint, twist  be wry, -ся покоситься, a. look askance",
"скот" : "cattle livestock",
"скотина" : "famil. cattle, popul. brute, dolt boor",
"скотный двор" : "cattle yard",
"скотобойня" : "slaughterhouse",
"скотоводство" : "cattle breeding",
"скотский" : "brutish bestial swinish",
"скребок" : "scraper",
"скрежет" : "gnash",
"скрежетать" : "gnash",
"скрепа" : "cramp clamp",
"скрепить" : "s. скреплять",
"скрепка" : "clip",
"скрепление" : "fastening",
"скреплять" : "fasten, tighten, corroborate, validate, countersign",
"скрепя сердце" : "reluctantly",
"скрести" : "scrape, scratch",
"скрестить" : "cross",
"скрещивание" : "crossing",
"скрещивать" : "cross",
"скривить" : "crook, twist; See also: кривить душой",
"скрип" : "creak, scratch",
"скрипач" : "violinist",
"скрипеть" : "creak, scratch, grit gnash",
"скрипка" : "violin",
"скрипнуть" : "creak, scratch, grit gnash",
"скрипучий" : "creaky",
"скроить" : "cut"
};
