var dicctr_25 = {
"западня" : "trap",
"запаздывать" : "be late  be tardy",
"запаивать" : "solder",
"запаковать" : "pack, wrap up",
"запаковывать" : "pack, wrap up",
"запал" : "mining fuse, touchhole, heaves, famil. fit passion",
"запальная свеча" : "el. spark plug",
"запальный" : "touch...",
"запальный шнур" : "match",
"запальчивый" : "quick-tempered irascible, provoking",
"запас" : "stock, supply reserve; See also: в запасе, про запас",
"запасать" : "provide o.s.",
"запасаться" : "provide o.s.",
"запасливый" : "provident",
"запасной" : "spare, reserve..., emergency... side...",
"запасный" : "spare, reserve..., emergency... side...",
"запасти" : "provide o.s.",
"запастись" : "provide o.s.",
"запасть" : "fall in sink, impress",
"запах" : "smell odor scent",
"запахивать" : "запахать plow #or turn up in, запахнуть lap  wrap up, famil. slam",
"запачкать" : "soil",
"запашка" : "tillage",
"запаять" : "solder",
"запевала" : "precentor leader",
"запевать" : "lead",
"запеканка" : "baked pudding, spiced brandy",
"запекать" : "bake, -ся clot coagulate, crack",
"запеленать" : "swaddle",
"запереть" : "s. запирать",
"запертый" : "locked, pent",
"запеть" : "start singing strike up",
"запечатать" : "s. запечатывать",
"запечатлевать" : "embody render impress  retain, mark seal",
"запечатлеть" : "embody render impress  retain, mark seal",
"запечатывать" : "seal, close glue up",
"запечь" : "bake, -ся clot coagulate, crack",
"запивать" : "wash down  drink #or take after thereupon, famil. take to drink",
"запинаться" : "stumble  falter, pause hesitate",
"запинка" : "без запинки",
"запираемый" : "lockup",
"запирательство" : "disavowal denial",
"запирать" : "lock, nav. blockade, -ся famil. deny disavow",
"записать" : "s. записывать",
"записка" : "note slip, letter, memorandum report, pl. notes memoirs reminiscences, transactions proceedings",
"записной" : "note..., famil. inveterate",
"записывать" : "write down note, record, enter enrol register, jur. transfer  deed, -ся enrol register matriculate, subscribe  book, make an appointment",
"запись" : "entry, enrolment, registration, record, subscription, jur. deed",
"запить" : "wash down  drink #or take after thereupon, famil. take to drink",
"запихать" : "push in, cram stuff",
"запихивать" : "push in, cram stuff",
"запихнуть" : "push in, cram stuff",
"запищать" : "peep squeak cheep",
"заплаканный" : "tearful in tears tear-stained",
"заплакать" : "pf. begin to cry",
"заплата" : "patch",
"заплатить" : "pay, settle",
"заплесневелый" : "moldy",
"заплесневеть" : "get moldy",
"заплести" : "braid plait",
"заплетать" : "braid plait",
"заплетаться" : "ноги заплетаются; See also: язык заплетается",
"запломбировать" : "fill stop",
"заплывать" : "swim  get, be covered #or closed, swell bloat puff up",
"заплыть" : "swim  get, be covered #or closed, swell bloat puff up",
"запнуться" : "stumble  falter, pause hesitate",
"заповедать" : "command",
"заповедник" : "reserve, nursery",
"заповедный" : "forbidden reserved, secret, dear, intimate inmost",
"заповедовать" : "command",
"заповедь" : "#Bibl. commandment",
"заподазривать" : "suspect",
"заподозривать" : "suspect",
"заподозрить" : "suspect",
"запоздалый" : "late tardy, out-of-date",
"запоздать" : "be late  be tardy",
"запой" : "hard drinking, пить запоем booze tipple be a hard drinker",
"заползать" : "creep",
"заползти" : "creep",
"заполненный" : "filled",
"заполнитель" : "filler",
"заполнить" : "fill, fill out",
"заполнять" : "fill, fill out",
"запоминать" : "remember keep in mind, memorize, -ся remember stick to one's memory",
"запомнить" : "remember keep in mind, memorize, -ся remember stick to one's memory",
"запонка" : "cuff link, collar button",
"запор" : "bar bolt, lock, med. constipation, на запоре bolted",
"запорашивать" : "powder #or cover",
"запорошить" : "powder #or cover",
"запотелый" : "moist sweaty",
"заправила" : "boss chief",
"заправить" : "put tuck, dress season, get ready, tank refuel",
"заправка" : "refueling, seasoning condiment",
"заправлять" : "put tuck, dress season, get ready, tank refuel",
"заправочная колонка" : "filling station",
"заправочная станция" : "filling station",
"заправочный" : "заправочная колонка; See also: заправочная станция",
"запрашивать" : "inquire",
"запрет" : "prohibition",
"запретительный" : "prohibitive, prohibitory",
"запретный" : "tabu",
"запрещать" : "forbad, forbade, forbid, prohibit, thumbs down",
"запрещение" : "ban, interdict, proscription",
"запрещенный" : "forbidden",
"запрокидывать" : "famil. throw back, popul. overturn",
"запрокинуть" : "famil. throw back, popul. overturn",
"запрос" : "inquiry, pl. demands requirements claims interests, famil. overcharge, commerc. цена без запроса fixed price",
"запросить" : "ask inquire, request, charge ask",
"запросто" : "plainly unceremoniously",
"запруда" : "dam",
"запрудить" : "dam up, famil. jam crowd",
"запруживать" : "dam up, famil. jam crowd",
"запрягать" : "harness, put to, yoke, get ready",
"запряжка" : "harness, team",
"запрятать" : "hide conceal, put, popul. confine",
"запрятывать" : "hide conceal, put, popul. confine",
"запрячь" : "harness, put to, yoke, get ready",
"запуганный" : "timid",
"запугать" : "intimidate",
"запугивать" : "intimidate",
"запуск" : "start",
"запускать" : "neglect, disregard, let grow, leave untilled, engin. start set going, fly, famil. fling hurl, put slip thrust drive",
"запустелый" : "desolate",
"запустеть" : "become empty #or deserted",
"запустить" : "neglect, disregard, let grow, leave untilled, engin. start set going, fly, famil. fling hurl, put slip thrust drive",
"запутанность" : "intricacy",
"запутанный" : "a. intricate",
"запутать" : "tangle, fig. confuse perplex, complicate, famil. entangle involve",
"запутывать" : "tangle, fig. confuse perplex, complicate, famil. entangle involve",
"запущенность" : "neglect",
"запущенный" : "deserted desolate, neglected uncared-for unkempt",
"запылать" : "blaze flare  flame, glow burn, rage",
"запылить" : "dust",
"запыхавшийся" : "breathless, puffed, winded",
"запыхаться" : "pant",
"запястье" : "wrist, obsol. bracelet",
"запятая" : "comma, famil. hitch fix",
"запятнать" : "imbrue",
"зарабатывать" : "earn, -ся o.s.",
"заработать" : "earn, -ся o.s.",
"заработная плата" : "wages pl., salary, pay",
"заработок" : "earnings pl., job; See also: на заработки",
"заражать" : "infect, -ся become infected  catch",
"заражение" : "infection; See also: заражение крови",
"заражение крови" : "blood poisoning",
"зараз" : "famil. at once, at the same time",
"зараза" : "infection, contagion, pest",
"заразительный" : "infectious",
"заразить" : "infect, -ся become infected  catch",
"заразный" : "infectious contagious, infected",
"заранее" : "beforehand in advance",
"зарастать" : "be overgrown",
"зарасти" : "be overgrown",
"зарево" : "blaze glow gleam",
"зарегистрировать" : "register, index",
"зарез" : "slaughter, popul. ruin; See also: до зарезу",
"зарекаться" : "forswear abjure",
"зарекомендовать" : "pf. recommend; See also: зарекомендовать себя",
"зарекомендовать себя" : "show o.s. prove",
"заречься" : "forswear abjure",
"заржаветь" : "rust",
"заржавленный" : "rusty",
"заржать" : "neigh",
"зарисовка" : "drawing sketch",
"зарница" : "sheet lightning",
"зародить" : "s. зарождать",
"зародыш" : "fetus, foetus",
"зародышевый" : "embryonal, foetal, germinal",
"зарождаться" : "germinate",
"зарождающийся" : "incipient",
"зарождение" : "genesis",
"заросли" : "spinney, thicket",
"заросший" : "ivied, overgrown, rank",
"зарубежный" : "foreign",
"зарубить" : "kill cut down, notch cut in, заруби на носу ! mark it well!",
"зарубка" : "incision notch",
"зарубцеваться" : "pf. cicatrize",
"заручаться" : "secure",
"заручиться" : "secure",
"зарывать" : "bury",
"зарыть" : "bury",
"заря" : "заря dawn; See also: вечерняя заря, на заре, от зари до зари, заря занимается",
"заря занимается" : "it dawns",
"заряд" : "charge, shot, shell cartridge, fig. store",
"зарядить" : "s. заряжать",
"зарядка" : "milit. loading, el. charge -ging, #sport: gymnastics pl. bodily exercise",
"зарядный" : "charge... loading",
"зарядный ящик" : "ammunition wagon",
"заряжать" : "phot. load, el. charge, fig. inspire imbue, famil. reiterate #or go on & on",
"засада" : "ambush; See also: попасть в засаду",
"засадить" : "plant, famil. confine, compel to",
"засаживать" : "plant, famil. confine, compel to",
"засаживаться" : "sit down, settle retire stay, hide lie in ambush, set #or begin to bury o.s. in",
"засаливать" : "засалить grease smear, засолить salt, corn",
"засаривать" : "litter, soil stop  obstruct, med. constipate, be weedy, засорять глаз have s.th. in one's eye",
"засасывать" : "suck in, engulf swallow up",
"засахаренный" : "candied sugared",
"засветить" : "pf. light",
"заседание" : "session, sitting",
"заселить" : "people populate, occupy inhabit",
"заселять" : "people populate, occupy inhabit",
"засесть" : "sit down, settle retire stay, hide lie in ambush, set #or begin to bury o.s. in",
"засечь" : "notch mark, stop, flog to death",
"засеять" : "sow",
"засидеть" : "flyblow, -ся sit stay #or live long, sit up late",
"засиживать" : "flyblow, -ся sit stay #or live long, sit up late",
"заскорузлый" : "hardened",
"заслон" : "backstop",
"заслонить" : "protect, screen, shut off take away, repress oust",
"заслонка" : "door screen trap",
"заслонять" : "protect, screen, shut off take away, repress oust",
"заслуга" : "merit desert, он получил по заслугам served him right",
"заслуженный" : "merited deserved just, meritorious worthy, honored",
"заслуживать" : "merit deserve, famil. earn",
"заслуживающий" : "deserving",
"заслужить" : "merit deserve, famil. earn",
"заслушать" : "hear, -ся listen with delight",
"заслушивать" : "hear, -ся listen with delight",
"засматриваться" : "feast one's eyes #or gloat, look with delight",
"засмеяться" : "laugh, mock, deride, famil. joke",
"засмолить" : "pitch tar",
"засмотреться" : "feast one's eyes #or gloat, look with delight",
"заснуть" : "s. засыпать",
"засов" : "bar bolt",
"засовывать" : "put slip tuck, famil. mislay",
"засолить" : "s. засаливать",
"засорение" : "obstruction, med. constipation",
"засорить" : "litter, soil stop  obstruct, med. constipate, be weedy, засорять глаз have s.th. in one's eye",
"засорять" : "litter, soil stop  obstruct, med. constipate, be weedy, засорять глаз have s.th. in one's eye",
"засосать" : "suck in, engulf swallow up",
"засохнуть" : "s. засыхать",
"засохший" : "dry dried up, bot. dead",
"заспанный" : "sleepy",
"застава" : "hist. gate turnpike, milit. frontier post, outpost",
"заставать" : "find meet with, surprise, take ...",
"заставить" : "compel force make",
"заставить ждать" : "keep waiting",
"заставить замолчать" : "silence, block, fill",
"заставлять" : "compel force make",
"застаиваться" : "stagnate",
"застарелый" : "inveterate chronic",
"застать" : "find meet with, surprise, take ...",
"застегивать" : "button, buckle clasp hook",
"застегнуть" : "button, buckle clasp hook",
"застежка" : "clasp",
"застеклить" : "glaze",
"застеклять" : "glaze",
"застенок" : "torture chamber",
"застенчивый" : "shy timid",
"застигать" : "surprise catch, take..."
};
