var dicctr_66 = {
"почтительность" : "respect",
"почтительный" : "respectful, respectable",
"почтить" : "s. почитать",
"почтмейстер" : "postmaster",
"почтовая марка" : "stamp",
"почтовый" : "post mail..., post-office, note; See also: почтовый ящик, почтовая марка",
"почтовый ящик" : "mail box, Post Office Box",
"почувствовать" : "feel",
"почуять" : "scent feel",
"пошабашить" : "knock off",
"пошарить" : "rummage",
"пошевелить" : "stir move, turn",
"пошевельнуть" : "budge",
"пошел" : "go!",
"пошлина" : "toll",
"пошлый" : "banal, low-minded",
"поштучно" : "apiece",
"поэзия" : "poetry",
"поэт" : "poet",
"поэтический" : "poetic",
"поэтому" : "therefore",
"появиться" : "s. появляться",
"появление" : "appearance",
"появляться" : "appear, emerge",
"пояс" : "belt, zone",
"пояснение" : "explanation",
"пояснительный" : "explanatory",
"пояснить" : "s. пояснять",
"поясница" : "small of the back",
"поясничный" : "lumbar",
"поясной" : "belt..., zone..., half-length",
"пояснять" : "explain",
"прабабушка" : "great-grandmother",
"правда" : "truth, правда it is true, ваша правда you are right, не правда ли? isn't it he? aren't you they? don't ... ?",
"правдиво" : "truly",
"правдивый" : "truthful",
"правдоподобие" : "credibility, verisimilitude",
"правдоподобный" : "likely probable verisimilar",
"праведник" : "righteous",
"праведный" : "just righteous godly",
"правило" : "rule, principle, pl. regulations",
"правильный" : "correct right, regular",
"правитель" : "ruler, regent",
"правительственный" : "governmental",
"правительство" : "government",
"править" : "govern rule, drive, nav. steer, read, strop, perform",
"правка" : "proofreading, stropping",
"правление" : "government, board of directors managing #or executive committee, obsol. administration",
"правнук" : "great-grandson",
"право" : "right, law, justice, famil. license, famil. indeed really",
"право голоса" : "suffrage",
"правовед" : "jurist",
"правоведение" : "jurisprudence",
"правоверный" : "orthodox",
"правовой" : "legal",
"правомочный" : "authorized",
"правонарушитель" : "lawbreaker, trespasser",
"правописание" : "orthography spelling",
"правопреемник" : "assign",
"православие" : "Orthodoxy",
"православный" : "Orthodox",
"правосудие" : "justice",
"правота" : "right rectitude",
"правый" : "right  right-hand",
"правящий" : "ruling",
"прага" : "Prague",
"прагматический" : "pragmatic",
"прадед" : "grandfather",
"празднество" : "festival, gala, jubilee",
"праздник" : "holiday, festival, с праздником! compliments pl. !",
"праздничный" : "festive holiday...",
"празднование" : "celebration",
"праздновать" : "celebrate",
"празднословие" : "idle talk",
"праздность" : "idleness",
"праздный" : "idle",
"празеодим" : "praseodymium",
"практик" : "practical man, expert",
"практика" : "practice",
"практиковать" : "practice -ise",
"практический" : "practical",
"практичный" : "practical",
"прапорщик" : "ensign",
"прародитель" : "progenitor",
"прах" : "dust, ashes pl.",
"прачечная" : "laundry",
"прачка" : "laundress",
"праща" : "sling",
"пребывание" : "stay",
"пребывать" : "stay",
"превзойти" : "s. превосходить",
"превозмогать" : "overcome subdue",
"превозмочь" : "overcome subdue",
"превознести" : "extol exalt",
"превозносить" : "extol exalt",
"превосходительство" : "Excellency",
"превосходить" : "excel surpass",
"превосходный" : "excellent splendid, superior, gr. superlative",
"превосходство" : "superiority",
"превосходящий" : "superior, transcendent",
"превратить" : "s. превращать",
"превратность" : "vicissitude",
"превращать" : "transmogrify, transmute",
"превращение" : "conversion, transform, transmutation",
"превышать" : "exceed, outreach",
"преграждать" : "bar block",
"прегрешать" : "sin",
"прегрешить" : "sin",
"пред" : "= перед",
"предавать" : "betray, subject expose; See also: предать забвению",
"предаваться" : "indulge, devote o.s. up",
"предание" : "legend, tradition",
"предания" : "lore",
"преданность" : "devotion",
"преданный" : "devoted faithful true, cf. искренний",
"предатель" : "traitor",
"предательский" : "treacherous",
"предательство" : "treason treachery",
"предать" : "betray, subject expose; See also: предать забвению",
"предать забвению" : "bury in oblivion",
"предварительно" : "previously before",
"предварительный" : "preliminary, a. on remand",
"предварить" : "forestall, advise",
"предварять" : "forestall, advise",
"предвестие" : "= предзнаменование",
"предвестник" : "harbinger",
"предвещать" : "forebode presage",
"предвзятый" : "preconceived",
"предвидение" : "foreknowledge, precognition, prescience",
"предвидеть" : "foresee",
"предвкусить" : "foretaste",
"предвкушать" : "foretaste",
"предвкушение" : "foretaste",
"предводитель" : "leader, obsol. marshal",
"предводительство" : "leadership",
"предвосхитить" : "anticipate forestall",
"предвосхищать" : "anticipate forestall",
"предвыборный" : "election...",
"предгорье" : "foothill",
"предел" : "limit bound, border, pl. precincts",
"предельный" : "limit... maximum..., utmost extreme",
"предзнаменование" : "omen presage portent",
"предзнаменовать" : "pf. portend presage",
"предисловие" : "preface",
"предки" : "ancestry",
"предлагать" : "offer, propose, suggest, order",
"предлог" : "pretext  pretense, gr. preposition",
"предложение" : "offer, proposal proposition suggestion, parl. motion, commerc. supply, gr. sentence clause",
"предложить" : "offer, propose, suggest, order",
"предложный" : "gr. prepositional",
"предместье" : "suburb",
"предмет" : "object, subject, commerc. article; See also: на предмет",
"предметный" : "subject..., objective",
"предназначать" : "destine",
"предназначить" : "destine",
"преднамеренный" : "premeditated deliberate",
"предначертать" : "pf. predetermine",
"предок" : "ancestor",
"предопределение" : "predestination",
"предопределить" : "predetermine",
"предопределять" : "predetermine",
"предоставить" : "let have, leave, give render, grant, place",
"предоставить слово" : "give pers. permission to speak",
"предоставлять" : "let have, leave, give render, grant, place",
"предостерегать" : "warn",
"предостерегающий" : "admonitory, monitory",
"предостережение" : "warning",
"предостеречь" : "warn",
"предосторожность" : "precaution",
"предосудительный" : "reprehensible scandalous",
"предотвратить" : "avert prevent",
"предотвращать" : "avert prevent",
"предотвращение" : "prevention",
"предохранение" : "protection",
"предохранительный" : "precautionary, med. preventive, engin. safety...",
"предохранить" : "guard preserve",
"предохранять" : "guard preserve",
"предписание" : "order instruction direction",
"предписать" : "order prescribe",
"предписывать" : "order prescribe",
"предписывающий" : "prescriptive",
"предплюсна" : "instep",
"предполагаемый" : "expected, presumptive",
"предполагать" : "suppose assume, impf. intend plan, presuppose",
"предположение" : "conjecture, supposition, surmise",
"предположения" : "guesswork",
"предположительный" : "presumable",
"предположить" : "suppose assume, impf. intend plan, presuppose",
"предпослать" : "s. предпосылать",
"предпоследний" : "last but one",
"предпосылать" : "premise",
"предпосылка" : "supposition, condition prerequisite",
"предпочесть" : "prefer, pt.  бы would rather",
"предпочитать" : "prefer, pt.  бы would rather",
"предпочтение" : "preference, favor; See also: отдать предпочтение",
"предпочтительный" : "preferable",
"предприимчивость" : "enterprise",
"предприимчивый" : "enterprising",
"предприниматель" : "employer, industrialist businessman",
"предпринимать" : "undertake",
"предпринять" : "undertake",
"предприятие" : "undertaking enterprise, business, plant works factory",
"предрасполагать" : "predispose",
"предрасположение" : "predisposition",
"предрасположить" : "predispose",
"предрассудок" : "prejudice",
"председатель" : "chairman president",
"председательница" : "chairwoman",
"председательство" : "presidency",
"председательствовать" : "preside  be in the chair",
"предсердие" : "atrium",
"предсказание" : "prediction, forecast, prophecy",
"предсказатель" : "diviner, soothsayer",
"предсказать" : "foretell predict, forecast, prophesy",
"предсказывать" : "foretell predict, forecast, prophesy",
"предсмертный" : "death... dying",
"представать" : "appear",
"представитель" : "representative, a. полпред, advocate",
"представительный" : "representative, stately imposing",
"представительство" : "representation, a. полпредство",
"представить" : "s. представлять",
"представление" : "performance, presentation, representation",
"представлять" : "deputize, ideate, introduce, perform, represent",
"предубеждение" : "animus, prejudice",
"предугадать" : "guess  foresee",
"предугадывать" : "guess  foresee",
"предумышленный" : "s. преднамеренный",
"предупредительный" : "preventive, obliging",
"предупредить" : "forestall anticipate  prevent, warn, give notice",
"предупреждать" : "forestall anticipate  prevent, warn, give notice",
"предупреждение" : "warning, notice, notification, prevention",
"предусматривать" : "foresee, provide  stipulate",
"предусмотреть" : "foresee, provide  stipulate",
"предусмотрительный" : "prudent",
"предчувствие" : "presentiment",
"предчувствовать" : "have a presentiment",
"предшественник" : "predecessor",
"предшествовать" : "precede",
"предшествующий" : "antecedent, anterior, foregoing, precedent, prior",
"предыдущий" : "preceding previous",
"предьявитель" : "bearer",
"предьявить" : "present produce show, jur. bring, assert",
"предьявлять" : "present produce show, jur. bring, assert",
"преемник" : "successor",
"прежде" : "formerly, first, before",
"прежде всего" : "above all",
"преждевременный" : "premature early",
"прежний" : "former previous",
"президент" : "president",
"президентский" : "presidential"
};
