var dicct_55 = {
"meliorate" : "мелиорировать",
"mellow" : "спелый, приятный на вкус, смягчать [-чить], созреть",
"melodic" : "мелодичный",
"melodious" : "мелодичный",
"melodrama" : "мелодрама",
"melodramatic" : "мелодраматический",
"melody" : "мелодия",
"melon" : "дыня",
"melpomene" : "n  греч. миф. Мельпомена",
"melt" : "[рас]таять, [рас]плавить, смягчать [-чить]",
"member" : "член",
"membership" : "членство",
"membrane" : "плева оболочка, перепонка, мембрана",
"memento" : "напоминание",
"memo" : "меморандум",
"memoir" : "мемориальная статья",
"memoirs" : "мемуары /PL",
"memorable" : "незабвенный",
"memoranda" : "See: memorandum",
"memorandum" : "заметка, меморандум",
"memorial" : "памятник",
"memorials" : "хроника, мемориальный",
"memorize" : "Am заучивать наизусть",
"memory" : "память, воспоминание",
"men" : "люди, мужчины /PL",
"menace" : "угрожать [-озить] [по]грозить, угроза, опасность",
"menagerie" : "зверинец",
"mend" : "исправлять [-авить], [по]чинить, улучшаться [улучшиться], поправляться [-авиться], починка; See also: mend one's ways, on the mend",
"mend one's ways" : "исправляться [-авиться]",
"mendacious" : "лживый",
"mendacity" : "лживость",
"mendicant" : "нищий, нищенствующий монах",
"menfolk" : "n pl  1) мужчины  2) мужская часть семьи",
"menial" : " слуга  лакей; See also: раболепный лакейский",
"meningitis" : "менингит",
"meniscus" : "мениск",
"menopause" : "менопауза",
"menstruate" : "менструировать",
"mensurable" : "измеримый",
"mensuration" : "измерение",
"mental" : "умственный, психический; See also: mental arithmetic",
"mental arithmetic" : "счет в уме",
"mentality" : "способность мышления, склад ума",
"mention" : "упоминание, упоминать [-мянуть]; See also: don't mention it!",
"mentor" : "ментор",
"menu" : "меню",
"mercantile" : "торговый коммерческий",
"mercenary" : "корыстный, наемный, наемник",
"mercer" : "торговец шелком и бархатом",
"merchandise" : "товар",
"merchant" : "торговец купец; See also: law merchant",
"merchantman" : "торговое судно",
"merciful" : "милосердный",
"merciless" : "немилосердный",
"mercurial" : "ртутный",
"mercuric" : "содержащий двухвалентную ртуть",
"mercury" : "ртуть",
"mercy" : "милосердие, сострадание, прощение; See also: be at a 's mercy",
"mere" : "простой, сплошной",
"merely" : "только просто",
"meretricious" : "показной, мишурный, распутный",
"merganser" : "n  крохаль (птица)",
"merge" : "слить",
"merger" : "слияние обЙединение",
"meridian" : "полуденный, высший, полдень, меридиан, высшая точка, расцвет",
"meridional" : "меридиональный",
"meringue" : "n  кул. меренга",
"merit" : "заслуга, достоинство, заслуживать [-ужить]; See also: make a merit of a",
"meritorious" : "достойный награды, похвальный",
"merle" : "черный дрозд",
"merlin" : "кречет",
"mermaid" : "русалка наяда",
"merriment" : "веселье",
"merry" : "веселый радостный; See also: make merry",
"merry-andrew" : "n  шут, фигляр, гаер",
"merry-go-round" : "карусель",
"merry-making" : "веселье, празднество",
"mesa" : "столовая гора",
"mescaline" : "n  мескалин (наркотик)",
"mesh" : "петля, опутывать сетями, запутаться в сетях; See also: meshes, be in mesh",
"meshes" : "сети",
"mesmeric" : "a  гипнотический",
"meson" : "n  физ. мезон",
"mesozoic" : "a  геол. мезозойский",
"mess" : "беспорядок путаница, неприятность, кавардак, приводить в беспорядок, mess about, общий стол, столовая; See also: make a mess of a",
"mess about" : "работать кое-как",
"message" : "сообщение, послание, поручение",
"messenger" : "посыльный, предвестник",
"messiah" : "мессия",
"messieurs" : "See: monsieur",
"messrs" : "n pl (сокр. от Messieurs)  господа (ставится перед фамилиями владельцев фирмы, напр., Messrs Chapman &amp; Hall)",
"messy" : "грязный",
"met" : "от meet",
"metabolic" : "относящийся к обмену веществ",
"metabolism" : "обмен",
"metal" : "металл, щебень, мостить щебнем",
"metallic" : "металлический",
"metallically" : "металлический",
"metalliferous" : "рудоносный",
"metallography" : "металлография",
"metalloid" : "металлография",
"metallurgist" : "n  металлург",
"metallurgy" : "металлургия",
"metalwork" : "n  1) металлообработка  2) собир. металлические изделия",
"metamorphism" : "метаморфизм",
"metamorphose" : "метаморфоз",
"metamorphosis" : "метаморфоза",
"metaphor" : "метафора",
"mete" : "I  n  граница; пограничный знак;  metes and bounds юр. границы, пределы",
"meteor" : "метеор",
"meteoric" : "метеорный",
"meteorite" : "метеорит",
"meteorology" : "метеорология",
"meter" : "счетчик, измеритель",
"methane" : "метан",
"methionine" : "метионин",
"method" : "метод способ, система порядок",
"methodic" : "~al, методический методичный; See also: систематический",
"methodist" : "методист",
"methodology" : "методология",
"methuselah" : "n  библ. Мафусаил",
"methyl" : "метил",
"meticulous" : "дотошный, щепетильный",
"metier" : "фр. n занятие, профессия, ремесло",
"metre" : "метр",
"metric" : "метрический; See also: metric system",
"metric system" : "метрическая система",
"metro" : "метрополитен",
"metronome" : "метроном",
"metropolis" : "столица, метрополия",
"metropolitan" : "столичный",
"mettle" : "темперамент, пыл",
"mettlesome" : "смелый",
"mew" : "чайка",
"mexican" : "мексиканский, мексиканец",
"mexico" : "мексика",
"mezzanine" : "мезонин",
"mezzo-soprano" : "n  меццо-сопрано",
"mi" : "ми",
"miasma" : "n (pl -s , -ta)  уст. миазмы, вредные испарения",
"miasmal" : "a  миазматический",
"miauw" : "[за]мяукать",
"mica" : "слюда",
"mice" : "мыши /PL",
"michaelmas" : "Михайлов день",
"michigan" : "мичиган",
"mickey" : "n:  to take the mickey out of smb. сл. дразнить кого-л., издеваться над кем-л.",
"micro" : "микро",
"micro..." : "микро...",
"microcosm" : "микрокосм",
"microfiche" : "n (pl -s , тж. без измен.)  информ. микрофиша",
"micrography" : "n  микрография",
"micron" : "микрон",
"microphone" : "микрофон",
"microscope" : "микроскоп",
"microscopy" : "микроскопия",
"mid" : "средний, срединный",
"midair" : "in midair",
"midday" : "полдень, полуденный",
"middle" : "середина, средний; See also: Middle Ages",
"middle ages" : "средние века  средневековье",
"middle-aged" : "средних лет",
"middle-class" : "средняя буржуазия",
"middle-sized" : "средней величины",
"middle-weight" : "средний вес, среднего веса",
"middleman" : "посредник",
"middlemen" : "See: middleman",
"middleweight" : "n  1) средний вес  2) борец или боксёр среднего веса (68—71 кг)",
"middling" : "посредственный",
"middy" : "= midshipman",
"midge" : "мошка",
"midget" : "карлик, миниатюрный",
"midland" : "внутренняя часть страны",
"midmost" : "центральный",
"midnight" : "полночь",
"midriff" : "диафрагма",
"midship" : "мидель",
"midshipman" : "корабельный гардемарин",
"midshipmen" : "See: midshipman",
"midst" : "середина, среда; See also: in the midst of, in our midst",
"midstream" : "середина реки",
"midsummer" : "середина лета",
"midterm" : "n (обыкн. pl)  амер. разг. экзамены в середине семестра (в университете; тж. midterm exams)",
"midway" : "на полпути",
"midweek" : "середина недели",
"midwife" : "акушерка",
"midwifery" : "акушерство",
"midwinter" : "середина зимы",
"midwives" : "See: midwife",
"mien" : "мина",
"miff" : "легкая ссора",
"might" : "мощь, могущество, от may; See also: with might and main",
"mighty" : "могущественный, громадный",
"migrant" : "мигрант",
"migrate" : "мигрировать",
"migration" : "миграция, перелет",
"migratory" : "кочующий, перелетный",
"mike" : "микрофон",
"milage" : "расстояние в милях",
"milch" : "молочный",
"mild" : "мягкий, кроткий, слабый",
"mildew" : "милдью, плесень",
"mildness" : "мягкость, кроткость, умеренность",
"mile" : "миля",
"mileage" : "расстояние в милях",
"miles" : "See: mile",
"milestone" : "мильный камень или столб",
"milieu" : "окружение",
"militant" : "боец",
"militarism" : "милитаризм",
"militarist" : "n  1) милитарист  2) pl военщина",
"military" : "военный, воинский, военные, военные власти; See also: Military Government",
"military government" : "военное правительство",
"militate" : "бороться",
"militia" : "милиция, ополчение",
"militiaman" : "n  1) ополченец; солдат милиционной армии  2) милиционер",
"milk" : "молоко, [вы]доить; See also: powdered milk, whole milk, milkmaid, milkman, milksop, milky, Milk Way",
"milk way" : "Млечный путь",
"milkmaid" : "доярка",
"milkman" : "молочник",
"milksop" : "бесхарактерный человек тряпка",
"milkweed" : "n  название многих растений, выделяющих млечный сок, напр. молочай",
"milky" : "молочный",
"mill" : "мельница, фабрика завод, [с]молоть, [от]фрезеровать, милл",
"mill-pond" : "мельничный пруд",
"mill-stone" : "жернов",
"millennia" : "See: millennium",
"millennium" : "тысячелетие",
"millepede" : "многоножка",
"miller" : "мельник, фрезерный станок, фрезеровщик",
"millet" : "просо",
"milliner" : "модистка",
"millinery" : "магазин дамских шляп",
"million" : "миллион",
"millionaire" : "миллионер",
"millions" : "See: million",
"millionth" : "миллионный, миллионная часть",
"millipede" : "многоножка",
"mills" : "See: mill",
"millstone" : "жернов",
"milord" : "милорд",
"milt" : "молоки /PL",
"mimeograph" : "мимеограф",
"mimesis" : "имитирование",
"mimetic" : "подражательный",
"mimic" : "подражательный, имитатор, пародировать, подражать",
"mimicked" : "See: mimic",
"mimicking" : "See: mimic",
"mimicry" : "подражание, мимикрия",
"minaret" : "минарет",
"mince" : "[из]рубить, говорить жеманно, рубленое мясо; See also: he does not mince matters",
"mince-pie" : "пирог",
"mincemeat" : "фарш из изюма яблок и т.п.",
"mincing-machine" : "мясорубка",
"mind" : "ум разум, мнение, намерение, охота, память, помнить, [по]заботиться о, остерегаться [-речься]; See also: to my mind, out of one's mind, change one's mind, bear in mind, have a mind to, have a on one's mind, make up one's ~, never mind!, I don't mind, would you mind taking off your hat?",
"mindful" : "внимательный, заботливый",
"mine" : "мой  мое  мои, мои моя семья, рудник копь  шахта, источник, мина, добыть, рыть, производить горные работы, минировать, подрыть, подрывать [подорвать]; See also: miner",
"minefield" : "минное поле",
"miner" : "горняк шахтер",
"mineral" : "минерал, минеральный; See also: minerals",
"mineralogy" : "минералогия",
"minerals" : "минеральные воды"
};
