var dicctr_50 = {
"обрезать" : "cut off, cut short",
"обрезок" : "scrap",
"обрезывать" : "s. обрезать",
"обрекать" : "doom",
"обременительный" : "burdensome",
"обременить" : "burden",
"обременять" : "burden",
"обреченный" : "doomed",
"обречь" : "doom",
"обрисовать" : "outline sketch, -ся loom appear",
"обрисовывать" : "outline sketch, -ся loom appear",
"оброк" : "rent tribute",
"обросший" : "overgrown",
"обрубать" : "hew  lop",
"обрубить" : "hew  lop",
"обрубок" : "stump block",
"обруч" : "hoop",
"обручальный" : "engagement...",
"обручать" : "affiance betroth, -ся be engaged",
"обручение" : "betrothal",
"обрученный" : "fiance'",
"обручить" : "affiance betroth, -ся be engaged",
"обрушивать" : "demolish, cast, -ся fall in collapse, fall on",
"обрушить" : "demolish, cast, -ся fall in collapse, fall on",
"обрыв" : "precipice steep",
"обрывать" : "tear #or pluck, break off cut short, -ся a. fall",
"обрывистый" : "steep, abrupt",
"обрывок" : "scrap shred",
"обрывочный" : "scrappy",
"обрызгать" : "sprinkle",
"обрызгивать" : "sprinkle",
"обрюзглый" : "flabby bloated",
"обряд" : "ceremony rite",
"обрядовый" : "ritual",
"обсадить" : "plant",
"обсаживать" : "plant",
"обсевать" : "sow, stud",
"обсерватория" : "observatory",
"обсеять" : "sow, stud",
"обсидиан" : "obsidian",
"обследование" : "inspection, inquiry  investigation",
"обследовать" : "pf. inspect examine investigate",
"обслуживание" : "service, operation",
"обслуживать" : "serve attend, operate, supply",
"обслужить" : "serve attend, operate, supply",
"обсохнуть" : "s. обсыхать",
"обставить" : "surround, furnish fit out, famil. arrange settle",
"обставлять" : "surround, furnish fit out, famil. arrange settle",
"обстановка" : "furniture, thea. scenery, situation conditions pl.",
"обстоятельный" : "detailed circumstantial, famil. solid thorough",
"обстоятельства" : "circumstance",
"обстоятельственный" : "adverbial",
"обстоятельство" : "circumstance, gr. adverb",
"обстоять" : "be stand, как обстоит дело с ? what about ...?",
"обстрел" : "bombardment fire",
"обстреливать" : "fire on shell, famil. tried",
"обстрелять" : "fire on shell, famil. tried",
"обступать" : "surround",
"обступить" : "surround",
"обсудить" : "discuss",
"обсуждать" : "discuss",
"обсуждение" : "discussion",
"обсушить" : "pf. dry",
"обсчитать" : "pf. cheat",
"обсчитаться" : "miscalculate",
"обсыпать" : "strew",
"обсыхать" : "dry",
"обтачивать" : "turn",
"обтекаемый" : "streamline...",
"обтереть" : "s. обтирать",
"обтесать" : "hew",
"обтесывать" : "hew",
"обтирание" : "rubdown",
"обтирать" : "rub off #or down wipe  dry, famil. fray",
"обточить" : "turn",
"обтрепанный" : "shabby frayed",
"обтягивать" : "cover, impf. fit close",
"обтяжка" : "в обтяжку close-fitting",
"обтянуть" : "cover, impf. fit close",
"обувать" : "put shoes on, famil. shoe",
"обувь" : "footwear shoes pl.",
"обугливать" : "char",
"обуглить" : "char",
"обуза" : "burden load",
"обуздать" : "bridle",
"обуздывать" : "bridle",
"обусловить" : "condition, cause",
"обусловливать" : "condition, cause",
"обуть" : "put shoes on, famil. shoe",
"обух" : "butt, famil. thunder",
"обучать" : "teach  train, -ся learn be taught",
"обучение" : "instruction training, education",
"обучить" : "teach  train, -ся learn be taught",
"обхват" : "arm's span, circumference",
"обхватить" : "clasp  embrace infold",
"обхватывать" : "clasp  embrace infold",
"обход" : "round beat, detour, s. обходить, evasion",
"обходительный" : "affable amiable",
"обходить" : "go #or pass round, travel through #or over, visit, milit. outflank, avoid, pass over, cost, manage, do without, there is, treat",
"обходиться" : "do without",
"обходной" : "bypass",
"обходный" : "roundabout",
"обхождение" : "treatment manners pl.",
"обшаривать" : "rummage",
"обшарить" : "rummage",
"обшивать" : "sew round border, plank face sheath, famil. clothe",
"обшивка" : "trimming etc.",
"обширный" : "vast extensive, numerous",
"обшить" : "sew round border, plank face sheath, famil. clothe",
"общаться" : "associate",
"общедоступный" : "popular, a. доступный",
"общежитие" : "hostel home, social intercourse #or life",
"общеизвестный" : "well-known",
"общенародный" : "nationwide",
"общение" : "intercourse",
"общепринятый" : "generally accepted common",
"общественность" : "community public",
"общественный" : "social public, common",
"общественный деятель" : "public man",
"общество" : "society, company, association, community",
"обществоведение" : "social science",
"общеупотребительный" : "current common widespread",
"общий" : "general, common, public, total whole, d'hote",
"община" : "community, a. = общество",
"общинный" : "communal",
"общительный" : "sociable affable",
"общность" : "community, commonness",
"объединение" : "coalition, joinder, rally",
"объединенный" : "associate, cooperative, joint, united",
"объединять" : "unify, unionize",
"объезд" : "circuit",
"объективность" : "objectivity",
"объем" : "volum",
"объемистый" : "capacious",
"объемлющий" : "embedding, enclosing",
"объемный" : "volumetric",
"объявление" : "ad, advertisement, announcement",
"объявлять" : "declare, give out, meld",
"объяснение" : "explanation, interpretation, rede",
"объяснимый" : "explicable",
"объяснительный" : "explanatory, explicative, exponent",
"объяснять" : "account for, explain, explicate",
"объятие" : "cuddle",
"объятия" : "embrace",
"обыватель" : "inhabitant, Philistine",
"обывательский" : "Philistine...",
"обыграть" : "beat, win",
"обыгрывать" : "beat, win",
"обыденный" : "everyday ordinary",
"обыкновение" : "habit; See also: по обыкновению",
"обыкновенный" : "ordinary usual habitual",
"обыск" : "search",
"обыскать" : "search",
"обыскивать" : "search",
"обычай" : "custom, famil. habit",
"обычный" : "customary usual habitual",
"обьедать" : "eat #or gnaw round away, -ся overeat o.s.",
"обьединение" : "association union, unification",
"обьединить" : "unite  join, rally",
"обьединять" : "unite  join, rally",
"обьедки" : "leavings",
"обьезд" : "detour by-pass, vb.  в обьезд = обьезжать",
"обьезжать" : "обьехать go drive round, travel through #or over, visit, обьездить break in, s.",
"обьект" : "object",
"обьективный" : "objective",
"обьем" : "volume, size, extent range",
"обьемистый" : "voluminous",
"обьесть" : "eat #or gnaw round away, -ся overeat o.s.",
"обьехать" : "s. обьезжать",
"обьявить" : "s. обьявлять",
"обьявить вне закона" : "outlaw",
"обьявление" : "announcement notice, advertisement, declaration",
"обьявлять" : "declare  tell, announce proclaim, advertise, express",
"обьяснение" : "explanation, declaration",
"обьяснимый" : "explicable accountable",
"обьяснительный" : "explanatory",
"обьяснить" : "explain illustrate, account for, -ся explain o.s., be accounted for, declare o.s., o.s. understood",
"обьяснять" : "explain illustrate, account for, -ся explain o.s., be accounted for, declare o.s., o.s. understood",
"обьятия" : "embrace, arms",
"обязанность" : "duty, milit. service; See also: исполняющий обязанности",
"обязанный" : "obliged, indebted owe, responsible",
"обязательно" : "without fail certainly",
"обязательный" : "obligatory compulsory",
"обязательство" : "obligation, liability, engagement",
"обязать" : "oblige, bind commit, -ся engage undertake pledge o.s.",
"обязывать" : "oblige, bind commit, -ся engage undertake pledge o.s.",
"овал" : "ellipse",
"овальный" : "elliptic, elliptical, oval",
"овдовевший" : "widowed",
"овен" : "aries",
"овес" : "oats pl.",
"овечий" : "sheep",
"овладевать" : "seize take possession of, get control over, master",
"овладеть" : "own possess, rule govern, master, manage; See also: владеть собой",
"овод" : "gadfly",
"овощ" : "potherb, vegetable",
"овощи" : "vegetables",
"овощной магазин" : "greengrocery",
"овраг" : "ravine",
"овсянка" : "oatmeal",
"овсяный" : "oat",
"овца" : "sheep",
"овцеводство" : "sheep breeding",
"овчарка" : "sheep dog",
"овчина" : "sheepskin",
"огам" : "ogam, ogham",
"огарок" : "candle end",
"огибать" : "turn #or bend, nav. double",
"оглавление" : "table of contents",
"огласить" : "announce, divulge, publish, fill resound, -ся ring",
"огласка" : "publicity",
"оглашать" : "announce, divulge, publish, fill resound, -ся ring",
"оглашение" : "announcement, publication, banns pl.",
"оглобля" : "shaft",
"оглушать" : "deafen stun",
"оглушительный" : "deafening stunning",
"оглушить" : "deafen stun",
"оглядеть" : "examine take a view of",
"оглядеться" : "look round, оглянуться",
"оглядка" : "без оглядки",
"огненный" : "fiery, flamy, lurid",
"огнеопасный" : "flammable",
"огнеупорный" : "fireproof, refractory",
"оговорить" : "slander, stipulate, a. = -ся make a reservation, a. обмолвиться",
"оговорка" : "reservation reserve proviso, cf.",
"оголить" : "bare",
"оголять" : "bare",
"огонек" : "light, spark",
"огонь" : "fire, light; See also: из огня да в полымя, сквозь огонь и воду",
"огораживать" : "enclose fence",
"огород" : "kitchen garden",
"огородить" : "enclose fence",
"огородник" : "trucker market #or kitchen gardener",
"огородничество" : "trucking market gardening",
"огорчать" : "grieve  afflict vex distress",
"огорчение" : "grief affliction trouble",
"огорчительный" : "grievous, vexatious",
"огорчить" : "grieve  afflict vex distress",
"ограбить" : "rob plunder",
"ограбление" : "robbing robbery",
"ограда" : "fence, wall",
"оградить" : "enclose, guard protect",
"ограждать" : "enclose, guard protect",
"ограждение" : "enclosure, protection",
"ограничение" : "limitation, restriction",
"ограниченный" : "confined, limited, narrow",
"ограничивать" : "confine limit restrict",
"ограничительный" : "restrictive",
"ограничить" : "confine limit restrict",
"огромный" : "huge vast, enormous tremendous"
};
