var dicctr_15 = {
"газовая педаль" : "mot. accelerator, gauze...",
"газовый" : "gas...; See also: газовый счетчик, газовая педаль",
"газовый счетчик" : "= газомер",
"газомер" : "gas meter",
"газометр" : "gasometer",
"газон" : "lawn",
"газообразный" : "gaseous",
"газопровод" : "gas pipe line",
"гаити" : "haiti",
"гаитянский" : "haitian",
"гаичка" : "chickadee",
"гайка" : "engin. nut",
"галактический" : "galactic",
"галантерейные товары" : "notions pl. pl.",
"галантерейный магазин" : "notions store Brt. haberdashery",
"галантерея" : "notions pl. pl.",
"галантность" : "gallantry",
"галдеж" : "row hubbub",
"галдеть" : "clamor din",
"галерея" : "gallery",
"галерка" : "thea. gallery",
"галифе" : "ind. milit. breeches",
"галка" : "jackdaw",
"галл" : "gaul",
"галлий" : "gallium",
"галлон" : "gallon",
"галоп" : "gallop",
"галопировать" : "gallop",
"галопом" : "at a gallop",
"галоша" : "galosh, gumshoe, overshoe",
"галоши" : "galoshes rubbers",
"галстук" : "tie",
"галун" : "galloon braid",
"гальванизация" : "galvanism",
"гальванизировать" : "pf. galvanize",
"гальванический" : "galvanic",
"гальванометр" : "galvanometer",
"галька" : "pebble",
"гам" : "din row rumpus",
"гамак" : "hammock",
"гамаши" : "gaiters",
"гамма" : "mus. scale, range",
"гана" : "ghana",
"ганг" : "ganges",
"гангрена" : "gangrene",
"гангстер" : "gangster",
"гандикап" : "handicap",
"ганноверский" : "hanoverian",
"гантели" : "dumbbells",
"гантель" : "barbell, dumbbell",
"гараж" : "garage",
"гарантировать" : "guarantee warrant",
"гарантия" : "guarantee warrant",
"гардероб" : "wardrobe, check- cloakroom",
"гардеробщик" : "cloakroom attendant",
"гардеробщица" : "cloakroom attendant",
"гардина" : "curtain",
"гарем" : "harem, seraglio",
"гармоника" : "accordion; See also: губная гармоника",
"гармонировать" : "harmonize be in harmony",
"гармонист" : "accordionist, harmonist",
"гармонический" : "harmonic, гармоничный",
"гармоничный" : "harmonious",
"гармония" : "harmony, a. = гармонь; See also: гармошка",
"гармонь" : "= гармоника",
"гармошка" : "= гармоника",
"гарнизон" : "garrison",
"гарнир" : "pf. cook. garnish",
"гарнировать" : "pf. cook. garnish",
"гарнитур" : "set",
"гарпия" : "harpy",
"гарпун" : "harpoon",
"гарпунить" : "harpoon",
"гарцевать" : "prance",
"гарь" : "burnt char",
"гасить" : "extinguish put #or blow out, slake",
"гаснуть" : "go out die away, fig. fade wither",
"гастролер" : "guest actor #or artist star",
"гастролировать" : "tour give performance on a tour",
"гастроль" : "starring",
"гастроном" : "gastronome, gourmet, a. = гастрономический магазин",
"гастрономический" : "gastronomic; See also: гастрономический магазин",
"гастрономический магазин" : "delicatessen food store #or shop",
"гастрономия" : "gastronomy, dainties delicacies pl.",
"гауптвахта" : "guardhouse",
"гашиш" : "hasheesh, hashish",
"гвалт" : "rumpus din",
"гвардеец" : "guardsman",
"гвардия" : "Guards pl.",
"гватемала" : "guatemala",
"гвоздик" : "cf.",
"гвоздика" : "carnation pink, clove",
"гвоздь" : "nail, fig. main feature hit",
"гг" : "abbr.:, годы, господа",
"где-нибудь" : "anywhere, someplace, somewhere",
"гегемония" : "hegemony",
"гейзер" : "geyser",
"гейша" : "geisha",
"гелий" : "helium",
"гелиотроп" : "plasm",
"гемоглобин" : "hemoglobin",
"геморрой" : "hemorrhoid, hemorrhoids, piles",
"генеалогия" : "genealogy",
"генерал" : "general",
"генерал-майор" : "major general",
"генеральная репетиция" : "dress rehearsal",
"генеральный" : "general; See also: генеральная репетиция",
"генератор" : "generator",
"генетический" : "genetic",
"гениальность" : "charisma",
"гениальный" : "of genius, ingenious",
"гений" : "genius",
"генотип" : "biotype, genotype",
"географ" : "geographer",
"географический" : "geographic",
"география" : "geography",
"геолог" : "geologist",
"геология" : "geology",
"геометрия" : "geometry",
"георгий" : "George",
"георгин" : "dahlia",
"георгина" : "dahlia",
"геофизика" : "geophysics",
"геохимия" : "geochemistry",
"геоцентрический" : "geocentric",
"гепард" : "cheetah",
"герань" : "geranium",
"герасим" : "Gerasim",
"герб" : "arms, emblem",
"гербовый" : "stamp",
"геркулес" : "hercules",
"геркулесовский" : "herculean",
"германий" : "germanium",
"германия" : "Germany",
"германская демократическая республика" : "German Democratic Republic",
"германский" : "German",
"гермафродитный" : "bisexual",
"герметический" : "hermetic",
"героизм" : "heroism",
"героин" : "heroin",
"героиня" : "heroine",
"героический" : "heroic",
"герой" : "hero",
"геройский" : "heroic",
"герц" : "hertz",
"герцог" : "duke",
"герцогиня" : "duchess",
"герцогство" : "duchy, dukedom",
"гессенский" : "hessian",
"гестапо" : "gestapo",
"гетероциклический" : "heterocyclic",
"гетры" : "gaiters",
"гетто" : "ghetto",
"г-жа" : "abbr.: госпожа",
"гиацинт" : "hyacinth",
"гиббон" : "gibbon",
"гибель" : "ruin destruction, loss, nav. wreck, death, popul. immense number lots of",
"гибельный" : "disastrous fatal",
"гибкий" : "supple pliant flexible",
"гибкость" : "flexibility",
"гиблый" : "ruinous",
"гибнуть" : "perish",
"гибралтар" : "Gibraltar",
"гигант" : "giant",
"гигантский" : "gigantic huge",
"гигиена" : "hygiene",
"гигиенический" : "hygienic",
"гигиеничный" : "hygienic",
"гигроскопический" : "hygroscopic",
"гид" : "guide",
"гидра" : "hydra",
"гидравлический" : "hydraulic",
"гидрат" : "hydrate",
"гидрировать" : "hydrogenate",
"гидродинамический" : "hydrodynamic",
"гидролиз" : "hydrolysis",
"гидроплан" : "seaplane hydroplane",
"гидросамолет" : "seaplane hydroplane",
"гидростанция" : "hydroelectric power station",
"гидросфера" : "hydrosphere",
"гидрофильный" : "hydrophilic",
"гиена" : "hyaena, hyena",
"гиканье" : "whoop",
"гильдия" : "guild",
"гильза" : "case, shell",
"гильотина" : "guillotine",
"гималаи" : "The Himalayas",
"гимн" : "hymn, anthem",
"гимназист" : "pupil #of гимназия",
"гимназия" : "high school Brt. grammar school",
"гимнаст" : "gymnast",
"гимнастерка" : "Brt. tunic",
"гимнастика" : "gymnastics",
"гимнастический" : "gymnastic",
"гинея" : "guinea",
"гипербола" : "hyperbole, math. hyperbola",
"гиперболический" : "hyperbolic exaggerated",
"гипноз" : "hypnosis",
"гипнотизировать" : "hypnotize",
"гипнотический" : "hypnosis",
"гипотеза" : "hypothesis",
"гипотетический" : "hypothetic, hypothetical",
"гиппопотам" : "hippopotamus",
"гипс" : "min. gypsum, engin. plaster of Paris",
"гипсовый" : "gypsum... plaster...",
"гирлянда" : "garland",
"гиря" : "weight",
"гитара" : "guitar",
"глава" : "head, top summit, cupola, chapter, во главе at the head, lead, head chief",
"главарь" : "leader chieftain",
"главенство" : "priority hegemony",
"главенствовать" : "dominate",
"главнокомандующий" : "commander in chief; See also: Верховный главнокомандующий",
"главный" : "chief main principal central, head..., ... in chief, главная книга commerc. ledger, главное the main thing, above all, главный город capital; See also: главным образом",
"главным образом" : "mainly chiefly",
"глагол" : "gr. verb, obsol. word speech",
"глагольный" : "verb",
"гладиатор" : "gladiator",
"гладильный" : "ironing",
"гладиолус" : "gladiola, gladiolus",
"гладить" : "выгладить iron press, погладить stroke caress, famil. гладить по головке treat with indulgence #or favor",
"гладкий" : "smooth, lank, plain, popul. well-fed",
"гладкость" : "smoothness",
"гладь" : "smoothness",
"глаз" : "eye, look, sight, famil. heed care, темно хоть ~ выколи famil. it is pitch-dark; See also: в глаза, в моих глазах, за глаза, на глаз, на глазах, с глазу на глаз, простым глазом, невооруженным глазом",
"глазастый" : "goggle-eyed, sharp-sighted",
"глазго" : "glasgow",
"глазеть" : "stare #or gape",
"глазничный" : "orbital",
"глазной" : "eye... optic; See also: глазной врач",
"глазной врач" : "oculist",
"глазок" : "dim. of глаз; See also: анютины глазки",
"глазомер" : "на глазомер",
"глазурь" : "glaze",
"глашатай" : "bellman, crier",
"глина" : "clay",
"глинистый" : "argillaceous",
"глиняный" : "earthenware, fictile",
"глист" : "worm, глист tapeworm",
"глиста" : "worm, глист tapeworm",
"глицерин" : "glycerine",
"глобус" : "globe",
"глодать" : "gnaw",
"глотать" : "swallow, famil. devour",
"глотка" : "throat, во всю глотку s. голос",
"глотнуть" : "swallow, famil. devour",
"глоток" : "draught gulp",
"глохнуть" : "оглохнуть grow deaf, заглохнуть fade die away out, go out, grow desolate",
"глубина" : "depth, remoteness, fig. profundity, thea. background, ... #or ... в B ... deep",
"глубокий" : "deep, low, remote, fig. profound, complete, great, глубокой зимой, in the dead of winter"
};
