var dicctr_69 = {
"притон" : "den nest",
"приторный" : "sugary luscious",
"притрагиваться" : "touch",
"притронуться" : "touch",
"притупить" : "blunt dull",
"притупление" : "atrophy",
"притуплять" : "blunt dull",
"притча" : "parable",
"притягивать" : "draw pull, attract, s. привлекать",
"притягиваться" : "gravitate",
"притяжательный" : "possessive",
"притяжение" : "attraction",
"притязание" : "claim pretension",
"притянуть" : "draw pull, attract, s. привлекать",
"приурочить" : "pf. time date",
"приучать" : "accustom habituate, train",
"приученный" : "housebroken",
"приучить" : "accustom habituate, train",
"прихварывать" : "be unwell #or sickly",
"прихворнуть" : "be unwell #or sickly",
"приход" : "arrival coming, commerc. receipt credit, parish",
"приходить" : "come  arrive, fig. fall get fly, приходить в голову на ум etc., think of hit on  take into one's head, #not: a. dream; See also: приходить в себя, приходить в чувство",
"приходить в себя" : "come to",
"приходить в чувство" : "come to",
"приходиться" : "suit fit, be, fall, мне приходится I have to must, придется s. попасть",
"приходный" : "receipt...",
"приходо-расходный" : "cash",
"приходский" : "parish...",
"приходящий" : "day, med. ambulatory",
"прихожанин" : "parishioner",
"прихожая" : "s. передняя",
"прихотливый" : "freakish, fastidious",
"прихоть" : "whim freak",
"прихрамывать" : "limp slightly",
"прицветник" : "bract",
"прицел" : "sight, прицеливание",
"прицеливание" : "aim",
"прицеливаться" : "aim",
"прицелить" : "aim",
"прицепить" : "hook, couple",
"прицепиться" : "stick cling, a. пристать",
"прицепка" : "coupling",
"прицеплять" : "hook, couple",
"прицепляться" : "stick cling, a. пристать",
"прицепной вагон" : "trailer",
"причал" : "mooring",
"причаливать" : "moor, land",
"причалить" : "moor, land",
"причастие" : "gr. participle, eccl. Eucharist, famil. = причащение",
"причастить" : "administer the Lord's Supper #or Sacraments",
"причастный" : "participating #or involved",
"причащать" : "administer the Lord's Supper #or Sacraments",
"причащение" : "administration of the Lord's Supper",
"причем" : "... ~ известно что ... = ... it being known that ...",
"прическа" : "hairdo  coiffure",
"причесывать" : "do brush comb",
"причина" : "cause, reason, по причине because of",
"причинить" : "cause do",
"причинность" : "causality",
"причинный" : "causal",
"причинять" : "cause do",
"причислить" : "rank number, milit. assign, famil. add",
"причислять" : "rank number, milit. assign, famil. add",
"причитание" : "lamentation",
"причитать" : "lament",
"причитаться" : "be due have to pay",
"причуда" : "whim freak",
"причудливый" : "freakish, cranky",
"пришелец" : "newcomer arrival",
"пришибленный" : "dejected",
"пришивать" : "sew, famil. involve  impose",
"пришить" : "sew, famil. involve  impose",
"пришпорить" : "pf. spur on",
"прищемить" : "pinch squeeze in",
"прищемлять" : "pinch squeeze in",
"прищуривать" : "s. жмурить",
"прищурить" : "s. жмурить",
"приют" : "refuge shelter, asylum orphanage",
"приютить" : "pf. shelter",
"приятель" : "friend",
"приятельница" : "friend",
"приятельский" : "friendly",
"приятно на вкус" : "= вкусно",
"приятный" : "pleasant pleasing agreeable",
"приятный на вкус" : "savory",
"про" : "famil. about of; See also: про себя",
"про запас" : "in store #or reserve",
"про себя" : "to o.s. silently",
"проанализировать" : "analyze",
"проба" : "trial  test, engin. assay sample, standard hallmark",
"пробарабанить" : "drum",
"пробег" : "run race",
"пробегать" : "run  pass, cover, skim",
"пробежать" : "run  pass, cover, skim",
"пробел" : "blank gap, defect",
"пробивать" : "break through, pierce punch, a. бить",
"пробиваться" : "fight one's way, famil. rough it, bot. come up, shine through, pf. toil",
"пробил его час" : "his hour has struck",
"пробирать" : "famil. scold, blow up upbraid",
"пробираться" : "make one's way, steal #or slip",
"пробирка" : "test tube",
"пробить" : "break through, pierce punch, a. бить",
"пробка" : "cork, stopper plug, el. fuse, #traffic: jam",
"пробковый" : "cork...",
"проблема" : "problem",
"проблематический" : "problematic",
"проблематичный" : "problematic",
"проблеск" : "gleam, flash",
"проблуждать" : "roam wander",
"пробный" : "trial... test..., specimen... sample..., touch, pilot",
"пробовать" : "try, taste",
"пробоина" : "hole, nav. leak",
"пробор" : "parting",
"пробормотать" : "murmur mutter",
"пробочник" : "corkscrew",
"пробрать" : "famil. scold, blow up upbraid",
"пробраться" : "s. пробирать",
"пробренчать" : "clink jingle, strum",
"пробудить" : "waken rouse",
"пробудиться" : "awake wake up",
"пробуждать" : "waken rouse",
"пробуждаться" : "awake wake up",
"пробуждение" : "awakening",
"пробуравить" : "bore drill",
"пробурить" : "bore",
"пробыть" : "pf. stay",
"провал" : "collapse, fig. failure",
"проваливать" : "wreck, fail, reject, thea. damn, проваливай! famil. decamp",
"проваливаться" : "break #or fall in, fail flunk, thea. be damned, disappear, провались! famil. the deuce take you!",
"провалить" : "wreck, fail, reject, thea. damn, проваливай! famil. decamp",
"провалиться" : "break #or fall in, fail flunk, thea. be damned, disappear, провались! famil. the deuce take you!",
"провальсировать" : "waltz",
"прованский" : "olive",
"проведать" : "pf. visit, find out",
"проведение" : "carrying out realization, construction installation",
"провезти" : "s. провозить",
"провентилировать" : "ventilate air",
"проверить" : "s. проверять",
"проверка" : "check examination control",
"проверять" : "examine check  control",
"провести" : "s. проводить",
"проветривать" : "air ventilate",
"проветрить" : "air ventilate",
"провиант" : "s. провизия",
"провизия" : "provisions foodstuffs victuals pl.",
"провиниться" : "pf. commit offence be guilty, offend",
"провинциал" : "hick",
"провинциальный" : "provincial",
"провинция" : "province",
"провод" : "wire line, cable, lead",
"проводимость" : "conductivity",
"проводить" : "провести lead el. impf. conduct guide, carry out  realize put, put #or get through, pass, spend, draw, lay construct, develop, pursue, hold, commerc. enter book, famil. trick cheat, s. провожать",
"проводка" : "construction installation, el. lead, tel. line wire",
"проводник" : "guide, el. conductor",
"проводящий" : "conductive",
"провожать" : "see  accompany, follow",
"провоз" : "transport",
"провозгласить" : "proclaim, propose",
"провозглашать" : "proclaim, propose",
"провозглашение" : "proclamation",
"провозить" : "drive convey, take get carry",
"провокатор" : "agent provocateur",
"провокация" : "provocation",
"проволока" : "wire",
"проволочка" : "delay  protraction",
"проворный" : "quick nimble deft",
"проворство" : "quickness nimbleness deftness",
"провоцировать" : "a. спровоцировать provoke",
"провялить" : "dry sun",
"прогадать" : "pf. lose",
"прогалина" : "glade, patch spot",
"прогиб" : "hogging, sag",
"проглатывать" : "swallow gulp, famil. lose",
"проглотить" : "swallow, famil. devour",
"проглядывать" : "проглядеть overlook, look over, проглянуть peep out appear",
"прогнать" : "s. прогонять",
"прогневаться" : "be angry",
"прогноз" : "forecast, med. prognosis",
"проговаривать" : "say, talk, -ся blab",
"проговорить" : "say, talk, -ся blab",
"проголодаться" : "pf. get #or feel hungry",
"проголосовать" : "vote",
"прогонять" : "drive, fig. banish, famil. fire, run",
"прогорать" : "burn through, famil. smash",
"прогореть" : "burn through, famil. smash",
"прогорклый" : "rancid",
"прогорланить" : "bawl",
"программа" : "program",
"программирование" : "programming",
"программист" : "programmer",
"прогреметь" : "thunder peal, rattle clank tinkle, clatter, fig. ring, be famous",
"прогресс" : "progress",
"прогрессивный" : "progressive",
"прогрессировать" : "progress",
"прогрызать" : "gnaw #or bite through",
"прогрызть" : "gnaw #or bite through",
"прогул" : "truancy",
"прогуливать" : "shirk  play truant",
"прогуливаться" : "take walk",
"прогулка" : "walk  stroll ride",
"прогульщик" : "shirker truant",
"прогулять" : "shirk  play truant",
"продавать" : "sell",
"продавец" : "seller salesman clerk Brt. shop assistant",
"продавщица" : "seller salesman clerk Brt. shop assistant",
"продажа" : "sale",
"продажный" : "for sale, venal corrupt",
"продать" : "sell",
"продвигать" : "move push",
"продвигаться" : "advance",
"продвигающийся" : "onward, onwards",
"продвижение" : "advance",
"продвинуть" : "move push",
"продвинуться" : "advance",
"продекламировать" : "declaim",
"проделать" : "s. проделывать",
"проделка" : "trick prank",
"проделывать" : "break through make, carry through #or out do, famil. play",
"продемонстрировать" : "demonstrate, show project",
"продеть" : "pf. pass through thread",
"продиктовать" : "dictate",
"продлевать" : "prolong",
"продление" : "prolongation",
"продлить" : "prolong",
"продлиться" : "last",
"продовольственный" : "food..., grocery...",
"продовольствие" : "food provisions pl.",
"продолговатый" : "oblong",
"продолжатель" : "continuator",
"продолжать" : "continue go on, lengthen, prolong",
"продолжаться" : "last",
"продолжение" : "continuation, sequel, course; See also: продолжение следует",
"продолжение следует" : "to be continued",
"продолжительность" : "duration",
"продолжительный" : "long",
"продолжить" : "continue go on, lengthen, prolong",
"продольный" : "longitudinal",
"продрогнуть" : "pf. be chilled",
"продукт" : "product, material, a. stuffs",
"продуктивность" : "productivity",
"продуктивный" : "productive",
"продуктовый" : "grocery",
"продукция" : "production  output",
"продумать" : "think over",
"продумывать" : "think over",
"проедать" : "eat away #or through, famil. spend, eat",
"проезд" : "passage thoroughfare; See also: проездом",
"проездить" : "s. проезжать",
"проездная плата" : "fare",
"проездной" : "проездной билет; See also: проездная плата"
};
