var dicctr_88 = {
"томография" : "stratigraphy, tomography",
"тому назад" : "ago",
"тон" : "tone",
"тональный" : "tonal",
"тонизирующий" : "tonic",
"тоника" : "keynote",
"тонкий" : "thin, slim slender, small, fine, delicate subtle, keen, light, high, famil. cunning",
"тонкость" : "thinness s. тонкий, delicacy subtlety, pl. details",
"тонна" : "ton",
"тоннаж" : "tonnage",
"тонуть" : ", потонуть затонуть sink, submerge, утонуть drown",
"тоня" : "dim. #of Антонина",
"топаз" : "topaz",
"топать" : "stamp",
"топить" : ", затопить потопить sink, flood, затопить истопить натопить heat, light a fire, растопить melt, утопить drown",
"топка" : "heating, furnace",
"топкий" : "boggy marshy",
"топленый" : "melted, molten",
"топливо" : "fuel",
"топнуть" : "stamp",
"топограф" : "topographer",
"топография" : "topography",
"тополь" : "poplar",
"топор" : "ax",
"топорик" : "hatchet",
"топорный" : "coarse",
"топот" : "stamp tramp",
"топтать" : "trample tread",
"топтаться" : "tramp, famil. hang about, mark time",
"топь" : "march mire bog fen",
"тора" : "torah",
"торба" : "nosebag",
"торг" : "bargaining chaffer, pl. auction",
"торгаш" : "dealer",
"торговать" : "trade deal, sell, be open",
"торговаться" : "bargain",
"торговец" : "dealer trader merchant",
"торговка" : "market woman",
"торговля" : "trade commerce, traffic, business",
"торговый" : "trade... trading commercial of commerce, nav. mercantile merchant...",
"торгпред" : "Soviet trade representative",
"торгпредство" : "trade agency of the U.S.S.R.",
"торжественность" : "solemnity",
"торжественный" : "solemn, festive, triumphant",
"торжество" : "triumph, festivity celebration",
"торжествовать" : "triumph, impf. celebrate",
"торжествующий" : "triumphant",
"торий" : "thorium",
"торможение" : "braking, inhibition",
"тормоз" : "brake, fig. drag",
"тормозить" : "brake, fig. hamper, psych. curb restrain",
"тормошить" : "s. теребить",
"торнадо" : "tornado",
"торный" : "beaten",
"торопить" : "hasten hurry up",
"торопливый" : "hasty hurried",
"торпеда" : "pf. torpedo",
"торпедировать" : "pf. torpedo",
"торпедный" : "torpedo...",
"торпедный катер" : "torpedo boat",
"торс" : "torso",
"торт" : "pie, fancy cake",
"торус" : "tore",
"торф" : "peat",
"торфяной" : "peat...",
"торчать" : "stick out, famil. hang about",
"тоска" : "melancholy, anxiety grief, yearning, boredom ennui; See also: тоска по родине",
"тоска по родине" : "homesickness",
"тосканец" : "tuscan",
"тоскливый" : "melancholy, sad dreary",
"тосковать" : "grieve feel sad, feel bored, yearn #or long, be homesick",
"тоскующий" : "wistful",
"тост" : "toast",
"тот" : "that pl. those, the one, the other, a. то; See also: и тот и другой, ни тот ни другой, не тот, тот же, тем более, тем лучше, тем самым",
"тот же" : "the same",
"тоталитарный" : "totalitarian",
"тотчас" : "immediately at once",
"точильный" : "grinding",
"точильщик" : "grinder",
"точить" : "наточить whet grind, sharpen, выточить turn, источить eat away, gnaw at, perforate, wear, weather",
"точить зуб" : "have a grudge against",
"точка" : "point, dot, gr. period full stop, высшая точка zenith climax, точка с запятой gr. semicolon, точка! famil. enough!, a. точь",
"точка зрения" : "point of view standpoint angle",
"точно" : "adv. #of точный, a. = словно, indeed, так точно! milit. yes sir!",
"точность" : "accuracy exactness precision, в точности s. точно",
"точный" : "exact precise accurate, punctual, precision",
"точь в точь" : "famil. exactly",
"тошнить" : "меня тошнит I feel sick, I loathe",
"тошнота" : "nausea",
"тощий" : "gaunt, lank, lean",
"трава" : "grass, herb",
"травма" : "maim, trauma",
"травник" : "redshank",
"травяной" : "grassy, herbaceous, herbal",
"трагедия" : "tragedy",
"трагик" : "tragedian",
"трагический" : "tragic",
"трагичный" : "tragic",
"традиционный" : "traditional",
"традиция" : "tradition",
"траектория" : "trajectory",
"тракт" : "highway, anat. tract",
"трактат" : "treatise",
"трактир" : "inn tavern famil. pub",
"трактирщик" : "innkeeper",
"трактовать" : "treat",
"трактовка" : "treatment",
"трактор" : "tractor",
"тракторист" : "tractor operator",
"тракторный" : "tractor...",
"трал" : "trawl",
"тральщик" : "trawler, milit. mine sweeper",
"трамбовать" : "ram",
"трамвай" : "streetcar Brt. tramway tram",
"трамплин" : "springboard",
"транзистор" : "transistor",
"транзит" : "transit",
"транзитный" : "transit",
"транс" : "trance",
"трансатлантический" : "transatlantic",
"трансконтинентальный" : "transcontinental",
"транскрибировать" : "pf. transcribe",
"транслировать" : "pf. transmit, relay",
"трансляция" : "transmission",
"транспарант" : "transparency",
"транспорт" : "transport",
"транспортировать" : "pf. transport convey",
"транспортировка" : "hauling, portage",
"транспортный" : "transport",
"трансформатор" : "transformer",
"траншея" : "trench",
"трап" : "gangway",
"трапеция" : "trapeze, math. trapezium",
"трасса" : "route line",
"трата" : "expenditure, expense, waste",
"тратить" : "spend, waste",
"тратта" : "draft",
"траур" : "mourning",
"траурный" : "mourning..., funeral...",
"трафарет" : "cliche'",
"трах" : "crack!",
"трахея" : "trachea",
"требование" : "claim, demand, requisition",
"требовательный" : "demanding, exigent",
"требуемый" : "requisite",
"тревога" : "alarm",
"тревожить" : "harass",
"трезвон" : "peal",
"трезвость" : "sobriety",
"трезвый" : "sober",
"трезубец" : "trident",
"трель" : "mordent, trill, warble",
"трение" : "attrition, friction, rub, rubbing",
"тренировать" : "practise",
"тренировка" : "training, workout",
"трепет" : "tremor quiver",
"трепетание" : "flutter",
"трепетать" : "tremble, quiver shiver, flicker, palpitate",
"трепетный" : "quivering, flickering",
"треск" : "crack crash",
"треска" : "cod",
"трескаться" : "burst, crack split, chap",
"трескотня" : "crackle, rattle, chirp, gabble",
"трескучий" : "hard ringing, fig. bombastic",
"треснуть" : "burst, crack split, chap",
"трест" : "trust",
"третейский" : "of arbitration",
"третий" : "third, третьего дня = позавчера, cf. пятый",
"третий с конца" : "last but two",
"третировать" : "treat",
"третичный" : "tertiary",
"треть" : "third",
"треугольник" : "triangle",
"треугольный" : "triangular, three-cornered",
"трефы" : "clubs",
"трехгодичный" : "three years', triennial",
"трехгранный" : "trihedral, triquetrous",
"трехдневный" : "three days'",
"трехколесный" : "three-wheeled",
"трехлетие" : "triennial",
"трехлетний" : "three-years'",
"трехногий" : "tripod",
"трехсотый" : "three hundredth",
"трехцветный" : "three-color, tricolor",
"трехэтажный" : "three-storied",
"трещать" : "затрещать crack, протрещать crackle, rattle, chirp, famil. prattle, треснуть burst",
"трещина" : "split  crack cleft crevice fissure, chap",
"трещотка" : "rattle, famil. chatterbox",
"три" : "three, cf. пять",
"триада" : "triad",
"трибуна" : "tribune platform, stand",
"трибунал" : "tribunal",
"тривиальный" : "trivial",
"тригонометрия" : "trigonometry",
"тридцатый" : "thirtieth, cf. пятидесятый",
"тридцать" : "thirty",
"триединый" : "triune",
"трижды" : "three times thrice",
"трико" : "tights pl.",
"трикотаж" : "hosiery, jersey",
"триктрак" : "backgammon",
"триллион" : "trillion",
"трилогия" : "trilogy",
"триместр" : "trimester",
"тринадцатый" : "thirteenth, cf. пятый",
"тринадцать" : "thirteen, cf. пять",
"трио" : "trio",
"триста" : "three hundred",
"тритон" : "newt, triton",
"триумф" : "triumph",
"триумфальный" : "triumphal, triumphant",
"трогательный" : "touching moving",
"трогать" : "touch, famil. pester, трогай! go!",
"трогаться" : "start, set out, move, be touched",
"троглодит" : "troglodyte",
"трое" : "three",
"троекратный" : "repeated three times",
"троица" : "Trinity, Whitsunday",
"тройка" : "three, troika, triumvirate, cf.",
"тройник" : "tee",
"тройной" : "threefold triple treble",
"тройня" : "triplets pl.",
"тройственный" : "tripartite",
"троллейбус" : "trolley bus",
"тромб" : "thrombus",
"тромбоз" : "thrombosis",
"тромбон" : "trombone",
"трон" : "throne",
"тронный" : "Brt. King's",
"тронуть" : "touch, famil. pester, трогай! go!",
"тропа" : "path track",
"тропинка" : "path",
"тропический" : "tropic",
"трос" : "hawser cable",
"тростник" : "reed, cane",
"тростниковый" : "reed..., cane...",
"тросточка" : "cane a. walking stick",
"трость" : "cane a. walking stick",
"тротуар" : "sidewalk Brt. pavement footpath footway",
"трофеи" : "booty",
"трофей" : "trophy",
"трофейный" : "trophy",
"трохей" : "trochee",
"троюродный" : "second",
"троякий" : "threefold triple",
"троянский" : "trojan",
"труба" : "pipe tube, chimney, nav. smokestack funnel, engine, mus. trumpet",
"трубач" : "trumpeter",
"трубить" : "blow",
"трубка" : "tube, pipe, teleph. receiver, roll"
};
