var dicctr_84 = {
"спорить" : "dispute argue debate, quarrel, famil. bet, poet. fight",
"спориться" : "succeed get along",
"спорный" : "disputable questionable",
"спорный вопрос" : "point at issue",
"спорт" : "sport; See also: лыжный спорт",
"спортивный" : "sporting athletic, sport...",
"спортсмен" : "sportsman",
"спортсменка" : "sportswoman",
"спору нет" : "no doubt",
"способ" : "method means, manner way, directions pl.",
"способность" : "ability  talent, faculty, capacity, power, quality",
"способный" : "able talented clever, capable",
"способствовать" : "promote further contribute to",
"способствующий" : "conducive, contributory",
"споткнуться" : "stumble",
"спотыкаться" : "stumble",
"спохватиться" : "bethink o.s.",
"спохватываться" : "bethink o.s.",
"справа" : "on to the right",
"справедливость" : "justice, truth; See also: по справедливости",
"справедливый" : "just fair, true right",
"справить" : "s. справлять",
"справка" : "enquiry, inquiry, reference",
"справочник" : "catalogue, enchiridion",
"справочный" : "information inquiry, reference...",
"спрашивается" : "one may ask",
"спрашивать" : "ask  inquire, demand, be taken to account",
"спрашиваться" : "s. проситься",
"спринт" : "sprint",
"спроектировать" : "project plan",
"спрос" : "demand, без спроса #or спросу famil. without permission",
"спросить" : "ask  inquire, demand, be taken to account",
"спросонок" : "famil. half asleep",
"спроста" : "famil. unintentionally innocently",
"спрыгивать" : "jump down",
"спрыгнуть" : "jump down",
"спрыскивать" : "sprinkle, famil. wet",
"спрыснуть" : "sprinkle, famil. wet",
"спрягать" : "gr. conjugate",
"спряжение" : "gr. conjugation",
"спрясть" : "spin",
"спрятать" : "hide  conceal",
"спугивать" : "shoo",
"спуск" : "lowering, descent, slope, launch, drain, famil. quarter",
"спускать" : "lower let down, launch, drain, unchain set free, pull, slacken, famil. pardon, lose gamble away",
"спускаться" : "go down descend, slip down sink",
"спускающийся" : "descending, downward",
"спустить" : "lower let down, launch, drain, unchain set free, pull, slacken, famil. pardon, lose gamble away",
"спуститься" : "go down descend, slip down sink",
"спустя" : "later after",
"спутать" : "confuse muddle, mix up entangle",
"спутник" : "fellow traveler, companion",
"спутница" : "fellow traveler, companion",
"спутывать" : "confuse",
"спячка" : "hibernation, sleep",
"спящий" : "asleep, sleeper",
"ср" : "cf.",
"сравнение" : "compare, comparison, simile",
"сравнивать" : "collate",
"сравнительный" : "comparative",
"сражаться" : "fought",
"сражение" : "battle",
"сраженный" : "smitten",
"сразить" : "smite, overwhelm, overtake",
"сразу" : "at once, at one stroke",
"срам" : "shame disgrace",
"срамить" : "disgrace shame compromise",
"срамиться" : "bring shame upon o.s.",
"срастаться" : "grow together knit",
"срастись" : "grow together knit",
"среда" : "Wednesday, environment surroundings pl. sphere, medium, midst",
"среди" : "among, in the middle  amid",
"средиземноморский" : "Mediterranean",
"средиземный" : "Mediterranean",
"средина" : "mid",
"средневековый" : "medieval",
"средний" : "middle, medium..., central, middling, average..., math. mean, gr. neuter, secondary",
"средоточие" : "center",
"средства" : "specifics",
"средство" : "means, remedy, chem. agent, a. facilities",
"средь бела дня" : "in broad day-light",
"срезать" : "cut off, famil. cut short, fail",
"срезывать" : "cut off, famil. cut short, fail",
"сровнять" : "s. сравнивать",
"сродный" : "related cognate",
"сродство" : "affinity",
"срок" : "term  date deadline, time  period",
"срочный" : "urgent pressing, timed",
"сруб" : "blockhouse",
"срубать" : "cut down fell, carpenter build",
"срубить" : "cut down fell, carpenter build",
"срыв" : "frustration, failure breakdown, breaking up",
"срывать" : "сорвать tear off, pluck pick, famil. break up disrupt frustrate, vent, -ся come off, break away, fall down, famil. dart off, escape, fail go wrong, срыть level raze to the ground",
"ссадина" : "graze abrasion",
"ссадить" : "pf. graze, make alight, drop",
"ссора" : "quarrel, altercation, variance",
"ссориться" : "quarrel fall out",
"ссср" : ", U.S.S.R.",
"ссуда" : "loan",
"ссудить" : "pf. lend",
"ссудный" : "loan...",
"ссылать" : "exile banish",
"ссылаться" : "refer to cite",
"ссылка" : "exile, deportation, reference",
"ссыльный" : "exiled",
"ссыпать" : "pour sack",
"ст" : "abbr.:, столетие, станция, старший",
"стабиль" : "stabile",
"ставка" : "rate, stake",
"стадион" : "stadium",
"стадо" : "drove, gaggle, herd",
"сталкивать" : "push",
"сталкиваться" : "collide run into, come across",
"сталь" : "steel",
"стальной" : "steel...",
"стамбул" : "istanbul",
"стамеска" : "chisel",
"стан" : "figure, camp, engin. mill",
"стандарт" : "standard",
"стандартный" : "standard..., prefabricated",
"станица" : "Cossack village",
"становиться" : "stand, become grow get, step place o.s. get stop, pf. begin, will, feel; See also: стать в очередь, во что бы то ни стало",
"станок" : "machine, lathe, press, bench; See also: ткацкий станок",
"станцевать" : "dance",
"станционный" : "station..., waiting, post",
"станция" : "station, teleph. office exchange, a. yard; See also: узловая станция",
"стаптывать" : "tread down, wear out",
"старание" : "pains pl. care, endeavor trouble",
"старательный" : "assiduous diligent, careful",
"стараться" : "endeavor try, strive",
"старая дева" : "old maid",
"старейший" : "eldest",
"стареть" : "постареть grow old age, устареть grow obsolete",
"старец" : "monk, старик",
"старик" : "old man",
"старина" : "olden time #or days, famil. old man",
"старинный" : "ancient antique, old, longstanding",
"старить" : "make old",
"старомодный" : "old-fashioned out-of-date",
"староста" : "elder, warden, monitor",
"старость" : "old age",
"стартовать" : "pf. start",
"старуха" : "old woman",
"старческий" : "senile",
"старший" : "elder older senior, eldest oldest, higher highest, fore, first",
"старшина" : "foreman, chairman manager, milit. first sergeant",
"старшинство" : "seniority",
"старый" : "old, ancient antique, olden",
"старье" : "second-hand articles pl., junk Brt. lumber",
"стаскивать" : "pull, take bring",
"стасовать" : "shuffle",
"статист" : "thea. supernumerary, #film: extra",
"статистик" : "statistician",
"статистика" : "statistics",
"статистический" : "statistical",
"статистка" : "thea. supernumerary, #film: extra",
"статический" : "static",
"статный" : "stately portly",
"статус" : "status",
"статуэтка" : "figurine, statuette",
"статуя" : "statue",
"стать" : "stand, become grow get, step place o.s. get stop, pf. begin, will, feel; See also: стать в очередь, во что бы то ни стало",
"стать в очередь" : "line Brt. queue up",
"стать в тупик" : "be at one's wit's end",
"стать1" : "build, trait, famil. need seemly, с какой стати? famil. why",
"стать2" : "s. становиться",
"статься" : "famil. happen, be",
"статья" : "article, item entry, famil. matter business",
"стахановец" : "Stakhanovite",
"стационарный" : "stationary",
"стачать" : "seam sew",
"стачка" : "strike",
"стащить" : "pull, take bring",
"стая" : "flight flock, shoal, pack troop",
"стаять" : "pf. thaw off melt",
"ствол" : "trunk, barrel",
"створчатый" : "folding",
"стебель" : "stalk stem",
"стеганый" : "quilted",
"стегать" : "выстегать простегать quilt, once стегнуть whip",
"стежок" : "stitch",
"стекать" : "flow",
"стекаться" : "join, flock gather",
"стекло" : "glass, pane, chimney",
"стекловидный" : "vitreous",
"стеклянный" : "glass..., glassy",
"стекольщик" : "glazier",
"стелить" : "s. стлать",
"стеллаж" : "hotbed",
"стельная корова" : "cow with calf",
"стена" : "wall",
"стенгазета" : "wall newspaper",
"стенка" : "wall",
"стенной" : "wall...",
"стенограмма" : "shorthand report #or notes pl.",
"стенографист" : "stenographer",
"стенографистка" : "stenographer",
"стенография" : "shorthand",
"степан" : "Stephen",
"степенный" : "sedate staid grave dignified, mature",
"степень" : "degree  extent, math. power",
"степной" : "steppe...",
"степь" : "steppe",
"стерва" : "damned wretch",
"стерео" : "stereo",
"стереография" : "stereography",
"стереотипный" : "stereotyped",
"стереть" : "s. стирать",
"стеречь" : "guard watch",
"стержень" : "core, pivot",
"стерилизовать" : "pf. sterilize",
"стерильный" : "sterile",
"стерпеть" : "pf. endure bear",
"стеснение" : "constraint restraint",
"стесненный" : "cabined, straitened, stringent",
"стеснительный" : "constraining embarrassing",
"стеснить" : "constrain restrain, embarrass hamper, cramp, trouble press",
"стеснять" : "constrain restrain, embarrass hamper, cramp, trouble press",
"стесняться" : "feel shy self-conscious #or embarrassed, be ashamed of, hesitate",
"стетоскоп" : "stethoscope",
"стечение" : "confluence, coincidence",
"стечь" : "flow",
"стигматы" : "stigmata",
"стиль" : "style, Style",
"стимул" : "inducement, stimulus",
"стимулировать" : "propel",
"стипендия" : "scholarship",
"стиральный" : "washing",
"стирать" : "стереть, wipe #or rub off out, erase efface blot out, clean, pulverize, выстирать wash launder",
"стирка" : "wash laundry; See also: отдать в стирку",
"стискивать" : "clench, grasp press",
"стиснуть" : "clench, grasp press",
"стих" : "verse, a. poem",
"стихарь" : "alb, surplice",
"стихать" : "abate, fall, cease, calm down quiet",
"стихи" : "verse, a. poem",
"стихийный" : "elemental, spontaneous, natural",
"стихия" : "element",
"стихнуть" : "abate, fall, cease, calm down quiet",
"стихотворение" : "poem",
"стлать" : "spread lay, make",
"стлаться" : "impf. spread, drift, bot. creep",
"сто" : "hundred",
"стог" : "stack rick",
"стоимость" : "cost, value worth",
"стоить" : "cost, be worth, pay, take require, need if, matter, не стоит famil. = не за что",
"стоический" : "stoic, stoical",
"стой" : "stop! halt!",
"стойка" : "rack, stanchion, stilt",
"стойкий" : "steadfast, sturdy"
};
