var dicctr_42 = {
"мука1" : "pain torment suffering torture, famil. harassment",
"мука2" : "flour, meal",
"мул" : "mule",
"мулла" : "moolah, mullah",
"мультфильм" : "cartoon",
"мульча" : "mulch",
"мумия" : "mummy",
"мундир" : "uniform, картошка в мундире famil., potatoes in their jackets #or skin",
"мундштук" : "cigarette holder, tip, mouthpiece",
"мундштучный" : "curb",
"мурава" : "grass, glaze",
"муравей" : "ant",
"муравейник" : "ant hill",
"муравьед" : "anteater",
"муравьинокислый" : "formic",
"муравьиный" : "ant...",
"мурашки" : "~ бегают по спине, famil. gives the shivers",
"мурлыканье" : "purr",
"мурлыкать" : "croon",
"мускат" : "muscat, muscatel",
"мускулатура" : "musculature",
"мускулистый" : "brawny, muscular, sinewy",
"мускус" : "musk",
"муслин" : "muslin",
"мусон" : "monsoon",
"мусор" : "garbage, rubbish, sweepings",
"мустанг" : "mustang",
"мусульманин" : "muslim, turk",
"мусульманский" : "moslem, mussulman",
"мутировать" : "mutate",
"мутный" : "feculent, roily, turbid",
"мутовка" : "twirling stick",
"муть" : "dregs pl., mud, blur, haze, dazzle",
"муфта" : "muff, engin. socket sleeve",
"муха" : "fly",
"мухоловка" : "flycatcher",
"мухомор" : "toadstool",
"мучать" : "torment torture, vex worry",
"мучение" : "s. мука",
"мученик" : "martyr",
"мучитель" : "tormentor",
"мучительный" : "painful agonizing",
"мучить" : "torment torture, vex worry",
"мучиться" : "agonize suffer torments, toil",
"мучной" : "flour mealy",
"мушка" : "midge, beauty spot, speck, fly, sight",
"мушкет" : "musket",
"муштра" : "drill",
"муэдзин" : "muezzin",
"мшистый" : "mossy",
"мы" : "ourself, we",
"мы с ним" : "he and I",
"мылить" : "soap; See also: мылить голову",
"мылить голову" : "famil. blow up scold",
"мыло" : "soap, lather",
"мыловарение" : "soap boiling",
"мыльница" : "soap dish",
"мыльный" : "soap",
"мыс" : "cape",
"мысленный" : "mental",
"мысли" : "unbosom o.s., #anger: vent ... on",
"мыслимый" : "conceivable",
"мыслитель" : "thinker",
"мыслить" : "think, imagine",
"мысль" : "thought idea, intention",
"мытарство" : "toil drudgery",
"мыть" : "wash",
"мычание" : "bellow, moo, mooing",
"мышка" : "armpit, arm, dim. #of мышь",
"мышление" : "thought thinking",
"мышца" : "muscle",
"мышь" : "mouse",
"мышьяк" : "arsenic",
"мэр" : "mayor",
"мюнхен" : "munich",
"мягкий" : "soft, smooth sleek, tender, mild gentle, lenient, easy",
"мягкий вагон" : "rail. first-class coach #or car",
"мягкосердечный" : "soft-hearted",
"мягкость" : "softness",
"мягкотелый" : "chubby, fig. fladdy spineless",
"мягчительный" : "lenitive",
"мягчить" : "soften",
"мякина" : "chaff",
"мякиш" : "crumb",
"мякнуть" : "become soft",
"мякоть" : "flesh pulp",
"мямлить" : "mumble, dawdle",
"мясистый" : "fleshy pulpy, famil. fat chubby",
"мясник" : "butcher",
"мясной" : "meat..., butcher's",
"мясо" : "meat, flesh pulp, fodder",
"мясорубка" : "mincing machine, fig. slaughter",
"мята" : "mint",
"мятеж" : "rebellion mutiny",
"мятежник" : "rebel",
"мятежный" : "rebellious",
"мять" : "rumple press, knead wrinkle, trample",
"мяться" : "famil. waver",
"мяукать" : "mew",
"мяукнуть" : "mew",
"мяч" : "ball",
"мячик" : "dim. #of мяч",
"на" : "onto, upon",
"на авось" : "at random",
"на бегу" : "while running, s. бегом",
"на бок" : "sideways",
"на борту судна" : "on board a ship",
"на вес" : "by weight",
"на взгляд" : "in appearance by sight",
"на виду" : "in sight, visible",
"на восток" : "east eastward",
"на востоке" : "in the east",
"на время" : "for a time temporarily, in run",
"на всякий случай" : "to be on the safe side",
"на выбор" : "at a pers.'s discretion, random",
"на выдержку" : "at random",
"на глаз" : "approximately by eye",
"на глазах" : "in s.b.'s presence sight",
"на глазомер" : "estimate by the eye, eye",
"на даче" : "out of town in the country",
"на дворе" : "outside outdoors",
"на днях" : "the other day, one of these days",
"на заказ" : "made to order",
"на замке" : "under lock & key",
"на заработки" : "in search of a job, ... to hire o.s. out",
"на заре" : "at dawn daybreak, fig. at the earliest stage #or beginning",
"на иждивении" : "at s.b.'s expense depend on",
"на имя" : "addressed to for",
"на кой черт" : "a. the deuce",
"на людях" : "in public",
"на мели" : "aground, famil. in a fix",
"на меху" : "fur-lined",
"на мой взгляд" : "in my opinion",
"на несчастье" : "unfortunately",
"на одну доску" : "on a level",
"на очереди" : "next",
"на ощупь" : "to the touch",
"на память" : "a. by heart",
"на первый взгляд" : "at first sight",
"на первых порах" : "at first in the beginning",
"на поводу" : "in leading strings",
"на посту" : "milit. #stand sentinel, fast",
"на предмет" : "for the purpose of",
"на свою голову" : "famil. to one's own harm",
"на скорую руку" : "famil. in haste offhand anyhow",
"на славу" : "famil. first-rate A-one",
"на словах" : "by word of mouth orally",
"на сон грядущий" : "for a nightcap",
"на сторону" : "abroad",
"на худой конец" : "at worst",
"на часах" : "sentinel",
"на черный день" : "for a rainy day",
"на что" : "what for?, :, on upon, in at, with, for, на ней ... she has ... on",
"набат" : "tocsin",
"набег" : "foray, raid",
"набережная" : "quay",
"набивать" : "tamp",
"набивка" : "gasket, stuffing, wadding",
"набирать" : "gather, enlist recruit, teleph. dial, typ. set, take, gain, be have, -ся a. pluck #or screw up, famil. catch, acquire",
"набитый" : "packed, popul. arrant; See also: битком набитый",
"набить" : "stuff fill, fix on, shoot, print",
"наблюдатель" : "observer",
"наблюдательный" : "observant alert, observation",
"наблюдать" : "observe, watch, see after #or to",
"наблюдение" : "observation, supervision",
"набожность" : "unction",
"набожный" : "pious devout",
"набок" : "to #or on one side",
"наболевший" : "sore, burning",
"набор" : "enlistment levy, enrolment, set, typesetting, taking",
"наборщик" : "typesetter compositor",
"набрасывать" : "набросать sketch design draft, throw, набросить throw over on, -ся fall on",
"набрать" : "gather, enlist recruit, teleph. dial, typ. set, take, gain, be have, -ся a. pluck #or screw up, famil. catch, acquire",
"набрести" : "pf. come across",
"набросок" : "sketch draft",
"набухать" : "swell",
"набухнуть" : "swell",
"наваливать" : "heap, load, -ся press, fall on go at",
"навалить" : "heap, load, -ся press, fall on go at",
"наведаться" : "call on, inquire after about",
"наведываться" : "call on, inquire after about",
"навек" : "forever for good",
"навеки" : "forever for good",
"навербовать" : "enlist recruit, engage hire",
"наверно" : "probably, for certain definitely, without fail",
"наверху" : "aloft",
"навес" : "canopy, shed",
"наветренный" : "windward",
"навечно" : "forever for good",
"навещать" : "call on",
"навзничь" : "on one's back",
"навзрыд" : "плакать навзрыд",
"нависший" : "beetle, beetling",
"наводнение" : "deluge, flood, spate",
"наводнять" : "inundate",
"навоз" : "dung, manure, muck, ordure",
"навозный" : "dung...; See also: навозная жижа",
"наволочка" : "pillowcase",
"навострить" : "pf. prick up",
"навощить" : "wax",
"навряд" : "famil. hardly scarcely",
"навсегда" : "forever, for all",
"навстречу" : "toward; See also: идти навстречу",
"навыворот" : "popul. topsy-turvy inside out wrongly, делать шиворот-навыворот put the cart before the horse",
"навык" : "experience skill, habit",
"навыкат" : "goggle",
"навязчивый" : "obsessive",
"навязывание" : "imposition",
"навязывать" : "impose, obtrude",
"нагибать" : "bend bow stoop",
"нагишом" : "famil. naked nude",
"наглазник" : "blinder",
"наглец" : "impudent fellow",
"наглость" : "impudence insolence",
"наглухо" : "tightly",
"наглый" : "impudent insolent famil. cheeky",
"наглядеться" : "pf. feast one's eyes; See also: не наглядеться",
"наглядный" : "vivid graphic, obvious, direct, object, visual",
"нагнать" : "s. нагонять",
"нагнести" : "pump",
"нагнетательный" : "force",
"нагнетать" : "pump",
"нагноение" : "suppuration",
"нагнуть" : "bend bow stoop",
"наговаривать" : "say tell talk, famil. slander, conjure, record",
"наговорить" : "say tell talk, famil. slander, conjure, record",
"наговориться" : "pf. talk one's fill; See also: не наговориться",
"нагой" : "nude naked bare",
"наголо" : "clean",
"наголову" : "totally",
"нагоняй" : "blowup",
"нагонять" : "overtake catch up, make up, drive, etc. frighten bore etc.",
"нагорный" : "upland",
"нагородить" : "talk nonsense",
"нагота" : "nudity, bareness",
"наготавливать" : "prepare, lay in",
"наготове" : "ready",
"наготовить" : "prepare, lay in",
"награбить" : "pf. rob plunder",
"награда" : "reward  recompense, decoration",
"наградить" : "reward, decorate, fig. endow",
"награждать" : "reward, decorate, fig. endow",
"нагревательный" : "heating",
"нагревать" : "s. греть",
"нагреть" : "warm, heat; See also: греться на солнце",
"нагримировать" : "make up",
"нагромождать" : "pile up",
"нагромоздить" : "pile up",
"нагрубить" : "say rude things",
"нагрудник" : "bib, plastron"
};
