var dicctr_98 = {
"экспедиционный" : "forwarding..., expedition...",
"экспедиция" : "dispatch, forwarding agency, expedition",
"экспериментальный" : "experimental",
"экспериментирование" : "experimentation",
"эксперт" : "expert",
"экспертиза" : "examination, opinion",
"эксплуататор" : "exploiter",
"эксплуатация" : "exploitation, engin. operation",
"эксплуатировать" : "exploit, sweat, engin. operate run",
"экспонат" : "exhibit",
"экспонировать" : "pf. exhibit, phot. expose",
"экспорт" : "pf. export",
"экспортирование" : "exportation",
"экспортировать" : "pf. export",
"экспортный" : "export...",
"экспромт" : "impromptu",
"экспромтом" : "a. extempore",
"экспроприировать" : "expropriate",
"экстаз" : "ecstasy",
"экстраверт" : "extrovert",
"экстракт" : "extract",
"экстраполировать" : "extrapolate",
"экстренный" : "special, extra, urgent",
"эксцентричный" : "eccentric",
"эластичность" : "elasticity",
"эластичный" : "elastic",
"элегантность" : "elegance",
"элегантный" : "elegant stylish",
"элегия" : "elegy",
"электрик" : "electrician",
"электрифицировать" : "pf. electrify",
"электрическая грелка" : "heating pad",
"электрический" : "electric",
"электричество" : "electricity",
"электровоз" : "electric locomotive",
"электрод" : "electrode",
"электролиз" : "electrolysis",
"электролит" : "electrolyte",
"электролитический" : "electrolytic",
"электромонтер" : "s. электрик",
"электрон" : "electron",
"электронный" : "electron, electronic",
"электростанция" : "power station",
"электротехник" : "electrical engineer",
"электротехника" : "electrical engineering",
"элемент" : "element",
"элементарный" : "elementary",
"элизия" : "elision",
"элита" : "elite, jet set",
"эллипсис" : "ellipsis",
"эллипсоид" : "ellipsoid",
"эмалевый" : "enamel",
"эмалировать" : "enamel",
"эмаль" : "enamel",
"эмблема" : "emblem",
"эмблематический" : "emblematic",
"эмигрант" : "emigrant, emigre",
"эмигрантка" : "emigrant, emigre",
"эмигрантский" : "emigrant, emigre",
"эмигрировать" : "pf. emigrate",
"эмоциональный" : "emotional",
"эмпиризм" : "empiricism",
"эмпирический" : "empiric, empirical",
"энергичный" : "energetic, drastic",
"энергия" : "energy",
"энтузиазм" : "enthusiasm",
"энтузиаст" : "enthusiast",
"энцефацит" : "encephalitis",
"энциклопедический" : "encyclopedic",
"энциклопедический словарь" : "encyclopedia",
"энциклопедия" : "encyclopedia",
"эпиграмма" : "epigram",
"эпиграмматический" : "epigrammatic",
"эпиграф" : "epigraph",
"эпидемический" : "epidemic",
"эпидемия" : "epidemic",
"эпизод" : "episode",
"эпизодический" : "episodic",
"эпилепсия" : "epilepsy",
"эпилептический" : "epileptic",
"эпилог" : "epilogue",
"эпитет" : "epithet",
"эпический" : "epic",
"эполет" : "epaulet, epaulette",
"эпос" : "epic  epos",
"эпоха" : "epoch era period",
"эпохальный" : "epochal",
"эра" : "era",
"эрдель-терьер" : "airedale",
"эрозийный" : "erosive",
"эротический" : "erotic",
"эрстед" : "oersted",
"эрудированный" : "erudite",
"эскадра" : "nav. squadron",
"эскадренный миноносец" : "destroyer",
"эскадрилья" : "av. squadron",
"эскадрон" : "squadron",
"эскалатор" : "escalator",
"эскапада" : "escapade",
"эскиз" : "sketch",
"эскимос" : "Eskimo",
"эскимосский" : "eskimo",
"эскортировать" : "escort",
"эсминец" : "nav. destroyer",
"эссенция" : "essence",
"эстакада" : "overpass, trestle",
"эстафета" : "relay race",
"эстафетный бег" : "relay race",
"эстет" : "aesthete",
"эстетический" : "aesthetic",
"эстонец" : "Estonian",
"эстонка" : "Estonian",
"эстонский" : "Estonian",
"эстрада" : "platform, s. варьете",
"эта" : "this pl. these, su. this one, that, it, there, это a. well then as a matter of fact",
"этаж" : "floor story, дом в три этажа three-storied house",
"этажерка" : "whatnot, bookshelf",
"этак" : "s. так",
"эти" : "these",
"этикет" : "etiquette",
"этил" : "ethyl",
"этилат" : "ethylate",
"этичный" : "ethic, ethical",
"этнический" : "ethnic, ethnical",
"этнография" : "ethnography",
"этнология" : "ethnology",
"этот" : "this",
"этюд" : "etude",
"эфес" : "hilt",
"эфиопия" : "ethiopia",
"эфир" : "ether",
"эфирный" : "ethereal",
"эффективность" : "officacy",
"эффективный" : "efficacious",
"эффектный" : "effective",
"эх" : "ah!",
"эхо" : "echo",
"эшафот" : "scaffold",
"эшелон" : "echelon, troop train",
"юбилей" : "jubilee",
"юбилейный" : "jubilee...",
"юбиляр" : "pers. celebrating his jubilee",
"юбка" : "skirt",
"ювелир" : "jeweller",
"ювелирный" : "jeweller'",
"юг" : "south, ехать на ~ travel south, cf. восток",
"юго-восток" : "southeast",
"юго-восточный" : "southeast ...",
"юго-запад" : "southwest",
"юго-западный" : "southwest ...",
"югославия" : "Yugoslavia",
"югославский" : "yugoslav",
"югурт" : "yogurt",
"южно-африканский союз" : "Union of South Africa",
"южный" : "south, southerly",
"юла" : "humming top, pers.",
"юмор" : "humor",
"юмористический" : "humorous, comic",
"юнга" : "cabin boy",
"юнона" : "juno",
"юность" : "youth",
"юноша" : "youth",
"юношеский" : "adolescent, teenage",
"юношество" : "youth",
"юный" : "young youthful",
"юпитер" : "jove, jupiter",
"юридический" : "juridical, of law",
"юрий" : "George",
"юрисдикция" : "jurisdiction",
"юрисконсульт" : "legal adviser",
"юрист" : "lawyer, famil. law student",
"юркий" : "nimble quick",
"юркнуть" : "pf. vanish",
"юродивый" : "fool in Christ",
"юрта" : "nomad's tent",
"юстиция" : "justice",
"ютиться" : "nestle, be cooped",
"юфть" : "Russia leather",
"я" : "I, это я it's me",
"ябеда" : "slander talebearing",
"ябедник" : "slanderer informer",
"ябедничать" : "slander",
"яблоко" : "apple, ball",
"яблоня" : "apple tree",
"яванский" : "java, javanese",
"явить" : "s. являть",
"явления" : "phenomena",
"явный" : "apparent, evident, mere, pronounced, sheer",
"ягода" : "berry",
"ягодица" : "buttock",
"ягодицы" : "breech, buttocks, nates, prat",
"ягодный" : "berry",
"ягуар" : "jaguar",
"яд" : "poison, a. venom",
"ядерный" : "nuclear",
"ядовитый" : "poisonous, venomous",
"ядреный" : "strong stalwart solid, pithy, fresh",
"ядро" : "kernel, bot. nucleus, cannon ball, fig. core pith",
"ядрышко" : "nucleolus",
"язва" : "ulcer, plague, wound",
"язвительнось" : "acrimony",
"язвительный" : "venomous, caustic",
"язык" : "tongue, language, speech, на русском языке #speak Russian; See also: держать язык за зубами",
"язык заплетается" : "slur mumble",
"языковед" : "linguist",
"языковой" : "language...",
"языковый" : "tongue...",
"языкознание" : "linguistics",
"языческий" : "pagan",
"язычество" : "paganism",
"язычник" : "pagan",
"язычок" : "uvula, tongue",
"яичко" : "testicle",
"яичник" : "gonad, ootheca, ovary",
"яичница" : "eggs pl.",
"яичный" : "egg...",
"яйцеклетка" : "ovule, ovulum, ovum",
"яйцеобразный" : "oviform",
"яйцо" : "egg",
"яйцо вкрутую" : "hard-boiled egg",
"яйцо всмятку" : "soft-boiled egg",
"як" : "yak",
"якобит" : "jacobite",
"якобы" : "allegedly, as it were",
"яков" : "Jakob",
"якорь" : "anchor, стоять на якоре anchor",
"ялик" : "jolly boat",
"яма" : "hole pit, famil. dungeon",
"ямб" : "iamb",
"ямбический" : "iambic",
"ямка" : "dimple",
"ямочка" : "dimple",
"январский" : "january",
"янки" : "yank",
"янтарь" : "amber",
"янычар" : "janissary, janizary",
"япония" : "japan",
"японский" : "japanese, japonic, nipponese",
"ярд" : "yard",
"яркий" : "bright",
"яркость" : "brightness",
"ярлык" : "label, tag",
"ярмо" : "yoke",
"яровой" : "summer spring",
"яростный" : "furious fierce",
"ярость" : "fury rage",
"ярус" : "circle, layer",
"ярый" : "fierce violent, ardent",
"ясень" : "ash",
"ясли" : "crib manger, day nursery Brt. creche"
};
