var dicctr_52 = {
"олеум" : "oleum",
"оливин" : "olivine",
"оливковый" : "mulatto, olivaceous, olive",
"олигархия" : "oligarchy",
"олимпийский" : "olympian, olympic",
"олицетворять" : "embody, personalize, personify",
"оловянный" : "tin",
"олух" : "blockhead dolt",
"ольха" : "alder",
"ольховый" : "alder",
"ом" : "ohm",
"оман" : "oman",
"омар" : "lobster",
"омега" : "omega",
"омела" : "mistletoe",
"омерзение" : "abhorrence loathing",
"омерзительный" : "abominable detestable loathsome, famil. lousy",
"омертвелый" : "numb, dead",
"омертветь" : "deaden, grow #or turn numb",
"омертвление" : "necrosis",
"омлет" : "omelet",
"омметр" : "ohmmeter",
"омолаживать" : "rejuvenate",
"омоложение" : "rejuvenation",
"омоним" : "ling. homonym",
"омрачать" : "darken sadden",
"омрачить" : "darken sadden",
"омут" : "whirlpool vortex, deep",
"омывать" : "wash",
"омылять" : "saponify",
"омыть" : "wash",
"он" : "he she it they",
"она" : "he she it they",
"онагр" : "onager",
"онежское озеро" : "Lake Onega",
"онемелый" : "numb, famil. dumb",
"онеметь" : "grow dumb numb",
"они" : "he she it they",
"оникс" : "onyx",
"онкология" : "oncology",
"оно" : "he she it they",
"онтогенез" : "ontogenesis, ontogeny",
"онтология" : "ontology",
"онуча" : "s. портянка",
"оон" : "U.N.O.",
"опадать" : "fall, diminish decrease",
"опаздывать" : "be late arrive late, miss",
"опал" : "opal",
"опала" : "disgrace ban",
"опалить" : "singe",
"опалка" : "singeing",
"опаловый" : "opalescent",
"опальный" : "disgraced",
"опалять" : "singe",
"опасаться" : "fear apprehend, beware",
"опасающийся" : "apprehensive",
"опасение" : "fear apprehension anxiety",
"опасливый" : "wary, anxious",
"опасность" : "danger peril jeopardy, risk",
"опасный" : "dangerous",
"опасть" : "fall, diminish decrease",
"опека" : "guardianship tutelage, trusteeship",
"опекаемый" : "ward",
"опекать" : "be guardian to, patronize",
"опекун" : "guardian, trustee",
"опекунство" : "tutelage",
"опекунша" : "guardian, trustee",
"опера" : "opera",
"операнд" : "operand",
"оперативный" : "operative, surgical, executive, milit. front... war...",
"оператор" : "operator",
"операционный" : "operating",
"опередить" : "outstrip",
"опережать" : "outstrip",
"оперение" : "plumage",
"оперетта" : "operetta",
"опереться" : "s. опираться",
"оперившийся" : "fledged",
"оперировать" : "pf. operate",
"опериться" : "fledge",
"оперный" : "opera",
"оперяться" : "fledge",
"опечалить" : "grieve",
"опечатать" : "seal",
"опечатка" : "misprint erratum",
"опечатывать" : "seal",
"опилки" : "sawdust",
"опираться" : "lean  fig. = rest rely",
"описание" : "description",
"описатель" : "declarator, specifier",
"описательный" : "descriptive",
"описать" : "s. описывать",
"описка" : "slip of pen",
"описывать" : "describe, make, distrain, -ся make a slip of the pen",
"опись" : "list inventory, distraint",
"опиум" : "opium",
"оплакать" : "bewail deplore mourn",
"оплакивать" : "bewail deplore mourn",
"оплата" : "pay, settlement",
"оплатить" : "pay, remunerate, settle",
"оплачиваемый" : "paid, stipendiary",
"оплачивать" : "pay, remunerate, settle",
"оплеуха" : "box on the ear",
"оплодотворение" : "fertilization",
"оплодотворенный" : "fertilized, impregnate, impregnated",
"оплодотворить" : "fertilize fecundate",
"оплодотворять" : "fertilize fecundate",
"опломбировать" : "seal",
"оплот" : "bulwark stronghold",
"оплошность" : "blunder",
"оповестить" : "notify, inform a. advise",
"оповещать" : "notify, inform a. advise",
"опоздание" : "delay, s. опаздывать",
"опоздать" : "be late arrive late, miss",
"опознавательный" : "distinctive",
"опознавать" : "identify",
"опознать" : "identify",
"опозорить" : "dishonor disgrace",
"оползень" : "landslide",
"ополчаться" : "rise in arms",
"ополченец" : "militiaman",
"ополчение" : "militia, Territorial Army",
"ополчиться" : "rise in arms",
"опомниться" : "pf. come to #or recover one's senses come round",
"опор" : "во весь опор",
"опора" : "mainstay, pylon",
"опосредствованный" : "mediate",
"опоссум" : "opossum, possum",
"оппозиция" : "stonewall",
"оправдание" : "alibi, justification, justificatory, plea",
"оправданный" : "exonerate",
"оправдательный" : "justificatory, of 'not guilty'",
"оправдательный документ" : "voucher",
"оправдать" : "justify excuse, acquit, -ся a. prove true",
"оправдываемый" : "defensible",
"оправдывать" : "justify excuse, acquit, -ся a. prove true",
"оправдывающий" : "exculpatory",
"оправить" : "put in order, set, -ся recover, put one's dress hair in order",
"оправка" : "arbour, mandrel",
"оправлять" : "put in order, set, -ся recover, put one's dress hair in order",
"опрашивать" : "interrogate question",
"определение" : "determination, definition, designation, jur. decision, gr. attribute",
"определенный" : "definite, fixed, certain positive",
"определить" : "determine, define, designate, appoint fix, -ся take shape, enter enlist",
"определять" : "determine, define, designate, appoint fix, -ся take shape, enter enlist",
"опровергать" : "refute, deny",
"опровергнуть" : "refute, deny",
"опровержение" : "refutation, denial",
"опрокидывание" : "capsize, tumbling",
"опрокидывать" : "overthrow throw",
"опрокинуть" : "overthrow throw",
"опрометчивый" : "rash precipitate",
"опрометью" : "headlong at top speed",
"опрос" : "interrogation inquiry",
"опросить" : "interrogate question",
"опросный лист" : "questionnaire",
"опротестовать" : "protest",
"опрыскать" : "sprinkle",
"опрыскивать" : "sprinkle",
"опрятный" : "tidy",
"оптик" : "optician",
"оптика" : "optics",
"оптимальный" : "optimum",
"оптимизм" : "optimism",
"оптимист" : "optimist",
"оптимистический" : "sanguine",
"оптовый" : "adv. wholesale",
"оптом" : "adv. wholesale",
"оптометрия" : "optometry",
"опубликование" : "publication",
"опубликовать" : "publish",
"опубликовывать" : "s. публиковать",
"опус" : "opus",
"опускать" : "lower, cast down, hang, drop, draw, опустить руки lose heart, -ся sink, fall, go down, fig. come down, p.pt.a. down & out",
"опустелый" : "deserted",
"опустеть" : "become empty #or deserted",
"опустить" : "lower, cast down, hang, drop, draw, опустить руки lose heart, -ся sink, fall, go down, fig. come down, p.pt.a. down & out",
"опустошать" : "devastate",
"опустошение" : "devastation",
"опустошительный" : "devastating",
"опустошить" : "devastate",
"опутать" : "wrap  muffle, fig. entangle",
"опутывать" : "wrap  muffle, fig. entangle",
"опухать" : "swell",
"опухнуть" : "swell",
"опухоль" : "swelling tumor",
"опухший" : "turgid",
"опушка" : "edge border",
"опущение" : "omission",
"опылить" : "pollinate",
"опылять" : "pollinate",
"опыт" : "experiment, attempt, essay, experience",
"опытный" : "experiment, empirical, experienced",
"опьянение" : "intoxication",
"опьянеть" : "get drunk",
"опьяняющий" : "intoxicant",
"опять" : "again",
"орава" : "gang horde mob",
"оракул" : "oracle",
"орангутанг" : "orangoutang, orangutan",
"оранжевый" : "orange...",
"оранжерея" : "greenhouse",
"оратория" : "oratorio",
"ораторский" : "declamatory, oratorical",
"орать" : "yell bawl",
"орбита" : "orbit",
"оргазм" : "orgasm",
"орган" : "organ",
"орган1" : "organ",
"орган2" : "organ",
"организатор" : "organizer",
"организация" : "setup",
"организация обьединенных наций" : "U.N.O.",
"организм" : "organism, constitution",
"организовать" : "organize",
"организовывать" : "organize",
"органический" : "organic",
"оргия" : "orgy",
"орда" : "horde",
"орден" : "order decoration",
"ордер" : "warrant",
"ординарец" : "orderly",
"ордината" : "ordinate",
"ореада" : "oread",
"орел" : "eagle; See also: орел или решка{?}",
"орел или решка" : "heads or tails?",
"орех" : "nut",
"ориноко" : "orinoco",
"оркестр" : "orchestra",
"орлиный" : "aquiline",
"орнамент" : "decor, ornament",
"оробеть" : "be timid quail, не робей! courage!",
"орография" : "orography",
"оросить" : "irrigate",
"орошать" : "irrigate",
"орошение" : "irrigation",
"ортодоксальный" : "orthodox",
"ортопедический" : "orthopedic",
"орудие" : "tool instrument implement, milit. gun",
"орудийный" : "gun...",
"орудовать" : "handle operate",
"оружейная палата" : "armory",
"оружейный" : "arms...",
"оружие" : "weapon arm, steel",
"орфей" : "orpheus",
"орфографический" : "orthographic",
"орфография" : "spelling",
"орхидея" : "orchid",
"оса" : "wasp",
"осада" : "siege"
};
