var dicct_40 = {
"harpoon" : "гарпун острога",
"harpsichord" : "клавесин",
"harpy" : "гарпия",
"harrow" : " борона, [вз]боронить, [из]мучить [ис]терзать",
"harry" : "разорять [-рить] опустошать [-шить]",
"harsh" : "резкий, жесткий, строгий суровый, терпкий",
"hart" : "олень",
"harvest" : "жатва уборка  сбор, урожай, собирать урожай",
"has" : "P. от have",
"hash" : "рубленое мясо, путаница, [по]рубить [по]крошить",
"hashish" : "гашиш",
"hasp" : "засов",
"hassle" : "перебранка",
"hast" : "(полная форма)(редуцированные формы)  уст. 2-е л. ед. ч. настоящего времени гл. to have",
"haste" : "поспешность; See also: make haste",
"hasten" : "[по]торопить",
"hasty" : "поспешный, вспыльчивый, необдуманный",
"hat" : "шляпа",
"hatch" : "выводок, люк, высиживать [высидеть], вылупляться из яйца",
"hatchet" : "топорик",
"hatchway" : "люк",
"hate" : "ненависть, ненавидеть",
"hateful" : "ненавистный",
"hath" : "(полная форма)(редуцированные формы)  уст. = has",
"hatred" : "ненависть",
"haughtiness" : "надменность  высокомерие",
"haughty" : "надменный высокомерный",
"haul" : "перевозка, тяга, [по]тянуть, таскать [по]тащить, перевозить [-везти]",
"haulage" : "перевозка",
"haunch" : "бедро ляжка, задняя нога",
"haunt" : "появляться [-виться] в, часто посещать, любимое место, притон",
"haunted" : "house дом с привидением",
"havana" : "гаванская сигара",
"have" : "иметь, вспомогательный глагол, для образования перфектной формы:; See also: I have to do, have one's hair cut, he will have it that, I had better go, I had rather go, have about one, I have come",
"have a bee in one's bonnet" : "быть с причудой",
"have a close shave" : "едва избежать опасности",
"have a coat on" : "быть в пальто",
"have a go at" : "[по]пробовать",
"have a look at a ЗthЗ" : "посмотреть на, ознакомляться [-комиться] с",
"have a mind to" : "иметь желание",
"have a run of 20 nights" : "идти двадцать вечеров подряд",
"have a shave" : "[по]бриться",
"have a shot" : "сделать попытку",
"have a smoke" : "покурить",
"have a sweet tooth" : "быть сластеной",
"have a ЗthЗ on one's mind" : "беспокоиться о чем-либо",
"have about one" : "иметь при себе",
"have at command" : "иметь в своем распоряжении",
"have company" : "иметь гостей",
"have done reading" : "кончить читать",
"have in view" : "иметь в виду",
"have no business to " : "не иметь права",
"have one's fling" : "[по]веселиться",
"have one's hair cut" : "стричься",
"have one's way" : "добиваться своего, настаивать на своем",
"have recourse to" : "прибегать к помощи",
"have the floor" : "взять слово",
"haven" : "гавань, убежище",
"havoc" : "опустошение",
"haw" : "бормотание",
"hawaiian" : "Islands геогр. Гавайские острова",
"hawk" : "ястреб, торговать вразнос",
"hawthorn" : "боярышник",
"hay" : "сено; See also: hay fever, haycock, haystack, hayloft",
"hay fever" : "сенная лихорадка",
"haycock" : "копна сена",
"hayloft" : "сеновал",
"hays" : "See: hay",
"haystack" : "копна сена",
"hazard" : "шанс, риск, рисковать [-кнуть]",
"hazardous" : "рискованный",
"haze" : "легкий туман дымка, зло подшучивать над",
"hazel" : "орешник, карий",
"hazel-nut" : "лесной орех",
"hazelnut" : "n  лесной орех, фундук (плод)",
"hazy" : "туманный, смутный",
"he" : "он; See also: he who ..., he-...",
"he does not mince matters" : "он говорит без обиняков",
"he failed to do" : "ему не удалось сделать, забыть",
"he happened to be at home" : "он случайно оказался дома",
"he is badly off" : "его дела плохи",
"he is better" : "ему лучше",
"he is free to" : "он волен",
"he is likely to die" : "он вероятно умрет",
"he is my senior by a year" : "он старше меня на год",
"he is said to be ..." : "говорят что он ...",
"he is wanting in patience" : "ему недостает терпения",
"he lacks money" : "у него недостаток денег",
"he pledged himself" : "он связал себя обещанием",
"he wants energy" : "ему недостает энергии",
"he who ..." : "тот кто ...",
"he will come" : "он придет",
"he will do it" : "он это сделает, он хочет это сделать, он обычно это делает",
"he will have it that" : "он настаивает на том чтобы",
"he would do it" : "он сделал бы это, он обычно это делал",
"he-..." : "перед названием животного обозначает самца",
"head" : "голова, глава, начальник, вождь, изголовье, лицевая сторона, главный, возглавлять, направляться [-авиться]; See also: come to a head, get it into one's head that ..., head off, head for",
"head for" : "держать курс на",
"head off" : "отклонять [-нить]",
"head over heels" : "вверх тормашками",
"head-dress" : "головной убор, прическа",
"head-line" : "заголовок",
"head-phone" : "наушник",
"headache" : "головная боль",
"headboard" : "передняя спинка кровати",
"headdress" : "головной убор",
"heading" : "заголовок",
"headland" : "мыс",
"headlight" : "головной фонарь, фара",
"headline" : "заголовок",
"headlong" : "опрометчивый, опрометчиво, очертя голову",
"headmaster" : "директор школы",
"headphone" : "наушники",
"headquarter" : "See: headquarters",
"headquarters" : "штаб-квартира",
"headroom" : "n  1) авто высота кузова  2) стр. габаритная высота  3) просвет (арки, моста)",
"headset" : "радио головной телефон",
"headsman" : "палач",
"headsmen" : "See: headsman",
"headstone" : "могильный камень",
"headstrong" : "своевольный упрямый",
"headwater" : "верхняя вода",
"headwaters" : "истоки",
"headway" : "make headway",
"headwind" : "встречный ветер",
"heady" : "стремительный, опьяняющий",
"heal" : "излечивать [-чить] исцелять [-лить], зажить",
"health" : "здоровье",
"health-resort" : "курорт",
"healthful" : "целебный",
"healthy" : "здоровый, полезный",
"heap" : "куча масса, груда, нагромождать [-моздить], нагружать [-узить], накоплять [-пить]",
"hear" : "[у]слышать, [по]слушать",
"heard" : "и pt от hear",
"hearer" : "слушатель",
"hearing" : "слух; See also: слушание разбор дела",
"hearken" : "слушать",
"hearsay" : "слух молва",
"hearse" : "катафалк",
"heart" : "сердце, мужество, суть, сердцевина",
"heart-break" : "сильная печаль",
"heart-broken" : "убитый горем",
"heartache" : "душевная боль",
"heartbeat" : "пульсация сердца",
"heartbreak" : "большое горе",
"heartburn" : "изжога",
"hearten" : "ободрять [-рить]",
"heartfelt" : "искренний",
"hearth" : "очаг",
"heartless" : "бессердечный",
"heartrending" : "душераздирающий",
"hearts" : "черви, сердце душа; See also: by hearts, out of hearts, lay to hearts, lose hearts, take hearts",
"hearty" : "дружеский сердечный, здоровый",
"heat" : "жара жар, пыл, забег заплыв заезд, нагреть, топить, [раз]горячить",
"heater" : "нагреватель, калорифер радиатор",
"heath" : "местность поросшая вереском; See also: вереск",
"heathen" : "язычник, языческий",
"heathenish" : "варварский",
"heating" : "нагревание, отопление, накаливание",
"heave" : "подЙем, волнение, поднимать [-нять], [по]тянуть, вздыматься, напрягаться [-ячься]",
"heaven" : "небеса  небо",
"heavenly" : "небесный",
"heaviness" : "тяжесть, инертность, депрессия",
"heavy" : "тяжелый, обильный, сильный, бурный, мрачный, неуклюжий, heavy current",
"heavy current" : "ток высокого напряжения",
"heavy-weight" : "тяжеловес",
"heavyweight" : "тяжеловес",
"hebe" : "n  греч. миф. Геба",
"hebraic" : "древнееврейский",
"hebrew" : "еврейский",
"hecate" : "n  греч. миф. Геката",
"hecatomb" : "n  греч. рел. гекатомба",
"heck" : "щеколда",
"heckle" : "прерывать замечаниями",
"hectic" : "чахоточный, лихорадочный возбужденный",
"hector" : "задира",
"hedge" : "изгородь, огораживать изгородью, ограничить, окружать [-жить], уклоняться от прямого ответа",
"hedgehog" : "еж",
"hedonism" : "n  1) филос. гедонизм  2) жажда наслаждений",
"hedonist" : "n  1) филос. приверженец гедонизма  2) человек, любящий наслаждения",
"heed" : "внимание осторожность, обращать внимание на; See also: take no heed of",
"heedless" : "небрежный, необдуманный",
"heel" : "пятка, каблук, Am хам подлец, прибивать каблук к, следовать по пятам за; See also: head over heels, heels over head, down at heel",
"heels over head" : "вверх тормашками",
"heft" : "большая часть",
"hefty" : "дюжий",
"hegelian" : "1. a гегельянский 2. n гегельянец",
"hegemony" : "гегемония",
"heifer" : "телка",
"heigh" : "оклик",
"height" : "высота, вышина, возвышенность, верх",
"heighten" : "повышать [повысить], усилить",
"heinous" : "отвратительный ужасный",
"heir" : "наследник; See also: heir apparent",
"heir apparent" : "законный наследник",
"heiress" : "наследница",
"heirloom" : "наследство",
"held" : "от hold",
"helical" : "винтовой",
"helicopter" : "вертолет",
"heliocentric" : "a  гелиоцентрический",
"heliotrope" : "n  бот. гелиотроп",
"helium" : "гелий",
"helix" : "завиток ушной раковины",
"hell" : "ад, адский; See also: raise hell",
"hellbender" : "гуляка",
"hellebore" : "n  бот.  1) морозник  2) чемерица",
"hellenic" : "греческий",
"hellish" : "адский",
"hello" : "алло",
"helm" : "руль  рулевое колесо штурвал, кормило",
"helmet" : "шлем",
"helmsman" : "рулевой, кормчий",
"helmsmen" : "See: helmsman",
"help" : "помощь, спасение, помогать [помочь], угощать [угостить], помогать [-мочь], годиться; See also: mother's help, help self, I could not help laughing",
"help self" : "не церемониться брать",
"help-mate" : "помощник, товарищ подруга, супруг",
"helper" : "помощник",
"helpful" : "полезный",
"helping" : "порция",
"helpless" : "беспомощный",
"helplessness" : "беспомощность",
"helpmate" : "муж",
"helpmeet" : "помощник, товарищ подруга, супруг",
"helsinki" : "хельсинки",
"helve" : "ручка рукоять",
"hem" : "рубец кромка, подрубать [-бить]; See also: hem in",
"hem in" : "окружать [-жить]",
"hematite" : "= haematite",
"hemisphere" : "полушарие",
"hemispheric(al)" : "a  полусферический",
"hemlock" : "болиголов",
"hemoglobin" : "гемоглобин",
"hemorrhage" : "амер. = haemorrhage",
"hemorrhoid" : "геморрой",
"hemp" : "конопля пенька",
"hemstitch" : "ажурная строчка",
"hen" : "курица, самка",
"henbane" : "белена",
"hence" : "отсюда, следовательно; See also: a year hence",
"henceforth" : "с этого времени впредь",
"henceforward" : "с этого времени впредь",
"henchman" : "приверженец",
"henchmen" : "See: henchman",
"henpeck" : "держать мужа под башмаком",
"henpecked" : "находящийся под башмаком у жены",
"henry" : "n  эл. генри (единица индуктивности)",
"hepatitis" : "n  мед. гепатит, воспаление печени",
"heptane" : "n  хим. гептан",
"her" : "ее ей",
"herald" : "вестник, возвещать [-вестить] обЙявлять [-вить]; See also: herald in",
"herald in" : "вводить [ввести]",
"herb" : "трава, растение",
"herbivorous" : "травоядный",
"herculean" : "геркулесовский",
"hercules" : "геркулес",
"herd" : "стадо гурт, толпа, пасти, ходить стадом, [с]толпиться",
"herdsman" : "пастух",
"here" : "здесь тут, сюда, вот; See also: here's to you!",
"here's to you!" : "за ваше здоровье",
"hereabout" : "поблизости",
"hereafter" : "в будущем, будущее"
};
