var dicctr_13 = {
"выдумывать" : "invent contrive devise",
"выдыхание" : "expiration",
"выдыхать" : "breathe out, -ся become stale, o.s.",
"выезд" : "departure, drive ride, exit, gateway, visit",
"выездить" : "break in",
"выезжать1" : ", leave depart, drive #or ride out on, move, visit",
"выезжать2" : "break in",
"выезживать" : "break in",
"выемка" : "excavation, hollow",
"выехать" : ", leave depart, drive #or ride out on, move, visit",
"выжать" : "s. выжимать",
"выждать" : "s. выжидать",
"выжечь" : "burn out down #or in, brand",
"выживание" : "survival",
"выживать" : "survive, go through, stay, famil. oust",
"выжигать" : "burn out down #or in, brand",
"выжидать" : "wait for #or till",
"выжимать" : "squeeze press #or wring out, #sport lift",
"выжимки" : "bagasse, marc",
"выжить" : "survive, go through, stay, famil. oust",
"выжить из ума" : "be in one's dotage",
"вызвать" : "s. вызывать",
"вызваться" : "undertake #or offer",
"выздоравливать" : "recover",
"выздоравливающий" : "convalescent",
"выздороветь" : "recover",
"выздоровление" : "recovery",
"вызов" : "call, summons, invitation, challenge",
"вызолотить" : "gild",
"вызубривать" : "= зубрить",
"вызывание" : "evocation",
"вызывать" : "call, send for, summon, challenge, rouse cause, evoke",
"вызывающий" : "defiant provoking",
"выиграть" : "win  gain benefit",
"выигрывать" : "win  gain benefit",
"выигрыш" : "win gain, prize, profit, быть в выигрыше have won",
"выигрышный" : "advantageous profitable, lottery...",
"выйти" : "s. выходить",
"выйти в люди" : "arrive make one's way in life",
"выйти в отставку" : "retire resign",
"выйти в офицеры" : "rise to the rank of an officer",
"выйти за" : "be beside o.s.",
"выйти из терпения" : "lose one's temper",
"выйти на пенсию" : "retire resign",
"выказать" : "show prove, display",
"выказывать" : "show prove, display",
"выкалывать" : "put out, cut out",
"выкапывать" : "dig out #or up",
"выкарабкаться" : "scramble #or get out",
"выкарабкиваться" : "scramble #or get out",
"выкармливать" : "bring up rear breed",
"выкатить глаза" : "popul. stare",
"выкатывать" : "выкатать mangle, roll, выкатить push #or move out; See also: выкатить глаза",
"выкидывать" : "throw out #or away discard, omit, strand, stretch, hoist, miscarry, famil. play",
"выкидыш" : "miscarriage abortion",
"выкинуть" : "throw out #or away discard, omit, strand, stretch, hoist, miscarry, famil. play",
"выкладка" : "laying out spreading, exposition, border trimming, computation calculation, milit. outfit",
"выкладывать" : "take #or lay out spread, set forth, border, brick #or mason, compute",
"выкликать" : "call up",
"выключатель" : "el. switch",
"выключать" : "switch #or turn off, stop, exclude",
"выключение" : "switching off stopping",
"выключенный" : "off",
"выключить" : "switch #or turn off, stop, exclude",
"выковать" : "forge, fig. mold",
"выковывать" : "forge, fig. mold",
"выколачивать" : "beat #or knock out, dust, popul. exact",
"выколотить" : "beat #or knock out, dust, popul. exact",
"выколоть" : "put out, cut out",
"выкопать" : "dig out #or up",
"выкормить" : "bring up rear breed",
"выкорчевать" : "root up #or out",
"выкорчевывать" : "root up #or out",
"выкраивать" : "cut out, famil. hunt  spare",
"выкрасить" : "paint dye",
"выкрашивать" : "paint dye",
"выкрикивать" : "cry #or call",
"выкрикнуть" : "cry #or call",
"выкроить" : "cut out, famil. hunt  spare",
"выкройка" : "pattern",
"выкрутасы" : "flourishes scrolls, dodges subterfuges",
"выкрутить" : "twist, wring, famil. unscrew, -ся famil. slip out",
"выкручивать" : "twist, wring, famil. unscrew, -ся famil. slip out",
"выкуп" : "redemption, ransom",
"выкупать" : "bath, bathe",
"выкупать1" : "redeem, ransom",
"выкупать2" : "s. купать",
"выкупаться" : "take a bath, bathe",
"выкупить" : "redeem, ransom",
"выкуривать" : "smoke, distill",
"выкурить" : "smoke, distill",
"вылавливать" : "fish out #or up",
"вылазка" : "milit. sally, excursion outing",
"вылакать" : "lap",
"выламывать" : "break out",
"вылезать" : "climb #or get out, fall out",
"вылезть" : "climb #or get out, fall out",
"вылепить" : "model",
"вылеплять" : "model",
"вылет" : "av. start taking off, flight",
"вылетать" : "fly out, av. start take off, rush out #or up, fall out, slip",
"вылететь" : "fly out, av. start take off, rush out #or up, fall out, slip",
"вылечивать" : "cure heal",
"вылечить" : "cure heal",
"выливать" : "pour",
"вылинять" : "fade, molt",
"вылитый" : "poured out, engin. cast, famil. just like",
"вылить" : "pour",
"выловить" : "fish out #or up",
"выложить" : "take #or lay out spread, set forth, border, brick #or mason, compute",
"выломать" : "break out",
"вылощить" : "gloss polish",
"вылупить" : "shell, -ся hatch",
"вылуплять" : "shell, -ся hatch",
"вылущить" : "shell husk",
"вымазать" : "smear, soil",
"вымазывать" : "smear, soil",
"вымаливать" : "get #or obtain by entreaties",
"выманивать" : "lure, coax #or cheat",
"выманить" : "lure, coax #or cheat",
"вымарать" : "soil, delete cross out",
"вымаривать" : "extirpate, вымаривать голодом starve",
"вымарывать" : "soil, delete cross out",
"вымачивать" : "drench soak #or wet",
"вымащивать" : "pave",
"выменивать" : "exchange",
"выменять" : "exchange",
"вымереть" : "s. вымирать",
"вымерший" : "extinct",
"вымести" : "sweep",
"выместить" : "avenge o.s., vent",
"выметать" : "sweep",
"вымещать" : "avenge o.s., vent",
"вымирать" : "die out become extinct",
"вымогательство" : "blackmail extortion",
"вымогать" : "extort",
"вымокать" : "wet through get wet",
"вымокнуть" : "wet through get wet",
"вымолвить" : "pf. utter say",
"вымолить" : "get #or obtain by entreaties",
"выморить" : "extirpate, вымаривать голодом starve",
"вымостить" : "pave",
"вымочить" : "drench soak #or wet",
"вымпел" : "pennant pennon",
"вымывать" : "wash, вымыть голову famil. bawl out blow up",
"вымысел" : "invention, falsehood",
"вымыслить" : "invent",
"вымыть" : "wash, вымыть голову famil. bawl out blow up",
"вымышленный" : "a. fictitious",
"вымышлять" : "invent",
"вымя" : "udder",
"вынашивать" : "wear out, evolve bring forth, train, nurse",
"вынести" : "s. выносить",
"вынимать" : "take #or draw out produce",
"выносить" : "wear out, evolve bring forth, train, nurse",
"выносить1" : "carry #or take out  remove, transfer, endure bear, acquire, submit, express, pass",
"выносить2" : "s. вынашивать",
"выноска" : "marginal note footnote",
"выносливость" : "endurance",
"выносливый" : "enduring sturdy hardy tough",
"выносящий" : "efferent",
"вынудить" : "force compel, extort",
"вынуждать" : "force compel, extort",
"вынужденный" : "forced, of necessity",
"вынуть" : "take #or draw out produce",
"вынырнуть" : "pf. emerge",
"выпад" : "falling out, fenc. lunge, fig. thrust attack",
"выпадать" : "fall #or drop, slip out, fall  devolve on, lunge",
"выпадение" : "falling out, fenc. lunge, fig. thrust attack",
"выпаливать" : "blurt out, famil. shoot",
"выпалить" : "blurt out, famil. shoot",
"выпалывать" : "weed",
"выпаривать" : "steam, evaporate",
"выпарить" : "steam, evaporate",
"выпасть" : "fall #or drop, slip out, fall  devolve on, lunge",
"выпачкать" : "soil",
"выпекать" : "bake",
"выпечь" : "bake",
"выпивать" : "drink, famil. booze, выпить o.s., выпить чашку чаю have a cup of tea",
"выпивка" : "booze",
"выпивший" : "drunk, tipsy",
"выписать" : "write out, copy, s. выводить 6), order subscribe, discharge dismiss, -ся register one's departure; See also: выписаться из больницы",
"выписаться из больницы" : "leave hospital",
"выписка" : "writing out copying, extract, commerc. statement, order subscription, discharge, notice of departure",
"выписывать" : "write out, copy, s. выводить 6), order subscribe, discharge dismiss, -ся register one's departure; See also: выписаться из больницы",
"выпить" : "drink, famil. booze, выпить o.s., выпить чашку чаю have a cup of tea",
"выплавка" : "smelting",
"выплакать" : "pf. weep out, famil. obtain by weeping",
"выплата" : "payment",
"выплатить" : "pay",
"выплачивать" : "pay",
"выплевывать" : "spit out",
"выплескать" : "dash #or splash",
"выплескивать" : "dash #or splash",
"выплеснуть" : "dash #or splash",
"выплывать" : "emerge come out appear",
"выплыть" : "emerge come out appear",
"выплюнуть" : "spit out",
"выполаскивать" : "rinse, gargle",
"выползать" : "creep or crawl out",
"выползти" : "creep or crawl out",
"выполнение" : "fulfilment execution realization",
"выполнимый" : "doable, manageable",
"выполнить" : "carry out fulfil, make",
"выполнять" : "carry out fulfil, make",
"выполоскать" : "rinse, gargle",
"выполоть" : "weed",
"выпотрошить" : "draw disembowel",
"выправить" : "set right #or straight, correct",
"выправка" : "correction, carriage",
"выправлять" : "set right #or straight, correct",
"выпрашивать" : "obtain by request",
"выпроваживать" : "see out, turn out",
"выпроводить" : "see out, turn out",
"выпросить" : "obtain by request",
"выпрыгивать" : "jump out #or off",
"выпрыгнуть" : "jump out #or off",
"выпрягать" : "unharness",
"выпрямитель" : "rectifier",
"выпрямить" : "straighten, -ся erect o.s.",
"выпрямлять" : "straighten, -ся erect o.s.",
"выпрячь" : "unharness",
"выпуклость" : "bulge, camber, convexity, gibbosity, protuberance",
"выпуклый" : "convex, prominent, fig. expressive distinct",
"выпуск" : "letting out, omission, engin. output, commerc. issue, publication, instalment, class of graduates",
"выпускать" : "let out, jur. release, engin. produce, issue, publish, omit leave out, graduate",
"выпускать в продажу" : "put on sale",
"выпускать из виду" : "lose sight of",
"выпускник" : "graduate",
"выпускной" : "graduate ... graduation ... final leaving, engin. discharge..., outlet ...",
"выпустить" : "let out, jur. release, engin. produce, issue, publish, omit leave out, graduate",
"выпутать" : "disentangle #or extricate",
"выпутывать" : "disentangle #or extricate",
"выпучивать" : "bulge, s. таращить",
"выпучить" : "bulge, s. таращить",
"выпытать" : "find out elicit",
"выпытывать" : "find out elicit",
"выпь" : "bittern",
"выпяливать" : "s. таращить",
"выпялить" : "s. таращить",
"выпятить" : "protrude",
"выпячивать" : "protrude",
"вырабатывать" : "manufacture produce, elaborate work out, develop, earn make",
"выработать" : "manufacture produce, elaborate work out, develop, earn make",
"выработка" : "manufacture production, output performance, elaboration",
"выравнивать" : "level engin. plane, smooth, -ся straighten, milit. dress, develop grow up",
"выражать" : "express show, выражать словами put into words",
"выражение" : "expression",
"выразительность" : "emphasis, expression",
"выразительный" : "expressive, famil. significant"
};
