var dicctr_73 = {
"разбегаться" : "take a run, scatter, disperse",
"разбежаться" : "take a run, scatter, disperse",
"разбивать" : "break  crash crush, defeat, divide, lay out, pitch, knock, -ся break, crash, split, come to nothing",
"разбирательство" : "trial",
"разбирать" : "take to pieces dismantle pull down, investigate inquire into, review, analyze  parse, make out decipher understand, sort out, jur. try, buy up, famil. take, impf. be particular",
"разбираться" : "famil. grasp understand, unpack",
"разбитие" : "crash defeat",
"разбитый" : "broken, famil. jaded",
"разбить" : "break  crash crush, defeat, divide, lay out, pitch, knock, -ся break, crash, split, come to nothing",
"разбогатеть" : "grow rich",
"разбой" : "robbery",
"разбойник" : "robber",
"разбойничать" : "rob, pirate",
"разбойнический" : "predatory, of robbers #or brigands",
"разбойничий" : "predatory, of robbers #or brigands",
"разболтать" : "let out",
"разбомбить" : "bomb",
"разбор" : "analysis, review critique, investigation inquiry, jur. trial, без разбора разбору famil. indiscriminately",
"разборка" : "taking to pieces dismantling, sorting",
"разборный" : "folding collapsible",
"разборчивость" : "legibility, scrupulousness",
"разборчивый" : "legible, discerning, scrupulous fastidious",
"разбрасывать" : "scatter throw about strew, famil. squander",
"разбрасывающий" : "dispersive",
"разбредаться" : "disperse",
"разбрестись" : "disperse",
"разброд" : "disorder mess",
"разбросанный" : "scattered",
"разбросать" : "scatter throw about strew, famil. squander",
"разбухать" : "swell",
"разбухнуть" : "swell",
"развал" : "collapse breakdown, chaos",
"разваливать" : "pull down, disorganize",
"разваливаться" : "fall to pieces collapse, famil. sprawl",
"развалины" : "ruins",
"развалить" : "pull down, disorganize",
"развалиться" : "fall to pieces collapse, famil. sprawl",
"разве" : "really, perhaps, only, famil. unless",
"развеваться" : "flutter, stream",
"разведать" : "s. разведывать",
"разведение" : "breeding, cultivation",
"разведенный" : "divorced divorce su.",
"разведка" : "reconnaissance, intelligence service",
"разведочный" : "reconnaissance...",
"разведчик" : "scout, intelligence officer, reconnaissance plane",
"разведывательный" : "s. разведочный",
"разведывать" : "reconnoiter, famil. find out",
"развезти" : "s. развозить",
"развенчать" : "pf. uncrown dethrone, unmask",
"развенчивать" : "debunk, dethrone",
"развернутый" : "large-scale",
"развернуть" : "unfold unroll unwrap, open, milit. deploy, fig. develop",
"развертывание" : "deploy",
"развертывать" : "unfold unroll unwrap, open, milit. deploy, fig. develop",
"развеселить" : "amuse divert",
"развесить" : "s. развешивать",
"развесной" : "weighed out",
"развести" : "s. разводить",
"разветвляться" : "ramify",
"развивать" : "develop, educe, uncurl",
"развиваться" : "evolve, in progress, maturate",
"развилина" : "crotch",
"развинтить" : "unscrew",
"развинчивать" : "unscrew",
"развитие" : "development, evolution",
"развитой" : "developed, intelligent, advanced",
"развить" : "develop, evolve, untwist",
"развлекать" : "entertain amuse, divert",
"развлечение" : "entertainment amusement diversion",
"развлечь" : "entertain amuse, divert",
"развод" : "divorce, milit. relief mounting",
"разводить" : "take  bring, divorce, separate, dilute, mix, rear breed, plant cultivate, light make, milit. mount relieve",
"разводиться" : "get divorced, famil. multiply grow #or increase in number",
"развозить" : "deliver carry",
"разворачивать" : "s. развертывать",
"разврат" : "debauch, depravity",
"развратить" : "s. развращать",
"развратник" : "lecher",
"развратничать" : "debauch",
"развратный" : "dissolute licentious",
"развращать" : "deprave debauch corrupt",
"развращение" : "depravity",
"развращенность" : "depravity",
"развязать" : "s. развязывать",
"развязаться" : "come untied, famil. get rid",
"развязка" : "denouement, outcome conclusion head",
"развязный" : "forward easy",
"развязывать" : "untie undo, fig. unleash, famil. loosen",
"развязываться" : "come untied, famil. get rid",
"разгадать" : "s. разгадывать",
"разгадка" : "solution",
"разгадывать" : "solve unriddle",
"разгар" : "heat thick  height  swing",
"разгибать" : "unbend straighten",
"разгладить" : "smooth, iron press",
"разглаживать" : "smooth, iron press",
"разгласить" : "divulge, trumpet",
"разглашать" : "divulge, trumpet",
"разглядеть" : "pf. make out",
"разглядывать" : "examine view",
"разгневанный" : "angry",
"разгневаться" : "be angry",
"разговаривать" : "talk  converse speak",
"разговор" : "talk conversation, cf. речь",
"разговорный" : "colloquial",
"разговорчивый" : "talkative",
"разгон" : "dispersal, a. = разбег, в разгоне out",
"разгонять" : "disperse scatter, dispel, famil. drive away",
"разгоняться" : "take a run",
"разгораться" : "kindle  flame blaze up",
"разгореться" : "kindle  flame blaze up",
"разгорячить" : "heat, -ся get #or be excited",
"разграбить" : "plunder pillage loot",
"разграбление" : "plunder pillage loot",
"разграблять" : "plunder pillage loot",
"разграничение" : "delimitation",
"разграничивать" : "demarcate delimit",
"разграничить" : "demarcate delimit",
"разграфить" : "line #or rule  draw columns",
"разгром" : "rout, debacle destruction ruin chaos",
"разгромить" : "smash crush, rout",
"разгружать" : "unload, famil. relieve",
"разгрузить" : "unload, famil. relieve",
"разгрузка" : "unloading",
"разгрызть" : "gnaw  nibble, bite, crack",
"разгул" : "revelry carouse, debauch licentiousness",
"разгуливать" : "stroll saunter",
"разгуливаться" : "clear up, famil. have a good walk #or run move without restraint",
"разгульный" : "dissolute, loose easy",
"разгуляться" : "clear up, famil. have a good walk #or run move without restraint",
"раздавать" : "distribute, play out, -ся sound be heard, give way, split separate, famil. expand",
"раздавленный" : "crushed",
"раздавливать" : "s. давить",
"раздать" : "distribute, play out, -ся sound be heard, give way, split separate, famil. expand",
"раздача" : "distribution",
"раздваивать" : "bifurcate",
"раздваиваться" : "s. двоиться",
"раздвигать" : "part separate move apart, pull out",
"раздвижной" : "sash..., telescope -pic",
"раздвинуть" : "part separate move apart, pull out",
"раздвоение" : "bifurcation",
"раздвоенный" : "bifid, forked, furcate",
"раздвоиться" : "bifurcate",
"раздевалка" : "checkroom cloakroom",
"раздевальня" : "checkroom cloakroom",
"раздевать" : "undress  take off, famil. strip",
"раздел" : "division, section",
"разделаться" : "pf. get rid #or be quit",
"разделение" : "division, eccl. schism",
"разделенный" : "divided, parted",
"разделительный" : "dividing, gr. disjunctive",
"разделить" : "& делить",
"раздельно" : "apart",
"разделять" : "disunite, participate, share, share in",
"разделяющий" : "disjunctive, dividing, divisive",
"раздражать" : "irritate provoke, vex annoy",
"раздражаться" : "lose one's temper",
"раздражение" : "irritation, temper",
"раздражительный" : "irritable touchy",
"раздражить" : "irritate provoke, vex annoy",
"раздробить" : "break to pieces crush, dismember divide #or split up, famil. drum",
"раздробление" : "breaking, smashing",
"раздроблять" : "s. дробить",
"раздувать" : "fan, blow, swell, puff up exaggerate",
"раздуваться" : "swell inflate",
"раздумать" : "change one's mind, impf. deliberate consider",
"раздумывать" : "change one's mind, impf. deliberate consider",
"раздумье" : "thought meditation, doubt",
"раздуть" : "fan, blow, swell, puff up exaggerate",
"разевать" : "open wide",
"разжалобить" : "pf. move to pity",
"разжаловать" : "pf. degrade",
"разжать" : "s. разжимать",
"разжевать" : "chew",
"разжевывать" : "chew",
"разжечь" : "kindle, heat, rouse, unleash",
"разжигать" : "kindle, heat, rouse, unleash",
"разжижающий" : "diluent",
"разжимать" : "unclench open",
"разжиреть" : "grow fat",
"разинуть" : "open wide",
"разиня" : "gawk gaper",
"разительный" : "striking",
"разлагать" : "analyze, decompose, demoralize corrupt",
"разлад" : "dissension discord dissonance, disturbance",
"разламывать" : "break, pull down",
"разлетаться" : "fly, famil. break, come to naught, take a sweep",
"разлететься" : "fly, famil. break, come to naught, take a sweep",
"разлив" : "flood",
"разливать" : "spill, pour out, bottle, ladle, flood overflow, spread, bestow",
"разлить" : "spill, pour out, bottle, ladle, flood overflow, spread, bestow",
"различать" : "distinguish",
"различаться" : "impf. differ",
"различие" : "distinction difference",
"различительный" : "distinctive",
"различить" : "distinguish",
"различный" : "different, different various diverse",
"разложение" : "analysis, decomposition decay, corruption degeneration",
"разложить" : "analyze, decompose, demoralize corrupt",
"разломать" : "break, pull down",
"разломить" : "break, pull down",
"разлука" : "separation  parting",
"разлучать" : "separate  part",
"разлучить" : "separate  part",
"размазать" : "unwind wind off",
"размазывать" : "unwind wind off",
"разматывать" : "unwind wind off",
"размах" : "swing brandish, span  sweep, amplitude, fig. vim verve elan, scope",
"размахивать" : "swing sway dangle, brandish, gesticulate",
"размахиваться" : "lift",
"размахнуть" : "swing sway dangle, brandish, gesticulate",
"размахнуться" : "lift",
"размашистый" : "wide, diffuse",
"размежевать" : "pf. mark off demarcate",
"размельчать" : "pound crush",
"размельчить" : "pound crush",
"размен" : "change",
"разменивать" : "change",
"разменная монета" : "change",
"разменять" : "change",
"размер" : "size, dimension measure, rate  amount, scale, #poetic. mus. a. time measure",
"размеренный" : "measured",
"размерить" : "measure",
"размерять" : "measure",
"разместить" : "s. размещать",
"разметить" : "mark",
"размечать" : "mark",
"размешать" : "stir, knead",
"размешивание" : "kneading, stir",
"размешивать" : "stir, knead",
"размещать" : "place, lodge accommodate, distribute",
"размещение" : "distribution, accommodation, arrangement order",
"разминать" : "knead, famil. stretch",
"разминка" : "warm up, warmup",
"разминуться" : "cross, miss o.a.",
"размножать" : "multiply, mimeograph",
"размножаться" : "proliferate, reproduce",
"размножение" : "multiplication, propagation reproduction",
"размножить" : "multiply, mimeograph",
"размозжить" : "pf. smash crush",
"размокать" : "soak swell",
"размокнуть" : "soak swell",
"размолвка" : "tiff quarrel",
"размолоть" : "pf. grind crush",
"размораживать" : "defrost",
"размотать" : "unwind wind off",
"размочить" : "pf. soak",
"размывать" : "wash out #or away",
"размыкать" : "open",
"размыть" : "wash out #or away"
};
