var dicctr_16 = {
"глубокий тыл" : "hinterland",
"глубоко" : "deeply",
"глубокомысленный" : "thoughtful sagacious",
"глубокомыслие" : "thoughtfulness",
"глубокоуважаемый" : "dear",
"глубочайший" : "inmost, innermost",
"глубь" : "s. глубина",
"глумиться" : "sneer mock scoff",
"глумление" : "mockery",
"глупеть" : "become stupid",
"глупец" : "fool blockhead",
"глупить" : "fool",
"глупость" : "stupidity, foolery, nonsense",
"глупый" : "foolish silly stupid",
"глупыш" : "fulmar, gosling, noddy",
"глухарь" : "capercailie wood grouse",
"глухая тетеря" : "deaf fellow",
"глухой" : "deaf, dull vague, desolate wild, out-of-the-way, arch. tight solid blind, late the dead of, gr. voiceless",
"глухонемой" : "deaf-mute",
"глухота" : "deafness",
"глушитель" : "muffler",
"глушить" : "оглушить deafen stun, заглушить deafen, deaden, muffle, smother suppress, engin. switch off throttle, el. jam",
"глушь" : "thicket, wilderness, solitude lonely spot nook",
"глыба" : "lump clod, block",
"глюкоза" : "dextrose, glucose",
"глядеть" : "look glance, famil. look after take care of, peep, famil. гляди very likely, look out!, того и гляди ... may  inf., куда глаза глядят at random, after one's nose",
"гляди" : "lo",
"глянец" : "polish, luster",
"глянуть" : "look glance, famil. look after take care of, peep, famil. гляди very likely, look out!, того и гляди ... may  inf., куда глаза глядят at random, after one's nose",
"глянцевитый" : "glossy",
"глянцевый" : "glossy lustrous, glazed #paper",
"г-н" : "abbr.: господин",
"гнать" : "drive, famil. send, float, distil, pursue chase, speed along",
"гнев" : "anger",
"гневаться" : "be angry",
"гневный" : "angry",
"гнедой" : "sorrel chestnut",
"гнездиться" : "nest",
"гнездо" : "nest aerie",
"гнет" : "press, oppression",
"гнетущий" : "depressing, dismal, oppressive",
"гнида" : "nit",
"гниение" : "putrefaction",
"гнилой" : "rotten putrid, wet",
"гниль" : "rottenness",
"гнить" : "rot putrefy",
"гноение" : "suppuration",
"гноить" : "fester",
"гной" : "pus",
"гнойный" : "purulent",
"гном" : "gnome, leprechaun",
"гнусавость" : "snuffle",
"гнусность" : "enormity",
"гнушаться" : "scorn despise disdain",
"гобелен" : "gobelin, tapestry",
"гобой" : "oboe",
"говенье" : "fast",
"говеть" : "fast",
"говор" : "talk hum murmur, rumor, accent, dialect patois",
"говорится" : "they say it is said",
"говорить" : "speak #or talk, say tell; See also: говорят, говорится, говорить по-русски, иначе говоря, не говоря уже о, по правде говоря, по совести говоря, что вы говорите{!}, что ни говори, как ни говори, что и говорить, и не говори{!}",
"говорить обиняками" : "speak in a roundabout way",
"говорить по-русски" : "speak Russian",
"говорливый" : "talkative",
"говорят" : "they say it is said",
"говядина" : "beef",
"говяжий" : "beef",
"гогот" : "cackle, popul. roar",
"гоготать" : "cackle, popul. roar",
"год" : "year, cf. пятый; See also: в этом году, в прошлом году, из года в год, год от году, круглый год, годами, с годами",
"год от году" : "year by year",
"годами" : "for years",
"годиться" : "be of use  do, fit, pf. come in handy, это не годится, that's no good, that won't do it's bad",
"годичный" : "annual",
"годный" : "fit suitable useful good milit. able; See also: ни на что не годный",
"годовой" : "annual, one year",
"годовщина" : "anniversary",
"гол" : "goal; See also: забить гол",
"голенище" : "bootleg",
"голень" : "shank",
"голландец" : "Dutchman",
"голландия" : "Holland",
"голландка" : "Dutchwoman",
"голландский" : "Dutch",
"голливуд" : "hollywood",
"голова" : "head, head chief; See also: голова сахару, как снег на голову, с головы до ног, в головах, на свою голову, повесить голову, голова идет кругом",
"голова идет кругом" : "thoughts are in a whirl",
"голова кружится" : "feel giddy",
"голова сахару" : "sugar loaf",
"головастик" : "tadpole",
"головка" : "small head, head, bulb clove",
"головная боль" : "headache",
"головной" : "head..., milit. advance ...",
"головокружение" : "giddiness",
"головокружительный" : "dizzy giddy",
"головоломка" : "puzzle",
"головомойка" : "famil. blowup",
"головорез" : "daredevil, cutthroat thug",
"головотяп" : "booby bungler",
"голография" : "holography",
"голод" : "hunger, s. голодовка",
"голодать" : "starve",
"голодный" : "hungry, starving",
"голодовка" : "starvation, famine, hunger strike",
"гололедица" : "ice-crusted ground",
"голос" : "voice, vote; See also: право голоса, во весь голос, в один голос, голоса за и против",
"голоса за и против" : "the yeas & noes",
"голосить" : "bawl",
"голословный" : "unfounded, empty",
"голосование" : "voting poll, закрытое голосование secret vote",
"голосовать" : "vote",
"голосовая щель" : "glottis",
"голосовой" : "vocal",
"голубец" : "stuffed cabbage",
"голубиный" : "columbine",
"голубка" : "dear",
"голубоватый" : "bluish",
"голубь" : "dove, pigeon",
"голый" : "bare, naked, nude, unclad",
"гольф" : "golf",
"гомогенный" : "homogeneous",
"гомологический" : "homologous",
"гомология" : "homology",
"гомосексуалист" : "homo, invert, sodomite",
"гомосексуальный" : "gay, homosexual",
"гонг" : "gong",
"гондола" : "gondola",
"гондурас" : "honduras",
"гонка" : "rush, chase, famil. haste, chem. distilment, nav. regatta, famil. blowup",
"гонка вооружений" : "arms race",
"гонки" : "race",
"гонконг" : "Hong Kong",
"гонор" : "airs pl.",
"гонорар" : "fee",
"гоночный" : "race... racing",
"гоночный автомобиль" : "racing car racer",
"гонт" : "coll. shingles",
"гончар" : "potter",
"гончарные изделия" : "pottery",
"гончарный" : "potter's; See also: гончарные изделия",
"гончая" : "hound",
"гонять" : "drive s. гнать",
"гора" : "mount, mountain",
"горб" : "hump",
"горбун" : "hunchback",
"горбушка" : "top crust heel",
"горделивый" : "haughty proud",
"гордец" : "proud man",
"гордиться" : "be proud",
"гордость" : "pride",
"гордый" : "proud",
"горе" : "grief distress, trouble, misfortune disaster, с горя out of grief, горе мне! woe is me!, ему и горя мало famil. he doesn't care a bit, с горем пополам famil. hardly with difficulty",
"горевать" : "grieve, regret",
"горелка" : "burner",
"горелый" : "burnt",
"горемыка" : "poor wretch",
"горение" : "combustion",
"горестный" : "sad sorrowful",
"горесть" : "cf. горе",
"гореть" : "burn  be on fire, glow gleam, не горит famil. there's no hurry, дело горит famil. the matter is top urgent",
"горец" : "mountaineer",
"горечь" : "bitter taste, fig. bitterness, grief affliction",
"горжетка" : "neckpiece",
"горизонт" : "horizon",
"горизонтальный" : "horizontal level",
"горилла" : "gorilla",
"гористый" : "mountainous, hilly",
"горихвостка" : "redstart",
"горка" : "s., hill, whatnot small cupboard",
"горланить" : "bawl",
"горло" : "throat, gullet, neck, по горло famil. up to the eyes, я сыт по горло famil. I've had my fill, fig. I'm fed up with, во все горло s. голос",
"горлышко" : "spout",
"горн" : "engin. furnace forge, crucible, mus. horn bugle",
"горнист" : "bugler",
"горничная" : "parlormaid",
"горное дело" : "mining",
"горное солнце" : "sun lamp",
"горнозаводский" : "mining metallurgical",
"горнопромышленный" : "mining metallurgical",
"горнорабочий" : "miner",
"горностай" : "ermine",
"горный" : "mountain hilly, min. rock..., engin. mining; See also: горный промысел, горное дело, горное солнце",
"горный промысел" : "mining",
"горняк" : "miner",
"город" : "town, city, за город #go out of town",
"городить" : "talk nonsense",
"городок" : "small town, quarter",
"городской" : "town... city... municipal, a. горсовет",
"городской совет" : "city #or town soviet",
"горожанин" : "townsman, pl. townspeople",
"горожанка" : "townswoman",
"гороскоп" : "horoscope",
"горох" : "pea, pl.",
"гороховый" : "pea..., pea green; See also: чучело гороховое, шут гороховый",
"горошек" : "pl.",
"горошина" : "pea, dot",
"гортанный" : "guttural, laryngeal, throaty",
"гортань" : "larynx",
"горчица" : "mustard",
"горшок" : "pot",
"горький пьяница" : "dipsomaniac",
"горючее" : "fuel, gasoline Brt. petrol",
"горючий" : "combustible, popul. bitter",
"горячий" : "hot, fiery hot-tempered, ardent passionate, violent, warm, cordial, hard busy",
"горячить" : "heat, -ся get #or be excited",
"горячка" : "fever",
"горячность" : "vehemence hot temper",
"гос" : "state...; See also: Госбанк, Госиздат, Госплан",
"госбанк" : "State Bank",
"госиздат" : ", State Publishing House",
"госпиталь" : "milit. hospital",
"госплан" : ", State Planning Committee",
"господин" : "gentleman, master, Mr., gentlemen, pl. master & mistress, уважаемые господа dear Sirs, я сам себе господин I am my own master",
"господский" : "seignorial lord's master's, manor",
"господство" : "rule, supremacy",
"господствовать" : "rule reign, dominate prevail, command",
"господствующий" : "dominant, prevailing",
"господь" : "Lord God",
"госпожа" : "lady, mistress, Mrs. #or Miss",
"гостеприимный" : "hospitable",
"гостеприимство" : "hospitality",
"гостиная" : "drawing room",
"гостинец" : "present gift",
"гостиница" : "hotel, inn",
"гостить" : "be on a visit stay with",
"гость" : "guest, visitor, идти в гости go to see, быть в гостях = гостить",
"государственный" : "state...; See also: Госбанк, Госиздат, Госплан",
"государственный деятель" : "statesman",
"государственный переворот" : "coup d'etat",
"государственный строй" : "political system regime, a. ГПУ",
"государство" : "state",
"государь" : "sovereign, Czar; See also: милостивый государь",
"готический" : "gothic",
"готовальня" : "drawing utensils pl.",
"готовить" : "приготовить prepare, подготовить prepare train, заготовить store up, lay in",
"готовность" : "readiness, willingness",
"готовый" : "ready  on the point of, finished, willing, ready-made, будь готов! - всегда готов!, be ready! - always ready!",
"гпу" : ", G.P.U.= Political State Administration",
"гр" : "abbr.: гражданин",
"грабеж" : "depredation, looting, rapine, ravin, robbery",
"грабительский" : "predatory",
"грабить" : "depredate, despoil, loot, rob",
"грабли" : "rake",
"гравий" : "gravel, grit",
"гравировать" : "engrave, etch",
"град" : "hail",
"градина" : "chalazion, hailstone",
"градус" : "degree",
"гражданин" : "citizen",
"гражданка" : "citizen"
};
