var dicctr_47 = {
"непредусмотрительный" : "improvident",
"непреклонный" : "uncompromising, steadfast",
"непреложный" : "inviolable invariable, incontestable",
"непременно" : "s. обязательно",
"непременный" : "indispensable, permanent",
"непреодолимый" : "insuperable, irresistible",
"непререкаемый" : "indisputable",
"непрерывность" : "continuity",
"непрерывный" : "continuous",
"непрестанный" : "incessant",
"непривычный" : "unaccustomed, unusual",
"неприглядный" : "homely mean",
"непригодный" : "unfit, useless",
"неприемлемый" : "unacceptable",
"неприкосновенный" : "inviolable, untouched untouchable",
"неприкрашенный" : "unvarnished",
"неприличный" : "indecent unseemly",
"неприменимый" : "inapplicable, unworkable",
"неприметный" : "imperceptible unnoticeable, plain",
"непримиримый" : "irreconcilable implacable",
"непринужденный" : "easy at ease",
"непристойный" : "obscene indecent",
"неприступный" : "inaccessible, impregnable, unapproachable haughty",
"непритворный" : "sincere unfeigned",
"непритязательный" : "unpretentious modest plain",
"неприязненный" : "hostile unkind",
"неприязнь" : "dislike",
"неприятель" : "enemy",
"неприятельский" : "enemy",
"неприятность" : "trouble",
"неприятный" : "disagreeable unpleasant",
"непроглядный" : "pitch-dark",
"непродолжительный" : "short brief",
"непроезжий" : "impassable",
"непрозрачный" : "opaque",
"непроизводительный" : "unproductive",
"непроизвольный" : "involuntary",
"непромокаемый" : "waterproof",
"непроницаемый" : "impenetrable impermeable impervious",
"непропеченный" : "soggy",
"непростительный" : "unpardonable",
"непрофессиональный" : "amateurish, unprofessional",
"непроходимый" : "impassable, famil. complete",
"непрочный" : "flimsy unstable",
"непрощенный" : "unbidden",
"непрямой" : "indirect",
"нептун" : "neptune",
"нептуний" : "neptunium",
"нерабочий" : "free off",
"неравенство" : "inequality",
"неравномерный" : "uneven",
"неравный" : "unequal",
"нерадивый" : "careless listless",
"неразбериха" : "mess",
"неразборчивый" : "illegible, unscrupulous",
"неразвитой" : "undeveloped",
"нераздельный" : "indivisible integral, undivided",
"неразлагающийся" : "indecomposable",
"неразличимый" : "indistinguishable",
"неразложимый" : "infrangible, irresolvable",
"неразлучный" : "inseparable",
"неразрешимый" : "insoluble",
"неразрывный" : "indissoluble",
"неразумный" : "injudicious",
"нерасположение" : "dislike",
"нерасположенный" : "averse, indisposed, undisposed",
"нерассудительный" : "imprudent",
"нерастворимый" : "indissoluble, insoluble",
"нерациональный" : "irrational, preposterous",
"нерв" : "nerve",
"нервировать" : "make nervous",
"нервничать" : "be nervous",
"нервнобольной" : "neurotic",
"нервный" : "nervous, high-strung",
"нерегулярный" : "irregular, sporadic",
"нерешительность" : "indecision",
"нерешительный" : "halfhearted, hesitating, indecisive, irresolute",
"нержавеющий" : "rustless, rustproof",
"неровность" : "jagging",
"нерон" : "nero",
"нерушимый" : "imperishable, indestructible",
"неряха" : "slattern, sloven, slut, trollop",
"неряшливый" : "grubby, scruffy, slatternly, slovenly",
"несамостоятельный" : "slavish",
"несвоевременный" : "amiss, inopportune, timeless, untimely",
"несвойственный" : "extrinsic",
"несвязный" : "incoherent",
"несгораемый" : "fireproof",
"несдержанный" : "unrestrained",
"несерьезный" : "frivolous",
"несет" : "there's a draught",
"несжимаемый" : "incompressible, incondensable",
"несказанный" : "indescribable",
"нескладный" : "ungainly unwieldy, incoherent",
"несклонный" : "loath, loth, unwilling",
"несклоняемый" : "indeclinable",
"несколько" : "a few some several, somewhat",
"нескромный" : "immodest",
"нескрываемый" : "overt",
"несложный" : "foolproof",
"неслыханный" : "unheard-of, awful",
"неслышный" : "inaudible noiseless",
"несменяемый" : "irremovable",
"несметный" : "innumerable",
"несмешиваемый" : "immiscible",
"несмотря" : "in spite of despite notwithstanding, though",
"несмываемый" : "indelible",
"несносный" : "intolerable",
"несоблюдение" : "nonobservance",
"несовершеннолетие" : "minority",
"несовершенный" : "imperfect",
"несовершенолетие" : "infancy",
"несовершенство" : "imperfection",
"несовместимый" : "incompatible",
"несогласие" : "disagreement",
"несогласный" : "discordant, inconsistent",
"несоизмеримый" : "incommensurable",
"несокрушимый" : "indestructible",
"несомненно" : "a. undoubtedly without doubt",
"несомненный" : "doubtless",
"несообразный" : "incompatible, absurd foolish",
"несообщаемый" : "incommunicable",
"несоответственный" : "incongruous",
"несоответствие" : "discrepancy",
"несоразмерный" : "disproportionate",
"несостоятельный" : "needy, insolvent, unsound baseless",
"неспокойный" : "restless uneasy",
"неспособность" : "disability, inability, inefficiency",
"неспособный" : "incapable  unfit",
"несправедливость" : "injustice, wrong",
"несправедливый" : "unjust wrong",
"неспроста" : "s. недаром",
"несравненный" : "incomparable",
"несравнимый" : "incomparable",
"нестерпимый" : "intolerable",
"нести" : "carry, bear, bring, suffer, do, drift waft speed, снести lay, famil. talk, smell; See also: несет",
"нестроевой" : "noncombatant",
"нестройный" : "ungainly, discordant, disorderly",
"несуразный" : "foolish absurd, ungainly",
"несущественный" : "immaterial, inessential, unessential",
"несуществующий" : "defunct",
"несходный" : "unlike different",
"несчастливый" : "infelicitous",
"несчастный" : "unhappy unlucky, famil. paltry",
"несчастный случай" : "accident",
"несчастье" : "misfortune, disaster, accident; See also: к несчастью, на несчастье",
"несчетный" : "innumerable",
"нет" : "part.: no; See also: нет еще",
"нет еще" : "not yet, vb. : there is no, у меня ~ I have no, его ~ he is not here #or in",
"нет лица" : "be bewildered",
"нетерпеливый" : "impatient",
"нетерпение" : "impatience",
"нетерпимый" : "intolerant, intolerable",
"нетленный" : "imperishable",
"неточность" : "inaccuracy, inexactitude",
"неточный" : "hit-and-mis, inaccurate, inexact",
"нетрезвый" : "drunk",
"нетронутый" : "untouched",
"нетрудоспособный" : "disabled",
"нетто" : "net",
"нету" : "famil. = нет",
"неубедительный" : "inconclusive, unconvincing",
"неуважение" : "disrespect",
"неуверенный" : "uncertain",
"неувядаемый" : "unfading",
"неувядающий" : "amaranthine, evergreen, fadeless",
"неугасимый" : "inextinguishable",
"неугомонный" : "restless unquiet, untiring",
"неудача" : "misfortune, failure",
"неудачливый" : "unlucky",
"неудачник" : "unlucky fellow",
"неудачный" : "unsuccessful unfortunate",
"неудержимый" : "irrepressible",
"неудивительно" : "no wonder",
"неудобный" : "inconvenient, uncomfortable, improper",
"неудобоваримый" : "indigestible",
"неудобство" : "inconvenience",
"неудовлетворительный" : "unsatisfactory",
"неудовольствие" : "displeasure",
"неужели" : "really? is it possible?",
"неуживчивый" : "unsociable unaccommodating",
"неуклонный" : "unswerving firm",
"неуклюжий" : "clumsy awkward",
"неукротимый" : "indomitable",
"неуловимый" : "elusive, imperceptible",
"неумело" : "bungle",
"неумелый" : "unskillful awkward",
"неумение" : "inability",
"неумеренный" : "intemperate immoderate",
"неуместность" : "impropriety, inaptitude",
"неуместный" : "inappropriate",
"неумолимый" : "inexorable",
"неумышленный" : "unintentional",
"неупотребительность" : "desuetude",
"неупотребительный" : "not in use",
"неурожай" : "bad harvest",
"неурочный" : "unseasonable",
"неуспех" : "failure",
"неустанный" : "incessant, constant, a. неутомимый",
"неустойка" : "forfeit",
"неустойчивость" : "imbalance, instability",
"неустойчивый" : "unstable, unsteady",
"неустрашимый" : "intrepid dauntless",
"неуступчивый" : "uncomplying tenacious",
"неусыпный" : "incessant unremitting, a. неутомимый",
"неутешный" : "disconsolate inconsolable",
"неутолимый" : "unquenchable, insatiable",
"неутомимый" : "tireless indefatigable untiring",
"неуч" : "ignoramus",
"неученый" : "illiterate",
"неученье" : "ignorance",
"неучтивый" : "uncivil",
"неуютный" : "uncomfortable",
"неуязвимый" : "invulnerable",
"нефология" : "nephology",
"нефрит" : "jade, nephrite, nephritis",
"нефтеналивной" : "s. наливной",
"нефтепровод" : "pipe line",
"нефть" : "oil",
"нефтяной" : "oil...",
"нехватка" : "shortage",
"нехороший" : "bad",
"нехотя" : "unwillingly",
"нецелесообразный" : "inadvisable, inexpedient",
"нецензурный" : "s. непристойный",
"нечаянный" : "unexpected, accidental casual",
"нечего" : "~  inf. nothing to ..., need not no need, no use, stop ...ing",
"нечестивый" : "impious, unholy",
"нечетный" : "odd, uneven",
"нечленораздельный" : "inarticulate",
"нечто" : "aught",
"нечувствительный" : "impassive, insensible, insensitive",
"неэластичный" : "inelastic",
"неэффективный" : "void",
"неявка" : "nonappearance",
"неяркий" : "dull dim, mediocre",
"неясный" : "not clear, fig. vague",
"ни" : "not a, ~ ... ~ neither ... nor, ... ever, кто бы то ~ был, whosoever, как ~  a. in spite #or for all  su.; See also: как бы ни было, ни за что ни про что",
"ни в грош не ставить" : "not care a straw",
"ни гроша" : "not a stiver #or farthing",
"ни дать ни взять" : "exactly like",
"ни за что" : "not for the world",
"ни за что ни про что" : "for nothing",
"ни к селу ни к городу" : "famil. without rhyme or reason",
"ни кола ни двора" : "neither house nor home",
"ни на йоту" : "not a jot",
"ни на что не годный" : "good-for-nothing",
"ни на что не похоже" : "famil. shocking",
"ни под каким видом" : "on no account",
"ни разу" : "not once never"
};
