var dicct_7 = {
"bank" : "берег, насыпь, банк, окружать валом, запруживать [-удить], класть в банк, быть банкиром, делать вираж накреняться [-ниться]; See also: bank of issue, bank on, banker, banking",
"bank of issue" : "эмиссионный банк",
"bank on" : "полагаться [-ложиться] на",
"banker" : "банкир",
"banking" : "банковое дело",
"bankrupt" : "банкрот, обанкротившийся, делать банкротом; See also: bankruptcy",
"bankruptcy" : "банкротство",
"banks" : "See: bank",
"banner" : "знамя  стяг",
"banns" : "оглашение",
"banquet" : "банкет пир, давать банкет, пировать",
"banshee" : "n  1) ирл., шотл. миф. дух, стоны которого предвещают смерть  2) разг. сирена воздушной тревоги",
"bantam" : "n  1) бентамка (мелкая порода кур)  2) разг. «петух», задира, забияка  3) attr.:  bantam car малолитражка",
"banter" : "подшучивать [-утить] поддразнивать [-нить]",
"baptism" : "крещение",
"baptismal" : "a  относящийся к крещению;  baptismal certificate свидетельство о крещении;  baptismal name имя, данное при крещении",
"baptist" : "баптист",
"baptist(e)ry" : "n  1) баптистерий  2) купель (у баптистов)",
"baptize" : "[о]крестить",
"bar" : "брусок, засов, отмель, бар, стойка, преграда препятствие, запирать на засов, преграждать [-радить], исключать [-чить]; See also: такт, адвокатура",
"bar-keeper" : "буфетчик",
"barb" : "колючка, зубец; See also: barbed wire",
"barbarian" : "варвар, варварский",
"barbaric" : "варварский",
"barbarism" : "варварство",
"barbarous" : "дикий, грубый жестокий",
"barbecue" : "целиком жарить, целиком зажаренная туша",
"barbed wire" : "колючая проволока",
"barbell" : "гантель",
"barber" : "парикмахер",
"barberry" : "барбарис",
"barbiturate" : "n  хим. барбитурат",
"bard" : "певец",
"bare" : "голый обнаженный, пустой, обнажать [-жить] открыть; See also: barefaced, bare-foot, bare-footed, bare-headed, barely",
"bare-foot" : "босиком",
"bare-footed" : "босой",
"bare-headed" : "с непокрытой головой",
"barefaced" : "бесстыдный",
"barefoot" : "босой",
"barely" : "едва",
"barfly" : "n  разг. завсегдатай баров",
"bargain" : "сделка выгодная покупка, [по]торговаться",
"barge" : "баржа; See also: bargeman",
"bargeman" : "лодочник с баржи",
"baritone" : "баритон",
"barium" : "барий",
"bark" : "кора, сдирать кору с, лай, [за]лаять",
"barley" : "ячмень",
"barlow" : "n  амер. большой складной карманный нож (тж. barlow knife)",
"barn" : "амбар",
"barnacle" : "щипцы",
"barney" : "n  разг. шумная ссора",
"barnstorm" : "v  амер. разг.  1) играть в сарае, в случайном помещении (о странствующем актёре)  2) выступать с речами во время предвыборной кампании (в маленьких городках)",
"barnyard" : "n  1) гумно; ток  2) скотный двор",
"barometer" : "барометр",
"baron" : "барон",
"baroness" : "баронесса",
"baronet" : "1. n баронет (титул) 2. v давать титул баронета",
"baronial" : "баронский",
"barony" : "владения барона",
"baroque" : "вычурный",
"barrack" : "барак, казарма",
"barracuda" : "n  зоол. барракуда, морская щука",
"barrage" : "заграждение, заградительный огонь",
"barrel" : "бочка бочонок, ствол, цилиндр, барабан, вал, разливать по бочкам",
"barren" : "неплодородный бесплодный",
"barrette" : "заколка",
"barricade" : "баррикада, [за]баррикадировать",
"barrier" : "барьер застава, препятствие помеха",
"barrister" : "адвокат",
"barrow" : "тачка",
"bartender" : "буфетчик",
"barter" : "товарообмен меновая торговля, [по]менять обменивать [-нять]",
"barton" : "усадьба",
"basal" : "основной",
"basalt" : "базальт",
"base" : "подлый низкий, основа базис фундамент, основание, основывать [-овать]  базировать",
"base-ball" : "бейсбол",
"baseball" : "бейсбол",
"baseboard" : "плинтус",
"baseless" : "без оснований",
"baseline" : "n  1) базисная линия, основание  2) спорт. задняя линия площадки; линия подачи",
"basement" : "подвал подвальный этаж",
"baseness" : "низость",
"bases" : "основание исходный пункт",
"bash" : "удар",
"bashaw" : "паша",
"bashful" : "застенчивый робкий",
"basic" : "основной, основный",
"basically" : "основной, основный",
"basil" : "базилик",
"basilisk" : "роковой",
"basin" : "таз миска, бассейн",
"basis" : "основание исходный пункт, база",
"bask" : "греться",
"basket" : "корзина; See also: basket-ball",
"basket-ball" : "баскетбол",
"basketball" : "баскетбол",
"bass" : " бас, басовый",
"bassi" : "See: basso",
"bassinet(te)" : "n  плетёная колыбель с верхом",
"basso" : "бас",
"basswood" : "n  американская липа",
"bastard" : "внебрачный, поддельный, ломаный, внебрачный ребенок",
"baste" : "поливать жаркое соком, наметывать [наметать]",
"bastion" : "укрепление",
"bat" : "летучая мышь, бита, бить ударять в мяч",
"batch" : "пачка",
"bate" : "ярость",
"bates" : "See: bate",
"bath" : "ванна, купальня, [вы- по]мыть [вы]купать; See also: bath-room, bath-sheet, bath-towel",
"bath-room" : "ванная комната",
"bath-sheet" : "купальная простыня",
"bath-towel" : "купальное полотенце",
"bathe" : "[вы]купаться",
"bathing" : "купание; See also: bathing-hut, bathing-suit",
"bathing-hut" : "кабина",
"bathing-suit" : "купальный костюм",
"bathos" : "ложный пафос",
"bathrobe" : "купальный халат",
"bathroom" : "ванная",
"bathtub" : "ванна",
"batik" : "n  батик",
"batiste" : "батист",
"baton" : "жезл, дирижерская палочка, полицейская дубинка",
"battalion" : "батальон",
"batten" : "планка",
"batter" : "взбитое тесто, сильно бить [по]колотить [от]дубасить; See also: batter down, batter in",
"batter down" : "взламывать [взломать]",
"batter in" : "взламывать [взломать]",
"battery" : "батарея; See also: assault and battery",
"battle" : "битва сражение, сражаться [сразиться], бороться; See also: battle-ax, battle-axe, battle-field, battle-plane, battle-ship",
"battle-ax" : "боевой топор, Am бой-баба",
"battle-axe" : "боевой топор, Am бой-баба",
"battle-field" : "поле битвы",
"battle-plane" : "штурмовик",
"battle-ship" : "линейный корабль",
"battlefield" : "поле боя",
"battleground" : "театр боевых действий",
"batwing" : "a  в форме крыла летучей мыши (о рукаве и т. п.)",
"bauble" : "игрушка",
"baud" : "бод",
"bauxite" : "боксит",
"bawd" : "сводня",
"bawdy" : "непристойный",
"bawl" : "кричать [крикнуть] [за]орать; See also: bawl out",
"bawl out" : "выкрикивать [выкрикнуть]",
"bay" : "гнедой, гнедая лошадь, залив бухта, лавровое дерево, лай, [за]лаять; See also: bring to bay",
"bay-window" : "эркер, брюшко",
"bayed" : "See: bay",
"bayonet" : " штык, колоть штыком",
"bayou" : "заболоченный рукав реки",
"bazaar" : "базар",
"bazar" : "базар",
"be" : ": a) быть бывать, жить, находиться, поживать чувствовать себя, there is are есть, b), c); See also: be about, be at, be off, be on, be reading, be read",
"be a bad sailor" : "страдать морской болезнью",
"be a good sailor" : "не страдать морской болезнью",
"be a match for" : "быть ровней",
"be able" : "мочь быть в состоянии",
"be about" : "собраться",
"be about to do" : "собираться делать",
"be acquainted with" : "быть знакомым с",
"be afflicted" : "страдать",
"be afraid of" : "бояться",
"be alive to" : "ясно понимать",
"be asleep" : "спать",
"be astonished" : "удивляться [-виться]",
"be aware of" : "знать  сознать",
"be badly off" : "быть бедным быть в плохом положении",
"be boged" : "увязать [увязнуть]",
"be carried" : "быть принятым",
"be cast down" : "быть в унынии",
"be closeted with" : "совещаться наедине с",
"be confined" : "рожать [родить]",
"be connected with" : "иметь связи",
"be cut out for" : "быть словно созданным для",
"be delivered" : "разрешиться от бремени родить",
"be down upon" : "нападать [напасть] на",
"be driven ashore" : "наскочить на мель",
"be engaged" : "быть занятым, быть помолвленным",
"be engaged in reading" : "заниматься чтением",
"be fond of" : "любить",
"be for sale" : "продаваться",
"be going to" : "намереваться собираться",
"be good at" : "быть способным к",
"be in a jam" : "быть в затруднительном положении",
"be in a twitter" : "дрожать",
"be in charge of" : "заведовать",
"be in for" : "a) быть обреченным на",
"be in keeping with ..." : "согласоваться с",
"be in mesh" : "сцепляться [-питься]",
"be in need of" : "нуждаться в",
"be in operation" : "быть в действии",
"be in pain" : "испытывать боль",
"be in power" : "быть у власти",
"be in progress" : "развиваться, вестись",
"be in suspense" : "быть нерешенным",
"be in the chair" : "председательствовать",
"be in the secret" : "быть посвященным в секрет",
"be in the swim" : "быть в курсе дела",
"be in transports" : "быть вне себя",
"be in with" : "быть в хороших отношениях с",
"be in work" : "иметь работу",
"be infested with" : "кишеть",
"be itching to " : "гореть желанием",
"be keen on" : "очень любить  страстно увлекаться",
"be keyed up" : "быть в взвинченном состоянии",
"be knocked down" : "попадать под автомобиль и т.п.",
"be lacking" : "недостать",
"be late" : "опаздывать [опоздать]",
"be left" : "остаться",
"be liable to" : "быть предрасположенным к",
"be limited to" : "ограничиться",
"be locateed" : "быть расположенным",
"be long" : "медлить, долго длиться",
"be lost" : "пропадать [-пасть], погибать [-гибнуть], растеряться",
"be mazeed" : "быть растерянным",
"be missing" : "отсутствовать",
"be mistaken" : "ошибаться [-биться]",
"be mix up with" : "быть замешанным в",
"be much accounted of" : "иметь хорошую репутацию",
"be nauseateated" : "испытывать тошноту",
"be not worth-while" : "не стоить труда",
"be of effect" : "вступать в силу",
"be off" : "отправляться [-авиться]",
"be off guards" : "быть недостаточно бдительным",
"be off the air" : "не работать",
"be on" : "быть в действии",
"be on a par with" : "быть наравне на одном уровне с",
"be on bad terms" : "быть в плохих отношениях",
"be on edge" : "быть как на иголках",
"be on fire" : "гореть",
"be on good terms" : "быть в хороших отношениях",
"be on sale" : "продаваться",
"be on strike" : "бастовать",
"be on the air" : "работать",
"be on the point of ger." : "собраться",
"be opposed to" : "быть против",
"be out of keeping with ..." : "не согласоваться с",
"be out of sorts" : "быть не в духе, плохо чувствовать себя",
"be out of work" : "быть безработным",
"be out with" : "быть в ссоре с",
"be pleased to do" : "делать с удовольствием",
"be pleased with" : "быть довольным",
"be possessed" : "быть одержимым",
"be pressed for time" : "спешить",
"be read" : "читаться быть читанным",
"be reading" : "читать",
"be reputeded" : "слыть",
"be right" : "быть правым",
"be seateded" : "сидеть садиться [сесть]",
"be sensible of" : "сознать",
"be serious" : "серьезно говорить",
"be sick for" : "тосковать по",
"be slow" : "отстать",
"be snowed under" : "быть занесенным снегом",
"be stranded" : "быть без средств",
"be susceptible of" : "допускать [-стить]",
"be taken ill" : "заболеть",
"be the craze" : "быть в моде",
"be the wear" : "быть в моде",
"be to blame for" : "быть виноватым в"
};
