var dicctr_0 = {
"﻿а" : "cj. but and; See also: а то, а что{?}",
"а если" : "if ever, whereas",
"а не то" : "else",
"а также" : "as well as",
"а то" : "or else",
"а что" : "why so?, int. ah!, famil. eh?",
"аббат" : "abbot",
"абзац" : "indention, indenture, paragraph",
"абрикос" : "apricot",
"абсолютный" : "stark, unconditioned",
"абстрактный" : "abstractive, noetic, transcendental",
"абсурдный" : "grotesque",
"авангард" : "advance guard, vanguard",
"аванпост" : "outpost",
"аванс" : "advance",
"авансом" : "in advance",
"авансцена" : "proscenium",
"авантюра" : "adventure",
"авантюрист" : "adventurer",
"авантюристка" : "adventuress",
"аварийный" : "emergency...",
"авария" : "accident, wreck",
"август" : "August",
"авель" : "abel",
"авиабаза" : "air base",
"авиабомба" : "air bomb",
"авиаконструктор" : "aircraft designer",
"авиалиния" : "airline",
"авиаматка" : "aircraft carrier",
"авианосец" : "aircraft carrier",
"авиапочта" : "air mail",
"авиаспециалист" : "airman",
"авиатрасса" : "air route",
"авиационный" : "air...",
"авиация" : "aviation, aircraft pl.",
"авиашкола" : "flying school",
"авокадо" : "avocado",
"авось" : "famil. perhaps maybe; See also: на авось",
"австралиец" : "Australian",
"австралийка" : "Australian",
"австралийский" : "Australian",
"австралия" : "Australia",
"австриец" : "Austrian",
"австрийка" : "Austrian",
"австрийский" : "Austrian",
"австрия" : "Austria",
"автобиографический" : "autobiographic",
"автобиографичный" : "autobiographic",
"автобиография" : "autobiography",
"автобус" : "bus",
"автогонки" : "race",
"автограф" : "autograph",
"автожир" : "autogiro",
"автозавод" : "car factory automobile plant",
"автоклав" : "autoclave",
"автократия" : "autocracy",
"автомагистраль" : "highway",
"автомат" : "automaton, slot machine, submachine gun",
"автоматизировать" : "automate",
"автоматический" : "automatic",
"автоматичный" : "automatic",
"автоматчик" : "submachine gunner",
"автомашина" : "s. автомобиль",
"автомобилист" : "motorist",
"автомобиль" : "car; See also: гоночный автомобиль",
"автомобильный" : "vehicular",
"автономия" : "autonomy",
"автономный" : "autonomous",
"автор" : "author",
"авторизовать" : "pf. authorize",
"авторитарный" : "authoritarian",
"авторитет" : "authority",
"авторский" : "author's",
"авторское право" : "copyright",
"авторство" : "authorship",
"авторучка" : "fountain pen",
"автострада" : "highway",
"автотрансформатор" : "autotransformer",
"ага" : "aha!, I see!",
"агат" : "agate",
"агафья" : "Agatha",
"агент" : "agent",
"агентство" : "agency",
"агентура" : "agency",
"агитационный" : "agitation... propaganda...",
"агитировать" : "agitate",
"агитка" : "leaflet",
"агитпроп" : ", pol. agitation and propaganda department",
"агитпункт" : "agitation center",
"аграрный" : "agrarian",
"агрессивный" : "aggressive",
"агрессия" : "aggression",
"агрикультура" : "agriculture",
"агроном" : "agriculturist",
"агрономический" : "agronomic",
"агрономия" : "agronomy",
"ад" : "hell",
"адам" : "Adam",
"адаптер" : "pickup",
"адвокат" : "lawyer, attorney  Brt. barrister, solicitor",
"адвокатура" : "jur. bar",
"административный" : "administrative",
"администрация" : "administration",
"адмирал" : "admiral",
"адмиралтейство" : "admiralty",
"адрес" : "address",
"адресат" : "addressee, consignee",
"адресатка" : "addressee, consignee",
"адресный" : "адресный стол register-office",
"адский" : "hellish, infernal, sulphurous",
"адъютант" : "aide",
"ажиотаж" : "boom",
"азалия" : "azalea",
"азартный" : "venturesome",
"азиатский" : "Asian, Asiatic",
"азимут" : "azimuth",
"азия" : "Asia; See also: Малая Азия",
"азовский" : "Asov...",
"азот" : "nitrogen",
"азотистый" : "nitrous",
"азотный" : "nitric",
"азы" : "elementaries",
"аист" : "stork",
"аистовый" : "stork...",
"ай" : "ah! oh!",
"айва" : "quince",
"айсберг" : "berg, iceberg",
"академик" : "academician, graduate",
"академический" : "academic",
"академия" : "academy; See also: Академия наук, Академия художеств",
"академия наук" : "Academy of Sciences",
"академия художеств" : "Academy of Arts",
"акация" : "acacia",
"акварель" : "water color",
"аквариум" : "aquarium",
"акклиматизация" : "acclimate, acclimation, acclimatization",
"акклиматизировать" : "pf. acclimatize",
"аккомпанемент" : "accompaniment",
"аккомпанировать" : "accompany",
"аккорд" : "chord",
"аккордный" : "аккордная работа piecework",
"аккуратный" : "natty, neat, trim",
"акр" : "acre, acreage",
"акробат" : "acrobat, contortionist, equilibrist",
"акрополь" : "acropolis",
"аксиома" : "axiom",
"активировать" : "activate",
"актриса" : "actress",
"акула" : "shark",
"акушерка" : "midwife, obstetrician",
"акушерский" : "obstetric, obstetrical",
"акушерство" : "midwifery",
"акцент" : "accent, stress",
"акцептовать" : "pf. accept",
"акции" : "stock",
"акционер" : "stockholder Brt. shareholder",
"акционерный" : "joint-stock",
"акция" : "share, a. stock",
"албанец" : "Albanian",
"албания" : "albania",
"албанка" : "Albanian",
"албанский" : "Albanian",
"алгебра" : "algebra",
"алгебраический" : "algebraic",
"алебастр" : "alabaster",
"алексей" : "Alexis",
"алергический" : "allergic",
"алеть" : "blush grow crimson, glow",
"алжир" : "Algeria, Algiers",
"алименты" : "alimony",
"алкоголик" : "alcoholic",
"алкоголь" : "alcohol",
"аллах" : "allah",
"аллегорический" : "allegorical",
"аллегория" : "allegory",
"аллея" : "avenue alley",
"аллигатор" : "alligator",
"алло" : "hullo",
"алмаз" : "diamond",
"алмазный" : "diamond",
"алоэ" : "aloe",
"алтарь" : "altar",
"алфавит" : "alphabet",
"алфавитный" : "alphabetical",
"алхимия" : "alchemy",
"алчность" : "greed",
"алчный" : "greedy",
"алый" : "crimson",
"альбатрос" : "albatross, mallemuck",
"альбом" : "album, sketchbook",
"альманах" : "almanac",
"альпийский" : "alpine",
"альпинизм" : "mountain climbing Alpinism",
"альпинист" : "climber Alpinist",
"альпинистка" : "climber Alpinist",
"альпы" : "Alps",
"альт" : "alto",
"альтруизм" : "altruism",
"альфа" : "от альфы до омеги",
"аляска" : "alaska",
"амбар" : "barn, granary, grange",
"амбулатория" : "ambulance station dispensary",
"амбулаторный" : "амбулаторный больной outpatient",
"амеба" : "amoeba",
"американизм" : "americanism",
"американский" : "american, yankee",
"аметист" : "amethyst",
"аминь" : "amen",
"аммиачный" : "ammoniac, ammoniacal",
"аморальный" : "amoral",
"ампер" : "ampere",
"амперметр" : "ammeter",
"амстердам" : "amsterdam",
"амулет" : "joss, periapt",
"амуниция" : "ammunition",
"амур" : "amur, cupid",
"амфибия" : "amphibian",
"амфитеатр" : "amphitheater, thea. circle",
"анализ" : "analysis",
"анализировать" : "analyze",
"аналитик" : "analyst",
"аналитический" : "analytic",
"аналог" : "analog, analogue",
"аналогичный" : "analogous similar",
"аналогия" : "analogy",
"ананас" : "pineapple",
"анархия" : "anarchy",
"анатомировать" : "pf. anatomize",
"анатомический" : "anatomical",
"анатомия" : "anatomy",
"анахронизм" : "anachronism",
"ангар" : "hangar",
"ангел" : "angel",
"ангина" : "quinsy tonsillitis",
"англизировать" : "anglicize",
"английская булавка" : "safety pin",
"английский" : "English",
"английский ключ" : "monkey wrench",
"англиканский" : "anglican",
"англичанин" : "Englishman",
"англичанка" : "Englishwoman",
"англия" : "England",
"андрей" : "Andrew",
"анды" : "Andes",
"анекдот" : "anecdote",
"анемия" : "anemia",
"анестезия" : "anesthesia",
"анилин" : "aniline",
"анис" : "anise",
"анкара" : "Ankara"
};
