var dicctr_43 = {
"нагружать" : "load, a. burden busy assign",
"нагруженный" : "laden",
"нагрузить" : "load embark",
"нагрузка" : "load, a. burden job assignment",
"нагрянуть" : "pf. appear come suddenly unawares, break out, take by surprise",
"над" : "over above, at, about, with",
"надавить" : "press, push, press out",
"надавливать" : "press, push, press out",
"надбавить" : "s. набавлять",
"надбавка" : "raise increase, extra charge",
"надбавлять" : "s. набавлять",
"надбровный" : "superciliary",
"надвигать" : "push, pull, -ся approach draw near, cover",
"надвигаться" : "impend",
"надвигающийся" : "oncoming",
"надвинуть" : "push, pull, -ся approach draw near, cover",
"надвое" : "in two",
"надгробие" : "gravestone",
"надгробный" : "tomb... grave...",
"надевать" : "put on",
"надежда" : "hope; See also: подавать надежды",
"надежный" : "reliable dependable, firm, safe, sure",
"надел" : "lot plot allotment",
"наделать" : "pf. make, do cause inflict",
"наделать шуму" : "cause a sensation",
"наделить" : "allot, give endow",
"наделять" : "allot, give endow",
"надеть" : "put on",
"надеющийся" : "hopeful",
"надеяться" : "hope, rely",
"надземный" : "overground, Brt. high-level...",
"надзиратель" : "supervisor, inspector, jailer",
"надзор" : "supervision, surveillance",
"надир" : "nadir",
"надколенная чашка" : "kneecap",
"надкрылье" : "elytron, shard, sherd",
"надламывать" : "crack break, shatter",
"надлежать" : "have to be to be  p.pt.",
"надлежащий" : "appropriate suitable; See also: надлежащим образом",
"надлежащим образом" : "properly duly",
"надлом" : "crack fissure, fig. crisis",
"надломать" : "crack break, shatter",
"надломить" : "crack break, shatter",
"надлунный" : "superlunary",
"надменный" : "haughty",
"надо" : "over above, at, about, with",
"надобность" : "need  necessity, affair matter",
"надоедать" : "tire, bother molest, мне надоел ... I'm tired  fed up",
"надоедливый" : "tiresome, troublesome annoying",
"надоесть" : "tire, bother molest, мне надоел ... I'm tired  fed up",
"надолго" : "for long",
"надорвать" : "s. надрывать",
"надписать" : "superscribe, commerc. endorse",
"надписывать" : "superscribe, commerc. endorse",
"надпись" : "inscription, commerc. endorsement",
"надпочечный" : "adrenal, suprarenal",
"надрез" : "cut incision",
"надрезать" : "cut incise",
"надрезывать" : "cut incise",
"надругательство" : "outrage",
"надрыв" : "rent tear, strain burst",
"надрывать" : "tear, shatter break undermine, injure, strain; See also: надрывать животики, надрываться",
"надрывать животики" : "split one's sides",
"надрываться" : "split one's sides",
"надсмотр" : "supervision",
"надсмотрщик" : "supervisor",
"надстраивать" : "overbuild, raise",
"надстроить" : "overbuild, raise",
"надстройка" : "superstructure",
"надувательство" : "dupery, humbug, trickery",
"надувать" : "inflate swell, drift blow, famil. dupe, надуть губы pout, -ся",
"надувной" : "inflatable air...",
"надуманный" : "far-fetched strained",
"надумать" : "pf. think  devise, make up one's mind",
"надутый" : "swollen, sulky",
"надуть" : "inflate swell, drift blow, famil. dupe, надуть губы pout, -ся",
"надуться" : "swell, famil. sulk be angry with, o.s. airs",
"надымить" : "smoke, steam",
"надя" : "dim. #of Надежда",
"наедаться" : "eat one's fill",
"наедине" : "alone in private, tete-a-tete",
"наезд" : "short #or flying visit run",
"наездник" : "horseman equestrian, trainer",
"наезжать" : "run into knock against, come across, famil. come  call on, run",
"наем" : "hire, rent",
"наемник" : "hireling mercenary",
"наемный" : "hired rent, hackney mercenary",
"наесться" : "eat one's fill",
"наехать" : "run into knock against, come across, famil. come  call on, run",
"нажать" : "s. нажимать",
"наждак" : "emery",
"наждачный" : "emery",
"нажива" : "profit gain, a. = наживка",
"наживать" : "earn gain profit amass, make, get catch",
"наживка" : "bait",
"нажим" : "pressure, stress strain",
"нажимать" : "press push, stress",
"нажить" : "earn gain profit amass, make, get catch",
"назавтра" : "famil. the next day, tomorrow",
"назад" : "back, назад! get back!; See also: тому назад",
"назади" : "famil. behind",
"название" : "name, title",
"назвать" : "s. называть",
"наземный" : "land... ground...",
"наземь" : "famil. to the ground",
"назидание" : "edification, instruction",
"назидательный" : "edifying instructive",
"назло" : "to spite",
"назначать" : "appoint  designate, fix settle, prescribe, destine, famil. assign",
"назначение" : "appointment, assignment, prescription, destination",
"назначить" : "appoint  designate, fix settle, prescribe, destine, famil. assign",
"назойливый" : "importunate",
"назревать" : "ripen, swell, med. gather, fig. mature, be imminent #or impending",
"назреть" : "ripen, swell, med. gather, fig. mature, be imminent #or impending",
"назубок" : "famil. by heart thoroughly",
"называть" : "call name, mention, называть себя introduce o.s., famil. invite, называть вещи своими именами, call a spade a spade",
"называться" : "call o.s. be called, как называется ...? what is ...?",
"наи" : "#in compds. ... of all very",
"наибольший" : "maximum, most",
"наивность" : "naivete",
"наивный" : "naif",
"наизусть" : "by heart, rote",
"наилучший" : "optimal, topflight",
"наименьший" : "least, smallest",
"наихудший" : "worst",
"найденный" : "found",
"найденыш" : "foundling",
"наймит" : "hireling mercenary",
"найти" : "s. находить",
"найтись" : "be, happen to have, not to be at a loss",
"наказ" : "order, mandate",
"наказание" : "punishment, penalty, famil. nuisance",
"наказать" : "punish, obsol. order",
"наказуемый" : "punishable",
"наказывать" : "punish, obsol. order",
"накал" : "incandescence",
"накаленный" : "incandescent red-hot",
"накаливать" : "incandesce",
"накалить" : "incandesce",
"накалывать" : "pin fix, chop break, prick, kill",
"накануне" : "the day before, ~ on the eve",
"накапливать" : "accumulate amass, collect gather",
"накатка" : "knurl",
"накидка" : "cape cloak",
"накидывать" : "накидать throw, накинуть throw upon, famil. add, raise, -ся famil. fall on",
"накипь" : "scum, scale deposit",
"накладная" : "waybill",
"накладной" : "laid on, plated, false, commerc. overhead",
"накладывать" : "lay  apply, put  set, impose, leave, fill, pack load",
"наклеветать" : "slander",
"наклеивать" : "glue #or paste on, stick on affix",
"наклеить" : "glue #or paste on, stick on affix",
"наклейка" : "label",
"наклон" : "inclination, slope",
"наклонение" : "s. наклон, gr. mode mood",
"наклонить" : "bend bow, fig. incline, drive at, obsol. cast down, меня клонит ко сну I am sleepy",
"наклонный" : "inclined slanting",
"наклонять" : "bend tilt, bow stoop, obsol. incline, -ся",
"наковальня" : "anvil",
"накожный" : "skin... cutaneous",
"наколоть" : "pin fix, chop break, prick, kill",
"наконец" : "at last finally, at length",
"наконечник" : "ferrule, tip point",
"накопить" : "save, store up",
"накопление" : "accumulation, milit. concentration",
"накоплять" : "accumulate amass, collect gather",
"накопляться" : "accrue",
"накормить" : "feed; See also: кормить грудью",
"накрахмаленный" : "starched",
"накрахмалить" : "starch",
"накрашенный" : "painted rouged",
"накренить" : "list",
"накрепко" : "fast tightly firmly",
"накрест" : "crosswise",
"накрошить" : "crumb, popul. crush",
"накрывать" : "cover, lay, serve, milit. hit, popul. catch trap, dupe",
"накрыть" : "cover, lay, serve, milit. hit, popul. catch trap, dupe",
"накупать" : "buy",
"накупить" : "buy",
"накуривать" : "smoke #or perfume scent",
"накурить" : "smoke #or perfume scent",
"налагать" : "lay  apply, put  set, impose, leave, fill, pack load",
"наладить" : "put right #or in order get straight fix, set going, establish, tune",
"налаживать" : "put right #or in order get straight fix, set going, establish, tune",
"налево" : "to #or on the left, s. направо",
"налегать" : "press  fig. oppress, apply o.s., lie, sink cover, famil. stress",
"налегке" : "famil. with light #or no baggage, lightly dressed",
"налет" : "flight, blast, av. raid attack, med. fur, touch, с налета on the wing with a swoop, cf. лет",
"налетать" : "fly, swoop down, raid attack, fall, rush squall",
"налететь" : "fly, swoop down, raid attack, fall, rush squall",
"налетчик" : "bandit",
"налечь" : "press  fig. oppress, apply o.s., lie, sink cover, famil. stress",
"наливать" : "pour, fill, ripen, p.pt.p. ripe, plump, sappy",
"наливка" : "liqueur",
"наливное судно" : "tanker",
"наливной" : "p.pt.p.",
"налим" : "burbot",
"налиновать" : "rule",
"налитой" : "s. наливать",
"налить" : "pour, fill, ripen, p.pt.p. ripe, plump, sappy",
"налицо" : "present on hand",
"наличие" : "presence",
"наличность" : "stock, cash, a. = наличие, в наличности = налицо",
"наличный" : "cash  ready, present on hand, за наличные cash",
"налог" : "tax duty levy",
"налогоплательщик" : "taxpayer",
"наложенным платежом" : "cash on delivery",
"наложить" : "lay  apply, put  set, impose, leave, fill, pack load",
"наложить вето" : "veto",
"налощить" : "gloss polish",
"налюбоваться" : "pf. admire to one's heart's content; See also: не налюбоваться",
"намазывать" : "s. мазать",
"намалевать" : "paint daub",
"намарать" : "scribble daub",
"наматывать" : "s. мотать",
"намедни" : "popul. recently the other day",
"намек" : "allusion  hint",
"намекать" : "allude  hint",
"намекнуть" : "allude  hint",
"намереваться" : "intend = намерен",
"намерение" : "intention design purpose",
"намеренный" : "intentional deliberate",
"наместник" : "governor",
"наметать" : "s. наметывать",
"наметить" : "s. намечать",
"наметка" : "draft plan, tack, a. метать",
"наметывать" : "draft plan, tack, a. метать",
"намечать" : "mark trace, design plan, select, nominate",
"намного" : "much far",
"намокать" : "get wet",
"намокнуть" : "get wet",
"намордник" : "muzzle",
"наморщить" : "wrinkle frown, distort",
"намотать" : "reel wind, once мотнуть shake wag, beckon point, jerk, famil. промотать squander waste",
"намочить" : "wet moisten, soak step",
"намудрить" : "subtilize, quibble, trick, bully",
"намылить" : "soap; See also: мылить голову",
"намякнуть" : "become soft",
"нанести" : "s. наносить",
"нанизать" : "string",
"нанизывать" : "string",
"нанимать" : "hire engage rent, famil. lodge, -ся a. hire out",
"нанка" : "nankeen",
"нанкин" : "nanking",
"наново" : "anew again",
"нанос" : "alluvium",
"наносить" : "bring, carry waft deposit wash ashore, heap, enter mark, lay on apply, inflict  cause, pay, deal",
"наносный" : "alluvial, fig. casual assumed",
"нанять" : "hire engage rent, famil. lodge, -ся a. hire out",
"наоборот" : "the other way round vice versa conversely, on the contrary"
};
