var dicctr_6 = {
"булочная" : "bakery",
"булочник" : "baker",
"булыжник" : "cobblestone",
"бульвар" : "boulevard avenue",
"бульварная пресса" : "gutter press",
"бульварный" : "boulevard...; See also: бульварный роман, бульварная пресса",
"бульварный роман" : "dime novel Brt. penny dreadful",
"бульдог" : "bulldog",
"булькать" : "gurgle",
"бульон" : "broth bouillon",
"бумага" : "paper, document",
"бумажка" : "slip of paper, popul. note",
"бумажная" : "pulp",
"бумажник" : "wallet",
"бумажный" : "paper..., cotton...",
"бумазея" : "fustian",
"бумеранг" : "boomerang",
"бункер" : "bin, bunker",
"бунт" : "revolt mutiny insurrection uprising, bale pack",
"бунтарский" : "rebellious",
"бунтарь" : "= бунтовщик",
"бунтовать" : "rebel revolt",
"бунтовской" : "rebellious mutinous",
"бунтовщик" : "mutineer rebel",
"бура" : "borax",
"бурав" : "drill auger",
"буравить" : "bore drill",
"буран" : "snowstorm blizzard",
"бурда" : "wash wish-wash",
"бурдюк" : "wineskin",
"буревестник" : "petrel",
"бурение" : "drilling boring",
"буржуа" : "bourgeois",
"буржуазия" : "bourgeoisie",
"буржуазный" : "bourgeois...",
"буржуй" : "s. буржуа",
"буржуйка" : "s. буржуа",
"бурить" : "bore",
"бурка" : "felt cloak",
"бурлак" : "hauler",
"бурлить" : "rage, seethe",
"бурмистр" : "steward, mayor",
"бурный" : "stormy storm..., violent boisterous",
"бурун" : "surf",
"бурчанье" : "grumbling, rumbling",
"бурчать" : "mumble, grumble, rumble",
"буры" : "Boers",
"бурый" : "brown fulvous; See also: бурый уголь",
"бурый уголь" : "brown coal lignite",
"бурьян" : "wild grass",
"буря" : "storm tempest",
"бусинка" : "bead",
"бусы" : "coll. beads",
"бутадиен" : "butadiene",
"бутан" : "butane",
"бутафория" : "pl.",
"бутерброд" : "sandwich",
"бутон" : "bud",
"бутсы" : "football boots",
"бутылка" : "bottle",
"бутылочка" : "small bottle",
"бутыль" : "large bottle, carboy",
"буф" : "puff, рукав буфом puffed sleeve",
"буфер" : "buffer",
"буфет" : "sideboard, bar lunchroom refreshment room",
"буфетчик" : "barkeeper",
"буфетчица" : "barmaid",
"буффон" : "buffoon",
"бух" : "bounce! plump!",
"буханка" : "loaf",
"бухара" : "Bokhara",
"бухарест" : "Bucharest",
"бухать" : "plump",
"бухгалтер" : "bookkeeper",
"бухгалтерия" : "bookkeeping",
"бухгалтерский" : "bookkeeper... bookkeeping...",
"бухнуть" : "plump",
"бухта" : "bay, coil",
"бухточка" : "cove, covey",
"бушевать" : "roar rage storm",
"бушлат" : "jacket",
"бушприт" : "bowsprit",
"буян" : "brawler rowdy ruffian",
"буянить" : "brawl riot kick up a row",
"бы" : "#short б, #is #used #to #render #subjunctive #and #conditional #patterns:, a) #with #the #preterite e.g. я сказал бы если ~ знал, I would say it if I knew it, b) #with #the #infinitive e.g.:, все ~ ему знать he would like to know everything, не вам ~ говорить you had better be quiet",
"бывалый" : "experienced, former, common, cf. бывать",
"бывать" : "occur happen, как ни в чем не бывало as if nothing had happened, он бывало гулял he would go for a walk, боли как не бывало famil. the pain had entirely disappeared, побывало be  visit stay",
"бывший" : "former late ex-...",
"бык" : "bull, abutment",
"был" : "was",
"былина" : "Russian epic",
"былинка" : "blade of grass",
"было" : "already:, я уже заплатил было деньги ..., I had already paid the money ..., almost nearly was just going to ..., я чуть ~ не сказал, I was on the point of saying I nearly said",
"былое" : "past",
"былой" : "bygone former",
"быль" : "true story #or occurrence, past",
"быстро" : "apace, pronto, quickly",
"быстроногий" : "swift",
"быстрота" : "quickness swiftness rapidity",
"быстроходный" : "fast",
"быстрый" : "quick fast swift",
"быт" : "way of life manners pl.",
"бытие" : "existence being, #Bibl. Genesis",
"бытность" : "stay, в мою бытность в during my stay in while staying in",
"бытовой" : "of manners popular genre, common everyday",
"быть" : "be, ~ ... will be #or happen, мне было ..., I was ...; See also: как быть{?}, так и быть{!}, будь что будет, будь по-вашему, будьте добры",
"быть в курсе" : "be posted on",
"быть вне себя" : "be beside o.s.",
"быть впору" : "fit",
"быть вправе" : "have the right",
"быть к лицу" : "suit #or become a pers.",
"быть на побегушках" : "famil. run errands",
"быть на хорошем счету" : "stand high favor",
"быть ни при чем" : "pers.'s fault",
"быть по вкусу" : "be to one's taste relish s.th.",
"быть похожим" : "look like",
"быть при" : "have, be attached to",
"быть против" : "object mind",
"бычий" : "bovine",
"бювар" : "writing case",
"бюджет" : "budget",
"бюджетный" : "budget",
"бюллетень" : "bulletin, ballot Brt. voting paper, medical certificate",
"бюретка" : "buret",
"бюро" : "office bureau; See also: справочное бюро, бюро путешествий",
"бюро находок" : "lost-property office",
"бюро путешествий" : "travel bureau Brt. tourist office",
"бюрократ" : "bureaucrat",
"бюрократизм" : "red tape",
"бюрократический" : "bureaucratic",
"бюрократия" : "bureaucracy",
"бюст" : "bust",
"бюстгальтер" : "bra",
"бязь" : "cheap cotton goods",
"в" : ":, to into, for, в окно out of the window, in at on within, в среду on Wednesday, в два часа at two o'clock, at of, в день a #or per day, длиной в четыре метра four meters long, чай в семь рублей килограмм, tea at 7 roubles a kilo, в десять раз больше ten times as much, to the rank of, идти в солдаты become a soldier, :, in at on, in, в конце года, at the end of the year, в пяти километрах от, five kilometers from",
"в долгу" : "indebted",
"в духе" : "in a good temper #or in high spirits",
"в запасе" : "in stock on hand",
"в здравом уме" : "in one's senses",
"в знак" : "in token of",
"в исправности" : "intact in good order, accurate correct, diligent industrious",
"в конец" : "completely",
"в конечном счете" : "ultimately",
"в конце" : "at the end of",
"в конце концов" : "at long last",
"в корне" : "totally",
"в коротких словах" : "in a few words",
"в котором часу" : "what time?",
"в летах" : "elderly advanced in years",
"в лицо" : "by sight, to s.b.'s face",
"в месяц" : "a month per month",
"в моем духе" : "to my taste",
"в моих глазах" : "in my view #or opinion",
"в настоящее время" : "at present",
"в натуре" : "in kind",
"в недоумении" : "at a loss",
"в нерешительности" : "at a loss",
"в оба конца" : "there & back",
"в оборот" : "famil. to task",
"в один голос" : "unanimously",
"в один конец" : "one way",
"в одиночку" : "alone",
"в отдельности" : "individually",
"в отличие от" : "as against",
"в отместку" : "in revenge",
"в пользу" : "in favor of",
"в придачу" : "to boot",
"в противном случае" : "otherwise failing which",
"в прошлом году" : "last year",
"в пух" : "to pieces, utterly totally, famil. over",
"в расчете" : "quits",
"в розницу" : "by retail",
"в самый раз" : "just in time famil.",
"в свою очередь" : "in my etc. turn",
"в силу" : "by virtue",
"в складчину" : "by clubbing",
"в скором времени" : "soon",
"в совершенстве" : "a. perfectly",
"в сопровождении" : "accompanied",
"в стороне" : "aloof apart",
"в сторону" : "aside apart",
"в то время" : "at that time",
"в то время как" : "whereas",
"в то же время" : "at the same time",
"в угоду" : "for s.b.",
"в упор" : "point-blank straightforward",
"в хвосте" : "behind",
"в целости" : "intact",
"в этом году" : "this year",
"в этот день" : "that day",
"ваал" : "baal",
"вавилон" : "Babylon",
"вагон" : "car",
"вагонетка" : "lorry trolley truck",
"вагоновожатый" : "streetcar driver",
"вагон-ресторан" : "dining car",
"вади" : "wadi",
"важнейший" : "cardinal",
"важничать" : "put on airs",
"важность" : "importance, conceit",
"важный" : "important significant, haughty, famil. неважно rather bad, это неважно that doesn't matter #or is of no importance",
"ваза" : "vase bowl",
"вакансия" : "vacancy",
"вакантный" : "vacant",
"вакса" : "polish blacking",
"вакцина" : "vaccine",
"вакцинация" : "vaccinate, vaccination",
"вал" : "rampart, bank, wall, billow, engin. shaft axle",
"валгалла" : "valhalla",
"валежник" : "brushwood",
"валенок" : "felt boot",
"валентность" : "atomicity, valence, valency",
"валерьянка" : "валерьяновые капли /pl. valerian",
"валерьяновый" : "валерьяновые капли /pl. valerian",
"валик" : "bolster",
"валиться" : "topple",
"валлиец" : "taffy",
"валлийский" : "welsh",
"валун" : "boulder",
"вальдшнеп" : "woodcock",
"вальс" : "waltz",
"вальс-бостон" : "boston",
"вальсировать" : "waltz",
"вальцевать" : "engin. roll",
"валюта" : "currency; See also: золотая валюта",
"валютный" : "currency... exchange...",
"валютный курс" : "rate of exchange",
"валять" : "roll, knead, full, popul. валяй! go!; See also: валять дурака",
"валять дурака" : "idle play the fool",
"валяться" : "wallow loll, lie about",
"вампир" : "ghoul, vampire",
"ванадий" : "vanadium",
"ваниль" : "vanilla",
"ванильный" : "vanilla",
"ванна" : "tub, bath, солнечная ванна sun bath, принять ванну take a bath",
"ванная" : "bath",
"ванька" : "s. Ваня; See also: ванька-встанька",
"ванька-встанька" : "tumbler",
"ваня" : "dim. #of Иван John",
"варан" : "varan",
"варвар" : "barbarian",
"варвара" : "Barbara Babette",
"варварский" : "barbarous",
"варварство" : "barbarity",
"варган" : "jew,s-harp",
"варежка" : "mitten",
"варение" : "= варка",
"вареник" : "boiled pieces of paste enclosing curd #or fruit",
"вареный" : "cooked boiled",
"варенье" : "jam preserves pl."
};
