var dicctr_76 = {
"реабилитация" : "whitewash",
"реабилитировать" : "pf. rehabilitate",
"реагировать" : "react, respond",
"реактивный" : "reactive, jet",
"реакционер" : "reactionary",
"реакционный" : "reactionary",
"реакция" : "reaction",
"реализм" : "realism",
"реализовать" : "pf. realize, a. sell",
"реалистический" : "realistic",
"реальность" : "reality",
"реальный" : "real, realistic",
"ребенок" : "child, baby famil. kid; See also: грудной ребенок",
"ребро" : "rib, edge",
"ребром" : "fig. point-blank",
"ребята" : "pl. #of ребенок, famil. boys",
"ребяческий" : "childish",
"ребячество" : "childishness",
"ребячий" : "childish",
"ребячиться" : "behave childishly",
"рев" : "roar, bellow, howl",
"реванш" : "revenge, return match",
"ревень" : "rhubarb",
"реверанс" : "curtsey",
"реветь" : "roar, bellow, howl, famil. cry",
"ревизия" : "inspection, auditing, revision",
"ревизор" : "inspector, auditor",
"ревматизм" : "rheumatism",
"ревматический" : "rheumatic",
"ревнивый" : "jealous",
"ревновать" : "be jealous",
"ревностный" : "zealous eager",
"ревность" : "jealousy, zeal eagerness",
"револьвер" : "revolver",
"революционер" : "revolutionary",
"революционный" : "revolutionary",
"революция" : "revolution",
"регалии" : "regalia",
"регата" : "regatta",
"регистр" : "register, index",
"регистратура" : "registry",
"регистрация" : "registration",
"регистрировать" : "register, index",
"регламент" : "order regulations pl.",
"регресс" : "retrogression",
"регулировать" : "regulate, settle",
"регулярный" : "regular",
"регулятор" : "regulator",
"редактировать" : "edit redact",
"редактор" : "editor",
"редакционный" : "editorial",
"редакция" : "editorial staff, editorship, editor's office, wording text version, redaction, desk",
"редеть" : "thin",
"редиска" : "radish",
"редкий" : "rare, thin sparse, scarce, a. seldom",
"редко" : "rarely, seldom",
"редкость" : "rarity curiosity, sparsity thinness, uncommon, на редкость famil. extremely awfully",
"редька" : "radish",
"режим" : "regime, conditions pl., regulations pl. order",
"режиссер" : "stage manager, director producer",
"режиссировать" : "stage",
"режущий" : "cutting, trenchant",
"резать" : "разрезать cut, carve, зарезать slaughter kill, вырезать carve cut, срезать cut off, famil. fail, impf. hurt, famil. say, popul. talk, -ся famil. cut, gamble",
"резвиться" : "frolic frisk gambol",
"резвый" : "frisky sportive frolicsome, quick, lively",
"резерв" : "reserve",
"резервист" : "reservist",
"резервный" : "reserve...",
"резервуар" : "reservoir",
"резец" : "incisor",
"резина" : "rubber",
"резинка" : "eraser rubber, elastic",
"резиновый" : "rubber...",
"резкий" : "sharp keen, biting piercing, acute, harsh shrill, glaring, rough abrupt",
"резкость" : "sharpness s. резкий, harsh word",
"резной" : "carved",
"резня" : "slaughter",
"резолюция" : "resolution, decision",
"резон" : "reason",
"резонанс" : "resonance",
"резонировать" : "resonate",
"резонный" : "reasonable",
"результат" : "result",
"резус" : "bandar, rhesus",
"резьба" : "carving",
"резьба по дереву" : "wood engraving",
"резюме" : "summary",
"резюмировать" : "pf. summarize",
"рейд" : "nav. road, milit. raid",
"рейн" : "Rhine",
"рейнский" : "rhenish",
"рейс" : "trip, voyage, flight",
"рейх" : "reich",
"река" : "river stream",
"реквизировать" : "commandeer",
"реклама" : "advertising, advertisement, publicity",
"рекламирование" : "advertising, puffery",
"рекламировать" : "pf. advertise, boost, claim complain",
"рекламный" : "advertising",
"рекомендательный" : "of recommendation",
"рекомендация" : "recommendation, reference",
"рекомендовать" : "a. порекомендовать recommend advise, obsol. introduce",
"реконструировать" : "pf. reconstruct",
"рекорд" : "record",
"рекордный" : "record...",
"рекордсмен" : "champion",
"рекордсменка" : "champion",
"рекрут" : "dogface, rookie",
"ректор" : "president chancellor rector",
"реле" : "relay",
"религиозность" : "religiosity, religiousness",
"религиозный" : "religious",
"религия" : "religion",
"реликвия" : "relic",
"реликтовый" : "relict",
"рельс" : "rail, track",
"рельсовый" : "rail, track",
"ремень" : "strap, belt",
"ремесленник" : "craftsman artisan, fig. bungler",
"ремесленный" : "trade..., handicraft..., home-made, bungling",
"ремесло" : "trade craft, occupation",
"ремонт" : "repair, remount",
"ремонтировать" : "repair",
"ремонтный" : "repair",
"рений" : "rhenium",
"рента" : "rent, revenue, annuity",
"рентабельный" : "profitable",
"рентген" : "roentgen",
"рентгеновские лучи" : "X-rays",
"рентгеновский" : "рентгеновский снимок; See also: рентгеновские лучи",
"реостат" : "rheostat",
"репа" : "turnip",
"репатриировать" : "pf. repatriate",
"репейник" : "bur, agrimony",
"репертуар" : "repertoire repertory",
"репетировать" : "rehearse",
"репетитор" : "coach",
"репетиция" : "rehearsal",
"реплика" : "retort, thea. cue",
"репортаж" : "report",
"репортер" : "reporter",
"репрессалия" : "reprisal",
"репрессивный" : "repressive",
"репрессия" : "reprisal",
"реприз" : "reprise",
"репс" : "rep",
"репутация" : "reputation, repute",
"ресницы" : "eyelash",
"реснички" : "cilia",
"респиратор" : "breather, respirator",
"республиканский" : "republic, republican",
"ресторан" : "restaurant",
"ресурсы" : "resources",
"ретивый" : "zealous, mettlesome",
"ретроактивный" : "retroactive",
"ретушировать" : "pf. отретушировать retouch",
"реферат" : "report paper",
"референдум" : "referendum",
"рефлектор" : "reflector",
"реформа" : "pf. reform",
"реформатор" : "reformer",
"реформировать" : "pf. reform",
"рецензент" : "reviewer",
"рецензировать" : "review",
"рецензия" : "review",
"рецепт" : "recipe",
"рецептор" : "receptor",
"рецидив" : "relapse",
"речевой" : "speech...",
"речитатив" : "recitative",
"речка" : "river",
"речной" : "river...",
"речь" : "speech, discourse talk conversation, word, об этом не может быть и речи that is out of the question, cf. идти",
"речь идет о" : "the question #or matter is, it is a question #or matter, ... is at stake",
"решать" : "solve, decide resolve, dare risk, не решаться hesitate",
"решающий" : "decisive",
"решение" : "decision, solution",
"решетка" : "grating, lattice, trellis, grate",
"решето" : "sieve",
"решетчатый" : "trellis",
"решимость" : "determination",
"решительный" : "resolute firm, decisive, definite, absolute",
"решить" : "solve, decide resolve, dare risk, не решаться hesitate",
"реять" : "soar fly",
"ржаветь" : "rust",
"ржавчина" : "rust",
"ржавый" : "rusty",
"ржанка" : "plover",
"ржаной" : "rye...",
"ржать" : "neigh",
"риза" : "chasuble, robe",
"риккетсия" : "rickettsia",
"рикошет" : "rebound, ricochet",
"рикша" : "ricksha, rickshaw",
"рим" : "Rome",
"римлянин" : "Roman",
"римлянка" : "Roman",
"римский" : "Roman",
"ринуться" : "pf. rush, plunge",
"рис" : "rice",
"риск" : "risk",
"рискнуть" : "risk venture",
"рискованный" : "risky",
"рисковать" : "risk venture",
"рисовальный" : "crayon",
"рисование" : "drawing, designing",
"рисовать" : "draw, design",
"рисоваться" : "appear loom, pose mince",
"рисовый" : "rice...",
"рисунок" : "drawing design, picture illustration",
"ритм" : "rhythm",
"ритмический" : "rhythmic",
"ритмичный" : "rhythmical",
"риторика" : "oratory, rhetoric",
"риф" : "reef",
"рифма" : "rhyme",
"робеть" : "be timid quail, не робей! courage!",
"робкий" : "shy timid",
"робость" : "shyness timitidy",
"ров" : "ditch",
"ровесник" : "coeval of the same age",
"ровно" : "precisely exactly #time a. sharp, famil. absolutely",
"ровный" : "even level flat, straight, equal, equable",
"ровня" : "equal",
"рог" : "horn, antler, bugle",
"рогатка" : "slingshot",
"рогатый" : "horned",
"роговица" : "cornea",
"роговой" : "horn ...",
"рогожа" : "mat",
"род" : "genus, race, generation, kind, way, gr. gender, birth, famil. class, родом из с Р come #or be from; See also: от роду, с роду",
"родео" : "rodeo",
"родий" : "rhodium",
"родильный" : "maternity",
"родимое пятно" : "birthmark mole",
"родимый" : "& родинка",
"родина" : "native land home",
"родинка" : "birthmark mole",
"родители" : "parents",
"родитель" : "parent",
"родительный" : "genitive",
"родительский" : "parental",
"родить" : "bear give birth to, beget, fig. bring forth produce",
"родиться" : "be born, arise, come up grow",
"родник" : "spring",
"родной" : "own, native, dear, родня",
"родня" : "relative relation",
"родовитость" : "blue blood, gentility",
"родовой" : "patrimonial, generic",
"рододендрон" : "rhododendron"
};
