var dicctr_35 = {
"крапива" : "nettle",
"крапивник" : "wren",
"крапивница" : "hives, nettle-rash",
"крапивный" : "nettle",
"крапинка" : "speckle spot",
"краса" : "s. красота",
"красавец" : "handsome man",
"красавица" : "beauty beautiful woman",
"красавка" : "belladonna",
"красивый" : "beautiful, handsome, iron. fine",
"красильный" : "dye...",
"красильня" : "dye shop",
"красильщик" : "dyer",
"краситель" : "dye",
"красить" : "paint color dye, famil. накрасить paint make up, rouge",
"краска" : "color paint dye",
"красная строка" : "typ. paragraph new line",
"красная цена" : "famil. outside price",
"краснеть" : "redden grow #or turn red, blush, impf. be ashamed, appear show red",
"красноармеец" : "Red Army man",
"краснобай" : "glib talker",
"красновато-коричневый" : "henna, puce, rufous",
"красноватый" : "reddish",
"красное дерево" : "mahogany",
"красное словцо" : "famil. witticism",
"краснознаменный" : "decorated with the Order of the Red Banner",
"краснокожий" : "redskin",
"красноречивый" : "eloquent",
"красноречие" : "eloquence",
"краснота" : "redness, ruddiness",
"краснофлотец" : "Red Navy man",
"краснощекий" : "ruddy",
"краснуха" : "German measles",
"красный" : "red, s. красивый, bot. coniferous; See also: красный зверь, красная строка, красная цена, красное словцо, проходить красной нитью",
"красный зверь" : "deer",
"красоваться" : "shine show",
"красота" : "beauty",
"красть" : "steal",
"красться" : "prowl, slink",
"краткий" : "short brief concise, и краткое #or и с краткой #the #letter й, a. короткий",
"кратковременный" : "short, passing",
"краткосрочный" : "short, short-dated, short-term",
"краткость" : "brevity",
"кратный" : "divisible, su. multiple, ...кратный ...fold",
"крах" : "failure crash ruin",
"крахмал" : "starch",
"крахмалить" : "starch",
"крахмальный" : "starch",
"крашение" : "dyeing",
"крашеный" : "painted, dyed",
"креветка" : "prawn, shrimp",
"кредит" : "credit; See also: в кредит",
"кредитный" : "pf. credit",
"кредитовать" : "pf. credit",
"кредитор" : "creditor",
"кредитоспособный" : "solvent",
"кредо" : "creed",
"крейсер" : "cruiser",
"крейсерство" : "cruise",
"крейсировать" : "cruise, ply",
"крем" : "cream",
"крематорий" : "crematorium, crematory",
"кремень" : "flint",
"кремировать" : "cremate",
"кремлевский" : "Kremlin",
"кремль" : "Kremlin",
"кремниевый" : "silicic",
"кремний" : "silicon",
"кремнистый" : "gravelly stony, siliceous",
"крен" : "list careen",
"крендель" : "cracknel",
"кренить" : "list",
"креп" : "crepe crape",
"крепить" : "fix secure, reinforce, nav. belay, furl, fig. strengthen",
"крепиться" : "take courage, famil. persevere",
"крепкий" : "strong, firm solid sound, robust, hard, affectionate",
"крепко" : "a. fast, deep",
"крепление" : "tier",
"крепнуть" : "grow strong",
"крепостничество" : "serfdom",
"крепостное право" : "s. крепостничество, fortress",
"крепостной" : "bond, su. serf",
"крепость" : "fortress, strength, firmness, jur. deed",
"кресло" : "armchair, thea. obsol. stall",
"крест" : "cross",
"крестины" : "baptism christening",
"крестить" : "pf. окрестить baptize christen, godfather godmother sponsor",
"крест-накрест" : "crosswise",
"крестная" : "godmother",
"крестник" : "godson",
"крестница" : "goddaughter",
"крестный" : "cross, крестный godfather; See also: крестная",
"крестовник" : "groundsel, groundsill",
"крестовый поход" : "crusade",
"крестообразно" : "crosswise",
"крестцовый" : "sacral",
"крестьянин" : "peasant farmer",
"крестьянка" : "countrywoman country girl, farmer's wife",
"крестьянский" : "farm peasant..., country...",
"крестьянство" : "peasantry",
"кретин" : "cretin",
"кречет" : "merlin",
"крещение" : "baptism christening, боевое крещение",
"кривая" : "curve",
"кривизна" : "crookedness curvature",
"кривить" : "crook, twist; See also: кривить душой",
"кривить душой" : "palter",
"кривляние" : "grimacing twisting",
"кривляться" : "grimace, mince",
"криво" : "askew",
"кривобокий" : "lopsided",
"кривой" : "crooked  wry, curve, famil. one-eyed",
"криволинейный" : "curvilinear",
"кривоногий" : "bandy-legged",
"кривотолки" : "rumors gossip",
"кривошип" : "crank",
"кризис" : "crisis",
"крик" : "cry shout, bawl outcry, cri",
"крикливый" : "shrill, clamorous, loud",
"крикнуть" : "s. кричать",
"крикун" : "bawler clamorer, tattler",
"крикунья" : "bawler clamorer, tattler",
"криминальный" : "criminal",
"криптон" : "krypton",
"кристалл" : "crystal",
"кристаллический" : "crystalline",
"кристальный" : "crystalline",
"критерий" : "criterion",
"критик" : "critic",
"критика" : "criticism, critique review",
"критиковать" : "criticize",
"критический" : "critical",
"критичный" : "critical",
"кричать" : "cry  shout, scream",
"кричащий" : "crying, garish, screaming",
"кришна" : "krishna",
"кров" : "shelter, home, obsol. roof",
"кровавый" : "bloody sanguinary",
"кровать" : "bed, bedstead",
"кровельщик" : "tiler, slater",
"кровеносный" : "blood",
"кровля" : "roof",
"кровный" : "blood, full-blooded pure- thoroughbred, vital, arch...",
"кровожадный" : "bloodthirsty",
"кровоизлияние" : "extravasation hemorrhage",
"кровообращение" : "circulation of the blood",
"кровопийца" : "bloodsucker",
"кровоподтек" : "bruise",
"кровопролитие" : "bloodshed",
"кровопролитный" : "s. кровавый",
"кровопускание" : "bloodletting",
"кровосмесительный" : "incestuous",
"кровосмешение" : "incest",
"кровотечение" : "bleeding, s. кровоизлияние",
"кровоточить" : "bleed",
"кровь" : "blood",
"кровяной" : "blood...",
"кроить" : "cut",
"кройка" : "cutting",
"крокет" : "croquet",
"крокодил" : "crocodile",
"крокодиловый" : "crocodilian",
"кролик" : "rabbit",
"кроме" : "except besides  apart from, but",
"кромсать" : "hack mangle",
"крона" : "crown",
"кронциркуль" : "caliper",
"кронштейн" : "bracket, cantilever, corbel",
"кропить" : "sprinkle",
"кропотливый" : "laborious toilsome, painstaking assiduous",
"кроссворд" : "crossword puzzle",
"крот" : "zo. mole",
"кроткий" : "gentle meek",
"кроха" : "crumb, bit",
"крохотный" : "tiny",
"крошечный" : "tiny",
"крошить" : "crumb, popul. crush",
"крошиться" : "crumble",
"крошка" : "crumb, bit, famil. baby little one",
"круг" : "circle, sphere range, orbit, famil. average, slice",
"кругловатый" : "roundish",
"круглогодичный" : "perennial",
"круглоголовый" : "roundhead",
"круглолицый" : "chubby-faced",
"круглые сутки" : "round the clock",
"круглый" : "round, famil. perfect complete",
"круглый год" : "all the year round",
"круговой" : "circular, mutual",
"круговорот" : "circulation, succession",
"кругозор" : "horizon scope",
"кругом" : "round, around round about, кругом! milit. about face !, famil. entirely",
"кругооборот" : "circulation",
"кругообразный" : "circular",
"кругосветный" : "round the world, nav. circum...",
"кружевной" : "lacy",
"кружево" : "lace",
"кружить" : "turn  whirl, circle, rotate revolve spin, stray about; See also: голова кружится",
"кружка" : "mug, box",
"кружный" : "roundabout",
"кружок" : "circle disk, fig. circle, slice",
"круп" : "croup",
"крупа" : "grits groats pl., sleet",
"крупинка" : "grain",
"крупный" : "coarse gross, big large great, outstanding, commerc. wholesale, close, крупный разговор",
"крупный разговор" : "high words",
"крупье" : "croupier",
"крутизна" : "steep",
"крутить" : "twist, twirl, roll, turn, whirl, impf. trick",
"крутой" : "steep sharp abrupt sudden, hard, harsh",
"крутость" : "steepness, harshness",
"круча" : "s. крутизна",
"кручина" : "grief affliction",
"крушение" : "rail. accident, nav. wreck, ruin breakdown",
"крушина" : "buckthorn",
"крыжовник" : "gooseberry -ries pl.",
"крылатый" : "winged",
"крыло" : "wing, sail, splashboard",
"крыльцо" : "steps pl. staircase porch",
"крым" : "Crimea",
"крымский" : "Crimean",
"крыса" : "rat",
"крысий" : "rat",
"крысиный" : "ratty",
"крыть" : "cover, coat, trump, -ся impf. lie #or consist in, be at the bottom of",
"крыша" : "roof",
"крышка" : "lid cover, popul. end ruin",
"крюк" : "hook, famil. detour",
"крючковатый" : "hooked",
"крючкотворство" : "pettifoggery",
"крючок" : "hook, crochet needle, flourish, famil. hitch",
"кряж" : "range, chain of hills",
"крякать" : "quack",
"крякнуть" : "quack",
"кряхтеть" : "groan moan",
"ксенон" : "xenon",
"ксеркс" : "xerxes",
"ксерокс" : "xerox",
"ксилофон" : "xylophone",
"кстати" : "to the point, opportune in the nick of time, apropos, besides too as well, incidentally by the way",
"кто" : "who, ~ ... ~ ... some ... others ..., ~ кто-либо; See also: кто-нибудь, кто-то, кто бы ни, кто бы то ни был",
"кто бы ни" : "whoever",
"кто бы то ни был" : "whoever it may be",
"кто его знает" : "goodness knows, popul. apparently probably",
"кто-либо" : "any- somebody",
"кто-нибудь" : "any- somebody",
"кто-то" : "any- somebody",
"куб" : "math. cube, boiler",
"кубарем" : "famil. head over heels",
"кубик" : "cube, block",
"кубический" : "cubic"
};
