var dicctr_8 = {
"верховье" : "upper",
"верхом" : "astride, on horseback; See also: ездить верхом",
"верхушка" : "top crest, the highest ranks",
"вершина" : "peak summit",
"вершить" : "solve decide, direct, accomplish",
"вершок" : "vershok 75 #in.)",
"вес" : "weight; See also: на вес, удельный вес, пользоваться большим весом",
"веселая" : "lilt",
"веселить" : "amuse divert",
"веселость" : "gaiety mirth",
"веселый" : "gay merry cheerful, как весело! it's such fun!, ему весело he enjoys himself is of good cheer",
"веселье" : "merriment merrymaking fun",
"весельчак" : "merry fellow",
"весенний" : "spring...",
"весить" : "weigh",
"веский" : "weighty",
"весло" : "oar",
"весна" : "spring",
"веснушка" : "freckle",
"весовой" : "weight..., balance..., sold by weight",
"весовщик" : "weigher",
"весом в" : "weighing...",
"вести" : "lead conduct guide, carry on, keep, drive, вести начало spring; See also: вести себя",
"вести себя" : "behave",
"вести учет" : "keep books pl.",
"вестибюль" : "entrance hall",
"вест-индия" : "West Indies",
"вестись" : "be conducted #or carried on, так уж у нас ведется that's a custom among us",
"вестник" : "messenger, bulletin",
"вестовой" : "orderly",
"весть" : "news message, gossip rumor",
"весы" : "scales balance",
"весь" : "adj. all the whole, full life, all over, everything a. everybody, лучше всего best of all the best, при всем том #or со всем тем for all that, во всем мире all over the world, по всей стране throughout the country, всего хорошего! good luck!, во всю s. сила, все adv. always all the time, only just, все не not yet, все больше more and more, все же nevertheless yet",
"весь день" : "all day",
"весьма" : "very extremely; See also: весьма вероятно",
"весьма вероятно" : "most probably",
"ветвистый" : "branchy",
"ветвь" : "branch",
"ветер" : "wind; See also: встречный ветер, попутный ветер, бросать деньги на ветер, бросать слова на ветер, держать нос по ветру",
"ветеран" : "veteran",
"ветеринар" : "ветеринарный врач veterinarian",
"ветеринарный" : "ветеринарный врач veterinarian",
"ветерочек" : "light wind breeze breath",
"ветка" : "branch twig, rail. branch line",
"вето" : "veto; See also: наложить вето",
"веточка" : "sprig",
"ветошь" : "rags tatters pl.",
"ветр" : "ulcer",
"ветреный" : "windy",
"ветролом" : "windbreak",
"ветряная мельница" : "windmill",
"ветряная оспа" : "chicken pox",
"ветряной" : "wind...; See also: ветряная мельница",
"ветхий" : "old dilapidated, worn-out shabby, decrepit",
"ветхость" : "decay dilapidation, приходить в ветхость fall into decay",
"ветчина" : "ham",
"ветшать" : "decay dilapidate weaken",
"веха" : "landmark, nav. spar buoy",
"вечер" : "evening, evening party, soiree; See also: вечером, сегодня вечером, вчера вечером, под вечер",
"вечереть" : "decline",
"вечеринка" : "= вечер",
"вечерком" : "famil. = вечером",
"вечерний" : "evening... night...",
"вечерня" : "vespers pl. evensong",
"вечерняя заря" : "evening glow",
"вечером" : "in the evening",
"вечеря" : "тайная вечеря #or вечеря господня, the Lord's Supper",
"вечность" : "aeon, eon, eternity, perpetuity",
"вечный" : "eternal, everlasting, sempiternal",
"вешать" : "hang, hung, suspend",
"вещество" : "stuff",
"вещь" : "thing",
"веять" : "winnow",
"взаимность" : "reciprocity",
"взаимный" : "mutual reciprocal, спасибо взаимно famil. thanks the same to you",
"взаимо-" : "inter",
"взаимодействие" : "interaction, cooperation",
"взаимодействовать" : "interact, cooperate",
"взаимоотношение" : "mutual relation",
"взаимопомощь" : "mutual aid",
"взаимопонимание" : "mutual understanding",
"взаймы" : "on credit #or loan; See also: брать взаймы, давать взаймы",
"взамен" : "instead of in exchange for",
"взаперти" : "locked up under lock and key",
"взаправду" : "popul. = вправду",
"взбаламутить" : "trouble stir up",
"взбалмошный" : "extravagant",
"взбалтывать" : "shake #or stir up",
"взбегать" : "run up",
"взбежать" : "run up",
"взбесить" : "enrage madden",
"взбешенный" : "savage",
"взбивать" : "fluff, whip froth",
"взбираться" : "climb",
"взбить" : "fluff, whip froth",
"взболтать" : "shake #or stir up",
"взбороздить" : "furrow",
"взбороновать" : "harrow",
"взбудораживать" : "= будоражить",
"взбудоражить" : "excite",
"взбунтовать" : "instigate",
"взбухать" : "swell",
"взбухнуть" : "swell",
"взваливать" : "load charge",
"взвалить" : "load charge",
"взвесить" : "weigh, -ся weigh o.s.",
"взвести" : "s. взводить",
"взвести курок" : "cock",
"взвешивать" : "weigh, -ся weigh o.s.",
"взвивать" : "whirl up, -ся soar up rise",
"взвизгивать" : "squeak scream",
"взвизгнуть" : "squeak scream",
"взвинтить" : "excite, raise",
"взвинченный" : "keyed, strung, wrought up",
"взвинчивать" : "excite, raise",
"взвить" : "whirl up, -ся soar up rise",
"взвод" : "platoon",
"взводить" : "lead up, lift, impute; See also: взвести курок",
"взволнованный" : "excited, uneasy",
"взволновать" : "s. волновать",
"взгромождать" : "load pile up, -ся clamber perch",
"взгромоздить" : "load pile up, -ся clamber perch",
"взгрустнуть" : "grieve, long",
"вздергивать" : "jerk up",
"вздернутый нос" : "pug nose",
"вздернуть" : "jerk up",
"вздор" : "nonsense",
"вздорный" : "foolish absurd, famil. quarrelsome",
"вздорожание" : "rise of price",
"вздорожать" : "s. дорожать",
"вздох" : "sigh; See also: испустить последний вздох",
"вздохнуть" : "s. вздыхать",
"вздрагивать" : "start wince, shudder",
"вздремнуть" : "pf. nap",
"вздрогнуть" : "start wince, shudder",
"вздувать" : "whirl up, -ся inflate, famil. thrash",
"вздумать" : "pf. conceive the idea take it into one's head",
"вздуматься" : "ему вздумалось = он вздумал; See also: как вздумается",
"вздутый" : "swollen",
"взлет" : "blastoff, takeoff",
"взломщик" : "breaker, burglar, picklock, yegg",
"взмахнуть" : "swing",
"взметать" : "whirl #or throw up, flap",
"взметнуть" : "whirl #or throw up, flap",
"взморье" : "seashore seaside",
"взмутить" : "trouble muddle, fog, меня мутит famil. I feel sick",
"взнос" : "payment, fee",
"взнуздать" : "bridle",
"взнуздывать" : "bridle",
"взобраться" : "climb",
"взойти" : "& всходить",
"взор" : "look, gaze, eyes pl.",
"взорвать" : "s. взрывать",
"взорваться" : "burst",
"взрослый" : "grown-up adult",
"взрыв" : "explosion, detonation, fig. outburst",
"взрыватель" : "fuse",
"взрывать" : "blow up, fig. enrage, -ся explode",
"взрывной" : "explosive",
"взрывчатый" : "explosive",
"взрыхлить" : "loosen",
"взрыхлять" : "s. рыхлить",
"взывать" : "cry call, invoke, appeal",
"взыскание" : "levy collecting, punishment reprimand",
"взыскательный" : "exacting exigent",
"взыскать" : ", levy exact, collect, recover, call to account, impose a penalty, не взыщи! no offence!",
"взыскивать" : ", levy exact, collect, recover, call to account, impose a penalty, не взыщи! no offence!",
"взьезжать" : "ride #or drive up",
"взьерошивать" : "dishevel tousle, -ся bristle up",
"взьерошить" : "dishevel tousle, -ся bristle up",
"взьехать" : "ride #or drive up",
"взявший" : "captor",
"взятие" : "seizure capture",
"взятка" : "bribe; See also: дать взятку",
"взяточник" : "bribe taker corrupt official",
"взяточничество" : "bribery",
"взять" : "take, a. взимать, его взяла охота писать he took a fancy to writing, он взял да сказал famil. he said it without further consideration; See also: взять напрокат, взять пример, взять верх над, взять на поруки, взять слово, взять слово, взять обратно, взять себя в руки, взять на себя, взять за правило, возьмите направо{!}",
"взять в плен" : "take prisoner",
"взять верх над" : "be victorious over conquer",
"взять внаймы" : "rent hire",
"взять за правило" : "make it a rule",
"взять измором" : "milit. starve",
"взять на буксир" : "take in tow",
"взять на поруки" : "be bail",
"взять на себя" : "assume",
"взять на учет" : "register",
"взять напрокат" : "hire",
"взять обратно" : "withdraw",
"взять себя в руки" : "o.s. pull o.s. together",
"взять слово" : "take the floor",
"взяться" : "undertake, set about, take hold of seize, откуда это берется? where does that come from?, откуда у него деньги берутся?, wherever does he get his money from?; See also: взяться за руки, взяться за книгу, откуда ни возьмись",
"взяться за книгу" : "set about #or start reading a book",
"взяться за руки" : "join hands",
"виадук" : "viaduct",
"вибрация" : "vibration",
"вибрировать" : "vibrate",
"вибрирующий" : "vibrant, vibratory",
"виг" : "whig",
"вигвам" : "wigwam",
"вид" : "look appearance air, sight view, kind sort, species, gr. aspect; See also: в виде, при виде, на виду, с виду, по виду, ни под каким видом, у него хороший вид, делать вид, показывать вид, терять из виду, выпускать из виду, не терять из виду, не выпускать из виду, ставить на вид",
"вид с птичьего полета" : "bird's-eye view",
"видать" : "его давно не видать, I #or we haven't seen him for a long time, -ся meet see",
"видение" : "vision",
"видеомагнитофон" : "videotape",
"видеть" : "see, catch sight of; See also: увидеть во сне, видишь ли{?}, видите ли{?}",
"видеться" : "= видаться",
"видимо" : "apparently evidently",
"видимо-невидимо" : "famil. lots of immense quantity",
"видимость" : "visibility, appearance",
"видимый" : "visible, apparent",
"видите ли" : "you see?",
"видоизменять" : "modify, transfigure",
"виза" : "visa",
"византиец" : "byzantine",
"визг" : "shriek, squeal, yelp",
"визгливый" : "shrill squeaky",
"визжать" : "shriek, yelp",
"визировать" : "pf. visa",
"визит" : "visit call",
"визитная карточка" : "calling card",
"вика" : "vetch",
"викарий" : "vicar",
"викинг" : "viking",
"виконт" : "viscount",
"викторианский" : "victorian",
"вилка" : "fork, вилка el. plug",
"вилла" : "chateau, villa",
"вилы" : "pitchfork",
"вильнуть" : "wag, fig. prevaricate shuffle",
"вилять" : "wag, fig. prevaricate shuffle",
"вина" : "guilt, fault, reason, вменять в вину impute, сваливать вину lay the blame, это не по моей вине it's not my fault",
"винегрет" : "vinaigrette",
"винительный" : "gr. accusative",
"винить" : "blame  accuse",
"винная ягода" : "fig",
"винный" : "wine...; See also: винный камень, винная ягода",
"винный камень" : "tartar",
"вино" : "wine, famil. vodka",
"виноватый" : "guilty, виноват! sorry! excuse me!, pardon!, вы в этом виноваты it's your fault, я виноват перед вами I must apologize to you, it's all my fault",
"виновник" : "culprit, originator author",
"виновность" : "guilt",
"виновный" : "guilty",
"виноград" : "vine, pl., сбор винограда vintage",
"виноградарство" : "winegrowing",
"виноградарь" : "winegrower",
"виноградник" : "vineyard",
"виноградный" : "grape",
"виноделие" : "winemaking",
"винокуренный" : "винокуренный завод distillery",
"винт" : "screw"
};
