var dicctr_90 = {
"углубление" : "recess",
"углублять" : "deepen",
"угнетать" : "oppress",
"угнетение" : "oppression",
"угнетенный" : "depressive",
"уговаривать" : "coax, expostulate",
"уговор" : "agreement arrangement, condition, pl. persuasion",
"уговорить" : "persuade",
"угода" : "в угоду",
"угождать" : "cater",
"угол" : "angle, corner",
"уголовный" : "penal",
"уголь" : "charcoal, coal",
"угольный" : "carbonic",
"угорать" : "be poisoned by coal gas, famil. go mad",
"угореть" : "be poisoned by coal gas, famil. go mad",
"угорь" : "eel, blackhead",
"угостить" : "treat  entertain",
"угощать" : "treat  entertain",
"угощение" : "entertainment, food drinks pl.",
"угрожать" : "threaten",
"угрожающий" : "imminent, minacious, minatory, threatening",
"угроза" : "threat menace",
"угрызение" : "угрызения pl. совести remorse",
"угрюмый" : "sullen, surly",
"удав" : "anaconda, boa",
"удаленный" : "removed",
"удалять" : "amputate",
"удаляться" : "retire withdraw, move away",
"удаляющийся" : "recessive",
"удар" : "blow, stroke, fig. shock, impact, slash, clap, famil. form",
"ударение" : "stress accent",
"ударить" : "s. ударять",
"ударный" : "percussion, percussive",
"ударять" : "jounce",
"удача" : "luck",
"удачливый" : "lucky, successful",
"удачный" : "felicitous",
"удвительный" : "wonderful",
"удержать" : "withhold restrain, keep retain, suppress, deduct",
"удержаться" : "hold, refrain",
"удерживание" : "retention",
"удерживать" : "withhold restrain, keep retain, suppress, deduct",
"удерживаться" : "hold, refrain",
"удерживающий" : "deterrent",
"удешевить" : "cheapen",
"удешевлять" : "cheapen",
"удивительный" : "wonderful marvelous, miraculous, amazing strange, удивительно it is a wonder",
"удивить" : "s. удивлять",
"удирать" : "decamp, get away, skedaddle",
"удлинять" : "elongate, lengthen",
"удобно" : "cose",
"удобный" : "comfortable, convenient, habitable",
"удобо" : "easily ...",
"удобоваримый" : "digestible",
"удобрять" : "fertilize, nourish",
"удовлетворение" : "gratification, satisfaction",
"удовлетворительный" : "passable, satisfactory",
"удовлетворять" : "gratify, satisfy",
"удовольствие" : "gusto, pleasure",
"удод" : "hoopoe",
"удорожить" : "raise the price of",
"удостаивать" : "honor favor, bestow confer, award, deign",
"удостоверение" : "certificate certification, card, corroboration",
"удостоверить" : "certify attest, prove, convince",
"удостоверять" : "certify attest, prove, convince",
"удостоить" : "honor favor, bestow confer, award, deign",
"удосужиться" : "find time",
"удочка" : "fishing tackle, fig. trap; See also: закинуть удочку",
"удрать" : "run away",
"удружить" : "s. услужить",
"удручать" : "deject depress",
"удрученный" : "crestfallen, dejected, dispirited",
"удручить" : "deject depress",
"удушение" : "suffocation, poisoning",
"удушливый" : "stifling suffocating, oppressive, poison",
"удушье" : "asthma",
"уединение" : "solitude",
"уединенные" : "solitude",
"уединенный" : "retired secluded lonely solitary",
"уединиться" : "retire seclude o.s.",
"уединяться" : "retire seclude o.s.",
"уезд" : "district",
"уездный" : "district",
"уезжать" : "leave  go",
"уехать" : "leave  go",
"уж" : "grass snake, = уже, famil. indeed well, #do #be",
"ужалить" : "sting bite",
"ужас" : "horror, terror fright, famil. = ужасный ужасно",
"ужасать" : "horrify",
"ужасаться" : "be horrified #or terrified",
"ужасающий" : "horrifying",
"ужаснуть" : "horrify",
"ужаснуться" : "be horrified #or terrified",
"ужасный" : "terrible horrible dreadful, famil. awful",
"уже" : "already, as early as; See also: уже не, вот уже",
"уже не" : "not ... any more",
"ужение" : "angling fishing",
"уживаться" : "get accustomed, live in harmony",
"уживчивый" : "sociable accommodating",
"ужимка" : "grimace, gesture",
"ужин" : "supper",
"ужинать" : "have supper",
"ужиться" : "get accustomed, live in harmony",
"узаконение" : "legalization, statute",
"узаконенный" : "statutory",
"узаконивать" : "legalize",
"узаконить" : "legalize",
"узаконять" : "legalize",
"узбек" : "Uzbek",
"узбекский" : "Uzbek",
"узда" : "bridle",
"уздечка" : "bridle",
"узел" : "knot, rail. junction, center Brt. centre, anat. ganglion, bundle",
"узелок" : "knot, packet",
"узкий" : "narrow, tight",
"узкое место" : "bottleneck, weak point",
"узкоколейный" : "narrow-gauge",
"узловатый" : "knotty",
"узловая станция" : "junction",
"узловой" : "knot, central chief, s. узел",
"узнавать" : "recognize, learn  find out know hear; See also: позвольте узнать",
"узнать" : "recognize, learn  find out know hear; See also: позвольте узнать",
"узник" : "prisoner",
"узор" : "pattern design, с узорами = узорчатый",
"узорчатый" : "figured, pattern",
"узость" : "narrowness",
"узурпация" : "usurpation",
"узурпировать" : "usurp",
"узы" : "bonds ties",
"уикенд" : "weekend",
"уйма" : "a great lot",
"уйти" : "s. уходить",
"указ" : "decree edict ukase",
"указание" : "instruction  direction, indication",
"указатель" : "index, indicator, guide",
"указательный" : "indicatory, fore  index, gr. demonstrative",
"указать" : "s. указывать",
"указка" : "pointer, famil. order",
"указывать" : "point out, point, show, indicate",
"указывающий" : "directive, indicant, indicating, indicative",
"укачать" : "rock to sleep lull, impers. make sick",
"укачивать" : "rock to sleep lull, impers. make sick",
"уклад" : "mode way, form",
"укладка" : "packing, laying",
"укладывать" : "put, lay, pack, place, cover",
"укладываться" : "a. find room, famil. manage",
"уклон" : "slope incline, slant, pol. deviation",
"уклонение" : "swerve deviation, evasion",
"уклониться" : "s. уклоняться",
"уклончивый" : "evasive",
"уклоняться" : "deviate, evade, swerve, digress",
"уключина" : "oarlock",
"укол" : "prick, med. injection",
"укомплектовать" : "complete",
"укомплектовывать" : "complete fill, supply",
"укор" : "reproach",
"укорачивать" : "shorten",
"укоренить" : "implant",
"укорениться" : "take root",
"укоренять" : "implant",
"укореняться" : "take root",
"укоризна" : "s. укор",
"укоризненный" : "reproachful",
"укорить" : "s. укорять",
"укоротить" : "shorten",
"укорять" : "reproach blame",
"украдкой" : "furtively",
"украина" : "Ukraine",
"украинец" : "Ukrainian",
"украинка" : "Ukrainian",
"украинский" : "Ukrainian",
"украсить" : "adorn, decorate, trim, embellish",
"украсть" : "steal",
"украшать" : "adorn, decorate, trim, embellish",
"украшение" : "adornment, decoration, ornament, embellishment",
"украшенный" : "beautified, decorated, medalled",
"укрепить" : "s. укреплять",
"укрепление" : "bastion, consolidation",
"укреплять" : "strengthen, fasten, consolidate, milit. fortify, укрепляющий med. restorative",
"укрепляться" : "strengthen become stronger, milit. entrench",
"укрепляющий" : "restorative, roborant",
"укромный" : "secluded",
"укроп" : "fennel",
"укротитель" : "tamer",
"укротительница" : "tamer",
"укротить" : "tame, break, subdue restrain",
"укрощать" : "tame, break, subdue restrain",
"укрощение" : "taming, subdual",
"укрупнить" : "enlarge extend, centralize",
"укрупнять" : "enlarge extend, centralize",
"укрыватель" : "receiver",
"укрывать" : "cover, shelter, conceal harbor",
"укрываться" : "cover o.s., hide, take shelter #or cover",
"укрытие" : "cover shelter",
"укрыть" : "cover, shelter, conceal harbor",
"укрыться" : "cover o.s., hide, take shelter #or cover",
"уксус" : "vinegar",
"укус" : "bite укусить s. кусать",
"укусить" : "bite  sting",
"укутать" : "wrap up",
"укутывать" : "wrap up",
"ул" : "abbr.: улица",
"улан" : "lancer, uhlan",
"улей" : "beehive, hive",
"улитка" : "cochlea, snail",
"улица" : "street",
"улов" : "catch",
"уловимый" : "perceptible",
"уловить" : "catch seize, grasp",
"уловка" : "trick ruse",
"уложить" : "put, lay, pack, place, cover",
"улучать" : "find",
"улучить" : "find",
"улучшать" : "improve, -ся",
"улучшение" : "improvement",
"улучшить" : "improve, -ся",
"улыбаться" : "smile",
"улыбка" : "smile",
"улыбнуться" : "smile",
"ультиматум" : "ultimatum",
"ультракороткий" : "very-high-frequency",
"ум" : "intellect, mind, sense, head, без ума mad, задним умом крепок #be wise after the event, быть на уме have in mind, не его ума дело beyond his reach, сойти с ума go mad, сходить с ума a. be mad, ~ за разум заходит famil. #be crazy, ~ короток famil. #be dull #or dense",
"умаление" : "belittling",
"умалить" : "s. умалять",
"умалчивать" : "pass over in silence",
"умалять" : "belittle derogate disparage, curtail",
"умаляться" : "decrease lessen",
"умаляющий" : "derogatory",
"умелец" : "handyman",
"умелый" : "skilful skilled",
"умение" : "skill faculty knowhow",
"уменьшаемое" : "minuend",
"уменьшать" : "reduce diminish decrease",
"уменьшаться" : "dwindle",
"уменьшение" : "decrease reduction",
"уменьшительный" : "diminutive",
"уменьшить" : "reduce diminish decrease",
"умеренность" : "moderation moderateness",
"умеренный" : "moderate temperate",
"умереть" : "s. умирать",
"умерить" : "s. умерять",
"умертвить" : "s. умерщвлять",
"умерший" : "dead",
"умерщвлять" : "kill destroy, mortify",
"умерять" : "moderate",
"уместить" : "s. умещать",
"уместный" : "apposite, apropos, germane, relevant",
"умирающий" : "dying, moribund",
"умиротворять" : "appease, propitiate"
};
