var dicctr_26 = {
"застигнуть" : "surprise catch, take...",
"застилать" : "cover, cloud",
"застичь" : "surprise catch, take...",
"застлать" : "cover, cloud",
"застой" : "standstill deadlock, stagnation",
"застойный" : "stagnant, chronic, commerc. unsalable",
"застольный" : "table..., drinking",
"застопорить" : "stop",
"застояться" : "pf. stand #or stay too long, be stagnant stale",
"застраивать" : "build on, build up encumber",
"застраховать" : "insure, fig. safeguard",
"застраховывать" : "insure, fig. safeguard",
"застревать" : "stick, famil. come to a standstill, be delayed, be lost",
"застреливать" : "shoot kill",
"застрелить" : "shoot kill",
"застрельщик" : "milit. skirmisher, fig. instigator, initiator",
"застроить" : "build on, build up encumber",
"застройка" : "building",
"застрять" : "stick, famil. come to a standstill, be delayed, be lost",
"заступ" : "spade",
"заступать" : "take  relieve, famil. start, -ся take s.b.'s side, protect, intercede for",
"заступить" : "take  relieve, famil. start, -ся take s.b.'s side, protect, intercede for",
"заступник" : "protector patron, advocate",
"заступница" : "protectress patroness",
"заступничество" : "intercession",
"застывать" : "cool down congeal, stiffen be #or stand stockstill, freeze  chill",
"застыть" : "cool down congeal, stiffen be #or stand stockstill, freeze  chill",
"засунуть" : "put slip tuck, famil. mislay",
"засуха" : "drought",
"засучивать" : "turn #or tuck up",
"засучить" : "turn #or tuck up",
"засушивать" : "dry, famil. make arid",
"засушить" : "dry, famil. make arid",
"засушливый" : "droughty",
"засчитать" : "reckon count, credit",
"засчитывать" : "reckon count, credit",
"засыпать" : "засыпать fill up, cover drift, fig. heap ply overwhelm, famil. pour strew, заснуть fall asleep",
"засыхать" : "dry up, wither",
"затаенный" : "a. secret",
"затаивать" : "conceal hide, hold, bear",
"затаить" : "conceal hide, hold, bear",
"затапливать" : "light a fire, flood, sink",
"затаптывать" : "trample tread",
"затасканный" : "worn shabby, hackneyed, затащить drag pull, mislay",
"затаскивать" : "famil. затаскать wear out; See also: затасканный",
"затвердевать" : "harden",
"затвердеть" : "harden",
"затвердить" : "memorize learn",
"затверживать" : "memorize learn",
"затвор" : "bolt bar, lock, gate, phot. shutter",
"затворить" : "shut close, -ся shut o.s. up",
"затворять" : "shut close, -ся shut o.s. up",
"затевать" : "start undertake, conceive, resolve",
"затейливый" : "fanciful, ingenious intricate",
"затекать" : "flow, swell, be numb asleep  bloodshot",
"затем" : "then, for that purpose that is why; See also: затем чтобы, затем что",
"затем что" : "obsol. because",
"затем чтобы" : "in order to",
"затемнение" : "milit. blackout, obscuration",
"затемнить" : "darken overshadow obscure, milit. black out",
"затемнять" : "darken overshadow obscure, milit. black out",
"затененность" : "opacity",
"затереть" : "s. затирать",
"затерять" : "pf. lose",
"затеряться" : "get #or be lost, disappear, lie in the midst of",
"затечь" : "flow, swell, be numb asleep  bloodshot",
"затея" : "plan undertaking, invention freak, diversion, trick",
"затеять" : "start undertake, conceive, resolve",
"затирать" : "wipe #or blot out, jam block, famil. wear out, efface stunt",
"затихать" : "become silent #or quiet stop, die away #or off, calm down abate",
"затихнуть" : "become silent #or quiet stop, die away #or off, calm down abate",
"затишье" : "lull calm, shelter quiet spot nook",
"заткнуть" : "s. затыкать",
"затмевать" : "eclipse",
"затмение" : "eclipse",
"затмить" : "eclipse",
"зато" : "but  instead in return on the other hand, therefore",
"затоваривание" : "glut",
"затопить" : "light a fire, flood, sink",
"затоплять" : "light a fire, flood, sink",
"затоптать" : "trample tread",
"затор" : "jam block obstruction",
"затормозить" : "brake, fig. hamper, psych. curb restrain",
"заточать" : "confine imprison, exile",
"заточение" : "confinement imprisonment, exile",
"заточить" : "confine imprison, exile",
"затравить" : "bait  course chase down",
"затравливать" : "bait  course chase down",
"затрагивать" : "touch, affect, hurt",
"затрата" : "expense expenditure",
"затратить" : "spend",
"затрачивать" : "spend",
"затрепетать" : "tremble, quiver shiver, flicker, palpitate",
"затронуть" : "touch, affect, hurt",
"затруднение" : "difficulty trouble, embarrassment, в затруднении a. at a loss",
"затруднительное положение" : "predicament",
"затруднительный" : "difficult hard straitened",
"затруднить" : "embarrass trouble, render difficult inconvenience, aggravate complicate, -ся a. be at a loss",
"затруднять" : "embarrass trouble, render difficult inconvenience, aggravate complicate, -ся a. be at a loss",
"затуманивать" : "fog, dim",
"затухнуть" : "die out, fade",
"затушевать" : "shade, famil. smooth over, -ся efface",
"затушевывать" : "shade, famil. smooth over, -ся efface",
"затушить" : "s. тушить",
"затхлый" : "musty fusty",
"затыкать" : "stop  cork, famil. tuck slip",
"затылок" : "back of the head, nape",
"затылочный" : "cervical, occipital",
"затычка" : "bung plug",
"затягивать" : "tighten draw tight, gird lace enclose press, draw in etc., involve, cover, impers.: sink, close skin, protract delay, begin",
"затяжка" : "drawing tight, protraction, inhalation",
"затяжной" : "long lengthy protracted",
"затянутый" : "overextended",
"затянуть" : "tighten draw tight, gird lace enclose press, draw in etc., involve, cover, impers.: sink, close skin, protract delay, begin",
"заунывный" : "sad mournful melancholy",
"заурядный" : "common ordinary mediocre",
"заусенец" : "burr",
"заусеница" : "agnail",
"заутреня" : "matins pl.",
"заучивать" : "memorize",
"заучить" : "memorize",
"зафиксировать" : "fix",
"захват" : "seizure capture, usurpation",
"захватить" : "grasp grip, take, seize capture, usurp, absorb captivate, famil. catch snatch take",
"захватнический" : "aggressive",
"захватчик" : "invader aggressor",
"захватывать" : "grasp grip, take, seize capture, usurp, absorb captivate, famil. catch snatch take",
"захворать" : "pf. fall sick ill",
"захлебнуться" : "choke stifle, o.s., engin. break down stop",
"захлебываться" : "choke stifle, o.s., engin. break down stop",
"захлестнуть" : "lash, swamp, fig. seize",
"захлестывать" : "lash, swamp, fig. seize",
"захлопнуть" : "slam bang",
"захмелевший" : "sprung",
"захолустный" : "out-of-the-way provincial country..., rustic boorish",
"захолустье" : "solitude lonely #or dreary spot",
"захотеть" : "want wish, я хотел бы I would like, я хочу чтобы вы  pt. I want you to ...; See also: хочешь не хочешь",
"захохотать" : "roar",
"захудалый" : "down & out, mean",
"зацепить" : "catch hook on grapple, fasten, & -ся s. задевать",
"зацеплять" : "catch hook on grapple, fasten, & -ся s. задевать",
"зачаровать" : "charm",
"зачаровывать" : "charm",
"зачастую" : "famil. often frequently",
"зачатие" : "conception",
"зачаток" : "germ, pl. rudiments",
"зачаточный" : "rudimentary",
"зачать" : "conceive",
"зачахнуть" : "wither shrivel, grow stunted",
"зачем" : "why wherefore for what",
"зачем-то" : "for some purpose",
"зачеркивать" : "strike out obliterate",
"зачеркнуть" : "strike out obliterate",
"зачерпнуть" : "scoop dip",
"зачерпывать" : "scoop dip",
"зачерствелый" : "stale, fig. unfeeling",
"зачерстветь" : "grow stale, harden",
"зачесать" : "comb",
"зачесть" : "s. зачитывать1",
"зачесывать" : "comb",
"зачет" : "examination test, educ. credit",
"зачинщик" : "instigator",
"зачислить" : "enrol enlist engage, commerc. enter",
"зачислять" : "enrol enlist engage, commerc. enter",
"зачитать" : "read, famil. thumb wear out tear, not return, -ся be absorbed, read long",
"зачитывать1" : "reckon charge account, educ. credit",
"зачитывать2" : "read, famil. thumb wear out tear, not return, -ся be absorbed, read long",
"зачумленный" : "infected with pestilence",
"зашивать" : "sew up",
"зашить" : "sew up",
"зашифровать" : "cipher code",
"зашифровывать" : "cipher, encipher",
"зашнуровать" : "lace",
"зашнуровывать" : "lace",
"заштопанный" : "darned",
"заштопать" : "darn",
"заштриховать" : "hatch, shade",
"зашуршать" : "rustle",
"защелка" : "click, detent, pawl",
"защелкивать" : "snap catch",
"защелкнуть" : "snap catch",
"защемить" : "squeeze  pinch jam, fig. oppress with grief",
"защемлять" : "squeeze  pinch jam, fig. oppress with grief",
"защита" : "defense  protection cover, maintenance",
"защитить" : "s. защищать",
"защитник" : "defender, protector, jur. advocate  counsel for the defense, #sport: back",
"защитного цвета" : "khaki, flowers, blossom bloom, a. prime",
"защитный" : "protective, safety..., khaki ..., crash",
"защищать" : "defend, protect, vindicate advocate maintain support, jur. defend plead",
"заявить" : "s. заявлять",
"заявка" : "application, claim request",
"заявление" : "declaration statement, petition application",
"заявлять" : "declare announce state, claim present, enter lodge, notify inform, show manifest",
"заядлый" : "= завзятый",
"заяц" : "hare, famil. speck, popul. stowaway",
"заячий" : "hare..., famil. cowardly",
"заячья губа" : "harelip",
"звание" : "rank, title, class, standing",
"званый" : "invited; See also: званый обед, званый вечер",
"званый вечер" : "evening party",
"званый обед" : "dinner party",
"звательный" : "gr. vocative",
"звать" : "позвать call, invite, назвать famil. call, как вас зовут? what is your name?, меня зовут Петром #or Петр my name is Peter",
"звезда" : "star; See also: морская звезда",
"звездный" : "star... stellar, starry, starlit",
"звездообразный" : "asteroid, stellated",
"звездочка" : "starlet, #print. asterisk",
"звенеть" : "ring jingle clink, у меня звенит в ушах my ears ring",
"звено" : "link, fig. part branch, av. flight, squad",
"зверинец" : "menagerie",
"звериный" : "animal, feral, s. зверский",
"зверобой" : "hunter",
"зверолов" : "trapper, hunter",
"зверский" : "s. звериный, fig. brutal atrocious, famil. beastly awful dog",
"зверство" : "brutality, pl. atrocities",
"зверь" : "animal beast, fig. brute",
"звон" : "ring jingle peal chime",
"звонарь" : "bell ringer sexton",
"звонить" : "ring  chime peal, telephone call up",
"звонкий" : "sonorous clear, resonant, gr. voiced, hard",
"звонкость" : "sonority",
"звонок" : "bell, ring, the bell rings",
"звук" : "sound, tone, tune",
"звуковой" : "sound..., talking",
"звуконепроницаемый" : "soundproof",
"звукоподражание" : "onomatopoeia",
"звукоподражательный" : "onomatopoeic",
"звучание" : "sounding",
"звучать" : "sound, ring, clang",
"звучный" : "sonorous clear, resonant",
"звякать" : "clink",
"звякнуть" : "clink",
"зги" : "зги не видать #or не видно, it is pitch-dark",
"здание" : "building",
"здесь" : "here, therein",
"здоровый" : "bouncing, healthful, healthy, robust",
"здоровье" : "health",
"здрав и невредим" : "safe & sound",
"здравие" : "obsol. = здоровье; See also: здравия желаю",
"здравица" : "toast",
"здравия желаю" : "milit. good morning  sir!",
"здравница" : "sanatorium, sanitarium",
"здравомыслящий" : "sane sensible",
"здравоохранение" : "public health service",
"здравствовать" : "be in good health; See also: здравствуй!, да здравствует {...!}",
"здравствуй" : "hello! hi! good morning!, how do you do?",
"здравый" : "sane",
"зебра" : "zebra",
"зевнуть" : "yawn, famil. gape",
"зевок" : "yawn"
};
