var dicctr_75 = {
"распределение" : "distribution",
"распределительный" : "distributing, engin. control..., el. switch...",
"распределить" : "distribute, allot, assign, arrange classify",
"распределять" : "distribute, allot, assign, arrange classify",
"распродавать" : "sell out",
"распродажа" : "sale",
"распродать" : "sell out",
"распростереть" : "spread stretch, extend",
"распростертый" : "a. open",
"распростирать" : "spread stretch, extend",
"распроститься" : "bid farewell, give up abandon",
"распространение" : "spread expansion, dissemination propagation, circulation",
"распространенный" : "widespread",
"распространить" : "spread extend, propagate disseminate, diffuse",
"распространиться" : "famil. enlarge upon",
"распространять" : "spread extend, propagate disseminate, diffuse",
"распространяться" : "famil. enlarge upon",
"распространяющийся" : "pervasive",
"распрощаться" : "famil. = распроститься",
"распря" : "strife contention conflict",
"распрягать" : "unharness",
"распрячь" : "unharness",
"распускать" : "dismiss disband dissolve break up, unfurl, undo, loosen, spread, melt, fig. spoil",
"распускаться" : "open, expand, loosen untie, dissolve, famil. become spoiled",
"распустить" : "dismiss disband dissolve break up, unfurl, undo, loosen, spread, melt, fig. spoil",
"распуститься" : "open, expand, loosen untie, dissolve, famil. become spoiled",
"распутать" : "s. распутывать",
"распутица" : "impassability of roads",
"распутник" : "s. развратник",
"распутный" : "lecherous, libertine, profligate, rakish",
"распутство" : "lechery",
"распутывать" : "untangle",
"распутье" : "crossroad",
"распухать" : "swell",
"распухнуть" : "swell",
"распухший" : "swollen",
"распущенность" : "debauchery",
"распущенный" : "spoiled undisciplined, dissolute",
"распылитель" : "spray atomizer",
"распылить" : "spray atomize, scatter",
"распылять" : "spray atomize, scatter",
"распятие" : "crucifixion",
"распять" : "crucify",
"рассада" : "sprout",
"рассадить" : "s. рассаживать",
"рассадник" : "nursery, fig. hotbed",
"рассаживать" : "transplant, seat",
"рассаживаться" : "sit down take seats, famil. sit at ease",
"рассвести" : "dawn",
"рассвет" : "dawn  daybreak",
"рассветать" : "dawn",
"расседлать" : "pf. unsaddle",
"рассеивание" : "dispersal, dispersion, dissipation",
"рассеивать" : "disseminate, scatter disperse, dissipate dispel, divert",
"рассекать" : "cut  dissect hew cleave, swish",
"рассекречивать" : "declassify",
"расселить" : "settle, separate",
"расселять" : "settle, separate",
"рассердить" : "annoy vex fret anger",
"рассесться" : "sit down take seats, famil. sit at ease",
"рассечь" : "cut  dissect hew cleave, swish",
"рассеянность" : "absent-mindedness",
"рассеянный" : "absent-minded, dissipated, scattered, phys. diffused",
"рассеять" : "disseminate, scatter disperse, dissipate dispel, divert",
"рассказ" : "story tale narrative, short novel",
"рассказать" : "s. рассказывать",
"рассказчик" : "narrator, storyteller",
"рассказывать" : "tell, relate narrate",
"расслабить" : "weaken enervate",
"расслабление" : "relaxation",
"расслабленный" : "emasculate",
"расслаблять" : "weaken enervate",
"расследование" : "investigation inquiry into",
"расследовать" : "pf. investigate inquire into",
"расслоение" : "stratification",
"расслышать" : "pf. hear distinctly, не расслышать not catch",
"рассматривать" : "examine view, consider, discern distinguish",
"рассмешить" : "make laugh",
"рассмеяться" : "pf. burst out laughing",
"рассмотрение" : "examination, consideration",
"рассмотреть" : "examine view, consider, discern distinguish",
"рассол" : "brine pickle",
"рассортировать" : "sort",
"расспрашивать" : "inquire ask",
"расспросить" : "inquire ask",
"расспросы" : "inquiries",
"рассрочка" : "instalments",
"расставание" : "s. прощание",
"расставаться" : "part separate, leave",
"расставить" : "place, arrange, set, move apart",
"расставлять" : "place, arrange, set, move apart",
"расстановка" : "arrangement, distribution, order, punctuation, drawing up, pause",
"расстаться" : "part separate, leave",
"расстегивать" : "unbutton, unfasten",
"расстегнуть" : "unbutton, unfasten",
"расстилать" : "spread",
"расстояние" : "distance",
"расстраивать" : "upset derange, disorganize, disturb spoil, shatter, frustrate, mus. put out of tune",
"расстраиваться" : "be upset etc., fail",
"расстрел" : "shooting execution",
"расстреливать" : "shoot execute",
"расстрелять" : "shoot execute",
"расстричь" : "defrock",
"расстроить" : "upset derange, disorganize, disturb spoil, shatter, frustrate, mus. put out of tune",
"расстройство" : "disorder confusion, disturbance derangement, frustration",
"расступаться" : "give way part, open split",
"расступиться" : "give way part, open split",
"рассудительность" : "judiciousness",
"рассудительный" : "judicious wise",
"рассудить" : "pf. judge, decide, consider",
"рассудок" : "reason sense, judgment mind",
"рассудочный" : "rational",
"рассуждать" : "argue reason, talk",
"рассуждение" : "reasoning argument, objection, treatise essay",
"рассчитать" : "calculate estimate, judge, dismiss pay off, impf. count #or reckon, expect, intend",
"рассчитывать" : "calculate estimate, judge, dismiss pay off, impf. count #or reckon, expect, intend",
"рассчитываться" : "settle accounts get even  pay off, count off",
"рассылать" : "send out",
"рассылка" : "distribution dispatch",
"рассыпать" : "scatter spill, spread, ( -ся crumble fall to pieces break up fail, shower [П/Д] resound burst out)",
"расталкивать" : "push aside, push",
"растапливать" : "light kindle, melt",
"растаптывать" : "tread down",
"растаскать" : "pilfer, take to pieces, famil. separate",
"растаскивать" : "pilfer, take to pieces, famil. separate",
"растащить" : "pilfer, take to pieces, famil. separate",
"растаять" : "thaw melt, fade die, languish pine",
"раствор" : "solution, mortar",
"растворимый" : "soluble",
"растворитель" : "menstruum, resolvent",
"растворить" : "dissolve, open",
"растворять" : "dissolve, open",
"растворяющий" : "dissolvent, solvent",
"растение" : "plant",
"растереть" : "s. растирать",
"растерзать" : "pf. tear to pieces, lacerate",
"растерянный" : "confused perplexed bewildered",
"растерять" : "pf. lose",
"расти" : "grow increase",
"растирать" : "pound pulverize, rub, smear",
"растительность" : "vegetation flora, hair",
"растительный" : "vegetable, vegetative",
"растить" : "rear, famil. grow",
"растолкать" : "push aside, push",
"растолковать" : "pf. expound explain",
"растолочь" : "pound",
"растолстеть" : "grow stout",
"растопить" : "light kindle, melt",
"растоптать" : "tread down",
"растопырить" : "pf. spread",
"расторгать" : "break  annul, dissolve sever",
"расторгнуть" : "break  annul, dissolve sever",
"расторжение" : "breaking off, annulment, dissolution",
"расторопный" : "deft quick",
"расточать" : "squander waste dissipate, lavish",
"расточитель" : "prodigal spendthrift extravagant",
"расточительный" : "prodigal spendthrift extravagant",
"расточить" : "squander waste dissipate, lavish",
"растравить" : "irritate, fret stir",
"растравлять" : "irritate, fret stir",
"растрата" : "waste, embezzlement",
"растратить" : "spend waste, embezzle",
"растратчик" : "embezzler",
"растрачивать" : "spend waste, embezzle",
"растрепать" : "pf. tousle dishevel, tear  thumb",
"растрогать" : "pf. move touch",
"растущий" : "growing",
"растягивание" : "stretch",
"растягивать" : "stretch, med. strain, drawl, extend prolong",
"растяжение" : "stretching, strain",
"растяжимый" : "extensible elastic, fig. vague",
"растянутый" : "long-drawn",
"растянуть" : "stretch, med. strain, drawl, extend prolong",
"растянуться" : "sprawl",
"расформировать" : "pf. disband",
"расформировывать" : "deactivate, disband, disembody",
"расхаживать" : "walk about #or up & down pace",
"расхваливать" : "extol praise",
"расхвалить" : "extol praise",
"расхватать" : "snatch away, buy up",
"расхватывать" : "snatch away, buy up",
"расхитить" : "plunder",
"расхищать" : "plunder",
"расхищение" : "plunder",
"расход" : "expenditure  expense, a. debit, consumption, sale",
"расходиться" : "disperse, break up, differ, diverge, part separate get divorced, pass #or miss o.a. cross, be sold out sell, be spent run out of, melt dissolve, ramify, radiate, famil. spread, become enraged, get excited #or animated",
"расходовать" : "spend expend, a. use up",
"расхождение" : "divergence difference, radiation",
"расцарапать" : "scratch",
"расцарапывать" : "scratch",
"расцвести" : "bloom, flourish thrive",
"расцвет" : "blossom bloom, prime, prosperity",
"расцветать" : "bloom, flourish thrive",
"расцветка" : "coloring",
"расценивать" : "estimate value rate",
"расценить" : "estimate value rate",
"расценка" : "valuation, rate tariff",
"расцепить" : "uncouple unhook",
"расцеплять" : "uncouple unhook",
"расчесать" : "s. расчесывать",
"расческа" : "comb",
"расчесть" : "calculate estimate, judge, dismiss pay off, impf. count #or reckon, expect, intend",
"расчесывать" : "comb",
"расчет" : "calculation estimation, settlement, payment, dismissal famil. a. sack, account consideration, intention, providence, famil. use, pl.; See also: из расчета, в расчете",
"расчетливый" : "provident thrifty, circumspect",
"расчистить" : "clear",
"расчищать" : "clear",
"расчленить" : "dismember",
"расчленять" : "dismember",
"расшатать" : "loosen, shatter",
"расшатывать" : "loosen, shatter",
"расшевелить" : "pf. stir",
"расшибать" : "s. ушибать",
"расшивать" : "embroider, undo rip",
"расширение" : "widening enlargement, expansion",
"расширить" : "widen enlarge, extend expand, med. dilate",
"расширять" : "widen enlarge, extend expand, med. dilate",
"расшитый" : "fancy",
"расшить" : "embroider, undo rip",
"расшифровавать" : "decipher",
"расшифровать" : "decipher decode",
"расшифровка" : "decoding",
"расшифровывать" : "decipher decode",
"расшнуровать" : "pf. untie",
"расщелина" : "crevice cleft crack",
"расщепить" : "split",
"расщепление" : "splitting, fission",
"расщепленный" : "split",
"расщеплять" : "split",
"расщепляющийся" : "fissile",
"ратификация" : "ratification",
"ратифицировать" : "pf. ratify",
"ратовать" : "fight struggle",
"рафинад" : "lump sugar",
"рафия" : "raffia",
"рахит" : "rickets",
"рахитический" : "rickety",
"рационализировать" : "pf. rationalize",
"рациональный" : "rational",
"рашпиль" : "grater",
"рвануть" : "pf. jerk",
"рвануться" : "dart",
"рваный" : "ragged",
"рвать" : "разорвать изорвать, tear  -ся, сорвать pluck, вырвать pull out, impers. vomit spew, прервать break off, взорвать blow up, рвать и метать famil. be in a rage",
"рваться" : "break, strive #or long",
"рвение" : "zeal, eagerness",
"рвота" : "vomit",
"рвотный" : "emetic",
"рдеть" : "redden flush",
"ре" : "re"
};
