var dicctr_91 = {
"умник" : "wiseacre",
"умножать" : "multiply",
"умножение" : "multiplication",
"умный" : "clever, intelligent, knowledgeable, smart",
"умозрительный" : "speculative",
"умолить" : "s. умолять",
"умолк" : "без умолку",
"умолять" : "beseech, entreat, implore",
"умственный" : "intellective, mental",
"умывальная" : "washroom",
"умывальник" : "wash stand, washbowl Brt. wash-basin",
"умывание" : "washing, wash",
"умывать" : "wash",
"умысел" : "design intent, с умыслом intentionally",
"умыть" : "wash",
"университетский" : "university, varsity",
"унижать" : "abase, demean, humiliate",
"унижение" : "humiliation",
"униженный" : "humble",
"унизительный" : "humiliating",
"унизить" : "humble humiliate abase",
"уникальный" : "unique",
"унимать" : "appease soothe, still, stanch",
"униматься" : "calm #or quiet down, subside",
"унисон" : "unison",
"уничижительный" : "ling. pejorative",
"уничтожать" : "annihilate, destroy, abolish annul",
"уничтожение" : "annihilation",
"уничтожить" : "annihilate, destroy, abolish annul",
"уносить" : "carry take",
"уноситься" : "speed away",
"унтер-офицер" : "corporal",
"унция" : "ounce",
"унывать" : "despond",
"унылый" : "sad dejected",
"уныние" : "despondency, ennui",
"унять" : "appease soothe, still, stanch",
"упадок" : "decay decadence",
"упадок духа" : "dejection",
"упадок сил" : "collapse",
"упадочный" : "decadent, depressive",
"упаковать" : "pack",
"упаковка" : "packing, wrappings pl.",
"упаковщик" : "packer",
"упаковывать" : "pack",
"упаси бог" : "God forbid!",
"упасть" : "s. падать",
"упереть" : "prop stay, rest, popul. steal",
"упереться" : "lean prop, famil. rest, insist on, be obstinate",
"упирать" : "prop stay, rest, popul. steal",
"упираться" : "lean prop, famil. rest, insist on, be obstinate",
"упитанный" : "well-fed fat",
"уплата" : "payment",
"уплатить" : "pay, settle",
"уплачивать" : "pay, meet",
"уплотнить" : "condense compact, fill up",
"уплотнять" : "condense compact, fill up",
"уплывать" : "swim #or sail, pass  vanish",
"уплыть" : "swim #or sail, pass  vanish",
"уповать" : "trust  hope",
"уподобить" : "liken, assimilate",
"уподоблять" : "liken, assimilate",
"упоение" : "rapture ecstasy",
"упоенный" : "enraptured",
"упоительный" : "rapturous delightful, intoxicating",
"уползти" : "pf. creep away",
"уполномоченный" : "plenipotentiary",
"уполномочивать" : "authorize empower",
"уполномочить" : "authorize empower",
"упоминание" : "mention",
"упоминать" : "mention",
"упомянутый" : "mentioned",
"упомянуть" : "mention",
"упор" : "rest, support prop, rail. buffer stop, engin. stop catch; See also: делать упор, в упор",
"упорный" : "pertinacious persistent persevering, stubborn obstinate",
"упорство" : "persistence perseverance, obstinacy",
"упорствовать" : "persevere persist",
"употребительный" : "common customary, current",
"употребить" : "s. употреблять",
"употребление" : "use, usage",
"употреблять" : "use employ, take, make, употребить во зло abuse",
"управдом" : "manager of the house",
"управиться" : "s. управляться",
"управление" : "administration  management, direction, board, engin. control, gr. government",
"управлять" : "manage operate, rule, govern, drive, nav. steer, engin. control, guide, mus. conduct",
"управляться" : "manage, finish",
"управляющий" : "manager, steward",
"упражнение" : "exercise, practice",
"упражнять" : "exercise",
"упразднение" : "abolition",
"упразднить" : "abolish",
"упразднять" : "abolish",
"упрашивать" : "persuade",
"упрек" : "reproach blame",
"упрекать" : "reproach blame",
"упрекнуть" : "reproach blame",
"упросить" : "persuade",
"упростить" : "s. упрощать",
"упрочение" : "consolidation",
"упрочивать" : "consolidate  stabilize",
"упрочить" : "consolidate  stabilize",
"упрощать" : "simplify",
"упрощение" : "simplification",
"упругий" : "elastic resilient",
"упругость" : "elasticity",
"упряжь" : "harness",
"упрямиться" : "be obstinate, persist",
"упрямство" : "obstinacy stubbornness",
"упрямый" : "obstinate stubborn",
"упрятать" : "hide",
"упрятывать" : "hide",
"упускать" : "let go, let escape, miss",
"упустить" : "let go, let escape, miss",
"упущение" : "neglect omission",
"ура" : "hurrah!",
"уравнительный" : "egalitarian",
"уравновешивать" : "counterweigh, equilibrate",
"ураган" : "hurricane",
"уран" : "uranus",
"уранинит" : "pitchblende",
"урановый" : "uranium",
"урегулирование" : "settlement, regulation, cf. регулировать",
"урегулировать" : "regulate, settle",
"урезать" : "cut  curtail",
"урезать урезывать" : "cut  curtail",
"урезонить" : "pf. bring to reason",
"уремия" : "uraemia, uremia",
"уретра" : "urethra",
"урна" : "urn, box",
"уровень" : "level, standard, gauge, rate",
"уровнять" : "s. уравнивать",
"урод" : "monster, famil. ugly creature",
"уродиться" : "pf. grow be born, famil. be like",
"уродливый" : "deformed, ugly, abnormal",
"уродование" : "deformation",
"уродовать" : "deform disfigure, mutilate, spoil",
"уродство" : "deformity, ugliness, abnormity",
"урожай" : "harvest crop",
"урожайность" : "yield  productivity",
"урожайный" : "fruitful",
"урожденная" : "nee",
"уроженец" : "native",
"уроженка" : "native",
"урок" : "lesson, task",
"урон" : "loss, injury",
"уронить" : "drop, droop, lose, shed, fig. disparage discredit",
"урочный" : "set fixed",
"уругвай" : "Uruguay",
"урчать" : "rumble, murmur",
"урывками" : "famil. by fits",
"ус" : "mustache; See also: китовый ус",
"усадить" : "s. усаживать",
"усадка" : "shrink",
"усадьба" : "farm, manor",
"усаживать" : "seat, set, plant",
"усаживаться" : "sit down take a seat, settle down",
"усатый" : "with a mustache",
"усваивать" : "adopt, acquire assimilate, master learn",
"усвоение" : "adoption, acquirement assimilation, mastering learning",
"усвоить" : "adopt, acquire assimilate, master learn",
"усеивать" : "stud",
"усердие" : "zeal eagerness, assiduity",
"усердный" : "eager zealous, assiduous",
"усесться" : "sit down take a seat, settle down",
"усеять" : "stud",
"усидеть" : "pf. remain seated sit still sit, hold out",
"усидчивый" : "assiduous persevering",
"усик" : "dim. #of yc, zo. feeler",
"усиление" : "strengthening reinforcement, intensification, amplification",
"усиленный" : "intense, substantial, pressing",
"усиливать" : "strengthen reinforce, intensify, amplify, aggravate",
"усиливаться" : "increase",
"усилие" : "effort strain exertion",
"усилитель" : "amplifier",
"усилить" : "strengthen reinforce, intensify, amplify, aggravate",
"ускакать" : "pf. leap #or gallop",
"ускользать" : "slip  escape",
"ускользнуть" : "slip  escape",
"ускорение" : "acceleration",
"ускорить" : "speed up accelerate, -ся",
"ускорять" : "speed up accelerate, -ся",
"уславливаться" : "s. условливаться",
"усладить" : "sweeten soften, delight услать s. усылать",
"услаждать" : "sweeten soften, delight услать s. усылать",
"услать" : "send",
"условие" : "condition  term, stipulation, proviso, agreement contract",
"условиться" : "s. условливаться",
"условленный" : "agreed upon fixed",
"условливаться" : "arrange fix agree",
"условность" : "convention",
"условные знаки" : "pl. conditional signes",
"условный" : "conditional, conventional, relative, jur. probational",
"усложнить" : "complicate",
"усложнять" : "complicate",
"услуга" : "service  favor",
"услуживать" : "do a service #or favor",
"услужить" : "do a service #or favor",
"услужливый" : "obliging",
"услыхать" : "s. слышать",
"усматривать" : "see",
"усмехаться" : "smile grin",
"усмехнуться" : "smile grin",
"усмешка" : "smile grin",
"усмирение" : "suppression",
"усмирить" : "pacify, suppress",
"усмирять" : "pacify, suppress",
"усмотрение" : "discretion  judgment",
"усмотреть" : "see",
"уснуть" : "pf. fall asleep, sleep",
"усовершенствование" : "improvement perfection",
"усовершенствованный" : "improved perfected",
"усовершенствовать" : "perfect  improve polish up",
"усомниться" : "doubt",
"усопший" : "deceased",
"успеваемость" : "progress",
"успевать" : "have time manage succeed, arrive be in time, catch, impf. get on make progress learn, не успел  как no sooner  pt. than",
"успевающий" : "advanced",
"успеть" : "have time manage succeed, arrive be in time, catch, impf. get on make progress learn, не успел  как no sooner  pt. than",
"успех" : "success, result, a. progress",
"успешно" : "a. with success",
"успешный" : "successful",
"успокаивать" : "calm soothe, reassure, satisfy",
"успокаиваться" : "calm down, subside, become quiet, content o.s.",
"успокаивающий" : "calming, lenitive, restful, sedative, soothing",
"успокоение" : "peace, calm",
"успокоительный" : "soothing reassuring",
"успокоить" : "calm soothe, reassure, satisfy",
"усср" : ", Ukrainian Soviet Socialist Republic",
"уста" : "mouth lips pl.",
"устав" : "statute, regulations pl., charter",
"уставать" : "get tired",
"уставить" : "place, cover  fill, fix",
"уставиться" : "stare",
"уставлять" : "place, cover  fill, fix",
"уставляться" : "stare",
"усталость" : "weariness fatigue",
"усталый" : "tired weary",
"устанавливать" : "set #or put up, mount, arrange, fix, establish, find out ascertain, adjust",
"устанавливаться" : "be established, form, set in",
"установить" : "set #or put up, mount, arrange, fix, establish, find out ascertain, adjust",
"установиться" : "be established, form, set in",
"установка" : "mounting installation, engin. plant, fig. orientation",
"установление" : "establishment",
"устаревший" : "moldy, outworn, passe",
"устарелый" : "obsolete out-of-date",
"устать" : "get tired",
"устилать" : "cover lay out",
"устлать" : "cover lay out",
"устно" : "viva, viva voce",
"устный" : "oral verbal"
};
