var dicctr_31 = {
"канадка" : "Canadian",
"канадский" : "Canadian",
"канак" : "kanaka",
"канал" : "canal, channel, pipe",
"канализация" : "canalization, severage",
"канарейка" : "canary",
"канат" : "rope cable",
"канатный" : "rope cable",
"канва" : "canvas, fig. basis, outline",
"кандалы" : "fetters shackles",
"канделябры" : "candelabra",
"кандидат" : "candidate, a. #lowest #Sov. #univ. #degree #approx. = master",
"каникулы" : "vacation a. holidays",
"канитель" : "fuss, trouble, humdrum monotony",
"канонада" : "cannonade",
"канонерка" : "gunboat",
"канонический" : "canonic, canonical",
"каноэ" : "canoe",
"канун" : "eve",
"кануть" : "pf. sink fall; See also: как в воду кануть, кануть в вечность",
"кануть в вечность" : "pass into oblivion",
"канцелярия" : "office secretariat",
"канцелярский" : "office..., writing, clerk's",
"канцелярщина" : "red tape",
"каньон" : "canyon",
"капанье" : "drip",
"капать" : "drip drop trickle, leak",
"капель" : "eavesdrop",
"капелька" : "droplet, famil. bit grain",
"капилляр" : "capillary",
"капитал" : "commerc. capital, stock",
"капитализм" : "capitalism",
"капиталист" : "capitalist, capitalist",
"капиталовложение" : "investment",
"капитальный" : "capital, dear expensive, main, thorough",
"капитан" : "nav. captain",
"капитулировать" : "pf. capitulate",
"капитуляция" : "capitulation",
"капкан" : "trap",
"капля" : "drop, famil. bit grain",
"каплями" : "by drops, как две капли воды as two peas",
"капнуть" : "drip drop trickle, leak",
"капот" : "dressing gown, overcoat, Brt. bonnet",
"каприз" : "whim caprice",
"капризничать" : "be capricious",
"капризный" : "capricious whimsical",
"капсула" : "capsule",
"капсюль" : "percussion cap",
"капуста" : "cabbage; See also: кислая капуста",
"капут" : "ruin end",
"капюшон" : "hood",
"кара" : "punishment",
"карабин" : "carbine",
"карабканье" : "clamber",
"карабкаться" : "climb",
"каравай" : "loaf",
"караван" : "caravan",
"караемый" : "jur. punishable",
"каракатица" : "cuttle, cuttlefish",
"каракулевый" : "astrakhan",
"каракули" : "scrawl",
"каракуль" : "astrakhan",
"каракуля" : "scrawl",
"карандаш" : "pencil",
"карантин" : "quarantine",
"карапуз" : "tot, hop-o'-my-thumb",
"карась" : "crucian",
"карат" : "carat, karat",
"карательный" : "punitive",
"карать" : "punish",
"каратэ" : "karate",
"караул" : "sentry guard, взять на караул! present arms!, стоять на карауле stand sentinel, famil. караул! help! murder!",
"караулить" : "guard watch",
"караульная" : "guardroom",
"караульный" : "sentry...",
"караульня" : "guardroom",
"карачи" : "karachi",
"карбид" : "carbide",
"карболовый" : "carbolic",
"карбункул" : "carbuncle",
"карбюратор" : "carburetor",
"кардиология" : "cardiology",
"карел" : "Karelian",
"карелия" : "Karelia",
"карелка" : "Karelian",
"карета" : "carriage coach",
"карий" : "brown, bay",
"карикатура" : "caricature cartoon",
"карикатурный" : "caricature..., comic funny",
"каркас" : "frame skeleton",
"каркать" : "croak  caw",
"каркнуть" : "croak  caw",
"карлик" : "dwarf pygmy",
"карликовый" : "dwarf..., dwarfish",
"карман" : "pocket, это мне не по карману famil. I can't afford that, это бьет по карману that makes a hole in my purse, держи ~ that's a vain hope, он за словом в ~ не лезет he has a ready tongue",
"карманный" : "pocket..., note",
"карманный вор" : "pickpocket, cf. фонарик",
"кармин" : "carmine",
"карнавал" : "carnival",
"карниз" : "cornice",
"карп" : "carp",
"карпаты" : "Carpathian Mts",
"карта" : "map, nav. chart, card, menu, ставить на карту, stake",
"картавить" : "jar #Russ. r & l",
"картежник" : "gambler",
"картель" : "cartel",
"картечь" : "case shot",
"картина" : "picture, movie image, painting, scene",
"картинка" : "picture illustration",
"картинный" : "picture..., picturesque vivid",
"картография" : "cartography",
"картон" : "cardboard pasteboard, картонка",
"картонка" : "box, hatbox",
"картонный" : "pasteboard",
"картотека" : "card index",
"картофелина" : "spud",
"картофель" : "pl.",
"карточка" : "card, famil. ticket, photo, menu",
"карточная система" : "rationing system",
"карточный" : "card...; See also: карточная система, карточный домик",
"карточный домик" : "house of cards",
"картошка" : "potato",
"картуз" : "cap, obsol. pack",
"карусель" : "merry-go-round",
"карцер" : "dungeon, lockup",
"карьер" : "full gallop; See also: с места в карьер",
"карьера" : "career, fortune",
"карьерист" : "careerist",
"касательная" : "tangent",
"касательно" : "concerning",
"касательный" : "tangential",
"касаться" : "touch, concern, famil. be about deal #or be concerned with, дело касается s. идти`, что касается ... то as for",
"каска" : "helmet",
"каскад" : "cascade",
"каспийский" : "Caspian",
"касса" : "pay desk #or office, rail. ticket window, Brt. booking office, thea. box office, bank, fund, cash, cash register, money box #or chest safe",
"кассационный" : "s. апелляционный",
"кассация" : "reversal",
"кассета" : "phot. plate holder",
"кассир" : "cashier",
"кассирша" : "cashier",
"каста" : "caste",
"касторовый" : "castor",
"кастрированный" : "neuter",
"кастрировать" : "pf. castrate",
"кастрюля" : "saucepan, pot",
"катализ" : "catalysis",
"катализатор" : "accelerant, accelerator, catalyst",
"каталитический" : "catalytic",
"каталог" : "catalogue",
"катание" : "driving riding skating etc.",
"катапульта" : "catapult",
"катастрофа" : "catastrophe",
"катастрофический" : "catastrophic",
"катать" : "roll, mangle; See also: покатать",
"кататься" : "drive ride  row, skate, sled  etc., roll",
"катафалк" : "catafalque, hearse",
"категорический" : "categorical",
"категория" : "category",
"катер" : "cutter; See also: торпедный катер",
"катить" : "roll drive wheel",
"катод" : "cathode",
"катодный" : "cathodic",
"каток" : "rink, mangle, engin. roll",
"католик" : "Catholic",
"католический" : "Catholic",
"католичество" : "catholicism",
"католичка" : "Catholic",
"каторга" : "hard labor in exile, place of such penal servitude, fig. drudgery misery",
"каторжанин" : "convict",
"каторжник" : "convict",
"каторжный" : "hard penal, s. каторга, su. = каторжник",
"катушка" : "spool, el. coil",
"катюша" : "Kitty Kate",
"катя" : "Kitty Kate",
"каучук" : "caoutchouc rubber",
"кафе" : "cafe",
"кафедра" : "platform pulpit lecturing desk, chair cathedra",
"кафель" : "tile",
"кафетерий" : "cafeteria",
"качалка" : "rocking chair",
"качание" : "rocking, swing, pumping",
"качать" : "покачать once качнуть rock, swing, shake  toss, nav. roll pitch, накачать pump",
"качели" : "swing",
"качественный" : "qualitative",
"качество" : "quality, в качестве as in one's capacity as in the capacity of",
"качка" : "rolling, pitching",
"качнуть" : "s. качать",
"кашалот" : "cachalot",
"кашель" : "cough",
"кашицеобразный" : "pappy",
"кашне" : "neckscarf",
"каштан" : "chestnut",
"каштановый" : "chestnut",
"каюта" : "cabin stateroom",
"кающийся" : "contrite",
"каяться" : "repent",
"кв" : "abbr.:, квадратный, квартира",
"квадрант" : "quadrant",
"квадратный" : "foursquare, quadrate, quadratic",
"квадратура" : "quadrature",
"квадрильон" : "quadrillion",
"квакать" : "croak",
"квалифицированный" : "qualified",
"квалифицировать" : "qualify",
"квантовый" : "quantum",
"кварта" : "quart",
"квартет" : "quartet, quartette",
"квартирмейстер" : "quartermaster",
"квартирная плата" : "rent",
"квартирный" : "housing house...; See also: квартирная плата, квартплата",
"квартплата" : "rent",
"кварцевый" : "quartz",
"квас" : "quass",
"квасить" : "sour",
"квасцовый" : "aluminous",
"квасцы" : "alum",
"квашеный" : "sour leavened",
"кверху" : "up upward",
"квинт" : "quint",
"квинтет" : "quintet, quintette",
"квинтэссенция" : "quintessence",
"квит" : "famil. quits even square",
"кворум" : "quorum",
"квота" : "quota",
"кедр" : "cedar",
"кельтский" : "Celtic",
"келья" : "eccl. cell",
"кем" : "= cf.",
"кембридж" : "cambridge",
"кембрийский" : "cambrian",
"кенгуру" : "kangaroo",
"кения" : "kenya",
"кентавр" : "centaur",
"кепи" : "cap",
"кепка" : "cap",
"керамика" : "ceramics",
"керамиковый" : "ceramic",
"керамический" : "ceramic",
"керосин" : "kerosene",
"керосиновый" : "kerosene",
"кессон" : "coffer",
"кета" : "Siberian salmon",
"кетцаль" : "quetzal",
"кетчуп" : "catchup, ketchup",
"кефаль" : "mullet",
"кефир" : "kefir",
"кеч" : "ketch",
"кибитка" : "tilt cart",
"кивать" : "nod, beckon, point"
};
