var dicctr_29 = {
"император" : "emperor",
"императорский" : "imperial",
"императрица" : "empress",
"империализм" : "imperialism",
"империалист" : "imperialist",
"империалистический" : "imperialist",
"империя" : "empire",
"импорт" : "pf. import",
"импортировать" : "pf. import",
"импотентный" : "impotent",
"импровизация" : "improvisation",
"импровизированный" : "ad-lib, extemporaneous, extemporary, impromptu",
"импровизировать" : "& сымпровизировать improvise",
"импульс" : "impulse",
"импульсивный" : "impulsive",
"имущество" : "property, belongings pl., движимое имущество pl.",
"имущий" : "well-to-do",
"имя" : "name, имени: школа им. Чехова Chekhov school; See also: именем, во имя, от имени, на имя, по имени",
"инакомыслящий" : "dissentient, dissident, nonconformist",
"иначе" : "differently, otherwise else; See also: не иначе как, так или иначе",
"иначе говоря" : "in other words",
"инвалид" : "invalid; See also: инвалид труда, инвалид войны",
"инвалид войны" : "disabled veteran Brt. ex-serviceman",
"инвалид труда" : "disabled worker",
"инвариантный" : "invariant",
"инвентаризация" : "inventory stock-taking",
"инвентарь" : "inventory, stock, implements fittings pl.",
"индеец" : "Indian",
"индеец-могавк" : "mohawk",
"индейка" : "turkey",
"индейский" : "Indian, индейский петух = индюк",
"индекс" : "index, subscript",
"индексы" : "indices",
"индианка" : "#fem. #of индеец & индиец",
"индивид" : "individual",
"индивидуализм" : "individualism",
"индивидуальный" : "individual",
"индивидуум" : "individual",
"индиец" : "Indian Hindu",
"индий" : "indium",
"индийский" : "Indian  Hindu",
"индия" : "India",
"индокитай" : "Indo-China",
"индокитайский" : "indochinese",
"индонезия" : "Indonesia",
"индостан" : "Hindustan",
"индуизм" : "hinduism",
"индус" : "Hindu",
"индуска" : "Hindu",
"индусский" : "Hindu",
"индустриализация" : "industrialization",
"индустриализовать" : "pf. industrialize",
"индюк" : "turkey cock",
"иней" : "frost",
"инертный" : "inert",
"инерционный" : "inertia",
"инерция" : "inertia, по инерции mechanically",
"инженер" : "engineer",
"инженерный" : "engineering",
"инженер-строитель" : "civil engineer",
"инициалы" : "initials",
"инициатива" : "initiative",
"инициатор" : "initiator",
"инквизитор" : "inquisitor",
"иногда" : "sometimes now and then",
"иногородний" : "nonresident foreign",
"иноземец" : "foreigner",
"иноземный" : "foreign",
"иной" : "other different, some many a",
"иной раз" : "sometimes, не кто иной  как ... nobody else but ...",
"инородное тело" : "foreign matter",
"иносказание" : "circumlocution, parable",
"иносказательный" : "allegorical",
"иностранец" : "foreigner",
"иностранка" : "foreigner",
"иностранный" : "foreign, a. министерство",
"иноходь" : "amble",
"инспектор" : "inspector",
"инстанция" : "jur. instance, pl. channels, hierarchy",
"инстинкт" : "instinct",
"инстинктивный" : "instinctive",
"институт" : "institute, institution, form. boarding school",
"инструмент" : "instrument",
"инструментовать" : "orchestrate",
"инструментовка" : "instrumentation",
"инсценировать" : "pf. stage screen, fig. feign",
"инсценировка" : "staging etc., direction, dramatization",
"интеграл" : "integral",
"интегральный" : "integral",
"интеллектуальный" : "intellectual",
"интеллигент" : "intellectual",
"интеллигентность" : "intelligence",
"интеллигентный" : "intelligent, intellectual",
"интеллигенция" : "intelligentsia intellectuals pl.",
"интендант" : "milit. commissary",
"интендантство" : "commissariat",
"интенсивный" : "intense intensive",
"интервал" : "interval",
"интервенция" : "intervention",
"интервью" : "pf. interview",
"интервьюировать" : "pf. interview",
"интервьюируемый" : "interviewed, interviewee",
"интерес" : "interest, famil. use",
"интересный" : "interesting, famil. handsome attractive",
"интересовать" : "interest",
"интересоваться" : "be interested take an interest in",
"интернат" : "boarding school, hostel",
"интернационал" : "International",
"интернациональный" : "international",
"интернирование" : "internment",
"интернировать" : "pf. intern",
"интимность" : "intimacy",
"интимный" : "intimate",
"интонировать" : "intonate, intone",
"интрига" : "intrigue",
"интриган" : "intriguer",
"интриганка" : "intrigante",
"интриговать" : "intrigue",
"интуитивный" : "intuitive",
"интуиция" : "intuition",
"интурист" : "State bureau of foreign tourism",
"инфаркт" : "infarct, infarction",
"инфекция" : "infection",
"инфляционный" : "inflationary",
"инфляция" : "inflation",
"информационный" : "informative",
"информация" : "information",
"информбюро" : "Information Bureau Cominform",
"информировать" : "inform",
"ио" : "= исполняющий обязанности",
"иомен" : "yeoman",
"ион" : "ion",
"ионный" : "ionic",
"ионосфера" : "ionosphere",
"ионы" : "dihydric",
"иорданский" : "jordan",
"ипподром" : "hippodrome",
"ирак" : "iraq",
"иран" : "iran",
"иранский" : "irani, iranian",
"иридий" : "iridium",
"ириска" : "toffee",
"ирландец" : "irishman, milesian",
"ирландия" : "erin, ireland",
"ирландский" : "irish",
"иронический" : "ironic, ironical",
"ирония" : "satire",
"искажать" : "distort, garble, misrepresent",
"искажение" : "distortion",
"искаженный" : "awry, warped",
"искатель" : "finder, selector",
"искать" : "look for, seek, jur. sue",
"исключать" : "exclude leave out, expel; See also: исключая, исключено",
"исключая" : "except",
"исключение" : "exclusion, expulsion, exception",
"исключено" : "impossible",
"исключительный" : "exceptional, exclusive, extraordinary, famil. excellent, a. solely only",
"исключить" : "exclude leave out, expel; See also: исключая, исключено",
"исковеркать" : "distort deform, mutilate, murder",
"искомкать" : "crumple",
"искомый" : "sought looked for",
"искони" : "obsol. = издавна",
"исконный" : "original native, arch...",
"ископаемый" : "fossil, mined, su. minerals; See also: полезные ископаемые",
"искоренить" : "extirpate",
"искоренять" : "extirpate",
"искоса" : "askance asquint",
"искра" : "spark, spangle",
"искренний" : "sincere frank candid",
"искренно преданный вам" : "Sincerely yours",
"искренность" : "sincerity frankness",
"искривить" : "bend  crook, distort disfigure",
"искривлять" : "bend  crook, distort disfigure",
"искристый" : "sparkling",
"искриться" : "sparkle scintillate",
"искромсать" : "hack mangle",
"искрошить" : "crumb, popul. crush",
"искупать" : "atone for expiate",
"искупаться" : "take a bath, bathe",
"искупить" : "atone for expiate",
"искупление" : "atonement expiation",
"искус" : "trial",
"искуситель" : "tempter",
"искусительница" : "temptress",
"искусить" : "s. искушать",
"искусный" : "skilful skilled",
"искусственный" : "artificial, false  imitation",
"искусство" : "art, skill",
"искушать" : "tempt",
"искушение" : "temptation",
"искушенный" : "tried, versed experienced",
"ислам" : "Islam",
"исландия" : "Iceland",
"исландский" : "icelandic",
"испанец" : "Spaniard",
"испания" : "Spain",
"испанка" : "Spaniard",
"испанский" : "Spanish",
"испарение" : "evaporation, a. vapor",
"испарить" : "evaporate",
"испарять" : "evaporate",
"испаряться" : "transpire",
"испачкать" : "soil",
"испепелить" : "burn to ashes",
"испепелять" : "burn to ashes",
"испестрить" : "mottle speckle variegate, stud, interlard",
"испестрять" : "mottle speckle variegate, stud, interlard",
"испечь" : "bake, scorch",
"испещрить" : "mottle speckle variegate, stud, interlard",
"испещрять" : "mottle speckle variegate, stud, interlard",
"исписать" : "write  write upon  fill, исписан full of notes etc., famil. use up, -ся o.s. out, be used up",
"исписывать" : "write  write upon  fill, исписан full of notes etc., famil. use up, -ся o.s. out, be used up",
"испитой" : "emaciated",
"исповедание" : "confession, creed",
"исповедать" : "obsol. = исповедовать",
"исповедник" : "confessor",
"исповедовать" : "pf. confess, profess, famil. interrogate",
"исповедь" : "confession",
"исподволь" : "famil. gradually",
"исподлобья" : "frowningly",
"исподтишка" : "famil. on the quiet",
"испокон" : "~ веку = издавна",
"исполинский" : "gigantic",
"исполком" : "executive committee",
"исполнение" : "execution, fulfilment performance, приводить в исполнение = исполнять",
"исполнимый" : "realizable, practicable",
"исполнитель" : "executor, mus. performer, jur. bailiff",
"исполнительный" : "executive, industrious",
"исполнительный комитет" : "executive committee",
"исполнить" : "carry out execute, fulfil do, hold fill, keep, mus. perform, -ся come true, be: ему исполнилось пять лет he is five, pass",
"исполнять" : "carry out execute, fulfil do, hold fill, keep, mus. perform, -ся come true, be: ему исполнилось пять лет he is five, pass",
"исполняющий обязанности" : "acting",
"использование" : "use utilization",
"использовать" : "pf. use utilize",
"испортить" : "s. портить",
"испорченность" : "corruption, depravity",
"испорченный" : "spoilt broken, depraved",
"исправдом" : "reformatory reform school",
"исправимый" : "corrigible",
"исправительный" : "correctional, s. исправдом",
"исправить" : "correct, improve, reform, repair, impf. hold, -ся reform",
"исправление" : "correction, improvement, reform",
"исправлять" : "correct, improve, reform, repair, impf. hold, -ся reform",
"исправность" : "intactness, accuracy",
"исправный" : "intact in good order, accurate correct, diligent industrious",
"испражнение" : "med. evacuation, pl. feces",
"испражниться" : "med. evacuate",
"испражняться" : "med. evacuate",
"испуг" : "fright",
"испуганный" : "afraid, frightened, scared"
};
