var dicctr_60 = {
"плошать" : "blunder",
"площадка" : "ground, playground, court, platform, landing",
"площадной" : "vulgar",
"площадь" : "square, area, space s. жилплощадь",
"плуг" : "plow Brt. plough",
"плут" : "rogue, trickster cheat",
"плутать" : "stray",
"плутовать" : "trick cheat",
"плутовской" : "roguish, rogue...",
"плутовство" : "roguery",
"плутоний" : "plutonium",
"плыть" : "swim, float sail, cf. плавать",
"плюгавый" : "shabby",
"плюнуть" : "spit, famil. not care",
"плюс" : "plus, famil. advantage",
"плюш" : "plush",
"плюшевый" : "plushy",
"плющ" : "ivy",
"пляж" : "beach",
"плясать" : "dance",
"пляска" : "dance, dancing",
"плясовой" : "dance... dancing",
"пневматический" : "pneumatic",
"пневмокок" : "pneumococcus",
"пневмония" : "pneumonia",
"по" : "on along, through, all over, in, by, according to after, through, owing to, for, over, across, upon, each at a time, to up to, till through, for, on; See also: по мне, по часу в день",
"по-" : ": cf. русский ваш",
"по виду" : "by sight, judging from one's appearance",
"по временам" : "from time to time now and then sometimes",
"по выбору" : "at a pers.'s discretion, random",
"по доброй воле" : "of one's own will",
"по душам" : "heart-to-heart",
"по дюжинам" : "by the dozen",
"по закону" : "according to law",
"по имени" : "named, in name, by name",
"по мне" : "for all I care",
"по обыкновению" : "as usual",
"по порядку" : "one after another, current",
"по правде говоря" : "to tell the truth",
"по прозвищу" : "nicknamed",
"по сердцу" : "to one's liking",
"по словам" : "according to",
"по случаю" : "second hand, on account of",
"по совести" : "honestly",
"по совести говоря" : "to tell the truth",
"по справедливости" : "by rights",
"по счастью" : "fortunately",
"по уши" : "over head and ears",
"по часу в день" : "an hour a day",
"побагроветь" : "become purple redden",
"побаиваться" : "be afraid of",
"побег" : "escape flight, bot. shoot sprout",
"побегать" : "run, famil. shun, fig. run after; See also: бегать взапуски",
"побегушки" : "быть на побегушках",
"победа" : "victory, win through",
"победоносный" : "victor, victorious",
"побеждать" : "vanquish",
"побережье" : "coast",
"поблизости" : "hereabout, thereabouts",
"побои" : "whipping",
"побоище" : "battle",
"поборник" : "advocate",
"побороть" : "pf. conquer, overcome, beat",
"побочный" : "accessory incidental casual, secondary, subsidiary, by-, illegitimate",
"побояться" : "be afraid  fear; See also: боюсь сказать",
"побранить" : "scold rebuke abuse, -ся quarrel wrangle, swear curse",
"побрататься" : "fraternize",
"побрести" : "drag lag, grope",
"побрить" : "shave, -ся get shaved shave",
"побудительная причина" : "motive",
"побудительный" : "incentive",
"побудить" : "induce prompt impel",
"побуждать" : "induce prompt impel",
"побуждающий" : "stimulant",
"побуждение" : "motive impulse incentive",
"побывка" : "stay visit",
"повадиться" : "pf. fall into the habit",
"повадка" : "famil. habit, popul. encouragement",
"повалить" : "overturn tumble  fell, heap  dump, flock throng, снег валит it is snowing heavily",
"повальный" : "epidemic, general",
"повалять" : "roll, knead, full, popul. валяй! go!; See also: валять дурака",
"повар" : "cook",
"поваренный" : "culinary, cook, kitchen",
"повариха" : "cook",
"поведение" : "behavior conduct",
"повезти" : "drive  transport, pull, ему везет famil. he is lucky",
"повелевать" : "rule",
"повелеть" : "order, command",
"повелительный" : "imperative",
"повергать" : "throw #or cast, put into",
"повергнуть" : "throw #or cast, put into",
"поверенный" : "confidant, plenipotentiary, charge'",
"поверить" : "believe, believe trust; See also: поверить на слово",
"поверить на слово" : "take on trust",
"поверка" : "check, roll call",
"повернуть" : "s. поворачивать",
"поверхностный" : "sketchy, skin-deep, superficial",
"поверхность" : "superficies, surface",
"поверять" : "confide, unbosom",
"повеса" : "lothario, playboy",
"повествовательный" : "narrative; See also: повествовательное предложение",
"повествовать" : "narrate",
"повести" : "lead conduct guide, carry on, keep, drive, вести начало spring; See also: вести себя",
"повестка" : "summons, notice",
"повестка дня" : "agenda",
"повесть" : "story tale, narrative",
"повешение" : "hanging",
"повидать" : "его давно не видать, I #or we haven't seen him for a long time, -ся meet see",
"по-видимому" : "apparently",
"повидло" : "jam fruit butter",
"повинная" : "confession",
"повинность" : "duty",
"повинный" : "guilty, owing",
"повиноваться" : "obey, submit",
"повиновение" : "obedience",
"повиснуть" : "hang be suspended",
"повлечь" : "drag pull, fig. attract draw; See also: влечь за собой",
"повлиять" : "influence",
"повод" : "cause, occasion по поводу a. concerning, rein; See also: на поводу",
"поводить" : "lead conduct guide, drive, move, breed; See also: водить дружбу",
"поводья" : "rein, reins",
"повозка" : "cart, wagon",
"поволжье" : "Volga region",
"поволочить" : "drag pull draw",
"поворачивать" : "turn",
"поворожить" : "tell fortunes",
"поворот" : "turn",
"поворотить" : "turn",
"поворотливый" : "nimble agile",
"поворотный" : "turning",
"поворчать" : "grumble growl",
"повредить" : "injure",
"повреждать" : "impair",
"повреждение" : "damage, injury, lesion",
"повременный" : "periodical, time...",
"повседневный" : "everyday, daily",
"повсеместно" : "everywhere",
"повсеместный" : "general universal",
"повстанец" : "rebel insurgent",
"повстанческий" : "rebel",
"повсюду" : "everywhere",
"повторение" : "repetition, review",
"повторительный" : "repetitive",
"повторить" : "repeat, review",
"повторный" : "repeated second",
"повторять" : "repeat, review",
"повторяющийся" : "iterant, iterative",
"повысить" : "raise, promote, -ся rise, advance",
"повышать" : "raise, promote, -ся rise, advance",
"повышение" : "rise, promotion",
"повышенный" : "increased higher",
"повязать" : "bind, put on",
"повязка" : "bandage, band armlet",
"повязывать" : "bind, put on",
"поганка" : "grebe, toadstool",
"погасить" : "extinguish put #or blow out, slake",
"погаснуть" : "go out die away, fig. fade wither",
"погашать" : "put out extinguish, discharge",
"погашение" : "amortization",
"погибать" : "perish",
"погибель" : "s. гибель",
"погибнуть" : "perish",
"погибший" : "lost",
"поглотить" : "swallow up devour, absorb",
"поглощать" : "swallow up devour, absorb",
"поглощающий" : "absorbent",
"поглощение" : "absorption",
"поглупеть" : "become stupid",
"поглядеть" : "look glance, famil. look after take care of, peep, famil. гляди very likely, look out!, того и гляди ... may  inf., куда глаза глядят at random, after one's nose",
"поглядывать" : "look",
"погнать" : "drive, famil. send, float, distil, pursue chase, speed along",
"погнушаться" : "scorn despise disdain",
"поговаривать" : "speak, say",
"поговорить" : "speak #or talk, say tell; See also: говорят, говорится, говорить по-русски, иначе говоря, не говоря уже о, по правде говоря, по совести говоря, что вы говорите{!}, что ни говори, как ни говори, что и говорить, и не говори{!}",
"поговорка" : "saying proverb",
"погода" : "weather",
"погодить" : "pf. wait",
"погодостойкий" : "weatherproof",
"погодя" : "later",
"поголовно" : "without exception",
"поголовный" : "general universal",
"поголовье" : "livestock",
"погон" : "epaulet shoulder strap",
"погонщик" : "drover",
"погоня" : "pursuit, pursuers pl.",
"погонять" : "drive #or urge  hurry",
"погоревать" : "grieve, regret",
"погорелец" : "burnt down pers.",
"погост" : "churchyard",
"пограничник" : "frontier guard",
"пограничный" : "frontier...",
"погреб" : "cellar, magazine",
"погребальный" : "funeral",
"погребать" : "bury inter",
"погребение" : "burial, funeral",
"погремушка" : "rattle",
"погрести" : "row, scull, rake, scoop",
"погрешность" : "error fault",
"погрозить" : "threaten",
"погром" : "pogrom",
"погружать" : "immerse, sink plunge submerge, -женный a. absorbed lost, load ship",
"погружение" : "immersion",
"погруженный" : "immersed, invested, sunken, wrapped up in",
"погрузить" : "load embark",
"погрузка" : "loading shipment",
"погрязать" : "sink",
"погрязнуть" : "sink",
"погубить" : "destroy ruin, waste",
"погулять" : "go for a walk  stroll, fig. sweep, make merry",
"под" : ":, under, toward to, about, on the eve of, a la in imitation of, for suitable as, :, under below beneath, near by of, for with, поле под рожью rye field",
"подавление" : "suppression",
"подавленный" : "depressed, despondent",
"подавлять" : "browbeat, depress, mortify, overbear, overpower",
"подавно" : "famil. so much #or all the more",
"подагра" : "gout, podagra",
"подальше" : "famil. rather far off",
"подарить" : "give  present",
"подарок" : "present gift",
"податель" : "bearer, petitioner",
"податливый" : "pliant",
"подать" : "give, serve, drive up get ready, move, hand in, lodge  bring, set, render, raise, не подавать виду s. показывать",
"подача" : "giving, serving, serve, presentation, rendering, supply",
"подача голоса" : "voting",
"подачка" : "charity gift",
"подаяние" : "alms",
"подбадривать" : "invigorate",
"подбегать" : "run up",
"подбежать" : "run up",
"подбивать" : "line fur, sole, hit injure, famil. instigate incite",
"подбирать" : "pick up, tuck up, draw in, pick out select, -ся sneak up",
"подбитый" : "famil. black",
"подбить" : "line fur, sole, hit injure, famil. instigate incite",
"подбор" : "picking up #or out, selection, assortment, на подбор chosen select",
"подбородок" : "chin",
"подбрасывать" : "throw, jolt, add, foist palm",
"подбросить" : "throw, jolt, add, foist palm",
"подвал" : "basement, cellar",
"подвезти" : "s. подвозить",
"подвергать" : "subject expose, -ся undergo, be exposed, run",
"подвергаться" : "go through, incur",
"подвергнуть" : "subject expose, -ся undergo, be exposed, run",
"подвержение" : "subjection",
"подверженный" : "subject",
"подвесить" : "s. подвешивать",
"подвесной" : "handing, engin. suspension",
"подвести" : "s. подводить",
"подветренный" : "leeward",
"подвешивать" : "hang, fix",
"подвздошный" : "iliac",
"подвиг" : "feat exploit deed"
};
