var dicctr_46 = {
"нееврей" : "gentile",
"неестественный" : "unnatural, affected forced",
"нежелание" : "unwillingness",
"нежелательный" : "undesirable",
"нежели" : "obsol. = чем than",
"неженатый" : "single unmarried",
"неженка" : "coddle, mollycoddle, sissy",
"нежизненный" : "impracticable, unreal",
"нежилой" : "uninhabited, deserted desolate, store...",
"нежить" : "coddle pamper fondle",
"нежиться" : "loll lounge",
"нежничать" : "indulge in caresses",
"нежность" : "tenderness, fondness, civility",
"нежный" : "tender fond, delicate, soft, sentimental",
"незабвенный" : "unforgettable",
"незабудка" : "forget-me-not",
"незабываемый" : "unforgettable",
"независимость" : "independence",
"независимый" : "independent",
"незадачливый" : "unlucky",
"незадолго" : "shortly",
"незаконнорожденный" : "bastard, illegitimate, unfathered, whoreson",
"незаконность" : "illegitimacy",
"незаконный" : "illegal unlawful illegitimate, illicit",
"незамедлительность" : "immediacy",
"незамедлительный" : "prompt",
"незаменимый" : "irreplaceable",
"незаметно" : "insinuate",
"незаметный" : "imperceptible, unnoticeable plain ordinary humdrum",
"незамеченный" : "unnoticed",
"незамысловатый" : "simple plain, dull",
"незанятый" : "easeful, unoccupied, vacant",
"незапамятный" : "immemorial",
"незатейливый" : "plain simple",
"незаурядный" : "remarkable",
"незачем" : "there is no need #or point",
"незваный" : "uninvited",
"нездоровиться" : "мне нездоровится",
"незнакомец" : "newcomer",
"незначительный" : "insignificant",
"незрелый" : "unripe, immature",
"незримый" : "invisible",
"незыблемый" : "firm, unshakable",
"неизбежный" : "inevitable",
"неизведанный" : "неизвестный",
"неизвестность" : "suspense",
"неизвестный" : "unknown, a. stranger",
"неизгладимый" : "indelible",
"неизлечимый" : "incurable",
"неизменный" : "invariable, permanent, true",
"неизменяемый" : "irrevocable",
"неизмеримый" : "immense",
"неизьяснимый" : "inexplicable",
"неизящный" : "inelegant",
"неимение" : "за неимением",
"неискоренимый" : "ineradicable",
"неискренний" : "insincere",
"неискусный" : "unskillful",
"неисполнение" : "nonfulfillment",
"неисполнимый" : "impracticable",
"неисправимый" : "incorrigible",
"неисправность" : "engin. disrepair",
"неисправный" : "out of repair #or order broken defective, careless faulty, inaccurate, unpunctual",
"неиссякаемый" : "inexhaustible",
"неистовство" : "rage frenzy, atrocity",
"неистовствовать" : "rage",
"неистовый" : "frantic furious",
"неистощимый" : "inexhaustible",
"неистребимый" : "ineradicable",
"неисцелимый" : "incurable",
"неисчерпаемый" : "s. неистощимый",
"неисчислимый" : "innumerable",
"нейлоновый" : "nylon",
"нейрон" : "neuron, neurone",
"нейтралитет" : "neutrality",
"нейтральный" : "neutral",
"нейтрино" : "neutrino",
"нейтрон" : "neutron",
"неказистый" : "= невзрачный",
"некий" : "a certain some",
"некогда" : "there is no time, once",
"некого" : "there is nobody #or no one",
"некомпетентный" : "incompetent",
"некоторый" : "some",
"некрасивый" : "homely ugly, mean",
"некролог" : "obituary",
"некромантия" : "necromancy",
"некстати" : "inopportunely, inappropriately malapropos off the point",
"нектар" : "nectar",
"нектарин" : "nectarine",
"нектарник" : "nectary",
"некто" : "somebody -one, a certain",
"некуда" : "there is no, a. незачем, famil. could not be",
"некультурный" : "uncultured, ill-mannered",
"некурящий" : "nonsmoker nonsmoking",
"неладный" : "wrong bad",
"нелегальный" : "illegal",
"нелепый" : "absurd, famil. awkward",
"неловкий" : "awkward clumsy, inconvenient embarrassing",
"нелогичный" : "illogical",
"нельзя" : "impossible one cannot must not, нельзя! no!, ~ не s. мочь; See also: как нельзя лучше",
"нельсон" : "nelson",
"нелюдимый" : "unsociable",
"немало" : "a lot a great deal",
"немедленный" : "immediate",
"немезида" : "nemesis",
"неметь" : "grow dumb numb",
"немец" : "German",
"немецкий" : "German",
"немилосердный" : "unmerciful ruthless",
"немилостивый" : "ungracious",
"немилость" : "disgrace",
"неминуемый" : "inevitable",
"немка" : "German",
"немногие" : "few some",
"немногим" : "a little",
"немного" : "a little, slightly somewhat, a. немногие",
"немногое" : "little",
"немножко" : "famil. a bit",
"немой" : "dumb, mute",
"немощный" : "infirm",
"ненавидеть" : "detest, hate",
"ненавистный" : "accurst, hated, hateful, odious",
"ненависть" : "odium",
"ненарушенный" : "inviolate",
"ненастный" : "rainy foul",
"ненастье" : "foul weather",
"ненасытный" : "insatiable",
"ненормальный" : "abnormal, famil. deranged",
"ненужный" : "unnecessary",
"необдуманный" : "rash hasty",
"необитаемый" : "uninhabited, desert",
"необозримый" : "immense vast",
"необоснованный" : "unfounded",
"необработанный" : "uncultivated, crude unpolished",
"необратимый" : "irreversible",
"необузданный" : "unbridled unruly",
"необходимое" : "necessary",
"необходимость" : "necessity  need",
"необходимый" : "necessary  essential, cf. нужный",
"необщественный" : "asocial",
"необщительный" : "unsociable reserved",
"необъяснимый" : "inexplicable",
"необъятный" : "immense",
"необыкновенный" : "unusual uncommon",
"необычный" : "unusual uncommon",
"необязательный" : "dispensable, facultative, optional",
"неограниченный" : "absolute, illimitable, indefinite",
"неодим" : "neodymium",
"неоднородность" : "heterogeneity",
"неодушевленный" : "inanimate",
"неожиданно" : "unawares",
"неолитический" : "neolithic",
"неологизм" : "neologism, neology",
"неоновый" : "neon...",
"неописуемый" : "indescribable",
"неоплаченный" : "unpaid unsettled",
"неоплачиваемый" : "honorary",
"неоправданный" : "unjustified",
"неопределенный" : "indefinite  uncertain vague, gr. infinitive",
"неопределимый" : "indefinable, indeterminable",
"неопровержимый" : "irrefutable",
"неопрятный" : "unclean, unkempt, untidy",
"неопытность" : "inexperience",
"неопытный" : "inexperienced",
"неорганический" : "inorganic",
"неослабный" : "unremitting unabated",
"неосмотрительный" : "imprudent",
"неосновательный" : "unfounded baseless",
"неоспоримый" : "incontestable",
"неосторожный" : "careless incautious, imprudent",
"неосуществимый" : "impracticable",
"неосязаемый" : "intangible",
"неотвратимый" : "unavoidable, fatal",
"неотвязный" : "obtrusive importunate",
"неотвязчивый" : "obtrusive importunate",
"неотесанный" : "unhewn, famil. rude",
"неоткуда" : "s. негде",
"неотложный" : "pressing urgent",
"неотлучный" : "& постоянный",
"неотразимый" : "irresistible",
"неотступный" : "persistent, importunate",
"неотчетливый" : "indistinct",
"неотъемлемый" : "inalienable, indefeasible",
"неотьемлемый" : "integral, inalienable",
"неофициальный" : "informal, unofficial",
"неохота" : "listlessness, reluctance, неохота famil. I am not in the mood",
"неохотно" : "unwillingly",
"неоценимый" : "invaluable",
"неочищенный" : "impure",
"неощутимый" : "imponderable, inappreciable",
"непал" : "nepal",
"непентес" : "nepenthe",
"неперелетный" : "resident",
"непереходный" : "intransitive",
"неплавкий" : "infusible",
"неплатеж" : "nonpayment",
"неплатежеспособный" : "insolvent",
"неплодородный" : "infertile",
"неплотный" : "loose",
"непобедимый" : "invincible",
"неповиновение" : "contumacy, defiance",
"неповинующийся" : "insubordinate",
"неповоротливый" : "clumsy slow",
"непогода" : "foul weather",
"непогрешимый" : "infallible",
"неподалеку" : "not far",
"неподатливый" : "unyielding refractory",
"неподвижный" : "motionless fixed, sluggish",
"неподдельный" : "genuine true, sincere",
"неподкупность" : "probity",
"неподкупный" : "incorruptible",
"неподобающий" : "improper unbecoming, undue",
"неподражаемый" : "inimitable",
"неподходящий" : "unsuitable",
"неподчинение" : "insubordination",
"непозволительный" : "improper unbecoming",
"непоколебимый" : "firm steadfast, unflinching, imperturbable",
"непокорный" : "intractable",
"неполадка" : "defect trouble, strife",
"неполитичный" : "impolitic",
"неполный" : "incomplete, short",
"непомерный" : "excessive exorbitant",
"непонимание" : "incomprehension",
"непонятливый" : "slow-witted",
"непонятный" : "unintelligible incomprehensible, strange odd",
"непоправимый" : "irreparable",
"непорочный" : "chaste immaculate, virgin...",
"непорядочный" : "dishonorable disreputable",
"непоседливый" : "fidgety",
"непосильный" : "beyond one's strength",
"непоследовательный" : "inconsistent",
"непослушный" : "disobedient",
"непосредственный" : "immediate direct, spontaneous",
"непостижимый" : "inconceivable",
"непостоянный" : "inconstant unsteady fickle",
"непохожий" : "unlike different",
"непочтительный" : "disrespectful, irreverent",
"неправда" : "untruth lie, not true, ... и неправдами or by crook",
"неправдоподобный" : "improbable",
"неправедный" : "unjust, sinful",
"неправильный" : "incorrect wrong, irregular, improper",
"неправоспособность" : "incapacity",
"неправота" : "wrong",
"неправый" : "wrong, unjust",
"непрактичный" : "impractical",
"непревзойденный" : "unsurpassed",
"непредвиденный" : "unforeseen",
"непредубежденный" : "unbiased",
"непредусмотрительность" : "hindsight"
};
