var dicctr_4 = {
"бирманка" : "Burmese",
"бирманский" : "Burmese",
"бирюза" : "turquoise",
"бирючина" : "privet",
"бис" : "encore!",
"бисер" : "pl.",
"бисквит" : "sponge cake",
"битва" : "battle",
"битком набитый" : "famil. crammed full",
"битник" : "beatnik",
"биток" : "meat ball",
"битумный" : "bituminous",
"битый" : "beaten",
"битый час" : "one solid hour",
"бить" : "побить beat, churn, пробить strike, разбить break smash, убить shoot kill, trump, #no pf. spout; See also: бить в глаза, бить в набат, бить тревогу, бить отбой, пробил его час",
"бить баклуши" : "famil. idle dawdle fool",
"бить в глаза" : "strike the eye",
"бить в ладоши" : "clap",
"бить в набат" : "sound the alarm",
"бить ключом" : "bubble, boil over, sparkle, abound in vitality",
"бить мимо" : "miss",
"бить отбой" : "the retreat",
"бить тревогу" : "sound the alarm",
"биться" : "fight, beat, drudge toil, биться головой о стену, dash against the rock, биться об заклад bet, он бьется как рыба об лед, he exerts himself in vain",
"бифштекс" : "steak",
"бицепс" : "biceps",
"бич" : "whip, fig. scourge",
"бичевать" : "lash scourge",
"благо" : "boon",
"благовидный" : "attractive, fig. seemly",
"благоволение" : "benevolence goodwill",
"благоволить" : "wish well be kind, deign",
"благовоние" : "fragrance",
"благовонный" : "fragrant",
"благовоспитанный" : "well-bred",
"благоговейный" : "devout reverent respectful",
"благоговение" : "awe  reverence respect",
"благоговеть" : "worship venerate",
"благодарение" : "thanksgiving",
"благодарить" : "thank",
"благодарность" : "gratitude, thanks; See also: не стоит благодарности",
"благодарный" : "grateful thankful",
"благодарственный" : "testimonial",
"благодаря" : "thanks #or owing to",
"благодатный" : "blessed",
"благодать" : "blessing",
"благодетель" : "benefactor",
"благодетельница" : "benefactress",
"благодетельный" : "beneficent, beneficial",
"благодеяние" : "benefit",
"благодушие" : "good nature kindness",
"благодушный" : "kindhearted benign",
"благожелательность" : "benevolence",
"благожелательный" : "benevolent",
"благозвучие" : "euphony sonority",
"благозвучность" : "euphony sonority",
"благозвучный" : "sonorous harmonious",
"благонадежный" : "reliable trustworthy",
"благонамеренный" : "well-meaning well-meant",
"благонравный" : "well-mannered modest",
"благообразный" : "attractive comely sightly",
"благополучие" : "well-being prosperity happiness",
"благополучный" : "happy, safe",
"благоприятный" : "favorable propitious",
"благоприятствовать" : "favor promote",
"благоразумие" : "prudence discretion",
"благоразумный" : "prudent judicious",
"благородный" : "noble, high-minded distinguished, lofty, precious",
"благородство" : "nobility",
"благосклонность" : "grace",
"благосклонный" : "favorable well-disposed ] a Д)",
"благословение" : "benediction blessing",
"благословить" : "bless",
"благословлять" : "bless",
"благосостояние" : "prosperity",
"благотворительный" : "beneficent charitable",
"благотворный" : "wholesome salutary",
"благоустроенный" : "well-furnished comfortable",
"благоухание" : "fragrance odor",
"благоухать" : "scent exhale fragrance",
"благоухающий" : "odoriferous, odorous",
"благочестивый" : "pious",
"благочестие" : "piety",
"блаженный" : "blissful",
"блаженство" : "bliss",
"блаженствовать" : "enjoy felicity",
"блажить" : "be capricious cranky",
"блажной" : "capricious, preposterous",
"блажь" : "caprice whim freak fancy, folly",
"бланк" : "form, letterhead",
"блат" : "profitable connections, по блату on the quiet illicitly through good connections",
"блатной" : "trickster rogue",
"блатной язык" : "thieves' slang cant",
"блевать" : "spue",
"бледнеть" : "turn pale",
"бледноватый" : "palish",
"бледно-желтый" : "jonquil, primrose",
"бледнолицый" : "with a pale face",
"бледность" : "pallor",
"бледный" : "pale",
"блеклый" : "faded withered",
"блекнуть" : "fade wither",
"блеск" : "luster shine brilliance glitter splendor",
"блесна" : "troll",
"блеснуть" : "shine glitter, flash, не все то золото что блестит all is not gold that glitters",
"блестеть" : "shine glitter, flash, не все то золото что блестит all is not gold that glitters",
"блестка" : "paillette, spangle",
"блестки" : "spangle",
"блестящий" : "brilliant",
"блеф" : "bluff",
"блеяние" : "bleat",
"блеять" : "bleat",
"ближайший" : "the nearest next",
"ближе" : "nearer",
"ближний" : "near, su. fellow creature",
"ближний восток" : "the Near East",
"близ" : "near close",
"близиться" : "approach",
"близкие" : "pl. folk one's family relatives",
"близкий" : "near close",
"близко" : "closely, earshot, hard by",
"близко от" : "close to not far from",
"близлежащий" : "nearby neighboring",
"близнец" : "twin",
"близорукий" : "short-sighted",
"близорукость" : "myopia, nearsight, shortsight",
"близость" : "nearness proximity, intimacy",
"блин" : "pancake",
"блистательный" : "brilliant splendid magnificent",
"блистать" : "shine beam",
"блок" : "bloc coalition, pulley",
"блокада" : "blockade",
"блокировать" : "pf. blockade block up",
"блокировка" : "blockage, blocking",
"блокнот" : "notebook",
"блок-схема" : "flowchart",
"блокшив" : "hulk",
"блондин" : "blond",
"блондинка" : "blonde",
"блоха" : "flea",
"блоховник" : "pennyroyal",
"блуд" : "licentiousness",
"блудить" : "roam wander, debauch",
"блудливый" : "wanton",
"блудница" : "whore",
"блудный" : "wanton",
"блудный сын" : "prodigal son",
"блуждать" : "roam wander",
"блуждающая почка" : "floating kidney",
"блуждающий" : "migratory, wandering",
"блуждающий огонек" : "will-o'-the-wisp",
"блуза" : "blouse smock",
"блузка" : "blouse",
"блюдечко" : "saucer",
"блюдо" : "dish, course",
"блюдце" : "saucer",
"блюсти" : "observe preserve maintain, watch",
"блюститель" : "keeper guardian",
"блюстительница" : "keeper guardian",
"бляха" : "metal plate badge",
"боа" : "zo. boa, boa",
"боб" : "bean, haricot, остаться на бобах have one's trouble for nothing",
"бобер" : "beaver",
"бобина" : "bobbin spool reel",
"бобовый" : "бобовые растения legumes",
"бобр" : "beaver, castor",
"бог" : "god",
"богатство" : "fleshpots, riches, wealth",
"богатый" : "moneyed, pinguid, rich",
"богатырь" : "hero, athlete",
"богач" : "rich man",
"богема" : "bohemia",
"богемия" : "Bohemia",
"богемский" : "Bohemian",
"богиня" : "goddess",
"богоматерь" : "the Blessed Virgin",
"богомол" : "mantis",
"богомолец" : "devotee, pilgrim",
"богомолка" : "devotee, pilgrim",
"богомолье" : "prayer, pilgrimage",
"богомольный" : "prayerful",
"богоотступник" : "atheist",
"богоподобный" : "godlike",
"богородица" : "the Blessed Virgin Our Lady",
"богослов" : "theologian",
"богословие" : "theology divinity",
"богословский" : "theological",
"богослужение" : "divine service",
"боготворить" : "adore deify",
"богохульник" : "blasphemer",
"богохульничать" : "blaspheme",
"богохульный" : "blasphemous",
"богохульство" : "blasphemy",
"богохульствовать" : "= богохульничать",
"богоявление" : "epiphany",
"бод" : "baud",
"бодать" : "butt gore",
"боднуть" : "butt gore",
"бодрость" : "vivacity sprightliness",
"бодрствовать" : "be awake",
"бодрствующий" : "wakeful, waking",
"бодрый" : "awake, sprightly vivacious brisk, vigorous",
"боевик" : "hit draw",
"боевое крещение" : "baptism of fire",
"боевой" : "battle... fighting war... military, live, pugnacious militant; See also: боевой парень, боевой порядок",
"боевой парень" : "dashing fellow",
"боевой порядок" : "battle array",
"боеприпасы" : "ammunition",
"боеспособный" : "effective",
"боец" : "soldier fighter",
"боже" : "oh God! good gracious!",
"божественность" : "deity, godhead",
"божественный" : "celestial, divine, heavenly",
"бой" : "combat",
"бойкий" : "glib, perky",
"бойкот" : "boycott",
"бойница" : "loophole",
"бойня" : "shambles, slaughterhouse",
"бокал" : "snifter, wineglass",
"боковой" : "lateral",
"боком" : "sideways",
"бокс" : "boxing",
"боксер" : "boxer",
"боксер-левша" : "southpaw",
"боксировать" : "box",
"боксит" : "bauxite",
"болван" : "dolt blockhead",
"болгарин" : "Bulgarian",
"болгария" : "Bulgaria",
"болгарка" : "Bulgarian",
"болгарский" : "Bulgarian",
"более" : "more, ~ высокий higher; See also: более или менее, не более",
"более или менее" : "more or less",
"болезненный" : "sickly ailing morbid, painful",
"болезнетворный" : "pathogenetic, pathogenic",
"болезнь" : "sickness  illness, disease, disorder, sick",
"болельщик" : "#sport: fan",
"болеть" : "be sick ill, be anxious  apprehensive, hurt ache, у меня болит голова, I have a headache",
"болеутоляющий" : "analgesic, anodyne, paregoric",
"боливия" : "bolivia",
"болотистый" : "boggy swampy",
"болотный" : "bog... swamp...",
"болото" : "bog swamp",
"болт" : "bolt",
"болтать" : "взболтать shake up, dangle, famil. поболтать chat, -ся famil. loaf #or lounge about",
"болтливый" : "talkative",
"болтовня" : "idle talk gossip",
"болтун" : "babbler chatterbox",
"болтунья" : "babbler chatterbox",
"боль" : "pain ache"
};
