var dicctr_57 = {
"пачкать" : "soil",
"паша" : "bashaw, pacha, pasha",
"пашня" : "tillage field",
"паштет" : "pie",
"паяльник" : "soldering iron",
"паясничать" : "play the fool",
"паять" : "solder",
"паяц" : "buffoon merry-andrew",
"пво" : "= противовоздушная оборона",
"певец" : "singer",
"певица" : "singer",
"певучий" : "melodious",
"певчий" : "singing, su. chorister choirboy",
"певчий-солист" : "cantor",
"пегас" : "pegasus",
"пегий" : "piebald",
"пегматит" : "pegmatite",
"педагог" : "pedagogue teacher",
"педагогика" : "pedagogics",
"педагогический" : "pedagogic",
"педагогичный" : "pedagogic",
"педаль" : "treadle pedal",
"педант" : "pedant",
"педантизм" : "pedantry",
"педантичный" : "pedantic",
"педиатр" : "pediatrician, pediatrist",
"пейзаж" : "landscape",
"пекари" : "peccary",
"пекарня" : "bakery",
"пекарь" : "baker",
"пекин" : "peking",
"пелена" : "shroud",
"пеленать" : "swaddle",
"пеленка" : "swaddling band  diaper a. napkin",
"пеликан" : "pelican",
"пеллагра" : "pellagra",
"пельмени" : "ravioli",
"пемзовый" : "pumice",
"пена" : "foam froth, lather",
"пенал" : "pen case",
"пенелопа" : "penelope",
"пение" : "singing, crow",
"пенис" : "penis",
"пенистый" : "foamy frothy",
"пениться" : "foam froth, sparkle mantle",
"пенициллин" : "penicillin",
"пенка" : "scum, froth",
"пенни" : "pence, penny",
"пенсия" : "pension",
"пенсне" : "pince-nez eyeglasses pl.",
"пентагон" : "pentagon",
"пентаграмма" : "pentagram",
"пентан" : "pentane",
"пень" : "stump, blockhead",
"пенька" : "hemp",
"пеньковый" : "hemp",
"пеня" : "fine",
"пенять" : "blame",
"пенящийся" : "bubbly, foamy",
"пепел" : "ashes pl.",
"пепелище" : "the ashes, a. пожарище",
"пепельница" : "ash tray",
"пепельный" : "ashy",
"первейший" : "the very first, first-rate, cf. пятый",
"первенец" : "first-born",
"первенство" : "primogeniture, superiority, championship",
"первичный" : "primary",
"первобытный" : "primitive primeval",
"первоисточник" : "source origin",
"первоклассный" : "first-rate #or -class",
"первокурсник" : "freshman",
"первому попавшемуся" : "to the first comer",
"перво-наперво" : "popul. first of all",
"первоначальный" : "original, primary",
"первообраз" : "prototype",
"первоосновы" : "elements",
"первоочередной" : "top-priority",
"первосортный" : "= первоклассный",
"первостепенный" : "paramount supreme",
"первый" : "first, chief main, Brt. ground, thea. dress, первое first course, первым делом #or в первую очередь, first of all first thing",
"первый встречный" : "the first comer",
"первый план" : "foreground",
"пергамент" : "parchment",
"перебегать" : "run over, desert",
"перебежать" : "run over, desert",
"перебежчик" : "deserter, turncoat",
"перебивать" : "interrupt, break, kill, -ся break, famil. rough it",
"перебирать" : "look a th. over, sort, mus. finger, tell, -ся move, cross",
"перебить" : "interrupt, break, kill, -ся break, famil. rough it",
"перебой" : "stoppage break, irregularity",
"перебороть" : "pf. overcome master",
"перебранка" : "wrangle",
"перебрасывать" : "throw over, commerc. transfer shift, lay, -ся exchange",
"перебрать" : "look a th. over, sort, mus. finger, tell, -ся move, cross",
"перебросить" : "throw over, commerc. transfer shift, lay, -ся exchange",
"переброска" : "transference",
"перевал" : "pass",
"переваливать" : "tumble turn, famil. pass, impers. перевалило за is past...",
"перевалить" : "tumble turn, famil. pass, impers. перевалило за is past...",
"переварить" : "digest",
"перевезти" : "s. перевозить",
"перевернуть" : "turn over, overturn, turn",
"перевертывать" : "turn over, overturn, turn",
"перевес" : "preponderance",
"перевесить" : "hang, reweigh, outweigh, -ся hang #or bend over",
"перевести" : "s. переводить",
"перевешивать" : "outbalance, preponderate",
"перевешивающий" : "preponderant",
"перевод" : "remittance, rendering, rending, rendition",
"переводить" : "translate",
"переводчица" : "translator, interpreter",
"перевоз" : "ferriage ferry, a. = перевозка",
"перевозить" : "transport convey, remove, ferry",
"перевозка" : "transport conveyance",
"перевозчик" : "ferryman",
"перевооружение" : "rearmament",
"переворачивать" : "= перевертывать",
"переворот" : "revolution",
"перевоспитание" : "reeducation",
"переврать" : "misquote distort",
"перевыборы" : "reelection",
"перевыполнение" : "overfulfilment",
"перевыполнить" : "exceed surpass",
"перевыполнять" : "exceed surpass",
"перевязать" : "tie up, dress bandage",
"перевязка" : "dressing bandage",
"перевязочный" : "dressing",
"перевязывать" : "tie up, dress bandage",
"перегиб" : "bend fold, dog-ear",
"перегибать" : "bend, -ся lean over",
"переглядываться" : "exchange glances",
"переглянуться" : "exchange glances",
"перегнать" : "s. перегонять",
"перегной" : "humus",
"перегнуть" : "bend, -ся lean over",
"переговаривать" : "talk over  discuss",
"переговорить" : "talk over  discuss",
"переговоры" : "negotiations, milit. parley",
"перегонка" : "distillation",
"перегонять" : "distance outstrip, surpass outdo, chem. distil",
"перегораживать" : "partition",
"перегорать" : "burn out, blow",
"перегореть" : "burn out, blow",
"перегородить" : "partition",
"перегородка" : "partition",
"перегревать" : "overheat",
"перегреть" : "overheat",
"перегружать" : "overload, overwork",
"перегрузить" : "overload, overwork",
"перегрузка" : "overload, overwork",
"перегруппировать" : "pf. regroup",
"перегруппировка" : "regrouping",
"перегрызать" : "gnaw through",
"перегрызть" : "gnaw through",
"перед" : "before",
"перед1" : "before in front of",
"перед2" : "front",
"передавать" : "pass hand  deliver, give, broadcast, transmit, reproduce, render, tell, take a message, commerc. endorse, -ся med. be communicated",
"передаточный" : "transmissive",
"передатчик" : "transmitter",
"передать" : "pass hand  deliver, give, broadcast, transmit, reproduce, render, tell, take a message, commerc. endorse, -ся med. be communicated",
"передача" : "delivery handing over, transfer, broadcast transmission, gear, med. communication, reproduction, package",
"передающийся" : "transmissible",
"передвигать" : "move shift",
"передвижение" : "movement, transportation",
"передвижка" : "traveling mobile itinerant",
"передвижной" : "traveling mobile itinerant",
"передвинуть" : "move shift",
"передел" : "repartition",
"переделать" : "recast, make over alter",
"переделка" : "alteration, recast, famil. mess",
"переделывать" : "recast, make over alter",
"передний" : "front... fore...",
"передний план" : "foreground",
"передник" : "apron",
"передняя" : "hall antechamber",
"передо" : "before in front of",
"передовик" : "best worker #or farmer",
"передовица" : "leading article editorial",
"передовой" : "progressive, leading foremost, front",
"передовой отряд" : "vanguard",
"передок" : "front, milit. limber",
"передохнуть" : "pf. take breath #or rest",
"передразнивать" : "mimic",
"передразнить" : "mimic",
"передряга" : "fix scrape",
"передумать" : "change one's mind, s. обдумать",
"передумывать" : "change one's mind, s. обдумать",
"передышка" : "respite",
"переезд" : "passage, crossing, move removal",
"переезжать" : "cross, move, run over",
"переехать" : "cross, move, run over",
"переждать" : "s. пережидать",
"пережевать" : "chew famil. repeat over and over again",
"пережевывать" : "chew famil. repeat over and over again",
"переживание" : "experience",
"переживать" : "experience, go through endure, survive outlive",
"пережидать" : "wait",
"пережиток" : "survival",
"пережить" : "experience, go through endure, survive outlive",
"перезимовать" : "winter, hibernate",
"перезрелый" : "overripe",
"переизбирать" : "reelect",
"переизбрание" : "reelection",
"переизбрать" : "reelect",
"переиздавать" : "republish",
"переиздание" : "reedition",
"переиздать" : "republish",
"переименовать" : "pf. rename",
"переиначивать" : "alter modify, distort",
"переиначить" : "alter modify, distort",
"перейти" : "s. переходить",
"перекидывать" : "throw over, upset, -ся exchange",
"перекинуть" : "throw over, upset, -ся exchange",
"перекипать" : "boil over",
"перекипеть" : "boil over",
"перекись" : "peroxide",
"перекладина" : "crossbar crossbeam",
"перекладывать" : "put lay #or pack  shift, interlay, cf. перелагать",
"перекликаться" : "shout to o.a., reecho",
"перекликнуться" : "shout to o.a., reecho",
"перекличка" : "roll call",
"переключать" : "switch over",
"переключение" : "switching over",
"переключить" : "switch over",
"перековать" : "pf. shoe over again, fig. reeducate remake",
"перекошенный" : "wry",
"перекраивать" : "cut again, remake",
"перекрестить" : "cross",
"перекрестный" : "cross",
"перекресток" : "crossroad",
"перекрещенный" : "contralateral",
"перекрещивающийся" : "crisscross",
"перекроить" : "cut again, remake",
"перекрывать" : "cover, exceed surpass",
"перекрытие" : "covering",
"перекрыть" : "cover, exceed surpass",
"перекусить" : "bite through, famil. take a bite",
"перекусывать" : "bite through, famil. take a bite",
"перелагать" : "transpose, arrange",
"переламывать" : "переломить break in two, overcome, переломать break to pieces",
"перелезать" : "climb over",
"перелезть" : "climb over",
"перелет" : "passage, av. flight",
"перелетать" : "fly, pass migrate, flit",
"перелететь" : "fly, pass migrate, flit",
"перелетный" : "of passage",
"перелив" : "mus. run roulade, play",
"переливание" : "transfusion",
"переливать" : "decant pour, med. transfuse, переливать из пустого в порожнее, mill the wind, -ся overflow, mus. warble roll, play shimmer"
};
