var dicctr_77 = {
"родоначальник" : "ancestor father",
"родонит" : "rhodonite",
"родословная" : "family tree",
"родословный" : "genealogical",
"родственник" : "relative relation",
"родственники" : "innards, kinsfolk",
"родственница" : "relative relation",
"родственность" : "affinity",
"родственный" : "related kindred cognate, of blood",
"родство" : "relationship, cognation, famil. relatives, в родстве related",
"роды" : "birth",
"рожа" : "med. erysipelas, popul. mug",
"рожать" : "bear give birth to, beget, fig. bring forth produce",
"рождаемость" : "birth rate",
"рождать" : "bear give birth to, beget, fig. bring forth produce",
"рождение" : "birth, день рождения birthday",
"рождественская елка" : "Christmas tree #or, party",
"рождественский" : "Christmas...",
"рождество" : "Christmas, поздравить с Рождеством Христовым wish a Merry Xmas, до Р.Хр. B.C.",
"рожок" : "dim. #of рог, ear trumpet, feeding bottle, burner, shoehorn",
"рожь" : "rye",
"роза" : "rose",
"розарий" : "rosary",
"розга" : "rod",
"розетка" : "rosette, el. socket",
"розмарин" : "rosemary",
"розница" : "в розницу",
"розничный" : "retail",
"розовато-лиловый" : "mauve",
"розоватый" : "pinkish, pinky",
"розовый" : "pink, roseate, rosy",
"роковой" : "basilisk, fatal, fateful",
"роланд" : "roland",
"ролик" : "roll, roller",
"роль" : "role",
"ром" : "rum",
"роман" : "novel, famil. affair romance",
"романист" : "novelist",
"романский" : "romance, romanesque, romanic",
"романтизм" : "romanticism",
"романтический" : "romantic",
"романтичный" : "romantic",
"ромашка" : "camomile",
"ромб" : "rhombus",
"ромбический" : "rhombic",
"рондо" : "rondeau, rondel, rondo, roundel",
"ронять" : "drop, droop, lose, shed, fig. disparage discredit",
"ропот" : "murmur grumble growl",
"роптать" : "murmur grumble growl",
"роса" : "dew",
"росистый" : "dewy",
"роскошный" : "luxurious, magnificent splendid sumptuous, famil. luxuriant exuberant",
"роскошь" : "luxury, magnificence sumptuousness, luxuriance",
"рослый" : "big tall",
"роспись" : "list, fresco",
"роспуск" : "dissolution, dismissal, disbandment, breaking up",
"российский" : "russian, cf. РСФСР",
"россия" : "Russia",
"рост" : "growth, increase, stature size, ... высокого роста tall ...",
"ростовщик" : "usurer",
"ростовщический" : "usurious",
"ростовщичество" : "gombeen, usury",
"росток" : "sprout shoot",
"росчерк" : "flourish, stroke",
"росянка" : "sundew",
"рот" : "mouth",
"рота" : "company",
"ротный" : "company",
"ротовой" : "oral",
"ротогравюра" : "rotogravure",
"ротозей" : "gaper",
"ротонда" : "rotunda",
"роща" : "grove",
"рояль" : "piano",
"рсфср" : ", Russian Soviet Federative Socialist Republic",
"ртутный" : "mercurial",
"ртуть" : "mercury",
"рубанок" : "plane",
"рубашка" : "shirt, chemise",
"рубеж" : "boundary, border  frontier; See also: за рубежом",
"рубец" : "hem, scar wake",
"рубидий" : "rubidium",
"рубин" : "ruby",
"рубить" : "нарубить chop cut hew hack, mince, срубить fell, impf. speak bluntly",
"рубиться" : "fight",
"рубка" : "felling, nav. cabin",
"рубленый" : "chopped minced",
"рубль" : "ruble",
"рубрика" : "heading, column",
"рубчатый" : "ribbed",
"ругань" : "abuse",
"ругательный" : "abusive",
"ругательство" : "curse oath",
"ругать" : "abuse scold",
"ругаться" : "swear curse, abuse o.a.",
"руда" : "ore",
"рудимент" : "rudiment, vestigium",
"рудиментарный" : "rudimentary",
"рудник" : "mine pit",
"рудничный" : "mine, fire",
"рудный" : "ore",
"рудокоп" : "miner",
"рудоносный" : "metalliferous",
"ружейный" : "gun...",
"ружье" : "gun rifle",
"рука" : "hand, arm, рука в руку hand in hand, из рук вон famil. quite wretched, быть на руку suit a pers., на руку нечист light-fingered, от руки in handwriting, по рукам! it's bargain!, под рукой at hand within reach, рукой подать it's no distance, руки коротки famil. it's not in power, из первых рук at first hand, приложить руку sign",
"рукав" : "sleeve, branch, hose",
"рукавица" : "mitten, gauntlet",
"рукавчик" : "cuff",
"руки вверх" : "hands up!",
"руководитель" : "instructor",
"руководить" : "fugle, manage",
"руководиться" : "follow conform",
"руководство" : "leadership, guidance, instruction, textbook guide",
"руководствовать" : "s. руководить",
"рукописный" : "manuscript",
"рукопожатие" : "handshake",
"рукоятка" : "haft, hilt, manubrium, stele",
"рулевой" : "cox, coxswain, helmsman, steersman, wheelsman",
"рулетка" : "reel, roulette, tapeline",
"руль" : "rudder",
"румб" : "rhumb",
"румын" : "Rumanian",
"румынка" : "Rumanian",
"румынский" : "Rumanian",
"румяна" : "rouge",
"румянец" : "ruddiness, blush",
"румянить" : "зарумянить redden, нарумянить rouge",
"румяный" : "ruddy rosy, red scarlet",
"руна" : "rune",
"руно" : "fleece",
"рупия" : "rupee, rupia",
"рупор" : "megaphone, mouthpiece",
"русалка" : "mermaid",
"русло" : "bed channel",
"русский" : "Russian, adv. по-русски Russian",
"русый" : "fair blond",
"русь" : "poet. Russia",
"рутений" : "ruthenium",
"рутина" : "routine",
"рутинный" : "routine",
"рухлядь" : "lumber stuff",
"рухнуть" : "pf. crash down, fail",
"ручательство" : "guarantee",
"ручаться" : "warrant guarantee vouch for",
"ручеек" : "brooklet, rill, streamlet",
"ручей" : "brook stream",
"ручка" : "hand, handle knob, #chair arm, lever, pen",
"ручной" : "hand..., manual, handmade, small, a. light, tame, wrist",
"рушить" : "pf. collapse break down",
"рыба" : "fish",
"рыбак" : "fisher, fisherman",
"рыболовство" : "fishery",
"рыгать" : "burp",
"рыдать" : "sob",
"рыжевато-коричневый" : "tawny",
"рыжеволосый" : "redhead",
"рынок" : "market",
"рыночный" : "market...",
"рысак" : "trotter",
"рыскание" : "yaw, yawing",
"рыскать" : "rove run about",
"рысь" : "trot, zo. lynx",
"рытвина" : "rut groove hole",
"рыть" : "dig, burrow mine",
"рыться" : "rummage",
"рыхлить" : "loosen",
"рыхлый" : "friable crumbly loose",
"рыцарский" : "knightly chivalrous, knight's",
"рыцарство" : "chivalry, knighthood",
"рыцарь" : "knight",
"рыча ть" : "growl",
"рычаг" : "lever",
"рычание" : "growl, snarl",
"рьяный" : "zealous, mettlesome",
"рюмка" : "glass",
"рябина" : "mountain ash, famil. pit",
"рябить" : "ripple, mottle, impers. flicker",
"рябой" : "pockmarked, piebald spotted, freckled",
"рябчик" : "hazel grouse",
"рябь" : "ripples pl., flicker",
"рявкать" : "bellow bawl, snap",
"рявкнуть" : "bellow bawl, snap",
"ряд" : "row, line, file, series, number several, pl. ranks, a. tier; See also: рядами, из ряда вон выходящий",
"рядами" : "in rows",
"рядовой" : "ordinary, milit. private",
"рядом" : "side by side, beside next to, next door, close by",
"ряженый" : "disguised masked, masker",
"ряса" : "cassock",
"с" : "abbr.: село",
"с места в карьер" : "on the spot",
"с натуры" : "from nature #or life",
"с одной стороны" : "on the one hand",
"с первого взгляда" : "on the face of it, at once",
"с поличным" : "red-handed",
"с роду" : "in one's life",
"с тех пор" : "since then",
"с тех пор как" : "since",
"с часу на час" : "hourly",
"с чего" : "famil. why? wherefore?",
"саам" : "lapp",
"сабля" : "sabre",
"саботировать" : "sabotage, shirk",
"саван" : "shroud",
"савояр" : "savoyard",
"саврасый" : "roan",
"сага" : "saga",
"сагиб" : "sahib",
"сагитировать" : "agitate",
"саго" : "sago",
"сад" : "garden",
"садизм" : "sadism",
"садить" : "s. сажать",
"садиться" : "sit down, get in #or on board, rail. entrain, mount, alight, av. land, set, settle, sink, shrink, set, run",
"садовник" : "gardener",
"садоводство" : "gardening horticulture",
"садовый" : "garden",
"садок" : "vivarium",
"сажа" : "soot, в саже sooty",
"сажать" : "seat, put, plant, rail. entrain",
"сажень" : "#Russ. fathom",
"сайда" : "pollack, pollock",
"саквояж" : "traveling bag",
"саксония" : "saxony",
"саксонский" : "saxon",
"саксофон" : "saxophone",
"сакэ" : "sake",
"салазки" : "sled",
"саламандра" : "salamander",
"салат" : "salad, lettuce",
"салат-латук" : "lettuce",
"сало" : "bacon, suet tallow",
"салон" : "salon",
"салфетка" : "napkin",
"сальдо" : "commerc. balance",
"сальный" : "greasy, obscene",
"салют" : "pf. salute",
"салютовать" : "pf. salute",
"сам" : "-self: я сам I ... myself, мы сами we ... ourselves",
"сама" : "-self: я сам I ... myself, мы сами we ... ourselves",
"самарий" : "samarium",
"самец" : "zo. male",
"сами" : "-self: я сам I ... myself, мы сами we ... ourselves",
"самка" : "zo. female",
"само" : "-self: я сам I ... myself, мы сами we ... ourselves",
"самобытный" : "original",
"самовар" : "samovar",
"самовластный" : "autocratic",
"самовлюбленность" : "egomania, narcissism",
"самовлюбленный" : "bighead"
};
